### ISSUE TITLE
Chart is invisble

### ISSUE THREAD

**Issue by nseb** [amcharts/amcharts5#1]
I'm trying migrate amchart4 to amchart5 , my data it's present in the chart, but invisible , colors problems ?

![image](https://user-images.githubusercontent.com/6363226/131250406-be6a5618-eb7d-4937-8fea-95a2b24d7285.png)

the code  , I use Quasar (Vue3) , amchartv4 is always present in project to keep the old charts

  import * as am5 from '@amcharts/amcharts5'
  import * as am5xy from '@amcharts/amcharts5/xy'
  
  ... 

  createChart() {
      // eslint-disable-next-line @typescript-eslint/no-this-alias
      var self = this
      // Create chart instance
     let root = am5.Root.new('linechartdiv');
  
      root.setThemes([
        am5themes_Animated.new(root)
      ]);

    let chart = root.container.children.push(
      am5xy.XYChart.new(root, {
        panX: true,
        wheelable : false,
        wheelX : 'none',
        wheelY : 'none'
      })
    )
    // Add data
    const data = self.resultData.results
      ? self.resultData.results.map(item => ({label: ` (${item.identifier})`, value: item.value})) : []

    // Create axes
    let xAxis = chart.xAxes.push(
      am5xy.ValueAxis.new(root, {
        renderer: am5xy.AxisRendererX.new(root, {
          strokeOpacity: 1,
          strokeWidth: 2,
          fill: am5.color(0x095256),
        })
      })
    );

    let valueAxis = chart.yAxes.push(
      am5xy.ValueAxis.new(root, {
        renderer: am5xy.AxisRendererY.new(root, {})
      })
    );

    // Create series
    let series = chart.series.push(
      am5xy.SmoothedXLineSeries.new(root, {
        name : 'Resutls',
        valueYField: 'value',
        valueXField: 'label',
        xAxis : xAxis,
        yAxis : valueAxis,
        fill: am5.color(0x095256),
        stroke: am5.color(0x095256)
      }));
    series.strokes.template.setAll({
      strokeWidth: 2
    });
    series.fills.template.setAll({visible:true, fillOpacity:0.2})

    console.table(data);

    const cursor = chart.set("cursor", am5xy.XYCursor.new(root, { behavior: "zoomX" }));
    cursor.lineY.set("visible", false);

    chart.set("scrollbarX", am5.Scrollbar.new(root, {
      orientation: "horizontal"
    }));

    let scrollbarX = am5xy.XYChartScrollbar.new(root, {
      orientation: "horizontal",
      height: 50,
    });

    chart.set("scrollbarX", scrollbarX)

    series.data.setAll(data);

    series.appear();
    chart.appear();

    self.skeleton = false;
    self.chart = chart;
  }
}

**Comment by martynasma** [comment]
The code looks good at first glance. Can you also post your data?

**Comment by nseb** [comment]
Replace: 
valueXField: 'label' by   valueXField: 'date', try datas retrieve for your doc site : 
    series.data.pushAll([{
      date: new Date(2021, 0, 1).getTime(),
      value: 1000
    }, {
      date: new Date(2021, 0, 2).getTime(),
      value: 800
    }, {
      date: new Date(2021, 0, 4).getTime(),
      value: 800
    }, {
      date: new Date(2021, 0, 5).getTime(),
      value: 800
    }]);
    
    It's works  , but poor quality and no preview in zoom bar
    
    
![image](https://user-images.githubusercontent.com/6363226/131631399-de341988-d31e-4c4e-b9bc-71098a2e57b6.png)

**Comment by nseb** [comment]
@martynasma see the first code, I had configured scrollbar with preview.
New code , same issue: 


    let root = am5.Root.new('linechartdiv');

    root.setThemes([
      am5themes_Animated.new(root)
    ]);

    let chart = root.container.children.push(
      am5xy.XYChart.new(root, {
        panX: true,
        wheelable : false,
        wheelX : 'none',
        wheelY : 'none'
      })
    )
    // Add data
    const data = this.resultData.results
      ? this.resultData.results.map(item => ({label: ` (${item.identifier})`, value: item.value})) : []


    // Create axes
    let xAxis = chart.xAxes.push(
      am5xy.CategoryAxis.new(root, {
        categoryField: "label",
        renderer: am5xy.AxisRendererX.new(root, {})
      })
    );

    let valueAxis = chart.yAxes.push(
      am5xy.ValueAxis.new(root, {
        renderer: am5xy.AxisRendererY.new(root, {})
      })
    );

    // Create series
    let series = chart.series.push(
      am5xy.SmoothedXLineSeries.new(root, {
        name : 'Results',
        valueYField: 'value',
        categoryXField : 'label',
        xAxis : xAxis,
        yAxis : valueAxis
      }));
    series.strokes.template.setAll({
      strokeWidth: 2
    });

    console.table(data);


    const cursor = chart.set("cursor", am5xy.XYCursor.new(root, { behavior: "zoomX" }));
    cursor.lineY.set("visible", false);


    let scrollbarX = am5xy.XYChartScrollbar.new(root, {
      orientation: "horizontal",
      height: 50,
    });
    chart.set("scrollbarX", scrollbarX)

    series.data.setAll(data);

    series.appear();
    chart.appear();

**Comment by martynasma** [comment]
I don't see any series being added to the scrollbarX. You might've missed that part in docs:

https://www.amcharts.com/docs/v5/charts/xy-chart/scrollbars/#Scrollbar_with_chart_preview

**Comment by nseb** [comment]
@martynasma , I found the problem for the graph invisible in case CategoryAxis , we need add : xAxis.data.setAll(data);
for the probleme scrollbarX , you are right, I am making the modification

**Comment by nseb** [comment]
I have a test working ;-)
![image](https://user-images.githubusercontent.com/6363226/132255750-dac38021-ba66-4c1d-8cf4-ee028696a8c6.png)

We have small issues with horizontal preview, et the when I drag the button ,pointer mouse is staggered.
It's possible to set font-family in chart to to have a smoother rendering

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.

**Comment by sassomedia** [comment]
@martynasma Looks like the bot has some issues, there's a bunch of stale posts that it didn't close.
