### ISSUE TITLE
Legend is not visible if outside the container

### ISSUE THREAD

**Issue by sknhkrn** [amcharts/amcharts5#100]
Hi, for the line charts, if I have 30 series on the charts, some legend series is not accessible as it is not fit in the legend container. 

Here is the jsFiddle:
https://jsfiddle.net/xL72rzej/

Is there a way to see all the legend or probably add a scrollbar on the legend container? 
Thanks.

**Comment by martynasma** [comment]
You can enable scrolling for legend:
https://www.amcharts.com/docs/v5/concepts/legend/#Scrollable_legend

**Comment by sknhkrn** [comment]
Okay thank you. It works well now.
