### ISSUE TITLE
column series setting(fill, stroke) change doesn't reflect

### ISSUE THREAD

**Issue by Y-m1** [amcharts/amcharts5#1000]
**Question**
I tried to change column series color by color picker.
I use series fill and stroke change by set function but column color and legend marker color doesn't change.
It works in line series. why it doesn't works in column series?

**Comment by martynasma** [comment]
Can you provide more information or a link to your chart?

**Comment by Y-m1** [comment]
I mean, column series can't change their fill and stroke color and maybe legend marker also by events.

You can reproduce this one to insert below one to before last line
https://www.amcharts.com/demos/100-stacked-column-chart/ (with column doesn't work)
https://www.amcharts.com/demos/100-stacked-area-chart/ (with line work)

chart.plotContainer.events.on('click', () => {
chart.series.each((item) => {
  item.set("fill", am5.color('#000'));
            item.set("stroke", am5.color('#000'));
});
});

**Comment by martynasma** [comment]
Columns are created from column template, which is populated by series fill/stroke once - when series is created.

You can update column template instead:

```JavaScript
series.columns.template.set("fill", am5.color('#000'));
series.columns.template.set("stroke", am5.color('#000'));
```

**Comment by Y-m1** [comment]
I got it, thanks!
