### ISSUE TITLE
XY Chart: Is possible to define different colors per category?

### ISSUE THREAD

**Issue by rogeraraujo90** [amcharts/amcharts5#1001]
**Question**

I'm trying to render a category chart where each category must have a different color. Is that possible?

I've tried defining just one category with different series (screenshot) but when there are multiple series the columns are too thin. I know with one category per series we can zoom them, but having different colors per category is a requirement.

![image](https://github.com/amcharts/amcharts5/assets/6045678/83d48c7a-5ae5-4ab9-a7c2-b76242ecde8f)

**Environment (if applicable)**

- amCharts5
- EmberJS

**Additional context**

**Comment by martynasma** [comment]
You can bind column fill color to data using `templateField` for columns. [Docs](https://www.amcharts.com/docs/v5/concepts/settings/template-fields/).

Example: https://www.amcharts.com/demos/column-with-rotated-series/
