### ISSUE TITLE
XY Chart: Bullets on top of columns

### ISSUE THREAD

**Issue by rogeraraujo90** [amcharts/amcharts5#1002]
**Question**

I'm trying to render labels for each column in an XY Chart by using bullets as recommended [here](https://www.amcharts.com/docs/v5/tutorials/column-labels-as-categories/#Label_bullets)

In my chart, I need the bullets on top of the columns. I've tried it by defining `locationY: 1.1` but some labels, for example "her" or "she" is still being displayed inside of the columns. Is there a better way to accomplish this?

![image](https://github.com/amcharts/amcharts5/assets/6045678/2ab123f4-6ef9-4403-8c77-cbdc17005f0e)

**Environment (if applicable)**

- amCharts5
- EmberJS

**Additional context**

**Comment by martynasma** [comment]
Better to keep `locationY: 1` but shift the label up using `dy: -10` (or similar value).

Please note it's a setting for the `Label` in bullet, not the bullet itself.
