### ISSUE TITLE
XYChart: How do I format the date axis tooltip based on the value of the date? E.g. using an adapter

### ISSUE THREAD

**Issue by JosephCHW** [amcharts/amcharts5#1003]
I have an XY Chart with a DateAxis set to display hourly time, of which I have managed to customise the labels based on the time (e.g. 00:00, 01:00, 02:00) to my liking using something like this:

```
xAxis.get("renderer").labels.template.adapters.add("text", function(text, target) {
// Use value of text to return a custom label
});

```
I want to do the same for the tooltip of the date axis label.

I have set `tooltipDateFormat `which allows a custom format and a string, but that sets the format for all dates equally, and I am not aware of how I could customise the tooltip based on the date. I have not been able to achieve the same result that I had with the label, with the date axis tooltip. I have tried this approach
```
xAxis.get("tooltip").adapters.add("labelText", function(text, target) {
  return "Custom text";
});
```
But here target.dataItem is undefined and I can't find a way of getting the value of the date tooltip. text is just a static string that is the same for all date axis values.

I have tried to set labelText to have something like `"{value}"` so that I can access this value in the tooltip adapter as the "text" value, but this does not work. Neither does `{valueX}`, `{date}`, `{name}` etc ... all that I have tried just return blank.

any suggestions would be welcome. Thank you in advance for any help.

**Comment by martynasma** [comment]
In your adapter of the tooltip's label, you can get the date the cursor is in like this:

```JavaScript
xAxis.get("tooltip").adapters.add("labelText", function(text, target) {
  var x = cursor.getPrivate("positionX");
  if (x !== undefined) {
    var dateX = xAxis.positionToDate(xAxis.toAxisPosition(x));
    console.log(dateX)
  }
  // Do what you need here
  // ...
});
```
