### ISSUE TITLE
Line chart is not displayed 

### ISSUE THREAD

**Issue by RavidAtiasAxonius** [amcharts/amcharts5#1004]
Hey
I have the following code :

https://codepen.io/isItMeYouLookingFor/pen/BaGpMJo
 
In case I set:
series.strokes.template to a number lower than 7 it is not being displayed

**Comment by RavidAtiasAxonius** [comment]
@martynasma 
This is the output for 7:
![Screenshot 2023-07-09 at 11 45 52](https://github.com/amcharts/amcharts5/assets/111275139/e98d05cc-6fb7-492a-bea3-0bc28422d4d6)

While this is the output for 5:
![Screenshot 2023-07-09 at 11 46 41](https://github.com/amcharts/amcharts5/assets/111275139/79095d34-a19a-43d5-98c5-5a3495dde641)

**Comment by martynasma** [comment]
We'll need to do some more testing on different platforms. Will keep you posted.

**Comment by martynasma** [comment]
OK, so I tried this on a number of Chrome and other browsers running on various OSes. All show the 5px line just fine.

Can you describe precise setup you're getting the issue with?
