### ISSUE TITLE
Custom background color for tooltipHTML on amcharts5

### ISSUE THREAD

**Issue by sswatej** [amcharts/amcharts5#1006]
**Question**

I'm trying to plot a mapChart with bullets at locations with custom colors and tooltipHTML for each bullet, I was trying to get a custom background color for the tooltipHTML, does amcharts5 allows tooltipHTML to have a custom background other than the color of the bullet?

https://codepen.io/sai_tej/pen/abQVxKa

I was looking to have a custom background color for all the tooltipHTMLs rather than having the bullet color.

**Environment (if applicable)**

**Additional context**

**Comment by xorspark** [comment]
You can create a tooltip instance on the series and set `getFillFromSprite` to false to prevent the tooltip from inheriting from the bullet: https://www.amcharts.com/docs/v5/concepts/common-elements/tooltips/#Background

**Comment by sswatej** [comment]
@xorspark I tried it, but it didn't work well with the tooltipHTML. After making few changes, either tooltip is not displayed or it returns something with the same background as the bullet.

**Comment by martynasma** [comment]
You also need to set `fill` for the tooltip background when color is inherited.

**Comment by sswatej** [comment]
It's not working for the tooltipHTML within the Circle element. I've also tried with tooltip element on it's own, it didn't work with my HTML as expected. Either case, I was not able to update the tooltip background. 

Tried this 

```
 let tooltip: any = am5.Tooltip.new(root, {
            getFillFromSprite: false,
            getStrokeFromSprite: true,
            autoTextColor: false,
            getLabelFillFromSprite: true,
            tooltipHTML: tooltipHTML
        });

        tooltip.get("background").setAll({
            fill: am5.color(0xffffff),
            fillOpacity: 0.8
        });

        pointSeries.set("tooltip", tooltip);
```

**Comment by sswatej** [comment]
It worked after I combined both, the above tooltip without the `tooltipHTML` and the below code.


```
var circle = am5.Circle.new(root, {
                templateField: "bulletSettings",
                tooltipHTML: tooltipHTML
            });
```
