### ISSUE TITLE
Setting a variety of colors dynamically

### ISSUE THREAD

**Issue by alabanu** [amcharts/amcharts5#1007]
Question:

Trying to set multiple colors for a stacked area chart  by parsing an array that I am getting from an API. 
However, the chart's color settings are incorrect.

Environment (if applicable)

I'm working with AMCharts5, Angular and TS

Additional context
`let availableColors = ['#60627f', '#638c8e', '#dd96d0', '#626d73', '#3498db', '#989179', '#8086c5'];`
`let colorsArray = [];`
`availableColors.forEach(e => {
      colorsArray.push(am5.color(e));
    });`

`chart.get("colors").set("colors", colorsArray);`

**Comment by zeroin** [comment]
If you could create a codepen with full chart code, we could take a look. It is not possible to tell where the problem is just form this sample.

**Comment by alabanu** [comment]
ok my bad, it's working. 
[https://codepen.io/Alabanu/pen/KKrQKeL](https://codepen.io/Alabanu/pen/KKrQKeL)
Thank you anyway!
