### ISSUE TITLE
Unable to run amcharts5 test case using Jest in react app(Typescript)

### ISSUE THREAD

**Issue by shantu** [amcharts/amcharts5#1008]
**Question**

With the help of the official documentation, I am trying to write a test case with Jest in react app(Typescript) for amCharts 5 but getting the following error:

`Property 'root' does not exist on type 'Element'.ts(2339)
`

<img width="1440" alt="image" src="https://github.com/amcharts/amcharts5/assets/2716503/9309c631-37af-41d4-a6d2-1e4a883114d2">

Please refer to https://codesandbox.io/p/sandbox/amcharts5-react-jest-testcase-forked-8jgpq2 for more details.

**Environment (if applicable)**
 - amCharts version : 5.1.13
 - Browser and its version: Any browser
 - Related frameworks and their versions: React + TypeScript

**Additional context**

**Comment by martynasma** [comment]
Did you follow our official [Jest guide](https://www.amcharts.com/docs/v5/getting-started/integrations/jest/)?

**Comment by Pauan** [comment]
I wasn't able to get Jest working with codesandbox, but I have attached a zip file that contains a working example:

[Jest example.zip](https://github.com/amcharts/amcharts5/files/12028488/Jest.example.zip)

You just do `yarn install` and then `yarn test`

I followed our guide exactly, except I had to remove the `testEnvironment` setting in `package.json`.

**Comment by Pauan** [comment]
By the way, your code is incorrect. You're trying to test the App component, which doesn't work.

You need to do something like this instead:

```ts
// chart.ts
import * as am5 from "@amcharts/amcharts5";
import * as am5xy from "@amcharts/amcharts5/xy";
import am5themes_Animated from "@amcharts/amcharts5/themes/Animated";

export function makeChart() {
    let root = am5.Root.new("chartdiv");

    root.setThemes([am5themes_Animated.new(root)]);

    // Rest of chart code...

    return { root, chart, xAxis, series1, series2 };
}
```

```ts
// chart.test.ts
import { makeChart } from "./chart";

beforeEach(() => {
  // Create <div> which is needed by the chart
  document.body.innerHTML = `<div id="chartdiv"></div>`;
});

test("chart exists", () => {
  const { root, chart } = makeChart();

  // Test chart
  expect(root).toBeDefined();
  expect(chart).toBeDefined();
  expect(chart.get("wheelX")).toBe("panX");
});
```

```ts
// App.tsx
import React, { useLayoutEffect, useRef } from "react";
import "./styles.css";
import { makeChart } from "./chart";

export default function App(props: { data: any; }) {
  const series1Ref = useRef(null);
  const series2Ref = useRef(null);
  const xAxisRef = useRef(null);

  // This code will only run one time
  useLayoutEffect(() => {
    const { root, xAxis, series1, series2 } = makeChart();

    xAxisRef.current = xAxis;
    series1Ref.current = series1;
    series2Ref.current = series2;

    return () => {
      root.dispose();
    };
  }, []);

  // This code will only run when props.data changes
  useLayoutEffect(() => {
    xAxisRef.current.data.setAll(props.data);
    series1Ref.current.data.setAll(props.data);
    series2Ref.current.data.setAll(props.data);
  }, [props.data]);

  return <div id="chartdiv" style={{ width: "100%", height: "500px" }}></div>;
}
```

**Comment by Pauan** [comment]
Although I couldn't get CodeSandbox working, I did create a StackBlitz example:

https://stackblitz.com/edit/node-mm8hqa?file=src%2FApp.js

**Comment by rupak-technicise** [comment]
> 

Thank you @Pauan, for your help. 
But I am getting the following error while trying to run `yarn test` in [StackBlitz](https://stackblitz.com/edit/node-mm8hqa?file=src%2FApp.js):

![image](https://github.com/amcharts/amcharts5/assets/25173884/4d5486a6-68d1-482a-947c-dca95b83b32c)

> Note: It would be helpful if you share the typescript version of the same.

**Comment by Pauan** [comment]
@rupak-technicise That's because StackBlitz doesn't support the `canvas` npm module, there's nothing we can do about that. But if you copy the code into your own project it should work.

You can easily make it work with TypeScript by just renaming the `.js` files to `.ts`

**Comment by rupak-technicise** [comment]
> @rupak-technicise That's because StackBlitz doesn't support the `canvas` npm module, there's nothing we can do about that. But if you copy the code into your own project it should work.
> 
> You can easily make it work with TypeScript by just renaming the `.js` files to `.ts`

It works. Thank you @Pauan.

**Comment by brijesh-imemori** [comment]
`import * as am5 from "@amcharts/amcharts5";
import * as am5xy from "@amcharts/amcharts5/xy";

export function makeChart() {
  const root = am5.Root.new("chartdiv");

  const chart = root.container.children.push(
    am5xy.XYChart.new(root, {
      panX: false,
      panY: false,
      wheelX: "panX",
      wheelY: "zoomX",
    })
  );

  return { root, chart };
}
`

`import { makeChart } from "layouts/dashboards/imemori/ProjectedAndOpps/ProjectRev/amcharttesting";

beforeEach(() => {
  // Create <div> which is needed by the chart
  const div = document.createElement("div");
  div.id = "chartdiv";
  document.body.appendChild(div);
});

test("chart exists", () => {
  const { root, chart } = makeChart();
(url)
  // Test chart
  expect(root).toBeDefined();
  expect(chart).toBeDefined();
  expect(chart.get("wheelX")).toBe("panX");
});
`

Error:
![image](https://github.com/amcharts/amcharts5/assets/111352823/a3388581-4601-4218-a879-98fc86004a36)

So, I was doing the test code for the amcharts, and here this is the issue, I tried so many things but there is no solution out there for this kind of issue, So guys please help me out to resolve this issue.

**Comment by rupak-technicise** [comment]
@brijesh-imemori It could be a version issue.

**Comment by brijesh-imemori** [comment]
Hi @rupak-technicise I am using this version "@amcharts/amcharts5": "^5.5.7" in my project.

**Comment by rupak-technicise** [comment]
Hi @brijesh-imemori, I used "@amcharts/amcharts5": "^5.4.1". You can check other corresponding dependencies as well.

**Comment by brijesh-imemori** [comment]
hi @rupak-technicise I changed the version and it is showing:

![image](https://github.com/amcharts/amcharts5/assets/111352823/91361434-b269-4f4d-a1a4-56d3c53d3613)
