### ISSUE TITLE
Can't make heatRule behave

### ISSUE THREAD

**Issue by olneyMatt** [amcharts/amcharts5#101]
Fabulous library - loving v5 (but still climbing the learning curve!)

Could you help me with something please?

I'm trying to define a heatRule that varies the opacity of a LineSeries line, depending on the y value.

I've tried:

myLineSeries.set("heatRules", [{
    target: myLineSeries.strokes.template,
    dataField: "valueY",
    min: 0,
    max: 1,
    key: "strokeOpacity"
}]);

but it gives me an Uncaught TypeError.

Can you see what I'm doing wrong please?

Thanks Matt

**Comment by martynasma** [comment]
I don't think it will work like that.

LineSeries "strokes" are not created for each data item. In a regular line series there's one "stroke" object, so there's no data item or "valueY" per se.

If you need the line to get gradually lighter for lower values, why not just apply a vertical linear gradient to the stroke?

```JavaScript
series.strokes.template.set("strokeGradient", am5.LinearGradient.new(root, {
  stops: [{
    opacity: 1
  }, {
    opacity: 0
  }]
}));
```

**Comment by olneyMatt** [comment]
Ah - got it thanks.

It's OK, I was trying to achieve a 'broken line' to represent a binary - horizontal line that's visible when value is 1, invisible when value is 0.

I'll approach it a different way. Thanks.

**Comment by martynasma** [comment]
Well, in that case I'd go with the `templateField` approach with a `StepLineSeries`.

https://www.amcharts.com/docs/v5/concepts/settings/template-fields/
