### ISSUE TITLE
Legend does not looks properly in here

### ISSUE THREAD

**Issue by padfoot044** [amcharts/amcharts5#1010]
amCharts Version:5 
angular: 12

https://jsfiddle.net/ags3kt6q/3/

check the legend

**Comment by zeroin** [comment]
It should be: `centerY: am5.p100`

However a recommended way would be to set layout:root.verticalLayout on a chart and then do not set y and centerY for the legend at all, as your approach will result overlap.

**Comment by padfoot044** [comment]
Not its not working with centerY: am5.p100, now legend goes to top left

**Comment by padfoot044** [comment]
https://jsfiddle.net/qmydLn8r/

check this

**Comment by padfoot044** [comment]
https://codepen.io/team/amcharts/pen/wvXzOyz

its also not work with codePen

**Comment by padfoot044** [comment]
tooltip is not also working for same code

**Comment by zeroin** [comment]
Could you explain what you want to achieve? If you want axis tooltip, you need to add ChartCursor to the chart.

**Comment by padfoot044** [comment]
![image](https://github.com/amcharts/amcharts5/assets/55396959/36c0bfd8-ad0c-4abe-9363-55153e0d79d8)

I want this kind of tooltip
Do I need to use ChartCursor for this tooltip?

**Comment by zeroin** [comment]
Yes, you do.
