### ISSUE TITLE
How we can set interval between xAxes values?

### ISSUE THREAD

**Issue by padfoot044** [amcharts/amcharts5#1013]
amCharts version : 5
angular version: 12

![image_2023_07_14T06_14_28_964Z](https://github.com/amcharts/amcharts5/assets/55396959/1ea1e742-5d21-43e1-a04b-a72f2855014d)

as we can see there are 1 to 24 values in xAxes, but I want to make it in interval like 0 to 3 then 3 to 6
Is there any way to do that?

**Comment by martynasma** [comment]
The only way to ensure grid/labels appear at specific values is to use axis ranges:
https://www.amcharts.com/docs/v5/tutorials/using-axis-ranges-to-place-labels-at-arbitrary-values-or-dates/
