### ISSUE TITLE
amChart5 Candlestick Chart: Style xAxis & yAxis tooltips

### ISSUE THREAD

**Issue by enjoywithouthey** [amcharts/amcharts5#1014]
Regarding the amChart5 Candlestick chart, how do I style the fill & stroke colors of the x and y axis tooltips?

In some some cases I want to show the same color as the main chart tooltip and in some cases I want to simply change the styling. Right now I am unable to change any of the stroke or fill properties of the axis tooltips.

Please refer to the demo found here: https://www.amcharts.com/demos/candlestick-chart/
<img width="600" alt="Screenshot 2023-07-15 at 10 26 44 PM" src="https://github.com/amcharts/amcharts5/assets/17732015/09c8534f-fd43-4ddc-8156-db3b47ae4b50">

**Comment by martynasma** [comment]
You can style axis tooltip just like any other tooltip:
https://www.amcharts.com/docs/v5/concepts/common-elements/tooltips/#Outline

**Comment by enjoywithouthey** [comment]
@martynasma Not exactly.

In the CandleStick Demo above, a tooltip using `getFillFromSprite` is defined in the CandleStick Series.

But then when the Xaxis tooltip is rendered, the `getFillFromSprite` will not work.

How do we make the Xaxis tooltip match the same color changes happening in the cursor tooltip?

thanks,

**Comment by martynasma** [comment]
The axis tooltip does not have a "target sprite" hence `getFillFromSprite` not working.

Just to make sure, you need tooltip to dynamically change color to the nearest candle's? Just like series tooltip?

**Comment by enjoywithouthey** [comment]
Yes, that is correct.  I would like the Axis tooltip to have the same color changing behavior as the cursor tooltip.  Please see the candlestick demo here: https://www.amcharts.com/demos/candlestick-chart/

**Comment by martynasma** [comment]
Gotcha.

This can be easily achieved using an adapter:

```JavaScript
xAxis.get("tooltip").get("background").adapters.add("fill", function(fill, target) {
  return series.get("tooltip").get("background").get("fill");
});
```

Example:
https://codepen.io/team/amcharts/pen/qBQMoOx??editors=0010
