### ISSUE TITLE
Add a label parellel to the linking line of a line series

### ISSUE THREAD

**Issue by koorizhizhi** [amcharts/amcharts5#1017]
**Question**
I want to add a text label which should be parallel to the linking line between two points of a line series on a XY chart which has a category X axis and a value Y axis.
 
The label should be equally spaced either side of the 2 plots.

I've tried to calculate the angle and got the label rotated but since the x axis is a category axis I don't know how to ge the dx value(the interval between the 2 plots)... And I cannot figure out how to place it equally spaced on the linking line for the same reason.

The img below demonstrates what I want to achieve:
![image](https://github.com/amcharts/amcharts5/assets/83855880/9493599d-7312-4d5a-85bc-44c13a28a838)

Thanks in advance for all your support :)

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
I'm afraid there's no built-in functionality to add bullets on a series lines, rather than on the data point location.

**Comment by koorizhizhi** [comment]
> I'm afraid there's no built-in functionality to add bullets on a series lines, rather than on the data point location.

Do you know if there is a way to get numerical coordinates of a point on such a chart to let me calculate the midpoint as well as the angle?

**Comment by zeroin** [comment]
XYSeriesDataItem has `point` setting which holds x and y.
