### ISSUE TITLE
Format YAxis tooltip value?

### ISSUE THREAD

**Issue by binaryartifex** [amcharts/amcharts5#1018]
in the context of an XY time series chart, for the life of me i can't figure out how to format the y axis value tooltip - the tooltip that renders with the cursor whereever it is. at present its the raw number fed to the the chart. i have a custom transform function id like to use with no idea how to get the actual integer value to transform. the data series tooltips are easy enough however i can't seem to isolate and transform a 'tooltipDataItem' from an axis source as opposed to a data series source...

**Comment by zeroin** [comment]
You can use `tooltipNumberFormat` axis setting to format the value: https://www.amcharts.com/docs/v5/reference/valueaxis/#tooltipNumberFormat_setting

Alternatively you could add adapter for tooltip labels text setting:

```
var tooltip = am5.Tooltip.new(root, {})
tooltip.label.adapters.add("text", (text)=>{
  return text +"%" 
})

var yAxis = chart.yAxes.push(am5xy.ValueAxis.new(root, {
  tooltip: tooltip,
  renderer: am5xy.AxisRendererY.new(root, {})
}));
```

**Comment by binaryartifex** [comment]
yeah nice cheers for that. that done it.
