### ISSUE TITLE
Zoom Causing Browser Hang

### ISSUE THREAD

**Issue by jdsmith39** [amcharts/amcharts5#1019]
**Bug description**

If I zoom on the full chart (be sure to include all lines) and do this multiple times, it will eventually go into an infinite loop.  Based on what I briefly looked at, it looks like it keeps setting the bounds as dirty, which creates an infinite loop.

Example of the way to zoom.  Must always capture all of the data points.
![image](https://github.com/amcharts/amcharts5/assets/3290618/06b38458-1ff2-4c51-af65-efe0b5667f3a)

[Codepen link](https://codepen.io/Jeremy-Smith-the-bashful/pen/RwqBWPm)

**Environment (if applicable)**

Latest AMCharts 5
Chrome, Edge and Firefox (didn't try any others)

**Comment by zeroin** [comment]
Looks like it is causes by the syncing of the axes, I was unable to reproduce it with syncing turned off. Syncing of the axes is experimental feature and not always works fine, although I must admit it shouldn't hang the browser. However I was unable to find out what exactly causes this problem. If you have a license of amCharts, please, contact us through our support.

**Comment by jdsmith39** [comment]
We are using the free version currently.  We are turning off axis syncing for now.  Thank you for the work around.
