### ISSUE TITLE
Axis containers inside leftAxesContainer?

### ISSUE THREAD

**Issue by olneyMatt** [amcharts/amcharts5#102]
I want to create a plot to show **lots** of parameters stacked vertically like the attached.

I'd like more control over the placement of the y-axes (ability to overlap, offset left and right etc.) so I've pushed some containers into chart.leftAxesContainer. However, when I try to add y-axes to those containers, I get errors.

Am I doing something wrong or can y-axes only exist in the 'special' Axes containers?

Thanks
Matt

<img width="554" alt="Screenshot 2021-11-29 at 09 37 40" src="https://user-images.githubusercontent.com/94979269/143843534-7b4f90e4-1a81-4886-8323-ec6bccbebc93.png">

**Comment by martynasma** [comment]
There's no "special" container. And there should not be any issues with juggling parents for axes.

Do you have a runnable demo?

**Comment by olneyMatt** [comment]
Sorry to be a pain - I'm sure it's something daft I'm doing. As you'll see from the below, I am NOT a professional coder!

This codePen shows my issue in a cutdown version:
https://codepen.io/olneymatt/pen/LYzPwra

Lines 74, 86 and 97 try to push the axes to my new Y-axis containers (_fdYaxisCont1_ and _fdYaxisCont2_) but gets an Uncaught Type Error.

Using lines 83, 85 and 96 instead to push them as regular Y-axes works as expected.

Like I say - sure I've just done something stupid.
Thanks so much for your help.

**Comment by olneyMatt** [comment]
Ah, understood - I wondered how the chart 'knew' what to do with an axis.

That makes sense thanks - will give it a go.

**Comment by olneyMatt** [comment]
OK - I'm being a complete dullard!

I have updated the pen (https://codepen.io/olneymatt/pen/LYzPwra) to:
- push to `yAxes` first (eg line 80) 
- then push into my new containers (`fdYaxisCont1` and `2` with coloured backgrounds to show) eg line 91 

`myContainer.allChildren()` shows the axes as being children of the new containers and the chart renders successfully, but the axes are still rendering inside `leftAxesContainer` rather than my new containers.

Any help appreciated. Sorry to be such a pain!...

**Comment by martynasma** [comment]
No worries, man.

Would you try besides pushing into children also setting `parent`?

```JavaScript
fdYaxisCont1.children.push(fdParam1yAxis);
fdParam1yAxis.parent = fdYaxisCont1;
```

**Comment by olneyMatt** [comment]
Done (lines 92, 106 and 120)

No joy I'm afraid.

**Comment by martynasma** [comment]
Alright. I'll need to get back to you on this.

**Comment by olneyMatt** [comment]
No problem at all - thanks for your effort 👍

**Comment by martynasma** [comment]
OK, so it turns out our code needs axes to be in specific containers, for internal reasons.

There's no way to achieve what you need. Sorry :(

**Comment by olneyMatt** [comment]
OK - thanks so much for looking into it. I'll explore other ways of achieving inside the same container.

Thanks
