### ISSUE TITLE
Animation beetwin two point doesn't work

### ISSUE THREAD

**Issue by slavakamrad** [amcharts/amcharts5#1021]
Hello, I took your code as an example: https://www.amcharts.com/demos/map-with-animated-lines/

I only needed to connect two points on the map with an animated line. I changed the code, but something went wrong. Could you tell me why the animation does not start?

My codepen: https://codepen.io/slavakamrad/pen/BaGPGPK

And if this is not possible, then how can stop the animation in your example after a certain time has elapsed?

**Comment by zeroin** [comment]
When you set pointsToConnect, you use series and not data points:

`lineDataItem.set("pointsToConnect", [srcCitySeries, dstCitySeries])`

it should be:

`lineDataItem.set("pointsToConnect", [sourceDataItem, destinationDataItem])`

**Comment by slavakamrad** [comment]
> When you set pointsToConnect, you use series and not data points:
> 
> `lineDataItem.set("pointsToConnect", [srcCitySeries, dstCitySeries])`
> 
> it should be:
> 
> `lineDataItem.set("pointsToConnect", [sourceDataItem, destinationDataItem])`

Thanks a lot!!!
It's working =)
