### ISSUE TITLE
Get numerical coordinates/position of a point on a XY chart where X axis is a category axis

### ISSUE THREAD

**Issue by koorizhizhi** [amcharts/amcharts5#1022]
**Question**
Hi, is there a way to get numerical coordinates/position of a plot on a XY chart with a category axis and a value axis?

I tried to get them from dataitem._settings.point property but it looks like these values are available only when the chart has been rendered (but there is no such an event according to the event list of the chart). 

Thank you for your help!

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
Just to make sure, you need screen coordinates (X and Y) of the point of a particular data point?

**Comment by koorizhizhi** [comment]
> Just to make sure, you need screen coordinates (X and Y) of the point of a particular data point?

If it's possible to get the coordinates of a particular data point on the chart scale then that would be great.
If not then I want to try to use the screen coordinates...

Thank you for your support

**Comment by martynasma** [comment]
Both are possible.

When you say "coordinates of a particular data point", what do you mean?

Does it mean you have a data point object and need its value/category? Or its pixel coordinates within plot container? Something else?

**Comment by koorizhizhi** [comment]
Hi I want to have its pixel coordinates within plot container.
Very much appreciated : )

**Comment by koorizhizhi** [comment]
> Both are possible.
> 
> When you say "coordinates of a particular data point", what do you mean?
> 
> Does it mean you have a data point object and need its value/category? Or its pixel coordinates within plot container? Something else?

Hi can you share with me both the ways getting those coordinates?

**Comment by zeroin** [comment]
`point` of data item can change many times - when animating, zooming, etc. So I would suggest to monitor it:
https://codepen.io/team/amcharts/pen/abQQEzq/d33c27a4182740ca9d83b881c35b4ce9

```
am5.array.each(series.dataItems, (dataItem)=>{
  dataItem.on("point", (point)=>{
    console.log(point)
  })
})
```

**Comment by koorizhizhi** [comment]
> `point` of data item can change many times - when animating, zooming, etc. So I would suggest to monitor it: https://codepen.io/team/amcharts/pen/abQQEzq/d33c27a4182740ca9d83b881c35b4ce9
> 
> ```
> am5.array.each(series.dataItems, (dataItem)=>{
>   dataItem.on("point", (point)=>{
>     console.log(point)
>   })
> })
> ```

Thank you for all your help. I decided to draw the label in a chart ready callback and it works:
![image](https://github.com/amcharts/amcharts5/assets/83855880/8fd4b13c-1d6c-4548-888f-dd6b151735c6)
