### ISSUE TITLE
how to sync XY value axes when one axis has negative values? 

### ISSUE THREAD

**Issue by binaryartifex** [amcharts/amcharts5#1023]
The documentation [(here)](https://www.amcharts.com/docs/v5/charts/xy-chart/axes/value-axis/#Syncing_grid) for syncing two axes doesn't provide an example where one of the axis values might have a negative value. for instance if i have two axis with one having a calculated negative maximum of -500, however the opposing axis does not dip below 0, how can i force the opposing axis to stay level with the original axis 0 line? syncWithAxis doesn't seem to do...well, anything in this instance.

**Comment by martynasma** [comment]
Syncing works fine for me even in a mixed scenario where negative scale is involved. Example:
https://codepen.io/team/amcharts/pen/Jjeapqy/b6eac17048532140050584d455538894?editors=0010

If you do have an example where it fails, maybe you can provide a CodePen for us to test?

**Comment by binaryartifex** [comment]
@martynasma ironically the example you provided illustrates my point thats driving me insane. is it possible to have all axis' aligned to a base of zero? in the example there's negatives aligned with positives, id like to have all axis synced and scaled off of a base of zero. is this possible?

**Comment by binaryartifex** [comment]
case in point, i have energy on the left axis, power on the right. energy is a negatively stacked barchart. power is a trend line. power doesn't go into the negatives, yet its 'zero line' is in line with energy's lowest negative value. it would be great to have them normalized off the same zero line if that makes sense

**Comment by martynasma** [comment]
> is it possible to have all axis' aligned to a base of zero?

Nope. I'm afraid that's not possible using `syncWithAxis`.

The only way would be to dynamically adjust scale of each axis that it spans equal absolute values above and below zero, so that zero grid always in the middle.

However, that's not a very efficient use of space, and I don't have a ready made example for that.
