### ISSUE TITLE
Problem: geoBounds() not defined

### ISSUE THREAD

**Issue by adrmisty** [amcharts/amcharts5#1024]
Hello!

I am making a web component using Vue, and the Amcharts5 API (specifically world map visuals with GeoJSON data).
I am encountering this problem:

<img width="287" alt="image" src="https://github.com/amcharts/amcharts5/assets/98897794/2f004ac5-e7c3-472b-a91b-b1379ae003c5">

When trying to display the map (this.$am5.ready(.....)), it is not properly displayed due to the fact that the invoking of the function `geoBounds(geometry)` in MapUtils.js cannot be executed as it is only defined, but not implemented.

I do not know how to follow up with development, because I cannot find a reason for this happening. All proper imports have been done, and the code compiles except for this.

Thank you!

**Comment by martynasma** [comment]
We'll need to see your code, I'm afraid. We can't reproduce this error with our test map setups.

**Comment by adrmisty** [comment]
Hello,

Just one heads-up: this code used to work perfectly before I converted it into a Vue project.

-------------------------------------------------------------------------------------------------------------

These are the imports:

import * as am5 from '@amcharts/amcharts5';
import * as am5map from '@amcharts/amcharts5/map'; 
import * as am5geodata from "@amcharts/amcharts5-geodata"
import am5geodata_worldLow from "@amcharts/amcharts5-geodata/worldLow"
import am5geodata_data_countries2 from "@amcharts/amcharts5-geodata/data/countries2";
import am5themes_Animated from "@amcharts/amcharts5/themes/Animated";

// leave the export, even if you don't use it
export default ({ app, router, Vue }) => {
  Vue.prototype.$am5 = am5
  Vue.prototype.$am5map = am5map
  Vue.prototype.$am5geodata = am5geodata
  Vue.prototype.$am5geodata_data_countries2 = am5geodata_data_countries2
  Vue.prototype.$am5geodata_worldLow = am5geodata_worldLow
  Vue.prototype.$am5themes_Animated = am5themes_Animated
}
-------------------------------------------------------------------------------------------------------------

This is the code to set up the map:

        var root = this.$am5.Root.new("map"); 

        // Map theme (Mercator projection)
        root.setThemes([this.$am5themes_Animated.new(root)]);

        var map = root.container.children.push(
            this.$am5map.MapChart.new(root, {
              panX: "rotateX",
              addClassNames: true,
              projection: this.$am5map.geoMercator()
            })
          );

        map.chartContainer.set("background", this.$am5.Rectangle.new(root, {
            fill: this.$am5.color(0xF3F3F3),
            fillOpacity: 1
        }));

        let worldSeries = map.series.push(
            this.$am5map.MapPolygonSeries.new(root, {
                geoJSON: this.$am5geodata_worldLow,
                exclude: ["AQ"]
            })
        );

        // Create the polygons for each country
        worldSeries.mapPolygons.template.setAll({
            interactive: true,
            fill: this.$am5.color(0x045c74),
            templateField: "polygonSettings"
        });

-------------------------------------------------------------------------------------------------------------

There are further auxiliary functions that set up bubbleSeries, colours, hovers, actions... but as I said, everything worked perfectly. I am trying to add this map onto a widget in a given webpage, with this random dimensions I put just to try:

 `#map(style="width: 500px;height: 500px;")`

but the error I am finding is that MapUtils.js throws an exception because the method `geoBounds(geometry)` is not defined. Which is weird, considering I think I have imported everything correctly (?). The node-modules folder includes everything that might be needed:

<img width="94" alt="image" src="https://github.com/amcharts/amcharts5/assets/98897794/751691f5-8bda-4efd-819c-bb90ea54080e">

And here is the method that throws the exception:

<img width="450" alt="image" src="https://github.com/amcharts/amcharts5/assets/98897794/12af7d8c-abaa-45c1-9529-4edc7c1c9d50">

<img width="686" alt="image" src="https://github.com/amcharts/amcharts5/assets/98897794/4445e570-4e40-4c66-a38a-637c7aecec94">

-------------------------------------------------------------------------------------------------------------

Any help would be much appreciated. Thanks! :)

**Comment by adrmisty** [comment]
Hello,

Just one heads-up: this code used to work perfectly before I converted it into a Vue project.

These are the imports:

  import * as am5 from '@amcharts/amcharts5';
  import * as am5map from '@amcharts/amcharts5/map';
  import * as am5geodata from "@amcharts/amcharts5-geodata"
  import am5geodata_worldLow from "@amcharts/amcharts5-geodata/worldLow"
  import am5geodata_data_countries2 from "@amcharts/amcharts5-geodata/data/countries2";
  import am5themes_Animated from "@amcharts/amcharts5/themes/Animated";
  
  // leave the export, even if you don't use it
  export default ({ app, router, Vue }) => {
    Vue.prototype.$am5 = am5
    Vue.prototype.$am5map = am5map
    Vue.prototype.$am5geodata = am5geodata
    Vue.prototype.$am5geodata_data_countries2 = am5geodata_data_countries2
    Vue.prototype.$am5geodata_worldLow = am5geodata_worldLow
    Vue.prototype.$am5themes_Animated = am5themes_Animated
  }


This is the code to set up the map:

    var root = this.$am5.Root.new("map"); 

    // Map theme (Mercator projection)
    root.setThemes([this.$am5themes_Animated.new(root)]);

    var map = root.container.children.push(
        this.$am5map.MapChart.new(root, {
          panX: "rotateX",
          addClassNames: true,
          projection: this.$am5map.geoMercator()
        })
      );

    map.chartContainer.set("background", this.$am5.Rectangle.new(root, {
        fill: this.$am5.color(0xF3F3F3),
        fillOpacity: 1
    }));

    let worldSeries = map.series.push(
        this.$am5map.MapPolygonSeries.new(root, {
            geoJSON: this.$am5geodata_worldLow,
            exclude: ["AQ"]
        })
    );

    // Create the polygons for each country
    worldSeries.mapPolygons.template.setAll({
        interactive: true,
        fill: this.$am5.color(0x045c74),
        templateField: "polygonSettings"
    });

There are further auxiliary functions that set up bubbleSeries, colours, hovers, actions... but as I said, everything worked perfectly. I am trying to add this map onto a widget in a given webpage, with this random dimensions I put just to try:

#map(style="width: 500px;height: 500px;")

but the error I am finding is that MapUtils.js throws an exception because the method geoBounds(geometry) is not defined. Which is weird, considering I think I have imported everything correctly (?). The node-modules folder includes everything that might be needed:

image
And here is the method that throws the exception:

image image
Any help would be much appreciated. Thanks! :)

**Comment by adrmisty** [comment]
Hello,

Just one heads-up: this code used to work perfectly before I converted it into a Vue project.

These are the imports:

import * as am5 from '@amcharts/amcharts5';
import * as am5map from '@amcharts/amcharts5/map';
import * as am5geodata from "@amcharts/amcharts5-geodata"
import am5geodata_worldLow from "@amcharts/amcharts5-geodata/worldLow"
import am5geodata_data_countries2 from "@amcharts/amcharts5-geodata/data/countries2";
import am5themes_Animated from "@amcharts/amcharts5/themes/Animated";

// leave the export, even if you don't use it
export default ({ app, router, Vue }) => {
Vue.prototype.$am5 = am5
Vue.prototype.$am5map = am5map
Vue.prototype.$am5geodata = am5geodata
Vue.prototype.$am5geodata_data_countries2 = am5geodata_data_countries2
Vue.prototype.$am5geodata_worldLow = am5geodata_worldLow
Vue.prototype.$am5themes_Animated = am5themes_Animated
}


This is the code to set up the map:


    var root = this.$am5.Root.new("map"); 

    // Map theme (Mercator projection)
    root.setThemes([this.$am5themes_Animated.new(root)]);

    var map = root.container.children.push(
        this.$am5map.MapChart.new(root, {
          panX: "rotateX",
          addClassNames: true,
          projection: this.$am5map.geoMercator()
        })
      );

    map.chartContainer.set("background", this.$am5.Rectangle.new(root, {
        fill: this.$am5.color(0xF3F3F3),
        fillOpacity: 1
    }));

    let worldSeries = map.series.push(
        this.$am5map.MapPolygonSeries.new(root, {
            geoJSON: this.$am5geodata_worldLow,
            exclude: ["AQ"]
        })
    );

    // Create the polygons for each country
    worldSeries.mapPolygons.template.setAll({
        interactive: true,
        fill: this.$am5.color(0x045c74),
        templateField: "polygonSettings"
    });


There are further auxiliary functions that set up bubbleSeries, colours, hovers, actions... but as I said, everything worked perfectly. I am trying to add this map onto a widget in a given webpage, with this random dimensions I put just to try:

#map(style="width: 500px;height: 500px;")

but the error I am finding is that MapUtils.js throws an exception because the method geoBounds(geometry) is not defined. Which is weird, considering I think I have imported everything correctly (?). The node-modules folder includes everything that might be needed:

<img width="93" alt="image" src="https://github.com/amcharts/amcharts5/assets/98897794/4d22232a-ec06-41c2-af18-e3acca417b91">

And here is the method that throws the exception (in MapUtil.js and index.d.ts):

<img width="476" alt="image" src="https://github.com/amcharts/amcharts5/assets/98897794/aae06108-f06a-4625-b81c-98e44afe6cfa">

<img width="701" alt="image" src="https://github.com/amcharts/amcharts5/assets/98897794/43c283e7-e856-4bac-bc6f-90cb1e2846c6">


Any help would be much appreciated. Thanks! :)

**Comment by martynasma** [comment]
Have you tried following our Vue manual?

https://www.amcharts.com/docs/v5/getting-started/integrations/vue/

**Comment by adrmisty** [comment]
Yes, I have followed everything in the manual. I just don't understand why the 'geoBounds' error pops up!

**Comment by martynasma** [comment]
I'm sorry but from what little snipped you have posted it's not entirely clear whether that's the case.

Would you be able to post your whole chart setup on StackBlitz?
