### ISSUE TITLE
Radar chart needle (clock hand) not visible when changing limits

### ISSUE THREAD

**Issue by diana-sandu-syntax** [amcharts/amcharts5#1025]
**Question**
Sandbox: https://codesandbox.io/s/priceless-driscoll-chmg2c?file=/src/components/GaugeChart.vue

I'm attempting to change the value of a Radar chart from 2 to 2 seconds. I can also adjust the segments (bands) that the chart utilizes, allowing the min and max limits to vary over time. If I adjust the limits and the value is outside the boundaries, the needle disappears (which is usual behavior). The issue is that, even if the new number is correct and within the parameters, the needle will no longer be visible. 

For example, even though the value is correct, the needle is no longer visible:![image](https://github.com/amcharts/amcharts5/assets/91673654/8797b5f7-7f0c-4d4f-9ac6-26a40bdb9835)

I'd like to know how to properly update the radar chart so that I can see the needle (clock hand). 

I left a sandbox example where you can change the min and max for each band (no validations, so make sure you have a valid segment) and the needle will disappear if you fool around with the limits.

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
If you need to update start/end values of the axis range, you can use `setAll()` method on its object.

To update start/end values of the axis, use `setAll()` method on axis to set its `min`/`max` avalues.

E.g.:

```JavaScript
// Update last range
var range = xAxis.axisRanges.getIndex(xAxis.axisRanges.length - 1);
range.setAll({
  endValue: 90
});
xAxis.setAll({
  max: 90
});
```

Example:
https://codepen.io/team/amcharts/pen/poQQgdW/4d7debfedc879f952bb134782306bd7e?editors=0010

Also make sure that the values you set are numeric, as values that come from form inputs will be strings.

**Comment by diana-sandu-syntax** [comment]
> If you need to update start/end values of the axis range, you can use `setAll()` method on its object.
> 
> To update start/end values of the axis, use `setAll()` method on axis to set its `min`/`max` avalues.
> 
> E.g.:
> 
> ```js
> // Update last range
> var range = xAxis.axisRanges.getIndex(xAxis.axisRanges.length - 1);
> range.setAll({
>   endValue: 90
> });
> xAxis.setAll({
>   max: 90
> });
> ```
> 
> Example: https://codepen.io/team/amcharts/pen/poQQgdW/4d7debfedc879f952bb134782306bd7e?editors=0010
> 
> Also make sure that the values you set are numeric, as values that come from form inputs will be strings.

Thank you, it seems that is working.
