### ISSUE TITLE
How to show count if there are largest column here?

### ISSUE THREAD

**Issue by padfoot044** [amcharts/amcharts5#1026]
![image](https://github.com/amcharts/amcharts5/assets/55396959/20dc34a0-3b19-4754-b509-4a514608f753)

**Comment by padfoot044** [comment]
`    let chart = root.container.children.push(
        am5xy.XYChart.new(root, {
          panX: false,
          panY: false,
          wheelX: 'none',
          wheelY: 'none',
          layout: root.verticalLayout,
        })
      );

      // Add cursor
      // https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/
      let cursor = chart.set('cursor', am5xy.XYCursor.new(root, {}));
      cursor.lineY.set('visible', false);

      // Create axes
      // https://www.amcharts.com/docs/v5/charts/xy-chart/axes/
      let xRenderer = am5xy.AxisRendererX.new(root, { minGridDistance: 30 });
      xRenderer.labels.template.setAll({
        rotation: -45,
        centerY: am5.p50,
        centerX: am5.p100,
        paddingRight: 15,
      });

      xRenderer.grid.template.setAll({
        location: 1,
      });

      let xAxis = chart.xAxes.push(
        am5xy.CategoryAxis.new(root, {
          maxDeviation: 0.5,
          categoryField: x[0],
          renderer: xRenderer,
          tooltip: am5.Tooltip.new(root, {}),
        })
      );

      let yAxis = chart.yAxes.push(
        am5xy.ValueAxis.new(root, {
          maxDeviation: 0.3,
          renderer: am5xy.AxisRendererY.new(root, {
            strokeOpacity: 0.1,
          }),
        })
      );

      // Create series
      // https://www.amcharts.com/docs/v5/charts/xy-chart/series/
      let series = chart.series.push(
        am5xy.ColumnSeries.new(root, {
          name: 'Series 1',
          xAxis: xAxis,
          yAxis: yAxis,
          valueYField: x[1],
          sequencedInterpolation: true,
          categoryXField: x[0],
          tooltip: am5.Tooltip.new(root, {
            labelText: '[bold] {valueY}',
          }),
        })
      );

      series.bullets.push(function () {
        return am5.Bullet.new(root, {
          locationY: 1,
          sprite: am5.Label.new(root, {
            text: '{valueY}',
            centerY: am5.p100,
            centerX: am5.p50,
            populateText: true,
          }),
        });
      });

      series.columns.template.setAll({ strokeOpacity: 0 });
      series.columns.template.adapters.add('fill', function (fill, target) {
        return chart.get('colors').getIndex(series.columns.indexOf(target));
      });

      series.columns.template.adapters.add('stroke', function (stroke, target) {
        return chart.get('colors').getIndex(series.columns.indexOf(target));
      });

      xAxis.data.setAll(infodata);
      series.data.setAll(infodata);

      // Make stuff animate on load
      // https://www.amcharts.com/docs/v5/concepts/animations/
      series.appear(1000);
      chart.appear(1000, 100);`
      
      here is the code

**Comment by martynasma** [comment]
There are two ways to handle this:

1) Relatively expand Y axis scale.
2) Unmask bullets.

Please refer to this tutorial for further info:
https://www.amcharts.com/docs/v5/tutorials/handling-bullet-masking/
