### ISSUE TITLE
rotated x axis labels are overflowing out of view

### ISSUE THREAD

**Issue by chawkichalladia** [amcharts/amcharts5#1027]
I'm rotating my x axis labels by -30, however, the last few  labels are been hidden and not showing (see picture below). please let me know what I can do to fix this.

code is available in the following gist: https://gist.github.com/chawkichalladia/3b0636316d1674ad31652cfc2f50682a

![image](https://github.com/amcharts/amcharts5/assets/39971257/aa0b4d4e-61c6-4932-a9ba-c65b01433850)

**Comment by martynasma** [comment]
As text in chart cannot leave chart area, I suggest you add some `paddingRight` to chart.

E.g.:

```JavaScript
chart.set("paddingRight", 30);
```

**Comment by chawkichalladia** [comment]
it worked, thanks a lot. I'm kinda struggling with the documentation to know what needs to be done.
