### ISSUE TITLE
How to push labels on an xy chart from top to bottom without overlap responsive

### ISSUE THREAD

**Issue by NandaNxD** [amcharts/amcharts5#1028]
Im trying to insert lables into an XY chart. When i use dx and dy its not helping in responsive height and width, basically it merges things if i change font size of parent container. 
Is there any way to add labels without using dx and dy and without having label text merge with each other

**Comment by NandaNxD** [comment]
<img width="67" alt="image" src="https://github.com/amcharts/amcharts5/assets/65838540/08c1c517-0cf5-455c-b3d5-8fdf28b023df">
Basically when i try to add labels by using x and y percent it has a possibiity of merge like you can see on the right... I wanted to know if there is some other way like pushing in an array that handles merging automatically

**Comment by martynasma** [comment]
You can add a `Container` with `layout: root.verticalLayout` set.

Then push your `Label` elements into its children.

**Comment by NandaNxD** [comment]
Thankyou :)
