### ISSUE TITLE
Dynamically change colors of chart

### ISSUE THREAD

**Issue by StcYurii** [amcharts/amcharts5#1030]
Hi, 
I am developing an react SPA and would like to implement change of theme of site including charts. Now i fond that the only way to force rerender with new colors is to use series.data.setAll(data) in other useEffect (I access it through ref), is there a better way to do this. 
Thank you in advance,

**Comment by StcYurii** [comment]
I'm talking about the map chart in particular.

**Comment by ng-druid** [comment]
@StcYurii The color of each MapPolygon can be changed by using a fill on the series.

<img width="655" alt="Screen Shot 2023-07-31 at 6 33 17 PM" src="https://github.com/amcharts/amcharts5/assets/73197190/505522e5-0b56-41e8-aa34-c50d09cf4f97">

The outline color can be changed by using a stroke on the template.

<img width="370" alt="Screen Shot 2023-07-31 at 6 34 16 PM" src="https://github.com/amcharts/amcharts5/assets/73197190/ce9565e6-fca1-4635-80e2-600f72703bf8">

**Comment by devimaruthi** [comment]
Hi @martynasma How have you added question label to the question. I have a question and posted that. But cannot able to add label. Can you please help
