### ISSUE TITLE
How to change colors of  markers in a map dynamically according to the color present in my data

### ISSUE THREAD

**Issue by devimaruthi** [amcharts/amcharts5#1031]
I have a map with several markers in it. I want to color each marker according to  the color present in my data. I cannot able to dynamically change the color of my markers. How to do that. 

**Environment (if applicable)**

**Additional context**

**Comment by zeroin** [comment]
It is difficult to tell something without seeing your chart. You could either use heat rules:
https://www.amcharts.com/docs/v5/concepts/settings/heat-rules/

or simply set colors for your markers. If you'd show a codepen with your chart and data, maybe I could suggest something more.

**Comment by devimaruthi** [comment]
@zeroin Thanks for replying. This is the link for the codepen for my chart https://codepen.io/devi_maruthi/pen/rNQPxBL. Tooltip is adding dynamically to the marker but not the color. I can change color in my data from text-success to any color code if needed but in my map my marker has to be in a color that is predefined in my mapData

**Comment by zeroin** [comment]
I am afraid I don't see any markers in your example. My suggestion would be to use templateFields for your purpose:
https://www.amcharts.com/docs/v5/concepts/settings/template-fields/

**Comment by devimaruthi** [comment]
@zeroin Thanks for the suggestion. Here is my link for codepen. https://codepen.io/devi_maruthi/pen/rNQPWLv. I am having 1800 points in the map. From the server I will get the point title, latitude, longitude, url and color(cities). How to  color the point according to the data from the server

**Comment by zeroin** [comment]
Have you tried the template fields approach I suggested? 
If you have a license, please, address our support - I am sorry, but we can not provide such a support here.

**Comment by devimaruthi** [comment]
@zeroin I have tried the approach. I can't able to see a marker in a map, I will give a sample of mapData that i am going to get from y server and my approach to the logic function LoadMap(mapData){
            //creating root element
            var root = am5.Root.new("map");
            //creating map
            var chart = root.container.children.push(
                am5map.MapChart.new(root, {})
            );
            //creating polygon series for countries
            var polygonSeries = chart.series.push(
                am5map.MapPolygonSeries.new(root, {
                    geoJSON: am5geodata_region_world_worldRegionsLow,
                    exclude: ["antarctica"]
                })
            );
            //creating mappointseries for markers
            var pointSeries = chart.series.push(
                am5map.MapPointSeries.new(root, {
                    // ...
                })
            );
            var circleTemplate = am5.Template.new({
                tooltipText: "{title}"
            });

            //creating bullet series 
            pointSeries.bullets.push(function () {
                return am5.Bullet.new(root, {
                    sprite: am5.Circle.new(
                    root,
                    {
                        radius: 10,
                        templateField: "circleTemplate"
                    }, circleTemplate
                    )
                });
            });
            pointSeries.set("heatRules", [
                {
                    target: circleTemplate,
                    min: 3,
                    max: 30,
                    key: "radius",
                    dataField: "title"
                }
            ]);
            console.log(mapData);
            pointSeries.data.setAll(mapData);
        }. mapData = [{
        "title": "Una, Amb Road(Online)",
        "latitude": 35.158394,
        "longitude": 75.750988,
        "circleTemplate": {
            "fill": "#28a745"
        },
        "dot_color": "dot-color-#28a745",
        "url": "../transact/livedata?controllerid=7204",
        "zoomLevel": 22
    },
    {
        "title": "US-2 (PANEL-2)(Offline beyond 7 days)",
        "latitude": 34.03,
        "longitude": -84.65,
        "circleTemplate": {
            "fill": "#7e7b7b"
        },
        "dot_color": "dot-color-#7e7b7b",
        "url": "../transact/livedata?controllerid=5",
        "zoomLevel": 23
    }]

**Comment by devimaruthi** [comment]
![image](https://github.com/amcharts/amcharts5/assets/98639787/e7446d36-ee30-45ea-9b79-4c847b8d1c59)

**Comment by devimaruthi** [comment]
issue resolved
