### ISSUE TITLE
Legend Box 

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1032]
I want to customization in the legend.

1) I don't want that legend box/container.

2) I want to remove the space, marked with red in the image. As I am displaying multiple charts so space is an important factor.

Image:
![image](https://github.com/amcharts/amcharts5/assets/137867461/860ab7ae-84ca-46eb-8145-d97499e55c62)

Code for legend: 

```JavaScript
      var valueLegend = mainPanel.plotContainer.children.push(
          am5stock.StockLegend.new(root, {
            stockChart: stockChart,
            layout: am5.GridLayout.new(root, {
              maxColumns: 1,
              fixedWidthGrid: false,
            }),
          })
        ); 
    valueLegend.markers.template.setAll({
      width: 5,
      height: 5,
    });

    valueLegend.labels.template.setAll({
      fontSize: 10,
      fontWeight: "500",
    });

    valueLegend.valueLabels.template.setAll({
      fontSize: 10,
      fontWeight: "300",
    });

    setValueLegendData(valueLegend);
```

**Comment by zeroin** [comment]
I think the easiest way to do this would be to create a custom theme and override things set in StockChartDefaultTheme, for example:

```
const myTheme = am5.Theme.new(root);

myTheme.rule("RoundedRectangle", ["legend", "itemcontainer", "background", "stocklegend"]).setAll({
   fillOpacity: 0
});

myTheme.rule("Container", ["legend", "itemcontainer", "stocklegend"]).setAll({
   paddingRight:0,
   paddingTop:0,
   paddingBottom:0,
   paddingLeft:0
});

root.setThemes([
  am5themes_Animated.new(root),
  myTheme
]);
```

https://codepen.io/team/amcharts/pen/GRwzpXd/f5a97bb37034fbae07a0bbbd48bd3905?editors=1010

**Comment by workingbuddy10** [comment]
Thanks that box removal part worked, but still there is a change left.
Like removal of the space. Marked in the red circle. 
@zeroin 
![image](https://github.com/amcharts/amcharts5/assets/137867461/d7ff41ff-434e-43fb-9e95-a198d6426399)

**Comment by zeroin** [comment]
The space is added because labels, icons have padding. You can either modify padding for all elements or simply set some negative paddingTop for your itemContainer.

**Comment by workingbuddy10** [comment]
Can you update this in the below codepen link? And secondly I want to get the line between the chart and the  Y-axis as by this the chart looks neatly , like shown in the image below.
https://codepen.io/team/amcharts/pen/GRwzpXd/f5a97bb37034fbae07a0bbbd48bd3905?editors=1010

Image:
![image](https://github.com/amcharts/amcharts5/assets/137867461/d34aa9ae-9c82-43d3-b701-3742e047283e)

**Comment by workingbuddy10** [comment]
Thanks it worked.
