### ISSUE TITLE
Tooltip on small duration values in Gantt Charts

### ISSUE THREAD

**Issue by federicobohn-cs** [amcharts/amcharts5#1033]
**Question**

I'm working on a gantt chart based on https://www.amcharts.com/demos/gantt-chart/. There are some cases that this chart has many small duration values (in order of seconds).
Im having some trouble to display tooltips for these small duration values, we have to zoom in chart to be able to see tooltip for these kind of durations. It works good with bigger duration values.
is there a way to display tooltips on small duration values?

Here there is the code https://codepen.io/federico-bohn/pen/RwqEXpE.

Provide details about your development environment where you think it might be useful:
 - amCharts version 5

**Comment by federicobohn-cs** [comment]
Thanks for answer my question @zeroin!! It works, but if the right portion of a bar is not displayed on chart, we are not able to see tooltips, right?
In the example, the first image display whole bar and we can see tooltip:
![image](https://github.com/amcharts/amcharts5/assets/131985156/44a3c32b-a110-4f9b-8a0a-15ac03bc041b)

On the other hand the second image, the right portion of bar is outside of chart and tooltips is not displayed.
![image](https://github.com/amcharts/amcharts5/assets/131985156/f4f39bab-d9cf-43d1-a34c-a313a8229d56)

**Comment by martynasma** [comment]
Unfortunately, there's no way to display a tooltip if the column is mostly outside of the plot area.

**Comment by federicobohn-cs** [comment]
Thanks @martynasma. So, is that a missing feature or a bug? or which another alternative can be use to display a tooltip in this case? Thanks in advance.

**Comment by federicobohn-cs** [comment]
@martynasma Thanks! Yes,`strokeWidth` prop helped a lot with small duration bars.
