### ISSUE TITLE
Can I use amcharts5 on a commercial site?

### ISSUE THREAD

**Issue by Simeuilyang** [amcharts/amcharts5#1034]
**Question**

hi, 

Can I use free amchart5 on a commercial site?

Will it just show amchart logo? Are there other restrictions?

I checked it is available in amcharts4 Git repository issue. I want to know if amcharts5 is the same.

**Environment (if applicable)**

-

**Additional context**

-

**Comment by martynasma** [comment]
Yes, you're welcome to use amCharts 5 for a commercial site, as long as the branding logo is visible.
