### ISSUE TITLE
Can we implement Target line in stacked bar chart?

### ISSUE THREAD

**Issue by padfoot044** [amcharts/amcharts5#1035]
amChart version: 5
angular version: 12

![image](https://github.com/amcharts/amcharts5/assets/55396959/3e48ee24-8b81-4be6-bf53-6f2331932184)

like this

**Comment by martynasma** [comment]
Yes, you can use axis ranges for that:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/axis-ranges/

**Comment by padfoot044** [comment]
Thanks, I got it

**Comment by padfoot044** [comment]
How can we show that target string in right side?
is there are any property?

**Comment by martynasma** [comment]
Please refer to this tutorial:
https://www.amcharts.com/docs/v5/tutorials/aligning-axis-range-labels/

**Comment by padfoot044** [comment]
@martynasma Can we implement same target line in pieChart?

**Comment by martynasma** [comment]
> @martynasma Can we implement same target line in pieChart?

No, but I suggest checking out [Radar Chart](https://www.amcharts.com/docs/v5/charts/radar-chart/).

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.
