### ISSUE TITLE
Y-axis border

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1036]
To get the neat and clean look of  stock chart and according to my usecase I want to add a line between the chart and the Y-axis, like the in the given image. As this feature is in-built in e-charts library. So I am hoping any possible way to get it in amcharts5.

![image](https://github.com/amcharts/amcharts5/assets/137867461/9b29a2f1-669a-4750-9fcf-cab2ac742328)

**Comment by martynasma** [comment]
Please refer to this tutorial, on how to enable the axis line:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#axis-line
