### ISSUE TITLE
Rendering multiple amcharts xy charts in angular

### ISSUE THREAD

**Issue by NandaNxD** [amcharts/amcharts5#1038]
Im trying to render 40-50 charts using amcharts xy chart, in a single page. 
Its rendering slowly.. If the number of charts is like 10-12 its pretty fast,
But when number exceeds this the rendering becomes slow.
I came across an article daisy chaining or something, telling that its trying to render all charts together so its slow.
Is there any possibilty to speed up rendering?

Please help me out

**Comment by martynasma** [comment]
40-50 simple charts should render OK. If it's super slow it means those are more complex charts.

In such case you should probably consider implementing some kind of delayed rendering. E.g. render the chart only when it's actually required, or scrolled into view.

Another option is to implement daisy chain of rendering. E.g. have a list of charts to render, than iterate through the list, and launch rendering with a fraction of second delay.

I'm afraid there are no such bult-in tools, so you'll need to implement that in your app.

**Comment by NandaNxD** [comment]
How could we implement daisy chain of rendering?If you could give some hint it would be very helpful..

**Comment by martynasma** [comment]
Please refer to this tutorial:
https://www.amcharts.com/docs/v5/tutorials/daisy-chain-multiple-chart-rendering/

**Comment by NandaNxD** [comment]
Thankyou very much 😃
