### ISSUE TITLE
Hovering and displaying data value on legend issue

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1039]
Maybe it's a bug or something that on **Some** points while hovering the legend doesn't show its values. Though the data of that point is fine still.

Image 1 (the data value is not showing in the legend ):
![image](https://github.com/amcharts/amcharts5/assets/137867461/7662b8bb-4396-41ad-8809-c446f4aa2429)

Image 2 (the data point just before the above image showing the value):
![image](https://github.com/amcharts/amcharts5/assets/137867461/e8560407-a2f4-4f16-8145-2a811e291eeb)

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
