### ISSUE TITLE
Amcharts 5 question for performance of multiple chats in one page

### ISSUE THREAD

**Issue by hpeevmb** [amcharts/amcharts5#1040]
Hello,

Using `amcharts/amcharts5: 5.3.11` we are rendering multiple `am5xy.XYChart` with 4 `am5xy.CategoryAxis` and 1 `am5xy.ValueAxis` on each chart. On each chart we plot multiple (4-5), not very big `am5xy.ColumnSeries`.
In each bar we put `am5.Bullet.new` showing a number.

```
  series.bullets.push(function (root, series, dataItem: any) {
    return am5.Bullet.new(root, {
      sprite: am5.Label.new(root, {
        text: dataItem.dataContext[valueField],
        fill: root.interfaceColors.get('alternativeText'),
        centerY: am5.p50,
        centerX: am5.p50,
        populateText: true,
        fontSize: '0.8em',
      }),
    })
  })
```

On one page we can have 10-12 of these charts showing different datasets that update each second.
The data is relatively different on each update, so we are forced to redraw the whole graph every time.
We are doing this by removing and adding from chart.series

If we have 3-4 charts open the performance and feel of the page is good. But if we open more, for example 10-12, the page becomes slow and unresponsive on user actions. The CPU usage is close to 100% almost all the time.

We disabled animations by not using animated theme.

In the [performance](https://www.amcharts.com/docs/v4/concepts/performance/) page of amcharts4, there is section for Lazy_loading_charts. There as an option `am4core.options.onlyShowOnViewport = true;` As far as I understand the idea is to re-draw the chart only it is in the active view port of the screen. This sounds to be readable, however I can't find this option in amcharts5. Was it deprecated or it is the default behaviour?

In the same page there is section for `Creating a deferred chart instance`. Do you think it is suitable for our use case?

Do you have any other suggestions or technics that can used for keeping the page usable?

Thank you!

**N.B.**
We found google chrome settings that dramatically improved the CPU usage, because they offload the rendering to the GPU. This helped a lot but still when we open 10 charts CPU is raised to 100%

<img width="777" alt="image" src="https://github.com/amcharts/amcharts5/assets/37016327/09c0cd5b-3955-4208-90ff-4b3d4f699ed6">

**Comment by martynasma** [comment]
> In the [performance](https://www.amcharts.com/docs/v4/concepts/performance/) page of amcharts4, there is section for Lazy_loading_charts. There as an option am4core.options.onlyShowOnViewport = true; As far as I understand the idea is to re-draw the chart only it is in the active view port of the screen. This sounds to be readable, however I can't find this option in amcharts5. Was it deprecated or it is the default behaviour?

Neither lazy-loading nor deferred loads are included in amCharts 5, because it's much more faster than amCharts 4, and generally should not need any of these techniques.

That being said, maybe you will find daisy-chain approach useful:
https://www.amcharts.com/docs/v5/tutorials/daisy-chain-multiple-chart-rendering/
