### ISSUE TITLE
chartcontrols styling

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1042]
The indicator tools dropdown shifts from left to right on every click.
One time the dropdown goes in left and then next time it goes in right.

one time its left :
![image](https://github.com/amcharts/amcharts5/assets/137867461/7981326a-7b18-40e8-ad73-e2a80497c815)

second time on right:
![image](https://github.com/amcharts/amcharts5/assets/137867461/0ba96342-6cb0-4ca7-872f-c5dcd1cdfa64)

Code for my custom theme: 
`
         
    const mytheme = am5.Theme.new(root);
    mytheme
      .rule("RoundedRectangle", [
        "legend",
        "itemcontainer",
        "background",
        "stocklegend",
      ])
      .setAll({
        fillOpacity: 0,
      });
    mytheme.rule("AxisTick").setAll({
      stroke: am5.color(0xffffff),
      visible: true,
    });
    mytheme
      .rule("Container", ["legend", "itemcontainer", "stocklegend"])
      .setAll({
        paddingRight: 0,
        paddingTop: -20,
        paddingBottom: 17,
        paddingLeft: -10,
      });

    root.setThemes([
      am5themes_Animated.new(root),
      mytheme,
      am5themes_Dark.new(root),
    ]);

`

code of chartcontrol styling: 

`
           id={"chartcontrols" + props.index}
            style={{
              fontSize: "10px",
              padding: "2px",
              maxHeight: "20px",
            }}
`

**Comment by martynasma** [comment]
I don't see how this theme can affect stock toolbar controls. Do you perhaps have a runnable demo?

**Comment by workingbuddy10** [comment]
Sorry actually I cannot provide you the whole runnable code, but can you tell from where I can change/access styling for the popup.

And one more thing, if I add all the toolbar like PeriodSelector, DateRangeSelector etc, then this issue doesn't come. Whenever I am putting only one of the tool bar then its showing this issue. 
And this is not limited to indicators, if I **_only_** put series switcher then too its popup going left and right.

Can you tell me any possible way to handle this situation. Or is it a bug?

**Comment by martynasma** [comment]
I'm sorry, but we cannot figure this out without seeing your setup.

If you do have a support subscription, you can contact us privately at contact@amcharts.com
