### ISSUE TITLE
display xAxes values when using endLocation

### ISSUE THREAD

**Issue by AAJeck** [amcharts/amcharts5#1045]
Hi guys
I'm looking for a way to display a chart like the one attached.
We must display the area right next to the data and it must be visible all the way.
After adding endLocation, it works almost fine, but it does not display values in the x axis. 

> xAxis = this.mainPanel.xAxes.push(am5xy.GaplessDateAxis.new(_root, {
            baseInterval: {\n
                timeUnit: span,
                count: 1
            },
            endLocation:30,            
            renderer: am5xy.AxisRendererX.new(_root, {
            }),
            tooltip: am5.Tooltip.new(_root, {})
        }));

As a result, I need to display future points without removing values (time) from the x axis.
A kind of merge between images 1 and 2.

![Screen Shot 2023-08-10 at 11 19 41](https://github.com/amcharts/amcharts5/assets/127954053/c5a67ff8-9ce4-4999-b4a0-0c73efe978ce)

![Screen Shot 2023-08-10 at 11 32 29](https://github.com/amcharts/amcharts5/assets/127954053/953985f2-a208-4eeb-b6cc-3e9ab2340864)

**Comment by martynasma** [comment]
If you need to extend axis scale to specific date, you can use `max` setting of the axis.

Or you can use `extraMax` to relatively expand the scale.

More in docs:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#axis-date-scope

**Comment by AAJeck** [comment]
Both of the solutions don't work for me.

**Comment by martynasma** [comment]
Would you care to explain why? :)
