### ISSUE TITLE
Aligning the position of labels along the X axis

### ISSUE THREAD

**Issue by roman-gorkunenko** [amcharts/amcharts5#1047]
Hello. Can you please tell me what is the way to align the grid so that it does not become negative on the left? I found such a way. Are there any methods to determine the current position of the first label? Only the first label has a negative value, I thought that the entire container should have a negative value.

![iScreen Shoter - Google Chrome - 230810232415](https://github.com/amcharts/amcharts5/assets/91733660/31e807f7-db39-41a7-9c95-74a599046610)

**Comment by martynasma** [comment]
The following adapter will shift the very first label to the right:

```JavaScript
xAxis.get("renderer").labels.template.adapters.add("centerX", function(position, target) {
  if (xAxis.valueToPosition(target.dataItem.get("value")) === 0) {
    return 0
  }
  return position;
})
```

However, it comes at the risk of labels overlapping.

**Comment by roman-gorkunenko** [comment]
I thought that the shift of the first label would move all the other labels as well. But your code doesn't work for me.
Here is an example

https://codepen.io/Roman-Gorkunenko-the-flexboxer/pen/jOQEVwr

The video shows how the labels move when resizing https://www.dropbox.com/scl/fi/qk6s7p2vdy6zhaapy4bt5/chrome_8byMKfvWvx.mp4?dl=0&rlkey=b3hv9qecj8i6it1h7fk18x52v they should also be aligned in the middle of the column.
I did not set minGridDistance because in this case the labels will overlap each other
Is this a bug or is it possible to align labels in the middle of their columns while hiding other labels so that they don't overlap?

**Comment by martynasma** [comment]
If it's about all the labels, please refer to this doc:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#location-of-axis-elements

**Comment by roman-gorkunenko** [comment]
I already looked there
added these properties here https://codepen.io/Roman-Gorkunenko-the-flexboxer/pen/jOQEVwr 
minGridDistance - not suitable since labels will collapse
centerX, centerY - jumps to the left anyway
with minPosition: 0.1, maxPosition: 0.9 there are no label jumps to zero, because the first label is hidden,
![image](https://github.com/amcharts/amcharts5/assets/91733660/5e2fb854-c741-433b-b194-c868e5c306ab)
but in this case the labels are not in the middle
![image](https://github.com/amcharts/amcharts5/assets/91733660/fc1b9bdb-ac22-4574-a950-f9ab4e6d81dc)

What other properties can be used?

**Comment by martynasma** [comment]
You're looking for this:

```JavaScript
var xRenderer = xAxis.get("renderer");
xRenderer.ticks.template.setAll({
  location: 0.5,
  multiLocation: 0,
  visible: true
});
```

**Comment by roman-gorkunenko** [comment]
Thanks a lot
Everything is fine on the x-axis
Can you suggest how it is possible to make the labels on top of each other on the Y axis if oversizedBehavior: 'wrap'
Here is a video that can be clearly seen when resize:
https://github.com/amcharts/amcharts5/assets/91733660/bf7b216c-130a-4eca-8b43-7088b60b03ed

Here is an example chart on codepen:
https://codepen.io/Roman-Gorkunenko-the-flexboxer/pen/jOQEVwr

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.

**Comment by roman-gorkunenko** [comment]
Thanks a lot
