### ISSUE TITLE
Overlap labels on y-axis if oversizedBehavior: wrap

### ISSUE THREAD

**Issue by roman-gorkunenko** [amcharts/amcharts5#1049]
Hello. Can you suggest how it is possible to make the labels on top of each other on the Y axis not overlap if oversizedBehavior: 'wrap'
Here is a video that can be seen when resize:
https://github.com/amcharts/amcharts5/assets/91733660/bf7b216c-130a-4eca-8b43-7088b60b03ed

Here is an example chart on codepen:
https://codepen.io/Roman-Gorkunenko-the-flexboxer/pen/jOQEVwr

**Comment by martynasma** [comment]
There's no label overlap check going on in axis.

The only way to ensure that labels do not overlap, is to apply a generous [`minGridDIstance`](https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#grid-density), which would make axis skip some labels when they're too close to each other.

**Comment by roman-gorkunenko** [comment]
Thanks a lot
