### ISSUE TITLE
Tooltip cropped when canvas too small

### ISSUE THREAD

**Issue by aniznik1** [amcharts/amcharts5#105]
https://codepen.io/aniznik/pen/GRMRYRo

When hovering over a datapoint, the tooltip will be displayed only inside the canvas element, thus cropping it.

Is it possible to define the tooltip container outside to not make it crop inside the canvas element?

**Comment by martynasma** [comment]
> Is it possible to define the tooltip container outside to not make it crop inside the canvas element?

No, I'm afraid.
