### ISSUE TITLE
Date Axis tooltop value not correct for the 5 min period

### ISSUE THREAD

**Issue by KaskoYurii** [amcharts/amcharts5#1051]
**Question**

Hi! 

I have a column chart in Am5. 
I've used a `DateAxis`

> am5xy.DateAxis.new(root, {
>                     
>                     maxDeviation: 0,
>                     baseInterval: {
>                         timeUnit: 'minute',
>                         count: 5,
>                     },
>                     renderer: xRenderer,
>                     tooltip: am5.Tooltip.new(root, {}),
>                 }),

In case when I've got, for example, a range from 15:00 to 15:05, I've got one column with the highest item, but the tooltip value shows me only the last item from this range, but not the same that chart selected for showing.

data example : 

> data:  [
>     
>   { category: "2023-08-16 15:00", value: 2 },
>   { category: "2023-08-16 15:01", value: 3 },
>   { category: "2023-08-16 15:02", value: 2 },
>   { category: "2023-08-16 15:03", value: 4 }, <-- for this one will be showed column 
>   { category: "2023-08-16 15:04", value: 2 }, <-- this value will be showed in tooltip
>   { category: "2023-08-16 15:05", value: 7 }
>  ];

Of course my category value for the chart is formatted as 1692189240000

Here is an example: https://codepen.io/Bubble_gum/pen/oNJvroq

**Comment by martynasma** [comment]
The `baseInterval` in `DateAxis` settings should represent correct data granularity. In this case it is one minute, not five.

If you need to display a single column per 5 minutes, you should use data grouping instead:

```JavaScript
let xAxis = chart.xAxes.push(
  am5xy.DateAxis.new(root, {
    groupData: true,
    groupCount: 5,
    groupInterval: { timeUnit: "minute", count: 5 },
    groupIntervals: [{ timeUnit: "minute", count: 5 }],
    baseInterval: { timeUnit: "minute", count: 1 },
    renderer: am5xy.AxisRendererX.new(root, {})
  })
);

// ...
  var series = chart.series.push(
    am5xy.ColumnSeries.new(root, {
      name: "Series",
      xAxis: xAxis,
      yAxis: yAxis,
      valueYField: "value",
      valueXField: "date",
      valueYGrouped: "high",
      tooltip: am5.Tooltip.new(root, {
        labelText: "{valueY}"
      }),
      fill: am5.color("#6C95FF"),
      stroke: am5.color("#6C95FF")
    })
  );
```

Please note that you can control which value to use via `valueYGrouped` setting:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#aggregation-function

**Comment by martynasma** [comment]
CodePen:
https://codepen.io/team/amcharts/pen/vYvYgzV/c220cb34f5c4cb181ee3bf8122972bb8?editors=0010

**Comment by KaskoYurii** [comment]
Oh, thx! 
So if I have dynamic ranges, do I need to describe all cases for each unit? 
`const ranges = [
                {
                    unit: 'millisecond',
                    counts: [10, 50, 100, 500],
                },
                {
                    unit: 'second',
                    counts: [1, 5, 15, 30],
                },
                {
                    unit: 'minute',
                    counts: [1, 5, 15, 30],
                },
                {
                    unit: 'hour',
                    counts: [1, 3, 12],
                },
                {
                    unit: 'day',
                    counts: [1, 7, 30, 90, 365],
                },
            ]`
