### ISSUE TITLE
Tooltip is not working when using DateAxis

### ISSUE THREAD

**Issue by chunlampang** [amcharts/amcharts5#1052]
**Bug description**
Tooltip is not working when using DateAxis and the data is not sorted ascending by the date field.

https://codepen.io/ChazUK/pen/MWzgLrQ

**Comment by martynasma** [comment]
Your data is going backwards. The needs to be sorted in ascending order for proper behavior.

**Comment by chunlampang** [comment]
I think there should be a warning/error console or just display the tooltip anyway.

**Comment by martynasma** [comment]
It is mentioned a number of times in docs:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#Data_order
https://www.amcharts.com/docs/v5/concepts/data/#Data_order

Checking the data from integrity is a large unnecessary performance overhead. It's best to pre-sort your data, now that you know about this requirement :)
