### ISSUE TITLE
 Working on persian date type

### ISSUE THREAD

**Issue by mohammadhasananisi** [amcharts/amcharts5#1054]
Hello, how can I use solar date?

in stock chart

**Comment by zeroin** [comment]
I am afraid we do not support this, sorry.

**Comment by mohammadhasananisi** [comment]
But I fixed it

**Comment by mohammadhasananisi** [comment]
> I am afraid we do not support this, sorry.

But I fixed it

**Comment by zeroin** [comment]
Great then :)
