### ISSUE TITLE
Combine Clustered and Layered column chart?

### ISSUE THREAD

**Issue by pmatatias** [amcharts/amcharts5#1057]
First of all, thanks for the awesome chart

**Question**
### Is it possible to combine `Clustered` and `Layered` column chart?

I know we can combine `Clustered` and `Stacked` , but I want the second series also start from zero, not like `Stacked` the next series will start from the end of first value.

- for example, I have data like:
```
var data = [{
  "category": "YTD",
  "targetA": 3.5,
  "actualA": 4.2
}, {
  "category": "MTD",
  "targetA": 1.7,
  "actualA": 3.1
}, {
  "category": "WTD",
  "targetA": 2.8,
  "actualA": 2.9
}];
```
the chart will be:  
![image](https://github.com/amcharts/amcharts5/assets/33835308/9174231b-f1c7-4923-a6a8-34845f148122)

- What I want to achive is when i have more data in one category :
```
var data = [{
  "category": "YTD",
  "targetA": 3.5,
  "actualA": 4.2,
  "targetB": 3.5,
  "actualB": 4.2
}, {
  "category": "MTD",
  "targetA": 1.7,
  "actualA": 3.1,
  "targetB": 1.7,
  "actualB": 3.1
}, {
  "category": "WTD",
  "targetA": 2.8,
  "actualA": 2.9,
  "targetB": 2.8,
  "actualB": 2.9
}];
```
result: all the series was `Stacked` in the center. is it posibble to make it clustered ? 

> I expect `actualB` and `targetB` are `Layered` like `Series A`

![image](https://github.com/amcharts/amcharts5/assets/33835308/50fa9f5a-18ba-4eb4-8f21-c76ee2bab2f9)

demo codepen : https://codepen.io/pmatatias/pen/VwqYPQy?editors=0010\

Thank in advance 😄

**Comment by zeroin** [comment]
Do you mean something like this?
https://codepen.io/team/amcharts/pen/abPzyYK/6030ccca80f791f0363c4c4ad2a10edd?editors=0010

**Comment by pmatatias** [comment]
> Do you mean something like this? https://codepen.io/team/amcharts/pen/abPzyYK/6030ccca80f791f0363c4c4ad2a10edd?editors=0010
in my codepen before, `targetB` and `actualB` was separated between `Series A`. 
I want to group it like below.  Is it possible?

![image](https://github.com/amcharts/amcharts5/assets/33835308/92bc441f-3418-494b-bae9-f7f4349814c7)

**Comment by zeroin** [comment]
In this case I would set target value to the target-actual value and make target stack on actual.

**Comment by pmatatias** [comment]
yes, at first, I thought to use `Stacked`, but in some cases, the actual value is bigger than the target.
which means: `target-actual` is negative, and the target should be rendered lower than the actual column

that's why I'm looking for a method to draw a column chart from below.

**Comment by zeroin** [comment]
I think the only way to achieve this would be to add another xAxis (you can make it invisible) and add two of the series to this separate x axis.

**Comment by pmatatias** [comment]
@zeroin Thank you for your suggestions. Maybe I'll try it later.

**Comment by pmatatias** [comment]
Currently, I just try to explore another method. 
and I end up with [Grouped and Sorted Columns](https://www.amcharts.com/demos/grouped-and-sorted-columns/)

after some modification, I can get this result. 

Code Pen : https://codepen.io/pmatatias/pen/JjwoaQw?editors=0011


![image](https://github.com/amcharts/amcharts5/assets/33835308/65b87420-3e41-4c3c-bcd4-c35111d741b4)


###  I'm not sure this is the best approach. I'll try your suggestion by adding another `xAxis` later.

again, thank you for your help. 😄
