### ISSUE TITLE
animated bullet out of memory error

### ISSUE THREAD

**Issue by jaimelama2112** [amcharts/amcharts5#1059]
**Bug description**
im using this chart https://www.amcharts.com/demos/animated-bullet-at-the-end-of-the-series/ and the animated bullet accumulates memory when i check in the task administrator for chrome , this only happens when im looking at the chart because when i go into another app and then come back to the chart the memory resets. if you keep the chart open in chrome for a long time youll get the out of memory error. im using amchart5 latest version as of today. If you check the example in your url i just gave you it has the same memory increase problem

**Comment by zubairv85** [comment]
@jaimelama2112 My team experienced the same issue over the past 2 days and it looks to be a Chrome bug related to garbage collection. Upgrading Chrome to the latest version fixed it for us.
