### ISSUE TITLE
Can we change the color of plus and minus buttons of zoomControl ?

### ISSUE THREAD

**Issue by devimaruthi** [amcharts/amcharts5#1061]
I want to change the color of plus and minus buttons of zoomControl class to grey. Now they are in blue color. How can i do that?For vanilla JavaScript examples use:
CodePen (https://codepen.io/)
jsFiddle (https://jsfiddle.net/)

For TypeScript/Angular/React use:
CodeSandbox (https://codesandbox.io/)
StackBlitz (https://stackblitz.com/).
-->

**Environment (if applicable)**

**Additional context**

**Comment by xorspark** [comment]
The buttons are stored in [the `minusButton` and `plusButton` properties](https://www.amcharts.com/docs/v5/charts/map-chart/map-pan-zoom/#Configuring_buttons) in the zoomControl object. They're both Button instances, so you can get the background setting and make the appropriate changes ([docs](https://www.amcharts.com/docs/v5/concepts/common-elements/buttons/#Body_background))

```
zoomControl.plusButton.get('background').setAll({
  // ...
})
```

The hover color can be changed by doing the  same thing on the button's hover state ([docs](https://www.amcharts.com/docs/v5/concepts/common-elements/buttons/#States))

**Comment by devimaruthi** [comment]
@xorspark thanks that helped
