### ISSUE TITLE
How to access dataItem and dataContext of aCircle object

### ISSUE THREAD

**Issue by devimaruthi** [amcharts/amcharts5#1063]
I want to access to the Circle object dataItem and dataContext to see what is the color of circle. If color is equal to say "grey color" I want to create one more outer circle for all grey circles and wants to animate the outer circle. I have used adapter fill function to do that. In the adapter function only I can able to access to the particular circle dataIetm and dataContext But my page is showing out of memory because of the animations in adapter function. I have tried to access the dataItem and dataContext with the conatiner but undefined is coming.

![image](https://github.com/amcharts/amcharts5/assets/98639787/55bfd0f7-1ead-4a8f-b774-69547cf5c39b)
  

**Question**

**Environment (if applicable)**

**Additional context**

**Comment by devimaruthi** [comment]
https://codepen.io/pen?editors=1111 My complete code. Even though there is no data set to the series. I am observing one point near to South Africa. Why is that point coming?

**Comment by martynasma** [comment]
The code does not seem right.

You should never create elements in an adapter. It might get called a lot of times, and your code will be creating elements every time.

Instead, I suggest creating whatever extra elements you need in the bullet function. It receives a data item as a third parameter:

```JavaScript
series.bullets.push(function(root, series, dataItem) {
  // ...
});
```

**Comment by devimaruthi** [comment]
@martynasma I want to divide my circles and add animations only to some circles based on the color. I can't able to access to fill to divide circles circle.get('fill') is giving me undefined.

**Comment by martynasma** [comment]
I understand. The bullet function is called for each bullet individually, so you can have a code that creates bullets based on the data item (passed as a third parameter).

**Comment by devimaruthi** [comment]
@martynasma Can you give me an example code or  from documentation where dataItem is getting pushed into bullets list when Circles objects are created on top of Container objects in Map Point Series. In documentation of Mapchart I did not found this implementation

**Comment by martynasma** [comment]
```JavaScript
pointSeries.bullets.push(function(root, series, dataItem) {
  var color = dataItem.dataContext.color;
  return am5.Bullet.new(root, {
    sprite: am5.Circle.new(root, {
      radius: 5,
      fill: color
    })
  });
});
```

**Comment by devimaruthi** [comment]
@martynasma That worked magically. Thanks for the help!

**Comment by mehdi112357** [comment]
@martynasma Thanks a lot. it works for me
