### ISSUE TITLE
Out of memory is coming for animations created using adapter function after every 3 mins 

### ISSUE THREAD

**Issue by devimaruthi** [amcharts/amcharts5#1064]
In MapPointSeries Out of 1800 circles I want to choose circle which is having grey color and add outer circle to it. I want to animate outer circle. Now I have done it using adapter function. because I can't able to get the value for the fill of the circle and see whether it is equal to grey or not. From then after every 3minutes out of memory is coming in webpage instead of displaying map.

**Question**

**Environment (if applicable)**

**Additional context**

![image](https://github.com/amcharts/amcharts5/assets/98639787/25b8752f-2f54-45e5-b17a-0720222baef1)

**Comment by martynasma** [comment]
This seems like an issue with the code. Please refer to [this reply](https://github.com/amcharts/amcharts5/issues/1063#issuecomment-1690499981).

**Comment by devimaruthi** [comment]
Completed and close
