### ISSUE TITLE
How to change the color of +, - of ZoomControl plusbutton and minusbutton respectively

### ISSUE THREAD

**Issue by devimaruthi** [amcharts/amcharts5#1066]
I want to change the color of + and - of zoom in and out buttons to black color and when clicked I want to change the color to grey

**Question**

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
E.g.:

```JavaScript
zoomControl.minusButton.setAll({
  stroke: am5.color(0xff0000)
});

zoomControl.minusButton.get("background").setAll({
  stroke: am5.color(0xff0000),
  fill: am5.color(0x00ff00)
});
```

**Comment by devimaruthi** [comment]
@martynasma the buttons background to be in grey color and + and - Labels has to be in black color

**Comment by martynasma** [comment]
You can use any color. Just update color codes in the above snippet.

**Comment by anoop-mobi** [comment]
This One Will Work IF you are using amChart 5

https://stackoverflow.com/a/77993360/23284882
