### ISSUE TITLE
jDate

### ISSUE THREAD

**Issue by mohammadhasananisi** [amcharts/amcharts5#1067]
hi.

how to use jDate in this chart?

this is example in amchart 3 

https://github.com/amcharts/amcharts3/issues/181

**Comment by martynasma** [comment]
amCharts does not support Persian dates.

You would need to use an adapter on whatever date-based labels you need to convert to Persian date, then your or a third party library to convert the dates.

E.g.:

```JavaScript
xAxis.get("renderer").labels.template.adapters.add("text", function(text, target) {
  if (target.dataItem) {
    var date = new Date(target.dataItem.get("value"));
    // convert `date` to a Persian date
    return text;
  }
  return text;
});
```

**Comment by mohammadhasananisi** [comment]
Thank you
