### ISSUE TITLE
Drawing Tool

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1068]
Actually I am working on saving the workspace in the amcharts5.

 So I just wanted to know, how can we save the drawing of the charts? Like what exactly  what element/variable/function of amcharts we have to save in the backend so that chart drawing is getting saved too or how can I access it.
 
And also How to get the data like on which the chart drawing is plotted.

**Comment by xorspark** [comment]
This section shows how to access and load an annotation object: https://www.amcharts.com/docs/v5/concepts/exporting/annotator/#Pre_loading_annotations
