### ISSUE TITLE
how to disabled the click events in amcharts 5 pie chart for legend items

### ISSUE THREAD

**Issue by kirannarwade** [amcharts/amcharts5#1069]
![Screenshot from 2023-08-25 17-59-56](https://github.com/amcharts/amcharts5/assets/90048456/7028a387-cc79-4a8d-8584-ee85c5273b21)

**Comment by xorspark** [comment]
You can set `clickTarget` to `"none"` to disable toggling: https://www.amcharts.com/docs/v5/concepts/legend/#disabling-toggling
