### ISSUE TITLE
polygonSeries.mapPolygons conditional coloring

### ISSUE THREAD

**Issue by barrygwhite** [amcharts/amcharts5#107]
Hey, 
I'm trying to distinct countries with and without data. I know how to achive this in am4 but here I'm out of luck. 

Based on this example:  https://www.amcharts.com/demos/rotating-globe-with-circles/
I'm not sure how to set this properly: 
````
//map coloring, setAll?
polygonSeries.mapPolygons.template.setAll({
  fill: country_color,
  fillOpacity: 0.1,
  strokeWidth: 0.5,
  stroke: root.interfaceColors.get("background")
});

polygonSeries.events.on("datavalidated", function () {
  circleSeries.data.clear();

  for (var i = 0; i < data.length; i++) {
    var dataContext = data[i];
    var countryDataItem = polygonSeries.getDataItemById(dataContext.id);
    var countryPolygon = countryDataItem.get("mapPolygon");

    var value = dataContext.value;

    var radius = minRadius + maxRadius * (value - valueLow) / (valueHigh - valueLow);

//how can I change polygonSeries.mapPolygons after this?
    if (countryPolygon) {
      var geometry = am5map.getGeoCircle(countryPolygon.visualCentroid(), radius);
      circleSeries.data.push({
        name: dataContext.name,
        value: dataContext.value,
        polygonTemplate: dataContext.polygonTemplate,
        geometry: geometry
      });
    }
  }
})

````

**Comment by martynasma** [comment]
Why not use an adapter on the polygon template?

Something like this:

```JavaScript
circleSeries.mapPolygons.template.adapters.add("fill", function(fill, target) {
  if (target.dataItem) {
    return target.dataItem.dataContext.color;
  }
  return fill;
});
```

https://codepen.io/team/amcharts/pen/254bf2a642540ff790a6fff94fdb591e?editors=0010

**Comment by martynasma** [comment]
Or via templateField:

circleSeries.mapPolygons.template.set("templateField", "polygonSettings");

https://codepen.io/team/amcharts/pen/017c4cc114dd6b6d697943d7e56576ac?editors=0010

**Comment by barrygwhite** [comment]
But I would like to change the polygonSeries.mapPolygons.template.fill property conditionally (the map itself, background, not CircleSeries). For CircleSeries, I can pass the color in the chart data.

**Comment by martynasma** [comment]
Same thing. You can use either `templateField` or adapters on `polygonSeries.mapPolygons.template`.

**Comment by barrygwhite** [comment]
Got it, thanks.
