### ISSUE TITLE
How to apply tooltip to chart title?

### ISSUE THREAD

**Issue by diana-sandu-syntax** [amcharts/amcharts5#1070]
**Question**

I attempted to add a tooltip to a chart title made with Label, but the tooltip didn't seem to work. Here's what I tried: https://codepen.io/diana-sandu-fortech/pen/NWexXRE

Is there a way to add a tooltip to a chart title? 

Thank you

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
Please refer to the following documentation about how to make labels interactive:
https://www.amcharts.com/docs/v5/concepts/common-elements/labels/#labels-as-interactive-elements

**Comment by diana-sandu-syntax** [comment]
> Please refer to the following documentation about how to make labels interactive: https://www.amcharts.com/docs/v5/concepts/common-elements/labels/#labels-as-interactive-elements

Thank you! Adding a background to the label solved my issue.
