### ISSUE TITLE
cannot format pie chart raw value in tooltip

### ISSUE THREAD

**Issue by binaryartifex** [amcharts/amcharts5#1072]
for the life of me all i want to do is transform the raw number value of each pie slice into a preformatted text value to appear in a tooltip.  I have a similar implementation for my XY chart but the pie chart doesn't seem to have a tooltipDataItem...any help would be appreciated. 

The series is of type `am5percent.PieSeries`. basically if an optional transform is provided, the newly formatted label is provided, otherwise the default one is used.

```typescript
export function buildSeriesTooltip({
  chart,
  label,
  series,
  transform,
}: BuildSeriesTooltipArgs) {
  const tooltip = am5.Tooltip.new(chart.root, {
    autoTextColor: false,
    getFillFromSprite: false,
    getLabelFillFromSprite: true,
    getStrokeFromSprite: false,
    pointerOrientation: "horizontal",
    labelText: `[bold]{valuePercentTotal.formatNumber('0.00p')}[/] [#64748B]{category}[/] [#64748B]{value}[/]`,
  });

  tooltip.label.adapters.add("text", (value) => {
    const dataItem = series.get("tooltipDataItem")?.get("value");
    if (dataItem && transform) {
      return `[bold]{valuePercentTotal.formatNumber('0.00p')}[/] [#64748B]{category}[/] [#64748B]${transform(
        dataItem,
      )}[/]`;
    }
    return value;
  });

  return tooltip;
}
```

**Comment by martynasma** [comment]
Pardon for asking: What is a "raw number value"?

Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by binaryartifex** [comment]
@martynasma to use a snippet straight from the docs...

```typescript
var data = [{
  country: "France",
  sales: 100000
}, {
  country: "Spain",
  sales: 160000
}, {
  country: "United Kingdom",
  sales: 80001
}];
  })
);
```

im trying to create an adapter that allows me to format the 'sales' value within the hovered tooltip of a pie chart slice given the series passed into a factory function as above. i can't seem to figure out how to get the 'value' as is referenced in the labelText itself. the above example function i have is for an XY chart however 'tooltipDataItem' isn't available within the context of a pie chart so im a bit lost.

**Comment by martynasma** [comment]
Gotcha.

Why not use an adapter on slices?

```JavaScript
series.slices.adapters.add("tooltipText", (text, target) => {
  const value = target.dataItem.get("value");
  // ...
  return text;
});
```

**Comment by binaryartifex** [comment]
oh wow yeah nice. didnt even occur to me to use slices. one little issue though, although it works, typescript errors with the following. when i go to add a string to the get function, intellisense only allows for the 'visible' string constant to be passed.

```typescript
  series.slices.template.adapters.add("tooltipText", (text, target) => {
    const value = target.dataItem?.get("value"); // Argument of type '"value"' is not assignable to parameter of type '"visible"
    console.log(value); // correctly logs value
    return text;
  });
```

**Comment by martynasma** [comment]
Try `target: any` ;)

**Comment by binaryartifex** [comment]
such a reckless act of blasphemy will surely anger the typescript gods and bring upon me the wrath of the puritan typescript zealots.....but yeah ok, that'll work :)

**Comment by martynasma** [comment]
Ok, this will surely keep TS gods happy: `target: am5percent.IPieSeriesDataItem` ;)
