### ISSUE TITLE
The sticky tooltip has wrong position with zero Y value

### ISSUE THREAD

**Issue by itakartor** [amcharts/amcharts5#1073]
Hello everyone, i have created a XYChart with sticky tooltip on the bullets, when i try to set some of the dataset values to zero, in that moment the position of the tooltips are wrong. I had made the bug on a example that it is on the official documentation.

https://codepen.io/ITA-KARTOR/pen/gOZPVxe

The AmChart version is 5.4.5 that is the last one.

![image](https://github.com/amcharts/amcharts5/assets/58552414/295389d4-8522-49b7-bb8e-bb18d4356351)

**Comment by martynasma** [comment]
If you need to show tooltips on all bullets, I strongly suggest using `Tooltip` element as a bullet instead:

```JavaScript
series.bullets.push(function(root) {
  var tooltip = am5.Tooltip.new(root, {
    labelText: "{valueY}",
    pointerOrientation: "down",
    dy: -10,
    centerY: am5.p100
  });
  
  tooltip.get("background").setAll({
    fill: series.get("fill"),
    fillOpacity: 1
  });
   
  tooltip.show();
  
  return am5.Bullet.new(root, {
    sprite: tooltip
  });
});
```

It has a number of advantages:

1) It's better for performance.
2) It will move smoothly with the data item - no lagging behind.
3) Can be autohidden with `minBulletDistance`.
4) No issue with zero-value ;)

Example:
https://codepen.io/team/amcharts/pen/xxmZved/5c09800a65fb6d8a7b4ff14223d24bad?editors=0010

**Comment by itakartor** [comment]
ok, if i want to hide the tooltip manually or switch to hover version from always. What may i do ? Because if i try to access to the specific bullets of the dataItem, i can't do hide tooltip or call a method for hide the sticky tooltip.

**Comment by martynasma** [comment]
Do you mean you will want to toggle all tooltips on a live chart, or just specific ones?

**Comment by itakartor** [comment]
> Do you mean you will want to toggle all tooltips on a live chart, or just specific ones?

I would like to hide all sticky tooltip and show the normal tooltip and the other way round

**Comment by martynasma** [comment]
E.g.:

```JavaScript
function toggle() {
  am5.array.each(series.dataItems, function(dataItem) {
    am5.array.each(dataItem.bullets, function(bullet) {
      if (bullet.get("sprite").isType("Tooltip")) {
        var tooltip = bullet.get("sprite");
        if (tooltip.isVisible()) {
          tooltip.hide();
        }
        else {
          tooltip.show();
        }
      }
    })
  });
}
```

CodePen updated.

**Comment by itakartor** [comment]
It's a good function, but what do i have to do if i want set the bullets and over the tooltip?
For example, in this image there is a bullet over a label.
![image](https://github.com/amcharts/amcharts5/assets/58552414/5f1981af-43a6-43a4-9721-107aa280dc1b)

**Comment by itakartor** [comment]
if i change the bullets with the toggle function and set all data of a serie, then the serie reset the bullets with original form, but if i set the data and try to change the tooltip on the bullets, then the bullets are null. Which may be the problem?
