### ISSUE TITLE
Rounded corners on stacked xy chart with negative values

### ISSUE THREAD

**Issue by roman-gorkunenko** [amcharts/amcharts5#1075]
Hello. I found your example with rounded corners on column stacks https://www.amcharts.com/docs/v5/tutorials/adaptively-rounded-corners-on-mixed-column-stacks/ but this example doesn't work with negative values.
I tried to remake your example, but it doesn't work correctly https://codepen.io/Roman-Gorkunenko-the-flexboxer/pen/yLGOmBx
I get point and y value
Logically, the smaller the Y value - the higher column.
Then the top column should have its top corners rounded, and the bottom column should have its bottom corners rounded. If there are any columns in the middle, then we leave their corners straight. My function is working correctly, but for some reason the lower plot with negative values is not rounding correctly.
How can I get rounded corners on stacked xy chart with negative values?

**Comment by martynasma** [comment]
I'm afraid we do not have a ready-made example that would use negative values.

If you have a support subscription, please email us at contact@amcharts.com.

You're also welcome to take another stab ad modifying the demo code to suit the specific needs.

**Comment by martynasma** [comment]
We do have an example like that now:
https://codepen.io/team/amcharts/pen/rNoZxYe

Hope you find it useful.
