### ISSUE TITLE
Tick customization

### ISSUE THREAD

**Issue by intrvertmichael** [amcharts/amcharts5#1076]
**Question**

<img width="287" alt="Screenshot 2023-08-31 at 5 31 08 PM" src="https://github.com/amcharts/amcharts5/assets/45526432/32a048b2-50c1-491f-b5de-ba22db68accc">

is there a way to achieve this tick design with amcharts 5 pie chart ?
i was able to create the dashed tick with the correct width and color,
but I am not seeing a way to **bend the tick** or to **add a circle at the end of the line** in the chart
is this possible with this library ?

i have tried to add a graphic to the label but was not successful because it would appear inside of the label instead of on the tick. i looked at the [tick documentation](https://www.amcharts.com/docs/v5/charts/percent-charts/pie-chart/pie-series/#ticks) but could not find any specifics about how to achieve this.

**Comment by zeroin** [comment]
To add a circle, you can add bullet to a pie series. I don't see a simple way to make it bend like in your picture unless you write your own draw method for the tick which would do all the math and draw it like you want to.

**Comment by intrvertmichael** [comment]
thank you for the response @zeroin 🙏 
I was able to add the bullets successfully and will look further into the bent line
