### ISSUE TITLE
tooltip Clustered Bar Chart overlap in mobile

### ISSUE THREAD

**Issue by haivoi1107** [amcharts/amcharts5#1078]
**Bug description**
i use Clustered Bar Chart amcharts5 version ^5.2.26. 
When I open the phone device, I see an overlapping tooltip
![image](https://github.com/amcharts/amcharts5/assets/36144288/5dfded60-8eb0-4f31-ac4f-f4abf4b7b8fe)
https://codepen.io/hainc/pen/LYMRorL

**Environment (if applicable)**

**Additional context**

**Comment by zeroin** [comment]
You could combine tooltips into one to solve this:
https://www.amcharts.com/docs/v5/tutorials/combining-tooltip-values-from-multiple-series/

**Comment by haivoi1107** [comment]
> You could combine tooltips into one to solve this: https://www.amcharts.com/docs/v5/tutorials/combining-tooltip-values-from-multiple-series/

I'm required to separate each value with each tooltip, not combine them together, so I can't use this method :(

**Comment by zeroin** [comment]
Hm, I checked your pen on mobile and I see the tooltips overlap but only on first tap, all the others are fine, the tooltips are ok. I am not sure if we can fix this.

**Comment by haivoi1107** [comment]
If you can fix it, please let me know in this thread.
Thanks you
