### ISSUE TITLE
Format valueX and valueY in tooltios using Intl

### ISSUE THREAD

**Issue by zdm** [amcharts/amcharts5#1079]
Hi.
Is it possible to format `valueX` and `valueY` in tooltip using Intl?

I found this code snippet:
```
labelText: "[bold]{name}[/]\n{valueX.formatDate()}: {valueY}"
```

But seems there us currently no possibility to user Intl for tooltips?

**Comment by zdm** [comment]
I mean tooltips for series.
For axes it hass `tooltipNumberFormat`. setting.
It would be useful to have sane for series: `tooltipNumberFormatValueX`.

Or I am missed sometihng?

**Comment by martynasma** [comment]
You have two options:

1) Set `dateFormat` on a global `root.dateFormatter` to an Intl value. Then `{valuex.formatData()}` will use that format.

2) Use an adapter for tooltip contents.

**Comment by zdm** [comment]
I have two series.
They have different number formats ( bytes and percents ).
Need to have separated Intl formats,

**Comment by zdm** [comment]
For percent I need to use `{ style: "percent" }`.
For bytes: `{ style: "unit", unit: "megabyte" }`,

**Comment by martynasma** [comment]
You can create separate `NumberFormatter` instances for each series:

```JavaScript
series1.get("tooltip").label.set("numberFormatter", am5.NumberFormatter.new(root, {
  numberFormat: { style: "percent" }
}));

series2.get("tooltip").label.set("numberFormatter", am5.NumberFormatter.new(root, {
  numberFormat: { style: "unit", unit: "megabyte" }
}));
```

**Comment by zdm** [comment]
It works, Thank you,
