### ISSUE TITLE
TypeScript. Set data item type

### ISSUE THREAD

**Issue by roshaxo** [amcharts/amcharts5#1080]
Hello!
Is it possible to set data item type in one place and get it everywhere, where I'm trying to use `dataItem.dataContext`?
I want to avoid `as` keyword.

Example:
```
columnTemplate.adapters.add("interactive", (_, target) => {
  const { value } = target.dataItem?.dataContext as IDataItem;

  return value !== 0;
});
```

**Comment by martynasma** [comment]
I don't think that's correct. `dataContext` is arbitrary and does not implement `IDataItem` interface.

That said, I don't think there's a way to specify data Item type globally.

**Comment by roshaxo** [comment]
@martynasma Got you, thanks!
