### ISSUE TITLE
Map chart zoom functionality looks and feels jagged when the data is huge

### ISSUE THREAD

**Issue by sswatej** [amcharts/amcharts5#1081]
**Question**

I've got a list of about 3000 objects that I'm plotting on the Map chart with tooltip as bullets. 

When I filter the list with less number of objects in it. It zooms in and out smoothly. But with the huge list of objects the user experience doesn't feel good as the zoom is jagged. 

Is there a way to enhance this and make the zoom smoother?

**Environment (if applicable)**

**Additional context**

**Comment by zeroin** [comment]
The more objects you have, the more slowly the map will work, there is nothing we can do here, I am afraid.
