### ISSUE TITLE
Missing first (or last) horizontal grid line in Gantt chart

### ISSUE THREAD

**Issue by Mitwoc** [amcharts/amcharts5#1082]
Hi, I'm preparing a Gantt chart according to the official demo https://www.amcharts.com/demos/gantt-chart/, and whenever I remove `inversed: true` from AxisRendererY or `strokeOpacity: 0.1` from AxisRendererX, the first (or last) horizontal grid line is not displayed. It only seems to be working with the combination of those 2 settings.

![gantt chart](https://github.com/amcharts/amcharts5/assets/10099661/c2dd8ad5-6606-4be3-ae28-f2391f937340)

Environment: 
Google Chrome on Ubuntu

Version: 5.4.6

**Comment by zeroin** [comment]
It's not the first grid line but the axis line itself. The settings of this line are set on the AxisRenderer.

**Comment by Mitwoc** [comment]
Hi [zeroin](https://github.com/zeroin), thanks for the explanation! I didn't know that.

Is there a reason why is AxisRenderer not rendering that line when omitting `inversed: true`? I want to avoid reverting the data manually before passing them to the axis.

**Comment by zeroin** [comment]
It is rendering the  line on the other side.
