### ISSUE TITLE
Sticky Tooltip are limited

### ISSUE THREAD

**Issue by itakartor** [amcharts/amcharts5#1083]
Hi everyone, i created a chart with the sticky tooltip with a set of big number of data. I made the tooltips with the sprites in the bullets feature.
 I used a function for show and hide the tooltips, but they are not generated on the whole of the chart, but only on a reduced part, that is defined by the zoom.
If i go to the end of the chart i can not to see the tooltip because the library does not generate the bullets dynamically.

Is there a feature for resolve this little problem or a work around for show the tooltip dynamically?  

https://codepen.io/ITA-KARTOR/pen/BavpvRo

**Comment by zeroin** [comment]
Not sure I understand. If you uncomment `tooltip.show()` line in your code, the tooltips will be visible. I don't see where you call toggle method at all.

**Comment by itakartor** [comment]
The test case is: 
The sticky tooltips are hidden and i want to use the button to show them, but if i do that the toggle function does not show all tooltips

**Comment by zeroin** [comment]
This happens because tooltips are not created at the moment you call `toggle()` So you must save the status to some variable and then call tooltip.show() after you created, if it's true:

https://codepen.io/team/amcharts/pen/rNojRjx/6900ea3c06e875684a95e9ca6875cf3f
