### ISSUE TITLE
Custom indicators

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1084]
I am creating an auto indicator, which means that some of my customized indicators will automatically appear if any selected pattern or trend found in the data.
I  am using candlestick charts.

For example: In an any "A" product, I am checking in the data if there is a bullish engulfing pattern is there or not. If its there then at which ever point its found just indicate it on the chart.

One more example: Let's say if the a product "A" is channeling in certain high and low values, so automatically there will 2 trendlines will be drawn between those high and low points.  Like shown in the below image.

So my doubt is what should I trigger in amcharts to draw these technicals on the charts.

Image reference: 
![image](https://github.com/amcharts/amcharts5/assets/137867461/9fb4edc7-8ca1-4d3b-8dd6-14f415f4046d)

**Comment by zeroin** [comment]
There is a tutorial about creating custom indicators:
https://www.amcharts.com/docs/v5/tutorials/creating-custom-indicators-for-a-stock-chart/

I am afraid there is not more I can say from this description.
You can analyze how other similar indicators are made.
