### ISSUE TITLE
Obtain current date interval 

### ISSUE THREAD

**Issue by jalogar** [amcharts/amcharts5#1085]
Good morning. I'm using a StockChart with a GaplessDateAxis. I have a process that makes some calculation based on the current date interval (or the dates that appear in the chart), as you know, we could have 10 years of data but being show just 6 months for instance. My question is, how can I get the current date interval??? I have tried checking with 

`dateAxis.dataItems`

and some others, but unfortunately, I have been unable to find how to do it.

Thanks in advance!

**Comment by zeroin** [comment]
That would be `axis.getPrivate("baseInterval")`

https://www.amcharts.com/docs/v5/reference/gaplessdateaxis/#baseInterval_setting

You can even monitor the changes:
```
axis.onPricate("baseInterval", (baseInterval)=>{
   // do things
)
```

**Comment by jalogar** [comment]
Thanks for the quick response. I guess my question was incorrect. What I need is the 1st date shown in the chart, as well as the last date shown. I guess interval was not the proper term.

**Comment by zeroin** [comment]
This is also easy - `axis.getPrivate("min")` and `axis.getPrivate("max")` is a timestamp of your min and max dates.

**Comment by jalogar** [comment]
Thanks again for the response. I've seen that `min` and `max` give you the minimum and maximum values of your data, regardless of whether it is the range selected or not, so it's not what I'm looking for. However, now that I know the existence of `getPrivate`, I've seen that `axis.getPrivate("selectionMin")` and `axis.getPrivate("selectionMax")` is exactly what I'm looking for.

Thanks a lot for your time!
