### ISSUE TITLE
Require horizontal scrollbar in horizontally stacked axes 

### ISSUE THREAD

**Issue by saurabhahuja852** [amcharts/amcharts5#1087]
I want to create Column Chart with horizontally stacked axis, like given in below sample.
https://www.amcharts.com/demos/horizontally-stacked-axes/

If the number of  value axis is large in number , then I want to add horizontal scrollbar (see attached RequiredHorizonalScrollbar.png). 
Similarly like we added vertical scrollbar in below demo

https://www.amcharts.com/docs/v5/tutorials/scrollable-vertically-stacked-chart/

![RequiredHorizontalScrollbar](https://github.com/amcharts/amcharts5/assets/6298971/323312f4-79a5-4347-afee-4b7beafbb5b2)

**Comment by zeroin** [comment]
You can add horizontal scrollbar:

```
chart.set("scrollbarX", am5.Scrollbar.new(root, {
  orientation:"horizontal"
}))
```

however it won't work well in this case, as it will zoom all the axes together. 

The better approach would be to set pan:"zoom" on the renderers of value axes, this will enable zooming axes when hovering over values.

**Comment by saurabhahuja852** [comment]
Ok...
Can u provide sample code for second option.
And is there no way to add horizontal scrollbar in container ? I have only see option of verticalScrollbar

**Comment by zeroin** [comment]
No, our Containers only support vertical scrollbar.
The code to set pan:"zoom" on a AxisRenderer is very straightforward:

```
AxisRenderer.new(root, {
   pan:"zoom"
}
```

or:

axisRenderer.set("pan", "zoom");

https://www.amcharts.com/demos/line-graph/
