### ISSUE TITLE
How to update legend marker color?

### ISSUE THREAD

**Issue by ym010101** [amcharts/amcharts5#1089]
I used legend with 'useDefaultMarker: true' but I'd like to change it false.
In this case, 
markerRectangel.states.lookup("default).set("fill", newColor)
is not working. (I used this one to reflect color change to legend marker.)
How to reflect the lineSeries color change to legend marker immediately?

**Comment by zeroin** [comment]
Please provide full codepen of your case.

**Comment by ym010101** [comment]
Sorry, it's difficult to share my code for some reason so I will move to purchase support.
Thanks.
