### ISSUE TITLE
Make series not display in the legend

### ISSUE THREAD

**Issue by sknhkrn** [amcharts/amcharts5#109]
Hi, I have a multiple line series. Is there a way where some of the series not shown in the legend?
Thanks.

**Comment by xorspark** [comment]
A series is only shown in the legend if you add it to the legend's `data` list. If you don't want a particular series visible, simply don't push it into the list.

If you need to hide it after it has been added, just remove it with with the [ListData methods](https://www.amcharts.com/docs/v5/reference/listdata/#Methods), such as pop, shift, removeIndex.
