### ISSUE TITLE
series.slices.template.events don't fire

### ISSUE THREAD

**Issue by roman-gorkunenko** [amcharts/amcharts5#1091]
Hello. Please tell me why events on slices are not worked?
https://codepen.io/Roman-Gorkunenko-the-flexboxer/pen/xxmdpYY

**Comment by zeroin** [comment]
For focus/blur event you have to set:

`series.slices.template.set("focusable", true)`

and there are no "over" and "out" events, you should replace them with 'pointerover' and 'pointerout':

https://www.amcharts.com/docs/v5/reference/sprite/#pointerover_event
