### ISSUE TITLE
Tooltip Issue

### ISSUE THREAD

**Issue by hernes45** [amcharts/amcharts5#1092]
**Bug description**
Hi!!

When we have an Sparkline chart (for instance) with tooltip and the granularity of the chart is a little bit random, I have some samples of the timeserie that are Minutal, another Hourly and another Daily and I put the TimeUnit to Minute because it is the smallest granularity, the tooltip doesnt display properly for medium and large amount of data.

For instance,   a sample with:
Time; Value
01/01/2023 12:00; 4
01/01/2023 12:06; 4
01/01/2023 12:59; 4

02/01/2023 12:36; 4
02/01/2023 14:00; 4

02/02/2023 18:36; 4

What I spect is that the tooltip goes to the nearest point visible in the chart. like in this example when I put the cursor between two samples:
https://jsfiddle.net/api/post/library/pure/

Here is an example to reproduce the issue:
https://jsfiddle.net/aLqew3pk/1/

**Comment by martynasma** [comment]
Please refer to this doc:
https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/#Irregularly_spaced_data

**Comment by jindrichkuba** [comment]
I found the issue, issue was if you use any custom z-index inside global styles and then can effect AmCharts, then custom html tooltip is not possible used. There will be empty html content.

**Comment by jindrichkuba** [comment]
this code for html tooltip is working great `
const addTooltip = (root: am5.Root, chart: am5xy.XYChart, series: am5xy.ColumnSeries | am5xy.LineSeries, tooltipIds: number[]) => {
  const tooltip = am5.Tooltip.new(chart.root, {
    pointerOrientation: 'horizontal',
    labelHTML: `<div style="margin-bottom: 5px; font-family: 'Volta', sans-serif; background: #F2F2F2; padding: 5px 10px; font-size: 13px; font-weight: 500;">{categoryX}</div><div></div>`,
    getFillFromSprite: false,
  });

  tooltip.setAll({
    paddingTop: 0,
    paddingLeft: 0,
    paddingBottom: 10,
    paddingRight: 0,
  });

  tooltip.label.adapters.add('html', (text, target) => {
    chart.series.eachReverse((s) => {
      const { dataItem } = target as unknown as { dataItem: { dataContext: { [key: number]: number } } };
      const valueY = dataItem?.dataContext[Number(s.get('valueYField'))]?.toFixed(0);
      // eslint-disable-next-line no-param-reassign
      text += tooltipIds.includes(Number(s.get('valueYField')))
        ? `<div style="padding: 0 10px; display: flex; justify-content: space-between; font-weight: 500; font-family: 'Volta', sans-serif; font-size: 12px;"><span style="margin-right: 20px;"><span style="margin-right: 8px; color: ${
            s.get('fill')?.toString() as string
          }">●</span> <span>${s.get('name') as string}</span></span> <span>${valueY}</span></div>`
        : '';
    });
    return text;
  });

  tooltip.get('background')?.setAll({
    fill: am5.color(Colors.white),
    fillOpacity: 1,
    strokeOpacity: 0,
  });

  (series as am5xy.LineSeries).set('tooltip', tooltip);
};
`
