### ISSUE TITLE
Plotted data and date labels are not aligned

### ISSUE THREAD

**Issue by ankitsehgal94** [amcharts/amcharts5#1095]
**Bug description**

I am experiencing an issue where the date labels on the date axis do not align correctly with the plotted chart data when zoomed in. This problem occurs when there are only a few months displayed on the date axis.
<img width="1340" alt="Screenshot 2023-09-15 at 1 37 54 PM" src="https://github.com/amcharts/amcharts5/assets/25168592/2b0895c1-e768-436b-bd27-5fb94411f805">
<img width="1385" alt="Screenshot 2023-09-15 at 1 46 01 PM" src="https://github.com/amcharts/amcharts5/assets/25168592/f9edb93e-e97c-44bb-bdd3-011c76012751">
<img width="1391" alt="Screenshot 2023-09-15 at 1 46 40 PM" src="https://github.com/amcharts/amcharts5/assets/25168592/8472ff22-f214-4a53-8e5e-23d06be34d40">
<img width="1399" alt="Screenshot 2023-09-15 at 1 50 35 PM" src="https://github.com/amcharts/amcharts5/assets/25168592/5562c407-de4e-4cec-97ae-9c828c96f273">

**Expected Behavior:**
I expect the date labels and chart data to align properly, even when zoomed in with a limited number of months displayed on the date axis.

**Environment (if applicable)**
 - amCharts version 5

**Comment by xorspark** [comment]
If you modified the `location` property, you might also need to modify `multiLocation` as well. Please refer to https://www.amcharts.com/docs/v5/tutorials/location-of-items-on-date-axis-and-date-based-series/ for more details.

If that doesn't help, then we need to see a codepen.

**Comment by ankitsehgal94** [comment]
Thanks @xorspark for the reply. I am not using location and multilocation property. 
I have created a sandbox for more clarity [https://codesandbox.io/s/am-charts-line-chart-z3vkd3?file=/src/LineChart.tsx](url)
![Screenshot 2023-09-15 at 7 34 54 PM](https://github.com/amcharts/amcharts5/assets/25168592/0b7f450b-67d1-4ace-bef5-77f72076e999)

**Comment by xorspark** [comment]
All the dates in your codesandbox are set to the end of the month and they're placed correctly, i.e. July 31 is placed slightly to the right of July since it is at the end of the month. I don't see the case in your screenshot where July first is placed in that location. The first of the month be placed at the beginning of the month period, lining up with the axis.

**Comment by xorspark** [comment]
Also note that grid intervals also play a role here: https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#grid-granularity. Tweaking the gridIntervals setting will probably help:

```
      const xAxis = chart.xAxes.push(
        am5xy.GaplessDateAxis.new(root, {
          // ...
          gridIntervals: [
            { timeUnit: "day", count: 1 },
            { timeUnit: "month", count: 1 },
            { timeUnit: "year", count: 1 }
          ],
          // ...
        })
      );
```

**Comment by ankitsehgal94** [comment]
I didn't quite understand your explanation, but to clarify the issue further, I have recorded a Loom video.
[https://www.loom.com/share/8cf2154425ab484c9d9de6f5afc177aa](url)

**Comment by xorspark** [comment]
Did you try tweaking the gridIntervals like I suggested? Your sandbox works fine for me when I added them in.
https://codesandbox.io/s/am-charts-line-chart-forked-yj7qv3

**Comment by ankitsehgal94** [comment]
Yes, after adjusting the grid intervals, the chart now displays all the months when zoomed out and labels are aligned properly.
Previously, it used to group and show only some month labels when zoomed in. However, with the grid intervals, it no longer displays those few months and only shows the year. Months become visible only if the user zooms out significantly.
