### ISSUE TITLE
HTML tooltips with axis cursor are displayed incorrectly

### ISSUE THREAD

**Issue by roman-gorkunenko** [amcharts/amcharts5#1096]
Hello. If hover the cursor where the zero value is, the tooltip is displayed incorrectly. Then when hover where the values are, then the tooltips are displayed normally some time later.

video: https://github.com/amcharts/amcharts5/assets/91733660/09371c68-f8e0-4636-a03e-3995ba00dc0b

codepen: https://codepen.io/Roman-Gorkunenko-the-flexboxer/pen/YzdZmvg

**Comment by martynasma** [comment]
The issue is with your code. You need to set `labelHTML` on a `Tooltip` object, not `tooltipHTML`:

```JavaScript
const newTooltip = am5.Tooltip.new(root, {
  getFillFromSprite: false,
  getStrokeFromSprite: true,
  autoTextColor: false,
  getLabelFillFromSprite: true,
  labelHTML: tooltip,
  pointerOrientation: 'down',
  keepTargetHover: true,
});
```

You also don't have to set `tooltipHTML` on a column template as it's redundant.

**Comment by roman-gorkunenko** [comment]
Thanks a lot.
