### ISSUE TITLE
How to set bullet location to be high or low of candle stick

### ISSUE THREAD

**Issue by Afellman** [amcharts/amcharts5#1097]
Very simple question, I am using bullets on the CandlestickSeries on a StockChart. I want the Y position to be the exact high or low of the specific candle, but I can't figure out how to do it.

It seems like the `locationY` property only tracks the base of the candle (open - close) but not the "wicks". 

Any idea how I can achieve this?

**Comment by Afellman** [comment]
Only think I can think is to make a new line series with those high / low values, hide the line and only show the bullets.

This seems like a waste though...

**Comment by zeroin** [comment]
Yes, you should add another series with bullets for this purpose.

**Comment by Afellman** [comment]
Okay, thanks.
