### ISSUE TITLE
Axis ranges for DurationAxis

### ISSUE THREAD

**Issue by roman-gorkunenko** [amcharts/amcharts5#1099]
Hello.When all the values in DurationAxis are zero, how can I configure axis by y start from zero? 
Example https://codepen.io/Roman-Gorkunenko-the-flexboxer/pen/YzdZmvg
I tried setting the start value like this https://www.amcharts.com/docs/v5/charts/xy-chart/axes/axis-ranges/#range-start-and-end

`let rangeDataItem = yAxis.makeDataItem({
  value: 0
});
let range = yAxis.createAxisRange(rangeDataItem);`

but it did not help

**Comment by xorspark** [comment]
You're looking for the [min](https://www.amcharts.com/docs/v5/reference/durationaxis/#min_setting) setting to set the min/max values of the axis. An Axis Range is used to draw guides/fills at specified values.

```
    const yAxis = chart.yAxes.push(
      am5xy.DurationAxis.new(root, {
        baseUnit: 'minute',
        min: 0,
        renderer: am5xy.AxisRendererY.new(root, {}),
      }),
    );
```

**Comment by roman-gorkunenko** [comment]
Thanks a lot.
