### ISSUE TITLE
Can I use the event function after running zoomToGeoPoint?

### ISSUE THREAD

**Issue by hmPark85** [amcharts/amcharts5#1100]
Hello~!!

chart.zoomToGeoPoint(geoPoint).then(
	//
)

Can I use it as an example? Or is there any other way?
I want to hold another event after the zoom work

**Comment by martynasma** [comment]
No. `zoomToGeoPoint()` can either return an `Animation` object or `undefined` if the map is already in the target coordinates.

So you could do something like this:

```JavaScript
let anim = chart.zoomToGeoPoint(geoPoint);
if (anim) {
  anim.waitForStop().then(function() {
    // Do something
    // ...
  });
}
```
