### ISSUE TITLE
Divergent Stacked Bar size not matching percentage on X-axis

### ISSUE THREAD

**Issue by Rgri66** [amcharts/amcharts5#1104]
Bug in the demo of: https://www.amcharts.com/demos/divergent-stacked-bars/

When unselecting an option (in this example never) the size of the other options increases, and they do not match the percentages on the X axis.

<img width="809" alt="Screenshot 2023-09-20 141407" src="https://github.com/amcharts/amcharts5/assets/128379247/5c78c42c-5a0d-4550-a38d-a120151de99b">

(For student search engines "sometimes" option with a value of 34% the visual bar representation is over 40%)

This works correctly in version 4; https://www.amcharts.com/demos-v4/divergent-stacked-bars-v4/

**Comment by martynasma** [comment]
Thank you for bringing this to our attention! The demo is now fixed.
