### ISSUE TITLE
Can I set pointerOrientation of individual slices?

### ISSUE THREAD

**Issue by gutsuv** [amcharts/amcharts5#1105]
Hello,

I have a small pie chart consisting of four slices and would like to be able to set the pointerOrientation of each individual slice.

This problem arises because I used custom html in my center label and according to the documentation, the z-index cannot be set so it is running into issues with the tooltip.

![image](https://github.com/amcharts/amcharts5/assets/32459889/ef894d5c-31b5-4986-92ba-524f95043bb5)

I created a property in my data for the orientation I want for each slice. How can I pass that property into each slices tooltip?

Thank you

**Comment by martynasma** [comment]
Perhaps with an adapter:

```JavaScript
var tooltip = series.getTooltip();
tooltip.adapters.add("pointerOrientation", function(orientation, target) {
  var x = target.x();
  var y = target.y();
  var w = chart.seriesContainer.width();
  var h = chart.seriesContainer.height();
  if (y < (h * .25)) {
    return "down";
  }
  else if (y > (h * .75)) {
    return "up";
  }
  else if (x < (w * .25)) {
    return "right";
  }
  else {
    return "left";
  }
});
```

Hope the code makes sense.

Here's a live demo:
https://codepen.io/team/amcharts/pen/WNLzxqr??editors=0010

**Comment by gutsuv** [comment]
Although I was hoping there way a way to pass the tooltipSettings property you created, so each slice could be individually set, your posted solution works for the time being. Thank you for the help.

**Comment by martynasma** [comment]
`templateField` will not work for a tooltip, because it's shared, and template fields are used once, when the object is created.
