### ISSUE TITLE
Map Content Width()

### ISSUE THREAD

**Issue by jeadly** [amcharts/amcharts5#1107]
Hi, I'm trying to get the width of the map polygon series for comparison with the whole chart width.  The idea being that if I have a tall polygon displayed I don't need to responsively wrap my legend as soon as I would with a more horizontal aspect polygon.

However I can't get the polygonSeries.width() method to return anything but zero.
https://www.amcharts.com/docs/v5/reference/mappolygonseries/#width_method

Here is a quick example with Chile as a sample "Tall" geometry that has plenty of horizontal space so would not need to wrap as soon as other countries.
https://codepen.io/jeadly/pen/MWZrZvB

The responsive relevant evaluation console logs width values for the Chart, Map, Legend, and Series.  But the series width() is always zero.

If this isn't the intended use of this method, can you point me towards another path to evaluate responsive thresholds based on how much space is needed by the chart content?

**Comment by zeroin** [comment]
I'd recommend to listen to geoboundschanged event of the chart and then use geoBounds method to retrieve the coordinates. It will be in latitude/longitude, but should serve for your purpose:
```
chart.events.on("geoboundschanged", ()=>{
  console.log(chart.geoBounds())
})
```
