### ISSUE TITLE
Hiding series hides drawing

### ISSUE THREAD

**Issue by bradymbs** [amcharts/amcharts5#1108]
Hello, I'm trying to hide a series on a Stock Chart without the drawing to be hidden (the drawing should never be hidden)
*This may be a bug but it's not clear
steps to reproduce: click "select 'Doodle' tool" > draw on the chart > click "toggle series"
something that may be a bug however is you are able to draw while the series is hidden. However that isn't a concern for me since I don't want the drawing to be hidden

https://codepen.io/Brady-Lanning/pen/YzdarNG
codepen was forked from (https://codepen.io/team/amcharts/pen/mdGzONY)

**Comment by jeadly** [comment]
Looks like the stock chart is composed of many series and your toggle function is hiding them all, including the DoodleSeries.

I was able to leave the doodle on screen by adding a test for series type to your toggle call:

```
if (!series.isType("DoodleSeries") && series.get("visible")) {
        series.hide();
      } else {
        series.show();
      }
```

**Comment by zeroin** [comment]
Yes, drawing is just another series. So you must not hide it, as jeadly suggests.

**Comment by zeroin** [comment]
Then it's better to check if it's am5stock.DrawingSeries, as all drawing series extend this one.
