### ISSUE TITLE
(Category) AxisLabel text adapter not working properly from 5.0.0-beta.42 onwards

### ISSUE THREAD

**Issue by Cameramorphic** [amcharts/amcharts5#111]
Starting from version 5.0.0-beta.42 the text adapter gets called with the default text `'{category}'` instead of the actual substituted text.

```typescript
const data = [{ category: '1' }, { category: '2' }];
```
```typescript
const xAxis = chart.xAxes.push(
  am5xy.CategoryAxis.new(root, {
    renderer: am5xy.AxisRendererX.new(root, {}),
    categoryField: 'category',
  });
xAxis.get('renderer').labels.template.adapters.add('text', text => {
  console.log(`Adapter called for category "${text}"`);
  return foo[text];
);
```
expected log output (version 5.0.0-beta.41 and prior):
```
Adapter called for category "1"
Adapter called for category "2"
```
actual log output (version 5.0.0-beta.42 and later):
```
Adapter called for category "{category}"
Adapter called for category "{category}"
```

**Comment by martynasma** [comment]
Current behavior is correct.

In early Beta, CategoryAxis was just blatanly hardcoding category as labels' "text".

Since then it uses a data placeholder (`{category}`)  instead, letting label populate it from a data item.

If you need to format your label using related data, you can access adapter target's dataItem and its data context:

```JavaScript
xAxis.get('renderer').labels.template.adapters.add('text', function(text, target) {
  if (target.dataItem) {
    console.log(target.dataItem.dataContext);
    // modify text
  }
  return text;
});
```

**Comment by Cameramorphic** [comment]
Thanks for the quick reply!

I got it to work now, I actually tried to access the `dataItem`/`dataContext` from `target` before, but probably just aborted because it initially threw an undefined error. Also, typescript gives no indication that this property exists on target.

**Comment by martynasma** [comment]
Yeah, you might need to `<any>` the dataItem to make TS happy.
