### ISSUE TITLE
Event handling in column series

### ISSUE THREAD

**Issue by sankunSangji** [amcharts/amcharts5#1110]
I want code that changes the color of a bar when it is clicked and highlights the color of its label. 
Is this feature possible?

```javascript
var series = chart.series.push({ am5xy.ColumnSeries.new(root, {})});
series.columns.template.events.on('click', function (ev) { 
   \\ i want to highlights the color of labels
});
```

**Comment by zeroin** [comment]
Sure, you can address the clicked target through ev.target:

`ev.target.set("fill", am5.color(0xff0000)`

To access other elements, like bullets, you must do this through data item of a clicked target:

```
series.columns.template.events.on('click', function (ev) { 
   ev.target.set("fill", am5.color(0xff0000))
   var dataItem = ev.target.dataItem;
   dataItem.bullets[0].get("sprite").set("opacity", 0.5);
});
```

Instead of modifying separate properties, you can also create "active" state for columns and set toggleKey to "active":

```
series.columns.template.set("toggleKey", "active");
series.columns.template.states.create("active", {fill:am5.color(0xff0000)});
```

If you do this, you can do it for your bullets, but you will still need to set active state for bullet when column is clicked.

**Comment by sankunSangji** [comment]
@zeroin great thank you. i can solve to this problem well.
i have a another question.  


```
let selectedSeries;

series.columns.template.states.create("hover", {
            fill: am5.color(0x80C9FF),
            stroke: am5.color(0x80C9FF),
});

series.columns.template.states.create("highlight",{
            fill: am5.color(0x80C9FF),
            stroke: am5.color(0x80C9FF),
        });

series.columns.template.events.on('click', function (ev) {
            let column = ev.target;
            if (selectedSeries) {
                selectedSeries.states.apply("default");
                selectedSeries = undefined;
            }
            column.states.apply("highlight");
            selectedSeries = column;
        });
```
i want to two event for column series. but this code is not working. only it is working one event. 
is it possible using two event for one series column? 
if it is possible, i want to hover and click event for column series.

**Comment by zeroin** [comment]
I am afraid I will need a working codepen with full source in order to help here.

**Comment by sankunSangji** [comment]
@zeroin 
codepen url : https://codepen.io/sankunSangji/pen/BavxJmN

i want to click event and hover event for column series. 
When the mouse is hovered, the bar should change to the hover color, but when leaving the chart, the clicked bar should remain in the highlighted state again. And when you click the bar again, the highlight state should disappear, and when you select another bar, the bar should be in the highlighted state. is it possible? i wait your replay ! thank you.

**Comment by zeroin** [comment]
It's better to use "active" state as it is already working with clicks and you don't need to do almost anything, except to set active to false for your previously active column:

https://codepen.io/team/amcharts/pen/yLGjvbE/818aa033a0b4a4d858f44f4f45773eb3?editors=1010

**Comment by sankunSangji** [comment]
@zeroin 
wow, so perfect answer for me. Is there a way to get rid of the state in this code by pressing the same bar twice?

**Comment by sankunSangji** [comment]
@zeroin 
great thank you, i solve it completely :)
