### ISSUE TITLE
How to position a label on a value that depends on x/y

### ISSUE THREAD

**Issue by GustavoCunhaLacerda** [amcharts/amcharts5#1111]
I have a Stock Chart

wanted to position a label in a position that corresponds to the x and y value like this
![image](https://github.com/amcharts/amcharts5/assets/48692606/e9c55c3e-ed70-4282-8119-f880c16577d0)

I just have the date value and the x value of an event.

I tried something like this to plot but not work:
![image](https://github.com/amcharts/amcharts5/assets/48692606/4d321416-1d95-465d-808e-e996db40b1bf)

**Comment by martynasma** [comment]
I would create a separate series and add it via data and bullets.

This way you won't need to think about repositioning your element when chart is scrolled/resized/etc. You can also have multiple bullets.

Does that makes sense?

**Comment by GustavoCunhaLacerda** [comment]
Yes, that makes sense. I didn't have the idea of putting another series to render the point, because it looks too overkill.

Thanks for your support.
