### ISSUE TITLE
How to dynamically add and remove Map Line series dan Map point series

### ISSUE THREAD

**Issue by Fiqih57** [amcharts/amcharts5#1113]
I use amcharts 5

based on the demo in https://www.amcharts.com/demos/map-with-animated-lines/

I want to make it appear one by one, after the animationLineDataItem is finished the next data will appear along with the animation. How to delete Map Lines and Map points correctly ?

Add

`pointSeries.data.push(value);`

remove

`pointSeries.data.removeIndex(pointSeries.data._values.findIndex(obj => obj.id == city));`

and when use actual data items

```
var lineDataItem = lineSeries.pushDataItem({});
  lineDataItem.set("pointsToConnect", [londonDataItem, destinationDataItem])

  var startDataItem = animatedBulletSeries.pushDataItem({});
  startDataItem.setAll({
    lineDataItem: lineDataItem,
    positionOnLine: 0
  });
```
how to remove actual data items ?

**Comment by zeroin** [comment]
To remove points/lines, use `series.disposeDataItem(dataItem)` method.
