### ISSUE TITLE
How to change the tooltip text color to a custom color with saving autoTextColor feature behavior?

### ISSUE THREAD

**Issue by dmytro-kuz** [amcharts/amcharts5#1114]
Hi guys. I want to achieve a specific behavior: when I change the text in the tooltip to a custom color (for example, let it be any shade of blue), I want the text color to change to blue. However, it should not merge with the sector of the chart on which it is displayed. If the color matches the sector, then it should change to white. In essence, I'm looking for something similar to the amCharts autoTextColor feature. Can you help with this?

```   // set tooltip custom text color
      if (this.data.color) {
        let tooltip = am5.Tooltip.new(this.root, {
          autoTextColor: false,
          labelText: `{category}: ${format}`,
        });
        tooltip.label.setAll({
          fill: am5.color(hex),
        });
        series.set('tooltip', tooltip);
      }
```

**This is what I get when I change the text color in the tooltip -**
![image](https://github.com/amcharts/amcharts5/assets/92852665/2550faf5-b814-43f5-bae6-4e991ddc610a)
![image](https://github.com/amcharts/amcharts5/assets/92852665/a85abb08-67ec-46c6-8f4c-9bcaac5e675d)

**I would like to get a similar text color behavior to this screenshot, but for tooltip -**
![image](https://github.com/amcharts/amcharts5/assets/92852665/7889b49d-2342-4946-8fb2-a55250f36094)

**Additional context**

**Comment by zeroin** [comment]
If you could provide a codepen of your chart, I could help.

**Comment by dmytro-kuz** [comment]
> If you could provide a codepen of your chart, I could help.

https://codepen.io/Dmytro-Kuz/pen/XWoqBBK  

colors can be different - for series and for text color in tooltips.
Also, I don't need to change the fill color of the tooltips, just applied smth similar to autoTextColor

**Comment by dmytro-kuz** [comment]
Thanks a lot for the advice. It is a good point.
But what about cases when series and tooltip text colors are not absolutely identical (for example the same shade - 0xe6e61b and 0xe6e61c)
In this case, there will also be a merging of colors.

https://codepen.io/Dmytro-Kuz/pen/XWoqBBK

**Comment by dmytro-kuz** [comment]
Yeah, you're right, anyway thanks for helping!
