### ISSUE TITLE
ForceDirected link & label color

### ISSUE THREAD

**Issue by vueDevInci** [amcharts/amcharts5#1115]
I want to design mind map something like this https://prnt.sc/8BbrJ64VJxZP 
I want to set unique color for each node label & link/edge (which connect two nodes) specially. How can I set that? I used stroke in links but it did not work.

**Comment by martynasma** [comment]
Please refer to this tutorial:
https://www.amcharts.com/docs/v5/charts/hierarchy/hierarchy-node-colors/
