### ISSUE TITLE
How to get the width of ColumnSeries?

### ISSUE THREAD

**Issue by roman-gorkunenko** [amcharts/amcharts5#1119]
Hello. Charts can have different container sizes and different column widths. 

https://codepen.io/Roman-Gorkunenko-the-flexboxer/pen/eYbEyyp

There can also be very long labels that overlap each other, so I use oversizedBehavior: "wrap" . Therefore, if the label is fits width, i need to place it on one line. I want to implement dynamic maxWidth calculation for oversizedBehavior: "wrap" https://www.amcharts.com/docs/v5/concepts/common-elements/labels/#behavior

MaxWidth can be changed via adapter
`xAxis.get('renderer').labels.template.adapters.add("maxWidth", (maxWidth, target) => {
    return maxWidth;
});`

Can you please tell me please how to calculate this width?
![iScreen Shoter - 20231003214449327](https://github.com/amcharts/amcharts5/assets/91733660/609ff051-47e9-44e1-82a7-0172bb0be986)

**Comment by zeroin** [comment]
You can not have different sizes for the axis categories on one axis. Maybe you'd like to try stacking several different category axis, and setting a different width for each. Here is an example which shows how axis can be stacked:
https://www.amcharts.com/demos/horizontally-stacked-axes/

For the axis labels, check this tutorial:
https://www.amcharts.com/docs/v5/tutorials/handling-long-category-axis-labels/

**Comment by roman-gorkunenko** [comment]
Hello. Width of the series column will be the same. I need to calculate the maxWidth for each chart.
`xAxis.get('renderer').labels.template.setAll({
  oversizedBehavior: 'wrap',
  maxWidth: 100,
});`
For example, the default maximum width for labels is set to 100. The picture shows that there is still room for labels. Therefore, you need to put it in one line. To do this, i need to calculate the width of these columns and the distance between them. In other cases there may be more data. Accordingly, the width of the columns will be smaller. The maximum width for labels will need to be reduced.

**Comment by roman-gorkunenko** [comment]
Thank you, this option is probably suitable
`xAxis.onPrivate("cellWidth", function(cellWidth) {
  xRenderer.labels.template.set("maxWidth", cellWidth)
});`
