### ISSUE TITLE
Is it possible to use some parameter to adjust the distance for stacked: true?

### ISSUE THREAD

**Issue by roman-gorkunenko** [amcharts/amcharts5#1120]
Hello. Is it possible to adjust this distance?
![iScreen Shoter - Google Chrome - 231004100453](https://github.com/amcharts/amcharts5/assets/91733660/277d2cb6-9a34-4e4b-907c-4df31fc16e56)

**Comment by zeroin** [comment]
If you could provide a working codepen of this, I could tell. There are too many ways to get this view, so I can't guess what's happening there.

**Comment by roman-gorkunenko** [comment]
for example here is the chart
https://codepen.io/Roman-Gorkunenko-the-flexboxer/pen/jOXeMKo
I need any way to change this distance
I thought about doing it using these options:

cellStartLocation
cellEndLocation

but it doesn't work

**Comment by zeroin** [comment]
If you just need an equal space between columns, maybe a white stroke with big strokeWidth would do the thing? Otherwise you will need to do non-stacked columns and specify openValueY for each column.
