### ISSUE TITLE
White lines between fill colors in line chart

### ISSUE THREAD

**Issue by marciammart** [amcharts/amcharts5#1123]
**Bug description**

I'm experiencing an issue where white lines are appearing in between the fill colors of individual data points when I use `fillSettings`. My intention is to create a chart where multiple data points with the same fill color blend together seamlessly, without any noticeable lines between them.

![Screenshot 2023-10-06 at 14 43 16](https://github.com/amcharts/amcharts5/assets/53227495/d2a7d010-0fcc-4060-abbe-f4c4710693a2)

Here is a CodePen with an example of the issue: https://codepen.io/M-rcia-Martins/pen/gOZBRxM

**Environment (if applicable)**
Locally I'm using amCharts 5.3.15 in React and the white lines appears in every browser I tested (Firefox, Chrome and Safari).

**Comment by xorspark** [comment]
Every time a point has a templateField set, a new segment is created, which results in the white lines as a new fill is created for the segment. If you set the templateField on the first point that needs the new color, the rest of the line will inherit it until you specify a new one. In your case, setting the templatefields for the first point for purple and the middle point to black will give you the desired result without the white lines.

[Codepen](https://codepen.io/team/amcharts/pen/QWzJVBZ/c99288b97ba7f5346073625a01e9a818?editors=1010)

**Comment by marciammart** [comment]
@xorspark that fixed my issue, thank you so much!
