### ISSUE TITLE
Animation not working properly when triggered by custom event

### ISSUE THREAD

**Issue by afvca** [amcharts/amcharts5#1125]
Hi,

When attempting to animate the clock hand of a gauge chart using the `axisDataItem.animate` function triggered by a keyup event, the animation does not work as expected. Instead of smoothly transitioning to the new value, the clock hand immediately jumps to the new position.

You can reproduce this by taking [this](https://codepen.io/team/amcharts/pen/QWrOYeR) pen as example.

Adding this to the html part:
```html
<input id="gauge"></input>
```

And the corresponding javascript (replacing the existing setInterval function):

```javascript
document.getElementById("gauge").addEventListener('keyup', function() {
    var inputValue = document.getElementById("gauge").value;
    axisDataItem.animate({
      key: "value",
      to: inputValue,
      duration: 600,
      easing: am5.ease.out(am5.ease.cubic)
    });
});
```

Every time the input value changes the clock hand correctly moves to the new position, but no animation is shown.

Should I be doing this any other way?

**Comment by martynasma** [comment]
If you're grabbing input from a form field, it comes as a string, which cannot be animated.

Try casting it into a `number`:

```JavaScript
var inputValue = parseInt(document.getElementById("gauge").value);
```
