### ISSUE TITLE
Displaying sections with a zero value on the Pie chart

### ISSUE THREAD

**Issue by roman-gorkunenko** [amcharts/amcharts5#1127]
Hello.
If there are several zero values, they are not displayed on the chart even though strokeWidth is set

![iScreen Shoter - Google Chrome - 231010170731](https://github.com/amcharts/amcharts5/assets/91733660/a98638fd-deca-4db0-8934-604cbbfa1e20)

https://codepen.io/Roman-Gorkunenko-the-flexboxer/pen/xxmdpYY

Is it possible to make all zero values also appear in the chat? Thanks.

**Comment by zeroin** [comment]
Well, they are simply in the same spot and overlap each other. I don't see a proper way of solving this. Arranging them next to each other would be wrong.

**Comment by roman-gorkunenko** [comment]
For example, for xy charts there is such an option and it’s convenient that I can hover to column and read the tooltip. For pie charts it will always show the tooltip of that zero element which is on top.
![iScreen Shoter - Google Chrome - 231011083948](https://github.com/amcharts/amcharts5/assets/91733660/c1c03909-bb6e-4be3-aadb-41be814d79c3)

**Comment by martynasma** [comment]
There's no way around it, I'm afraid. They are zero-value slices and thus have zero-width.

If you absolutely need to display zero-slices in your chart, I suggest you group them all into a single "Others" slice.

**Comment by roman-gorkunenko** [comment]
Is it possible to configure z-index for slices? So that those who have zero values are on top. Then they overlap with other slices and it is difficult to hit with the cursor.

![iScreen Shoter - Google Chrome - 231012093737](https://github.com/amcharts/amcharts5/assets/91733660/fd87fe81-ce6e-4825-870a-5e1556cacdda)

**Comment by martynasma** [comment]
No, I'm afraid.
