### ISSUE TITLE
Tooltip not appearing when I change baseInterval on date axis to "second"

### ISSUE THREAD

**Issue by liamjbarry** [amcharts/amcharts5#1128]
**Question**

I am trying to use a simple line chart to display some data, the data is over the span of 1 minute and is 5 seconds apart (12 data points a minute) and so far I have achieved this but I am struggling with the tooltip on the series. I have baseInterval set as I believe to be correct below

```
chart.xAxes.push(
  am5xy.DateAxis.new(root, {
    baseInterval: {
      timeUnit: "second",
      count: 5,
    },
    renderer: am5xy.AxisRendererX.new(root, {}),
  })
);
```

When I do this I don't get tooltips but the chart shows as I would expect. If I change the `timeUnit` to `"minute"` rather than `"second"` I get a tooltip but the chart is wrong. I believe `"second"` is correct for my use case but this seems to cause the tooltip to stop working. I have spent a while on this trying to narrow down what seems to make the tooltip appear/disappear but for the life of me I cannot get a tooltip to show while I have `"second"` set as the time unit.

CodeSandbox:
https://codepen.io/liambarry/pen/PoXVVmE  

**Environment (if applicable)**
amCharts 5
ReactJS/TypeScript (I was able to reproduce in vanilla JS on CSB so probably irrelevant)

**Comment by xorspark** [comment]
Your data is incorrectly sorted. Date-based data must be in date-ascending order or you'll get weird issues (rendering, tooltips, etc): https://www.amcharts.com/docs/v5/concepts/data/#Data_order

Adding a `reverse` call to your data shows tooltips for me; they're empty, so you need to set the `labelText` inside your tooltip.

**Comment by liamjbarry** [comment]
Ahhhh! Thank you! one of the first things I tried was reversing the data but I obviously hadn't got the right combo! Thank you for the quick response I appreciate it!
