### ISSUE TITLE
Hiding axis labels in gauge chart

### ISSUE THREAD

**Issue by afvca** [amcharts/amcharts5#1130]
Hi,

Is it possible to hide only the outside gauge chart axis label values from [this](https://www.amcharts.com/demos/gauge-with-bands/) example?

Leaving it like this:

![Capture](https://github.com/amcharts/amcharts5/assets/13245732/b99c85aa-b80f-43f9-bbe2-fbded379bc44)

I tried with:

```javascript
axisRenderer.labels.template.setAll({
    visible: false,
});
```

But it removes all of the labels.

**Comment by xorspark** [comment]
You're halfway there. In addition to setting visible to false on the axisRenderer labels, you also need to set `visible` true on the axis ranges in the bands to make sure those stay visible:

```
  axisRange.get("label").setAll({
    text: data.title,
    inside: true,
    visible: true,
    radius: 15,
    fontSize: "0.9em",
    fill: root.interfaceColors.get("background")
  });
```
