### ISSUE TITLE
yAxis

### ISSUE THREAD

**Issue by mohammadhasananisi** [amcharts/amcharts5#1134]
Hi, Thank you for your great library.

when i use height in the yAxis this happens

https://github.com/amcharts/amcharts5/assets/47121464/e5f4136e-d26c-493b-ac22-7f2293b7eb97

can you fix that?

**Comment by martynasma** [comment]
Why would you set height on an axis and not on the panel?

**Comment by mohammadhasananisi** [comment]
// Create value axis
    yAxis = mainPanel.yAxes.push(
      am5xy.ValueAxis.new(root, {
        renderer: am5xy.AxisRendererY.new(root, {
          pan: "zoom",
          inversed: false,
          inside: false,
          minGridDistance: 30,

          labels: {
            adapter: am5.Tooltip.new(root, {
              getStrokeFromSprite: true,
              getFillFromSprite: true,
            }),
            location: 1.3,
          },

          // height: am5.percent(70),

        }),
        // strictMinMaxSelection: true,
        extraMin: 0.37, // adds some space for for main series
        extraMax: 0,
        tooltip: am5.Tooltip.new(root, {}),
        extraTooltipPrecision: 1,
        numberFormat: "#.##a",
        logarithmic: true,
        maxPrecision: 0,
        position: 'relative',

        // height: am5.percent(70),
        // 
      })
    );




this is my axis

**Comment by martynasma** [comment]
I'm afraid I'm not quite sure what "I have a line chart in the stock chart button." means.

Would you be able to post your working chart on CodePen?
