### ISSUE TITLE
`LineSeries` Bullets don't always get rendered as expected (Bubble Chart)

### ISSUE THREAD

**Issue by Cameramorphic** [amcharts/amcharts5#1135]
**Bug description**
I'm working on a bubble chart which can show a mixture of a `ValueAxis` and a `CategoryAxis` or two `ValueAxis`.
As described in the [Bubble Chart example](https://www.amcharts.com/demos/bubble-chart/), this is achieved by rendering bullets for the data points of a `LineSeries` and hiding the stroke.
I noticed that some, seemingly random, data points were missing from the chart, even though all properties were set correctly in the data.
I discovered, that the bullet function doesn't get called for all data points (all `dataItems` exist on the series though).
It appears that this behaviour is influenced by the order of the data and/or the order of the data for the `CategoryAxis`.
Depending on the these orders, the series sometimes renders all, only some, or even no bullets whatsoever.

I reduced/changed the mentioned Bubble Chart example to the code below.
To quickly show different results the commented out `.reverse()` calls can be used, but other faulty results can also be produced by reordering `data` differently.
The stroke is visible below, to better visualize where the bullets are missing and to show that the series itself indeed renders correctly.

```ts
const root = am5.Root.new('chartdiv');
const chart = root.container.children.push(am5xy.XYChart.new(root, {}));

const xAxis = chart.xAxes.push(am5xy.ValueAxis.new(root, {
  renderer: am5xy.AxisRendererX.new(root, { minGridDistance: 50 }),
}));
const yAxis = chart.yAxes.push(am5xy.CategoryAxis.new(root, {
  renderer: am5xy.AxisRendererY.new(root, {}),
  categoryField: 'category'
}));

const series = chart.series.push(am5xy.LineSeries.new(root, {
  xAxis,
  yAxis,
  categoryYField: 'y',
  valueXField: 'x',
}));

series.bullets.push(function() {
  return am5.Bullet.new(root, {
    sprite: am5.Circle.new(root, {
      radius: 10,
      fill: series.get('fill'),
    })
  });
});

var data = [
  { y: 'C', x: 8 },
  { y: 'A', x: 3 },
  { y: 'B', x: 4 },
];
const categoryData = [
  { category: 'A' },
  { category: 'B' },
  { category: 'C' },
];

// series.strokes.template.set("visible", false);
// data.reverse();
// categoryData.reverse();

yAxis.data.setAll(categoryData);
series.data.setAll(data);
```

**Environment**
amCharts: 5.4.6
Chrome: 116.0.5845.140
(Typescript / React)

**Comment by zeroin** [comment]
Well yes, the Category axis data and series data should be sorted in the same order, it's by design.

**Comment by Cameramorphic** [comment]
Ah ok, good to know. Is that documented anywhere? Because I didn't come across this information.
Especially for bubble charts / bullets, which are often used to show a dataset of arbitrary points that normally don't follow the consecutive nature of a *series*, because the data points have no direct correlation.
I was just confused because the series itself appears to render correctly, only the bullets don't.

**Comment by martynasma** [comment]
> Ah ok, good to know. Is that documented anywhere? Because I didn't come across this information.

We didn't have it. Adding as we speak. Sorry for the inconvenience.

**Comment by Cameramorphic** [comment]
Ok, thanks for the quick replies :)
