### ISSUE TITLE
Tooltip layering issue with html prop labels in AMCharts vertical bar chart

### ISSUE THREAD

**Issue by DenisSeverinov** [amcharts/amcharts5#1137]
Hi, thank you for your library!

**Problem**
The issue involves an inability to properly layer a tooltip above HTML-rendered labels (displaying value and percentage) on top of series columns in an AMCharts vertical bar chart within a React component.

**Description**
The goal is to have two labels displayed one below the other at the top of each column within the series - one showing the value and the other showing the percentage. A potential approach I considered was to utilize HTML for this purpose.
However, while attempting to implement this using prop _html_, I encountered an issue layer positioning. When hovering over a column, a tooltip is triggered which should appear on top of the labels. Unfortunately, the tooltip ends up being displayed behind the HTML element containing the value label, despite attempts to adjust the z-index. I have been unable to find a suitable workaround to ensure the tooltip appears on top or to properly position the labels using other methods. This poses a challenge in achieving the desired visual output for the chart.
Currently, I have the following relevant code snippet within my component:

```
series.bullets.push(function () {
  return am5.Bullet.new(root, {
    locationX: 0.5,
    locationY: 1,
    sprite: am5.Label.new(root, {
      centerY: 0,
      centerX: am5.p50,
      dy: -50,
      html:"<div style='display:flex;flex-direction:column;gap:4px'><span>{value}</span><span>{percentage} %</span></div>",
      populateText: true
    })
  });
});
```
I will be providing a more comprehensive code example to better illustrate the issue. Any insights or suggestions on how to resolve this issue would be greatly appreciated. Specifically, guidance on how to effectively use HTML to achieve the desired label positioning while ensuring the tooltip is displayed on the correct layer would be very helpful.

[CodeSandbox](https://codesandbox.io/s/amcharts-issue-6km5lm?file=/src/components/VerticalBarChart/index.tsx)

To reproduce the issue, hover over a series column in the provided example, and observe that the tooltip appears behind, not on top of the labels rendered via the html prop, making the tooltip content partially obscured.

**Comment by martynasma** [comment]
Unfortunately, there's no way around it.

HTML content is displayed in a `<div>` positioned over the whole chart, whereas the chrome of the tooltip is drawn in main chart canvas.

The solution would be not to use HTML for those column labels.

Another solution is to disable bult-in tooltip background, and draw tooltip background in HTML.

Hope that makes sense.

**Comment by DenisSeverinov** [comment]
Thanks for answer.

**Comment by bradzab0623** [comment]
@martynasma This issue is causing me a lot of pain. Is there really no way to resolve this? Why did tooltips appear above html labels/other html chart content correctly in version 5.2.29, but now that I upgraded to the latest it no longer is?

**Comment by martynasma** [comment]
You can fix it using CSS:

```CSS
.am5-layer-30 {
  z-index: 100
}
```

**Comment by bradzab0623** [comment]
@martynasma unfortunately it looks like that wont work in my case.

for this case, I have an HTML label on the chart but I am also using HTML inside my series tooltips. if I set that CSS, the chart items that are at layer 30 correctly appear over the label, but the content of the series tooltips then appear behind the chart.

if I then set the z-index of am5-html-container to a value above the layer-30, I'm back to square one.

The one thing I'm not clear about is why this seemed to work fine for me in version 5.2.29. HTML content in tooltips appeared over other chart elements but my HTML labels appeared under tooltips (including those without HTML)

**Comment by martynasma** [comment]
A lot of versions (and time) since 5.2.29. We've done a bunch of changes in the interim, including ones that affect expanded tooltip bounds, solving other issues.

Bottom line, there's currently no way to keep some HTML content behind canvas content and some above it 🙁
