### ISSUE TITLE
i want to make various legend mark shapes

### ISSUE THREAD

**Issue by sankunSangji** [amcharts/amcharts5#1144]
hello, i have a one question. I want to change the shape of the randomly created legend mark.

![스크린샷 2023-10-23 오후 4 31 06](https://github.com/amcharts/amcharts5/assets/111471485/ab0d0b1d-376a-4ae1-85fe-3b8c5a7f93bb)

The attached photo shown above is the standard shape used in Arm Chart. Can I change this shape like below?

![스크린샷 2023-10-23 오후 4 33 00](https://github.com/amcharts/amcharts5/assets/111471485/dbff42c1-691f-48e7-8735-c82ccf9ffd1c)

codepen url : https://codepen.io/sankunSangji/pen/MWLWxrO?editors=0010

**Comment by martynasma** [comment]
If you need to make default markers wider you can do it like this:

```JavaScript
legend.markers.template.setAll({
  width: 60
});
```

Not sure about the one with the vertical white lines. I suppose you could apply a [pattern](https://www.amcharts.com/docs/v5/concepts/colors-gradients-and-patterns/patterns/):

```JavaScript
legend.markerRectangles.template.setAll({
  fillPattern: am5.LinePattern.new(root, {
    color: am5.color(0xffffff),
    rotation: 45,
    width: 200,
    height: 200
  })
});
```

Example:
https://codepen.io/team/amcharts/pen/eYxmMpv/2dc4c98bf9e25c43be72c190badd82da
