### ISSUE TITLE
Docs: serializing/JSON examples need corrections

### ISSUE THREAD

**Issue by davidjb** [amcharts/amcharts5#1149]
**Bug description**

The docs for serialisation have a couple of issues:

1. Parsing (https://www.amcharts.com/docs/v5/concepts/serializing/#Parsing) mention a `target` property for automated pushing an object but from the source code and examples it appears this should be `parent`:

   https://github.com/amcharts/amcharts5/blame/master/src/.internal/plugins/json/Json.ts#L588

1. Stroke and fills (https://www.amcharts.com/docs/v5/concepts/serializing/#Strokes_and_fills) docs need a `properties` nested key in the examples for strokes and fills:

   ```js
   strokes: { 
      // a properties key needs to be added here
      template: {
        settings: {
          ...
        }
      }
    }
   ```

   This example also has a typo: `strokeWdith`.

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
Thanks! I believe all mentioned docs issues has now been fixed.

**Comment by davidjb** [comment]
Perfect, thanks @martynasma for updating that - looks great.
