### ISSUE TITLE
tooltip text on series with adapter - having trouble

### ISSUE THREAD

**Issue by morrow95** [amcharts/amcharts5#115]
Been having some trouble converting our code from version 4 to version 5.  In particular using an adapter to modify the tooltip text on a series.

version 4 : 

```
var series = chartReg['chart'].series.push(new am4charts.ColumnSeries());
//series.calculatePercent = true; //do this myself
series.dataFields.dateX = "Timestamp";
series.dataFields.valueY = "Total";
series.fill = am4core.color("#679fd0");
series.fillOpacity = 1;
series.name = "Total";
series.strokeWidth = 0;

series.tooltip.background.fill = am4core.color("#fff");
series.tooltip.background.fillOpacity = 1;
series.tooltip.background.pointerLength = 0;
series.tooltip.background.stroke = am4core.color("#BBB");
series.tooltip.background.strokeWidth = 2;
series.tooltip.dy = -30;
series.tooltip.fontSize = 13;
series.tooltip.getFillFromObject = false;
series.tooltip.label.fill = am4core.color("#0E0F10");
series.tooltip.pointerOrientation = "vertical";
//series.tooltipText = "Total : [bold]{valueY}[/]";
series.adapter.add("tooltipText", function (text, target, key) {
	//console.log(target.tooltipDataItem.dataContext);//the hovered points data
	var totalP = calcPercent(target.tooltipDataItem.dataContext.Total, target.tooltipDataItem.dataContext.TotalSum);

	return "Total : [bold]{Total}[/]\nPercent : [bold]"+totalP+"[/]";
});
```

What I have attempted so far with version 5 and can't get anything to pass : 

```
//series
var series = chart.series.push(am5xy.ColumnSeries.new(chartReg['chart'], {
  name: "Total",
  fill: am5.color(0x679fd0),
  xAxis: xAxis,
  yAxis: yAxis,
  valueYField: "Total",
  valueXField: "Timestamp",
  //tooltip: am5.Tooltip.new(chartReg['chart'], {
    //labelText: "{valueY}"
  //})
}));

series.columns.template.setAll({
  fillOpacity: 1,
  strokeWidth: 0
});

series.columns.template.adapters.add("tooltipText", function (text, target, key) {
	console.log(target);
	var totalP = calcPercent(target._dataItem.dataContext.Total, target._dataItem.dataContext.TotalSum);

	return "Total : [bold]{Total}[/]\nPercent : [bold]"+totalP+"[/]";
});
```
I can see that `target._dataItem.dataContext` holds the values I am after and there are no errors, but no tooltip is shown at all.  I feel like I just went through all of this not long ago going to version 3->4 and now the same is happening from 4->5.  I really hope the coding, methods, etc stay consistent in future versions.  Any help would be appreciated.

**Comment by martynasma** [comment]
It depends on how you want it to handle.

1) Do you want it be shown when directly hovering on column?

In such case you need to set `tooltipText` on column template along the adapter.

Adapter will not kick in if there's no setting in first place.

```JavaScript
series.columns.template.setAll({
  fillOpacity: 1,
  strokeWidth: 0,
  tooltiptext: "{valueY}"
});

series.columns.template.adapters.add("tooltipText", function (text, target, key) {
	console.log(target);
	var totalP = calcPercent(target._dataItem.dataContext.Total, target._dataItem.dataContext.TotalSum);

	return "Total : [bold]{Total}[/]\nPercent : [bold]"+totalP+"[/]";
});
```

2) Do you need tooltips shown on all series when using `XYCursor`?

You will need to add `text` adapter on tooltip's label:

```JavaScript
var series = chart.series.push(am5xy.ColumnSeries.new(chartReg['chart'], {
  name: "Total",
  fill: am5.color(0x679fd0),
  xAxis: xAxis,
  yAxis: yAxis,
  valueYField: "Total",
  valueXField: "Timestamp",
  tooltip: am5.Tooltip.new(chartReg['chart'], {
    labelText: "{valueY}"
  })
}));

series.get("tooltip").label.adapters.add("text", function (text, target, key) {
	console.log(target);
	var totalP = calcPercent(target._dataItem.dataContext.Total, target._dataItem.dataContext.TotalSum);

	return "Total : [bold]{Total}[/]\nPercent : [bold]"+totalP+"[/]";
});
```
```

**Comment by morrow95** [comment]
@martynasma  Thank you.  The first method works, but not quite like I had in the last version (you didn't have to hover directly over the column it would show the closest to the cursor position).

I can't make the second method you listed work because I can't find anywhere in `target` to access the column values - unless I'm just not seeing them.

**Comment by martynasma** [comment]
Try `target.dataItem`. It should hold proper data item for the tooltip.

**Comment by morrow95** [comment]
@martynasma turns out the second method works fine it just finds empty values sometimes in `_dataItem` sometimes so I had to add logic for it in the adapter.

New question and kind of related... how can I change the fill, stroke, opacity, etc of the tooltip when it is created as part of the series?

```
var series = chart.series.push(am5xy.ColumnSeries.new(chartReg['chart'], {
  name: "Total",
  fill: am5.color(0x679fd0),
  xAxis: xAxis,
  yAxis: yAxis,
  valueYField: "Total",
  valueXField: "Timestamp",
  tooltip: am5.Tooltip.new(chartReg['chart'], {
    labelText: "{valueY}"
  })
}));
```

Everything I find in the docs shows creating your own instance of the tooltip to modify these settings, but in this case the tooltip is created with the series. [https://www.amcharts.com/docs/v5/concepts/common-elements/tooltips/](https://www.amcharts.com/docs/v5/concepts/common-elements/tooltips/)

**Comment by martynasma** [comment]
Do you mean you want to change color of tooltip depending data? Different for each data item?

**Comment by morrow95** [comment]
I got it figured out - thank you!
