### ISSUE TITLE
Pie chart colours don't appear with JSON parsing unless using `parent` setting

### ISSUE THREAD

**Issue by davidjb** [amcharts/amcharts5#1150]
**Bug description**

When rendering a pie chart from parsed JSON, the chart's colours don't appear if pushing the charter into `root.container.children`, but they do appear when using the auto-push functionality via `parser.parse(config, { parent: root.container })`. The rest of the chart - labels, lines, amCharts branding - appears fine in both cases.

https://jsfiddle.net/Lbt3fj9q/1/

<img width="732" alt="image" src="https://github.com/amcharts/amcharts5/assets/1002811/cd297bfe-141c-4f6e-bd42-ef6665936194">

**Environment (if applicable)**

 - amCharts version: latest from CDN (5.5.1)
 - Browser: tested in Firefox 119, Chrome 118 and Safari 17
 - Vanilla JS

**Additional context**

**Comment by martynasma** [comment]
Upon further examination, this is not related to JSON parsing. Creating a full-fledged PieChart with data set before it is set to a `Root` element, does not apply defaults to `ColorSet` which is used to apply slice colors, hence slices remaining color-less.

I'll keep this issue open until we had a discussion whether it can be helped somehow.

Will keep you posted.
