### ISSUE TITLE
Line series is unable to deal with winter/summer time changes

### ISSUE THREAD

**Issue by a21674** [amcharts/amcharts5#1152]
**Bug description**
I have a presentation of daily data minute by minute, which works at a specific time, 02:30-02:29. The last few months everything worked correctly, however this morning there was a time change, to winter time (Portugal) , that is, at 02am, it was 01am again.

My dataset is already considering the time change, so I have exactly a dataset with 1339 minutes, from 02:30 on 28/10/2023 until 02:29 on 29/10/2023, however for some reason the graph is adding two blocks with the time from 01am to 02am, the first with data from the dataset, the second without data.

![image](https://github.com/amcharts/amcharts5/assets/74302921/30f42597-4480-4cab-969f-358abff6e43f)

I put code in a StackBlitz project that generates the graph, as well as the dataset I'm using:
https://stackblitz.com/edit/stackblitz-starters-itx7eh?file=src%2Flineseries.ts

Development environment:
 - amCharts5
 - Chrome, Edge
 - Angular

If this is not a bug but rather a configuration issue on my part, let me know and I will change the issue to "Question".

Thanks so much for your help.

**Comment by martynasma** [comment]
It seems your data has string-based dates. I'm not sure what you mean by "dataset is already considering the time change", but if you are supplying date/time in some specific timezone, your date strings should include it so that it is converted into a proper timestamp.

Like for instance if your data is recalculated to UTC (which does not have any DST switches), then it should explicitly specify it in the code, e.g.: `"2023-01-01T02:00:00+0000"`.

Better yet, include date/time in your data as timestamps, so you don't have to do two-way parsing.

Hope it makes sense.

**Comment by a21674** [comment]
Hi @martynasma 
First of all, thanks for the fast response.

I did a lot of changes, converte the date to use timezone, convert to unix timestamp, use the moment-timezone library, and all attempts resulted in the same problem, a repetition of the block from 01am to 02am.

This is one eg as the timezone came correct from the backend:

![image](https://github.com/amcharts/amcharts5/assets/74302921/3cbe66a4-6aee-47c2-a996-bc5ef1ec0139)

What leads me to wonder if there might be something going wrong internally in the time series, is that I make a breakpoint/console.log at this point "series.data.setAll(data);" and the dataset is correct, it goes from 02:30 to 02:29 (1339 minutes), the problem occurs after applying data.setAll() to the series

**Comment by martynasma** [comment]
Any chance of an updated StackBlitz?

**Comment by a21674** [comment]
Hi @martynasma I updated the StackBlitz with new json, but I'm having difficulty presenting the graph in stackbliz because of several dependencies on the component that displays the graph, see if you can reproduce the dataset I have there.

Thanks again for your excellent support

**Comment by martynasma** [comment]
Gotcha. Thanks. Looking into it.

**Comment by martynasma** [comment]
OK, so looking further into your data. The moment of the switch to DST:

```JavaScript
      {
        "time": "2023-10-29T00:58:00+01:00",
        "rating": 512.0644657,
        "ratingUw": 124,
        "totalSeconds": 1218960
      },
      {
        "time": "2023-10-29T00:59:00+01:00",
        "rating": 488.743534,
        "ratingUw": 121,
        "totalSeconds": 1181520
      },
      {
        "time": "2023-10-29T01:00:00+00:00",
        "rating": 479.6752357999998,
        "ratingUw": 120,
        "totalSeconds": 1185240
      },
      {
        "time": "2023-10-29T01:01:00+00:00",
        "rating": 488.01132939999985,
        "ratingUw": 123,
        "totalSeconds": 1187160
      },
```

The timezone offset changes from +01:00 to +00:00, yet the time itself is not adjusted.

The last data item before switch is `00:59:00`, the first after switch is `01:00:00`.

Shouldn't it go back one hour after switch?

The way I see it, there's a glitch in the data.
