### ISSUE TITLE
Overriding `Bullet` configuration with `templateField` in JSON parsing

### ISSUE THREAD

**Issue by davidjb** [amcharts/amcharts5#1158]
**Bug description**

I'm looking to create Bullets from parsed JSON data and have the Bullets styled on an individual basis, with a default fallback for colours, radius, position, etc. 

Given the caveat described at https://www.amcharts.com/docs/v5/concepts/common-elements/bullets/#template-fields for Template Fields and Bullets, I've been looking for a way to implement the same but from parsed JSON configuration. Given how other template setups work, it seemed this should be the configuration:

JSFiddle: https://jsfiddle.net/984pnxod/

```json
...
"refs": [
  {
    "data": [
      { "country": "USA", "value": 1, "bulletSettings": { "fill": "#ff0" } },
      { "country": "China", "value": 2 },
      { "country": "Japan", "value": 3 }
    ]
  },
...
"bullets": [
  {
    "type": "Bullet",
    "settings": {
      "sprite": {
        "type": "Circle",
        "settings": {
          "radius": 5,
          "stroke": "@series.get('stroke')",
          "templateField": "bulletSettings"
        },
        "properties": {
          "template": {
            "settings": {
              "fill": "@series.get('fill')"
            }
          }
        }
      }
    }
  }
]
```

But trying to do this results in an error:
```js
Uncaught TypeError: value._setObjectTemplate is not a function
```

Is this a supported or correct way to be setting this? 

The same issue occurs regardless of if the template `value` is `@series...` or if it's an explicit colour (e.g. written in `Color` object JSON notation `{ "type": "Color", "value": "#00f" }`).

Removing the `properties` key above allows the chart to render, with the USA bullet appearing yellow. This may be a separate issue, but I noticed that the `fill` property needs to be a string rather than a `Color` JSON object. If you use the latter, the Bullet's fill becomes black. This seems inconsistent with the rest of the object colour creation in JSON (as per https://www.amcharts.com/docs/v5/concepts/serializing/#Bullets). I saw same issue with Percent as well - the value needs to specified as a number rather than an object.

**Environment (if applicable)**

- amCharts version: CDN (5.5.2)

**Additional context**

Setting the `fill` as part of the sprite's `settings` triggers the caveat, in that bullets' colours are set from the sprite and not the `templateField`.

**Comment by martynasma** [comment]
Bullets are not created from a `TemplateList`, hence they cannot use `template`. So this approach is a no-go.

As you correctly observed, there's also no way to override settings with `templateField` either if they are set directly on bullet's visual element.

I'm not aware of a workaround, except using `templateField` with non-uniform bullet settings set for each and every data item.

**Comment by davidjb** [comment]
Thanks for the info @martynasma - do you think this is something that would be able to be added to the JSON config?

**Comment by martynasma** [comment]
Hm, OK, I've now taken a fresh look, and I think there's a way to work around that by slightly modifying JSON:

```JSON
"bullets": [
  {
    "type": "Bullet",
    "settings": {
      "sprite": {
        "type": "Circle",
        "settings": {
          "radius": 5,
          "stroke": "@series.get('stroke')",
          "templateField": "bulletSettings"
        },
        "properties": {
          "template": {
            "type": "Template", // <-- just added this, so that `Template` object is created and used for fill
            "settings": {
              "fill": "@series.get('fill')"
            }
          }
        }
      }
    }
  }
]
```

Updated Fiddle: https://jsfiddle.net/2wnh78d5/

**Comment by davidjb** [comment]
Fantastic, thanks @martynasma - that works perfectly. I had to make sure the series `fill` and `stroke` were correctly set (as per your JSFiddle) but that together with the `templateField` config above solved the issue. Many thanks!
