### ISSUE TITLE
Chart border spacing

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1159]
I am trying to show multiple charts in my frontend, therefore I am trying to optimize & reduce maximum possible space available which is not being used. I am using candlestick charts of amcharts5 in react.

I want to **remove** the highlighted/marked space, though earlier it was being used to show the technical indicators but now I have removed it.
 
 The space which I have to remove: 
 
![image](https://github.com/amcharts/amcharts5/assets/137867461/cb934034-8762-4b0b-b6ca-e4aa660e4e40)

Code for my theme: https://codepen.io/Ansh-m-the-reactor/pen/zYeqeyb?editors=0010

**Comment by martynasma** [comment]
It's hard to tell from partial code and screenshot, but there should not be this gap on a StockChart by default.

The only thing that jumped out at me from your code is that you have panel height set at 90%. If there's only one panel, it might be affecting white space.

Other than that, I'm not sure where it might be coming from. If you'd like for us to take a look, please consider posting a full working code on CodePen.

**Comment by workingbuddy10** [comment]
Thank you @martynasma  for responding. 
Actually the issue was from end only, as the space which is there is taken by the full screen toggle button.

**Comment by workingbuddy10** [comment]
Is there any feature in amcharts that help us to see the chart in the full screen mode?
As till I am using Antd library button for that.

And handling full screen like this: 

`  const handleFullScreenToggle = async () => {
    if (screenfull.isEnabled) {
      const element = document.getElementById(`chartContainer-${props.index}`);
      screenfull.toggle(element);
    }
  };`
  
  @martynasma

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.
