### ISSUE TITLE
Stockchart Zoom & Pinch

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1160]
I am unable to add the zoom-out pinch feature in my stockchart, and neither I found any docs for that. Though for XYcharts it is given.
XY chart: https://codepen.io/team/amcharts/pen/Badvajx

What I exactly want: 

- Zoom out feature in stockchart like given in Xychart.
- Zoom out should happen like this: Let's say the user have zoomed the chart to a certain state, and now they have clicked on the zoom-out button then only Right side part should zoom out. For example user zoom to start date: 15/10/2023 and end date: 20/10/2023, so when user click on zoom out button the start date remains the same (start date: 15/10/2023) but the end date should shift to recent/last candlestick (end date: 30/10/2023).

And also I have not added the scrollbar.

This is what my chart looks like : 
![image](https://github.com/amcharts/amcharts5/assets/137867461/4e4f42db-3f5d-4e71-80a2-4caa110b470f)

Code for the chart initalization: https://codepen.io/Ansh-m-the-reactor/pen/RwvadLZ?editors=1010

**Comment by workingbuddy10** [comment]
Is there any way we can achieve zoom feature in Stockchart ?
@martynasma

**Comment by martynasma** [comment]
You can enable pinch-zooming by setting [`pinchZoomX: true`](https://www.amcharts.com/docs/v5/charts/xy-chart/zoom-and-pan/#Pinch_zoom) on your panels.

```JavaScript
var mainPanel = stockChart.panels.push(am5stock.StockPanel.new(root, {
  wheelY: "zoomX",
  panX: true,
  panY: true,
  pinchZoomX: true
}));
```

**Comment by workingbuddy10** [comment]
Did the same as you suggested. Still it didn't worked!
Full chart rendering code: https://codepen.io/Ansh-m-the-reactor/pen/RwvadLZ?editors=1010
@martynasma 

```
    var stockChart = root.container.children.push(
      am5stock.StockChart.new(root, {
        panX: true,
        panY: true,
        wheelX: "panX",
        wheelY: "zoomX",
        pinchZoomX: true
      })
    );

    // Set global number format
    root.numberFormatter.set("numberFormat", "#,###.00");

    // Create a main stock panel (chart)
    var mainPanel = stockChart.panels.push(
      am5stock.StockPanel.new(root, {
        wheelY: "zoomX",
        panX: true,
        panY: true,
        height: am5.percent(90),
        pinchZoomX:true
      })
    );
```

**Comment by martynasma** [comment]
Your CodePen errors out for me.

**Comment by workingbuddy10** [comment]
Can you do in this codepen, this will not show any error.
Link: https://codepen.io/Ansh-m-the-reactor/pen/qBgNKvz

@martynasma

**Comment by martynasma** [comment]
Just add `pinchZoomX: true` to your panel:

```JavaScript
var mainPanel = stockChart.panels.push(am5stock.StockPanel.new(root, {
  wheelY: "zoomX",
  panX: true,
  panY: true,
  pinchZoomX: true
}));
```

Works for me on your latest CodePen.

**Comment by workingbuddy10** [comment]
I want the button to be there for zoom out.

Like this: 
![image](https://github.com/amcharts/amcharts5/assets/137867461/bd595438-d4a6-4cea-bf72-c1420437eb27)

In current codepen: 
![image](https://github.com/amcharts/amcharts5/assets/137867461/316a10cb-50f3-452a-980e-68b8bc5f7156)

@martynasma

**Comment by martynasma** [comment]
Zoom out button is disabled in StockChart by default.

You can enable it like this:

```JavaScript
mainPanel.zoomOutButton.set("forceHidden", false);
```

**Comment by workingbuddy10** [comment]
Thanks it worked!
Just last thing, I don't want my chart to be fully zoomed out.
I want it to be zoomed to maybe last/recent 10 days candle or any certain number of days. How can I achieve that?

Like in am5xy chart its given about minZoomCount & maxZoomCount, how can we achieve it in am5stock Exactly.
@martynasma

**Comment by martynasma** [comment]
Maybe this will help:
https://www.amcharts.com/docs/v5/charts/xy-chart/zoom-and-pan/#Pre_zooming_axes

**Comment by workingbuddy10** [comment]
Like I just want one more button side to the zoomout button, which Zoom-in to the recent/live data point added.

- How to add the button?
- How to set the button with this functionality in **am5stock**, as mainly examples are given for xy charts.
@martynasma

**Comment by martynasma** [comment]
`StockChart` does not have a plot container. Panels do.

So you can do the same on a panel.

**Comment by workingbuddy10** [comment]
Let's say you have the below data and the start and end dates are given, so whenever user clicks on the button it should be **zoomed in** to this candlesticks data. How can we achieve this? @martynasma 
Data: 
Start date: 1696363200000, end date: 1696370400000 (the data is in Unix format Only).
```
{
      Date: 1696363200000,
      Open: 4258.5,
      High: 4265.25,
      Low: 4251.25,
      Close: 4261,
      Volume: 172231
    },
    {
      Date: 1696366800000,
      Open: 4261,
      High: 4267.75,
      Low: 4252.25,
      Close: 4266.75,
      Volume: 306907
    },
    {
      Date: 1696370400000,
      Open: 4266.75,
      High: 4269.5,
      Low: 4262.5,
      Close: 4262.75,
      Volume: 70713
    }
```

Current code:

```
    var button = mainPanel.plotContainer.children.push(am5.Button.new(root, {
      dx: 1930,
      dy: 1040,
      label: am5.Label.new(root, {
        text: "->",
        fontSize: 15,
        fontWeight: "300",
        paddingTop: 2,
        paddingRight: 4,
        paddingBottom: 2,
        paddingLeft: 4
      })
    }));
    button.events.on("click", function(ev){
      dateAxis.zoomToDates(Date())
    })
```
