### ISSUE TITLE
Can you create 3D Charts with amcharts 5?

### ISSUE THREAD

**Issue by ozitrance** [amcharts/amcharts5#1162]
**Question**
Are the 3D versions of the charts implemented yet in amcharts 5? I cannot find any information regarding this. I can see it on version 4 but cannot make it work on 5 or find anything related to it in the docs (for version 5)

Thank you!

**Comment by xorspark** [comment]
[There is no 3D in v5](https://www.amcharts.com/docs/v5/migrating-from-amcharts-4/#No_3D).
