### ISSUE TITLE
Amcharts 5 | Stock Charts | Labels not correct in RTL

### ISSUE THREAD

**Issue by faryal-ali** [amcharts/amcharts5#1163]
Hi,

We are using amcharts 5 cdn version (https://cdn.amcharts.com/lib/5/stock.js) for display of a stock chart. We are facing an issue with RTL settings (Arabic). When the chart is displayed in **Arabic**, the legends are not being placed correctly and the values overlap the comparison sections.

![image](https://github.com/amcharts/amcharts5/assets/108254869/7693823c-dc84-47f1-9972-42b000cb2010)

We have tried following settings but the layout is not fixed:

1. root.rtl = true;
2. Added following properties:

root.language.setTranslationsAny({

				  "Draw": "يرسم",
				  "QE Index":"مؤشر التيسير الكمي",
				   "QEIndex":"مؤشر التيسير الكمي",
				    "QETR":"مؤشر التيسير الكمي",
				      "QEIndexTotal":"مؤشر التيسير الكمي",
				  "Indicators":"المؤشرات"
				});

3. Added multiple values on Legend to fix it:

  
 var valueLegend = mainPanel.plotContainer.children.push(am5stock.StockLegend.new(root, {
		  stockChart: stockChart,
		  reverseChildren: true,
		  direction: "rtl",
		 // align:"right",
		 // valueAlign:-150,
		  dx: 150,
		  centerX:  am5.p20,
		  marginLeft:50,
		  paddingLeft:100,
		  id: "id_"
		}));

4. Add properties at label level

      var series = am5xy.LineSeries.new(root, {
		    name: label,
		     //  centerX: -30, // Label starts at its left side
 		   valueYField: "value",
		    calculateAggregates: true,
		    valueXField: "date",
		    xAxis: dateAxis,
		    yAxis: valueAxis,
		    legendValueText: "{valueY.formatNumber('#.00')}",
		   direction:"rtl",
		  //    dx: -25//,
		 //     x: am5.percent(50)//,
		 // 	marginLeft:50,
		  	//paddingLeft:100
		  });

**Question**

**Environment (if applicable)**

**Additional context**

**Comment by Suleman12** [comment]
Also for the tooltip Settings Faced A similar issue 
![tooltip1234](https://github.com/amcharts/amcharts5/assets/24837687/5a63749f-bad1-4509-bfc0-6572f77d9798)

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by Suleman12** [comment]
I have added these properties to the Stock chart comparing prices .PF the Code Pen https://codepen.io/Suleman12-the-vuer/pen/poGENee   .The Chart Does not convert to rtl.

**Comment by martynasma** [comment]
Your CodePen looks good tome:
![image](https://github.com/amcharts/amcharts5/assets/1458520/d268d62f-06ea-472b-8109-fb5ba665e643)

The only visual "glitch" is that legend is shifted to right because of the margin/padding settings on it.

**Comment by martynasma** [comment]
You may need to set RTL directly on legend labels:

```JavaScript
valueLegend.labels.template.setAll({
  direction: "rtl"
});
```

**Comment by lodewykk** [comment]
This can be fixed for ColumnSeries tooltips by specifying `tooltipHTML` instead of `tooltipText`

``` ts
series.columns.template.setAll({
  // tooltipText: '{tooltipText}',
  tooltipHTML: "<span>{tooltipText}</span>",
});
```
