### ISSUE TITLE
Adding vertical axis-like lines on the chart

### ISSUE THREAD

**Issue by 12rita** [amcharts/amcharts5#1164]
Hi! I am now using Tree chart in my project. I need to add vertical lines, like this: 
<img width="364" alt="image" src="https://github.com/amcharts/amcharts5/assets/18229211/b025a7fa-553b-4599-ac62-158109e5316c">

Is there any way to do it? I found a way just to add line above the chart, but i need it to be placed between hierarchy levels directly, so i need to somehow retrieve information about distance between nodes or something like that

**Comment by martynasma** [comment]
There's no such feature in a `Tree`, I'm afraid.

**Comment by 12rita** [comment]
Is there a way to get coordanates of nodes?

**Comment by 12rita** [comment]
And one more question: i have wrapper div width set to 100%, but chart doesn't seem to take all the place. Why can it be?

**Comment by martynasma** [comment]
> Is there a way to get coordanates of nodes?

Yes, you can use node's methods `x()` and `y()` for that.

Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.

**Comment by 12rita** [comment]
> Yes, you can use node's methods `x()` and `y()` for that.

How can i do this? I've tried this way

**Comment by martynasma** [comment]
Are you calling this before data is set maybe?

**Comment by 12rita** [comment]
> Are you calling this before data is set maybe?

Yes, you were right. Now i got the result, but all nodes x and y are zeros

**Comment by martynasma** [comment]
Perhaps it would be easier if I know what are you trying to do with them.
