### ISSUE TITLE
Zoom out button

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1165]
I am unable to change the zoom out button icon in candlestick charts.

```
    mainPanel.zoomOutButton.get("icon").setAll({
      icon: am5.Picture.new(root, {
        interactive: true,
        src: "https://img.icons8.com/ios-glyphs/30/zoom-out.png",
        cursorOverStyle: "pointer",
      }),
    });
```

**Comment by martynasma** [comment]
You're setting "icon" on an icon itself. Just set it on the button:

```JavaScript
    chart.zoomOutButton.setAll({
      icon: am5.Picture.new(root, {
        interactive: true,
        src: "https://img.icons8.com/ios-glyphs/30/zoom-out.png",
        cursorOverStyle: "pointer",
      }),
    });
```

**Comment by workingbuddy10** [comment]
- And how to reduce the button size of zoomOutButton. 

@martynasma

**Comment by workingbuddy10** [comment]
And how to fix the position of the custom button like zoomOutButton, so that whenever we zoom the browser or change the screen size it should be adaptable.
@martynasma 
```
    var button = mainPanel.plotContainer.children.push(
      am5.Button.new(root, {
        dx: 1650,
        dy: 10,
        icon: am5.Picture.new(root, {
          interactive: true,
          src: "https://img.icons8.com/ios-glyphs/30/zoom-in--v1.png",
          cursorOverStyle: "pointer",
        }),
      })
    );
    button.events.on("click", function (ev) {
      var last10DataPoints = data.slice(-20);
      if (last10DataPoints.length) {
        var n = last10DataPoints.length;

        var startDate = last10DataPoints[0].Date;

        var endDate = last10DataPoints[n - 1].Date;
        dateAxis.zoomToDates(new Date(startDate), new Date(endDate));
      }
    });
```

**Comment by martynasma** [comment]
You can set button's padding:

```JavaScript
chart.zoomOutButton.setAll({
  paddingTop: 5,
  paddingBottom: 5,
  paddingLeft: 5,
  paddingRight: 5,
  icon: am5.Picture.new(root, {
    interactive: true,
    src: "https://img.icons8.com/ios-glyphs/30/zoom-out.png",
    cursorOverStyle: "pointer",
  }),
});
```

> And how to fix the position of the custom button like zoomOutButton, so that whenever we zoom the browser or change the screen size it should be adaptable.

I'm not sure what you mean by "adaptable position".

**Comment by workingbuddy10** [comment]
When I adaptable I mean to see the CUSTOM made button position should be dynamic, like when I select the FULL screen mode on the browser the CUSTOM MADE button shifts.
Whereas the built-in the button of amcharts (zoomoutbutton) it holds it position in both the cases.

Case 1: When the user view it in the normal view. Look out both the position of buttons the top right corner button is zoomoutbutton where as the bottom right corner button is my Custom made button which takes me to the recent data point.
![image](https://github.com/amcharts/amcharts5/assets/137867461/92a86379-76b0-4a55-aa9d-90a66f36692a)

Case 2: When user selects the FULL Screen mode, the CUSTOM made button shifts upside. Which I don't want.
![image](https://github.com/amcharts/amcharts5/assets/137867461/6109197a-f7c4-4dc1-a855-9f051fd569bc)


Code of the custom made button:


```
    var button = mainPanel.plotContainer.children.push(
      am5.Button.new(root, {
        dx: 1700,
        dy: 910,
        paddingTop: 5,
        paddingBottom: 5,
        paddingLeft: 5,
        paddingRight: 5,
        icon: am5.Picture.new(root, {
          interactive: true,
          width: "10",
          height: "10",
          src: "https://img.icons8.com/ios/20/circled-chevron-right--v1.png",
          cursorOverStyle: "pointer",
        }),
      })
    );

    button.events.on("click", function (ev) {
      var last10DataPoints = data.slice(-26);
      if (last10DataPoints.length) {
        var n = last10DataPoints.length;

        var startDate = last10DataPoints[0].Date;

        var endDate = last10DataPoints[n - 1].Date;
        dateAxis.zoomToDates(new Date(startDate), new Date(endDate));
      }
    });
```

@martynasma

**Comment by martynasma** [comment]
Please refer to this demo on how to dynamically position zoom-out button to the bottom:
https://www.amcharts.com/docs/v5/tutorials/position-the-zoom-out-button-to-bottom-right/

it's for an `XYChart`, but you can do the same on a panel.

**Comment by workingbuddy10** [comment]
I don't want to move the zoom-out to the bottom, I want the custom button to move down. Below is the code of the custom button and I tried to re-position it.
@martynasma 

```
    var button = mainPanel.plotContainer.children.push(
      am5.Button.new(root, {
        // dx: 1700,
        // dy: 910,
        paddingTop: 5,
        paddingBottom: 5,
        paddingLeft: 5,
        paddingRight: 5,
        icon: am5.Picture.new(root, {
          interactive: true,
          width: "10",
          height: "10",
          src: "https://img.icons8.com/ios/20/circled-chevron-right--v1.png",
          cursorOverStyle: "pointer",
        }),
      })
    );
    mainPanel.plotContainer.onPrivate("height",function(height){
      mainPanel.button.set("dy",height-60);
    })
    button.events.on("click", function (ev) {
      var last10DataPoints = data.slice(-30);
      console.log(last10DataPoints);
      if (last10DataPoints.length) {
        var n = last10DataPoints.length;

        var startDate = last10DataPoints[0].Date;

        var endDate = last10DataPoints[n - 1].Date;
        dateAxis.zoomToDates(new Date(startDate), new Date(endDate));
      }
    });
```

**Comment by martynasma** [comment]
The code applies to any button. Although your code should be like this:

```JavaScript
mainPanel.plotContainer.onPrivate("height",function(height){
   button.set("dy", height-60);
})
```

**Comment by workingbuddy10** [comment]
I want the button at the marked location. I tried this:
@martynasma 
```
    mainPanel.plotContainer.onPrivate("height",function(height){
      button.set("dx", height-10);
      button.set("dy", height-30);
   })
```

![image](https://github.com/amcharts/amcharts5/assets/137867461/7332c64a-2ca3-44e9-81ac-167dbd395126)

**Comment by workingbuddy10** [comment]
Yes it worked!
But these are the issue:

- It's just when I l click on the bottom it always miss the most recent point as it gets more zoomed. 
- And the button click, we have to Excatly click on the icon it doesn't work.

Video for the better reference:

https://github.com/amcharts/amcharts5/assets/137867461/8bb87e62-e938-4888-b64d-07c591b133b9

@martynasma

**Comment by workingbuddy10** [comment]
Any suggestions on this? @martynasma

**Comment by martynasma** [comment]
I'm sorry, but this is getting into a request territory.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).
