### ISSUE TITLE
Overlapping bullets with tooltip as sprite

### ISSUE THREAD

**Issue by vmagano** [amcharts/amcharts5#1166]
Hello, I am seeking a method to ensure that bullet tooltips remain constantly visible, but I am encountering an issue where some tooltips overlap, as shown in the example image.

I have attempted to utilize the 'minBulletDistance' property, but it did not yield the expected results. Instead, all bullets disappeared and only reappeared after a significant amount of zoom.

Is there a method to selectively display only certain tooltips, for instance, to avoid overlapping? I am seeking a solution that allows me to show specific tooltips while preventing overlap issues.

Thanks!

![image](https://github.com/amcharts/amcharts5/assets/56595647/a86d5551-9021-4953-b30b-4a995cf53b5b)
![image](https://github.com/amcharts/amcharts5/assets/56595647/6e0d93eb-460c-4750-9b4a-8eaf4686a513)

**Comment by zeroin** [comment]
This should help:
https://www.amcharts.com/docs/v5/concepts/common-elements/bullets/#selectively-displaying-bullets
