### ISSUE TITLE
Is it possible to apply a factor to valueY in a tooltip?

### ISSUE THREAD

**Issue by qn4k3** [amcharts/amcharts5#1168]
I use a tooltip to show the value of a series in a XYLineChart:

`tooltip: am5.Tooltip.new(root, {
	labelText: '{name}: [bold]{valueY} ' + unit + '[/]'
}),`

I would like to apply a series-specific factor to the value shown in the tooltip, something like that (which is not working):

`tooltip: am5.Tooltip.new(root, {
	labelText: '{name}: [bold]{valueY * 10} ' + unit + '[/]'
}),`

I only want to apply this factor to the tooltip, not to the data drawn in the chart.

Is that possible?
Thanks in advance :)

**Comment by zeroin** [comment]
The easiest way to solve this would be to add an adapter for the `labelText`

```
tooltip.adapters.add("labelText", (labelText)=>{
  var dataItem = series.get("tooltipDataItem");
  if(dataItem){
    return series.getNumberFormatter().format(dataItem.get("valueY") * 10);
  }
  return labelText
})
```

https://codepen.io/team/amcharts/pen/PoVWqYy
