### ISSUE TITLE
Gantt chart not correctly pre-zoomed when initialized

### ISSUE THREAD

**Issue by Mitwoc** [amcharts/amcharts5#1169]
I'm trying to pre-zoom a Gantt chart using steps from the documentation: https://www.amcharts.com/docs/v5/charts/xy-chart/zoom-and-pan/#Specific_range , however, the zoom is obviously ignored and the chart displays all the data when initialized.

This is the code I'm calling:
```
series.events.on("datavalidated", function() {
  const start = new Date(2016, 3, 27);
  const end = new Date(2016, 4, 15);
  xAxis.zoomToDates(start, end, 0); 
});
```
 
If I call _zoomToDates_ with a delay using setTimeout it works correctly, however, I can't use it in my solution.

Here is a demo: https://codepen.io/Mitwoc/pen/ExrNBvO?editors=1111

**Comment by zeroin** [comment]
Your baseAxis in this case is CategoryAxis, so the xAxis auto-zooms to show all the selected data, and this happens after you call zoomToDates. So you have two options here:

set autoZoom:false for your xAxis. In this case, if you zoom-in y axis, x axis won't be auto zoomed to the selection.
delay zooming a bit, with setTimeout.
