### ISSUE TITLE
Maps accessibility

### ISSUE THREAD

**Issue by Malvoz** [amcharts/amcharts5#117]
As far as I can tell, there's no way for keyboard users to:

- Pan the maps (can be achieved by setting `tabindex="0"` on `<svg>` and handling arrow keys)
- Operate the controls (can be achieved using `tabindex="0"` for focusability and `aria-label` or `title` to describe the purpose of each control)
- Tab to and interact with each feature (same as above)

Additionally, it'd be helpful to screen reader users if the maps were titled using [SVG `<title>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title) or `aria-label` (for example https://www.amcharts.com/svg-maps/?map=iceland could have `<svg aria-label="Iceland">`).

**Comment by martynasma** [comment]
We will consider adding arrow panning to the `MapChart`.

Though, how good is that for vision-impaired users? Do you have any real-life scenario where that might be actually something people would use?

I mean there's no meaningful way to convey chart pan position as a text/voice.

I believe that better use of arrow keys is allowing users to loop throug map objects by enabling groups:

https://www.amcharts.com/docs/v5/concepts/accessibility/#Grouping_focusable_elements

Please also note that amCharts 5 does not use SVG, so there's nothing to comment about your suggestions that related to SVG.

**Comment by Malvoz** [comment]
I don't use amCharts, and don't plan to, I just stumbled upon demos on the site which is linked to from this repo. I won't raise further issues, good luck!
