### ISSUE TITLE
Dynamic Number Formatter

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1170]
I want a dynamic number formatter, like I have different variety of products which I am showing in candlestick data pattern. So some products has the values to 4/5 decimal places and some 2 decimal places. 
So it should be dynamic like whenever the product has values to 4 decimal places it should show like that, when there are 3 decimal places then it should modify itself.

Currently I am doing like this:
`    root.numberFormatter.set("numberFormat", "#,###.00"); `

for Value and Volume axis:
```
    var valueAxis = mainPanel.yAxes.push(
      am5xy.ValueAxis.new(root, {
        renderer: am5xy.AxisRendererY.new(root, {
          pan: "zoom",
          strokeOpacity: 1,
          strokeWidth: 1,
          stroke: am5.color("#474747"),
        }),
        extraMax: 0.1,
        tooltip: am5.Tooltip.new(root, {}),
        numberFormat: "#,###.00",
        extraTooltipPrecision: 2,
      })
    );
    
        var volumeValueAxis = mainPanel.yAxes.push(
      am5xy.ValueAxis.new(root, {
        numberFormat: "#.#a",
        height: am5.percent(20),
        y: am5.percent(100),
        centerY: am5.percent(100),
        renderer: volumeAxisRenderer,
      })
    );
    
```

**Comment by martynasma** [comment]
There's a number of ways to set number formats for each series individually.

1) Create individual instance of `NumberFormatter` for each series:

```JavaScript
var series = chart.series.push(
  am5xy.LineSeries.new(root, {
    xAxis: xAxis,
    yAxis: yAxis,
    valueYField: "value",
    valueXField: "date",
    tooltip: am5.Tooltip.new(root, {
      pointerOrientation: "horizontal",
      labelText: "{valueY}",
      numberFormatter: am5.NumberFormatter.new(root, {
        numberFormat: "#,###.##"
      });
    })
  })
);
```

2) Use in-line number formats:

```JavaScript
var series = chart.series.push(
  am5xy.LineSeries.new(root, {
    xAxis: xAxis,
    yAxis: yAxis,
    valueYField: "value",
    valueXField: "date",
    tooltip: am5.Tooltip.new(root, {
      pointerOrientation: "horizontal",
      labelText: "{valueY.formatNumber('#,###.##')}"
    })
  })
);
```

**Comment by workingbuddy10** [comment]
Are there any limitations in making the decimal places on the y-axis dynamic? As currently its fixed to two places for all product.
Ideally, it should be dynamic and based on the products. We can't fix it to a specific decimal place, such as two or four. There are products where the minimum price increment is as low as 0.001 or even 0.00001.

So can we achieve this? 
@martynasma

**Comment by martynasma** [comment]
I'm not entirely sure I understand your question.

Decimals are not fixed by default.

If you explicitly specify a number format, you can specify number of decimals, too.

**Comment by workingbuddy10** [comment]
Like I have set of 2000 products, so there are some products which have OHLC values up to 4-5 decimal places and some products have 2-3 decimal places OHLC values.
So if I pre-defined the decimal number to 2 decimal places like this ( "#,###.00"), then how come the products which has 4-5 decimal OHLC values will be displayed ?
@martynasma

**Comment by martynasma** [comment]
If you don't need rounding up of decimals, you don't need to include it into number format.

Or, as I mentioned, don't specify number format at all.
