### ISSUE TITLE
Data point issue in the candlestick

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1171]
Some of the candlestick doesn't show the OHLC values in the legender like in the image shown, as there is no Data at that Time Interval the candle is made.

For Example : 
Candle of 2nd November, at 22:00  
Candlestick Chart :
![image](https://github.com/amcharts/amcharts5/assets/137867461/747ac8ff-6f4a-47c4-b3ad-01c470024c3d)

But in my DB there is no Data at  2nd November, at 22:00. And the candle which you are able to see its of data at  2nd November, at 23:00.
Snap shot the data:
![image](https://github.com/amcharts/amcharts5/assets/137867461/f9689a3e-7cd6-4d1c-85e3-80aac3c83f79)

**Comment by martynasma** [comment]
To begin with, the data needs to be ordered in ascending order. If your actual data is the same as in your screenshot, it appears unordered, which can lead to all kinds of anomalies.

If ordering data does not help, please consider posting your chart as a CodePen, so that we can take a look.

**Comment by workingbuddy10** [comment]
I believe there is some issue with my chart initialization only, as whenever the DAY changes the last candle displays that it is the data of the the current data but originally the data is of the next day.

Just wanted to know/ask possibly where it can go wrong? Though I am attaching the code pen link, it won't show any chart it will just give you a brief about amcharts candlestick initialization. 
https://codepen.io/Ansh-m-the-reactor/pen/jOdmEvK


Example:
There is no data of 8th November, at 23:00 in the data screenshot, where as in the chart it's showing that candle. In reality that candle is of next day (9th November 00:00) .

data screen  shot:
![image](https://github.com/amcharts/amcharts5/assets/137867461/3b7701c2-8b1b-47a1-8f04-a975c9716f60)

candle screen shot:
![image](https://github.com/amcharts/amcharts5/assets/137867461/67a91acc-95ac-40ac-9c56-52b185173891)

 @martynasma
