### ISSUE TITLE
I can't set endValue in an already created range

### ISSUE THREAD

**Issue by lucasalmeida92** [amcharts/amcharts5#1173]
I created this range:
```js
let rangeDataItem = yAxis.makeDataItem({
    value: lastTick.value,
    above: true,
  } as any); // TO DO: Fix type
  const range = yAxis.createAxisRange(rangeDataItem);
```

and for some reason I can't set the `endValue` setting:
```js
rangeDataItem.set('endValue', lastTick.value + 10);
```
![image](https://github.com/amcharts/amcharts5/assets/5767871/ca87a3ea-6362-44f7-ae3e-fe2f0788b760)

I'm trying to update this already created range so I can show a gradient(`axisFill`) above or below my range line(`grid`).

**Comment by xorspark** [comment]
You have to make the change on the range, not the rangeDataItem:

```
range.set('endValue', lastTick.value + 10)
```
