### ISSUE TITLE
Date Range Selector Query

### ISSUE THREAD

**Issue by Suleman12** [amcharts/amcharts5#1175]
I want in my Am Charts 5 Code to Extract Date from the Date Range Selector when  a User Clicks Apply and Fetch the Data for that Date Only. How Can I achieve this in Am Charts 5 . Are there any On Event Function that I can Use for Date Range Selector so I can handle this use case. If Date Range Selector Doesn't have On Event Function how can I use a customised Date Picker in Am charts 5 Code instead of Date Range Selector.

**Comment by xorspark** [comment]
There isn't a direct setting to get the apply button, but you can query the DOM element from the DateRangeSelector's private [`dropdown`](https://www.amcharts.com/docs/v5/reference/daterangeselector/#dropdown_setting) setting and access the DateRangeSelectors private [`fromDate`](https://www.amcharts.com/docs/v5/reference/daterangeselector/#fromDate_setting) and [`toDate`](https://www.amcharts.com/docs/v5/reference/daterangeselector/#toDate_setting) settings to get the selected values as Date objects: 

```
var dateRangeSelector = am5stock.DateRangeSelector.new(root, {
  stockChart: stockChart
});
// ...
dateRangeSelector.getPrivate('dropdown').get('parent').querySelector('input.am5-modal-primary').addEventListener('click', (event) => {
  console.log(dateRangeSelector.getPrivate('fromDate')) 
  console.log(dateRangeSelector.getPrivate('toDate'))
})
```

You can't stop the zoom from triggering, however.
