### ISSUE TITLE
Toggle series on multiple charts using same legend

### ISSUE THREAD

**Issue by KokKeong123** [amcharts/amcharts5#1177]
I am having dynamic number of charts in one page and i want all the charts to shared a legend so when clicking the legend can toggle series on all the charts, but currently in amcharts5 documentation it only shows how to create a legend for single chart. I've found similar tutorial demo but it's only for amchart4 plus the number of chart is fixed. How to code this in amchart5?
https://codepen.io/team/amcharts/pen/VwwNMWN

Can please help?
Thank you

**Comment by xorspark** [comment]
You can use the global chart registry to check every chart's series and use the series' `visible` callback to toggle/show the associated series accordingly:

```
      series.on('visible',(visible) => {
        am5.registry.rootElements.forEach((rootElement) => {
          if (rootElement.dom.id == root.dom.id) {
            return
          }
          let checkChart = rootElement.container.children.getIndex(0)
          for (let checkSeries of checkChart.series) {
            if (checkSeries.get('name') == series.get('name')) { 
              if (visible) {
                checkSeries.show()
              }
              else {
                checkSeries.hide()
              }
              break
            }
          }
          
        })
      })
```

Demo:  https://codepen.io/team/amcharts/pen/jOdmaNO/00d5b93c3cb501a3d2c0fd8da24515be?editors=0010

**Comment by KokKeong123** [comment]
Hi @xorspark ! ah yes, this is what i need. I didn't know we can use `am5.registry.rootElements` to select all chart. I will test it out and update if it's work for me. Thank you so much!
