### ISSUE TITLE
How can I apply cornerRadius property to a Tooltip?

### ISSUE THREAD

**Issue by suu3** [amcharts/amcharts5#1179]
**Question**
Hello, I would like to round the border-radius of the rectangular part of the tooltip more. However, there is no property like cornerRadiusTL for the Tooltip.
I tried to solve it with 'tooltipHtml' property, but when I added the CSS position property to the pointer part of the tooltip bubble in the HTML, it didn't render correctly.
Could you add the cornerRadius property to the tooltip, or if there's another solution, please let me know?

Thank you.

**Comment by zeroin** [comment]
By default tooltip's background is a PointedRectangle:
https://www.amcharts.com/docs/v5/reference/pointedrectangle/

And it has cornerRadius setting (no separate settings for each corner). So you can do this:

`tooltip.get("background").set("cornerRadius", 10);`

**Comment by suu3** [comment]
Ok, thank you, it works well.

But when I use` tooltip.('...').get('...').set()` or `tooltip.('...').setAll()` in TypeScript, I encounter an error that says **"Argument of type '"cornerRadius"' is not assignable to parameter of type 'keyof IGraphicsSettings'."**

It seems like the type is specified as `Settings.setAll(settings: Partial<am5.IGraphicsSettings>): void.`

Is there any way to resolve this issue?
