### ISSUE TITLE
Maps `menuitem` ARIA bug

### ISSUE THREAD

**Issue by Malvoz** [amcharts/amcharts5#118]
I noticed in https://www.amcharts.com/svg-maps/?map=iceland that the different region paths have `role="menuitem"`

https://www.w3.org/TR/wai-aria-1.1/#menuitem:

> Authors **_MUST_** ensure that menu items are owned by an element with role `menu` or `menubar` in order to identify that they are related widgets.

I'm not certain a menu with menuitems is desired, see https://www.w3.org/TR/wai-aria-practices-1.1/#menu (and the expected [keyboard interactions](https://www.w3.org/TR/wai-aria-practices-1.1/#keyboard-interaction-12)) for more info.

**Comment by martynasma** [comment]
I'm sorry, but I must mark this as off-topic, because this has nothing to do with amCharts 5.

That particular page uses amCharts 3, which has been deprecated years ago, and will not be updated.
