### ISSUE TITLE
overlapping chart and volume data

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1180]
In the below attachment in candlestick chart we can see the chart candle and the volume candle is getting overlapped at some point (where price is low and volume is high). I have some products which has higher volume candles with low prices, and most of them are overlapping.
Even though there is a lot of space above left.

Example:
I don't even have any timestamp with this 4500 range, yet there is a point in y-axis. **I want my candlestick to be shifted bit above, so there is no overlapping.**

![image](https://github.com/amcharts/amcharts5/assets/137867461/f72a4040-939d-437b-a02d-ed95768ef007)

**Comment by zeroin** [comment]
The only 100% way to avoid overlapping would be to to put volume in a separate panel:
https://www.amcharts.com/demos/separate-volume-panel/

You could also set `extraMin` value for the main series value axis to 0.1 or some other value (0.1 means 10% of the value axis minimum value will be less than calculated by 10% of the max-min difference. This will give more space in the bottom.
