### ISSUE TITLE
Chart Excess Zoom issue

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1182]
I am trying to pre-zoom my chart, even though I am giving the end date of the last timestamp yet the last candle is shifted towards the right. I believe chart is getting access zoom.

My usecase : Initially I want last 10 points to be zoomed-in (pre-zoom).

Example:
 Code part : 
(in the code these dates are in unix format)
 Start date = Tuesday, October 31, 2023 12:00:00 AM
end date =  Monday, November 13, 2023 12:00:00 AM 
   
```
    // Create a main stock panel (chart)
    var mainPanel = stockChart.panels.push(
      am5stock.StockPanel.new(root, {
        wheelY: "zoomX",
        panX: true,
        panY: true,
        height: am5.percent(90),
      })
    );
    var valueAxis = mainPanel.yAxes.push(
      am5xy.ValueAxis.new(root, {
        strictMinMax:true,
        renderer: am5xy.AxisRendererY.new(root, {
          pan: "zoom",
          strokeOpacity: 1,
          strokeWidth: 1,
          stroke: am5.color("#474747"),
        }),
        extraMin: 0.1,
        tooltip: am5.Tooltip.new(root, {}),
        extraTooltipPrecision: 2,
      })
    );
        var dateAxis = mainPanel.xAxes.push(
      am5xy.GaplessDateAxis.new(root, {
        baseInterval: {
          timeUnit: timeUnits,
          count: timeUnits === "minute" ? 30 : 1,
        },
        renderer: am5xy.AxisRendererX.new(root, {
          strokeOpacity: 1,
          strokeWidth: 1,
          stroke: am5.color("#474747"),
        }),
        tooltip: am5.Tooltip.new(root, {}),
      })
    );
        valueSeries.events.once("datavalidated", function(ev) {
      var startDateUnix = 1698710400000;
      var endDateUnix = 1699833600000;  
         
      // Convert Unix timestamps to Date objects
      var startDate = new Date(startDateUnix);
      var endDate = new Date(endDateUnix);
    
      ev.target.get("xAxis").zoomToDates(startDate, endDate);
    });
```

Image :
Currently it's showing like this (it seems that end date is of 10th November) :
![image](https://github.com/amcharts/amcharts5/assets/137867461/949bb7a1-3206-46f5-92a2-172d4243836d)

Ideally it should be like this (but the end date is 13th November): 
![image](https://github.com/amcharts/amcharts5/assets/137867461/27e0c10a-bfea-4b46-8734-bba681177710)

**Comment by zeroin** [comment]
When zooming, you should add a duration of one period (or more if you want) to the last data items timestamp - the axis zooms to the exact timestamp you provided, and it's the beginning of the last date. You can get the duration of current interval from the axis: `axis.intervalDuration()`

**Comment by workingbuddy10** [comment]
Exactly what should I do fix this issue? Sorry I wasn't able to get your point.
@zeroin

**Comment by workingbuddy10** [comment]
Thanks @zeroin it worked for me!!!

**Comment by workingbuddy10** [comment]
Hello @zeroin I am trying to use the same thing in a button like whenever the user clicks on the button it will zoom-in to last 30 candles. But the issue is the last/most recent candle was getting missed as it was getting shifted to the right side (like shown in the above images, same issue).
So I tried to add **dateAxis.intervalDuration()** but I am getting an error as :
![image](https://github.com/amcharts/amcharts5/assets/137867461/fc91f1dc-47fb-463b-8b26-f2943afdfaa7)



Sample Data:
```
{
      Date: 1696982400000,
      Open: 4392,
      High: 4419.75,
      Low: 4377.25,
      Close: 4409.75,
      Volume: 1489644
    },
    {
      Date: 1697068800000,
      Open: 4417.75,
      High: 4430.5,
      Low: 4355.5,
      Close: 4380.5,
      Volume: 1881573
    },
```
Code : 
```
  var button = mainPanel.plotContainer.children.push(
      am5.Button.new(root, {
        paddingTop: 5,
        paddingBottom: 5,
        paddingLeft: 5,
        paddingRight: 5,
        icon: am5.Picture.new(root, {
          interactive: true,
          width: "10",
          height: "10",
          src: "https://img.icons8.com/ios/15/circled-chevron-right--v1.png",
          cursorOverStyle: "pointer",
        }),
      })
    );
    mainPanel.plotContainer.onPrivate("width", function (width) {
      button.set("dx", width - 30);
    });
    mainPanel.plotContainer.onPrivate("height", function (height) {
      button.set("dy", height - 30);
    });
    button.events.on("click", function (ev) {
      var last10DataPoints = data.slice(-30);
      if (last10DataPoints.length) {
        var n = last10DataPoints.length;

        var startDate = last10DataPoints[0].Date;

        var endDate = last10DataPoints[n - 1].Date;
        dateAxis.zoomToDates(
          new Date(startDate),
          new Date(endDate) + dateAxis.intervalDuration()
        );
      }
    });
    button.get("background").setAll({
      fill: am5.color("#64788d"),
    });
```

**Comment by workingbuddy10** [comment]
@zeroin can you please re-open this issue for this part!

**Comment by zeroin** [comment]
Can you post a working codepen so I could work with the exact case?

**Comment by workingbuddy10** [comment]
No I can't provide the whole working codepen, as my usecase is too big. But ya I can provide you my amchart rendering portion only.
Code pen link: https://codepen.io/Ansh-m-the-reactor/pen/oNmqZgj

**Comment by workingbuddy10** [comment]
But ya when I don't add these (dateAxis.intervalDuration() OR +600000 ), then I don't recieve that error. But that spacing issue comes.
@zeroin

**Comment by zeroin** [comment]
I will still need some case where this can be reproduces, a simplified one will be even better than your full source code, I am afraid I can't help otherwise.
