### ISSUE TITLE
Chart spacing

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1184]
How to convert this period selector in the drop-down format? Is there any in-built  feature to do this, if not then exactly which class should I target & what should I change in the CSS property.

As there can be more granular level period selector, so it will occupy whole space.

Image reference:
![image](https://github.com/amcharts/amcharts5/assets/137867461/b005e743-2ff2-4d64-93ff-76adf98eb246)

**Comment by martynasma** [comment]
There's no built-in way to convert this to a dropdown.

You may consider implementing your own chart control though:
https://www.amcharts.com/docs/v5/charts/stock/toolbar/dropdown-list-control/

You could catch its events and use standalone instance of `PeriodSelector` to do actual zooms:
https://www.amcharts.com/docs/v5/charts/stock/toolbar/period-selector/#Standalone_usage_API

Hope it makes sense.
