### ISSUE TITLE
How to specify correct order of Links in Sankey Diagram?

### ISSUE THREAD

**Issue by JessieNguyen** [amcharts/amcharts5#1185]
Hi, 
This is my first time asking question on github so I hope I can explain my question clear enough.

I'm plotting my data using Sankey Diagram:

https://codepen.io/jessienguyen123/pen/mdvMaPo
![image](https://github.com/amcharts/amcharts5/assets/12731788/2ea459da-f78d-4bc7-aad6-4adf57ac1cc4)

My data is stored in the _data_ variable.

According to the documentation, the actual Links in the Diagram will be drawn in exactly the same order as they are defined in data. 

I have purposely ordered my data so that there's least crisscross as possible. For example, the links are sorted as:
- Links from Story 1 to b1
- Links from Story 2 to b1
- Links from Story 3 to b1
- etc. 

However, the links shown in the diagram does not appear in the same order that I need. I expect links from story 2 will not crossed link from story 3, and so on.

Could you please help to guide me on how to make the links plot with as little crisscrossing as possible?
Thanks.

Jessie

**Comment by martynasma** [comment]
You may find this tutorial useful:
https://www.amcharts.com/docs/v5/charts/flow-charts/sankey-diagram/#Link_sort_order

**Comment by JessieNguyen** [comment]
Thank you for the link. It works now!

**Comment by JessieNguyen** [comment]
Thanks for the link! It works now :)
