### ISSUE TITLE
Stock Chart Scroollbar Zoom Query

### ISSUE THREAD

**Issue by Suleman12** [amcharts/amcharts5#1186]
In My Code I am Initializing the Scrollbar like this :

```JavaScript
var scrollbar = mainPanel.set("scrollbarX", am5xy.XYChartScrollbar.new(root, {
  orientation: "horizontal",
  height: 50
}));
stockChart.toolsContainer.children.push(scrollbar);
mainPanel.bottomAxesContainer.children.push(scrollbar);
var sbDateAxis = scrollbar.chart.xAxes.push(am5xy.GaplessDateAxis.new(root, {
  baseInterval: {
    timeUnit: "day",
    count: 1
  },
  renderer: am5xy.AxisRendererX.new(root, {})
}));
```
 
In my Graph My Data Loads for the Intraday as well as Historical Values. When My Graph Loads For the Historical Values  the Scroll bar  Shows Days Values and  When User Selects a single day  Graph shows Intraday Values in Minutes as I change the Dateaxis baseinterval time unit to minutes .The Issue is Scrollbar Zoom is Showing all of the Values for the Days Cases i.e the Scrollbar is Zoomed on all of the data that is returned. But for Intraday in Minutes it Only shows the First Few Values . Let me Attach Screenshots for Reference. How Can I change that for in case of intraday case.

![scroolbarzoom](https://github.com/amcharts/amcharts5/assets/24837687/666ea7c6-03c3-4266-b240-73c561e63547)
![zoomscroollbar3](https://github.com/amcharts/amcharts5/assets/24837687/7de723b3-fdef-4ebe-a587-fccc083f5e2f)

![scroolbarzoom2](https://github.com/amcharts/amcharts5/assets/24837687/b4d5e891-1f6e-4740-9055-3ccbc2db2375)

**Comment by martynasma** [comment]
How would you like it to behave? Show the whole range (almost a year) of daily graph in scrollbar, and have a day worth of intraday data bunched up at the end in the chart itself?

If that is the case, you will need to either supplement the data for the intraday series with the starting value into the past so the chart keeps yearly range, as the scrollbar series data scope does not affect actual chart's scope.

**Comment by Suleman12** [comment]
In My Graph Basically the Data is being Updated Every time  a User Selects a date. My Chart Gets Updated with New Data and so Does my scrollbar when User Clicks Apply after Selecting a date. For Example Like this 
![picture1](https://github.com/amcharts/amcharts5/assets/24837687/422b0997-ee23-43cd-904e-2046257faccf)
![picture2](https://github.com/amcharts/amcharts5/assets/24837687/48575dee-dd23-4895-9ef9-bf9b36a51098)
 As You See in the Picture One User Selects A date between May and October so the Data Gets updated in the Chart as well as the scrollbar and the Scroll bar Zoom is between the Selected Dates .That works Fine.
Now If A User Selects The Same Date in Both To and From We are basically now Showing Intraday Values to the User for which the Time unit is Minutes .For Example like this 
![picture3](https://github.com/amcharts/amcharts5/assets/24837687/77b13584-6551-4880-b0b8-878c4776fe3f)
![picture4](https://github.com/amcharts/amcharts5/assets/24837687/34070407-bcdb-4c55-ab1b-176f409c66f3)

 In Case of Same Date we Update the Dateaxis so Now the Data is Displayed in Minutes in the Scrollbar as you see in the 4th Picture. Issue is the ScrollbarZoom on the Intraday . It Just Zooms in Randomly sometimes at the beginning sometimes at the end and shows only a few values.
I want it like this:
![picture5](https://github.com/amcharts/amcharts5/assets/24837687/64363595-379b-47cf-ac58-d4b35a03b658)
Like By Default it Should Show the Max Zoom in Case of Intraday when Time unit is minutes also. How can I achieve That.

**Comment by Suleman12** [comment]
I am Attaching Code on Codepen. But the Code will not work as the Ajax calls will not execute on code pen environment .Can you Please review the code js and  that if you find any issue logically .Thanks.

https://codepen.io/Suleman12-the-vuer/pen/abXWQoJ

**Comment by Suleman12** [comment]
I have placed the code of working chart on the following code pen link.
https://codepen.io/Suleman12-the-vuer/pen/MWLrmYJ?editors=1111
 How you can test is graph loads initially for day values .You can try to select the same date in to and from in the date range selector and then you would see the intraday values and the zoom issue that is triggered.Thanks
Attaching screenshots for Refrence.
![Screenshot 2023-11-17 182942](https://github.com/amcharts/amcharts5/assets/24837687/d4d4f90c-5919-4a57-b7e9-6f37a064b163)
![Screenshot 2023-11-17 183027](https://github.com/amcharts/amcharts5/assets/24837687/b5cbbea2-601f-407e-a462-b68e0ce6c8a8)

**Comment by Suleman12** [comment]
We have tried to use    
valueSeries.events.once("datavalidated", function() {
				

			sbDateAxis.zoomToValues(sbDateAxis.getPrivate("selectionMin"), sbDateAxis.getPrivate("selectionMax"));
				dateAxis.zoomToValues(dateAxis.getPrivate("selectionMin"), dateAxis.getPrivate("selectionMax"));
				  
				  })

in the Date range selector function but this only works for the first time when we switch then it shows the wrong zoom again the next time.

**Comment by martynasma** [comment]
I'm sorry but I don't understand the issue. When you select Nov 2 date, you load new data that goes up to Oct 1. The chart displays it correctly.

At this point, I'm not sure if we can continue this conversation here, as it does not seem like a bug or a generic question.

If you do have a support subscription with us, please contact us directly at contact@amcharts.com

**Comment by Suleman12** [comment]
Hello The Issue got resolved  .I used this property on   my data load function this made the chart and scrollbar to zoom out to the maximum value.
 valueSeries.events.once("datavalidated", function() {				
				  mainPanel.zoomOut();					  
				  })
Issue was with the chart zooming randomly on random values.Thanks
