### ISSUE TITLE
Instance of Picture Class Displays in Different Sizes on PC and Laptop

### ISSUE THREAD

**Issue by koorizhizhi** [amcharts/amcharts5#1187]
**Question**
Hi, I was asked to add a table to my line chart so I used a solution as below:
1. I firstly create a SVG table image:
 
`let svgData = '<svg><foreignObject x="0" y="0" width="100%" height="100%">some table definitions</foreignObject></svg>';`
`const tableData="data:image/svg+xml;base64,${window.btoa(svgData)}";`

2. Then I create a Picture instance with my table data and get it pushed as a child of my line chart( with both width and height explicitly declared):

`let pic = chart.children.push(am5.Picture.new(root, {`
`    width: 250,`
`    height: 160,`
`    x: 130 / 720 * maxWidth,`
`     y: 12,`
`    centerX: am5.percent(0),`
`    centerY: am5.percent(0),`
`    src: tableData,`
` }));`

It works and displys exactly as what I want on my PC (display resolution: 1920 x 1080) (on Microsoft Edge/Google Chrome):
![image](https://github.com/amcharts/amcharts5/assets/83855880/b323a817-c225-4054-baf0-17100d783c7a)

But a tester has reported an issue that the table is tool small looking from her laptop (ASUS zenbook ux501vw) (on Microsoft Edge):
![image](https://github.com/amcharts/amcharts5/assets/83855880/fac16ad1-ef23-43cf-909f-787da160dcfb)

And the size of table is fixed but everything else is getting larger when I zoom in.
I have no idea what caused the issue...
I would very much appreciate your support if you can help me fix it.

**Environment (if applicable)**

**Additional context**

**Comment by koorizhizhi** [comment]
> That table looks like it is being placed outside of the chart. Why make it a chart element at all? You can just place a regular table in HTML. Just an idea.

Hi, thank you for sharing with me the idea. But I was wondering why the picture displays in 2 different sizes. Does it has anything to do with the screen resolution of a device?

**Comment by martynasma** [comment]
It depends on how your page is set up, including CSS. Since I cannot see your whole code, I can't tell for sure.
