### ISSUE TITLE
Stacking Issues with multiple series & different data objects

### ISSUE THREAD

**Issue by m4w** [amcharts/amcharts5#1189]
AmCharts version 5

Missing data provides a wrongly stacked column chart. 

<img width="958" alt="image" src="https://github.com/amcharts/amcharts5/assets/1598385/21c980bd-2cef-40ec-b160-4fe2035385ab">

I created a [codepen example](https://codepen.io/m4w/pen/poGpRLQ) which shows the problem quite clearly. 
To reproduce you need the following
1) create two different data-objects, both of them cover the same time-frame, but one of them has a gap
2) create a XY-Chart, with one valueAxis and one dateAxis
3) create two series, with the same configuration but different data-objects, enable stacking
4) as a result the data-points are correctly positioned on the dateAxis, but the stacking-algorithm doesn't take into account that a value is missing on a specific time-slot.

**Comment by zeroin** [comment]
With stacked series, you must provide the same data set for all series in order data items to be stacked properly. We warn about this in our docs: https://www.amcharts.com/docs/v5/reference/ixyseriessettings/#stacked_property

**Comment by m4w** [comment]
Alright. I see. Thanks for the info.
I guess, we have to accept it. 
But I have the feeling the issue shouldn't be that big for you to fix, since the data is correctly placed at the dateAxis. I haven't looked into your implementation. Maybe it would require a huge refactoring, but that would surprise me. 
It seems to me, that you are delegating a problem you do not want to solve to your paying customers. 
Aligning that data before we pass it to amCharts is very hard. Since we do not know if and were we are missing values. Therefore we have to compare each series (could be many) and each data point (could be even more) with each other to find one missing data point and fill it with a zero. 

I would very appreciate if you would overthink this restriction.

**Comment by zeroin** [comment]
Merging data inside amCharts would be a lot more complicated and would require a lot more CPU usage than doing it outside. In my opinion it's really easy, here is a modified pen:

https://codepen.io/team/amcharts/pen/Rwvxvdw/205aeed77e8f5d9718453c1027fef4da

Method which does the thing:

```
var mergedData = [];

mergeData(data);
mergeData(dataAsia);

function mergeData(data){
  am5.array.each(data, function(item){
    var found = false;
    am5.array.each(mergedData, function(item2){
      if(item2.time == item.time){
        found = true;
        am5.object.each(item, function(key, value){
          if(value != undefined){
            item2[key] = value;
          }
        })
      }
    });
    if(!found){
      mergedData.push(item);
    }
  });
}
```

If this doesn't cover your scenario, I could take a look if you could created a codepen with a real scenario you use.

**Comment by martynasma** [comment]
FYI, just posted this tutorial with improved data merging function:
https://www.amcharts.com/docs/v5/tutorials/stacking-series-with-mismatched-categories-dates/

**Comment by m4w** [comment]
Thanks for your code example, although it isn't usable for us, since we have a dynamic set of series which are stacked together and this kind of merging to way to complex (cyclomatic complexity).
I found a solution, which should work fine. At least it should reduce the gaps to a very little number of edge cases.

My solution:
Assumptions: 
1) All series should have the same length 
2) All series should have data points from the same time frame 

- Calculate the timeOffset between two data points
- Go through each data set of each series
     - Identify missing datapoint
     - Inject a new datapoint with the correct time & empty data set
- Add extended data set to series

Thanks for your support.
