### ISSUE TITLE
site bug: invalid ARIA `role="nav"`

### ISSUE THREAD

**Issue by Malvoz** [amcharts/amcharts5#119]
(Not sure this is the correct repo to file site bugs)

The site's navbar uses `role="nav"`, the correct role (and implicit role of the `<nav>` element) is [`role="navigation"`](https://www.w3.org/TR/wai-aria-1.1/#navigation).

**Comment by martynasma** [comment]
Good catch.

Since this is not related to amCharts 5, I'm gonna go mark it as offtopic and close. But thanks!
