### ISSUE TITLE
Amcharts5 button

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1191]
I want to remove/disappear the button when I am already at the recent or zoom-in point. 
My custom button code:

```
var button = mainPanel.plotContainer.children.push(
      am5.Button.new(root, {
        paddingTop: 5,
        paddingBottom: 5,
        paddingLeft: 5,
        paddingRight: 5,
        hoverOnFocus: false,
        icon: am5.Picture.new(root, {
          interactive: true,
          width: 15,
          height: 15,

          src: "/t3.png",
          cursorOverStyle: "pointer",
        }),
      })
    );
    mainPanel.plotContainer.onPrivate("width", function (width) {
      button.set("dx", width - 30);
    });
    mainPanel.plotContainer.onPrivate("height", function (height) {
      button.set("dy", height - 30);
    });
    button.events.on("click", function (ev) {
      var last10DataPoints = data.slice(-30);
      if (last10DataPoints.length) {
        var n = last10DataPoints.length;

        var startDate = last10DataPoints[0].Date;
        //TODO: restructure hardcoded unix ms to dynamic
        var endDate = last10DataPoints[n - 1].Date + 86400000;
        dateAxis.zoomToDates(new Date(startDate), new Date(endDate));
      }
    });
    button.get("background").setAll({
      fill: am5.color("#CFCFCF"), 
      blur: 5, 
      opacity: 0.7, 
    });
```

And also when you EXACTLY CLICK ON THE ICON INSIDE THE BUTTON (place the pointer to the lines of the icon) the zoom-in doesn't work attaching the codepen for this and also remove / disappear the button when I am already at the recent or zoom-in point. 

codepen link:  https://codepen.io/Ansh-m-the-reactor/pen/dyamvrR

**Comment by workingbuddy10** [comment]
@zeroin Maybe this can be helpful! How can we fix this.

**Comment by martynasma** [comment]
```JavaScript
dateAxis.on("end", function(end) {
  if (end >= 1) {
    button.hide();
  }
  else {
    button.show();
  }
})
```

To make button clickable on all of it, remove `interactive: true` from your icon definition.

**Comment by martynasma** [comment]
Pay closer attention to the code snippet 😉

`1` means end. Not 100.

**Comment by workingbuddy10** [comment]
I got your point @martynasma, I want when I am at last 100 candle points then I don't want my button to be visible but whenever I scroll and my number of data points get more than 100 candles it should appear.

My purpose of button is to get the user to recent 100 candles, so if the user is already at recent 100 candles then there is no use of showing the button. Isn't?

I have already applied the button zoom-in feature to last 100th candles, it just I want to disappear the button. 
https://codepen.io/Ansh-m-the-reactor/pen/dyamvrR

**Comment by martynasma** [comment]
If you start your chart pre-zoomed, then you can initially hide your button with `button.hide()` as soon as you create it.

**Comment by workingbuddy10** [comment]
Sure that can be a way,
But how can I make it again  visible when I am not at last nth candles ( let's say last 100 candles/data points). Or I zoomed-out.

Like the user is already at last/recent 100 candles then do not show the button and when user zoomed-out via scroll or by shifting the chart to right then the button should appear so that user can again come back to the recent 100 candles.

And my chart is pre-zoomed to last 100th candles, so initially I can hide the button. But how can make it again visible when user zoomed-out and then again user zoomed-in then disappear the button.

@martynasma

**Comment by martynasma** [comment]
That's where [this code](https://github.com/amcharts/amcharts5/issues/1191#issuecomment-1822259425) comes in.
