### ISSUE TITLE
Date Range Selector Disabling Dates Query

### ISSUE THREAD

**Issue by Suleman12** [amcharts/amcharts5#1192]
This is how I initialize my date range selector. The Query is I want to disable Friday and Saturday of Every week in the calendar because in my data there are no values for these 2 days across every week. So when User Selects these dates in Case of Intraday Chart It sets Values to 0/null. Is there any functionality in date range selector where you can disable specific days in the Calendar.

var dateRangeSelector = am5stock.DateRangeSelector.new(root, {
			  stockChart: stockChart,
			  minDate: new Date(2016, 2, 1),
		      maxDate: null
			});

**Comment by martynasma** [comment]
No, I'm afraid there's no way to disable certain days from selection in date range selector 🙁
