### ISSUE TITLE
XY chart labels

### ISSUE THREAD

**Issue by RavidAtiasAxonius** [amcharts/amcharts5#1193]
Hi
I have XY chart with CategoryAxis.
I set label HTML by plain HTML and CSS : 
<img width="525" alt="Screenshot 2023-11-22 at 10 04 50" src="https://github.com/amcharts/amcharts5/assets/111275139/70fc9203-ba33-472d-b448-ba48d127717a">

My issue is when I decrease widget size, HTML has CSS property of display:none and it is not visible.
What can I do to prevent that and decide by myself if I should or should not display the HTML label?

**Comment by martynasma** [comment]
Maybe create a responsive rule?
https://www.amcharts.com/docs/v5/concepts/responsive/
