### ISSUE TITLE
Y-axis spacing in Stockchart

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1194]
I want some space between my last candle and the Y-axis, in Stock chart. I tried adding **endLocation** and **cellEndLocation** in my dateAxis. It didn't worked.

Attaching codepen link: https://codepen.io/Ansh-m-the-reactor/pen/dyamvrR 

![image](https://github.com/amcharts/amcharts5/assets/137867461/85bdee5a-bd9e-4434-92f8-8631ab5577c0)

**Comment by martynasma** [comment]
Use `extraMax` instead:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#relative-scope-extension

**Comment by martynasma** [comment]
Gotcha. Ok, `extraMax` does not work on a `GaplessDateAxis`.

In that case you need to use `endLocation` set to a higher number, e.g. 10:

```JavaScript
var dateAxis = mainPanel.xAxes.push(am5xy.GaplessDateAxis.new(root, {
  endLocation: 10,
  // ...
});
```

**Comment by workingbuddy10** [comment]
Did what you said @martynasma , though now we can achieve the space between the last candle and Y-axis but the feature of the custom button stopped working.

(Use case of the button is to move/zoom-in the chart to last nth candles).

You can check here : https://codepen.io/Ansh-m-the-reactor/pen/dyamvrR

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.

**Comment by workingbuddy10** [comment]
It's just adding extraMax lead to disturbing other feature.
@martynasma

**Comment by workingbuddy10** [comment]
In the DateAxis.d.ts file its written that IMPORTANT: `endLocation` is not supported by [[GaplessDateAxis]].

![image](https://github.com/amcharts/amcharts5/assets/137867461/249c0fbd-08f0-456a-be28-7df0d30fcdbe)

@martynasma

**Comment by martynasma** [comment]
You're right. My bad.

In that case, the only way to do the extension of the GaplessDateAxis is to add additional data items to your data for the days you want to extend it.

**Comment by martynasma** [comment]
What kind of issues do you expect? You don't have to add values, just need the extra data items for future dates.

https://codepen.io/team/amcharts/pen/abXjBZb/cfe824e6774620c6f9cefabae19e3ae4?editors=0010

**Comment by workingbuddy10** [comment]
It would have been great if there is something in-built for GaplessDateAxis too, like for XY chart series (endLocation ).
@martynasma

**Comment by workingbuddy10** [comment]
Thank you and Hats off   for your quick response and the updates ! @martynasma  & @zeroin  :clap:

- But I would to show you that still I am not able to achieve the space between the last candle and the Y-axis. 
- And In the pre-zoom in feature last candle only appears half.

Have a look to this codepen link: https://codepen.io/Ansh-m-the-reactor/pen/dyamvrR?editors=1010
