### ISSUE TITLE
tooltips are not shown by hovering inside a container with CSS style "transform: scale"

### ISSUE THREAD

**Issue by wj42ftns** [amcharts/amcharts5#1195]
**Bug description**
There is a little updated demo from: https://www.amcharts.com/docs/v5/concepts/common-elements/tooltips/#Without_cursor , where you can see that with "transform: scale" does not correctly triggered column "pointerover" event -> it's a reason why tooltips is not shown by hover column.
live demo: https://codepen.io/wj42ftns/pen/qBgYMoE?editors=0110
video demo: https://youtu.be/vwufow4qdp4

**Environment (if applicable)**
it reproduces in all browsers

**Additional context**
I see that in bar chart series.events.on("pointerover", ...) works correctly with "transform: scale" too, the problem inside series with columns.values[...].events.on("pointerover", ...) detection.
It happens not only with bar chart and columns. I see this happens also at least with Lines chart and showing tooltip on hover bullets.

**Comment by martynasma** [comment]
Please refer to this doc:
https://www.amcharts.com/docs/v5/getting-started/root-element/#Custom_sizing_function
