### ISSUE TITLE
Indicator tab On hover

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1197]
I don't want name on the indicator toolbar, but on hover it should appear as "Indicator" not as false.

It's is coming like this on hover:
![image](https://github.com/amcharts/amcharts5/assets/137867461/0e4e5beb-5a14-42ea-9247-3afd905a2e7e)

On hover it should appear as "Indicator", but there should be no name in the box too.
Code:
```
    var indicatorCntrl = am5stock.IndicatorControl.new(root, {
      stockChart: stockChart,
      legend: valueLegend,
      name: false,
    });
```

**Comment by martynasma** [comment]
Like this:

```JavaScript
var indicatorCntrl = am5stock.IndicatorControl.new(root, {
  stockChart: stockChart,
  legend: valueLegend,
  name: "",
  description: "Indicator"
});
```
