### ISSUE TITLE
 Value Axis Space

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1198]
I am using am5stock chart with GaplessDateAxis and I want to minimize the space taken by the Y-axis values in terms of width. As I am displaying multiple charts at that my Y-axis looks big and take more space which is not a good thing.

- How can I reduce the width of the Y-axis values?
- Is there any way from that I can achieve dynamic width. Like when I am one single chart it auto adjust and when I am on multi-cross layout it decreases the width of the Y-axis?

Image 1 when I am viewing single chart:
![image](https://github.com/amcharts/amcharts5/assets/137867461/59d8841c-a6c2-4be3-9fb0-22c37b10a54b)

Image 2 when I am on multi-chart layout, you can see chart's Y-axis is taking a lot of space.
![image](https://github.com/amcharts/amcharts5/assets/137867461/9664b9d0-a25e-4265-9834-8bba0eae3311)

code:
```
   mytheme
      .rule("RoundedRectangle", [
        "legend",
        "itemcontainer",
        "background",
        "stocklegend",
      ])
      .setAll({
        fillOpacity: 0,
      });
    mytheme.rule("AxisTick").setAll({
      stroke: am5.color(0xffffff),
      visible: true,
    });
    mytheme
      .rule("Container", ["legend", "itemcontainer", "stocklegend"])
      .setAll({
        paddingRight: 0,
        paddingTop: -20,
        paddingBottom: 17,
        paddingLeft: -10,
      });

    root.setThemes([
      am5themes_Animated.new(root),
      mytheme,
      am5themes_Dark.new(root),
    ]);

    // Create a stock chart
    var stockChart = root.container.children.push(
      am5stock.StockChart.new(root, {})
    );

    root.utc = true;

    // Create a main stock panel (chart)
    var mainPanel = stockChart.panels.push(
      am5stock.StockPanel.new(root, {
        wheelY: "zoomX",
        panX: true,
        panY: true,
        height: am5.percent(90),
      })
    );

    // Create value axis
    var valueAxis = mainPanel.yAxes.push(
      am5xy.ValueAxis.new(root, {
        renderer: am5xy.AxisRendererY.new(root, {
          pan: "zoom",
          strokeOpacity: 1,
          strokeWidth: 1,
          stroke: am5.color("#474747"),
        }),
        extraMin: 0.1,
        // extraMax:1,
        tooltip: am5.Tooltip.new(root, {}),
        extraTooltipPrecision: 2,
      })
    );

    valueAxis
      .get("tooltip")
      .get("background")
      .set("fill", am5.color(axisToolTipColor));
```

**Comment by workingbuddy10** [comment]
Thank you @martynasma it worked for me!

**Comment by workingbuddy10** [comment]
Just a small issue that decreasing the padding is hiding the label values. How can I decrease the label size? Of both dateAxis and valueAxis.
![image](https://github.com/amcharts/amcharts5/assets/137867461/5a5d8960-f259-40a2-9f50-ca75b82f1ce9)

I tried using this, but it didn't worked in both date/value axis:

```
    valueAxis
      .get("tooltip")
      .get("background")
      .set("fill", am5.color(axisToolTipColor));

    // valueAxis.set("tooltipText","[fontSize: 200px]");
```

@martynasma

**Comment by martynasma** [comment]
> How can I decrease the label size?

```JavaScript
valueAxis.get("renderer").labels.template.setAll({
  fontSize: 5
});
```

https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#labels

**Comment by workingbuddy10** [comment]
I want to decrese the size of the tooltip, that's why I tried doing this ( valueAxis.set("tooltipText","[fontSize: 200px]"); ).

![image](https://github.com/amcharts/amcharts5/assets/137867461/339a8d22-3373-4395-8485-4ed68f7d64b3)

code:
```
    valueAxis
      .get("tooltip")
      .get("background")
      .set("fill", am5.color(axisToolTipColor));

    // valueAxis.set("tooltipText","[fontSize: 200px]");
```
@martynasma

**Comment by martynasma** [comment]
```JavaSript
valueAxis.get("tooltip").label.setAll({
  fontSize: 10
});
```
