### ISSUE TITLE
Amcharts5 bullet rotation not working for circular axis

### ISSUE THREAD

**Issue by koorizhizhi** [amcharts/amcharts5#120]
I want to add two bullets at both the beginning and end of a circular axis of a gauge. Below is the start/end angle of my chart:

```
var chart = root.container.children.push(am5radar.RadarChart.new(root, {
  panX: false,
  panY: false,
  radius: am5.percent(45),
  startAngle: 160,
  endAngle: 380
}));
```
It turns out bullets will also be auto-rotated acoording to the angle of the axis, so the text of the bullet at end point will be upside down:
![image](https://user-images.githubusercontent.com/83855880/144702576-1d8beb42-2aaa-45da-b541-3e8fb79b5525.png)

I've tried to modify "rotation" property of this bullet as well as its sprite, but they don't work at all.
How can I modify the direction of these bullets?

**Comment by martynasma** [comment]
Try setting `orientation: "inward"` on your `Label`.

**Comment by koorizhizhi** [comment]
> 

Thank you for answering. I've just tried this:
```
var labelBullet = axisLabelDataItem2.set("bullet", am5.Bullet.new(root, {
  sprite: am5.Label.new(root, {
    centerX: am5.p0,
    centerY: am5.p50,
    text: Math.round(axisLabelDataItem2.get("value").toString()),
    orientation: "inward"
  }),
}));
```
But it still remains the same...

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by koorizhizhi** [comment]
> Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test
Yes no problem,
I've just post it there:
https://codepen.io/koorizhizhi/pen/jOGbGGV
Appreciate your help

**Comment by martynasma** [comment]
Thanks. You are adding your label as a bullet. This means that it is treated like any other `Sprite` and does not any special treatment as a label.

You need to use axis range's label for proper rotation:

https://www.amcharts.com/docs/v5/charts/xy-chart/axes/axis-ranges/#Label

E.g.:

```
var axisDataItem2 = xAxis.makeDataItem({
  value: 25
});
  
var range2 = xAxis.createAxisRange(axisDataItem2);
  
var bullet2 = axisDataItem2.set("bullet", am5xy.AxisBullet.new(root, {
  sprite: am5.Star.new(root, {
    radius: 16,
    fill: am5.color("#ff884d"),
    stroke: am5.color("#ffffff"),
    strokeWidth: 2,
  }),
}));
  
axisDataItem2.get("label").setAll({
  textType: "radial",
  visible: true,
  centerX: am5.p0,
  centerY: am5.p50,
  text: Math.round(axisDataItem2.get("value").toString()),
});
```

**Comment by koorizhizhi** [comment]
> var range2 = xAxis.createAxisRange(axisDataItem2);

Thanks for your reply.
But I got this error raised for `axisDataItem2.get("label").setAll()`:
Uncaught TypeError: Cannot read properties of undefined (reading 'setAll').
Statement `get("label")` returns undefined.

**Comment by martynasma** [comment]
I don't get errors when I add my code above to your CodePen. Can you update your CodePen, and I'll take a look?

**Comment by koorizhizhi** [comment]
😔 It's my bad. I didn't put `xAxis.createAxisRange(axisDataItem2);` before I try to get "label" property. 
It works now. Thank you very much for your help!
