### ISSUE TITLE
custom drawing patterns

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1200]
Is it possible to add some custom drawing patterns that are available in tradingView but not in amcharts ?
Or is there any way we can built the custom drawing tools like the custom indicators?
Like this:
![image](https://github.com/amcharts/amcharts5/assets/137867461/aec820ba-30bd-4815-b061-05f5e22a40d2)

**Comment by martynasma** [comment]
At this time we do not plan on implementing these.

You're welcome to examine source code how existing drawing tools are implemented, and implement your own.

Unfortunately, we won't be able to provide any support for this.

**Comment by workingbuddy10** [comment]
I am trying to build a custom drawing tool. Please let me know basic setup of the environment and how can I start working upon.
And things which can be helpful while building a tool.

@martynasma
