### ISSUE TITLE
Custom Drawing tools

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1203]
I have made the custom list on Drawing tools in my app, where I have already implemented a few of the drawing tool functionalities and they are working perfectly fine.
But I want to implement/add Parallel Channel & Measure tool. Only these two are not working!

For example I have implemented Fibonacci tool like this and it is working fine:

```
      function enableDrawingTool(tool) {
        //each time disable drawing tools and eraser
        disableEraser();
        disableDrawingTools();
        switch (tool) {
          case document
            .getElementsByClassName("custom-am5stock-list-item active")[0]
            .getAttribute("title"):
            return disableDrawingTools();
          case "Anchor":
            disableDrawingTools();
            break;
          default:
            document.getElementById("anchor").classList.remove("active");
            selectedChartData.drawingControl._maybeInitToolSeries(tool);
            let seriesList = selectedChartData.drawingControl._drawingSeries[tool];
            seriesList[0].enableDrawing();
            selectedChartData.drawingControl._currentEnabledSeries.push(
              seriesList[0]
            );
        }
        //selects the selected tool
        document
          .getElementById(tool.toLowerCase().replace(" ", ""))
          .classList.add("active");
      }

  return (
            <ul className="custom-am5stock-control-list">
              <li
                className="custom-am5stock-list-item"
                id="fibonacci"
                title="Fibonacci"
                onClick={() => enableDrawingTool("Fibonacci")}
              >
                <svg
                  viewBox="0 0 50 50"
                  className="custom-am5stock_control_default_icon"
                >
                  <path d="M2 3 h46 M2 11.5 h46 M2 24 h46 M2 49 h46"></path>
                </svg>
                <label>Fibonacci</label>
              </li>
              </ul>
              )
```

Like that only I am trying to add Parallel Channel & Measure tool :

 ```
 return (
            <ul className="custom-am5stock-control-list">
              <li
                className="custom-am5stock-list-item"
                id="fibonacci"
                title="Fibonacci"
                onClick={() => enableDrawingTool("Fibonacci")}
              >
                <svg
                  viewBox="0 0 50 50"
                  className="custom-am5stock_control_default_icon"
                >
                  <path d="M2 3 h46 M2 11.5 h46 M2 24 h46 M2 49 h46"></path>
                </svg>
                <label>Fibonacci</label>
              </li>
              
              
              {/* measure tool not working */}
              <li
                className="custom-am5stock-list-item"
                id="measure"
                title="Measure"
                onClick={() => enableDrawingTool("Measure")}
              >
                <svg
                  viewBox="0 0 50 50"
                  className="custom-am5stock_control_default_icon"
                >
                  <path d="M 3 38 L 35 6 L 46 17 L 14 49 L 3 38 M 10 31 L 16 37 M 16 25 L 20 29 M 22 19 L 26 23 M 28 13 L 34 19 M 50 50"></path>
                </svg>
                <label>Measure</label>
              </li>
              
              {/* parallel channel tool not working */}
              <li
                className="custom-am5stock-list-item"
                id="parallelchannel"
                title="Parallel Channel"
                onClick={() => enableDrawingTool("Parallel Channel")}
              >
                <svg
                  viewBox="0 0 50 50"
                  className="custom-am5stock_control_default_icon"
                >
                  <path d="M5 2.5 v46 M13.5 2.5 v46 M26 2.5 v46 M46.5 2.5 v46"></path>
                </svg>
                <label>Parallel Channel</label>
              </li>
              
              </ul>
              )

```
Encountering errors :
```
Cannot read properties of null (reading 'classList')
TypeError: Cannot read properties of null (reading 'classList')

```

So is it something I doing wrong like giving title or something?

**Comment by workingbuddy10** [comment]
A pattern is that whenever I am trying to add a tool which comprises of 2 words at that time it's showing me the 

> Cannot read properties of undefined (reading 'enableDrawing') error.

 
Right now only I tried to add Callout and Regression tool it added perfectly, but when I tried to Fibonacci Timezone and Parallel Channel it shows undefined.

**Comment by martynasma** [comment]
I'm not entirely sure what the code is suppose to do. Is it adding an icon to some stock toolbar control?

Would you be able to provide a working CodePen of your implementation?

**Comment by workingbuddy10** [comment]
I want to ask how can we target the settings of the individual drawing tool, like I am implementing whenever user right clicks on the tool then this pop-up displays for setting/config of the drawing tool.

For example user clicks on the callout tool, the tool gets activated but when user Right clicks on the callout tool then this config/setting pop-up should appear.

![image](https://github.com/amcharts/amcharts5/assets/137867461/4009dffd-018e-4584-859a-07c5fa022be8)
 
 @martynasma

**Comment by workingbuddy10** [comment]
> I'm not entirely sure what the code is suppose to do. Is it adding an icon to some stock toolbar control?
> 
> Would you be able to provide a working CodePen of your implementation?

I placed the icons of each tools and gave them the title, passing it to the enableDrawingTool & whenever user clicks on the icon the drawing tool of amcharts is initiated.

so like that I am able to initiate almost all of the tools except  Parallel Channel & Measure tool.

**Comment by workingbuddy10** [comment]
And how come  Parallel Channel & Measure tool is not mentioned in the Available tools, is there any exception?
![image](https://github.com/amcharts/amcharts5/assets/137867461/25a23493-91cc-42cf-b56a-b55cd9ac2afc)


As these two are causing the issue for me, rest of the tools are working fine.

https://www.amcharts.com/docs/v5/charts/stock/toolbar/drawing-control/#Available_tools

@martynasma

**Comment by martynasma** [comment]
Thank you for your heads up about documentation missing some information. It's now fixed.

As for other questions, if you want us to take a look, you might consider posting a working chart setup in a CodePen.

Otherwise, we can't help.

Alternatively, if you do have support subscription, feel free to contact us at contact@amcharts.com

Please note, custom addition development is not within the scope of our support service. We might point to some issues if something jumps out at us, and provide general guidance and answers to questions, but we do not provide full on user code reviews and troubleshooting. Hope that sounds reasonable.

**Comment by workingbuddy10** [comment]
> I want to ask how can we target the settings of the individual drawing tool, like I am implementing whenever user right clicks on the tool then this pop-up displays for setting/config of the drawing tool.
> 
> For example user clicks on the callout tool, the tool gets activated but when user Right clicks on the callout tool then this config/setting pop-up should appear.
> 
> ![image](https://private-user-images.githubusercontent.com/137867461/286168118-4009dffd-018e-4584-859a-07c5fa022be8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzY0MTksIm5iZiI6MTcwMTE3NjExOSwicGF0aCI6Ii8xMzc4Njc0NjEvMjg2MTY4MTE4LTQwMDlkZmZkLTAxOGUtNDU4NC04NTlhLTA3YzVmYTAyMmJlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOFQxMjU1MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YmNmM2QwYmZlNmYwNmE2ZjU1ODVjOTg0MzliNTM5MGQ2MjFmNWI2NWJjODczYTczZjVjMWQ4ZWE3ZTI3MjYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EgMSDgwwj9v9PzgYJNZYpu8m4DDQMQSHFQ8dwTN1Uhs)
> 
> @martynasma


Can you please help me how can I achieve this or how at least how can I target the settings of tools?
