### ISSUE TITLE
Stock Chart Value not Being Set After Being Initialized to 0.

### ISSUE THREAD

**Issue by Suleman12** [amcharts/amcharts5#1204]
I am facing an issue where in my Graph I need to set data to 0 of a graph to show no Values Exist for that particular date .I set it to 0 like this  valueSeries.data.setAll(0)   and for the scrollbar as well sbSeries.data.setAll(0);. Issue arises now when I try to set data again in this value Series it Does not Set the data now again.It Remains 0. It works fine for  scroll bar it sets the Data in sbSeries but does not in valueSeries.

**Comment by martynasma** [comment]
Series data needs to be an array. Setting it to a number will not work. To remove all the data try the following instead:

```
valueSeries.data.setAll([]);
```

**Comment by Suleman12** [comment]
I have tried using this  valueSeries.data.setAll([]);.
Data is Set to null/0 , But Behaviour is still the same when I try to set this valueSeries to data again it doesn't set.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by Suleman12** [comment]
I am attaching my Code pen for Testing. For Testing   this behaviour you can select from the date range selector Dates in to and from 2023 October 30th.In this case the value series and sbseries both are set to null array in the code. Now to try to reinitialize with data select any other dates from the date range selector .You would be able to see that the sbSeries scrollbar gets set with data but valueSeries does not.
https://codepen.io/Suleman12-the-vuer/pen/MWLrmYJ?editors=1111

**Comment by martynasma** [comment]
I'm afraid, I'm not entirely sure what you are doing with custom click events on internal date range selector elements.

If I add this, the updates work fine:

```JavaScript
setTimeout(function() {
   valueSeries.data.setAll([]);
    sbSeries.data.setAll([]); 
}, 3000)

setTimeout(function() {
  newdata=chartdataQEinitial;
  loadDatanew(QEIndex, [valueSeries,sbSeries], currentGranularity);
}, 6000)
```

If you do have a support subscription, please contact us at contact@amcharts.com if you'd like to take this further.
