### ISSUE TITLE
Development Environment setup

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1208]
I am trying to setup the Development Environment in my local machine. So that I can add/customize some of the features of amcharts.

- I have cloned the repo and installed all of the dependencies.
- And now I am trying to run xy-stock, but unable to do that.

I tried to run using this command :

> npm run run-example dist/script/examples/'xy-stock'

```
encountring the error as :
> spawn yarn.cmd ENOENT
```
Local versions: 
npm version : 9.6.6
node version: v18.16.0

**Comment by martynasma** [comment]
In that case you should use script version of amCharts, too.
https://www.amcharts.com/docs/v5/getting-started/#Loading_script_files

The Git repo you need only if you want to modify amCharts core functionality and build your own custom script files.

**Comment by workingbuddy10** [comment]
Yes, i'm trying to modify only core functionality.
 I'm struggling with importing the built files into my fresh react project with typescript.
 I've tried using `npm link` but it keeps throwing `cannot find module errors`

**Comment by martynasma** [comment]
If you are using script files, you won't be able to import or link.

You just need to make modifications to the code, then build script files:
https://github.com/amcharts/amcharts5#building-script-version

**Comment by HawtinZeng** [comment]
we can use this: yarn run-example gauge-bands

**Comment by HawtinZeng** [comment]
But failed because can't run yarn build, maybe it's a webpack version uncompatible?
