### ISSUE TITLE
exporting.events.on("dataprocessed", function(data) - need column values for calculation that I am not exporting

### ISSUE THREAD

**Issue by morrow95** [amcharts/amcharts5#121]
`response.data` has 3 values for each entry : Timestamp, Total, and TotalSum.  I need the TotalSum values in my `exporting.events.on` to calculate and add a new column named Percent for each entry, but because I am not including the TotalSum column in my export I do not have access to those values.  

Is there a way around this?  In version 4 I was adding the Percent column and its calculated values with `chartReg['chart'].exporting.adapter.add("data", function(data)` and had access to TotalSum this way.  Can we use adapters on exports with version 5 to add columns/data?  I am only seeing the method listed below in the docs where you do so on the `dataprocessed` event.

```
//exporting
exporting = am5plugins_exporting.Exporting.new(chartReg['chart'], {
  dataSource: response.data, //original data has Timestamp, Total, and TotalSum values
  dataFields: {
    Timestamp: "Date",
    Total: "Total",
    Percent: "Percent", //column I am adding in the dataprocessed event below
    //TotalSum: 'test' //I do not want to include this column in my export, but it is the only way to access these values in data in dataprocessed event below
  },
  dateFields: ["Timestamp"],
  dateFormat: "MM/dd/yyyy",
  filePrefix: selectTypeLabel + '-' + selectTypeText
});

//exporting add data
exporting.events.on("dataprocessed", function(data) {
  console.log(data); //data only has Timestamp, Total, and Percent (empty because calc has not been done yet)
  console.log(response.data); //original data has Timestamp, Total, and TotalSum values
  for(var i = 0; i < data.data.length; i++) {
    data.data[i].Percent = calcPercent(data.data[i].Total, data.data[i].TotalSum);
  }  
});
```

**Comment by martynasma** [comment]
Yes, any setting in amCharts 5 can be passed via an adapter:

```JavaScript
exporting.adapters.add("dataSource", function(data) {
  // do your stuff here
  // ...
  return data;
});
```

**Comment by morrow95** [comment]
@martynasma Perfect - that worked fine.  Thank you.
