### ISSUE TITLE
Measure tool issue

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1210]
I am using "Measure" drawing tool in my Stock Chart. When I try to remove the drawings of measure tool by Delete all drawings button, the message box of Measure tool remains there.
But when I try to remove it by earaser it removes properly.

I have written a function to delete All the drawings of the chart, and it is working fine for all the tools.

```
// selectedChartData is the current selected chart.
  function deleteAllDrawings() {
    var stockChart = selectedChartData.root.container.children.getIndex(0);
    stockChart.panels.each((panel) => {
      panel.drawings.each((drawing) => {
        drawing.data.clear();
      });
    });
    disableDrawingTools();
  }
```

Like this: 
The image 2 is after deleting all the drawings. 
Image 1:
![image](https://github.com/amcharts/amcharts5/assets/137867461/2a54511b-b893-4f4d-88c0-c8df497ef613)

Image 2: 
![image](https://github.com/amcharts/amcharts5/assets/137867461/e807472c-999c-4bab-9b0f-3a5b138b6af1)

**Comment by workingbuddy10** [comment]
I believe the box is a label and I am not deleting the label, maybe that's why?

**Comment by zeroin** [comment]
Are you using the latest version? As I can't reproduce this. Do you reproduce the same on our website?

**Comment by workingbuddy10** [comment]
The issue was from my end, due to version and code part.
