### ISSUE TITLE
Accessibility of Toolbar Items

### ISSUE THREAD

**Issue by Suleman12** [amcharts/amcharts5#1211]
In my Chart I want my toolbar items to be focusable so that they can also be accessed through  tab key press. Currently only  Scrollbar and Value legend of the Chart is Tab Accessible .I went through documentation regarding accessibility could only found it about scrollbar or Series Element. For example you wanna disable focusing of scrollbar you can set it like this 

```JavaScript
scrollbar.stratGrip.set("focusable", false);
scrollbar.endGrip.set("focusable", false);
```

 Also for the series if I want this property enabled I do this 

```JavaScript
series.columns.template.setAll({
  focusable: true,
  hoverOnFocus: true,
  tooltipText: "[bold]{name}[/]\n{categoryX}: {valueY}",
  tooltipY: 0
});
```

How can I achieve the same for toolbar Elements.
 I tried to do like this 

```JavaScript
var toolbar = am5stock.StockToolbar.new(root, {
  container: document.getElementById("chartcontrols5"),
  stockChart: stockChart,
  focusable: true,
  controls: [
    am5stock.IndicatorControl.new(root, {
      stockChart: stockChart,
      legend: valueLegend
    }),
    dateRangeSelector,
    am5stock.ResetControl.new(root, {
      stockChart: stockChart
    }),
    am5stock.DrawingControl.new(root, {
      stockChart: stockChart
    }),
    settingsControl
  ]
})
```

It did not work. Thanks.

**Comment by martynasma** [comment]
Implemented in [5.7.7](https://github.com/amcharts/amcharts5/releases/tag/5.7.7).

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
