### ISSUE TITLE
Tooltip location on step line series with locationX 1

### ISSUE THREAD

**Issue by baraJanis** [amcharts/amcharts5#1212]
**Question**
Hi,
I want to have the tooltip point to the bullet and not the middle of the step.
TooltipX does not do the trick for me.
Thanks in advance!

[CodePen](https://codepen.io/baraJanis/pen/rNPqZxW)

**Comment by martynasma** [comment]
I suppose you can add tooltips to bullets, then trigger their hover on cursor move:
https://codepen.io/team/amcharts/pen/ZEwNXaE/6f6948f9a5a04b0ffbffbb8b450d1d8e?editors=0010

Or, you can add another hidden LineSeries just for tooltips:
https://codepen.io/team/amcharts/pen/vYbweRp/959d89791afbf71005dc771656ed69be?editors=0010
