### ISSUE TITLE
TooltipContainerBounds not working with tooltips that have layer set

### ISSUE THREAD

**Issue by baraJanis** [amcharts/amcharts5#1216]
**Bug description**

When a Tooltip has the setting “layer” set, the setting tooltipContainerBounds does not work. It should expand the area for a tooltip beyond the chart area, but the tooltips get cut off.

**Steps to Reproduce:**

1. Create a chart with a tooltip.
2. Set the “layer” setting for the tooltip.
3. Set the tooltipContainerBounds setting to expand the area for the tooltip beyond the chart area.
4. Observe that the tooltips get cut off.

**Expected Results:** The tooltip should expand beyond the chart area.

**Actual Results:** The tooltips get cut off.

Here is the CodePen from the tooltipContainerBounds Demo modified to show the issue: [CodePen](https://codepen.io/baraJanis/pen/yLZZBBO)

I hope this helps! Let me know if you need anything else.

**Comment by martynasma** [comment]
If you need to use a non-standard layer for tooltips, you will need to specify its bounds, too:
https://www.amcharts.com/docs/v5/reference/ispritesettings/#layerMargin_property
