### ISSUE TITLE
Keep Map Chart polygon selected when cursor moving

### ISSUE THREAD

**Issue by gabrielle-mlt** [amcharts/amcharts5#1217]
Is this possible to keep the Map Polygon highlighted (active) on click ?

Like in this v4 [codepen](https://codepen.io/anon/pen/moeaWV)

**Comment by gabrielle-mlt** [comment]
Thanks @martynasma for the help.

I hadn't seen this solution because for me the map on the demo has no interaction, it's "frozen".  It has no hover and no click events.

Main Configuration:
- Windows 11 
- Brave 1.61.101

**Comment by martynasma** [comment]
OK, so it's a Brave thing.

Please [read here](https://github.com/amcharts/amcharts5/issues/908#issuecomment-1534846065).
