### ISSUE TITLE
Sync multiple y axes

### ISSUE THREAD

**Issue by cyanaryan** [amcharts/amcharts5#1220]
**Question**
I am using two y-axis in my amcharts. I wanted to sync both the y-axis like both the 0 should coincide if one of the series negative data. I tried using syncWithAxis property but it's not working. Is there any way I can do that?

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
There's no way to force 0 grid to match on both synced axes, unless you want to set `min` and `max` on both axes so that they are proportionally the same distance from 0 on both axes.
