### ISSUE TITLE
Does react integration is outdated ?

### ISSUE THREAD

**Issue by igorlino** [amcharts/amcharts5#1222]
**Question**

The latest version of the r[eact integration with AmCharts](https://www.amcharts.com/docs/v5/getting-started/integrations/react/) mentions 2 things at the top: 

1. creation of empty react project using create-react-app
2. starting the example with a Class-based component

https://www.amcharts.com/docs/v5/getting-started/integrations/react/

does it make sense to update the documentation using a recommended/maintained tool for creating the project and also using a hook base example at the top?

I think [Vite tool](https://vitejs.dev/guide/)is closest to CRA while being easy to use and very modern and powerful. And luckily also framework agnostic.

**Environment (if applicable)**

latest AmChart 5
latest React 18

**Additional context**

Announcement of the dead of create-react-app under: https://github.com/reactjs/react.dev/pull/5487#issuecomment-1409720741

The new official react documentation removed create-react-app: https://react.dev/learn/start-a-new-react-project

**Comment by Pauan** [comment]
@igorlino I read through [the link](https://github.com/reactjs/react.dev/pull/5487#issuecomment-1409720741) you posted, and it sounds like they're not removing create-react-app, but are instead tweaking the way it works a bit.

Do you have any evidence that they're outright deprecating / removing create-react-app entirely?

**Comment by Pauan** [comment]
@igorlino Thanks for providing that, but that just reinforces my point:

https://github.com/facebook/create-react-app/issues/13072#issuecomment-1475136004

> To summarize, it will become a launcher for other recommended tools, rather than being a standalone tool.

A create-react-app developer said that they intend to keep create-react-app but just tweak it, which is also what they said in [the earlier thread](https://github.com/reactjs/react.dev/pull/5487#issuecomment-1409720741).

So it sounds like it will continue to be relevant into the future, it will just defer to other frameworks.

Have they changed their mind and decided to remove it entirely?

**Comment by Pauan** [comment]
I'll discuss this with the rest of the team, about replacing the React tutorial with Vite. Thanks for letting us know about this.

**Comment by martynasma** [comment]
The tutorial has been updated:
https://www.amcharts.com/docs/v5/getting-started/integrations/react/
