### ISSUE TITLE
Hi guys, Was trying to create test code for the amchart, using jest but faced some issue.

### ISSUE THREAD

**Issue by brijesh-imemori** [amcharts/amcharts5#1223]
```
import * as am5 from "@amcharts/amcharts5";
import * as am5xy from "@amcharts/amcharts5/xy";

export function makeChart() {
const root = am5.Root.new("chartdiv");

const chart = root.container.children.push(
am5xy.XYChart.new(root, {
panX: false,
panY: false,
wheelX: "panX",
wheelY: "zoomX",
})
);

return { root, chart };
}
```

```
import { makeChart } from "layouts/dashboards/imemori/ProjectedAndOpps/ProjectRev/amcharttesting";

beforeEach(() => {
// Create

which is needed by the chart
const div = document.createElement("div");
div.id = "chartdiv";
document.body.appendChild(div);
});
test("chart exists", () => {
const { root, chart } = makeChart();
(url)
// Test chart
expect(root).toBeDefined();
expect(chart).toBeDefined();
expect(chart.get("wheelX")).toBe("panX");
});
```

Error:
![image](https://github.com/amcharts/amcharts5/assets/111352823/c03be72f-b9f8-450d-8eb1-9b8a5e43a4d5)

I have been working on the test code for AmCharts, and I've encountered an issue. Despite trying various solutions, I haven't been able to find a resolution for this particular problem, So guys please help me out to resolve this issue.

**Comment by martynasma** [comment]
Have you reviewed our Jest tutorial?
https://www.amcharts.com/docs/v5/getting-started/integrations/jest/

**Comment by brijesh-imemori** [comment]
Hi @martynasma apologies for the late reply, regarding the issue, yeah I have done the same thing that you guys mentioned in the documentation.

babel.config.js:

![image](https://github.com/amcharts/amcharts5/assets/111352823/1c0d6f70-a55e-4907-ab58-77fbd9903b3f)

jest.config.js:

![image](https://github.com/amcharts/amcharts5/assets/111352823/14c1c2e9-e422-4e4c-960d-f8189c59b96f)

package.json (devDependencies):

![image](https://github.com/amcharts/amcharts5/assets/111352823/37fe1317-d14e-4b61-bb5e-08ba00073038)

package.json (dependencies):

![image](https://github.com/amcharts/amcharts5/assets/111352823/b8205c58-173e-4cee-84b7-43f7d67b3e5b)

as you can see in the above images, please let me know what else I need to do, to complete my test code for the component.

**Comment by Pauan** [comment]
Are you sure that you have `canvas` setup properly? Were there any warnings or errors when you installed `canvas`?

Also, you need to remove the `chartdiv` element, otherwise it'll create duplicates:

```js
afterEach(() => {
    document.body.removeChild(document.getElementById("chartdiv"));
});
```

**Comment by brijesh-imemori** [comment]
Hi @Pauan sorry for the late reply, yeah I am using it correctly, but can you show me for example how you have created the test code for the amCharts? That will be great help.

**Comment by Pauan** [comment]
The `afterEach` is based on your code which you provided earlier.

[Our docs](https://www.amcharts.com/docs/v5/getting-started/integrations/jest/) show how to set up everything correctly (including the tests), and we have a [working example](https://stackblitz.com/edit/node-mm8hqa?file=src%2FApp.js).

**Comment by brijesh-imemori** [comment]
> The `afterEach` is based on your code which you provided earlier.
> 
> [Our docs](https://www.amcharts.com/docs/v5/getting-started/integrations/jest/) show how to set up everything correctly (including the tests), and we have a [working example](https://stackblitz.com/edit/node-mm8hqa?file=src%2FApp.js).




Hi @Pauan , this is what I get on the provided stackblitz when I do the **npm test** on terminal

`~/projects/node-mm8hqa
❯ npm test

> node-mm8hqa@0.1.0 test
> react-scripts test --env jsdom --watchAll=false

 FAIL  src/chart.test.js
  ● Test suite failed to run

    Cannot find module '../build/Release/canvas.node'
    Require stack:
    - /home/projects/node-mm8hqa/node_modules/canvas/lib/bindings.js
    - /home/projects/node-mm8hqa/node_modules/canvas/lib/canvas.js
    - /home/projects/node-mm8hqa/node_modules/canvas/index.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/utils.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/living/events/MouseEvent-impl.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/living/generated/MouseEvent.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/living/interfaces.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/browser/Window.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/api.js
    - /home/projects/node-mm8hqa/node_modules/jest-environment-jsdom/build/index.js
    - /home/projects/node-mm8hqa/node_modules/jest-util/build/requireOrImportModule.js
    - /home/projects/node-mm8hqa/node_modules/jest-util/build/index.js
    - /home/projects/node-mm8hqa/node_modules/jest-resolve/build/resolver.js
    - /home/projects/node-mm8hqa/node_modules/jest-resolve/build/index.js
    - /home/projects/node-mm8hqa/node_modules/jest-runtime/build/index.js
    - /home/projects/node-mm8hqa/node_modules/jest-runner/build/testWorker.js
    - /home/projects/node-mm8hqa/node_modules/jest-worker/build/workers/processChild.js

      at Module._resolveFilename (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:54:12642)
      at Module._load (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:54:10056)
      at Module.require (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:54:13775)
      at i (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:98:2198)
      at _0x3f4f2e (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:352:193969)
      at Object.eval (file:/home/projects/node-mm8hqa/node_modules/canvas/lib/bindings.js:3:18)
      at Object.function (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:352:194769)
      at Module._compile (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:54:14871)
      at Module._extensions..js (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:54:15550)
      at Module.load (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:54:13457)

 FAIL  src/App.test.js
  ● Test suite failed to run

    Cannot find module '../build/Release/canvas.node'
    Require stack:
    - /home/projects/node-mm8hqa/node_modules/canvas/lib/bindings.js
    - /home/projects/node-mm8hqa/node_modules/canvas/lib/canvas.js
    - /home/projects/node-mm8hqa/node_modules/canvas/index.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/utils.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/living/events/MouseEvent-impl.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/living/generated/MouseEvent.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/living/interfaces.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/jsdom/browser/Window.js
    - /home/projects/node-mm8hqa/node_modules/jsdom/lib/api.js
    - /home/projects/node-mm8hqa/node_modules/jest-environment-jsdom/build/index.js
    - /home/projects/node-mm8hqa/node_modules/jest-util/build/requireOrImportModule.js
    - /home/projects/node-mm8hqa/node_modules/jest-util/build/index.js
    - /home/projects/node-mm8hqa/node_modules/jest-resolve/build/resolver.js
    - /home/projects/node-mm8hqa/node_modules/jest-resolve/build/index.js
    - /home/projects/node-mm8hqa/node_modules/jest-runtime/build/index.js
    - /home/projects/node-mm8hqa/node_modules/jest-runner/build/testWorker.js
    - /home/projects/node-mm8hqa/node_modules/jest-worker/build/workers/processChild.js

      at Module._resolveFilename (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:54:12642)
      at Module._load (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:54:10056)
      at Module.require (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:54:13775)
      at i (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:98:2198)
      at _0x3f4f2e (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:352:193969)
      at Object.eval (file:/home/projects/node-mm8hqa/node_modules/canvas/lib/bindings.js:3:18)
      at Object.function (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:352:194769)
      at Module._compile (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:54:14871)
      at Module._extensions..js (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:54:15550)
      at Module.load (https:/nodemm8hqa-3w1m.w-corp.staticblitz.com/blitz.6854296d.js:54:13457)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        2.539 s
Ran all test suites.`

**Comment by stanley985** [comment]
@brijesh-imemori did your issue resolved? I've met the same issue as you.

**Comment by brijesh-imemori** [comment]
Hi @stanley985 , 
https://stackblitz.com/edit/node-mm8hqa?file=src%2FApp.js This will help you with what to do.

and also create jest.config.js

module.exports = {
  // Jest configuration options go here
  verbose: true,
  collectCoverage: true,
  moduleDirectories: ["node_modules", "src"],
  // to ignore amChart
  transformIgnorePatterns: ["<rootDir>/node_modules/(?!@amcharts|d3-|d3-array|internmap)"],
  testEnvironment: "jsdom",
  moduleNameMapper: {
    "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$":
      "<rootDir>/src/__mocks__/fileMock.js",
    "\\.(css|less)$": "<rootDir>/src/__mocks__/styleMock.js",
  },
  // ...other options
  setupFilesAfterEnv: ["<rootDir>/src/jest-setup.ts"],
};

and add the above code to that. also, we have made some changes in package.json

  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test -- --config=jest.config.js --collectCoverage",
    "clear_jest": "jest --clearCache",
    "eject": "react-scripts eject"
  },
  
  just look into it if this helps.

**Comment by stanley985** [comment]
> Hi @stanley985 , https://stackblitz.com/edit/node-mm8hqa?file=src%2FApp.js This will help you with what to do.
> 
> and also create jest.config.js
> 
> module.exports = { // Jest configuration options go here verbose: true, collectCoverage: true, moduleDirectories: ["node_modules", "src"], // to ignore amChart transformIgnorePatterns: ["/node_modules/(?!@amcharts|d3-|d3-array|internmap)"], testEnvironment: "jsdom", moduleNameMapper: { "\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "/src/**mocks**/fileMock.js", "\.(css|less)$": "/src/**mocks**/styleMock.js", }, // ...other options setupFilesAfterEnv: ["/src/jest-setup.ts"], };
> 
> and add the above code to that. also, we have made some changes in package.json
> 
> "scripts": { "start": "react-scripts start", "build": "react-scripts build", "test": "react-scripts test -- --config=jest.config.js --collectCoverage", "clear_jest": "jest --clearCache", "eject": "react-scripts eject" },
> 
> just look into it if this helps.

I will have a look and test if this work for me. whether success or not I will inform you. thanks a lot for this.

**Comment by stanley985** [comment]
> > Hi @stanley985 , https://stackblitz.com/edit/node-mm8hqa?file=src%2FApp.js This will help you with what to do.
> > and also create jest.config.js
> > module.exports = { // Jest configuration options go here verbose: true, collectCoverage: true, moduleDirectories: ["node_modules", "src"], // to ignore amChart transformIgnorePatterns: ["/node_modules/(?!@amcharts|d3-|d3-array|internmap)"], testEnvironment: "jsdom", moduleNameMapper: { ".(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "/src/**mocks**/fileMock.js", ".(css|less)$": "/src/**mocks**/styleMock.js", }, // ...other options setupFilesAfterEnv: ["/src/jest-setup.ts"], };
> > and add the above code to that. also, we have made some changes in package.json
> > "scripts": { "start": "react-scripts start", "build": "react-scripts build", "test": "react-scripts test -- --config=jest.config.js --collectCoverage", "clear_jest": "jest --clearCache", "eject": "react-scripts eject" },
> > just look into it if this helps.
> 
> I will have a look and test if this work for me. whether success or not I will inform you. thanks a lot for this.

Does your package.json config same as officer doc? I used Angular not React

**Comment by brijesh-imemori** [comment]
We are using React ts, it worked for us.
Don't know how to implement it in angular.
