### ISSUE TITLE
CandleVolume  Chart

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1225]
How can I achieve CandleVolume chart in my stockchart? What are custom changes I should look out for in stockchart.js file.

CandleVolume chart: 
Normal candlesticks, the open and close form the body of the candlestick, while the high and low form the upper and lower shadows. Volume determines the width of the candlestick. Wide candlesticks form when volume is high, while narrow candlesticks form when volume is low.

Like this : 
![image](https://github.com/amcharts/amcharts5/assets/137867461/a949c08c-2e4b-48e5-a4d0-4cbc95a0ea36)

**Comment by martynasma** [comment]
I'm afraid, there's no way to implement a chart like that in amCharts.

**Comment by martynasma** [comment]
Making candles wider would be easier. To alternate X axis cells based on candle width is a whole other matter.

I'm afraid we won't be able to provide such feature, or guidance on how to implement it yourself. Sorry 🙁

**Comment by workingbuddy10** [comment]
Thank you for the response! @martynasma
