### ISSUE TITLE
 Update the data and update the axis range without re creating series. Is there any way to do it?

### ISSUE THREAD

**Issue by cyanaryan** [amcharts/amcharts5#1227]
**Question**
I have axis range created for the series. But I want to update it and I don't want to create the series again. I just want to update the data and update the axis range (value and endValue, range). Is there any way to do it?

**Environment (if applicable)**

**Additional context**

**Comment by cyanaryan** [comment]
var rangeDataItem = .xAxis.makeDataItem({
         value: new Date(1,1,2023).getTime(),
         endValue: new Date.getTime(),
      });
      
        rangeDataItem.get('grid').setAll({
        strokeOpacity: 1,
        visible: true,
        stroke: am5.color(0x000000),
      });

      rangeDataItem.get('label').setAll({
        location: 0,
        visible: true,
        text: 'Forecasted',
        inside: true,
        centerX: 0,
        centerY: am5.p100,
      });
      
      
      I am also making rangeDataItem, but after new data is coming, multiple lines are coming with "Forecast" label.

**Comment by martynasma** [comment]
You can remove existing axis range by disposing the data item:

```JavaScript
rangeDataItem.dispose();
```
