### ISSUE TITLE
I need to export all the roots from container

### ISSUE THREAD

**Issue by canesen7** [amcharts/amcharts5#1228]
Hi, I've a chart like this

![image](https://github.com/amcharts/amcharts5/assets/67913330/6ee8b32b-0750-4af0-abb3-b9b481093458)

But in this container I've multiple roots.

![image](https://github.com/amcharts/amcharts5/assets/67913330/fa855595-c1cf-48c3-a31d-a6076d13057b)

Like this. I was not push the same container before I made the chart. So I need to export all the roots in one export pdf, png or jpg. I tried to 

    var exporting = am5plugins_exporting.Exporting.new(root, {
      menu: am5plugins_exporting.ExportingMenu.new(root, {}),
      extraImages: [
        {
          source: legendRoot
        },
        {
          source: conditionalLegendRoot
        }
      ]
    });

But this exports bottom to bottom to image. How can I export all the root elements in amcharts 5?

**Comment by martynasma** [comment]
I'm afraid there's no way to do that using built-in functionality.

You would need to export each Root to image individually, then combine into a single image using your own code.

Unfortunately, I don't have an example like that ready.

**Comment by canesen7** [comment]
Thank you Marty...
