### ISSUE TITLE
Height of Volume Candles

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1229]
I am looking in the **_library code_** where/how the height of volume of the candlesticks are managed. 
Like the maximum volume data has the highest volume candle height, whereas the minimum volume data has the lowest candle height. Where is the logic of this written.

The thing is I am trying to manipulate the width of the candlesticks, like the height of volume varies. Like that only we can change the width of the candlesticks.

Though I am able to change the width of the candlesticks by this : 
`this.columns.template.set("width",100);`

But this will change the width of all candlestick! I want it to vary with the volume bars.

**Comment by martynasma** [comment]
You can use an adapter:

```JavaScript
this.columns.template.adapters.add("width", function(width, target) {
  // Your code which determines width dynamically.
  return width;
});
```
