### ISSUE TITLE
XYChart Series flickers when real time new data is added + groupData true

### ISSUE THREAD

**Issue by lucasalmeida92** [amcharts/amcharts5#1232]
Hello there!
I'm having this flickering behavior when trying to make a real time XYChart with `groupData: true`:
[chart-series-flickering.webm](https://github.com/amcharts/amcharts5/assets/5767871/56ecc520-410b-4aa8-8ea6-32771c58bb3e)

This is the X Axis code:
```ts
const xAxis = chart.xAxes.push(
    am5xy.DateAxis.new(root, {
      baseInterval: { timeUnit: 'millisecond', count: 1 },
      maxDeviation: 1,
      extraMax: 0.3,
      groupData: true,
      minZoomCount: 1000 * 60,
      renderer: am5xy.AxisRendererX.new(root, {
        strokeOpacity: 0,
      }),
    })
  );
```

And here how I update series data(from websocket):
```ts
const addNewTickToChart = (newTick: TickType) => {
      series.data.push(newTick);
      bulletSeries.data.setIndex(0, newTick);

      const newDataItem = series.dataItems[series.dataItems.length - 1];

      animateNewTick(newDataItem);
  };
```

```ts
export function animateNewTick(newDataItem: am5.DataItem<any>) {
  newDataItem.animate({
    key: 'valueYWorking',
     to: newTickType.value,
    duration: 300,
    easing: am5.ease.linear,
  });
}
```

I can't figure out how to solve this :/
I already tried not adding Animated theme (`am5themes_Animated.new(root)`)
and changing groupIntervals.

**Comment by martynasma** [comment]
This code:

```JavaScript
export function animateNewTick(newDataItem: am5.DataItem<any>) {
  newDataItem.animate({
    key: 'valueYWorking',
     to: newTickType.value,
    duration: 300,
    easing: am5.ease.linear,
  });
}
```

You don't have `from` set, so it animates from zero, hence the jump.

Refer to this demo which uses `from` value and thus no jump:
https://www.amcharts.com/demos/line-chart-adding-data-every-second/

**Comment by lucasalmeida92** [comment]
Sorry I forgot to mention I also tried this already.
And I followed this demo to make mine.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by lucasalmeida92** [comment]
Not the whole thing because there is a lot of private code of the company I work for...But I'll try to make a similar one

**Comment by lucasalmeida92** [comment]
- Here a CodeSandbox: https://codesandbox.io/p/sandbox/real-time-chart-amcharts-v5-d4vlvq?file=%2Fsrc%2FChart.tsx

**Comment by martynasma** [comment]
Thanks. It does not flicker or jump, though.

**Comment by lucasalmeida92** [comment]
Please zoom in to see it flickering

**Comment by lucasalmeida92** [comment]
Hey @martynasma, did you manage to see it? 
I'm still struggling to get it done :/

**Comment by zeroin** [comment]
Could you create the same on codepen or jsfiddle without any dependencies? I can not edit or run your code locally where I could reproduce and debug this situation. And I don't see why this happens just looking at the code.

**Comment by lucasalmeida92** [comment]
@zeroin you can do this:
![image](https://github.com/amcharts/amcharts5/assets/5767871/42179c59-9ccc-4ee8-8653-6955e1af9570)

**Comment by zeroin** [comment]
I will still be unable to run this on my dev setup, I need an isolated code in one chunk in order to do debugging.

**Comment by lucasalmeida92** [comment]
Here it is:
https://codepen.io/lucasalmeida/pen/WNmvvWp

**Comment by lucasalmeida92** [comment]
Idk if this can help, but removing the **Animated theme** and these lines:
```ts
chartElements.lineSeries?.appear(200);
chartElements.chart.appear(1000, 100);
```
we can see this behavior(basically the same but without animation):
![realtime-chart-groupdata](https://github.com/amcharts/amcharts5/assets/5767871/16b3d6c5-eff2-4ba3-8347-13cae72281a1)

**Comment by lucasalmeida92** [comment]
I think I found the "problem"...
Actually I don't know WHY, but when I remove the lastTickBullet the chart is not flickering anymore

**Comment by lucasalmeida92** [comment]
I noticed that when there is more than 1 line series in the same chart, and `groupData` of xAxis is `true`, the flickering issue happens.

**Comment by zeroin** [comment]
I am afraid I can only comment if you could provide a codepen where this can be reproduced.

**Comment by lucasalmeida92** [comment]
@zeroin 
....I already did...
https://github.com/amcharts/amcharts5/issues/1232#issuecomment-1870649862

**Comment by martynasma** [comment]
Would you be able to post a scaled down vanilla version which we could use for testing?

I'm afraid your setup is too elaborate, we need a very concise repro case.

I hope you find it reasonable.

**Comment by lucasalmeida92** [comment]
Ok no problem... but please next time say this first...
