### ISSUE TITLE
Volume Profile Indicator stuck in Live Data

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1235]
Volume Profile Indicator is getting freeze, when stock is getting the live data.

Link to check :  https://codepen.io/Ansh-m-the-reactor/pen/wvNVpMB

**Comment by martynasma** [comment]
Volume Profile needs volume data.

Prior to 5.7.1 it would freeze if `volumeSeries` was not set.

5.7.1 and up it will just not show up silently.
