### ISSUE TITLE
Volume Profile Indicator lagging 

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1236]
Volume Profile Indicator lagging, when user selects the option of _ticks per row_ . And if there is a good amount of data let's say 1000 data points in this case it totally get's stuck.

Link : https://codepen.io/team/amcharts/pen/BaMXwQZ/f0883e6dd0d9cb1f1e56aba39443e0d7

**Comment by martynasma** [comment]
This is happening because when you switch to ticks and there's a lot of data, the default 24 ticks produces a lot of columns and calculations, hence the lag.

We will consider implementing some fuzzy logic to change default number of ticks to some meaningful number.

**Comment by workingbuddy10** [comment]
One more issue in this, when I selected the _ticks per row_ option and gave the count value to 1.

Then to it plotted the bar, you can reproduce it in the codepen link.

@martynasma

**Comment by martynasma** [comment]
We're introducing an automatic update to count value when switching count types in the next version.

**Comment by workingbuddy10** [comment]
Oh, excited to see the working !!
@martynasma

**Comment by martynasma** [comment]
Implemented in [5.7.5](https://github.com/amcharts/amcharts5/releases/tag/5.7.5).

## [5.7.5] - 2024-01-04

### Added
- New `Annotator` setting: `markerStyleSettings`. Allows setting default settings for UI styles of `MarkerArea`. [More info](https://www.amcharts.com/docs/v5/concepts/exporting/annotator/#Configuring_UI).
- "Moving Average Cross" (MACross) and "Price Volume Trend" (PVT) indicators added to `StockChart`.
- `ZoomControl` now has a new property: `homeButton`. It holds an instance of a button which zooms out the map to its initial position. It is hidden by default, so if needed, needs to unhide it by setting `zoomControl.homeButton.set("visible", true)`.

### Changed
- Settings dialog for a "Volume Profile" indicator will automatically update count field value to a more suitable one when switching count type.

### Fixed
- Clearing data on a `ClusteredPointSeries` would not remove its bullets representing clusters.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
