### ISSUE TITLE
Extract styling specific config details into custom theme class confusion

### ISSUE THREAD

**Issue by binaryartifex** [amcharts/amcharts5#1241]
ive read the documentation (v5) back to front trying to get my head around custom themes and have also dug into the codebase to look at how the default and additional themes are set and I still can't get my head around the idea of the 'tags' and how these are being determined. My intent is to completely extract all the styling specific properties from my heat map into a custom heat map theme and inject that into the root. Ive literally taken, almost verbatim, the code from the heat map example on the examples page.

so far my theme config looks as follows...

```typescript
export class HeatMapTheme extends Theme {
  readonly axisLabelColor = cssVariableToHex(COLORS.text.muted);

  protected setupDefaultRules(): void {
    this.rule("XYChart").setAll({
      panX: true,
      panY: false,
      wheelX: "none",
      wheelY: "none",
      paddingLeft: 0,
      layout: this._root.verticalLayout,
    });

    this.rule("AxisLabel").setAll({
      fill: this.axisLabelColor ? color(this.axisLabelColor) : undefined,
      fontSize: "14px",
    });

    this.rule("AxisRenderer").setAll({
      minGridDistance: 30,
      minorGridEnabled: true,
      visible: false,
    });

    this.rule("Grid").setAll({
      visible: false,
    });

    this.rule("RoundedRectangle", ["series", "column"]).setAll({
      height: percent(100),
      strokeOpacity: 1,
      strokeWidth: 2,
      width: percent(100),
    });
  }
}
```

what im left with in my useLayoutEffect (react based app) is as follows

```typescript
  useLayoutEffect(() => {
    const root = am5.Root.new(id);

    root.setThemes([
      am5themes_Responsive.new(root),
      am5themes_Animated.new(root),
      HeatMapTheme.new(root),
    ]);

    const chart = root.container.children.push(am5xy.XYChart.new(root, {}));
    const yRenderer = am5xy.AxisRendererY.new(root, {});
    const xRenderer = am5xy.AxisRendererX.new(root, {});

    const yAxis = chart.yAxes.push(
      am5xy.CategoryAxis.new(root, {
        categoryField: "yAxisCategory",
        maxDeviation: 0,
        renderer: yRenderer,
      }),
    );

    const xAxis = chart.xAxes.push(
      am5xy.CategoryAxis.new(root, {
        categoryField: "xAxisCategory",
        maxDeviation: 0,
        renderer: xRenderer,
      }),
    );

    const series = chart.series.push(
      am5xy.ColumnSeries.new(root, {
        calculateAggregates: true,
        clustered: false,
        xAxis: xAxis,
        yAxis: yAxis,
        categoryXField: "xAxisCategory",
        categoryYField: "yAxisCategory",
        valueField: "value",
      }),
    );

    series.columns.template.setAll({
      stroke: am5.color(0xffffff),
      tooltipText: "{value}",
    });

    series.set("heatRules", [
      {
        target: series.columns.template,
        min: am5.color(minColor),
        max: am5.color(maxColor),
        dataField: "value",
        key: "fill",
      },
    ]);

    series.data.setAll(chartData.data);
    xAxis.data.setAll(chartData.xLabels);
    yAxis.data.setAll(chartData.yLabels);

    chartRef.current = chart;

    return () => root.dispose();
  }, [chartData, id, maxColor, minColor]);
```

1. the issue im running into now is that the `series.colums.template` stroke property does not work when i remove it from the useLayoutEffect and add it to the RoundedRectangle rule. 

2. im injecting custom colors from a tailwind configuration that are derived from css variables (see axisLabelColor in the HeatMapTheme), however when i toggle between light and dark mode (in storybook), the chart is always one render cycle behind applying the new value to axisLabelColor. is there a way to optimize dark/light theming or will i need separate dark/light themes and somehow register a listener for a theme change and swap between the themes? 

any help is greatly appreciated, including any feedback on the direction im going here in the context of a React app...

**Comment by martynasma** [comment]
The issue with `stroke` (and `fill` for that matter) is that `ColumnSeries` explicitly sets its own `stroke` (and `fill`) on columns when they are created.

Explicitly set setting takes precedence over the one from them, hence it not working.

The only way to override column stroke via theme is to add an adapter:

```JavaScript
this.rule("RoundedRectangle", ["series", "column"]).adapters.add("stroke", () => am5.color(0xffffff));
```

**Comment by binaryartifex** [comment]
@martynasma much appreciated mate cheers for that. is there any doc references anywhere for which properties are explicitly set or is it just a matter of using adapters as a blunt force instrument if rules don't change properties?

**Comment by martynasma** [comment]
There's no such document, I'm afraid.

Basically, it's just `stroke` and `fill` for most of the series setting their items (columns, slices, etc.).

We usually avoid setting stuff on elements, unless absolutely necessary.
