### ISSUE TITLE
Comparison series in a separate Panel

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1242]
I am trying to get the comparison series in different panel, though I am able to create the panel succesfully just unable to push the data in the right way and getting an error as `Uncaught TypeError: stockChart.addPanel is not a function` .

Though I believe I am almost done, just getting stuck in a minor error.

Link to view: https://codepen.io/Ansh-m-the-reactor/pen/mdobpzN?editors=1011

**Comment by martynasma** [comment]
You don't need a method to add a panel, simply pushing it into `stockChart.panels` is enough.

**Comment by workingbuddy10** [comment]
@martynasma Can you Please update it in the given codepen link, that would be great help. As I tried doing that again some error popped.

**Comment by martynasma** [comment]
I'm afraid making edits to user code is a bit outside the scope of our support. Hope you find it reasonable.

Adding comparison series in same panel and new panel is exactly the same process, except you have to create a panel first.
