### ISSUE TITLE
Group stacked XY chart data as screen gets smaller / larger?

### ISSUE THREAD

**Issue by binaryartifex** [amcharts/amcharts5#1243]
In the context of a typical time series stacked bar chart, in some instances i have 1 - 2 days of 5 minute data that performs quite slugglishly on the browser (especially when each datum has 5 or 6 stacked properties). is it at all possible to group/aggregate the data with respect to the screen width or some other type of responsive indicator - which then allows for zooming in to greater and greater breakdowns of the data?

**Comment by martynasma** [comment]
You may consider data item grouping:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#dynamic-data-item-grouping

it's not related to screen size (I don't think screen size affects performance as much as the number of data items does), but rather zoom scope.

**Comment by binaryartifex** [comment]
@martynasma yeah thats the direction i naturally went towards. i think its specifically a use case such that if i have even 300-500+ data items, such as a stacked bar chart, looks fine on a wide screen, coming down to tablet or dare i say a mobile and it gets nasty fairly quick. i assume there's no capacity to also generate dynamic data item grouping based on minGridDistance? or perhaps being able to map the groupCount against the current grid distance to essentially keep arbitrarily zooming out to within a happy range based on the min/max group count as a function of min grid distance? just thinking out aloud here...

**Comment by martynasma** [comment]
Nope, there's no functionality in place that would allow grouping on any visual space metric.

That being said, I suppose you could create a code that measures screen size and sets `groupCount` on `DateAxis` accordingly.

You could set to some lower value on lower resolutions, so that grouping kicks in sooner on those devices.

Just a thought.
