### ISSUE TITLE
how to conditionally apply margin to ValueAxis if its on opposite axis

### ISSUE THREAD

**Issue by binaryartifex** [amcharts/amcharts5#1245]
is there any way to add margin between the value axis and the chart relative to which side of the chart the value axis is being rendered?

ive tried this and a few iterations of this and nothing seems to work...

```typescript
    this.rule("AxisRendererY", ["axis"]).adapters.add("marginRight", (_, target) => {
      return target._settings.opposite ? 20 : 0;
    });

    this.rule("AxisRendererY", ["axis"]).adapters.add("marginLeft", (_, target) => {
      return target._settings.opposite ? 20 : 0;
    });
```

is there a way to avoid the verbosity and target the actual plot container with margin values to 'push' away the initial x and y axis?

**Comment by martynasma** [comment]
How about just adding extra padding to labels?

```JavaScript
this.rule("AxisLabel", ["x"]).setAll({
  paddingLeft: 0,
  paddingRight: 50
});

this.rule("AxisLabel", ["x", "opposite"]).setAll({
  paddingLeft: 50,
  paddingRight: 0
});
```
