### ISSUE TITLE
Axis labels based on a field via JSON configuration

### ISSUE THREAD

**Issue by davidjb** [amcharts/amcharts5#1246]
**Question**

Is it possible to configure an axis' labels (e.g. for a CategoryAxis in particular) to use a different field than what's configured as its `categoryField` (e.g `categoryXField` or `categoryYField`)?

I've seen and implemented this solution https://www.amcharts.com/docs/v5/tutorials/using-adapters-on-category-axis-labels/ but is it possible for this to work via JSON-based configuration?

I've tried each of the following, and the `categoryField` value continues to be displayed:

* `CategoryAxis.templateField` setting
* `AxisRendererX.templateField` setting
* `AxisRendererX.labelTemplate` property

Before deep-diving into the issue, I wanted to check if this behaviour is supported by amCharts. The use of an adapter in the example suggests it may not be.  (If it isn't supported, could this be added?)

**Environment (if applicable)**

 - amCharts version: 5.7.1
 - Browser and its version: Chromium 119.0.6045.105
 - Related frameworks and their versions: Vanilla JS

**Additional context**

**Comment by martynasma** [comment]
I'm afraid there's no way to add adapters to a JSON config.

**Comment by davidjb** [comment]
Thanks for clarifying @martynasma. Aside from adding an adapter, is there any way of just directly configuring axis labels in the current JSON config setup? From reading the API and class docs, it seems that one of those field/template options should work - setting them didn't seem to affect chart output so I'm not clear on what each is intended for.

**Comment by martynasma** [comment]
`templateField` works only on series items, which axis items are not.

The other option won't work either, because axes have own logic of generating labels.
