### ISSUE TITLE
Tooltip not working in Series Switcher

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1247]
Tooltip is not visible when user goes to line series and comes back to candles.

Initially tooltip is visible, but when switch to line series via SeriesTypeControl it doesn't show the tool tip. And even after switching back to candles it is not showing the tootlip.

Link to check : https://codepen.io/Ansh-m-the-reactor/pen/RwdbOEm

**Comment by martynasma** [comment]
You don't seem to be setting `tooltip` for series when you re-create it with a new type.

**Comment by workingbuddy10** [comment]
Exactly where should I set the tooltip again?

Like I have taken the code from the amcharts example only just added a small part of code for tooltip box.

Do you have any working example?

https://www.loom.com/share/9fb5e0b58e9d47919566a56f65b26e02?sid=7707dde9-8de5-4ddf-917f-771c7cb3c86a

@martynasma

**Comment by martynasma** [comment]
> Exactly where should I set the tooltip again?

Series type switching works like that:

1) You create a new series
2) Set settings on a new series
3) Destroy the previous series
4) Add new series to the panel

In step 2) you do not add a `tooltip` to new series among other things.

Please note, that original `Tooltip` you created for initial series, gets disposed together with that series.

So when you create new series, you have to recreate the tooltip and add it to series. So there's an additional step:

2.5) Create new `Tooltip` and set on new series `tooltip`.

I hope it makes sense now.

**Comment by workingbuddy10** [comment]
Got your point,  as nothing related to tooltip was mentioned in the docs that's why got confused.

@martynasma

**Comment by workingbuddy10** [comment]
I am trying to add to the tooltip for series type control, but not able to get the result.

Below is the code for the tooltip, that I want to re-use at every series : 
```
var tooltip = am5.Tooltip.new(root, {
  getFillFromSprite: false,
  getStrokeFromSprite: true,
  autoTextColor: false,
  // keepTargetHover: true,
  pointerOrientation: "left",
  labelText:
    " O: [bold]{openValueY}[/]\n H: [bold]{highValueY}[/]\n L: [bold]{lowValueY}[/]\n C: [bold]{valueY}[/]"
});
tooltip.label.setAll({
  fill: am5.color("#FFFFFF")
});

tooltip.get("background").setAll({
  fill: am5.color("rgba(34, 34, 34, 0.8)"),
  fillOpacity: 0.5
});
```

Code pen link :  https://codepen.io/Ansh-m-the-reactor/pen/RwdbOEm?editors=1010

@martynasma

**Comment by workingbuddy10** [comment]
In the function getNewSettings I have tried doing this too, but it shows an error  `EventDispatcher is disposed` :
```
    function getNewSettings(series) {
      var newSettings = [];

      var tooltip = am5.Tooltip.new(root, {
        getFillFromSprite: false,
        getStrokeFromSprite: true,
        autoTextColor: false,
        // keepTargetHover: true,
        pointerOrientation: "left",
        labelText:
          " O: [bold]{openValueY}[/]\n H: [bold]{highValueY}[/]\n L: [bold]{lowValueY}[/]\n C: [bold]{valueY}[/]",
      });
      tooltip.label.setAll({
        fill: am5.color("#FFFFFF"),
      });

      tooltip.get("background").setAll({
        fill: am5.color("rgba(34, 34, 34, 0.8)"),
        fillOpacity: 0.5,
      });
      series.set("tooltip", tooltip);
      am5.array.each(
        [
          "name",
          "valueYField",
          "highValueYField",
          "lowValueYField",
          "openValueYField",
          "calculateAggregates",
          "valueXField",
          "xAxis", 
          "yAxis",
          "legendValueText",
          "stroke",
          "fill",
          "tooltip"
        ],
        function (setting) {
          newSettings[setting] = series.get(setting);
        }
      );
      return newSettings;
    }
```
