### ISSUE TITLE
For line charts oversizedBehavior: 'wrap' does not work

### ISSUE THREAD

**Issue by roman-gorkunenko** [amcharts/amcharts5#1250]
Hello,
Please tell me why oversizedBehavior: 'wrap' may not work for line charts?
![image](https://github.com/amcharts/amcharts5/assets/91733660/cb46da7c-e649-4147-bd4f-10bbff015d88)

Code example: https://codepen.io/Roman-Gorkunenko-the-flexboxer/pen/jOQEVwr

**Comment by martynasma** [comment]
It does work. It's just your labels are shorted than the `maxWidth` you have set ☺️

**Comment by roman-gorkunenko** [comment]
Oh, sorry.
