### ISSUE TITLE
I Want Get The Data Drawing Tools Data Like this from var stockchart variable same like as a hard coded data but i want which drawing tool i draw i want get that data dynamically

### ISSUE THREAD

**Issue by kirannarwade** [amcharts/amcharts5#1251]
![Capture](https://github.com/amcharts/amcharts5/assets/90048456/a3123652-232a-41ef-9b6b-15963b3780c3)
![Capture1](https://github.com/amcharts/amcharts5/assets/90048456/1c75848c-e79b-4150-ad27-617cb8ceadba)
**Bug description**

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
You can watch `drawingschanged` event on `StockChart`, then serialize current data.

https://www.amcharts.com/docs/v5/charts/stock/serializing-indicators-annotations/#Events

**Comment by kirannarwade** [comment]
but how i get the data dynamically instead of your code has hard coded data of drawing controls

**Comment by martynasma** [comment]
I'm not entirely sure what you're asking.

Do you want to serialize/unserialize data only for specific tools?

**Comment by kirannarwade** [comment]
I want get the data of drawing tool which are drawed in chart

**Comment by martynasma** [comment]
Well, the following tutorial explains how to grab current drawing data:
https://www.amcharts.com/docs/v5/charts/stock/serializing-indicators-annotations/#Serializing
