### ISSUE TITLE
Tooltip margin

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts5#1254]
Hello there !

Is there a way to add a margin (offset) for the tooltip ?

```
am5.Tooltip.new(root, {
	dx 					: 30,
})
```

Working fine if tooltip is on the right

![image](https://github.com/amcharts/amcharts5/assets/6083644/d6e22370-d515-4039-97e4-59e5305fa669)

But if the Tooltip is on the left:

![image](https://github.com/amcharts/amcharts5/assets/6083644/5e8e07bb-2abe-4518-8ecf-5fbd89f0f51f)

**Comment by martynasma** [comment]
You'll need an adapter to apply `dx` dynamically:

```JavaScript
tooltip.adapters.add("dx", function(x, target) {
  return target.get("background").get("pointerX") > 0 ? -20 : 20;
});
```
