### ISSUE TITLE
Value Legend Show Outside of Graph

### ISSUE THREAD

**Issue by Suleman12** [amcharts/amcharts5#1255]
How Can I show Value Legend on Top of my stock Graph instead of on it. Possibly between the toolbar and the Graph.
[
![valuelegends](https://github.com/amcharts/amcharts5/assets/24837687/d90db3d2-7d19-4951-a275-4b3b871268cc)

**Comment by martynasma** [comment]
The `StockLegend` is designed to be displayed inside plot container.

If you need a "classic" legend, you can just use [regular `Legend`](https://www.amcharts.com/docs/v5/charts/xy-chart/legend-xy-series/) instead.

```JavaScript
var valueLegend = valueAxis.axisHeader.children.push(
  am5.Legend.new(root, {
    useDefaultMarker: true
  })
);
```
