### ISSUE TITLE
Stock Chart Blinking

### ISSUE THREAD

**Issue by frxldi-xyz** [amcharts/amcharts5#1256]
**Bug description**
Stock Chart Blinking when i set my data range into more then 1 year. If below 1 year, it seem fine but candle disappear when i zoom it. Using data grouping and separated Price - Volume Panel like demo in website
https://www.amcharts.com/demos/stock-data-grouping/
I use fetch mechanism because it need Bearer token to access it. 

**Environment (if applicable)**

 - amCharts version: 5
 - Browser and its version: Opera GX and Blisk (Chromium)
 - Related frameworks and their versions: NextJS 14

**Additional context**
**Video**: https://app.blisk.io/screenrecords/shared/ec546269-0975-4eba-add1-ec99333726c2

**Comment by martynasma** [comment]
Can you doublecheck if you are using the latest version (5.7.3) in your app?

If you are, we'll need some kind of reproduction case which we can take a look at and test.

**Comment by frxldi-xyz** [comment]
> Can you doublecheck if you are using the latest version (5.7.3) in your app?
> 
> If you are, we'll need some kind of reproduction case which we can take a look at and test.

**Comment by frxldi-xyz** [comment]
> Can you doublecheck if you are using the latest version (5.7.3) in your app?
> 
> If you are, we'll need some kind of reproduction case which we can take a look at and test.

Ya i use 5.7.0 version

**Comment by martynasma** [comment]
Thanks.

Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by frxldi-xyz** [comment]
> Thanks.
> 
> Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

sure. its my little code [CodeSandbox](https://y6hyq7.csb.app/)

**Comment by martynasma** [comment]
Thanks.

It seems your `useLayoutEffect` is kicking in repeatedly, thus creating the chart anew several times a second, hence the flickering.

You should look into that.

**Comment by frxldi-xyz** [comment]
> Thanks.
> 
> It seems your `useLayoutEffect` is kicking in repeatedly, thus creating the chart anew several times a second, hence the flickering.
> 
> You should look into that.

Thanks for reply. Already fix that. But why candle disappearing in centain of range? also legend don't show properly
![12-28-2023 (11-32-19)](https://github.com/amcharts/amcharts5/assets/77787933/7941e9c0-4b53-4943-8fd9-d98de4b5c757)

**Comment by martynasma** [comment]
That looks like an issue with data. Data needs to be ordered by date in ascending order. If it's in any other order, it might glitch.
