### ISSUE TITLE
Category Axes last line missing

### ISSUE THREAD

**Issue by bartoszpytka** [amcharts/amcharts5#126]
While setting any of axis X or Y to category they are to loose their last line:

this is how it looks with both axes of value type:

![image](https://user-images.githubusercontent.com/81053076/144853566-1635c260-c453-44bd-b9ce-32989b7f50a8.png)

When one of them is categorial this is how it starts to look:

![image](https://user-images.githubusercontent.com/81053076/144853484-181d9803-c4ee-4049-8079-c3d8b985d0ec.png)

And when the other one is categorial:

![image](https://user-images.githubusercontent.com/81053076/144853715-fdc96734-9590-4446-993f-4baa417e6af7.png)

As you can see after the Marketing category to the end of an axis there is no line like it was while this axis was value type. 

Is there any property to set to retrieve this line back?

**Comment by martynasma** [comment]
There are a few ways to go about it.

1) Add an [axis range](https://www.amcharts.com/docs/v5/charts/xy-chart/axes/axis-ranges/):

```JavaScript
var xAxis = chart.xAxes.push(am5xy.CategoryAxis.new(root, {
  categoryField: "category",
  renderer: am5xy.AxisRendererX.new(root, {})
}));

var rangeDataItem = xAxis.makeDataItem({
  category: data[data.length - 1].category
});

var range = xAxis.createAxisRange(rangeDataItem);

rangeDataItem.get("grid").setAll({
  stroke: am5.color(0x000000),
  strokeOpacity: 0.15,
  location: 1
});
```

https://codepen.io/team/amcharts/pen/554ecde6988fe5f4d065d4e1d3a71c04?editors=0010

2) Add an "empty" data point / category to data and make + use `endLocation` on the axis:

```JavaScript
var data = [{
  category: "2021",
  value: 2.5
}, {
  category: "2022",
  value: 2.6
}, {
  category: "2023",
  value: 2.8
}, {
  category: ""
}]

var xAxis = chart.xAxes.push(am5xy.CategoryAxis.new(root, {
  categoryField: "category",
  renderer: am5xy.AxisRendererX.new(root, {}),
  endLocation: 0
}));
  
xAxis.data.setAll(data);
```

https://codepen.io/team/amcharts/pen/25494cb869606b5f806a3a172540f9ce?editors=0010
