### ISSUE TITLE
I Want Drawing Control Event in amcharts 5 when User is Draw an eg. Doodle drawing in chart and when the mouse key is released it means the after the drawing is completed then i want event drawed successfully like that in that images after drawed

### ISSUE THREAD

**Issue by kirannarwade** [amcharts/amcharts5#1260]
![drawing2](https://github.com/amcharts/amcharts5/assets/90048456/6cdb6a8b-0005-4a44-96a6-5ff9551d49d8)
[

**Question**

**Environment (if applicable)**

**Additional context**

**Comment by kirannarwade** [comment]
After release the drawing make event

**Comment by martynasma** [comment]
Please refer to the drawing tool API documentation:
https://www.amcharts.com/docs/v5/charts/stock/toolbar/drawing-control/#Standalone_usage_API
