### ISSUE TITLE
Stock Chart: Error in indicators when we change the period to 1 minute

### ISSUE THREAD

**Issue by jalogar** [amcharts/amcharts5#1262]
**Bug description**
To reproduce this issue:

1. Just go to the **changing-data-granularity** example -> https://www.amcharts.com/demos/changing-data-granularity/
2. Click on "Open in CodePen"
3. Once the chart is loaded, add the MACD indicator, accepting the default values
4. Then change the interval to **1 minute**.
5. The MACD indicator shows totally wrong data, it looks like the interval wasn't changed for it.

<img width="1312" alt="image" src="https://github.com/amcharts/amcharts5/assets/516005/1d1624e5-c53a-43b2-9cf1-f48f0d06e244">

**Note**:
If we create the date axis using 1 minute interval, it works fine (but obviously, it has other wrong consequences):
```
var dateAxis = mainPanel.xAxes.push(am5xy.GaplessDateAxis.new(root, {
  baseInterval: {
    timeUnit: "minute",
    count: 1
  },
  renderer: am5xy.AxisRendererX.new(root, {
    minorGridEnabled: true
  }),
  tooltip: am5.Tooltip.new(root, {})
}));
```

**Comment by zeroin** [comment]
Indeed. I updated the example, besides setting baseInterval for the main axis, you must also set it for all indicators which are ChartIndicator:

```
  stockChart.indicators.each(function(indicator){
    if(indicator instanceof am5stock.ChartIndicator){
      indicator.xAxis.set("baseInterval", ev.item.interval);
    }
  })
```

**Comment by jalogar** [comment]
Thanks for the code. It would be good to add the property `xAxis` into the **Indicator** class documentation, even although I looked for something similar I didn't find it.
Also, I had the impression that it was the **stockChart** responsibility to update the base interval in its indicators.

**Comment by zeroin** [comment]
Yes, most likely we will do the changes so that this would be handled by the StockChart.
