### ISSUE TITLE
Comparison series list items remain in-active

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1264]
There is an in-built logic for comparison series that user cannot plot the already plotted products in the comparison series again. The already plotted products will not clickable.

So there is an issue I am facing that even though I have removed the products from the chart (comparison series) then too it is not letting me to plot it.

Images for reference:

1) You can see I have plotted 5 series : 

![image](https://github.com/amcharts/amcharts5/assets/137867461/385e0d42-3ea1-4e49-864b-7af161e314f5)

2) In this I have removed the 5th product & it available to plot &  it is clickable: 

![image](https://github.com/amcharts/amcharts5/assets/137867461/77282953-a0f4-4275-b69e-813bd846f379)

3) But in the last 2 images I have removed other products, then too in the product list it is not clickable:

![image](https://github.com/amcharts/amcharts5/assets/137867461/568739ba-5440-4985-a476-9de4ba5d6a45)
![image](https://github.com/amcharts/amcharts5/assets/137867461/8b964fc0-8227-4106-9b63-e05522db4b27)

Code for comparison series I am using:
```
    var comparisonControl = am5stock.ComparisonControl.new(root, {
      stockChart: stockChart,
      name: "",
      description: "Comparison Control",
      searchable: true,
      searchCallback: function (query) {
        var compared = stockChart.getPrivate("comparedSeries", []);
        var main = stockChart.get("stockSeries");
        if (compared.length > 4) {
          return [
            {
              label: "A maximum of 5 comparisons added",
              subLabel: "Remove some to add new ones",
              id: "",
              className: "am5stock-list-info",
            },
          ];
        }

        var comparedIds = [];
        am5.array.each(compared, function (series) {
          comparedIds.push(series.get("name"));
        });

        var list = getTicker(query);
        am5.array.each(list, function (item) {
          if (
            comparedIds.indexOf(item.value) !== -1 ||
            main.get("name") === item.value
          ) {
            item.disabled = true;
          }
        });
        return list;
      },
    });
    function getTicker(search) {
      if (search === "") {
        return [];
      }
      search = search.toLowerCase();
      var tickers = props.products;

      return tickers.filter(function (item) {
        return item.label.toLowerCase().match(search);
      });
    }
    async function loadData(ticker, series) {
      const cancelTokenFetchData = axios.CancelToken.source();
      let product = ticker + "_" + currentTimeInterval;

      try {
        const response = await axios.get(BACKEND_URL + FETCH_DATA_URL, {
          params: {
            products: product,
            cancelToken: cancelTokenFetchData.token,
          },
        });

        const res = response.data;

        Object.entries(res).forEach(([key, value]) => {
          let resobj = value;
          if (resobj.status !== "SUCCESS") {
            // Send error message to the Ant Design error dropdown
            message.error("An error occurred: " + resobj.status);
          } else {
            let modifiedDataDf = resobj.df?.map((item) => ({
              ...item,
              Date: new Date(item.Date).getTime(),
            }));
            am5.array.each(series, function (item) {
              item.data.setAll(modifiedDataDf);
            });
          }
        });
      } catch (error) {
        console.error(error);
        message.error("Network error occurred.");
      }
    }
    comparisonControl.events.on("selected", function (ev) {
      if (ev.item.value !== "" && ev.item.value !== undefined) {
        addComparingSeries(ev.item);
      }
    });
    function addComparingSeries(label) {
      var series = am5xy.LineSeries.new(root, {
        name: label.label,
        valueYField: "Close",
        calculateAggregates: true,
        valueXField: "Date",
        xAxis: dateAxis,
        yAxis: valueAxis,
      });
      var comparingSeries = stockChart.addComparingSeries(series);
      loadData(label.label, [comparingSeries]);
    }
```

I am using the lastest version of amcharts 5.7.2

**Comment by martynasma** [comment]
The logic which produces a search list and identifies which items are disabled resets completely in user (your) code. It's not built-in.

So you might want to change that logic the way you see fit.

I'm afraid debugging your own code is a bit outside of our scope. But if you can reproduce the issue in one of our demos, we'll make sure to fix it.

**Comment by workingbuddy10** [comment]
The below example in the amcharts is not working in codepen :

https://www.amcharts.com/docs/v5/charts/stock/toolbar/comparison-control/#Dynamic_list

@martynasma

**Comment by martynasma** [comment]
It's an example to illustrate how dynamic list works. It does not have all the logic in it for the sake of simplicity.

Please see the following demo with more elaborate logic:
https://www.amcharts.com/demos/stock-chart-comparing-prices/

**Comment by workingbuddy10** [comment]
It's not updating in the demo too,

Steps to reproduce : 

- Open Codepen of that demo.
- You can see the APPLE series is already there, now add one more series Advanced Micro Devices (AMD). 
- Now remove the APPLE series.
- And in the comaprison search box, just Type  "s".  AMD & MSTF both are selected.
![image](https://github.com/amcharts/amcharts5/assets/137867461/960d28fe-30e9-413b-b7a6-704568b6881e)


![image](https://github.com/amcharts/amcharts5/assets/137867461/ec52ddb5-1b64-429f-b86c-f6146527d2de)

@martynasma 

Like where it being handle that product which is removed from the comparison series is again clickable in the list?

**Comment by martynasma** [comment]
MSFT is disabled because its displayed as the main series. Why would you want to compare MSFT with MSFT?
AMD is disabled because you added it in the first step.

**Comment by workingbuddy10** [comment]
> MSFT is disabled because its displayed as the main series. Why would you want to compare MSFT with MSFT? AMD is disabled because you added it in the first step.

Oh very sorry, my bad!!
@martynasma

**Comment by workingbuddy10** [comment]
In the searchCallback adding the below piece of code worked for me: 
```
 list.forEach(function (item) {
    // Set disabled to true if item is in comparedIds or is the main series,
    // otherwise set it to false to re-enable the item.
    item.disabled = comparedIds.includes(item.value) || main.get("name") === item.value;
  });
```

full code of searchCallback:

```
      searchCallback: function (query) {
        var compared = stockChart.getPrivate("comparedSeries", []);
        var main = stockChart.get("stockSeries");
        if (compared.length > 4) {
          return [
            {
              label: "A maximum of 5 comparisons added",
              subLabel: "Remove some to add new ones",
              value: "",
              className: "am5stock-list-info",
            },
          ];
        }
        var list = getTicker(query);
        var comparedIds = [];
        am5.array.each(compared, function (series) {
          comparedIds.push(series.get("name"));
        });
        am5.array.each(list, function (item) {
          if (
            comparedIds.indexOf(item.value) !== -1 ||
            main.get("name") === item.value
          ) {
            item.disabled = true;
          }
        });
        list.forEach(function (item) {
          item.disabled =
            comparedIds.includes(item.value) || main.get("name") === item.value;
        });
        return list;
      }
```
@martynasma
