### ISSUE TITLE
Add `className` to JSON config-used classes (e.g. `Percent`, `Color`, `Template`)

### ISSUE THREAD

**Issue by davidjb** [amcharts/amcharts5#1267]
**Question**

Several of the classes used by the JSON config parser (e.g. [`Percent`](https://github.com/amcharts/amcharts5/blob/master/src/.internal/core/util/Percent.ts), `Color` and `Template`) don't currently have a `className` attached to it like a lot of other classes do. Could this be added?

The use case is to be able to procedurally generate the JSON config ahead of parsing and without these constants, I need to re-define them in my own code and ensure they always with the magic numbers used in in https://github.com/amcharts/amcharts5/blob/master/src/.internal/plugins/json/Json.ts.

If `className` could be added to each of these classes, then this benefits the amCharts' JSON parser as it can reference them directly, de-duplicating hardcoded references and simplifying the code.

**Environment (if applicable)**

- amCharts version: 5.7.4

**Additional context**

**Comment by Pauan** [comment]
I don't understand what you're trying to do, could you please explain more about your use-case?

Those classes are already support by the JSON parser, you just use `{ "type": "Percent", "value": 50 }`

If you're instead trying to serialize *to* JSON, then you can use `instanceof`:

```js
if (foo instanceof Percent) {
    return { "type": "Percent", value: foo.value };

} else if (foo instanceof Color) {
    return { "type": "Color", value: foo.hex };
}
```

**Comment by davidjb** [comment]
I'm writing a function in JavaScript that generates JSON config structure for a chart, before that config gets parsed with `parser.parse({...})`. The reason I'm doing it this way (declaratively) is so that I'm able to combine multiple JSON sources (user-defined chart config, data refs) and augment them with other settings, such as JSON config that represents `Percent` and `Color`; using generated JSON allows me to create the whole structure on the server ahead of handing to a static client for rendering.

At the moment, I have to define objects like so:

```js
import * as am5 from '@amcharts/amcharts5';

const pc50 = {
  type: "Percent",
  value: 50,
}
const grey = {
  type: "Color",
  value: 0x333333,
}
```
which involves hard-coding the class names (`"Percent"` and `"Color"`) and ensuring I maintain them in line with what's hard-coded into https://github.com/amcharts/amcharts5/blob/master/src/.internal/plugins/json/Json.ts.  In actuality, I define these as constants at the top of my file so I don't have repeat them, but I still need to maintain them.

My request was to add a `className` property to each of the Percent, Color, etc classes in their respective definitions, as most other classes have (Axis, Chart types, Shapes, etc). Then, the JSON parser can reference `am5.Percent.className` to avoid repeating the class names in its source, and so can I, meaning my generated JSON ends up with the same exact `type` strings that are used in the parser and everything refers to the same exact strings.

Happy to create a PR to the code base if that'd make things clearer to see it as a diff instead :+1:

**Comment by Pauan** [comment]
Are you trying to serialize amCharts objects to JSON? If so, then you have to handle `Percent` and `Color` differently than a regular `Entity`, and so an `instanceof` check is needed regardless.

**Comment by martynasma** [comment]
Just to clarify, the reason why `Percent` and `Color` do not have `className` property is that they are standalone classes, and do not extend `Entity` like majority of other objects in amCharts 5.

Besides as @Pauan says, you kinda have to treat them differently anyway, since `Entity`-based objects have settings, whereas standlone objects like `Color` have their own properties/accessors.

**Comment by davidjb** [comment]
> @Pauan: Are you trying to serialize amCharts objects to JSON? If so, then you have to handle `Percent` and `Color` differently than a regular `Entity`, and so an `instanceof` check is needed regardless.

No, I'm creating a JSON structure that can be parsed _into_ amCharts with https://www.amcharts.com/docs/v5/concepts/serializing/#Parsing.

It boils down to my code needing to use the same string literals as are on this line: https://github.com/amcharts/amcharts5/blob/master/src/.internal/plugins/json/Json.ts#L235. They're hard-coded into the `parseAsync` method, which means I also have to hard-code them on my side. 

> @martynasma: Just to clarify, the reason why `Percent` and `Color` do not have `className` property is that they are standalone classes, and do not extend `Entity` like majority of other objects in amCharts 5.
> 
> Besides as @Pauan says, you kinda have to treat them differently anyway, since `Entity`-based objects have settings, whereas standlone objects like `Color` have their own properties/accessors.

`className` was just a suggestion, it seemed like a common pattern in TypeScript (and amChart's codebase) for retaining the class's name. I'm open to any other suggestion that you feel would work to avoid hard-coding `"Percent"`, `"Color"`, etc.

**Comment by Pauan** [comment]
> It boils down to my code needing to use the same string literals as are on this line: https://github.com/amcharts/amcharts5/blob/master/src/.internal/plugins/json/Json.ts#L235. They're hard-coded into the parseAsync method, which means I also have to hard-code them on my side.

I'm not sure if that's the right way of looking at it. Yes they are hard-coded, but they're intentionally designed to be the same as the class name.

So it doesn't matter what `Json.ts` does, since `Json.ts` is just matching the class name.

So you can be assured that they will always be `"Percent"` and `"Color"`, because that is the same as the class name.

And adding in a `className` doesn't actually help at all. Let's say we add in a `className`, and then later change the name from `Percent` to `Percent2`. Well, your code will still break, since you now need to change your code to use `am5.Percent2.className`.

So using `className` doesn't make your code more future-proof. So why do you think it's an issue to hardcode `"Percent"` and `"Color"` in your code?

**Comment by davidjb** [comment]
@Pauan As I was saying, it doesn’t have to be `className`, that was just a suggestion of what the JSON parser could be changed to use instead of it hardcoding strings. 

As for why hardcoding values is an issue, it’s a fundamental in programming - it’s the reason shared values are exported from libraries or exposed in programmatic APIs - so both sides can reliably refer to the same value. If everyone had to redefine their own `am5.Root` class, interoperability would be nearly impossible. As a worked example, if JSON.ts changes to using the value `”PercentSomething”`, then my code breaks until I discover the change and update my side. By comparison, if amCharts/JSON.ts centralises and exports the `”Percent”` string, then you can update it to your heart’s content and my code will never break.

**Comment by martynasma** [comment]
How about if we pledge to not renaming `Percent`, `Color`, and `Template` ever? :)

The reason why we're reluctant to add those properties, is that there's a lot of standalone objects (that do not inherit from `Entity`). For the sake of consistency, we would need to add the properties to all of them, which would bloat up the code and compiled sizes, as well as memory footprint. Quite unnecessarily, I might say.

**Comment by martynasma** [comment]
Please don't take it the wrong way. We're grateful for your suggestions and feedback. And we HAVE extensively discussed this internally, before coming to above conclusion.

**Comment by davidjb** [comment]
Thanks for the consideration @martynasma and I appreciate the discussions you've had about this 🙂

I figured those values wouldn't be changing often, if at all, so my only ask is that if they were renamed, that it be considered a breaking change and/or otherwise generate a changelog entry. Thanks again.

**Comment by martynasma** [comment]
> I figured those values wouldn't be changing often, if at all, so my only ask is that if they were renamed, that it be considered a breaking change and/or otherwise generate a changelog entry. Thanks again.

Yup.

Renaming those would create a disaster on a much major scale than serializers breaking, so we won't do it. Not that there's a slightest need for that 😉

**Comment by davidjb** [comment]
> With respect to this exact issue, I utilise `am5.Percent.name` to get the class's textual name when generating the `config`, and slot that into the relevant areas of the `config`.

This worked okay under Parcel and Webpack's dev servers, but when compiled for production, the  `am5.Percent.name` gets rewritten to a single char (e.g. `n`) instead. So, I've since switched to just defining consts in our codebase. (Fwiw, it would be helpful if amCharts exported these strings, even if they're not on the `am5.Percent` classes themselves, so I don't need to redefine them and can just reference them).
