### ISSUE TITLE
Settings button target in stockchart

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1268]
I don't want to show the settings button for OHLC, volume legend & rest for other things like indicator, series comparison etc. I want the settings button.

![image](https://github.com/amcharts/amcharts5/assets/137867461/67a6f877-f2d6-49a1-adad-e274a6f4ee6a)

I have added this in my code, but it hides all the setting buttons :

`valueLegend.settingsButtons.template.set("visible", false);`

**Comment by martynasma** [comment]
After adding series to a legend data, do this:

```JavaScript
series.get("legendDataItem").get("settingsButton").set("forceHidden", true);
```

**Comment by workingbuddy10** [comment]
> After adding series to a legend data, do this:
> 
> ```js
> series.get("legendDataItem").get("settingsButton").set("forceHidden", true);
> ```

I tried doing this but it didn't like what I expected.

I don't want the settings button for OHLC & Volume Legend ONLY. 

Rest for others I Want the settings button.

I added this first `valueLegend.settingsButtons.template.set("visible", false); ` then later I added this `series.get("legendDataItem").get("settingsButton").set("forceHidden", true);` it didn't worked.  I guess it is overriding.



I tried doing this here : https://www.amcharts.com/demos/stock-chart-comparing-prices/ . Can you try in the codepen in this?

@martynasma

**Comment by martynasma** [comment]
Legend item == series.

I presume you know the type of series when you are adding it to chart and subsequently to legend, so it should be easy to grab its legend data item afterwards and disable settings button (or not) based on series type.
