### ISSUE TITLE
DateAxis tooltip and value-axis tooltip is overlapping

### ISSUE THREAD

**Issue by cyanaryan** [amcharts/amcharts5#1269]
**Question**
The dateAxis tooltip and the value-axis label tooltip is overlapping due to which some of the label is not visible. Is there any way to avoid it. I don't want to create a single tooltip. Just wanted a different approach.
![image](https://github.com/amcharts/amcharts5/assets/49512251/4540c52b-9aea-4df2-aea6-ef0c06dcc069)

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
I suggest you move your axis tooltip to a lower layer, e.g.:

```JavaScript
var xAxis = chart.xAxes.push(am5xy.DateAxis.new(root, {
  // ...
  tooltip: am5.Tooltip.new(root, {
    layer: 10
  })
}));
```
