### ISSUE TITLE
Changing the link start and end position for the tree chart

### ISSUE THREAD

**Issue by jangirdeepak** [amcharts/amcharts5#1273]
**Question**
I have a horizontal tree chart as shown below.

![tree_links](https://github.com/amcharts/amcharts5/assets/155146500/1ad4ded7-33dd-4a72-bc99-139a8a2bc523)

here, the links are not rendering properly after changing the tree orientation from vertical to horizontal. Is there any way to change the link start position from the starting node's middle of the right border and it should end to the connecting node's middle of left border.

![tree_link3](https://github.com/amcharts/amcharts5/assets/155146500/191431db-c38b-4683-b1cf-e967482bf192)

**Environment (if applicable)**
 - amCharts version : 5

**Comment by martynasma** [comment]
There's no way to set "anchor points" for links.

I would suggest positioning your custom nodes so they are aligned to the links the way you need to, not the other way around.
