### ISSUE TITLE
Exporting image

### ISSUE THREAD

**Issue by anshmishra010** [amcharts/amcharts5#1275]
I am using the exporting image feature in my amcharts stock chart.

I wanted to know if is there any way we can only get a copy of the image instead of downloading it to the local machine.

I use this feature to share any trend patterns or any strategy that I have made in my chart, so every time I have to download the image then only I can share it in my group. Instead of this can we copy the image (including zoom, indicators, drawings, etc.) just like the image is downloaded I want a copy. So that I just to paste wherever I want.

**Comment by martynasma** [comment]
There's no built-in functionality to copy image into clipboard.

That said, you can use an Exporting API to grab a raw data for image, then use your own code to plop it into clipboard.

https://www.amcharts.com/docs/v5/concepts/exporting/exporting-api/#getting-data-uri
