### ISSUE TITLE
Wordcloud rendering issues on various browsers

### ISSUE THREAD

**Issue by AericN** [amcharts/amcharts5#1277]
I'm not sure if I should post this as a bug or a question. We are trying to implement the wordcloud in our app using Amcharts 5 and we get issues in various browsers. Only chrome seems to work as expected. My OS is Sonoma 14.1.2

Safari:
In v17.1.2 (Sonoma) the wordcloud rendering breaks and the words are just stuck overlapping, but click features work. Conversely v16.4 (Ventura) works as expected. 

<img width="655" alt="Screenshot 2024-01-09 at 10 54 39 AM" src="https://github.com/amcharts/amcharts5/assets/16948082/fd46b31e-27cf-4928-9395-89348cea7ffc">

Brave:
Any version we test with has an issue where only some of the words that render will be clickable. If we disable 'brave shield' then it works as expected and all words are clickable. A point of interest is that it always works on brave if running locally, it's only after deployment that the browser has an issue.

Is there a setting or configuration that you know of that will help us get more uniform functionality across the browsers? Brave is a lesser used browser but it still runs on chromium. Safari though is a bit more of a blocker for us.

**Comment by martynasma** [comment]
Safari:
I did try all the WordCloud[ demos available](https://www.amcharts.com/demos/) on our website on Sonoma. They appear fine.

Do you perhaps have a CodePen of the one that does not work?

It could also be a font issue. Are you loading external fonts?

Brave:
Unfortunately, that's how it works.

By default, Brave scrambles canvas pixel detection (which we rely on), so interactions might work erratically on that browser, or not work at all.

They call it "fingerprinting protection". You may disable this specific protection, without completely turning the shields off.

It's not just amCharts. It's any web app that relies on interactions with the canvas elements.

**Comment by AericN** [comment]
Thank you for your response, I set up the pen and it still has the issue in safari v17.1.2 

Here is my pen link (picture of my output below): https://codepen.io/a-eric-n/pen/OJqRXMo

<img width="1049" alt="Screenshot 2024-01-10 at 10 22 11 AM" src="https://github.com/amcharts/amcharts5/assets/16948082/b21a0e85-000f-4ff1-a17b-4fdb025a778e">

I tried the wordcloud demo in safari and it works fine so I tried setting the fontFamily in my Pen to the same as the example and it rendered properly. I am not setting the font specifically in the wordcloud settings, but maybe it's inheriting it. 

We use Cerebri sans, sans-serif and if I try to manually set that in the wordcloud settings then it doesn't work but if I use something else like Courier New or Times New Roman it renders correctly. It also renders correctly if I set fontFamily to an empty string. What is the correct way to specify Cerebri or a generic sans-serif?

**Comment by martynasma** [comment]
I'm not seeing Cerebri set anywhere in your CodePen, so it's still unclear how you are loading it.

Is it installed on your Mac and you are just using `font-family: Cerebri` in your CSS, or you are loading it externally, like with FontAwesome or Google Fonts, etc?
