### ISSUE TITLE
Some bars missing on multi-series bar chart, depending on the values

### ISSUE THREAD

**Issue by lindapaiste** [amcharts/amcharts5#1278]
**Bug description**

### [CodeSandbox Demo](https://codesandbox.io/p/sandbox/missing-bars-on-chart-3kfg79?file=%2Fsrc%2FApp.tsx%3A106%2C34)

I have a chart which is missing some bars.  This is dependent on the values in the data.  The linked demo shows 2 versions of the chart. 
 The one with percentage-based values which is missing two bars.  The second version takes the same set of data but charts a different property (`count` instead of `percent`) and this one is fine.

The combined tooltip includes the counts from the missing bar for the "dog" category.  This category appears in both series but only one bar is shown.
The "cat" category has no tooltip as the Series A bar is missing and it is not present in the Series B data.
![image](https://github.com/amcharts/amcharts5/assets/28965286/9ecdefb2-2480-4f6a-9d32-5cdeae4cdfbd)

It appears that the issue is related to the order in which the data is passed to the chart.  My code sorts the categories based on the total count.  I found that if I really want to break things, I can pass the categories out of order.

This is what happens to the `count` chart (the one which was previously fine) if I randomize the category order.

![image](https://github.com/amcharts/amcharts5/assets/28965286/58589bf0-1984-4b39-a181-40c4bdd5a0ad)

You can comment out line 95 in the demo to see this in action.
```
 // Uncomment one of these lines for total chaos
 //sortedCategories = shuffle(sortedCategories);
 //sortedCategories = reverse(sortedCategories);
```

**Environment (if applicable)**

 - amCharts version 5.7.6
 - Chrome on Windows
 - React.js

**Comment by martynasma** [comment]
The order of categories in axis data and series data needs to be the same, as per docs:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/category-axis/#relation-to-data

**Comment by lindapaiste** [comment]
> The order of categories in axis data and series data needs to be the same, as per docs: https://www.amcharts.com/docs/v5/charts/xy-chart/axes/category-axis/#relation-to-data

Thanks for the response.  It's worth noting that it is not enough just to sort the data in each series in the same order as the categories if not every category is present in that series.  In order to get it working I had to fill in the missing data points with empty objects `{ label, count: 0 }`, as some categories are present on only one of the two series.

That is, this does not work:
```
const sorted = orderBy(unsorted, (datum) => // lodash fn
  sortedCategories.indexOf(datum.label)
);
series.data.setAll(sorted);
```
But this does:
```
const keyedByLabel = keyBy(unsorted, "label");  // lodash fn
const withMissing = sortedCategories.map(
  (label) => keyedByLabel[label] ?? { label, count: 0 }
);
series.data.setAll(withMissing);
```

**Comment by martynasma** [comment]
That is a correct observation. Thanks for sharing it!
