### ISSUE TITLE
Apply theme/chart config without passing root.

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1279]
I am using Stockchart of amcharts, and I am displaying the candlestick charts in multi-chart layout format.
I every time I increase the chart layout ( i.e going from 1x1 layout to 1x2) I have to again re-create the whole chart instance again, this might lead to slower the _multi-chart layout rendering_ performance. 

Is there any way where I don't have to pass the root every time or just I have to create the template of the whole chart instance just have to set the data? 

Or just keeping aside the chart theme and other UI chart config template so I that I don't have to re-create whole chart theme/utils config every time when I increase the layout by passing **_root_** .

**Comment by martynasma** [comment]
Could you please clarify what you mean by 1x1 and 1x2 layout?

Are you just adding/removing panels?

**Comment by workingbuddy10** [comment]
Yes adding chart panels 

1x1 = single chart
1x2 = Two charts

@martynasma

**Comment by martynasma** [comment]
Why not just push a new panel into `chart.panels` when you need to add a new panel, and dispose it when you need to remove a panel?

https://www.amcharts.com/docs/v5/charts/stock/panels/#Adding_panels
https://www.amcharts.com/docs/v5/charts/stock/panels/#Via_API

**Comment by workingbuddy10** [comment]
@martynasma  Thank you for this idea! 

Secondly I wanted to ask how can I stop the sync of the cursor in the given example as there is no "syncWith" property given. 
https://www.amcharts.com/docs/v5/charts/stock/panels/#Example

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.

**Comment by workingbuddy10** [comment]
Sure no issue, created a new issue for this!
@martynasma
