### ISSUE TITLE
Modifying Y-Axis Color 

### ISSUE THREAD

**Issue by zhenyong25** [amcharts/amcharts5#1281]
I'm creating a function to modify the y-axis color when pointer over. However, I'm unable to modify the color through changing the properties of **yAxis.renderer**. Is there any way to modify the properties? 

![render-y-axis](https://github.com/amcharts/amcharts5/assets/77121875/eff15a7b-c6e8-4f3a-ba56-fd869df7c3e5)

**Comment by martynasma** [comment]
Try setting colors directly on `yAxis.renderer`, not `line`.

Or are you trying to set color of the grid lines?

**Comment by zhenyong25** [comment]
Yes, I'm trying to set the colors for the grid lines and label. Initially it is black in color when creating new axis. I want to set the color when i hover over a legend or button. How should i set the color of it? 

![y-axis-color](https://github.com/amcharts/amcharts5/assets/77121875/3d2810a0-63bb-4449-9819-bae269a45432)

**Comment by martynasma** [comment]
```JavaScript
yAxis.get("renderer").grid.template.setAll({
  stroke: am5.color(0xff0000)
}):
```

**Comment by zhenyong25** [comment]
Thank you very much ! It works !

Would also like to ask, how can i modify the Label color? I've tried **adapter.add("fill", am5.color(0xFF0000))**, but it doesn't work
![label-color](https://github.com/amcharts/amcharts5/assets/77121875/2e41bd5f-01bb-44ce-9be9-ac446a8498fc)

**Comment by martynasma** [comment]
Much the same way:

```JavaScript
yAxis.get("renderer").labels.template.setAll({
  stroke: am5.color(0xff0000)
}):
```

**Comment by zhenyong25** [comment]
I've tried both these method:
![label-renderer](https://github.com/amcharts/amcharts5/assets/77121875/fe12390a-714c-40f4-9b3b-3cd71119eca9)

First method ends up with 
![set-fill](https://github.com/amcharts/amcharts5/assets/77121875/47a04324-7039-4093-b50a-a9c6c6fd754c)

Second method ends up with 
![Screenshot 2024-01-16 145108](https://github.com/amcharts/amcharts5/assets/77121875/1d89d136-eba7-4912-9c9f-0621edd2d5f4)

Both method doesn't change my Power(P) label text to the respective color

**Comment by martynasma** [comment]
I'm terribly sorry, I made a mistake. It should be `fill`:

```JavaScript
yAxis.get("renderer").labels.template.setAll({
  fill: am5.color(0xff0000)
}):
```

**Comment by zhenyong25** [comment]
Modified the code as below
![label-renderer](https://github.com/amcharts/amcharts5/assets/77121875/2da9d883-0754-450a-9d3c-8b6058e7857b)

The modified code doesn't change the end result color of the Power(P) label text
![set-fill](https://github.com/amcharts/amcharts5/assets/77121875/af7b3ec6-19c0-40be-adcc-cab0966dfdd9)

Just fyi, the Label was created with 
![yaxis-label](https://github.com/amcharts/amcharts5/assets/77121875/91f00c9c-f3b9-4f47-ba24-973cae779b1a)

**Comment by martynasma** [comment]
That is not an axis label. It's just a standalone `Label` which you added to the axis children.

You need to retain a reference to it and change tis color, too:

```JavaScript
var axisTitle = yAxis.children.unshift(.....);

.......

axisTitle.setAll({
  fill: ....
});
```

In other news, posting screenshots of code instead of code as text is not super cool 😉

**Comment by zhenyong25** [comment]
Thank you very much for the help !  @martynasma  It solved my issue !
Thank you for the feedback as well. It was my first issue created. Will learn to post code next time instead !
