### ISSUE TITLE
clearDrawings function breaks chart while drawing line

### ISSUE THREAD

**Issue by marciammart** [amcharts/amcharts5#1283]
**Bug description**

I've noticed that, if I call the `DrawingControl.clearDrawings()` function while I'm drawing a line in the chart (after selecting the start of the line but not the end), the chart stops responding to any updates.

**Environment (if applicable)**
I'm using version 5.5.1 with React/Typescript

**Comment by martynasma** [comment]
I can't seem to be able to reproduce this with the current version (5.7.6).

Can you confirm this is still happening to you when you upgrade?

**Comment by marciammart** [comment]
Upgrading fixes the problem. Sorry for the inconvenience. Thank you!
