### ISSUE TITLE
Bullet sprite tooltipText does not work if fill is undefined

### ISSUE THREAD

**Issue by theoturner** [amcharts/amcharts5#1284]
When using any sprite shape for a bullet, if the `fill` property is undefined, `tooltipText` will not render. Example:

```js
am5.Bullet.new(root, {
  sprite: am5.Circle.new(root, {
    stroke: am5.color("#000000"),
    width: 10,
    height: 10,
    tooltipText: "A tooltip"
  })
})
```

**Environment**

AmCharts 5.7.6 with React.

Reproducible in Chrome, Brave, Firefox and Safari.

**Additional context**

Someone may want to have points with `tooltipText` on their chart with a transparent center. For example, if multiple types of points can occur at the same X/Y co-ordinate, this is a good way to indicate both exist.

Someone may be forced to use `tooltipText` instead of the `tooltip` for the relevant `series` because such tooltips cannot be shown for all points in a series if multiple points occur at the same X-coordinate, as was raised in [this ticket from 2021](https://github.com/amcharts/amcharts4/issues/3849).

The obvious fix is to specify a fill with transparency, however, **transparency also does not work for fill colours for these sprites**, e.g.
```js
am5.Bullet.new(root, {
  sprite: am5.Circle.new(root, {
    stroke: am5.color("#000000"),
    fill: am5.color("rgba(0, 0, 0, 0)"),
    width: 10,
    height: 10,
    tooltipText: "A tooltip"
  })
})
```
The point should render with a transparent center, but it is black.

So, for the moment, there is no way to have a transparent fill and use tooltips using the built in shapes.

**Comment by martynasma** [comment]
`fill` needs to be defined in order for an element to trigger hovers. Otherwise we treat it as transparent, only stroke triggering hover. It's by design.

There's a workaround if you want to keep the bullet transparent but hoverable all over its' area: set both `fill` (to any color) and `fillOpacity: 0`:

```JavaScript
am5.Bullet.new(root, {
  sprite: am5.Circle.new(root, {
    stroke: am5.color("#000000"),
    fill: am5.color("rgba(0, 0, 0, 0)"),
    fillOpacity: 0,
    width: 10,
    height: 10,
    tooltipText: "A tooltip"
  })
})
```
