### ISSUE TITLE
How to customize legend text color

### ISSUE THREAD

**Issue by adiamini** [amcharts/amcharts5#1285]
I'm trying to figure out how to change the base color of a chart's legend.

**Current behaviour**: the label appears **dark gray**; when clicking on it (the corresponding data is hidden and) the label goes **light gray**.

**Desired behaviour**: the label appears of **{stroke} color**; when clicking on it (the corresponding data is hidden and) the label goes **light gray**.

I tried using formatting in legendLabelText, like

`legendLabelText: "[{stroke}]{name}[/]"`

Unfortunately this is **not the solution** because the label initially appears of the **{stroke} color**, but when clicking on it (the corresponding data is hidden so) I expect it to go light gray, but it stays of the **{stroke} color**.

Here a basic fiddle showing the case: https://jsfiddle.net/fhryacsL/

**Comment by martynasma** [comment]
It can be implemented using an adapter:

```JavaScript
legend.labels.template.adapters.add("fill", function(fill, target) {
	if (fill && fill.hex == 11382189) {
  	return fill;
  }
  else if (target.dataItem) {
  	return target.dataItem.component.get("stroke");
  }
  return am5.color(0x000000);
});
```

**Comment by adiamini** [comment]
Thanks you very much @martynasma, it works successfully!

**Comment by rammarind03** [comment]
@adiamini , Do you have the woking example with the above from @martynasma . I am having the same issue, however the above code does not work for me
Thanks

**Comment by rammarind03** [comment]
I am able to make it work. I was trying with both legendLabelText and the above code. Hence it didnt work earlier. I needed to remove the legendLabelText setting in the series to make it work. 
Thanks @adiamini , @martynasma
