### ISSUE TITLE
Disable cursor sync in XY chart 

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1286]
I want to disable the cursor sync between multiple panels. In the given example as there is no "syncWith" property given.

https://www.amcharts.com/docs/v5/charts/stock/panels/#Example

I tried doing this, but it didn't worked
```

  var cursor = am5xy.XYCursor.new(root, {
    yAxis: valueAxis,
    xAxis: dateAxis,
    snapToSeries: false,
    snapToSeriesBy: false,
  });
  mainPanel.set("cursor", cursor);
```

**Comment by workingbuddy10** [comment]
I tried doing this, but it didn't worked
```

  var cursor = am5xy.XYCursor.new(root, {
    yAxis: valueAxis,
    xAxis: dateAxis,
    snapToSeries: false,
    snapToSeriesBy: false,
  });
  mainPanel.set("cursor", cursor);
```

**Comment by martynasma** [comment]
Just call for each panel **after** it has been added to charts:

```JavaScript
panel.removePrivate("otherCharts");
```

**Comment by workingbuddy10** [comment]
> Just call for each panel **after** it has been added to charts:
> 
> ```js
> panel.removePrivate("otherCharts");
> ```
This worked for cursor, sync!

Also there is a sync between the Zooming of the charts scrollbar etc.
I want to access the properties of the panel individually.  If I zoom in one chart panel only that should be zoomed.
