### ISSUE TITLE
AMCharts 5 DATA JSON FILE LOAD problem.

### ISSUE THREAD

**Issue by TaeJin82** [amcharts/amcharts5#1287]
Hi, I'm a beginner

I would like to apply the data part by loading the m2.json file.

[M2DATA.json](https://github.com/amcharts/amcharts5/files/13958219/M2DATA.json)

help ME Plz

THANK YOU

`

               <script>
                am5.ready(function () {

                  // Create root element
                  // https://www.amcharts.com/docs/v5/getting-started/#Root_element
                  var root = am5.Root.new("chartdiv");

                  // Set themes
                  // https://www.amcharts.com/docs/v5/concepts/themes/
                  root.setThemes([
                    am5themes_Animated.new(root)
                  ]);

                  root.dateFormatter.setAll({
                    dateFormat: "yyyy",
                    dateFields: ["valueX"]
                  });

                  var data = [
                    { "DATE": "2004-01", "M2": 901, "TOTAL": 798, "RATE": 89 },
                    { "DATE": "2004-02", "M2": 907, "TOTAL": 803, "RATE": 89 },
                    { "DATE": "2004-03", "M2": 917, "TOTAL": 809, "RATE": 88 },
                    { "DATE": "2004-04", "M2": 918, "TOTAL": 826, "RATE": 90 },
                    { "DATE": "2004-05", "M2": 921, "TOTAL": 833, "RATE": 90 },
                    { "DATE": "2004-06", "M2": 927, "TOTAL": 834, "RATE": 90 },
                    { "DATE": "2004-07", "M2": 932, "TOTAL": 835, "RATE": 90 },
                    { "DATE": "2004-08", "M2": 936, "TOTAL": 835, "RATE": 89 },
                    { "DATE": "2004-09", "M2": 946, "TOTAL": 834, "RATE": 88 },
                    { "DATE": "2004-10", "M2": 947, "TOTAL": 834, "RATE": 88 },
                    { "DATE": "2004-11", "M2": 949, "TOTAL": 833, "RATE": 88 },
                    { "DATE": "2004-12", "M2": 955, "TOTAL": 831, "RATE": 87 }
                    

                  ];

                  // Create chart
                  // https://www.amcharts.com/docs/v5/charts/xy-chart/
                  var chart = root.container.children.push(am5xy.XYChart.new(root, {
                    focusable: true,
                    panX: true,
                    panY: true,
                    wheelX: "panX",
                    wheelY: "zoomX",
                    pinchZoomX: true,
                    paddingLeft: 0,
                    layout: root.verticalLayout
                  }));

                  var easing = am5.ease.linear;

                  // Create axes
                  // https://www.amcharts.com/docs/v5/charts/xy-chart/axes/
                  var xAxis = chart.xAxes.push(am5xy.DateAxis.new(root, {
                    maxDeviation: 0.1,
                    groupData: false,
                    baseInterval: {
                      timeUnit: "month",
                      count: 1
                    },

                    renderer: am5xy.AxisRendererX.new(root, {
                      minorGridEnabled: true,
                      minGridDistance: 70
                    }),
                    tooltip: am5.Tooltip.new(root, {}),
                    tooltipDateFormat: "yyyy-MM"
                  }));
                  xAxis.get("dateFormats")["month"] = "yyyy/MM";

                  // Craete Y-axes
                  var yAxis1 = chart.yAxes.push(
                    am5xy.ValueAxis.new(root, {
                      height: am5.percent(50),
                      x: am5.percent(100),
                      centerX: am5.percent(100),
                      renderer: am5xy.AxisRendererY.new(root, {})
                    })
                  );

                  yAxis1.axisHeader.children.push(am5.Label.new(root, {
                    text: "비율(시가총액/M2)",
                    fontWeight: "500"
                  }));

                  var yAxis2 = chart.yAxes.push(
                    am5xy.ValueAxis.new(root, {
                      height: am5.percent(50),
                      x: am5.percent(100),
                      centerX: am5.percent(100),
                      renderer: am5xy.AxisRendererY.new(root, {})
                    })
                  );

                  yAxis2.axisHeader.set("paddingTop", 10);
                  yAxis2.axisHeader.children.push(am5.Label.new(root, {
                    text: "아파트시가총액,M2",
                    fontWeight: "500"
                  }));

                  // Stack Y-axes(Y축 2개 나누기)
                  chart.leftAxesContainer.set("layout", root.verticalLayout);

                  // Add series
                  // https://www.amcharts.com/docs/v5/charts/xy-chart/series/

                  //M2시리즈
                  var M2series = chart.series.push(am5xy.LineSeries.new(root, {
                    minBulletDistance: 10,
                    connect: false,
                    xAxis: xAxis,
                    yAxis: yAxis2,

                    valueYField: "M2",
                    valueXField: "DATE",
                    tooltip: am5.Tooltip.new(root, {
                      pointerOrientation: "horizontal",
                      labelText: "M2 {valueY}조"
                    })
                  }));

                  M2series.fills.template.setAll({
                    strokeWidth: 2,
                    fillOpacity: 2,
                    visible: true
                  });

                  M2series.strokes.template.setAll({
                    strokeWidth: 2
                  });

                  // Set up data processor to parse string dates
                  // https://www.amcharts.com/docs/v5/concepts/data/#Pre_processing_data
                  M2series.data.processor = am5.DataProcessor.new(root, {
                    dateFormat: "yyyy-MM",
                    dateFields: ["DATE"]
                  });

                  //시가총액 시리즈
                  var TOTALseries = chart.series.push(am5xy.LineSeries.new(root, {
                    minBulletDistance: 10,
                    connect: false,
                    xAxis: xAxis,
                    yAxis: yAxis2,
                    valueYField: "TOTAL",
                    valueXField: "DATE",
                    tooltip: am5.Tooltip.new(root, {
                      pointerOrientation: "horizontal",
                      labelText: "시가총액{valueY}조"
                    })
                  }));

                  //채움 구성
                  TOTALseries.fills.template.setAll({
                    fillOpacity: 0.2,
                    visible: true
                  });

                  //선 구성
                  TOTALseries.strokes.template.setAll({
                    strokeWidth: 2
                  });

                  // Set up data processor to parse string dates
                  // https://www.amcharts.com/docs/v5/concepts/data/#Pre_processing_data
                  TOTALseries.data.processor = am5.DataProcessor.new(root, {
                    dateFormat: "yyyy-MM",
                    dateFields: ["dateDATE"]
                  });

                  //비율시리즈
                  var RATEseries = chart.series.push(am5xy.LineSeries.new(root, {
                    minBulletDistance: 10,
                    connect: false,
                    xAxis: xAxis,
                    yAxis: yAxis1,

                    valueYField: "RATE",
                    valueXField: "DATE",
                    tooltip: am5.Tooltip.new(root, {
                      pointerOrientation: "horizontal",
                      labelText: "비율(시가총액/M2) {valueY}%"
                    })
                  }));

                  //선 구성
                  RATEseries.strokes.template.setAll({
                    strokeWidth: 3
                  });

                  // Set up data processor to parse string dates
                  // https://www.amcharts.com/docs/v5/concepts/data/#Pre_processing_data
                  RATEseries.data.processor = am5.DataProcessor.new(root, {
                    dateFormat: "yyyy-MM",
                    dateFields: ["DATE"]
                  });

                  // Setting data
                  M2series.data.setAll(data);
                  TOTALseries.data.setAll(data);
                  RATEseries.data.setAll(data);

                  // Add circle bullet
                  // https://www.amcharts.com/docs/v5/charts/xy-chart/series/#Bullets
                  M2series.bullets.push(function () {
                    var circle = am5.Circle.new(root, {
                      radius: 4,
                      fill: root.interfaceColors.get("background"),
                      stroke: M2series.get("fill"),
                      strokeWidth: 2
                    })

                    return am5.Bullet.new(root, {
                      sprite: circle
                    })
                  });

                  TOTALseries.bullets.push(function () {
                    var graphics = am5.Rectangle.new(root, {
                      width: 10,
                      height: 10,
                      centerX: am5.p50,
                      centerY: am5.p50,
                      fill: TOTALseries.get("stroke")
                    });

                    return am5.Bullet.new(root, {
                      sprite: graphics
                    });
                  });

                  // Add cursor
                  // https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/
                  var cursor = chart.set("cursor", am5xy.XYCursor.new(root, {
                    xAxis: xAxis,
                    behavior: "none"
                  }));
                  cursor.lineY.set("visible", false);

                  // add scrollbar
                  chart.set("scrollbarX", am5.Scrollbar.new(root, {
                    orientation: "horizontal"
                  }));

                  // Make stuff animate on load
                  // https://www.amcharts.com/docs/v5/concepts/animations/
                  chart.appear(1000, 100);

                }); // end am5.ready()
              </script> `

**Comment by workingbuddy10** [comment]
The below example might help you: 
https://www.amcharts.com/docs/v5/concepts/data/#Loading

@TaeJin82

**Comment by TaeJin82** [comment]
> @workingbuddy10 
   Thank you for answer.
  
The below example might help you: https://www.amcharts.com/docs/v5/concepts/data/#Loading

I saw this and applied it, but an error occurred.

Please modify the code below.

please.

`                 
 
                </script>
                 am5.ready(function () {

                  // Create root element
                  // https://www.amcharts.com/docs/v5/getting-started/#Root_element
                  var root = am5.Root.new("chartdiv");


                  // Set themes
                  // https://www.amcharts.com/docs/v5/concepts/themes/
                  root.setThemes([
                    am5themes_Animated.new(root)
                  ]);

                  root.dateFormatter.setAll({
                    dateFormat: "yyyy",
                    dateFields: ["valueX"]
                  });


                  am5.net.load("/m2.json").then(function (result) {

                    M2series.data.setAll(am5.JSONParser.parse(result.response));
                    TOTALseries.data.setAll(am5.JSONParser.parse(result.response));
                    RATEseries.data.setAll(am5.JSONParser.parse(result.response));
                  
                  }).catch(function (result) {
                    // This gets executed if there was an error loading URL
                    // ... handle error
                    console.log("Error loading " + result.xhr.responseURL);
                  });

                  // Create chart
                  // https://www.amcharts.com/docs/v5/charts/xy-chart/
                  var chart = root.container.children.push(am5xy.XYChart.new(root, {
                    focusable: true,
                    panX: true,
                    panY: true,
                    wheelX: "panX",
                    wheelY: "zoomX",
                    pinchZoomX: true,
                    paddingLeft: 0,
                    layout: root.verticalLayout
                  }));

                  var easing = am5.ease.linear;


                  // Create axes
                  // https://www.amcharts.com/docs/v5/charts/xy-chart/axes/
                  var xAxis = chart.xAxes.push(am5xy.DateAxis.new(root, {
                    maxDeviation: 0.1,
                    groupData: false,
                    baseInterval: {
                      timeUnit: "month",
                      count: 1
                    },

                    renderer: am5xy.AxisRendererX.new(root, {
                      minorGridEnabled: true,
                      minGridDistance: 70
                    }),
                    tooltip: am5.Tooltip.new(root, {}),
                    tooltipDateFormat: "yyyy-MM"
                  }));
                  xAxis.get("dateFormats")["month"] = "yyyy/MM";

                  // Craete Y-axes
                  var yAxis1 = chart.yAxes.push(
                    am5xy.ValueAxis.new(root, {
                      height: am5.percent(50),
                      x: am5.percent(100),
                      centerX: am5.percent(100),
                      renderer: am5xy.AxisRendererY.new(root, {})
                    })
                  );

                  yAxis1.axisHeader.children.push(am5.Label.new(root, {
                    text: "비율(시가총액/M2)",
                    fontWeight: "500"
                  }));

                  var yAxis2 = chart.yAxes.push(
                    am5xy.ValueAxis.new(root, {
                      height: am5.percent(50),
                      x: am5.percent(100),
                      centerX: am5.percent(100),
                      renderer: am5xy.AxisRendererY.new(root, {})
                    })
                  );

                  yAxis2.axisHeader.set("paddingTop", 10);
                  yAxis2.axisHeader.children.push(am5.Label.new(root, {
                    text: "아파트시가총액,M2",
                    fontWeight: "500"
                  }));

                  // Stack Y-axes(Y축 2개 나누기)
                  chart.leftAxesContainer.set("layout", root.verticalLayout);


                  // Add series
                  // https://www.amcharts.com/docs/v5/charts/xy-chart/series/

                  //M2시리즈
                  var M2series = chart.series.push(am5xy.LineSeries.new(root, {
                    minBulletDistance: 10,
                    connect: false,
                    xAxis: xAxis,
                    yAxis: yAxis2,

                    valueYField: "M2",
                    valueXField: "DATE",
                    tooltip: am5.Tooltip.new(root, {
                      pointerOrientation: "horizontal",
                      labelText: "M2 {valueY}조"
                    })
                  }));

                  M2series.fills.template.setAll({
                    strokeWidth: 2,
                    fillOpacity: 2,
                    visible: true
                  });

                  M2series.strokes.template.setAll({
                    strokeWidth: 2
                  });


                  // Set up data processor to parse string dates
                  // https://www.amcharts.com/docs/v5/concepts/data/#Pre_processing_data
                  M2series.data.processor = am5.DataProcessor.new(root, {
                    dateFields: ["M2"],
                    dateFormat: "yyyy-MM",
                    dateFields: ["DATE"]
                  });

                  //시가총액 시리즈
                  var TOTALseries = chart.series.push(am5xy.LineSeries.new(root, {
                    minBulletDistance: 10,
                    connect: false,
                    xAxis: xAxis,
                    yAxis: yAxis2,
                    valueYField: "TOTAL",
                    valueXField: "DATE",
                    tooltip: am5.Tooltip.new(root, {
                      pointerOrientation: "horizontal",
                      labelText: "시가총액{valueY}조"
                    })
                  }));

                  //채움 구성
                  TOTALseries.fills.template.setAll({
                    fillOpacity: 0.2,
                    visible: true
                  });

                  //선 구성
                  TOTALseries.strokes.template.setAll({
                    strokeWidth: 2
                  });


                  // Set up data processor to parse string dates
                  // https://www.amcharts.com/docs/v5/concepts/data/#Pre_processing_data
                  TOTALseries.data.processor = am5.DataProcessor.new(root, {
                    dateFields: ["TOTAL"],
                    dateFormat: "yyyy-MM",
                    
                  });

                  //비율시리즈
                  var RATEseries = chart.series.push(am5xy.LineSeries.new(root, {
                    minBulletDistance: 10,
                    connect: false,
                    xAxis: xAxis,
                    yAxis: yAxis1,

                    valueYField: "RATE",
                    valueXField: "DATE",
                    tooltip: am5.Tooltip.new(root, {
                      pointerOrientation: "horizontal",
                      labelText: "비율(시가총액/M2) {valueY}%"
                    })
                  }));

                  //선 구성
                  RATEseries.strokes.template.setAll({
                    strokeWidth: 3
                  });


                  // Set up data processor to parse string dates
                  // https://www.amcharts.com/docs/v5/concepts/data/#Pre_processing_data
                  RATEseries.data.processor = am5.DataProcessor.new(root, {
                    dateFields: ["RATE"],
                    dateFormat: "yyyy-MM",
                    
                  });






                  // Add circle bullet
                  // https://www.amcharts.com/docs/v5/charts/xy-chart/series/#Bullets
                  M2series.bullets.push(function () {
                    var circle = am5.Circle.new(root, {
                      radius: 4,
                      fill: root.interfaceColors.get("background"),
                      stroke: M2series.get("fill"),
                      strokeWidth: 2
                    })

                    return am5.Bullet.new(root, {
                      sprite: circle
                    })
                  });

                  TOTALseries.bullets.push(function () {
                    var graphics = am5.Rectangle.new(root, {
                      width: 10,
                      height: 10,
                      centerX: am5.p50,
                      centerY: am5.p50,
                      fill: TOTALseries.get("stroke")
                    });

                    return am5.Bullet.new(root, {
                      sprite: graphics
                    });
                  });





                  // Add cursor
                  // https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/
                  var cursor = chart.set("cursor", am5xy.XYCursor.new(root, {
                    xAxis: xAxis,
                    behavior: "none"
                  }));
                  cursor.lineY.set("visible", false);

                  // add scrollbar
                  chart.set("scrollbarX", am5.Scrollbar.new(root, {
                    orientation: "horizontal"
                  }));




                  // Make stuff animate on load
                  // https://www.amcharts.com/docs/v5/concepts/animations/
                  chart.appear(1000, 100);

                }); // end am5.ready()
              </script>`

**Comment by workingbuddy10** [comment]
Can you paste the code in the codepen and provide the link, it would be better to test the code?


@TaeJin82

**Comment by TaeJin82** [comment]
@workingbuddy10 

I make codepen

`<p class="codepen" data-height="300" data-default-tab="html,result" data-slug-hash="poYeRNZ" data-user="invoke20" style="height: 300px; box-sizing: border-box; display: flex; align-items: center; justify-content: center; border: 2px solid; margin: 1em 0; padding: 1em;">
  <span>See the Pen <a href="https://codepen.io/invoke20/pen/poYeRNZ">
  M2</a> by KIMTAEJIN (<a href="https://codepen.io/invoke20">@invoke20</a>)
  on <a href="https://codepen.io">CodePen</a>.</span>
</p>
<script async src="https://cpwebassets.codepen.io/assets/embed/ei.js"></script>`

**Comment by martynasma** [comment]
Your web server prohibits loading of data as it does not have a CORS policy.

For more information how to configure data access policies on your server, check here:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
