### ISSUE TITLE
Custom tooltip for null value while handling null for display

### ISSUE THREAD

**Issue by FTInterritus7624** [amcharts/amcharts5#1288]
Hello, I'm trying to create a custom tooltip that essentially shows the start and end date, but if there is no end date (null), tooltip will show something different. I used adapters to try and handle that, which logically, I believe looks correct. However, if null exists, then the column will not be displayed.

As a solution to that, I used DataProcessor's emptyAs to handle the null to display the column, but that would result in the tooltip to use emptyAs where the ToDate was once null. Is there a way to have the custom tooltip for when there is null while also being able to display data? Because the whole idea is that if something is ongoing, display-wise, it would just show current time as end date, but the tooltip will have better info in that end date would be shown in text as "N/A"

This is my codepen:
https://codepen.io/FTInterritus7624/pen/bGZqLMw

**Comment by FTInterritus7624** [comment]
So, I just want the column to look like all the other data, nothing different or special. Hypothetically, if data was sent in where toDate (which I consider as the end date) is null because it has yet to end, The column would go from fromDate (our start date) to toDate (which I set as "2018-01-02 0:30" being the hypothetical current date, using emptyAs). The issue really is making the tooltip show the "toDate - null" for the specific data point since null already is overwritten

**Comment by martynasma** [comment]
You may add some other info to data, which you could use to identify such no-end data items in the adapter, e.g.:

```JavaScript
  {
    category: "Donald",
    fromDate: "2018-01-01 13:00",
    toDate: "2018-01-02 0:30",
    noEnd: true,
    columnSettings: {
      fill: am5.Color.brighten(colors.getIndex(8), 0)
    }
  }
```
