### ISSUE TITLE
unserializeDrawings example to add Arrow&Icon on stock chart

### ISSUE THREAD

**Issue by chz8494** [amcharts/amcharts5#1289]
**Question**
I was following example from [serializing](https://www.amcharts.com/docs/v5/charts/stock/serializing-indicators-annotations/), and it creates beautiful line.
```
    const drawing = [{
        "__tool": "Line",
        "__panelIndex": 0,
        "__drawing": [
            {
                "stroke": {
                    "type": "Template",
                    "settings": {
                        "stroke": {
                            "type": "Color",
                            "value": "#882dff"
                        },
                        "strokeOpacity": 1,
                        "strokeDasharray": [],
                        "strokeWidth": 2
                    }
                },
                "fill": {
                    "type": "Template",
                    "settings": {
                        "fill": {
                            "type": "Color",
                            "value": "#ad6eff"
                        },
                        "fillOpacity": 0.5
                    }
                },
                "index": 1,
                "showExtension": true,
                "corner": "e",
                "__parse": true
            },
            {
                "valueY": 0.0000009,
                "valueX": 1705136940044,
                "corner": "p1",
                "index": 1,
                "__parse": true
            },
            {
                "valueY": 0.0000008,
                "valueX": 1705438020040,
                "corner": "p2",
                "index": 1,
                "__parse": true
            }
        ]
    }
    ]
    drawingControl.unserializeDrawings(drawing);
```

now I'd like to draw something like this
<img width="543" alt="image" src="https://github.com/amcharts/amcharts5/assets/19349532/fc68a2f7-9487-49c6-88fe-cfa373b682a9">
I guess there should be an available tool `Arrows&Icons` that I can draw and mark on my chart, but I can't find an example from your website.

If anyone knows how to do it, please share an example.
Thank you in advance

**Comment by martynasma** [comment]
You can select Draw and then an Arrows & Icons tool from a dropdown.

Once you draw your icons, you will be able to serialize them.

![image](https://github.com/amcharts/amcharts5/assets/1458520/92f65687-0c8e-4491-8779-c0839052a45b)

**Comment by chz8494** [comment]
@martynasma 
I know we can add Arrows&Icons through gui, but how to do it through code:
```
        "__tool": "Arrows&Icons",
        "__panelIndex": 0,
        "__drawing": [
```

**Comment by martynasma** [comment]
Well, we don't have a tutorial on how to construct custom unserializable JSON for drawings.

The workflow would be to create drawings using UI, serialize them, use the serialized data and maybe modify it.

Though, it looks like you need to just add bullets on certain data items. For that maybe using selectively-added bullets would be a better idea:
https://www.amcharts.com/docs/v5/concepts/common-elements/bullets/#Adding_data_item_bullet

**Comment by chz8494** [comment]
Cool, sounds like a solution. How to use it on `CandlestickSeries`? 
it seems like can only be used on `LineSeries`? how to draw on any spot on a chart?

**Comment by martynasma** [comment]
You can add it to absolutely any series, including `CandlestickSeries`.
