### ISSUE TITLE
How change column tooltip settings without change tooltip transition animation

### ISSUE THREAD

**Issue by HASSANDL** [amcharts/amcharts5#129]
In column series after ```series.set("tooltip", tooltip);``` changed transition animation for tooltip.
How change tooltip settings without change animation. compare examples:
https://codepen.io/hassandl/pen/RwLaaWJ
https://codepen.io/hassandl/pen/abLNdMm

**Comment by martynasma** [comment]
I'm not entirely sure what you mean by "change transition animation". Can you please explain?

**Comment by HASSANDL** [comment]
When change tooltip settings in column series (```series.set("tooltip", tooltip);```), tooltip transition animation is changed.
compare two example and pay attention to tooltip transition.
https://codepen.io/hassandl/pen/RwLaaWJ
https://codepen.io/hassandl/pen/abLNdMm

**Comment by martynasma** [comment]
It's because now each series have own tooltip.

You can create a single `Tooltip` instance and use it for all series:

https://codepen.io/team/amcharts/pen/bGopwoK?editors=0010

**Comment by HASSANDL** [comment]
thanks a lot.
