### ISSUE TITLE
Hide yAxis grid lines while keeping the base line visible

### ISSUE THREAD

**Issue by marciammart** [amcharts/amcharts5#1298]
**Question**

Is there a way to hide the all the `yAxis` grid lines while keeping the base line visible?
I've tried using `myTheme.rule("Grid", ["base"]).setAll` to set `strokeOpacity` to 1 in the base line and then 0 in the `yRenderer`, but as soon as I set the opacity to 0 in the `yRenderer` all grid lines disappear, including the base line.

**Comment by martynasma** [comment]
Could you please clarify: by "base line" do you mean a zero-value line or the actual axis line that goes along the edge of the plot area?

https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#base-grid
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#axis-line

**Comment by marciammart** [comment]
The zero-value line. I have the axis line at the bottom, with `visible: false`, and I would like to have the zero-value line in the chart but without adding any other grid lines

**Comment by martynasma** [comment]
OK, so you can create a custom theme that sets different visibility settings for regular and base grid:

```JavaScript
var myTheme = am5.Theme.new(root);

myTheme.rule("Grid").setAll({
  strokeOpacity: 0
});

myTheme.rule("Grid", ["base"]).setAll({
  strokeOpacity: 1
});

root.setThemes([
  myTheme
]);
```

**Comment by marciammart** [comment]
That works, thanks you!
