### ISSUE TITLE
HeatRules on StepLineSeries

### ISSUE THREAD

**Issue by SekMENtina** [amcharts/amcharts5#13]
Hi!

I want to change fill color on stepline series by using heat rules custom function. Is it possible ?

example:
https://stackblitz.com/edit/vue-dvdmto?file=src%2FChart.vue

**Comment by martynasma** [comment]
I'm afraid heat rules does not work that way.

The only way to color individual sections of `LineSeries` (or `StepLineSeries` for that matter) fill is via axis ranges:

https://www.amcharts.com/docs/v5/charts/xy-chart/axes/axis-ranges/#Series_axis_ranges

**Comment by SekMENtina** [comment]
Thanks a lot.
It not so cool as declarative heat rules but this is axactly what i was looking for.
