### ISSUE TITLE
Geocoordinates of MapChart click

### ISSUE THREAD

**Issue by olneyMatt** [amcharts/amcharts5#130]
Hi,

I'm trying to convert a mouse click on a MapChart to the geocoordinate, done like this in AM4:

https://www.amcharts.com/docs/v4/tutorials/retrieving-latitude-longitude-of-map-click/

However, I can't find the right approach as there's no `svgPointToGeo()` method in AM5.

I had thought it might be the `toGlobal()` method but it seems not.

I'm sure it's trivial but I'd appreciate a tip please.

Thanks
Matt

**Comment by martynasma** [comment]
Hi Matt,

For some reason we had `MapChart` methods for converting screen coordinates to lat/long and back hidden in class reference.

They're now visible.

This is what you need:

```JavaScript
chart.events.on("click", function(ev) {
  console.log(chart.invert(ev.point))
});
```

https://www.amcharts.com/docs/v5/charts/map-chart/map-api/#Converting_between_X_Y_and_lat_long_coordinates

**Comment by olneyMatt** [comment]
Fabulous - thanks so much.

You guys are so responsive, it's great!
