### ISSUE TITLE
Drawing lines break when scroll

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1300]
I have drawn some Horizontal Lines in my Candlestick Charts. And when I scroll/Zoom-in or Zoom-out the Lines break and again join.

Though it doesn't cause any issue, but it doesn't look good to view. Breaking lines while Zoom-in or Zoom-out is not a good UI isn't it?

Zoom-in or Zoom-out is very smooth & lag free but the drawings break & again join in between.

Demo:

https://github.com/amcharts/amcharts5/assets/137867461/d09d4292-2348-4844-b997-e9088b54a452

**Comment by martynasma** [comment]
I'm afraid it's not super clear what is "breaking" from the video.

Would you be able to post this chart as a CodePen so that we can live-test?

**Comment by workingbuddy10** [comment]
Sure,

In the below code link, you can see the dotted lines break with the main line on zooming.

https://codepen.io/team/amcharts/pen/vYarpYN


https://github.com/amcharts/amcharts5/assets/137867461/c1f48050-f0ef-4efb-9683-22d0cfd45e99


@martynasma
