### ISSUE TITLE
Get date grouped data points on column click

### ISSUE THREAD

**Issue by SDVII** [amcharts/amcharts5#1304]
**Question**

Is there a way to retrieve the set of grouped points on column click?

I have an XY Chart (a bar variant) which am using with group intervals and I've added an event in order to catch column clicks. However, I'd like to be able to know what are the data points that where grouped to compose that bar. Is there a way to do so?

This is what I got so far:
https://codepen.io/Houmam-Hatahet/pen/WNmdyvZ

**Environment (if applicable)**

 - amCharts: latest (via CDN)
 - Edge:  v121.0.2277.83

**Comment by martynasma** [comment]
You can set `groupDataWithOriginals: true` on your series.

When you do so, the data items for the series will have "originals" set in them, e.g. `dataItem.get("originals")` which will contain a list of original data items that comprised grouped data item.

**Comment by SDVII** [comment]
Thanks! Worked as expected. I've updated the CodePen in case anyone is curious about the final results
