### ISSUE TITLE
Problem synchronizing ValueAxis

### ISSUE THREAD

**Issue by SeltonJeff** [amcharts/amcharts5#1309]
Hello, firstly congratulations on the library.
I'm developing a project using it for a real-time trading system, using stockChart.
I came across the following problem:
I have custom events that are added to the chart as custom bullets, I needed to add a new Y axis so that these bullets do not break the autoZoom scale.
To synchronize, I tried some alternatives from the doc such as syncAxisWith, but I didn't have good results. The best way I found was the following:

```
const eventsAxisConfig = am5xy.ValueAxis.new(root, {
       strictMinMax: true,
       ...
}

const eventsValueAxis = mainPanel.yAxes.push(eventsAxisConfig);

root.events.on("framestarted", function () {
        if (valueAxis && eventsValueAxis) {
          const min = valueAxis.getPrivate("selectionMin");
          const max = valueAxis.getPrivate("selectionMax");

          eventsValueAxis.set("min", min);
          eventsValueAxis.set("max", max);
          eventsValueAxis.setPrivate("selectionMin", min);
          eventsValueAxis.setPrivate("selectionMax", max);
        }
}
```

However, this still leaves me with one point:
the function ```valueAxis.getPrivate("selectionMin")``` and ```valueAxis.getPrivate("selectionMax")``` return a Number, and javascript has its old habit of rounding values, in my case:
when I have a value ex: ```1.085432```
It returns something like ```1.0854```, intermittently, is there any way to get this value in a string? so that you can set the real value without rounding or any way to make this more efficient?

```Chrome latest, vuejs, typescypt```

**Comment by martynasma** [comment]
I don't think there's any way to return `selectionMin` as a string.

That said, I'm not entirely sure I understand why you need additional axis for bullets.

Perhaps you can post your chart on CodePen so that we understand your setup, and possibly offer an alternative?

**Comment by SeltonJeff** [comment]
I resolved this issue by setting interpolationDuration of valueAxis to 0 before appending new data and resetting it to the default value afterwards!

**Comment by SeltonJeff** [comment]
I resolved this issue by setting interpolationDuration of valueAxis to 0 before appending new data and resetting it to the default value afterwards!
