### ISSUE TITLE
Can a tooltip be displayed on empty data points in Line Series?

### ISSUE THREAD

**Issue by suu3** [amcharts/amcharts5#1312]
**Question**
https://codepen.io/team/amcharts/pen/gOWWZzd
In this chart, Can a tooltip be displayed on empty data points?
I want to display a tooltip saying "No data available" on empty data points. Is this possible?

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
There's no way to add a tooltip where nothing exists.

That said, if there is no obvious gap in series, isn't it obvious that there's no data?

**Comment by suu3** [comment]
Thank you for your response.

Then, if I set 'connect' property of the LineSeries to true, is it also impossible to display tooltips?
(like this situation - https://codepen.io/suu3/pen/GReGXoM , x-value is null and connect is true.)
Since we know the x-axis position, could it be possible to display tooltips even in cases where the value in the data is null?

**Comment by martynasma** [comment]
No. The tooltip can display in two situations:

1) If there's something to hover on, like a bullet.
2) If you use an `XYCursor` which snaps to data items automatically.

In neither of those situations there are bullets or data items to snap or hover to.

**Comment by suu3** [comment]
Ok, thanks. I'll close this issue :)
