### ISSUE TITLE
Value Axis - Is there a way to only move the position of first and last Y Axis labels meanwhile maintain the position of other labels of same Y axis 

### ISSUE THREAD

**Issue by raylin6666666** [amcharts/amcharts5#1313]
**Question**
Hi, I am new to amcharts5 and while learning Vertical Stacked Axes Chart using this [Demo](https://www.amcharts.com/demos/vertically-stacked-axes-chart/), I tried to remove the marginTop in this` function createSeries(field, margin, column) {`, it looks like marginTop is used to control the gaps between each chart, however there are labels overlapping(see the screenshot below). 
my question is after setting the marginTop to 0, [labels are overlapped](https://codepen.io/Ray-Lin/pen/xxBzqjq), is there a way to adjust the position of overlapped labels and maintain the position of other labels? What I am thinking here is if it is viable to move position of last label of each Y axis a little up and first label a little down. 

<img width="786" alt="Screenshot 2024-02-05 at 13 18 59" src="https://github.com/amcharts/amcharts5/assets/143089152/cb7aa7e7-ea9e-4588-aba7-3ebaef9cc5c5">

**Environment (if applicable)**
amCharts version : 5.5.6
Browser: Latest Chrome
React: 17.0.2

**Additional context**

**Comment by martynasma** [comment]
Technically, you could adjust position of each individual label using adapters, based on label's position within axis:

```JavaScript
yAxis.get("renderer").labels.template.adapters.add("dy", function(fy, target) {
  var axis = target.dataItem.component;
  var position = axis.valueToPosition(target.dataItem.get("value"));
  if (position >= 1) return 10;
  if (position <= 0) return -10;
  return 0;
});
```

But that looks a bit odd 🤔

![image](https://github.com/amcharts/amcharts5/assets/1458520/f7173419-ca81-40e3-9d1d-b440d627c103)


Why not just hide the first label of all but the bottom axis?

```JavaScript
yAxis.get("renderer").labels.template.setAll({
  minPosition: 0.01
});
```

Looks better IMO:
![image](https://github.com/amcharts/amcharts5/assets/1458520/bd479347-33cc-4b01-88e1-2dddf056e650)


Docs: https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#start-end-labels-and-ticks

**Comment by raylin6666666** [comment]
Thanks for Sharing these useful information! Per my experience from user experience perspective, it might be hard to distinguish each chart when removing the last and first label. Anyway, I will dive deep to take a look at ur comment and code and Lmk if you have any feedbacks on my thought.
