### ISSUE TITLE
Sankey Chart Fails to Apply Custom State

### ISSUE THREAD

**Issue by btbritz** [amcharts/amcharts5#1314]
Can't get custom states to work when I have the following Sankey chart setup:

```
import * as am5 from '@amcharts/amcharts5'
import * as am5flow from '@amcharts/amcharts5/flow'

let root = am5.Root.new('amChart')
root.addDisposer(
    am5.utils.addEventListener(root.dom, "contextmenu", function(ev) {
        ev.preventDefault();
    })
);

let series = root.container.children.push(
    am5flow.Sankey.new(root, {
        sourceIdField: 'from',
        targetIdField: 'to',
        valueField: 'value',
    })
)

series.nodes.states.create('selected', {
    fill: am5.color(0xff0000),
});

series.nodes.events.on('rightclick', function(ev) {
        let node = ev.target;
        node.states.apply('selected');
});

series.data.setAll([
    { from: "A", to: "B", value: 10 },
    { from: "B", to: "C", value: 8 },
    { from: "C", to: "D", value: 4 },
    { from: "C", to: "E", value: 3 }
])
```

Tried to dumb down the above example as I'm hoping my question is just me being silly.

Not sure what I'm doing wrong but I've tried this custom state approach with several of the Sankey codepen's (for example, on the docs page: https://www.amcharts.com/docs/v5/charts/flow-charts/sankey-diagram/#Nodes) with no luck either.

Notice that I am `preventDefault()`ing the right-click on root in order to get into the `rightclick` event. The rightclick function is being successfully fired and looking at my logs, the newly created state is part of the `states` object on the node...but visually nothing changes on right-click. As in, the new fill isn't there.

Any help is much appriciated.

**Comment by zeroin** [comment]
Here is how it should be:

```
let root = am5.Root.new('amChart')
root.addDisposer(
    am5.utils.addEventListener(root.dom, "contextmenu", function(ev) {
        ev.preventDefault();
    })
);

let series = root.container.children.push(
    am5flow.Sankey.new(root, {
        sourceIdField: 'from',
        targetIdField: 'to',
        valueField: 'value',
    })
)

series.nodes.rectangles.template.states.create('selected', {
    fill: am5.color(0xff0000),
});

series.nodes.rectangles.template.events.on('rightclick', function(ev) {
        let rectangle = ev.target;
        rectangle.states.apply('selected');
});

series.data.setAll([
    { from: "A", to: "B", value: 10 },
    { from: "B", to: "C", value: 8 },
    { from: "C", to: "D", value: 4 },
    { from: "C", to: "E", value: 3 }
])
```

series.nodes in Sankey is not a list of nodes, it's another Series - `SankeyNodes`:
https://www.amcharts.com/docs/v5/reference/sankeynodes/

And then it has a rectangles, which is a `ListTemplate`. You have to add events and state to the `rectangles.template`

**Comment by btbritz** [comment]
Ahhh I see, I wondered about that since I'm editing the rectangles `cornerRadius` in another section.

Worked like a charm, thanks @zeroin !

**Comment by btbritz** [comment]
@zeroin or maybe @martynasma I'm hoping you can help me with a followup question to this.

If I wanted to apply the newly created `selected` to all "children" of a node how would I go about doing that? Just using your answer as a code reference.

**Comment by btbritz** [comment]
Figured it out. For anyone interested I included the following to the above example:

```
am5.array.each(series.dataItems, function (dataItem) {
    let targetRectangle = series.nodes.rectangles.values.find(shape => shape.dataItem.dataContext.name === dataItem.dataContext.to) 
    targetRectangle.states.apply('selected')
})
```
