### ISSUE TITLE
How to get the max value from valueAxis

### ISSUE THREAD

**Issue by jiwonmik** [amcharts/amcharts5#1316]
**Question**

I have more than one `LineSeries` and above them, I want to color differently only the one `LineSeries` that have max value.
I found that `_maxReal` has the max value of `ValueAxis`, but `ValueAxis` doesn't have the property to get it.
Is it impossible to get only the `LineSeries` that have the max value?

For example, from this [CodeSandbox](https://codepen.io/pen?&prefill_data_id=864ba55c-a40f-4d11-9d33-9fb2156cf867) code, `Series2` is the line that has the max value. So I want to color only `Series2` to a specific color. 

I think the data changes, so I'll attach the image.
**From below image,  I want to color only `Series8` to a specific color.** 
<img width="1433" alt="image" src="https://github.com/amcharts/amcharts5/assets/59993029/ef6a7507-a2c1-4bb2-90a9-0fbc60b6543e">

 
**Environment (if applicable)**

- amCharts version: 5
- Related frameworks: Typescript

**Additional context**

**Comment by zeroin** [comment]
Hi,

Here is an example:
https://codepen.io/team/amcharts/pen/OJqEdme

What was done here:

`calculateAggregates: true` set for all series - this makes series to calculate it's highest value.

Check highest value when data is validated:
```
  series.events.on("datavalidated", function(){
    checkMax()
  });
```

The method which checks value (highest value can be get using `series.getPrivate("valueYHigh")`):

```
function checkMax() {
  var max = -Infinity;
  var maxSeries;

  chart.series.each(function (series) {
    var high = series.getPrivate("valueYHigh", -Infinity);
    console.log(high)
    if (high > max) {
      maxSeries = series;
      max = high
    }

    series.setAll({
      stroke: am5.color(0xdddddd),
      fill: am5.color(0xdddddd)
    })
  })

  if (maxSeries) {
    maxSeries.setAll({
      stroke: am5.color(0xff0000),
      fill: am5.color(0xff0000)
    })
  }
}
```

**Comment by jiwonmik** [comment]
Thank you so much! This is the exact one that I needed.

I have one more question - I want to use the color set above as in the tooltip. 

```js
        series.events.on('datavalidated', function () {
          checkMax({ chart, colors });
        });
        
        series.strokes.template.setAll({
          strokeWidth: 1.5,
        });

         // this color is different from set above in checkMax
        chart.series.each(function (series) {
          console.log('what is this here: ', series.get('stroke'));
        });
        // this color is different from set above in checkMax as well
        const color = series.get('fill').toString();

        const tooltip = getTooltip({ root, chart, series, legendCategory });
        series.set('tooltip', tooltip);
````

And `getTooltip` function is like below.

```js
export const getTooltip = ({ root, chart, series, legaendCategory }: LineChartType & { legendCategory: string }) => {
  // this color is different from set above in checkMax
  const color = series.get('fill').toString();

   // ... some settings here

  return tooltip;
};
```

But the color by `series.get('fill').toString()` returns all different random colors.. 
The correct result should be like below.

1. Color for line that has highest value
2. All other colors should be `0xdddddd`

How can I get the color set from `checkMax` function?

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.
