### ISSUE TITLE
Wrong date in the calendar

### ISSUE THREAD

**Issue by ivannrs** [amcharts/amcharts5#1318]
Thank you for your last release which fixed a lot of points, here is something we have just found in the new version and it might be considered as a follow of this ticket: 
https://github.com/amcharts/amcharts5/issues/1292

### Issue
On selecting dates via the predefined buttons or the calendar (zoomToDates) amCharts 5 is shows wrong periods and even adjust them.

**The calendar is showing dates out of the selected period and always extend the end date by 1 day**

1. Open my code pen https://codepen.io/kris-a/pen/qBvxdLO
2. Select these 2 dates: 2002-06-14 - 2002-12-14
Now the calendar is auto adjusted to show an end date 2002-12-16 which is wrong and different than what the charts shows. In my opinion the charts shows the correct series and period in this case, but the calendar is somehow wrongly set. 
And to see it even more obvious you can now select 2002-12-10 as end date, the calendar will show 11th, then just open the calendar, do not change any dates and just press apply - the dates will change again and again.
What's even more strange, if you force it to show 2002-12-12, it will show you 13th, but if you open the calendar again and force 2002-12-12 again as a date, it will successfully show you 12th. I assume this is because it does count this as a change and do not trigger any event. This should be definitely in the communication between the calendar and the chart.

_btw we are building our own calendar that looks like the one in v3, if you already have some tutorial or API guideline about this we would appreciate it_

**Environment**
- amCharts version: check the HTML tab
- Browser and its version: Edge and Chrome
- Licensed version (the demo is of course not)

**Comment by martynasma** [comment]
OK, so you are using `GaplessDateAxis`. There is no data on 2002-12-14, so it grabs the next available date, which is 2002-12-16 and zooms to 2002-12-16 00:00:00.

Because it is selected to the beginning of the day, we can't see 16th data item, but the axis considers selection to be applied to 16th, hence the date in the `DateRanegSelector`.

I would not consider it a bug.

**Comment by ivannrs** [comment]
Hey @martynasma ,
Thanks for your reply. I understand the logic you have described, can this be adjusted via some settings ?
Most of the stock charts are showing prices and I would expect if there is no price on 14th, the previous price to be displayed as a last price (at this point we still do not know the next price). And this is exactly how the chart's line works - it shows 13th, its just the calendar that shows 16th. Even if you now force it again to show 14th in the calendar it will stick to 14th.

_What's also confusing (the same case) is when you select a date which has an item/price on it._ 
Please select 2002-12-10 in the calendar and press Apply, you will see 2002-12-11, even though we have a price on 10th. 
Then open the calendar again and do not change the dates, just press Apply, you will see that it moves the dates again with one day, it will do it again and again if you continue open the calendar and pressing Apply.

**Comment by martynasma** [comment]
We've just released 5.8.2 which should fix this other issue you just mentioned.

**Comment by ivannrs** [comment]
Wow @martynasma , that was really fast. 
Thanks a lot for the fix, I would consider it as fixed. 
Only one small feedback from us related to this ticket which is really minor. The selection works perfectly fine if you select end date which has price on it (ex.: 2002-12-10, 2002-12-11) but if you select a date that has no price, or the next date has no price - it will move a bit the selection. In our example this happens if you select Friday 13th, Saturday 14th, or Sunday 15th - it will always send you to 15th for I don't know what reason since 15th also do not have price, its just 13th that has one from those 3 dates.

**Comment by martynasma** [comment]
It happens because the axis selects until 16th - the first day that has data item, like in my first explanation.

However, with the last change, we remove 1 second from the selection, hence it becomes 15th instead.

I'm afraid we won't be able to change this behavior, as per above reasons.
