### ISSUE TITLE
Exclamation mark in numberFormat

### ISSUE THREAD

**Issue by quadh** [amcharts/amcharts5#1321]
- amCharts version 5.7.7
 - Browser and its version: Chrome/Edge
 - Related frameworks and their versions: TypeScript / Web Component

May I check on the correct numberFormat I should be passing in if I want to use the exclamation mark? Specifically, where do I place the exclamation mark in the configuration?

As explained on https://www.amcharts.com/docs/v5/concepts/formatters/formatting-numbers/
![image](https://github.com/amcharts/amcharts5/assets/11628742/9bafa7ab-dedf-40bf-8e51-2744a3f59d61)

What I want to do is to "force" amcharts to display the axis labels with a certain suffix e.g. "M" in millions, and also convert the numeric portion to reflect that accordingly e.g. 500,000 would become 0.5 M.

My current configuration for numberFormat:

{ numberFormat: "#!a",
bigNumberPrefixes: [
            { number: 1e3, suffix: "M" },
            { number: 1e4, suffix: "M" },
            { number: 1e5, suffix: "M" },
            { number: 1e6, suffix: "M" },
            { number: 1e9, suffix: "M" },
            { number: 1e12, suffix: "M" },
          ],
}

You can see that I am attempting to force the various big numbers to display suffix in 'M', but this does not work. The numeric portions of the axis labels do not convert themselves automatically to follow the desired suffix.

**Comment by martynasma** [comment]
> What I want to do is to "force" amcharts to display the axis labels with a certain suffix e.g. "M" 

For that, you just need to remove all other `bigNumberPrefixes`:

```JavaScript
root.numberFormatter.setAll({
  numberFormat: "#a!",
  bigNumberPrefixes: [
    { number: 1e6, suffix: "M" }
  ]
});
```

The "!" modifier works by applying "M" suffix/calculation on numbers that are lower than 1M.
