### ISSUE TITLE
How limit extra max to a specific number in px?

### ISSUE THREAD

**Issue by lucasalmeida92** [amcharts/amcharts5#1322]
I can't find on documentation how to limit the right "padding" of the chart to a specific width in pixels independent of the current zoom.

`extraMax` works fine for the initial state of the chart, but if I zoom in the series can even disappear in the current range:
**Initial state:**
![image](https://github.com/amcharts/amcharts5/assets/5767871/017a116e-db4a-4b87-bb86-93eb12bd834e)
**After zooming in and panning to right:**
![image](https://github.com/amcharts/amcharts5/assets/5767871/fee9f26e-1fae-4903-bc4c-2ae0c772525a)

Here chart and axis code:
```ts
const mainPanel = stockChart.panels.push(
    am5stock.StockPanel.new(root, {
      panY: false,
      panX: true,
      wheelX: 'panX',
      wheelY: 'zoomX',
      pinchZoomX: true,
      paddingTop: 0,
      paddingRight: 0,
      paddingLeft: 0,
      paddingBottom: 16,
      wheelZoomPositionX: undefined,
    })
  );
```
```ts
const xAxis = chart.xAxes.push(
    am5xy.DateAxis.new(root, {
      baseInterval: { timeUnit: 'second', count: 1 },
      minZoomCount: 60,
      maxZoomCount: 60 * 20,
      extraMax: 0.07,
      strictMinMaxSelection: true,
      renderer: am5xy.AxisRendererX.new(root, {
        strokeOpacity: 0,
      }),
    })
```

**Comment by martynasma** [comment]
I'm afraid there's no such option to extend axis scale by a fixed number of pixels 🙁

**Comment by lucasalmeida92** [comment]
@martynasma  Do you have any idea how could I get this result(or at least almost)?

1) The user is able to pan to the left side as much as he/she wants;
2) The user is able to pan to the right side the maximum of 50% (the series has to be always shown, it cant disappear of the current range).

**Comment by martynasma** [comment]
I suppose you can set `min` and `max` values of the X axis, then monitor `xAxis.onPrivate("minSelection")` (and `maxSelection` accordingly).

Implement fuzzy logic which determines how close current min/max are to your target min/max, then update `xAxis.set("min")` (and `max`) as needed.

I hope that makes sense.
