### ISSUE TITLE
Zooming to data items on a `MapPointSeries` does not work

### ISSUE THREAD

**Issue by F0rce** [amcharts/amcharts5#1323]
The title pretty much explains the problem, but let me explain. 

We have a `MapPointSeries` where we add data items one by one using the `pushDataItem` function. Now we have a route that works perfectly. As a route can only be on a small part of a `MapPolygonSeries`, we decided that if a map has only one `MapPointSeries`, we want to zoom to its data items, because if it is the only route on the map, why bother with the rest of a country/island etc. 

This `zoomToDataItems` utility function, which we just call with the data items of the route (`mapPointSeries.zoomToDataItems(mapPointSeries.dataItems, false)`) will scroll the map to the top left so that our bullets are still visible but nothing of the map is left.

To reproduce this, we can use a codepen from the official documentation site.

1. Please open this official [codepen](https://codepen.io/team/amcharts/pen/eYWMyWv) - [documentation](https://www.amcharts.com/docs/v5/charts/map-chart/map-point-series/#Connecting_line_series_points)
2. Insert the following JS at the bottom `pointSeries.zoomToDataItems(pointSeries.dataItems, true);`
3. See the result, the chart is now completely white.

**Additional context**

If this behaviour is undesirable or there is another way of doing this, please let me know. It just seems like this is exactly the behaviour the function was created for.

Thanks in advance,
David

**Comment by martynasma** [comment]
I suppose if you call `zoomToDataitems()` immediately after creating series, the calculations needed for it might still not be there.

I would delay the call to the end of the frame, e.g.:

```JavaScript
root.events.once("frameended", function() {
  pointSeries.zoomToDataItems(pointSeries.dataItems, true);
});
```

**Comment by F0rce** [comment]
Thank you very much, the `frameend` event worked perfecty fine, didn't knew it existed.
