### ISSUE TITLE
Volume at Price issue when Auto Save is On

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1325]
There is a issue in Volume at Price when Auto Save is On.

When I have enabled the Auto save from Data Save Control toolbar, and user clicked on Volume at price in that they have opted for ticks per row and give the value as 1 or any value which takes time to calculate.

Whole chart freezes. As there is a heavy calculation I can understand that.

But due to Auto save, I am totally freeze, my whole app is stuck even though I re-open the app then too it doesn't fixes.

Steps to reproduce : 
Link : https://www.amcharts.com/demos/stock-chart/

- Enable the auto save
- Enable the Volume at price & give ticks per row as value 1.
- Then try to access the chart, even after closing the browser and re-opening the tab doesn't work & I am not able to remove the indicator.

**Comment by martynasma** [comment]
We're looking into this.

In the interim you can unstuck your app by going into console and entering this:

```
localStorage.clear();
```

**Comment by martynasma** [comment]
This is not exactly a bug. But we will consider adding some kind of dynamically-calculated reasonable minimum for ticks per row value.

**Comment by martynasma** [comment]
Implemented in [5.8.1](https://github.com/amcharts/amcharts5/releases/tag/5.8.1).

## [5.8.1] - 2024-02-14

### Changed
- `VolumeProfile` indicator will now not let select an unreasonably small value for its "ticks per row" setting.

### Fixed
- Using `DrawingControl` in standalone mode was resulting in error when trying to enable drawing tool from API.
- Volume profile indicator was taking one extra date which was out of selection in some cases.
- If `snapToSeries` was set on `XYCursor`, `tooltipDataItem` was set one extra time with incorrect value on `XYSeries`.
- `XYSeries` was not updating legend if `legendRangeValueText` text was set on series and range was changed from outside without animated theme enabled.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
