### ISSUE TITLE
Date formats are not applied to some groups values

### ISSUE THREAD

**Issue by SDVII** [amcharts/amcharts5#1328]
**Bug description**

* **Repo:** https://codepen.io/Houmam-Hatahet/pen/eYXPaRO
* **Description:** `dateFormats` overrides doesn't seem to apply to all values if grouping is applied. In the CodePen above, I've applied  a weekly group interval and changed the date formats for both weeks and days to "MM/dd". Yet, the formatting doesn't seem to apply to all labels. The issue only appears upon grouping.

**Environment (if applicable)**

 * amCharts v3.8.0
 * Edge v121.0.2277.112

**Additional context**

A screenshot of the issue
![image](https://github.com/amcharts/amcharts5/assets/10416702/0a4ddfbf-b93d-4f9f-a642-464d52388e24)

**Comment by martynasma** [comment]
Please refer to this tutorial:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#period-change-date-formats

**Comment by SDVII** [comment]
Apologies, must've missed it. Thank you for your response
