### ISSUE TITLE
zoomToDates causing unexpected date offset

### ISSUE THREAD

**Issue by dnewkerk** [amcharts/amcharts5#133]
Hi, thank you again for the great library!

I'm trying to zoom the stock chart example to a date range of the last 1 year of data by default. 

I forked the [Stock Chart demo](https://www.amcharts.com/demos/stock-chart/) and only added some code at the bottom of the JavaScript editor pane:
https://jsfiddle.net/8ph5caj7/

Here's the zoomToDates code I added:

```
// Zoom in to the last 1 year by default.
volumeSeries.events.once('datavalidated', (ev) => {
  // Get the last date in the dataset.
  const lastDate = new Date(data.at(-1).date);

  // Create a date for one year back from lastDate.
  const newDate = new Date(lastDate);
  const oneYearBack = new Date(newDate.setFullYear(newDate.getFullYear() - 1));

  // Zoom in to show the last 1 year of data.
  ev.target.get('xAxis').zoomToDates(oneYearBack, lastDate);
});
```

The zoom is successfully applied after the chart loads. What seems to be happening though is when the chart is zoomed in with zoomToDates, it leaves a buffer of days at the end, so it is not actually encompassing the last dates at the end of the data set. If you grab the right handle on the mini chart and drag right, it reveals the rest of the dates. If you hover to bring up the tooltips before and after, you can confirm that the last date shown changes. This only appears to happen with zoomToDates... when you view the unmodified stock chart demo, all of the dates are displayed.

Using a different example, I believe I confirmed that it is offsetting the zoomed in date range back by around a week. With the below example, even though the dates are set to January 1, the chart shows a start of December 24, and end of December 21:

https://jsfiddle.net/xoshdpyf/

```
// Zoom to a specific 1 year range.
volumeSeries.events.once('datavalidated', (ev) => {
  const dateA = new Date(new Date('2015-01-01:00:00:00'));
  const dateB = new Date(new Date('2016-01-01:00:00:00'));
  ev.target.get('xAxis').zoomToDates(dateA, dateB);
});
```

Please let me know if any more info is needed to clarify what's happening.

Thanks!

**Comment by zeroin** [comment]
So here is what happens:

Initially, data is grouped to months. In this case date axis spans from the beginning of first month to the end of last month. Your actual last date is not the last day of the month, so when you `zoomToDates`, it converts the actual last date to the position having in mind that the end of the axis is the last day of the month, so the position is no 1. When you zoom, the data grouping changes and it zooms to the position calculated based on the pervious situation. 

I must say I don't know if I can fix that internally. So my suggestion would be to use `axis.zoom` instead of `axis.zoomToDates` in your case, like this:

```
volumeSeries.events.once('datavalidated', (ev) => {
  // Get the last date in the dataset.
  const lastDate = new Date(data.at(-1).date);

  // Create a date for one year back from lastDate.
  const newDate = new Date(lastDate);
  const oneYearBack = new Date(newDate.setFullYear(newDate.getFullYear() - 1));
  const position = dateAxis.valueToPosition(oneYearBack.getTime())
  // Zoom in to show the last 1 year of data.
  ev.target.get('xAxis').zoom(position, 1);
});```

I will think if I can come up with a better solution

**Comment by rahaprogramming** [comment]
The chart zoom seems to work with value from zero to one. zero is the start and 1 is the end. You can directly set the zoom using -

dateAxis.zoom(0.25, .5);//one quarter from start to half of chart
dateAxis.zoom(0, 1);//start to end (default)
dateAxis.zoom(0.5, 1);//halfway point to end

same as:
series.events.once('datavalidated', (ev) => {
      ev.target.get('xAxis').zoom(0.25, 1,);
  });
This is a lot easier to me than parsing a bunch of dates and getting their positions.
