### ISSUE TITLE
Duplicating a Sankey link "To" if found by multiple "From"s

### ISSUE THREAD

**Issue by btbritz** [amcharts/amcharts5#1332]
Seems like the out-of-the-box functionality works like this:

```
let data = [
    { from: A, to: C, value: 1 }
    { from: B, to: C, value: 1 }
]
```
There would be **3 total nodes** created with 2 links spanning from node A to node C, and node B to node C.

Is there a solution to split that same data array into 4 nodes? To summarize, **4 total nodes** created with 2 links spanning from node A to node C and node B to a SEPARATE node C.

Thanks!

**Comment by martynasma** [comment]
You would need to give the two Cs a separate id to make them display as separate.

You can use a separate "node data" to map ids to actual names, which can duplicate.

More details:
https://www.amcharts.com/docs/v5/charts/flow-charts/sankey-diagram/#Node_data

Example:
https://codepen.io/team/amcharts/pen/RwdEryN??editors=0010

**Comment by btbritz** [comment]
Thanks!
