### ISSUE TITLE
How can I set text color as white conditionally?

### ISSUE THREAD

**Issue by jiwonmik** [amcharts/amcharts5#1333]
**Question**

Please see this [Codepen](https://codepen.io/jiwonmik-the-flexboxer/pen/ExMGPMr) example. 
<img width="1439" alt="image" src="https://github.com/amcharts/amcharts5/assets/59993029/f6f9cb24-0b47-41fc-bb82-649c36f6e47b">

It seems like the tooltip text color is automatically set to white when the heat color is darker / set to black when the heat color is lighter.

I want to set each value in each cell, and implement this same logic - to set text color white or black conditionally based on the background color. How can I do it? (As you can see in the above image, all of the text is **black**.)

FYI, this is how I set labels on each cell.
```js
  series.bullets.push(function (root) {
    return am5.Bullet.new(root, {
      locationX: 0.5,
      locationY: 0.5,
      sprite: am5.Label.new(root, {
        text: '{value}',
        centerX: am5.percent(50),
        centerY: am5.percent(50),
        populateText: true,
      }),
    });
  });
```

Also, I want to implement this logic when creating the **custom tooltip using HTML.** 
Seems like setting tooltip with `am5.Tooltip.new(root, {})` automatically do this, but I am customizing the tooltip by creating with HTML. So I set my tooltip like below.

```js
  tooltip.adapters.add('html', function () {
    return getTooltipHtml({ ... });
  });
```

So I have total 2 questions - both asking for same logic though.
1. How to set the text color(label for bullet) white or black based on the background color when setting labels for each bullets to show values.
2. How to set the text color(label for bullet) white or black based on the background color when setting tooltip with custom html tooltip.

I found that each colors are inside the `graphics` for each series.. Using this could be the solution?

**Environment (if applicable)**

- amCharts version: 5
- Related frameworks: Typescript

**Additional context**

**Comment by martynasma** [comment]
> How to set the text color(label for bullet) white or black based on the background color when setting labels for each bullets to show values.

Please refer to this tutorial on how to disable auto-coloring of tooltip text:
https://www.amcharts.com/docs/v5/concepts/common-elements/tooltips/#Text_color

You can then use an adapter for `tooltip.label` "fill" setting to apply custom logic as per your needs.

> How to set the text color(label for bullet) white or black based on the background color when setting tooltip with custom html tooltip.

HTML is completely independent on the coloring applied by a chart.

So you will need to use an adapter for "html" to examine target elements dataItem, determine color from it, and form your HTML accordingly.

**Comment by wjdwl002** [comment]
I'm working on the same project with the author and have a question about this specific condition:
We are using `tooltipHtml` for customized tooltip design.
We provide `max` and `min` colors at heat range and use `calculateAggregates = true` to color the cell background. 
Then, we use `getFillFromSprite = true` for the tooltip to inherit the assigned background color of the cell.
But there's a need to determine if the fill color inherited from the sprite is dark enough to make the text color white. Thought `autoTextColor` would do this but it's not working for some reason.
Any thoughts on this specific case?

```JS
series.columns.template.setAll({
      width: am5.percent(cellWidth),
      height: am5.percent(cellHeight),
      tooltipHTML: getGlobalTooltipHtml({ chart }),
      tooltip: am5.Tooltip.new(root, {
        paddingBottom: 0,
        paddingLeft: 0,
        paddingRight: 0,
        paddingTop: 0,
        getLabelFillFromSprite: true,
        autoTextColor: true, // -> This won't return white text color for dark background
        getFillFromSprite: true, // -> Because of this, the tooltip color is coming from the calculated heatmap color based on provided heat range
        getStrokeFromSprite: true,
      }),
    });


export const getGlobalTooltipHtml = ({
  chart
}) => {
  let html = ``;
  let tooltipDataItem;
  let color;
  chart.series.each(function (series, i) {
    if (i != 0) {
      html += '\n';
    } else {
      let y;
      let x;
      let header = '<span style="font-size: 15px; font-weight: bold">{categoryX}</span> <span>{categoryY}</span>';
      // value for categoryXField: categoryX, value for categoryYField: categoryY

      html += `<div style="min-width: 100px; min-height: 30px; height: fit-content; overflow-y: hidden; display: flex; flex-direction: column; align-items: center; justify-content: center; background-color: ${color}; padding: 10px; gap: 4px">
          ${header}
          </div> <div style="width: 100%; overflow-x: hidden; height: fit-content; padding: 10px; border-radius: 0 0 4px 4px; display: flex; flex-direction: column; align-items: center; gap: 5px; justify-content: space-between; background-color: #ffffff">`;
    }

    let name;
    let value = `{value}`;
    if (!value) return;
    html += `<div style="display: flex; justify-content: space-between; width: 100%; gap: 5px;">
      <div style="max-width: 140px; text-wrap: nowrap; font-weight: bold">
        ${
          color ? `<span style="color: ${series.get('stroke').toString()}"> ● </span> ` : ''
        } <span style="white-space: pre-wrap; overflow-wrap: break-word; flex: 1">${name || _name}</span></div>
        <span style="flex: 1; text-align: right">${value}</span>
        </div>`;
  });
  html += '</div>';
  return '<div style="width: 100%">' + html + '<div>';
};
```
<img width="491" alt="Screenshot 2024-02-16 at 4 18 25 PM" src="https://github.com/amcharts/amcharts5/assets/72961728/f1ac70d0-47b7-4d80-afd7-bde640c10a77">

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by jiwonmik** [comment]
<img width="749" alt="image" src="https://github.com/amcharts/amcharts5/assets/59993029/b80b158e-58fb-4974-83c4-d391c197967e">


I set color like above, using custom function and set color to 'sprite'. And when I get the color with below code, it gives me differenet color.

```js
color = series.columns.template._settings.fill
```

**Comment by jiwonmik** [comment]
<img width="820" alt="image" src="https://github.com/amcharts/amcharts5/assets/59993029/8b6f6b5a-b100-423c-8b93-03c0ceaff66c">

I set the heatmap color like above, using custom function and set "Sprite"'s color. 

The thing I want to do is to get this above set color for each from the series, to set the bullet text color based on this color.

```js
  series.bullets.push(function (root, series, dataItem) {
    return (
      dataItem._settings.value > 0 &&
      am5.Bullet.new(root, {
        locationX: 0.5,
        locationY: 0.5,
        sprite: am5.Label.new(root, {
          text: "{value.formatNumber('#.#a')}",
          centerX: am5.percent(50),
          centerY: am5.percent(50),
          populateText: true,
          // fill: (get the color that has been set through above custom function and do something to generate a new color)
        }),
      })
    );
  });
```
Above is how I wrote to set bullets. How can I get the color when creating bullets?

**Comment by zeroin** [comment]
Column and Bullet share the same data item, so you can get the column from it:

`dataItem.get("graphics")` is a column. And then you can get fill from it. However I am not sure if the fill will be set at the moment a bullet is created, if not, then you might need to add adapter for the label's fill, which again would get the fill from the column.

**Comment by jiwonmik** [comment]
Hmm.. I get `undefined` with `dataItem.get("graphics")` ,, 
Below is what I get with `console.log(dataItem) from above code.
<img width="1026" alt="image" src="https://github.com/amcharts/amcharts5/assets/59993029/1b6ffba0-17ad-4365-a387-79e53f7701a1">

**Comment by zeroin** [comment]
Indeed, the graphics is not yet created when you try to access it. So I would try with adapters and would check if the graphics is there already.

**Comment by jiwonmik** [comment]
```js
series.bullets.push(function (root, series, dataItem) {
    const label = am5.Label.new(root, {
      text: "{value.formatNumber('#.#a')}",
      centerX: am5.percent(50),
      centerY: am5.percent(50),
      populateText: true,
    });

    const bullet = am5.Bullet.new(root, {
      locationX: 0.5,
      locationY: 0.5,
      sprite: label,
    });

    return dataItem.dataContext[valueField.field] > 0 && bullet;
  });
```

So where can I use `adapter`?
I tried to change above code to use `adapter` but can't figure out.

**Comment by jiwonmik** [comment]
I figured it out.

```js
label.adapters.add('fill', (_, target) => {
      const color = dataItem.get('graphics').get('fill').toString();
      const fontColor = setFontColorBasedOnBackground(hexToRgb(color)).toString();
      
      return am5.color(fontColor);
    });
```

Thank you so much
