### ISSUE TITLE
Changing the colors in the scrollbar series

### ISSUE THREAD

**Issue by martin-konstantinov** [amcharts/amcharts5#1335]
**Question**

I am trying to change the colors in the scrollbar series, but I cannot seem to find a way to do it. 

Currently, I set the stroke and fill color in the scrollbarSeries object on lines 1099/1100 and later I set the background fill to be a specific gray color. However, I am looking to set the color of the unselected part of the scrollbar, both the color of the stroke/fill and the background color. I have looked in the documentation but I couldn't find a way to do it. Also, there seems to be an animation upon hovering over the selected part of the chart which I'd like to remove. I tried setting "animationEasing", "animationDuration", "stateAnimationDuration" and "stateAnimationEasing" to 0, but to no avail.

Codepen: https://codepen.io/martinsoft/pen/VwRqJQQ 

Here is what I am trying to achieve, color wise.

![image](https://github.com/amcharts/amcharts5/assets/160145904/7cddde19-3746-4d30-95f3-32aa772402d6)

Thanks!

**Comment by martynasma** [comment]
I'm afraid there's no way to apply different coloring to the selected fragment of the preview series.

You can only control `scrollbar.overlay` element which is a semi-transparent square displayed over selected range of the scrollbar.

You can use that object to disable hover animations:

```JavaScript
scrollbarX.overlay.setAll({
  animationDuration: 0
});
```
