### ISSUE TITLE
Is there a way to dynamically change date axis label baseInterval from 'day' to 'hour' after zooming in the chart at a certain zoom level? 

### ISSUE THREAD

**Issue by raylin6666666** [amcharts/amcharts5#1336]
**Question**
I am thinking if there is a way to dynamically change the date axis label baseInterval timeUnit from 'day' to 'hour' after zooming in. 

Use this [demo](https://codepen.io/pen) as example, when zooming at a certain level in the below screenshot, is that possible to make the date axis showing labels in 'hour' timeUnit, like Oct22 4:00, 8:00, 12:00 .etc instead of Oct22 Oct23 Oct24 only(check another screenshot)? and then display the data accordingly.  
<img width="1705" alt="Screenshot 2024-02-15 at 17 04 44" src="https://github.com/amcharts/amcharts5/assets/143089152/a496b254-1f39-4873-9510-b0554ef042d5">

<img width="1575" alt="Screenshot 2024-02-15 at 17 18 26" src="https://github.com/amcharts/amcharts5/assets/143089152/cc2a8cab-50f1-4d78-832a-e22af51b0236">

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
`baseInterval` is a hint about your data granularity, not a setting about grid density.

You should never change it dynamically, unless you are changing data accordingly as well.

As for the grid, you can modify settings that deal with grid granularity, like `minGridDistance` and `gridIntervals`:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#customizing-grid-granularity
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#grid-density
