### ISSUE TITLE
Customizing Map Polygon Background and Cursor Event for Regions with URL Data

### ISSUE THREAD

**Issue by abhay-jain03** [amcharts/amcharts5#1337]
I've shared a snippet of my code for a Map Polygon, which displays a world map with country-wise details. I referred to the following URL for using this code: https://www.amcharts.com/docs/v5/charts/map-chart/map-polygon-series/.

Main Task:

I want to customize the mapPolygon for regions where the URL is not present according to my dataset, as shown below. In the JSON below, there are two markets: India & Russia. The India object has a **URL key** that redirects to a particular page, but the Russia object does not have a URL key.

**I aim to implement changes in cursor behavior and background color of mapPolygons based on country regions while hovering.**

When I **hover** over the India region, which has a **URL present in the JSON**, the **background color** of the India region should change to "#3B3B3B" and the **cursor become "pointer" type**. On the other hand, when I hover over the Russia region in the map polygon, the background color should remain the same blue color and **cursor become not-allowed**, as shown in the screenshot, because the Russia object doesn't have a URL key in the data JSON.

```JavaScript

let data = {
  "temp": [
    {
      "id": "IN",
      "name": "India",
      "url": "https://.........."
    },
    {
      "id": "RS",
      "name": "Russia"
    }
  ]
}

am5.ready(function () {

    // Create root element
    var root = am5.Root.new("mapdiv");

    // Set themes
    root.setThemes([
        am5themes_Animated.new(root)
    ]);

    // Create the map chart
    var chart = root.container.children.push(am5map.MapChart.new(root, {
        panX: "translateX",
        panY: "translateY",
        projection: am5map.geoMercator()
    }));

    // Create main polygon series for countries
    var polygonSeries = chart.series.push(am5map.MapPolygonSeries.new(root, {
        geoJSON: am5geodata_worldLow,
        exclude: ["AQ"]
    }));

    var x = data["temp"];

    polygonSeries.mapPolygons.template.setAll({
        tooltipText: "[bold]{name}",
        toggleKey: "active",
        fill: am5.color(0x949494),
        interactive: true,
        templateField: "polygonSettings"
    });

    polygonSeries.mapPolygons.template.states.create("hover", {
        fill: am5.color(0x3B3B3B)
    });

    //Clickable map
    polygonSeries.mapPolygons.template.events.on("click", function (ev) {
        if (ev.target.dataItem.dataContext.url == undefined) {
            return;
        } else {
            window.location.href = ev.target.dataItem.dataContext.url;
        }
    });

    //Set data
    polygonSeries.data.setAll(x);
})

```

![image](https://github.com/amcharts/amcharts5/assets/37473241/2aff378f-cddc-467a-b102-d002ed535a0a)

Let me know if you need further assistance with this!

@martynasma  Can you help me in this above ?

**Comment by martynasma** [comment]
I suppose you can iterate through all of the polygon data items once it is created and update their hover and cursor settings based on their data:

```JavaScript
polygonSeries.events.on("datavalidated", function() {
  am5.array.each(polygonSeries.dataItems, function(dataItem) {
    if (dataItem.dataContext.url !== undefined) {
      dataItem.get("mapPolygon").setAll({
        cursorOverStyle: "pointer"
      });
      dataItem.get("mapPolygon").states.create("hover", {
        fill: am5.color(0x677935)
      });
    }
  });
});
```

https://codepen.io/team/amcharts/pen/OJqdgWE/cb5f61c053412d7a7dcfd118eb56920a?editors=0010

**Comment by abhay-jain03** [comment]
@martynasma  The above solution works for me, but there is one more concern. The body HTML tag has cursor: default !important set, which means the suggested solution doesn't overwrite the cursor property. Please suggest how to overwrite the cursor property with the above solution, while keeping the body tag's cursor as default !important.

**Comment by martynasma** [comment]
I'm not entirely sure what to suggest. Setting `cursor: default !important` on a body seems like a bad idea 🙁

**Comment by abhay-jain03** [comment]
@martynasma  Could you please provide some solutions and workarounds that help achieve the desired result without impacting the default CSS properties, or alternatively, how we can approach the solution?

**Comment by martynasma** [comment]
There's no such setting.

Maybe you can add hover events on polygons and temporarily reset global pointer CSS, e.g.:

```JavaScript
polygonSeries.mapPolygons.template.events.on("pointerover", function() {
  document.body.style.cursor = "default";
});

polygonSeries.mapPolygons.template.events.on("pointerout", function() {
  document.body.style.cursor = "default!important";
});
```
