### ISSUE TITLE
Bubble chart does not render proper size of a bubble using heat rule

### ISSUE THREAD

**Issue by juliadabrowka** [amcharts/amcharts5#1338]
I try to create a bubble chart with a legend. Everything works fine except the heating rule. The radius value is correctly implemented and it is also showns in a tooltip but the chart representation doesnt implement it. All the bubbles are the same size which value is taken from heat rule (max value).

this is how it looks like right now:
https://jsfiddle.net/5k8b1ox9/29/

but the bubbles sizes should look like here:
https://jsfiddle.net/e79d3q5u/24/

it's amCharts version 5
Bubble Chart
Chrome
Angular v.15

**Comment by martynasma** [comment]
The heat rules do not work because you are creating a new series for each individual bubble.

Heat rules work by calculating data item value across all values of the series. If your series has only one value, it will always be minimum and maximum value at the same time.

If you absolutely need to have a setup like that, you can specify `minValue` and `maxValue` for your HeatRule:
https://www.amcharts.com/docs/v5/concepts/settings/heat-rules/#custom-value-range

**Comment by juliadabrowka** [comment]
i set it like you said and now all bubbles are small

if i set the series value as all data (as in example 2) then i cant properly set the color of each bubble because it renders each color for all series nad the legend doesnt see each bubble seperate

**Comment by martynasma** [comment]
You can set color for each bubble individually using `templateField`:
https://www.amcharts.com/docs/v5/concepts/common-elements/bullets/#template-fields

**Comment by juliadabrowka** [comment]
yes, now i get all bubbles same color, one beneath the other and clicking in legend "takes off" all at once and the new color of all of them appears

https://jsfiddle.net/e79d3q5u/27/

**Comment by martynasma** [comment]
Just to reiterate what was already discussed. There are two options for you:

1) Keep multiple series, but add only relevant data items to each series data, and also calculate and set `minValue` and `maxValue` for heat rules.

2) Use one series; use `templateField` to apply custom color for each individual bullet.

**Comment by juliadabrowka** [comment]
ok, i understand, so i did some refactors as you suggested -> just one serie and it gets the color for each one. your way didnt work so i added the once event "datavalidated" on serie and then set colors there but the problem is the legend. which on jsfiddle doesnt work at all but on my local machine i can see the cursor changes from default to pointer and if i click on it all bubbles disappear.
https://jsfiddle.net/5k8b1ox9/46/

if i set `legend.data.setAll(series.dataItems)` then i click on each legend item, it gets greyed out and one bubble disappears but i cant see the labels or colors. here is a screenshot from my local machine:
![image](https://github.com/amcharts/amcharts5/assets/76727970/e506ff1c-35ab-4896-b5cb-4eb5ebff2bcf)

**Comment by martynasma** [comment]
You don't need all that. You can use `templateField` to color bubbles from data.

I have modified your fiddle: https://jsfiddle.net/062brfgo/
