### ISSUE TITLE
Customizing scrollbar thumbs doesn't seem to work

### ISSUE THREAD

**Issue by dez1729** [amcharts/amcharts5#134]
let scrollbarX = chart.set('scrollbarX', am5.Scrollbar.new(root, { orientation: 'horizontal' }));
scrollbarX.thumb.get('background').setAll({
  fill: am5.color(0x550000),
  fillOpacity: 0.1,
});

I'm getting the error from typescript:
Argument of type '"background"' is not assignable to parameter of type 'keyof IRoundedRectangleSettings'.ts(2345)

Indeed when I trace this through 
scrollbarX.thumb.get('background')
this is returning undefined

**Comment by martynasma** [comment]
Thumb does not have a `background` setting because it is an instance of `RoundedRectangle` itself.

So this should work:

```JavaScript
let scrollbarX = chart.set('scrollbarX', am5.Scrollbar.new(root, { orientation: 'horizontal' }));
scrollbarX.thumb.setAll({
  fill: am5.color(0x550000),
  fillOpacity: 0.1,
});
```

**Comment by dez1729** [comment]
Thanks, in that case the documentation needs to be updated.

**Comment by martynasma** [comment]
> Thanks, in that case the documentation needs to be updated.

Indeed. Thanks for the heads up!

Fixed the docs.
