### ISSUE TITLE
Get width of xAxis

### ISSUE THREAD

**Issue by canesen7** [amcharts/amcharts5#1340]
Hi. I've a single bar chart like this.

![image](https://github.com/amcharts/amcharts5/assets/67913330/3bcac4f4-d154-4573-8d9c-20cc0c3a4438)

As you can see, it has one xAxis and two series, first is opposite. When the values are different each other, they has different x axis width. And I need to each serie's max width.

![image](https://github.com/amcharts/amcharts5/assets/67913330/770d9aed-b0ef-4842-a843-c6839fd43503)

(I need to each line's width.)

Thanks

**Comment by martynasma** [comment]
Do I understand you correctly that the left part of the X axis should end at -600,000,000?

If so, you would need to set `min` setting to 600000000 on the X axis:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/value-axis/#Restricting_to_exact_min_and_max_values

**Comment by canesen7** [comment]
No, I need to know width between -200 000 000 to 0 and 0 to 600 000 000

**Comment by martynasma** [comment]
I suppose you can do it in a two-step process:

1) Determine axis position of `-200,000,000`, `0`, and `600,000,000` using axis method `valueToPosition()`.
2) Then use axis renderer's method `positionToCoordinate()` to convert it to a screen coordinates, do the math to calculate width of each segment.

Does that make sense?

**Comment by canesen7** [comment]
Yeah, that make sense but I search the easy way to do it bc in every render, this method must run and calculate label's position by label font-size and current bar width.

**Comment by martynasma** [comment]
What's the purpose of calculating those widths? Maybe there's a better approach.

**Comment by canesen7** [comment]
I need these for calculate values on bar labels. 

- If labels fit in bar, must show in bar,
- If labels not fit in bar but fits outer, must show left or right on bar
- If labels not fit in bar and out, labels opacity must be 0

**Comment by martynasma** [comment]
I'm a bit confused. There are no labels on bars in your screenshots. Are you going to have labels on bars as a bullets?

**Comment by canesen7** [comment]
![image](https://github.com/amcharts/amcharts5/assets/67913330/875f2de6-05d9-46cd-be4f-d6a1bf867392)
Yes like this

**Comment by martynasma** [comment]
OK, so you actually need a width of the related bar, not the axis width?
