### ISSUE TITLE
MapChart with clustered points containing data

### ISSUE THREAD

**Issue by pvougny** [amcharts/amcharts5#1341]
**Question**

My chart is `am5map.MapChart` which has two series: `am5map.MapPolygonSeries` and `am5map.ClusteredPointSeries`.

I set data with coordinates and custom data for each point:

```typescript
var data = [
  { latitude: 43.82429, longitude: 5.7895, data: { amount: 2 } },
  { latitude: 43.82429, longitude: 5.7895, data: { amount: 3 } },
  { latitude: 45.96277, longitude: 5.35635, data: { amount: 5 } },
  ...
];
```

In the `ClusteredPointSeries`, I'd like to use the data from the points of a specific cluster to make dedicated rendering, a sum of `data.amount` for instance. But `dataItem.dataContext` from `clusteredBullet` callback is empty and it looks like I can't retrieve this data in the given context.

```typescript
// pointSeries is of type am5map.ClusteredPointSeries
pointSeries.set('clusteredBullet', (root, series, dataItem) => {
  let container = am5.Container.new(root, {});

  // In a label, '{value}' contains the number of points.
  // FIXME: How to retrieve data from clustered points, since contextData is empty?

  container.children.push(
    am5.Label.new(root, {
      centerX: am5.p50,
      centerY: am5.p50,
      fill: am5.color(0xffffff),
      populateText: true,
      fontSize: 16,
      // text: '{value}',
      text: 'sum?' // for instance I'd like to sum all item's `data.amount`
    })
  );
  
  return am5.Bullet.new(root, {
    sprite: container,
  });
});
```

**Environment**

amCharts version 5.8
Angular 15

**Demo**

CodePen : https://codepen.io/pvougny/pen/OJqdZVG?editors=0011

Thank you for your feedback.

<img width="604" alt="Capture d'écran 2024-02-16 215544" src="https://github.com/amcharts/amcharts5/assets/34480075/1098b5d5-c3a3-46a2-898c-ebad2f7fd042">

**Comment by martynasma** [comment]
The data item for clustered bullet contains `children` setting, which contains all the sub-data items that go into the group.

You can add an adapter on a Label to iterate through them, and add up their values, e.g.:

```JavaScript
label.adapters.add("text", function(text, target) {
  console.log(target.dataItem.get("children"));
  return text;
});
```

**Comment by martynasma** [comment]
Your adapter calculates `sum`, yet returns `value`. You just need to return `sum` from the adapter.

**Comment by pvougny** [comment]
My adapter would like to calculate sum, yes, but since it does not render properly, I tried with value, which does not render properly either. Look at the chart, try to zoom in and out, it's clear that it does not do what it's supposed to do.

**Comment by martynasma** [comment]
Indeed. The issue is that text adapter does not kick in when underlying items change.

OK, another approach:

```JavaScript
pointSeries.set('clusteredBullet', (root, series, dataItem) => {
  let container = am5.Container.new(root, {});

  container.children.push(
    am5.Circle.new(root, {
      radius: 20,
      fill: am5.color(0xfda29b),
      stroke: am5.color(0xf04438),
      strokeWidth: 2,
    })
  );

  const label = container.children.push(
    am5.Label.new(root, {
      centerX: am5.p50,
      centerY: am5.p50,
      fill: am5.color(0xffffff),
      populateText: true,
      fontSize: 16
    })
  );
  
  dataItem.dataContext = {
    label: label
  }

  dataItem.on("children", function(children, dataItem) {
    console.log(children, dataItem)
    if (dataItem) {
      const length = dataItem.get('children')?.length;
      const sum = dataItem.get('children')?.reduce(
        (res, item) => res + item.dataContext?.data.amount,
        0
      );
      dataItem.dataContext.label.set("text", sum);
    }
  })
  
  return am5.Bullet.new(root, {
    sprite: container,
  });
});
```

**Comment by pvougny** [comment]
CodePen updated. It works fine this way.

Thank you.

**Comment by CHANDRAMOHANnegi** [comment]
dataItem.get('children') is undefined

**Comment by CHANDRAMOHANnegi** [comment]
Is there any way to change container ICON, 
container.set("html","")
is not working inside that "on" event handler
