### ISSUE TITLE
Using a custom image instead of a coloured polygon

### ISSUE THREAD

**Issue by SmileSoftSr** [amcharts/amcharts5#1342]
Is it possible to use an image, instead of a colour for map polygons?

For example, instead of this:

![image](https://github.com/amcharts/amcharts5/assets/53255018/a3a6d8ca-23eb-4392-9c2a-43121acdf7eb)

I want to have something like this:

![image](https://github.com/amcharts/amcharts5/assets/53255018/af6af378-3b1d-4312-8f9e-f71907f639c5)

I've tried using the following (modified from the official documentation, trimmed down to relevant part):

```
...
polygonSeries.data.setAll([
  {
    id: "US",
    polygonSettings: {
      fill: am5.color(0xff3c38)
    }
  },
  {
    id: "CA",
    polygonSettings: {
      fill: "url('https://flagcdn.com/ca.svg')"
    }
  },
  {
    id: "MX",
    polygonSettings: {
      fill: am5.color(0xff8c42)
    }
  }
]);
```

My expectation was that I would get something like in the second image, but the colour for Canada defaulted to the shade of blue which other countries have (barring USA, and MX, used in the sample code I posted).

Can this be done, and if it can, how? I've thought of using patterns, but there's nothing in the documentation (not even PathPattern) which suggests that using any kind of file-graphics (SVG or other format) is possible.

**Comment by martynasma** [comment]
`fill` is only for color. If you would like to fill using an image, you will need to use `fillPattern` setting:

https://www.amcharts.com/docs/v5/concepts/colors-gradients-and-patterns/patterns/#Image_patterns

**Comment by SmileSoftSr** [comment]
Thank you, I can get the image fill effect to work with that (and apologies for saying that there was nothing in the docs). However, the results are not quite what I had in mind.

With this:

```
  id: "CA",
  polygonSettings: {
    fillPattern: am5.PicturePattern.new(root, {
      src: "https://flagcdn.com/ca.svg",
      fit: "image", // tried fit: "pattern", which made the image disappear
      width: 600,
      height: 300
    })
  }
```

the CA flag is in the background, but zooming in and out is not adjusting the background automatically. Also, panning in any direction is not moving the flag with the respective country [This fiddle](https://jsfiddle.net/qg9sd8uc/) illustrates what I'm talking about.

While this makes sense (I guess, since it's a pattern), this isn't quite what I wanted to do.

AM5 seems to be working differently in this regard, when compared to AM4 (found [this](https://github.com/amcharts/amcharts4/issues/3691) in the meantime, which seems to be working as I had originally hoped AM5 would - with fill, and non-static backgrounds).

Are there any other options? Something akin to using `background-image: url('....')` in CSS? If not, what am I missing in my setup with `filPattern` and `PicturePattern`?

**Comment by martynasma** [comment]
Indeed.

I'm afraid I don't have a solution for that 🙁

**Comment by SmileSoftSr** [comment]
Ah, no worries, I'll rethink my design choices. Thank you for the responses.
