### ISSUE TITLE
Adding cursor lags the chart

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1343]
- I am not able to get the exact reason why this happening, but if I add the cursor my scroll, drawing tools etc lags.
- I am only adding this :  `mainPanel.set("cursor", am5xy.XYCursor.new(instance, {}));`
- If I remove this, everything works perfectly fine. Even I tested my app after removing all the customization of amcharts, only leaving candlesticks. Then too I add this cursor it lags.
- I am performing lazy/on-demand loading on GaplessDateAxis in stockchart.

Without using cursor, which is lag free and drawings also drop where the user is requesting/clicking : 

https://github.com/amcharts/amcharts5/assets/137867461/bb95813e-943a-4362-aab6-470c3da412e0

With cursor, which feels lag and drawings are also not dropping on a single click: 

https://github.com/amcharts/amcharts5/assets/137867461/67e43597-4add-4695-ba27-4814b46fece9

**Comment by workingbuddy10** [comment]
Don't know why my instincts say that it's not the cursor which is causing issue, there is some styling done which is causing this.


but if you remove the cursor code it will work perfectly.

You can tryout it in below code pen link, try using Rectangle, Ellipse Fibonacci continously you will feel sometimes it is not dropping where you want to:
 
https://codepen.io/Ansh-m-the-reactor/pen/KKEEGaq

And after that try removing the cursor code which is present in the last, now perform the same drawings it will work fine.

**Comment by workingbuddy10** [comment]
Sorry for tagging @martynasma , I think it's little bit important!

**Comment by zeroin** [comment]
I must say I don't experience lag at all. I tried with CPU throttling, but it works as it should. What I experience is that sometimes drawing is not drawn on click - we will fix that in next release. You can also fix it by setting `forceInactive:true` for `lineX` and `lineY` of the cursor:

```
let cursor = mainPanel.get("cursor");
cursor.lineX.setAll({
  forceInactive:true
});
cursor.lineY.setAll({
  forceInactive:true
});
```

My suggestion would be to set `animationDuration:0` for you axis tooltips, maybe this will reduce the effect of lagging.

**Comment by workingbuddy10** [comment]
thank you @zeroin, your suggestions worked for me!!


Sure do fix it in the next release too!
