### ISSUE TITLE
Labels looks not clear

### ISSUE THREAD

**Issue by jiwonmik** [amcharts/amcharts5#1344]
**Bug description**

![image](https://github.com/amcharts/amcharts5/assets/59993029/8ed71502-a14b-436c-bb35-a42e6464c763)

I added `Label` for specific series as above, but the texts looks not clear. Is this a bug? or is there any setting that I have to set?

I set `Label` through below code.

```js
 series.bullets.push(function (root, series, dataItem) {

          return am5.Bullet.new(root, {
            sprite: am5.Label.new(root, {
              text: 'test',
              fontSize: 15,
              fontWeight: '500',
              fill: series.get('fill'),
              centerX: am5.p50,
              centerY: am5.p100,
              dy: -3,
              dx: -40,
            }),
          });

      });
```

**Environment (if applicable)**

- amCharts version: 5
- Related frameworks: Typescript

**Additional context**

**Comment by martynasma** [comment]
The code looks ok. Does this happen in all browsers? Would you be able to post your whole chart on CodePen?

**Comment by jiwonmik** [comment]
Sorry, it was related to my monitor's resolution 😂 It's looking clear, thanks !
