### ISSUE TITLE
GaplessDateAxis extraMax and gap

### ISSUE THREAD

**Issue by SeltonJeff** [amcharts/amcharts5#1349]
I searched but didn't find anything similar, here are my questions:

1- Is it possible to add extraMax dynamically to a dateAxis, by date instead of percentage?
2- Is it possible to add a gap with a pre-defined date range to a gaplessDateAxis?

**Comment by martynasma** [comment]
> 1- Is it possible to add extraMax dynamically to a dateAxis, by date instead of percentage?
> 2- Is it possible to add a gap with a pre-defined date range to a gaplessDateAxis?

The only way to do that is to add empty data items to data.
