### ISSUE TITLE
Remove grid's from xy chart

### ISSUE THREAD

**Issue by canesen7** [amcharts/amcharts5#1352]
![image](https://github.com/amcharts/amcharts5/assets/67913330/5d433efc-4672-474f-b7ee-941c4f956653)

I've chart like this. I want to delete background grids. When I tried to give opacity 0 to yRenderer and xRenderer that didn't work. How can I disable grids from xychart on amcharts 5

**Comment by martynasma** [comment]
Refer to this:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#grid-lines

**Comment by canesen7** [comment]
I can't see any idea for my issue without use theme.

**Comment by martynasma** [comment]
Sorry, my bad. There's a typo in my code, should be `strokeOpacity`.

**Comment by canesen7** [comment]
I didn't see stoke too.. Thank you for your hardworking and your support marty
