### ISSUE TITLE
Data placeholders on ValueAxis

### ISSUE THREAD

**Issue by Angusross111** [amcharts/amcharts5#1353]
**Question**
How do I use Data placeholders in the numberFormat option and tooltop labelText on a ValueAxis?
My data looks like this:
```
{
    year: "1988",
    value: 0.18,
    label: "my label"
  },
```
And I want to replace my labels and tooltip on the ValueAxis with the label field in my data.

I was able to add it to the series tooltip fine, but the ValueAxis tooltip and numberFormat didnt work.

https://jsfiddle.net/9716apch/5/

```
var yAxis = chart.yAxes.push(am5xy.ValueAxis.new(root, {
  maxDeviation: 1,
  renderer: am5xy.AxisRendererY.new(root, {
    pan: "zoom"
  }),
  tooltip: am5.Tooltip.new(root, {
    labelText: "{.label}",
  }),
   numberFormat: "{.label}",
}));
```

**Comment by martynasma** [comment]
`ValueAxis` does not have any relation to actual data items, because it displays numeric scale, not grid for each data item.

If you need to place specific label at specific values, I suggest you use axis ranges:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/axis-ranges/
