### ISSUE TITLE
How to make excel cell merge

### ISSUE THREAD

**Issue by Emre-Karadogan** [amcharts/amcharts5#1354]
Is there any way to make cell merge in excel? I have used something like below in amcharts4 but i need something that has same attribute in amchart5.

 exporting.adapters.add("xlsxWorkbook", workbook => {
/*

*/
}

Are there any alternatives of it?

**Comment by martynasma** [comment]
Please refer to this tutorial:
https://www.amcharts.com/docs/v5/concepts/exporting/exporting-data/#Modifying_XLSX
