### ISSUE TITLE
YTD is defined relative to Jan 1 rather than Dec 31

### ISSUE THREAD

**Issue by theoturner** [amcharts/amcharts5#1357]
YTD is defined relative to the Dec 31 of the previous year.

When using a PeriodSelector as follows:
```js
am5stock.PeriodSelector.new(root, {
  stockChart: chart,
  periods: [
    { timeUnit: "ytd", name: "YTD" },
  ],
});
```

The first date used is the current year's 1 Jan. This should be Dec 31 of the previous year.

A similar issue was raised and fixed in v4 but appears to have reappared in v5.

https://github.com/amcharts/amcharts4/issues/3249

**Comment by martynasma** [comment]
Can you explain why you think YTD should include a single day from the previous year? I don't think it's a common behavior for stock charts.

Or am I misreading your post?

**Comment by theoturner** [comment]
The reference point for a YTD return is used as the dec 31 close throughout finance - the YTD **period** would be from jan 1. This means a percentage return could be computed for jan 1 (relative to dec 31), and would not just be 0% relative to itself. Notably, if an amcharts `PercentScale` is set, the return for ytd period starts at 0% jan 1.

Here's a quick workaround for anyone who needs it:
```js
{ timeUnit: "custom", name: "YTD", start: new Date(new Date().getFullYear() - 1, 11, 31)},
```

**Comment by martynasma** [comment]
Thanks for the explanation and the workaround.

From what I have seen in stock charts, YTD always starts at the first trading day in the current year. This year it's Jan 2.

The following services treat Jan 2 as the base price (like amCharts):

Yahoo Finance:
![image](https://github.com/amcharts/amcharts5/assets/1458520/b3f926b1-a48a-44c1-b937-d6546b63f760)

TradingView:
![image](https://github.com/amcharts/amcharts5/assets/1458520/c8bd944b-422f-4984-b2ec-82d4fe9c26e8)

However barchart calculates base price as of Dec 29, which is what you are requesting I believe:
![image](https://github.com/amcharts/amcharts5/assets/1458520/fad25086-adff-4019-b092-95470d0dcbf9)

From the looks of it, there is no "golden standard" as different services treat YTD differently.

Based on this observation, I don't think it would be correct for us to change the behavior, given that the workaround suggested by you, looks good 😉
