### ISSUE TITLE
Axis Logarithmic Scale

### ISSUE THREAD

**Issue by sassomedia** [amcharts/amcharts5#136]
I'm trying to use the logarithmic scale and I'm noticing some range oddities. Shouldn't the max on the scale be based on the max of the data (plus some padding)?

In my example here, my data ranges up to 15K but the max on the axis shows 100K, leaving a lot of white space:
<img width="1158" alt="Screen Shot 2021-12-10 at 12 17 55 AM" src="https://user-images.githubusercontent.com/5614099/145424669-d946240b-3b66-412a-b19a-adac09a9677b.png">

I'm wondering if this is right because I have to calculate the median of that data but that doesn't quite seem to match with the logarithmic scale. With linear scale, it works as expected.

**Comment by martynasma** [comment]
You may use `strictMinMax: true` on your `ValueAxis` to cap the scale at exact max value.

**Comment by sassomedia** [comment]
Ok thanks, that works when also adding `extraMax`. However, it severely limits the number of axis labels, I get maybe one or two. Probably would have to generate my own labels based on log scale. I'll leave it for now without `strictMinMax` and test with a bit more data.

**Comment by sassomedia** [comment]
@martynasma Seems like I found a bug, the axis `zoomToValues` does not take logarithmic into consideration:
https://github.com/amcharts/amcharts5/blob/b6384a63a3ba234a2f2c43c5b0645648959089b9/src/.internal/charts/xy/axes/ValueAxis.ts#L1275-L1281

This causes it to scale way out of proportion when logarithmic is true.

**Comment by sassomedia** [comment]
As a workaround, I can instead use the `zoom` function, in combination with `valueToPosition`:
```javascript
const minVal = 500;
const maxVal = 1500;

xAxis.set("logarithmic", true);
xAxis.zoomToValues(minVal, maxVal); // scales out of bounds
```
```javascript
const minVal = 500;
const maxVal = 1500;

xAxis.set("logarithmic", true);
const zMin = xAxis.valueToPosition(minVal);
const zMax = xAxis.valueToPosition(maxVal);
xAxis.zoom(zMin, zMax); // works as expected
```
