### ISSUE TITLE
How to remove the grid lines

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1361]
I want to remove the grid lines in the stock chart, but I want to keep the label dotted line.

I tried this : `valueAxis.get("renderer").grid.template.set("visible", false);` But it is also removing the label price dotted line.

Remove the background grid line ( red color marked ) & and keep the Label dotted line ( yellow color marked) : 
![image](https://github.com/amcharts/amcharts5/assets/137867461/0edbee1a-6f00-440f-96a1-b06165490d0f)

**Comment by zeroin** [comment]
Yes, you should set:

`yAxis.get("renderer").grid.template.set("forceHidden", true)`

And then set `forceHidden:false` for the grid of your axis range:

`rangeDataItem.get("grid").set("forceHidden", false)`

**Comment by workingbuddy10** [comment]
I did this : 
![image](https://github.com/amcharts/amcharts5/assets/137867461/ee2178e0-28bd-485f-b3b2-4a1f293d13fb)

But it is showing error :      Cannot read properties of undefined (reading 'get') at rangeDataItem

I am using stock chart with GaplessDateAxis

@zeroin

**Comment by zeroin** [comment]
`rangeDataItem` is a data item which you created for the red color marker, it's not a property of an axis.

**Comment by workingbuddy10** [comment]
I am creating label like the below given code and I have tried this : `currentGrid.set("visible", false)`

Below is the full code for the label only :

```
  _createUpdateLabel(lastData) {
    //label property
    if (!this.currentValueDataItem) {
      let currentValueDataItem = this.valueAxis.createAxisRange(
        this.valueAxis.makeDataItem({ value: 0 })
      );
      this.currentValueDataItem = currentValueDataItem;
    }

    let currentLabel = this.currentValueDataItem.get("label");
    if (currentLabel) {
      currentLabel.setAll({
        fill: am5.color(0xffffff),
        background: am5.Rectangle.new(this.instance, {
          fill: am5.color(0x000000),
        }),
      });
    }
    let currentGrid = this.currentValueDataItem.get("grid");
    if (currentGrid) {
      currentGrid.setAll({ strokeOpacity: 0.5, strokeDasharray: [2, 5] });
    }
    {
      let closeValue = lastData.Close;
      let openValue = lastData.Open;

      this.currentValueDataItem.animate({
        key: "value",
        to: closeValue,
        duration: 500,
        easing: am5.ease.out(am5.ease.cubic),
      });

    // this.currentValueDataItem.set("visible", false)

      currentGrid.set("visible", false)

      currentLabel.set(
        "text",
        this.stockChart.getNumberFormatter().format(closeValue)
      );
      var bg = currentLabel.get("background");
      if (bg) {
        if (closeValue < openValue) {
          bg.setAll({
            fill:am5.color("#eb5b3c"),
          })
        } else {
          bg.setAll({
            fill:am5.color("#00b386"),
          })
        }
      }
    }
  }
```

@zeroin

**Comment by workingbuddy10** [comment]
Thanks it worked now !
@zeroin
