### ISSUE TITLE
Stock chart axis panning out of the scope

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1363]
I don't want to limit the the user to stretch or pan the value axis to the limited range only.

currently valueAxis is this : 
```
    var valueAxis = mainPanel.yAxes.push(
      am5xy.ValueAxis.new(instance, {
        renderer: am5xy.AxisRendererY.new(instance, {
          pan: "zoom",
          strokeOpacity: 1,
          strokeWidth: 1,
          stroke: am5.color("#474747"),
        }),
        strictMinMax:true,
        extraMin: 0.01,
        tooltip: am5.Tooltip.new(instance, {}),
        extraTooltipPrecision: 2,
      })
    );
```

Added the  `strictMinMax:true`, because the candlesticks were overlapping the volume bars.

Like initially only show the range which the data points are present but if the user wants to pan the value axis beyond the scope then they can.

Something like this :

https://github.com/amcharts/amcharts5/assets/137867461/6e177aad-b4e1-4ce1-bb59-998c32d932c6

**Comment by martynasma** [comment]
I'm afraid there's no way to limit the scale of axis zoom.

**Comment by workingbuddy10** [comment]
There are 3 things I want to achieve : 

1. ` I want to pan the chart around the date axis beyond the scope and there should no space created while loading data`, Like this : 
   

https://github.com/amcharts/amcharts5/assets/137867461/a102953d-0751-4446-ae24-092a1d731e9b

We can add extra space via maxDeviation but in the case of on-demand loading it is not working fine : 

 - When the maxDeviation  is 0, it doesn't create the space while on-demand data loading which is good but I am not able to pan out of the scope : 
 

https://github.com/amcharts/amcharts5/assets/137867461/7b78f049-a6d3-4df3-a232-f27cf0b90c24

- But When the maxDeviation  is 1 or any value greater than 0, it create the space while on-demand data loading which is not good. But now I can pan out of the scope : 
 
https://github.com/amcharts/amcharts5/assets/137867461/6e5b3696-89c6-4f97-8cad-bb9fd282fe2d



@martynasma

**Comment by martynasma** [comment]
Then you should reset `maxDeviation` to zero before loading the data, and set it to whatever the value you need it to be after load.
