### ISSUE TITLE
Can't see tooltips on charts with same

### ISSUE THREAD

**Issue by vskorop** [amcharts/amcharts5#1364]
Hi! Aloha!

I have chart labels on the axis of my chart. I need a way to show a tooltip with the value from the current point. I can't add a tooltip even with "hardcoded" values.

Sometimes it works with different datasets.
There are 2 attached datasets. In the first case I can find the tooltip, in the other case I can't. Both datasets have the same structure.

Currently trying to implement this:
`LineSeries.new(state.root, {
              tooltip: Tooltip.new(state.root, {
                labelText: '{valueY}'
              })
            })`
 but it doesn't work:

CodeSandbox example is here: (https://codesandbox.io/p/devbox/amcharts5-tooltip-issue-vzw2tz?file=%2Fsrc%2Fchart%2FplanActualChart.ts&embed=1)

 - amCharts version: 5.8.2 or 5.8.4,
 - Google chrome: v122.0.6261.69 or later,
 - Related frameworks and their versions are [React: 18.2.0, effector: 23.2.0]

Thanks.

**Comment by martynasma** [comment]
When you have data that is spaced wider than `baseInterval` set on the `DateAxis`, the tooltip might not show if hovered interval does not have a data item.

To solve, enable tooltip snapping:
https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/#Irregularly_spaced_data

**Comment by vskorop** [comment]
You're absolutely right, appreciate it! Have a good day
