### ISSUE TITLE
Drawing Index behaviour

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1365]
In recent update as you have introduced the drawingId, and from that with the help of getIndex we can retrieve the index of that particular drawing which has that id.
 
For example I have passed the value of `level` & in the unserialize drawings I have a object as trendline and level.
- I have a unserialize drawing data object which is level and I have given the drawingId.
- Don't how the series_index is different from the index which I have getting by getIndex.  

In the blue code line it is console value.
![image](https://github.com/amcharts/amcharts5/assets/137867461/940a9599-3752-4017-9324-a04e83c98b60)

Full code for removing the data : 
```
  deleteAutoIndicator(indicator) {
    const chartInstances = this.chartStore.chartInstances; 
    chartInstances.forEach((chartInstance) => {
      const drawingData = chartInstance.mainPanel.drawings._values;
      drawingData.forEach((series) => {
        

        if (VALID_SERIES_TYPES.includes(series.className)) {
          // value of indicator = 'level', which is given as the drawingId 
          console.log(series);
           
          const index = series.getIndex(indicator)
          if (index) {

            console.log(index); 
            console.log(series._index);
            
            series._disposeIndex(index); 
          }
        }
      });
    });
  }
```

JSON data of the drawing which is being tested above url : https://codebeautify.org/alleditor/y24183888#

**Comment by martynasma** [comment]
Frankly, I'm not entirely sure what you're asking.

Here's a demo which can restore serialized data with `drawingId` in them, then delete by respective ids.

https://codepen.io/team/amcharts/pen/gOyOEKy/b91d5db28e2e2336ab92dc71665c501f?editors=0010

I hope you find it useful.

**Comment by workingbuddy10** [comment]
Thanks that example solved my confusion @martynasma !!
