### ISSUE TITLE
show an alert when hovering over data points/bullents on the radar chart

### ISSUE THREAD

**Issue by habu23183** [amcharts/amcharts5#1367]
To show an alert when hovering over data points on the chart, you can use the following code:
This code is not working?

javascript
series.bulletsContainer.children.each(function (bullet) {
    bullet.events.on("pointerover", function (event) {
        var stateValue = event.target.dataItem.get("state");
        alert("State Value: " + stateValue);
    });
});
This code iterates over each bullet in the series and adds an event listener for the "pointerover" event. When the event is triggered, it retrieves the value of the "state" property from the data item associated with the bullet and displays an alert with the state value.

**Comment by zeroin** [comment]
It's difficult to say without full context. Maybe you add this code before bullets are created?
And I would add this pointerOver event on the bullet template instead (before bullets are created), this is more elegant.
