### ISSUE TITLE
xy.js broken with heatmaps

### ISSUE THREAD

**Issue by DylanAlloy** [amcharts/amcharts5#137]
Getting `this.startIndex is not a function`, reverting back to 5.0.3 fixes it, when I last remember it working.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

XY works fine with heat rules for me here:
https://www.amcharts.com/demos/heat-map-with-legend/

**Comment by DylanAlloy** [comment]
Unfortunately it's PII data.

**Comment by martynasma** [comment]
I'm afraid I don't know what "PII data" is :)

Is there any way you can help us reproduce the issue you are seeing?

**Comment by DylanAlloy** [comment]
Sorry, personally identifiable information protected by law. 

https://www.dol.gov/general/ppii

**Comment by martynasma** [comment]
Gotcha. Though, I'm pretty sure you can obfuscate the real data by scrambling real values.

We'll need a repro case if we're to solve this, or provide other solution.

Otherwise it's just stabbing in the dark, since we can't reproduce it :(
