### ISSUE TITLE
How to configure Treemap with React jsx?

### ISSUE THREAD

**Issue by sakthi0803** [amcharts/amcharts5#1370]
I want to configure treemap with the react js with jsx extension template file instead of core-js, can anyone help with this?

**Comment by martynasma** [comment]
Please follow our official React guide:
https://www.amcharts.com/docs/v5/getting-started/integrations/react/

**Comment by SakthivelSaravana** [comment]
@martynasma I need an example for the Treemap chart. Could you please share any examples for that?

**Comment by martynasma** [comment]
I'm afraid we do not have an example specifically for Treemap, however it will be exactly the same as with other charts. Just change the actual chart code to Treemap.

**Comment by SakthivelSaravana** [comment]
@martynasma How to set the color for each cell?

https://codepen.io/sakthi_vs/pen/YzgJMEX

**Comment by SakthivelSaravana** [comment]
@zeroin Got it, Thank you.
