### ISSUE TITLE
How can I get the interval value from Value Axis? 

### ISSUE THREAD

**Issue by jiwonmik** [amcharts/amcharts5#1371]
**Question**

<img width="1431" alt="image" src="https://github.com/amcharts/amcharts5/assets/59993029/1739fc09-1942-4b49-b743-875ab1af8481">

How can I get **`Value Axis` interval value?**  From the above screenshot, I should get `20`.
(FYI, I got the example from [tutorial](https://codepen.io/team/amcharts/pen/xxLBymy)).

**Environment (if applicable)**

amCharts version: 5
Related frameworks: Typescript

**Additional context**

**Comment by martynasma** [comment]
You can use private setting `step` for that:

```JavaScript
yAxis.getPrivate("step");
```

Or, you can monitor to any changes in step:

```JavaScript
yAxis.onPrivate("step", function(step) {
  console.log(step);
});
```

**Comment by jiwonmik** [comment]
Great, Thank you!
