### ISSUE TITLE
Better user experience - pointerover: Can I set the distance to set pointerover state?

### ISSUE THREAD

**Issue by jiwonmik** [amcharts/amcharts5#1374]
**Question**

From [this example](https://github.com/amcharts/amcharts5/issues/new?assignees=&labels=&projects=&template=question.md&title=),

```js
  series.strokes.template.events.on("pointerover", function(ev){
    console.log(ev.target);
  });
```

Abvoe `pointerover` is triggered when I hover on the **exact line**.
For better user experience, I want to set `pointerover` state as well when I hover close to the line, even though it's not exactly on the line.

Can I set some custom function for setting `pointerover` event? 

**Environment (if applicable)**

amCharts version: 5
Related frameworks: Typescript

**Additional context**

**Comment by zeroin** [comment]
No, I am afraid. But you could create a second series with exactly the same data, set `strokeWidth:10` and `strokeOpacity:0` and add pointer over for the   `series2.strokes.template`.

**Comment by jiwonmik** [comment]
Got it, thanks for another idea !!!
