### ISSUE TITLE
Method which returns true when the map contains the co-ordinates

### ISSUE THREAD

**Issue by anipr2002** [amcharts/amcharts5#1375]
**Question**

Is there a way to check to if a marker is in view when we zoom in or out the map. There is a method in [LeafletJs](https://leafletjs.com/reference.html#latlngbounds-contains).

I went through the documentation and there seems to be nothing similar to this.

**Environment (if applicable)**

 - amCharts version : 5
 - Related frameworks : React

**Additional context**

![image](https://github.com/amcharts/amcharts5/assets/131559231/f3c87923-fd3e-467e-901d-a97d173d7219)
When I zoom in, I need to get the co-ordinates of only the visible markers.

**Comment by martynasma** [comment]
You can use `MapChart` method `geoBounts()` to get current map bounds:
https://www.amcharts.com/docs/v5/reference/mapchart/#geoBounds_method

Then iterate through the series data items and check if they are within the bounds.
