### ISSUE TITLE
Overlapping axis labels after upgrading to new version

### ISSUE THREAD

**Issue by marciammart** [amcharts/amcharts5#1378]
**Bug description**

After upgrading from version 5.5.1 to 5.8.4, I've been having problems with overlapping axis labels in my chart. Is there a setting I can use to fix this?

Using 5.5.1:
![Screenshot 2024-03-04 at 17 33 09](https://github.com/amcharts/amcharts5/assets/53227495/f0bf126c-4846-4c0a-bf01-35f696ab2815)

Using 5.8.4:
![Screenshot 2024-03-04 at 17 32 10](https://github.com/amcharts/amcharts5/assets/53227495/2881371f-0f9b-4c88-8b2b-c44017366a2d)

I've also noticed that the zoom is working on scroll although the documentation says that the default value for `wheelX` and `wheelY` is `none`. Adding those manually fixes that problem.

**Environment (if applicable)**
Version 5.8.4 in React/Typescript

**Comment by zeroin** [comment]
Please provide a codepen or jsfiddle where this case can be reproduced, it's not possible to tell just looking at the screenshot.
