### ISSUE TITLE
Exporting chart to png programmatically results in empty png image

### ISSUE THREAD

**Issue by pneary** [amcharts/amcharts5#138]
Hello, I am writing a script to create an xy stacked column chart that will use the exporter to automatically download a png when executed. I've tried setting up the chart and then executing the code
 ```//set up exporting plugin
    var exporting = am5plugins_exporting.Exporting.new(root, {
        menu: am5plugins_exporting.ExportingMenu.new(root, {}),
        pngoptions: {
            quality: 1.0,
            maintainPixelRatio: true
        },
    });

    exporting.download("png");
```
which results in an empty png image. 

I believe some of the chart functions are async and completing after `exporting.download("png")` has been executed. If I add a `setTimeout` of ~2 or so seconds before download, the image properly downloads.

Is there an event listener I can use in order to wait to download the chart as png until the chart has been completely setup and rendered? If not, any suggestions on how to get a downloaded png image without having to use the export menu? I can provide more code if needed. Thanks!

**Comment by martynasma** [comment]
Something like this should work:

```JavaScript
var timeout;

root.events.on("frameended", exportChart);

function exportChart() {
  if (timeout) {
    clearTimeout(timeout);
  }
  timeout = setTimeout(function() {
    root.events.off("frameended", exportChart);
    exporting.download("png");
  }, 100)
}
```

**Comment by martynasma** [comment]
P.S. you also have a typo in your export config: `pngOptions` needs to be camelCase.

**Comment by pneary** [comment]
That did the trick. Thanks for the help!
