### ISSUE TITLE
Can i add element for tooltip text props on Treemap?

### ISSUE THREAD

**Issue by sakthi0803** [amcharts/amcharts5#1380]
Can I add an element for tooltip text props on Treemap?

series.labels.template.setAll({
      fill: '#000',
      text: <div>{'{category} \n {value}'}</div>
    });

**Comment by zeroin** [comment]
Check this information about tooltips on labels:
https://www.amcharts.com/docs/v5/concepts/common-elements/tooltips/#Tooltips_on_labels
