### ISSUE TITLE
Control+scroll on stock chart

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1381]
I am trying to add this feature in my chart but it is not working even though the even it triggering.

I trying this example : https://www.amcharts.com/docs/v5/charts/xy-chart/zoom-and-pan/#Control_scroll

But it is not working !! 
Codepen link : https://codepen.io/Ansh-m-the-reactor/pen/KKEEGaq?editors=1010

**Comment by workingbuddy10** [comment]
And also I want to control or slow down the zoom-in of the cursor. As when I zoom-in it zooms very fast to the recent points, I want it zoom a little bit slow or less zoom.

**Comment by zeroin** [comment]
If you'd check your code before posting the question, you would find some differences between our and yours :)
And again, this is out of scope of free support to look for the errors like these in your code.
