### ISSUE TITLE
Interactive Bullet Hover: Highlight Matching Legend Item

### ISSUE THREAD

**Issue by habu23183** [amcharts/amcharts5#1383]
When hovering over bullets, please check their values. If the value of a bullet matches the value of an item in the #Legend div, which contains a list of items in li tags, add the class "active" to that li tag. 

`
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        #chartdiv {
            width: 100%;
            height: 500px;
        }

        .container {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        #chartdiv,
        #legend {
            flex-basis: 50%;
        }

        .list {
            list-style: none;
            padding-right: 40px;
        }

        .list li {
            margin-bottom: 20px;
            font-size: 16px;
            position: relative;
            line-height: 29px;
        }

        .list li::before {
            content: '';
            position: absolute;
            width: 20px;
            height: 20px;
            left: -30px;
            top: 4px;
            border-radius: 5px;
            background: #addfb3;
        }

        .active {
            color: red;
        }
    </style>

    
    <script src="https://cdn.amcharts.com/lib/5/index.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/xy.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/radar.js"></script>

    <script src="https://cdn.amcharts.com/lib/5/themes/Animated.js"></script>

</head>

<body>

    
    <script>
        am5.ready(function () {

            // Create root element
            // https://www.amcharts.com/docs/v5/getting-started/#Root_element
            var root = am5.Root.new("chartdiv");

            // Set themes
            // https://www.amcharts.com/docs/v5/concepts/themes/
            root.setThemes([
                am5themes_Animated.new(root)
            ]);

            // Create chart
            // https://www.amcharts.com/docs/v5/charts/radar-chart/
            var chart = root.container.children.push(am5radar.RadarChart.new(root, {
                panX: false,
                panY: false,
                wheelX: "panX",
                wheelY: "zoomX"
            }));

            // Add cursor
            // https://www.amcharts.com/docs/v5/charts/radar-chart/#Cursor
            var cursor = chart.set("cursor", am5radar.RadarCursor.new(root, {
                behavior: "zoomX"
            }));

            cursor.lineY.set("visible", false);

            // Create axes and their renderers
            // https://www.amcharts.com/docs/v5/charts/radar-chart/#Adding_axes
            var xRenderer = am5radar.AxisRendererCircular.new(root, {});
            xRenderer.labels.template.setAll({
                visible: false
            });

            var xAxis = chart.xAxes.push(am5xy.CategoryAxis.new(root, {
                maxDeviation: 0,
                categoryField: "category",
                renderer: xRenderer
            }));

            var yAxis = chart.yAxes.push(am5xy.ValueAxis.new(root, {
                renderer: am5radar.AxisRendererRadial.new(root, {}),
                min: 0,
                max: 5
            }));

            // Create series
            // https://www.amcharts.com/docs/v5/charts/radar-chart/#Adding_series
            var series = chart.series.push(am5radar.RadarLineSeries.new(root, {
                name: "Series",
                xAxis: xAxis,
                yAxis: yAxis,
                valueYField: "state",
                categoryXField: "category",
                strokeWidth: 1,
                stroke: am5.color("#addfb3"),
            }));

            var tooltip = am5.Tooltip.new(root, {

                getFillFromSprite: false,
                labelText: "{valueY}"
            });

            tooltip.get("background").setAll({
                fill: am5.color("#000000"),
                fillOpacity: 0.8
            });
            series.set("fill", am5.color(0xff0000));
            series.set("tooltip", tooltip);

            series.bullets.push(function () {
                return am5.Bullet.new(root, {
                    sprite: am5.Circle.new(root, {
                        radius: 5,
                        fill: am5.color("#14853D")
                    })
                });

            });

            // Set data
            // https://www.amcharts.com/docs/v5/charts/radar-chart/#Setting_data
            var data = [{
                "category": "text1",
                "state": 1
            }, {
                "category": "text2",
                "state": 3
            }, {
                "category": "text3",
                "state": 4
            }, {
                "category": "text4",
                "state": 2
            }, {
                "category": "text4",
                "state": 5
            }, {
                "category": "text5",
                "state": 2,
            }, {
                "category": "text6",
                "state": 1
            }];
            var legenDiv = document.querySelector('.list');
            data.forEach(function (item) {
                var categoryText = document.createElement('li');
                categoryText.textContent = item.category;
                legenDiv.appendChild(categoryText);

            });
            series.data.setAll(data);
            xAxis.data.setAll(data);

            // series.bulletsContainer.events.on("pointerover", (event) => {
                
            //     console.log(event.target.children.values[0].dataItem.dataContext.state)
                
            // });
            series.bulletsContainer.events.on("pointerover", (event) => {
  const hoveredBullet = event.target;
  const bullets = hoveredBullet.children;
  bullets.each((bullet) => {
    if (bullet.isHover) {
      const value = bullet.dataItem.dataContext.state;
      console.log(value);
    }
  });
});

            // Animate chart and series in
            // https://www.amcharts.com/docs/v5/concepts/animations/#Initial_animation
            series.appear(1000);
            chart.appear(1000, 100);

        }); // end am5.ready()
    </script>

    
    <div class="container">
        <div id="chartdiv"></div>
        <div id="legend">
            <ul class="list">

            </ul>
        </div>
    </div>
</body>

</html>
`
@martynasma  can you please help me with this, and i am using amchart5 for above code.

**Comment by zeroin** [comment]
I am afraid this is out of scope of free support, if you have a license, please, contact our support team.

**Comment by habu23183** [comment]
In this code i have shared html css and js all in one go, that is why its look too long, please just focus on js part for my query.
@martynasma  can please help me in with the above.
