### ISSUE TITLE
Change the zoom behavior of the chart.

### ISSUE THREAD

**Issue by p3777dev** [amcharts/amcharts5#1386]
I would like to enlarge my stock chart in this way: https://www.amcharts.com/demos/on-demand-data-loading/
 For example, the mouse wheel zooms in to the pointer data point wherever I place the cursor.

However, the example above is in the XY chart, and I want to implement this on the stock chart. 
At https://www.amcharts.com/demos/stock-chart/,

Please advise which properties should be added or changed to make the stock chart behave the same.

**Comment by zeroin** [comment]
Stock chart's panel is XYChart (StockPanel extends XYChart), so it's all the same like in the example provided.

**Comment by p3777dev** [comment]
> Stock chart's panel is XYChart (StockPanel extends XYChart), so it's all the same like in the example provided.

You are right, did the exactly same thing. Yet it didn't worked like the on-demand loading chart is zooming.

minimal code of stockchart:  https://codepen.io/prince-work/pen/XWQmomj

**Comment by zeroin** [comment]
I am afraid this is out of scope of free support. If you have a commercial license, please contact our support.
