### ISSUE TITLE
How to make the bullet of a MapPointSeries hover when hovering over a MapPolygon

### ISSUE THREAD

**Issue by suu3** [amcharts/amcharts5#1389]
**Question**

Hello, I'm looking for a way to make the bullet of a **MapPointSeries** hover when hovering over a **MapPolygon**.
Just like in this demo(https://codepen.io/team/amcharts/pen/rNGKyRG?editors=1111), I want the bullet to hover when hovering over a Polygon in the **MapPolygonSeries**.
However, even if I try the same `series.get("tooltip").dataItem`, it doesn't seem to work.

I want the bullet with the same id as the corresponding polygon to enter the hover state when the 'pointerover' event occurs on the mapPolygon
I also tried something like this: https://codepen.io/suu3/pen/mdgVRMm?editors=1111, but the hover doesn't work. Can you help me?

**Environment (if applicable)**

@amcharts/amcharts5: "^5.0.10"

**Comment by zeroin** [comment]
Here is a modified example:
https://codepen.io/team/amcharts/pen/YzMwVgP??editors=1111

And the code which does the thing:

```
polygonSeries.mapPolygons.template.events.on('pointerover', ev => {
  var di = bubbleSeries.getDataItemById(ev.target.dataItem.get("id"))
  if(di){
    var bullets = di.bullets;
    if(bullets){
      var bullet = bullets[0];
      if(bullet){
        var sprite = bullet.get("sprite");
        if(sprite){
          sprite.hover();
        }
      }
    }
  }

});


polygonSeries.mapPolygons.template.events.on('pointerout', ev => {
  var di = bubbleSeries.getDataItemById(ev.target.dataItem.get("id"))
  if(di){
    var bullets = di.bullets;
    if(bullets){
      var bullet = bullets[0];
      if(bullet){
        var sprite = bullet.get("sprite");
        if(sprite){
          sprite.unhover();
        }
      }
    }
  }
});
```

**Comment by suu3** [comment]
Thank you for the modified example! I appreciate it. So, there is a getDataItembyId function in MapPointSeries.
I will close this issue :)
