### ISSUE TITLE
How can I get the target series's data placeholder value?

### ISSUE THREAD

**Issue by jiwonmik** [amcharts/amcharts5#1391]
**Question**

```js
    const series = chart.series.push(
      am5xy.ColumnSeries.new(root, {
        name: label as string,
        stacked: stacked as boolean,
        xAxis,
        yAxis,
        valueYField: 'name',
        categoryXField: 'category',
        ....
      })
    );
```

And when data structure is like below,

```js
{
  category: "Research",
...
}, {
  category: "Marketing",
...
}, {
  category: "Sales",
...
}
```

If I set my series like the above, how can I get specific series's `category` **value**, not the key name?

For example, I want to get the value from below iteration.
```js
chart.series.each(function (chartSeries: am5xy.ColumnSeries) {
      console.log('===============================');
      console.log('what is the chartSeries: ', chartSeries);
      console.log('check this field out: ', chartSeries.get('category'));
      console.log('check this field out: ', chartSeries.get('name'));
    });
```

If I `console.log('check this field out: ', chartSeries.get('categoryField'));`
I get the "key" from the data, which is "category".
But I want to get "Research", "Marketing", "Sales", which is the values.

How can I get if from `chart.series.each(function ... ` ?

FYI, I know that `dataItem` has the data, but it get the whole series' data. I want to get each data when iterating over each series.

If `chart.series...` is wrong, please let me know another approach. 

**Environment (if applicable)**

amCharts version: 5
Related frameworks: Typescript

**Additional context**

**Comment by zeroin** [comment]
series.dataItems is an array of all dataItems, if this is what you are asking for.
