### ISSUE TITLE
why on panning valueAxis don't update according to the data points visible

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1392]
When I zoom-in/out the valueAxis update perfectly.

But when I try to pan/drag the candles to the right, the valueAxis should get update according to the presently visible high and low.

1) Currently it is happening like this : 

https://github.com/amcharts/amcharts5/assets/137867461/d37ca52f-7479-4ef1-8858-b400394b0efe

2) But is should update the valueAxis like this : 

https://github.com/amcharts/amcharts5/assets/137867461/07c1e0ee-353e-4806-bcfa-977e5a129521

Any help or lead would be great how to achieve this. As this is very standard thing to have.

**Comment by zeroin** [comment]
Do you have `panY` set to `true`? If yes, then you pan both x and y axis at the same time.  Try setting it to false.
