### ISSUE TITLE
Stock chart calendar questions

### ISSUE THREAD

**Issue by Chris-Anastasov** [amcharts/amcharts5#1393]
**Question**
Hello,
 
I'm trying to recreate the old calendar from version 3 (just text inputs for data), but I have some issues/questions regarding the functionalities.
Here's my [codepen]( https://codepen.io/kris-a/pen/wvZwQKL).

1. You can see how on input changes, I get the provided dates, parse them to js Date objects and use the function zoomToDates.
Example: Change the "To" date to "24.12.2002" and move away from the field (Tab) or press Enter.
- What happens is the chart's last date is showing 23.12.2002 and so is the new calendar.
![image](https://github.com/amcharts/amcharts5/assets/102764508/e5f9f88f-46f3-4491-9c19-b04694f4b028)
As far as I understand this was introduced in the 5.8 version due to a similar issue a colleage had sent where you remove a second from the "To" date in the calendar.
Is it safe to say that the chart will be always cut just before that "To" date? 
Can this be added to a setting, to either cut just before the desired date or have it featured?

2. Choosing "24.12.2002" in the new calendar.
- We get the proper date in the chart "24.12.2002", but the calendar date jumps to "25.12.2002" and as you can see I automatically change my inputs to the selected dates which apparently is "26.12.2002".
I see why you've removed the one second from the "To" date but it doesn't solve the case with gapless linechart and gaps bigger than one day.
We've currently solved that by adjusting the prices and filling all gaps with the last available price so just wanted to point it out.

3. Choosing 1 month from the date selector gives wrong dates.
- Since my last available date is 27.12.2002, when selecting 1 month I'd expect to see the range 27.11.2002 - 27.12.2002 (I have values for both dates), but what I get is 28.12.2002 - 27.12.2002 in the new calendar and 28.12.2002 - 28.12.2002 in mine.
I could adjust what I'm showing in the date inputs and what dates I'm sending to the zoomToDates function to recreate the desired effect that's specific to us but even so it would mess up the selectors.
Would you consider this as a bug or do you have any recommendations how to handle it?

Thank you in advance and keep up the good work!

**Comment by martynasma** [comment]
If you zoom axis to exactly "24.12.2002" it means "24.12.2002 00:00:00" or the very start of 24.12.2002, hence the actual 24th not visible.

What we do in built-in date range selector is add 23:59:59 to the Date object before zooming the date.

I hope that makes sense, and you will be able to make necessary changes to your code.

**Comment by Chris-Anastasov** [comment]
Thank you, it seems when I pass for example 24.12.2002 00:10:00" it actually returns the 24th (it switches the input to 25th automatically, but I can work with that).
Any suggestions for the 3rd point? 
I'm not sure how to handle it yet.. 
It's all related to the default behaviour of the Period selector.

**Comment by martynasma** [comment]
You need to adjust your "to date" as well to include correct dates.

**Comment by Chris-Anastasov** [comment]
We've ended up using the custom periods and setting the desired yearly range.
Thank you for your cooperation, I'll close the topic.
