### ISSUE TITLE
Collapsible Force-Directed Tree defalut click 

### ISSUE THREAD

**Issue by MinorN** [amcharts/amcharts5#1394]
**Question**

i want to change the defalut click,so i do this `series.events.on("click", this.handleLeftClick)`,but i found that not working,because it has default click to expand children, so how can i do this,because i want rightclick to expand children or pack up children

my english so poor ,  I hope you can understand it，thanks

**Additional context**
```
      let root = am5.Root.new("am5Chart");
      root.setThemes([animated.new(root)]);

      const container = root.container.children.push(
        am5.Container.new(root, {
          width: am5.percent(100),
          height: am5.percent(100),
          layout: root.verticalLayout,
        })
      );

      let series = container.children.push(
        am5hierarchy.ForceDirected.new(root, {
          singleBranchOnly: false,
          downDepth: 2,
          topDepth: 1,
          initialDepth: 1,
          valueField: "value",
          categoryField: "name",
          childDataField: "children",
          idField: "name",
          linkWithField: "linkWith",
          manyBodyStrength: -10,
          centerStrength: 0.8,
        })
      );

      this.am5Instance = series;

      series.links.template.set("strength", 0.5);

      console.log(series.events);

      series.data.setAll([mockData]);
      // series.circles.template.setAll({
      //   fill: "red",
      // });

      // series.set("selectedDataItem", series.dataItems[0]);

      // Make stuff animate on load
      series.appear(1000, 100);

      series.events.on("click", this.handleLeftClick);

      series.events.on("rightclick", this.handleRightClick);
```

**Comment by martynasma** [comment]
You need to add a click on a node, not on series:

```JavaScript
series.nodes.template.events.on("click", function(ev) {
  console.log(ev.target)
});
```

**Comment by MinorN** [comment]
> ```js
> series.nodes.template.events.on("click", function(ev) {
>   console.log(ev.target)
> });
> ```

i do this,but it also not working

**Comment by martynasma** [comment]
Make sure that events are set before data set on series.

**Comment by MinorN** [comment]
> Make sure that events are set before data set on series.

its run ! thanks, but when i click ,  it also can expand children,i just want to do it when i rightclick

**Comment by martynasma** [comment]
Please refer to this doc:
https://www.amcharts.com/docs/v5/charts/hierarchy/hierarchy-drill-down/#Disabling_drill_down

It shows how to disable built-in click toggling, also how to toggle on double-click. You can easily replace to right-click.

**Comment by MinorN** [comment]
> Please refer to this doc: https://www.amcharts.com/docs/v5/charts/hierarchy/hierarchy-drill-down/#Disabling_drill_down
> 
> It shows how to disable built-in click toggling, also how to toggle on double-click. You can easily replace to right-click.

thanks!
