### ISSUE TITLE
Can we use mouse wheel to scroll the valueAxis

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1395]
I am trying to add the mouse wheel property to my stockchart valueAxis.

Currently I have to pan to valueAxis to zoom -in/out the values of the axis. Can I do it on the mouse wheel scroll?
As it would be more smooth than panning.

My chart config is like this : 
```

    var mainPanel = stockChart.panels.push(
      am5stock.StockPanel.new(instance, {
        wheelY:"zoomX",
        panX: true,
        panY: true,
        height: am5.percent(90),
        wheelStep:0.1,
        // wheelable:true,
      })
    );
    
        var valueAxis = mainPanel.yAxes.push(
      am5xy.ValueAxis.new(instance, {
        renderer: am5xy.AxisRendererY.new(instance, {
          pan: "zoom",
          strokeOpacity: 1,
          strokeWidth: 1,
          stroke: am5.color("#474747"),
        }),
        strictMinMax:true,
        extraMin: 0.1,
        maxDeviation:1,
        tooltip: am5.Tooltip.new(instance, {}),
        extraTooltipPrecision: 2,
        autoZoom:false,
      })
    );
```

**Comment by zeroin** [comment]
Here are all the possible settings for wheelX:
https://www.amcharts.com/docs/v5/reference/xychart/#wheelY_setting
https://www.amcharts.com/docs/v5/charts/xy-chart/zoom-and-pan/#Setting_behavior

**Comment by workingbuddy10** [comment]
Just to re-confirm that you got my question :

I want something like this,  like zooming the valueAxis with the mouse wheel.

https://github.com/amcharts/amcharts5/assets/137867461/25c34889-968c-4cb9-98ae-27c7cfcf6722




> Here are all the possible settings for wheelX: https://www.amcharts.com/docs/v5/reference/xychart/#wheelY_setting https://www.amcharts.com/docs/v5/charts/xy-chart/zoom-and-pan/#Setting_behavior

So something like this is be achievable by using the above properties?

@zeroin

**Comment by zeroin** [comment]
I see. No, the is no separate wheel behavior for this area.

**Comment by workingbuddy10** [comment]
If it is possible & you guys feel important to have it in amcharts stock chart then please add it. As it increase the user experience.

Thank you @zeroin for your response !!
