### ISSUE TITLE
(MapChart) Why don't the wheelSensitivity and wheelDuration properties work when wheelY is set to zoom?

### ISSUE THREAD

**Issue by suu3** [amcharts/amcharts5#1398]
**Question**

I tried to apply the wheelSensitivity and wheelDuration properties to the MapChart, but it seemed to have no effect. Then, I found the following code in the amcharts5 repository.

```amcharts5/src/.internal/charts/map/MapChart.ts``` 346-382
```javascript
...
	this._wheelDp = chartContainer.events.on("wheel", (event) => {
	const wheelEasing = this.get("wheelEasing")!;
	const wheelSensitivity = this.get("wheelSensitivity", 1);
	const wheelDuration = this.get("wheelDuration", 0);

	const wheelEvent = event.originalEvent;

	// Ignore wheel event if it is happening on a non-chart element, e.g. if
	// some page element is over the chart.
	if ($utils.isLocalEvent(wheelEvent, this)) {
		wheelEvent.preventDefault();
	}
	else {
		return;
	}

	const point = chartContainer._display.toLocal(event.point);

	if ((wheelY == "zoom")) {
		this._handleWheelZoom(wheelEvent.deltaY, point);
	}
	else if (wheelY == "rotateY") {
		this._handleWheelRotateY(wheelEvent.deltaY / 5 * wheelSensitivity, wheelDuration, wheelEasing);
	}
	else if (wheelY == "rotateX") {
		this._handleWheelRotateX(wheelEvent.deltaY / 5 * wheelSensitivity, wheelDuration, wheelEasing);
	}

	if ((wheelX == "zoom")) {
		this._handleWheelZoom(wheelEvent.deltaX, point);
	}
	else if (wheelX == "rotateY") {
		this._handleWheelRotateY(wheelEvent.deltaX / 5 * wheelSensitivity, wheelDuration, wheelEasing);
	}
	else if (wheelX == "rotateX") {
		this._handleWheelRotateX(wheelEvent.deltaX / 5 * wheelSensitivity, wheelDuration, wheelEasing);
	}
...
```

I'm curious why wheelSensitivity and wheelDuration properties are missing only when wheelY is set to "zoom".

**Comment by zeroin** [comment]
Indeed, we will investigate and will let you know. Thank you for noticing.

**Comment by zeroin** [comment]
Although I think we decided that it should use `zoomStep` value, but still, we'll discuss it internally.

**Comment by suu3** [comment]
Thank you. I will use zoomStep.
In my opinion, it would be better if the documentation explicitly stated that wheelSensitivity and wheelDuration cannot be used when wheelY is set to "zoom", or if the same action is performed regardless of the value of wheelY.

**Comment by martynasma** [comment]
@suu3 We're updating docs as we speak. Thanks for the suggestion!
