### ISSUE TITLE
Dataprocessor not working

### ISSUE THREAD

**Issue by tobias-berg** [amcharts/amcharts5#14]
I have data coming in the format: [{date: '2021-10-01', value: 200} ... ] and as amcharts require javascript dates it would be nice to use the dataprocessor to convert this automatically.

Following the docs, this is what I've tried:

```
series.data.setAll(data);
                    series.data.processor = am5.DataProcessor.new(root, {
                        numericFields: ["value"],
                        dateFields: ["date"],
                        dateFormat: "yyyy-MM-dd",
                        emptyAs: 0,
                    });
```

However, this does not seem to do anything. No errors, just an empty graph. As soon as I start converting the dates in the backend like this: DateTime.fromISO(date).toMillis(), it works.

**Comment by martynasma** [comment]
There's a catch: processing of data happens immediately after you set it. Processor needs to be set before data, or it does not kick in.

Now that I'm looking at the docs, we don't have that stated anywhere, and even have some snippets that put processor code after data, which is a gross oversight on our part. Sorry about that.

We're making doc updates as we speak.

**Comment by tobias-berg** [comment]
Yes, that makes sense. Why didn't I try that? ;) As the documentation suggested the other way around I just followed that. Just tested to assign dataprocessor first and it works nicely. Thanks for the clarification!
