### ISSUE TITLE
Tooltip distance x or y offsets for adding positioning space

### ISSUE THREAD

**Issue by buggedcom** [amcharts/amcharts5#140]
![Screenshot 2021-12-10 at 08 43 28](https://user-images.githubusercontent.com/2810/145529881-181fa790-d623-4a4c-bf6f-2fe4231e47f3.png)

Take for example this chart with tooltips for each line series. The tooltips position themselves so close to the data point it's actually impossible to see the context of the data point.

Is it possible to add some kind of additional distance offsets to the tooltip to provide clearspace from the tooltip to the place that they are pointing too?

**Comment by zeroin** [comment]
You can increase distance between tooltips by setting marginBottom for the tooltip:

```
 tooltip: am5.Tooltip.new(root, {
      pointerOrientation: "horizontal",
      labelText: "{valueY}",
      marginBottom:20
    })
```

**Comment by buggedcom** [comment]
It's not the distance between the tooltips, but rather the distance between the crosshair and the tooltips.

**Comment by buggedcom** [comment]
Or rather the distance between the tooltip content box and the point that they are pointing to.

**Comment by zeroin** [comment]
Then maybe pointerLength of a tooltip background (as it's PointedRectangle) would help:

`series.get("tooltip").get("background").set("pointerLength", 20)`

**Comment by buggedcom** [comment]
Brilliant, Thank you.
