### ISSUE TITLE
Drawing tool event

### ISSUE THREAD

**Issue by p3777dev** [amcharts/amcharts5#1400]
I understand the drawings update method

```
 stockChart.events.on("drawingsupdated", function(ev) {
   //...    
 });
```
 
I want an event which tells me whenever the user has completed the drawing using any tool. Like endpolyline event which called on polyline drawing completion.

**Comment by martynasma** [comment]
I'm afraid there's no such event. `drawingsupdated` will trigger on any small change.

**Comment by martynasma** [comment]
Heads up, there's an update about this in 5.9.0. Relevant excerpt from changelog:

## [5.9.0] - 2024-04-09

### Added
- New `StockChart` events: `drawingadded`, `drawingremoved`, `drawingselected`, `drawingunselected`.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).
