### ISSUE TITLE
Hovering on border between rectangles causes Treemap tooltip to swerve

### ISSUE THREAD

**Issue by c-ody** [amcharts/amcharts5#1402]
**Bug description**

Sometimes, hovering your mouse right between two rectangles (in the white border between the rectangles) causes the tooltip to swerve to a different rectangle.

For a minimal example, using your demo Treemap (https://www.amcharts.com/demos/drill-down-treemap/), if you hover your mouse right between Ford and Toyota, the tooltip swerves to Subaru: https://jsfiddle.net/je598kua/.

**Comment by martynasma** [comment]
I can't seem to be able to reproduce this in the jsFiddle you provide.

However, you might try setting `crisp: true` on rectangles:

```JavaScript
series.rectangles.template.setAll({
  crisp: true
});
```

**Comment by zeroin** [comment]
This should solve the issue:
`series.nodes.template.setPrivate("trustBounds", true);` 

we will add this to our sources in next release - thanks for noticing.
