### ISSUE TITLE
 How to fixed node to dragged position in forced directed chart?

### ISSUE THREAD

**Issue by ChyunKim** [amcharts/amcharts5#1405]
amCharts version is AmChart5

I wanted the node to fix itself at the dragged position, so I set velocityDecay to 1.

If I set velocityDecay initially, the nodes lose their mobility before they are pre-sorted, which ruins the appearance of the chart. 
So I set up the animation as below:

```js
series.animate({
    key: "velocityDecay",
    to: 1,
    duration: 5000,
});
```

Is this the right approach?

If I reduce the duration of the animation, the chart's appearance will be compromised.

**Comment by zeroin** [comment]
Hi,

Here is a portion about it:
https://www.amcharts.com/docs/v5/charts/hierarchy/force-directed/#Fixed_nodes

So if you want any node to be fixed just after it is dragged, then you should set x and y for the data item after dragstopped event:

```
series.nodes.template.events.on("dragstop", function(e){
  e.target.dataItem.setAll({
    x:e.target.x(),
    y:e.target.y()
  })
})
```
https://codepen.io/team/amcharts/pen/RwOGoZB/555a6b68ca3bf2a1fe9bff009d7ec6d1

**Comment by ChyunKim** [comment]
Many thanks for helping out!
