### ISSUE TITLE
Add space per month in clustered and layered column chart

### ISSUE THREAD

**Issue by choconutzy** [amcharts/amcharts5#1407]
**Question**

How to add space between month (per month) in this layered and clustered chart
https://codepen.io/choconutzy/pen/PogwJNm
![Screenshot 2024-03-17 164501(clustered layered)](https://github.com/amcharts/amcharts5/assets/78308985/306aed91-60ec-4f5c-9087-5119c266e09e)
I've try to add cellStartLocation: 0.2, cellEndLocation: 0.8 on xRenderer variable but the space add per category/ per column
I'm using : 
- Amchart 5

**Comment by martynasma** [comment]
I'm afraid there's no way to add extra spacing to specific categories only.
