### ISSUE TITLE
Ctrl key event + On-demand loading changes the position of cursor

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1410]
I am using on-demand loading of stock chart, and I have also added the ctrl key zoom feature.

But when I am pressing the ctrl key and trying to load the data the cursor moves/shifts from the initial position. Ideally it should not happen.

Any way in amcharts to hold the cursor position when zooming out or loading the data via wheelended event.

In first half of the video  currently how it is working, and in second half ideally what should happen: 

https://github.com/amcharts/amcharts5/assets/137867461/d9f08398-9dde-4eaa-85c7-f813bc8eaddd

**Comment by workingbuddy10** [comment]
Sure @martynasma 

Just point out the cursor at one candlestick, and then zoom -out + ctrl key. More data will load but the cursor position will also shift ( which I don't want).

https://codepen.io/Ansh-m-the-reactor/pen/abxpLxB

**Comment by martynasma** [comment]
OK, so what happens, the overzoomed part gets reset when you update data.

The only workaround I can think of is to log X-axis' private variables `selectionMin` and `selectionMax` before loading data, then do `zoomToValues()` after series' `datavalidated` kicks in.

**Comment by workingbuddy10** [comment]
Isn't there any better or reliable way to achieve this? Like I'll be having live data coming too + on-demand loading.


> The only workaround I can think of is to log X-axis' private variables `selectionMin` and `selectionMax` before loading data, then do `zoomToValues()` after series' `datavalidated` kicks in.

**Comment by martynasma** [comment]
Not sure. Maybe disable overzoom?
