### ISSUE TITLE
OHLC Data Not Showing from valueSeries tooltipDataItem event by amcharts 5

### ISSUE THREAD

**Issue by kirannarwade** [amcharts/amcharts5#1411]
We have 1 feature in our live website, its show OHLC Data on hover change in drag div container, in previous days its working finely but now im checked its not working , im sharing you event code as well as past working image and now image please check and update me its urgent its live website.

![ohlc_old](https://github.com/amcharts/amcharts5/assets/90048456/b45fdebe-f8ca-41bb-b8e7-8ea2543acaa9)
![Screenshot from 2024-03-19 17-10-29](https://github.com/amcharts/amcharts5/assets/90048456/478e04d3-daf3-42d5-9dd0-8dd026e37d57)
![Screenshot from 2024-03-19 17-10-24](https://github.com/amcharts/amcharts5/assets/90048456/d9310681-c893-44f7-ac59-ee2dc6c8f193)

please check it.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by kirannarwade** [comment]
it is done from cursor event and getting data as per requirement. thank you, if any future issue ill tell you ,
Thanks buddy!
