### ISSUE TITLE
How i get the OLHC whole 1 candle open,high, etc all things by my cursor event

### ISSUE THREAD

**Issue by kirannarwade** [amcharts/amcharts5#1412]
i applied mouse hover event and its working on each and every candle hover but i want get the that 1 candle data of every mouse hover

![Screenshot from 2024-03-19 17-31-35](https://github.com/amcharts/amcharts5/assets/90048456/f1c1de85-d963-46ac-8abd-8db7a8a569c3)

**Comment by workingbuddy10** [comment]
Do you want to display the data/values of that OHLC candles, if user hovers on that candle?

@kirannarwade

**Comment by kirannarwade** [comment]
done by me.. thanks
