### ISSUE TITLE
`start` and `end` settings not working in `ValueAxis` after version 5.8.4

### ISSUE THREAD

**Issue by marciammart** [amcharts/amcharts5#1414]
**Bug description**

I've noticed that the `start` and `end` settings, when applied to the `ValueAxis` after upgrading to version `5.8.4` are being ignore and not adding the padding that I previously had in the axis. Here is an example of how I'm setting those values:

```javascript
const xAxis = chart.xAxes.push(
    am5xy.ValueAxis.new(root, {
        renderer: xRenderer,
        min: data[0].year,
        max: data[data.length - 1].year,
        paddingLeft: 0,
        paddingRight: 0,
        start: -0.09, // stopped working
        end: 1.09, // stopped working
    }),
);
```

Version 5.8.3 and previous versions work fine. Should I use different settings for that in the new version?

**Environment (if applicable)**
React/Typescript using version 5.8.4

**Comment by workingbuddy10** [comment]
You can also use extraMin & extraMax.

**Comment by martynasma** [comment]
@workingbuddy10 is right, use `extraMin` and `extraMax` for that.

https://www.amcharts.com/docs/v5/charts/xy-chart/axes/value-axis/#Relative_scope_extension
