### ISSUE TITLE
Passing bullets options with an object -> only last point is displayed

### ISSUE THREAD

**Issue by stla** [amcharts/amcharts5#1415]
Hello,

When creating a point series and setting the bullets options in such a way:
```js
let myOptions = {fill: "blue"}; 
series.bullets.push(function () {
  return am5.Bullet.new(root, {
    sprite: am5.Circle.new(
      root, myOptions
    )
  });
});
```
then there's a problem: only the last point is displayed on the map.

It took me three hours to understand that was the cause and to find a solution:
```js
let myOptions = {fill: "blue"}; 
series.bullets.push(function () {
  return am5.Bullet.new(root, {
    sprite: am5.Circle.new(
      root, {...myOptions}
    )
  });
});
```
I can do a fiddle if you want. Would be worth to mention this point in the docs.

**Comment by martynasma** [comment]
Thanks for sharing your solution.

Yes, different objects cannot share the same settings object, so it needs to be a copy.
