### ISSUE TITLE
Live Stock Chart Not Working In Amcharts 5

### ISSUE THREAD

**Issue by kirannarwade** [amcharts/amcharts5#1416]
We have 1 feature in our web application its 1D Data, so we have show live chart data with web socket live data, yesterday is working properly but today im checking the data of live chart then the chart is not showing its getting amcharts 5 error in index.js file in console.

please fix that issue because its urgent and already its live website.
im also sharing the screenshot and also sending error please rectify asap.

index.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'get')
    at index.js:1:166139
    at Module.o (index.js:1:225858)
    at h._calculateAggregates (index.js:1:165168)
    at h._prepareChildren (index.js:1:164002)
    at h._prepareChildren (xy.js:1:146272)
    at h._prepareChildren (xy.js:1:114001)
    at index.js:1:84709
    at Array.forEach (<anonymous>)
    at Ae._runDirties (index.js:1:84607)
    at Ae._renderFrame (index.js:1:85684)

![Screenshot from 2024-03-21 11-15-53](https://github.com/amcharts/amcharts5/assets/90048456/0d23529d-c359-48f5-872c-5e82cce9a605)

![Screenshot from 2024-03-21 11-06-02](https://github.com/amcharts/amcharts5/assets/90048456/46672748-f37f-49a8-95b6-31c4fa823f48)

please check buddy....

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by kirannarwade** [comment]
<script src="https://cdn.amcharts.com/lib/5/index.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/xy.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/stock.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/themes/Animated.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/themes/Micro.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/themes/Dark.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/plugins/exporting.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/themes/Responsive.js"></script>



    we have used this cdn files in our project,
    and our company also purchased the amcharts 5 stock chart licences from amcharts

    so the error is given from index.js file

    day 1 before i also told you tooltip OHLC data is not getting suddenly
    but now its working properly as previous without changing any code..

    so i want to inform you in your side there some bugs about live charts ...

    please check it buddy and inform me asap, beacuse its already live website...

**Comment by martynasma** [comment]
I'm afraid we cannot check it because we don't have a live chart to test with.

If you cannot provide it here, please contact our support at contact@amcahrts.com

**Comment by kirannarwade** [comment]
switch(ev.originalEvent.target.text) {
                case '1D':
                    g_flg_1DClick = true;
                    if(document.getElementById('search_comp_name').value == ""){
                        alert("Please enter company name");
                        $("#search_comp_name").val(arr_searchBox[currentChartID])
                        arr_dateAxis[currentChartID].zoom(0, 1, 0);
                        $("#periodicity_toolbox"+idx).find(".am5stock-link").each(function(){
                            var $this = $(this);
                            $this.removeClass('am5stock-active')
                        });
                        return false;
                    }


                    arr_storeTempStockSeriesData[currentChartID] = arr_stockChart[currentChartID].get("stockSeries").data._values
                    arr_storeTempVolumeSeriesData[currentChartID] = arr_volumeSeries[currentChartID].data._values
                    arr_storeStartDate[currentChartID] = f_start_date
                    arr_storeEndDate[currentChartID] = f_end_date
                    arr_dateAxis[idx].set('baseInterval', {
                        "timeUnit": "minute",
                        "count": 1
                    })
                    arr_volumeDateAxis[idx].set('baseInterval', {
                        "timeUnit": "minute",
                        "count": 1
                    })
                    start_date = document.getElementById('end_date').value
                    end_date = document.getElementById('end_date').value


                    $('#data_periodicity').val('15Mlive');
                    $("#corporate_events").hide();
                    toolbar4._settings.controls[0].hide()



                    document.getElementById("start_date").disabled = true;
                    document.getElementById("end_date").disabled = true;
                    document.getElementById("1D_small_id").innerHTML = txt_note_live;
                    
                    $("#date_span_id").removeClass("date-block span");
                    document.getElementById("date_span_id").style.fontSize = "10px";
                    document.getElementById("showTimer").style.fontSize = "10px";
                    document.getElementById("1D_small_id").style.fontSize = "10px";

                    //document.getElementById("data_periodicity").disabled = true;

                    $('#start_date').val(start_date.split('-').join('-'));
                    {% comment %} arr_stockChart[currentChartID].get("stockSeries").data.setAll([])
                    arr_volumeSeries[currentChartID].data.setAll([]); {% endcomment %}
                    //searchCompany(this);
                    {% comment %} //setInterval(getDelayedData, 5000); {% endcomment %}
                    if(g_flg_live == false){
                        searchCompany(this)
                        connectToServer(g_layout_name);
                    }
                    else{
                        searchCompany(this)
                    }


                    arr_g_flg_live[currentChartID] = true 


                    t_arr_last_candle_time[currentChartID] = new Date(arr_last_candle_time[currentChartID]).getMinutes()
                    t_arr_last_candle_volume[currentChartID] = arr_last_candle_volume[currentChartID]
                    st_control(ev.originalEvent.target.text, 'Period Selector')


                    // let tmp_last_date = new Date(arr_valueSeries[currentChartID].data._values[arr_valueSeries[currentChartID].data._values.length-1].DATE).toISOString().slice(0,10)
                    // $('#start_date').val(tmp_last_date.split('-').join('-'));
                    // searchCompany(this)
                    

                    break;

This is our case '1D' code here

**Comment by martynasma** [comment]
I'm afraid that does not help.

We will need a reproduction case, which we can run, in order to be able to investigate.

**Comment by kirannarwade** [comment]
buddy its big project, its frontend backend database live project how i can give you whole project

**Comment by martynasma** [comment]
I understand. If it was possible to figure out the issue from the screenshots and snippets you provided, we would do that.

As it stands, it's not possible, I'm afraid.

If you can distill the issue to a specific action, I suggest you take a basic example and build a reproduction case which is smaller and thus runnable in an isolated environment for us to test.

Also, are you using our CDN to load the libraries?

If so, you can downgrade to use earlier version in production, until this is resolved.

More details here:
https://www.amcharts.com/download/#versions

**Comment by kirannarwade** [comment]
i think its problem from your side of am5stock.PeriodSelector this function because some time its working and some time not working in PeriodSelector switcher.  because we have same functionality from dropdown menu its working from there
im sharing you screenshot

![Screenshot from 2024-03-21 15-25-08](https://github.com/amcharts/amcharts5/assets/90048456/a0ce2646-00ae-47dc-8418-34bf29e2358b)

**Comment by martynasma** [comment]
I don't see a PeriodSelector in your screenshot. You must be using it as a standalone item

Can you verify that it is indeed PeriodSelector that causes the issue? The error stack you posted before does not seem like related to it.

**Comment by kirannarwade** [comment]
i said this because 

valueSeries.on("tooltipDataItem", function(tooltipDataItem){
            try{
                $('#drag_company_name').html(arr_h_search_comp_name[currentChartID])
                $('#drag_open').html(tooltipDataItem.get("openValueY"))
                $('#drag_high').html(tooltipDataItem.get("highValueY"))
                $('#drag_low').html(tooltipDataItem.get("lowValueY"))
                $('#drag_close').html(tooltipDataItem.get("valueY"))
                //$('#drag_date').html(tooltipDataItem.get("valueX"))
                var dateX = new Date(tooltipDataItem.get("valueX"))
                $('#drag_date').html(('0' + dateX.getDate()).slice(-2) + '-' + dateX.toLocaleString('en-us', { month: 'short' }) + '-' + dateX.getFullYear() )
              }
              catch(err){

              }
        })


you gave this code for getting OHLC values last year but suddenly not working for 1 day after 1 day its working automatically, thats why in your side issue im telling you

**Comment by martynasma** [comment]
OK, so what exactly is not working?

1) `tooltipDataItem` change event does not kick in?
2) Data item does not contain some values, like `"lowValueY"?
3) Something else?

Does this happen always, or after something you do on your chart to manipulate it? If so, what?

Are you using the latest version (5.8.6)? Have you cleared your browser cache? Does it work if you go down a version, e.g. to 5.8.5?

**Comment by kirannarwade** [comment]
i said tooltip is working since last year but right now past 1 day working is stopeed but automatically start tooltip functionality.

thats why PeriodSelector also bug from your side. please check

**Comment by kirannarwade** [comment]
im using amcharts 5 cdn how can i check the version of amcharts 5 and which version i should be used?

**Comment by martynasma** [comment]
If you are using CDN, you are using the latest version (5.8.6). Just to be sure clear your browser cache.

Previous versions are also available in CDN using URL syntax like this:

```
<script src="https://cdn.amcharts.com/lib/version/5.8.5/index.js"></script>
```

You can update the reset of the resource URLs as well.

Let us know if going back to 5.8.5 fix the issue for you.

Also, since you cannot seem to be able to provide repro case for testing, we will need more details about your issue, not just "it stopped working".

**Comment by kirannarwade** [comment]
not solved by replacing <script src="https://cdn.amcharts.com/lib/version/5.8.5/index.js"></script> this from  <script src="https://cdn.amcharts.com/lib/5/index.js"></script>

**Comment by martynasma** [comment]
Have you replaced all files including `xy.js` and `stock.js`?

**Comment by kirannarwade** [comment]
i replaced only <script src="https://cdn.amcharts.com/lib/5/index.js"></script> this line from my html import in top

**Comment by martynasma** [comment]
Please replace all amCharts files you are using to version-based.

```
<script src="https://cdn.amcharts.com/lib/version/5.8.5/index.js"></script>
<script src="https://cdn.amcharts.com/lib/version/5.8.5/xy.js"></script>
<script src="https://cdn.amcharts.com/lib/version/5.8.5/stock.js"></script>
```

**Comment by kirannarwade** [comment]
Thank You So Much Buddy, Now its Working Properly
Thanks once again !!!

**Comment by martynasma** [comment]
I'm glad previous version is working for you.

However, the core issue is there and will be there moving forward.

So, if you would like to solve it, I'm going to need some more details on what you are doing to reproduce it.
