### ISSUE TITLE
Issue while using pancancelled event in stock chart.

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1417]
I am using pancancelled event for on-demand loading like this :
```
    let wheelTimeout;
    let skipNextPanEnded = false; // Flag to indicate whether to skip the next panended event
   
    const $this = this;
   
    const handleOnDemandDataLoading = () => {
      if (this.dateAxis.get("start") > 0) return;

      if (wheelTimeout) {
        wheelTimeout.dispose();
      }
     
      wheelTimeout = this.dateAxis.setTimeout(function () {
        $this.root.dataStore.requestMoreData($this);
      }, 50);
    };
   
    mainPanel.events.on("panended", function() {
      if (!skipNextPanEnded) { // Check if we should skip the next panended event
        handleOnDemandDataLoading();
      }
      skipNextPanEnded = false; // Reset the flag
    });
   
    mainPanel.events.on("pancancelled", function() {
      // Set the flag to skip the next panended event
      skipNextPanEnded = true;
    });
```

Issue 1 :

Tried doing by the above approach but now my chart jumps like this whenever we load the data via panning :

https://github.com/amcharts/amcharts5/assets/137867461/4c32c4a1-a232-45b4-b975-0d4add8c5966

my valueAxis is set to autoZoom True.

Issue 2 :

After adding the panning via the above approach, when we zoom-in/out the it shows blank space or sometimes candlesticks/ volume candles looks like covered by something:
- it mainly happens when you first you zoom-out then try to zoom-in.

 

https://github.com/amcharts/amcharts5/assets/137867461/62a668a7-94ae-4316-ab3e-8add0909da4d

![image](https://github.com/amcharts/amcharts5/assets/137867461/8e27bef3-1700-41d4-bbf1-95d214cc799d)

![image](https://github.com/amcharts/amcharts5/assets/137867461/b908d191-4844-416f-a9f8-f33ebe1ce259)

For more reference you can refer #1408

**Comment by martynasma** [comment]
I'm not entirely sure, how is this related to "pancancelled" event?

**Comment by workingbuddy10** [comment]
I'm also not very sure why this is happening, but when I remove the above given code then everything works fine. Just don't won't be loading via panning.

Any possible things to look around which Might be causing this, any config of valueAxis or DateAxis etc.
@martynasma

**Comment by workingbuddy10** [comment]
And also I have to remove this feature because you have improved the pancancel event in version 5.8.6, but now I can't use that. As it is causing severe lag in the app.

As mentioned in #1421

**Comment by martynasma** [comment]
We'll need a repro case to test.

**Comment by workingbuddy10** [comment]
@martynasma Can you provide any codepen link which includes data loading via panning + wheel on some random data?

Using StockChart. ( not XYChart). 

Though I have test it, Maybe I am doing anything wrong and can test it on the codepen which you provide. That would be a great help.

**Comment by martynasma** [comment]
I'm afraid I don't have such a ready-made demo.

That said, I just verified that pancancelled/panended combp I suggested works on a basic StockChart to work around the basic clicking on the chart.

**Comment by workingbuddy10** [comment]
After switching to latest package it is working for me also.
