### ISSUE TITLE
Error when integrating amcharts5 in a R Shiny application

### ISSUE THREAD

**Issue by stla** [amcharts/amcharts5#1419]
Hello,

I've done a R package which wraps **amCharts5**. I can display a chart without any problem, except in a Shiny application. Shiny is a web framework for R. When I run my application, I get this error:

![amMapChart1](https://github.com/amcharts/amcharts5/assets/4466543/ea5bc37a-37fe-4781-937e-72d1c343ea4e)

here is where it happens:

![amMapChart2](https://github.com/amcharts/amcharts5/assets/4466543/0a8476e2-1b01-4a8a-b833-49ee10a1fd8d)

Would you have an idea of the cause? I know this is a rather vague question, sorry. Is there a possible conflict with **jQuery**?

**Comment by martynasma** [comment]
I'm afraid we're not familiar with Shiny framework.

> Is there a possible conflict with jQuery?

There is no conflict with jQuery.

Neither jQuery nor amCharts are intrusive and modify universal global objects.

We have had no reports of any issues with jQuery, including the fact that it is used in amcharts.com website.

**Comment by stla** [comment]
Ok, thank you for answering.
