### ISSUE TITLE
Combining separator, decimals and percents in the chart numberFormatter dos not yield the expected result

### ISSUE THREAD

**Issue by BuduMcKinsey** [amcharts/amcharts5#142]
Bug description

When trying to combine thousands separator, decimals and percents for the numberFormatter the result is not the one expected.
Example:
Take the number 50
For format '#%' this becomes => 5000%
For '#,##%' => 5,000%
For '#,##.##' you would expect the value to still be 5,000% or at least display 5,000.00%, but the actual value returned is '50,00%'

JSFiddle with edited yAxis numberFormat
https://jsfiddle.net/xj9s078c/

**Comment by martynasma** [comment]
Actually, for thousand separators you would need "#,###".

`"#,###.##%"` works as expected.
