### ISSUE TITLE
Setting a treemap node value to something other than the sum of its children's values seems to break things

### ISSUE THREAD

**Issue by c-ody** [amcharts/amcharts5#1422]
**Bug description**

1. Set every node in a Treemap to have a value, rather than just the end nodes, and the value is the sum of its children's values.
2. Pick a parent node that would normally have a large value, and hardcode it to something smaller.
3. I would expect that since the node has a small value, and small size, it's positioned towards the bottom right with the other smaller rectangles. But instead, it's positioned near where it would be if it had its actual larger value (the sum of its children's values).
4. Also, clicking into that Treemap node no longer displays the children correctly.

I'm trying to limit the number of nodes shown in a level of the treemap, and stuffing the rest inside a small "Other" node towards the bottom right. But my "Other" node is being rendered towards the top left instead of the bottom right, presumably due to the large sum of its children's values. And clicking the "Other" node does not properly show all its children, as though it's trusting the value of the parent to be the sum of the values of its children. If this isn't a bug, is there a way to achieve what I'm wanting?

For a minimal example, I took your demo Treemap (https://www.amcharts.com/demos/drill-down-treemap/), gave every node a value instead of just the end nodes, and hardcoded Ford to have a value of 100,000, but Ford continues to appear towards the top left instead of with the smaller rectangles in the bottom right. I also tried reversing the list, but that wasn't it. https://jsfiddle.net/s7h6y4ju/

**Comment by zeroin** [comment]
Tree map only works fine with values set on last child nodes, I am afraid we are not going to change this behavior.
