### ISSUE TITLE
Stockchart Moving Average indicator legend text shows 0.00 for very small values

### ISSUE THREAD

**Issue by VRciF** [amcharts/amcharts5#1425]
**Question**

I've created an example, https://jsfiddle.net/wdLrbjvx/, which is basically a copy of https://codepen.io/team/amcharts/pen/jOzvvMM.  

In my example, I've divided the test data by a factor `1000000` at the very bottom to get small values, similar to some crypto currencies.  
The custom `My Indicator` correctly shows the small values in the legend text.  
But the `Moving Average` indicator

```
        var movingAverage7 = stockChart.indicators.push(am5stock.MovingAverage.new(root, {
            stockChart: stockChart,
            stockSeries: valueSeries,
            legend: valueLegend,
            period: 7,
            seriesColor: am5.color(0xff9900),
            numberFormatter: am5.NumberFormatter.new(root, {
              "numberFormat": "###,###,##0.00000000"
           })
        }));
```
Just shows `0.00`. Removing the `numberFormatter` does not change anything.  
The moving average indicator line is drawn correctly, but the legend values are wrong. I assume this is related to the number formatter, but I don't get it working correctly.  
Maybe I need to modify another numberFormatter of another series from the movingAverage indicator? Some legendText magic?

**Environment (if applicable)**

Browser Firefox 122.0, amcharts 5 cdn

--------------------------------------

Any help would be appreciated. Many thanks.

**Comment by zeroin** [comment]
Precision of the legend value is set in StockChartDefaultTheme, `legendValueText` setting. As you don't have a reference to the moving average series before it's created by user, the best way to solve your issue would be creating a custom theme:

```
var root = am5.Root.new("chartdiv");

var myTheme = am5.Theme.new(root);

myTheme.rule("LineSeries", ["movingaverage"]).setAll({
  legendValueText: "[{seriesColor} bold]{valueY.formatNumber('#.00000')}[/]"  
})

// Set themes
// -------------------------------------------------------------------------------
// https://www.amcharts.com/docs/v5/concepts/themes/
root.setThemes([
  am5themes_Animated.new(root),
  myTheme
]);
```

https://codepen.io/team/amcharts/pen/MWRoeqW
