### ISSUE TITLE
Linear gauge

### ISSUE THREAD

**Issue by HASSANDL** [amcharts/amcharts5#143]
Have amcharts5 linear gauge?

![image](https://user-images.githubusercontent.com/22093903/145969876-1323e6bb-d9a7-4bf1-873e-187eec8860d1.png)

![image](https://user-images.githubusercontent.com/22093903/145969944-27970ca0-af24-4269-9c71-9484e524e964.png)

**Comment by martynasma** [comment]
This looks like something achievable using simple `XYChart`.

Examples:
https://www.amcharts.com/demos/range-bullet-chart/
https://www.amcharts.com/demos/spectrum-chart/
https://www.amcharts.com/demos/progress-chart/
https://www.amcharts.com/demos/bullet-chart/
