### ISSUE TITLE
Treemap - variable visible depth + drilldown capabilities 

### ISSUE THREAD

**Issue by btbritz** [amcharts/amcharts5#1430]
Using this demo as a reference: https://www.amcharts.com/demos/multilevel-tree-map/  Ignore the container controls.

You can visibly see more of the child breakdowns because initalDepth is set to 2 however you can't drill into that first level to expand the 2nd level to animate and take up container like in this demo: https://www.amcharts.com/demos/drill-down-treemap/

I'm basically looking for a hybrid of both demos. One where I can visibly see the all the breakdown of children but still drill into sections if need be.

Right now I currently have 2 treemap series that are laying on top of one another while toggling rectangle opacity to get the above desired effect - super hacky and doesn't seem like the best experience.

**Comment by zeroin** [comment]
I updated the original demo so that it would do the thing: https://www.amcharts.com/demos/multilevel-tree-map/
To make it work, I added:

```
series.nodes.template.events.on("click", function (ev) {
  var depth = ev.target.dataItem.get("depth");
  if(depth == 2){
     series.selectDataItem(ev.target.dataItem.get("parent"));
  }
})
```

Also changed:
```
    downDepth: 2,
    upDepth: 0
```

**Comment by btbritz** [comment]
This is great! Thanks!
