### ISSUE TITLE
conditional grid stroke and prevent auto correction of grid lines?  (AmCharts v5)

### ISSUE THREAD

**Issue by binaryartifex** [amcharts/amcharts5#1431]
**Question**

is it possible to change the style of the stroke for the x axis from line to dashed when its above or below a certain value? further to this, is it possible to keep the lines that are lined up with the datums fixed in place? the lines adjust when the screen reduces or expands too much. Ive added a photo below to illustrate. Ive scoured the adapter options for the xAxis but there's no reference to any x axis values, and the series based adapters i can't find any reference back to the xaxis itself to make the change... 

![image](https://github.com/amcharts/amcharts5/assets/68464707/bfa2ced3-efac-4b41-9311-c63e40de86cc)

**Comment by martynasma** [comment]
> is it possible to change the style of the stroke for the x axis from line to dashed when its above or below a certain value?

Not with a grid line. But I suppose you can achieve this effect with a bullet. Here's an example:
https://www.amcharts.com/docs/v5/tutorials/using-bullets-to-apply-styling-to-grid-under-series/

> further to this, is it possible to keep the lines that are lined up with the datums fixed in place? the lines adjust when the screen reduces or expands too much. 

I'm not entirely sure I understand this question. In your screenshot everything seems to be lined up perfectly 🤔

**Comment by binaryartifex** [comment]
im surprised that demo got away from me, cheers for that i think thats perfect. yeah for the other issue ive attached another photo of the actual interface im working on. i think the dates clipping out has somehting to do with the min spacing between axis labels or something but the axis lines themselves, are they coupled to the rendering of the labels or can i at least force them not to move? you can actually see the exact same issue happen [in this amcharts demo](https://www.amcharts.com/demos/line-with-custom-bullets/)

![image](https://github.com/amcharts/amcharts5/assets/68464707/772c5b16-b392-459b-9962-78085e938571)

**Comment by binaryartifex** [comment]
all good mate. minGridDistance was indeed the culprint. cheers for your help.

**Comment by martynasma** [comment]
> im surprised that demo got away from me, cheers for that i think thats perfect.

Don't beat yourself up. I just posted it right before I replied to you 😉
