### ISSUE TITLE
Is it possible to show labels outside the chart? 

### ISSUE THREAD

**Issue by jiwonmik** [amcharts/amcharts5#1432]
**Question**

<img width="431" alt="image" src="https://github.com/amcharts/amcharts5/assets/59993029/1c9fb675-7fbc-4083-aa45-9be844fc305e">

I saw some tutorials or examples that show labels 'inside the chart', but as in the image, I want to show labels "outside the chart". 
Is it doable? Seems like we can do it with Pie chart, but I want to apply it in Line chart. 
<img width="753" alt="image" src="https://github.com/amcharts/amcharts5/assets/59993029/69108b4b-2748-4336-a1b2-4ec5acb79377">

If it's so, please let me know how. 
[CodePen](https://www.amcharts.com/demos/highlighting-line-chart-series-on-legend-hover/)

**Environment (if applicable)**
amCharts version: 5
Related frameworks: Typescript

**Additional context**

**Comment by martynasma** [comment]
Technically, you could display a bullet at the end of each series, like here:
https://www.amcharts.com/docs/v5/concepts/common-elements/bullets/#selectively-displaying-bullets

However, series that have similar values, would have their labels overlap. There's no way to make them space out so they do not overlap.

**Comment by jiwonmik** [comment]
Yeah that's the one I implemented right now, but I was curious if there's a way we can show label outside the chart as in the above attached image.

Good for now, thank you
