### ISSUE TITLE
Venn Diagram, set not being represented on screen

### ISSUE THREAD

**Issue by KhalilMensi** [amcharts/amcharts5#1433]
Hi.. am using Venn Diagram to display some sets on it.. some are being displayed good and for some i got this warning: 

WARNING: area .. not represented on screen

from what i saw in some posted questions on an other site it maybe caused by the lossFunction, got this : https://github.com/benfred/venn.js/pull/114

is there any configuration parameter or setting in amcharts5 which helps to solve this issue and represent all the sets plz ?

Thnx

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by KhalilMensi** [comment]
Hi.. here is the js fiddle https://jsfiddle.net/6qzgay73/1/
this set is not being rendered:
        {
            "count": 2,
            "name": "",
            "sets": [
                "Professional, Business & Support Services",
                "Construction",
                "Computing, Technology, Robotics & AI"
            ]
        },

**Comment by martynasma** [comment]
Thanks. Unfortunately, there's nothing we can do about it.

We're using external library for Venn, and don't have any influence on how it outputs the intersections.

Some Venn intersection setups are hard to plot, and some are unplottable.

I'm not sure which one it is, but at this time we won't be able to provide a solution, I'm afraid 🙁
