### ISSUE TITLE
How to set `extraMax` with absolute value

### ISSUE THREAD

**Issue by jiwonmik** [amcharts/amcharts5#1434]
**Question**
<img width="817" alt="image" src="https://github.com/amcharts/amcharts5/assets/59993029/ca7aa6b3-c020-4e71-b024-1545b18a1dd9">

Is it possible to set `extraMax` with absolute value? 

**Environment (if applicable)**
amCharts version: 5
Related frameworks: Typescript

**Additional context**

**Comment by martynasma** [comment]
Hi there,

I'm afraid there's no setting that would allow "extra*" as an absolute value.

**Comment by jiwonmik** [comment]
Hmm then is there another way to extend the x-axis scope with absolute value (without using 'extraMax'?)

I'm asking because I want to give extend it because the my chart's width is not a fixed value but it changes dynamically.

**Comment by martynasma** [comment]
Well, maybe recalculate `min` and `max` every time private value of `selectionMin` and `selectionMax` changes on the axis.

Does that make sense?
