### ISSUE TITLE
Treemap - Series bullet labels don't truncate relative to 

### ISSUE THREAD

**Issue by btbritz** [amcharts/amcharts5#1435]
For the following:

```
treemapSeries.bullets.push(function (root, series, dataItem) {
        let depth = dataItem.get('depth');
        if (depth == 1) {
            myLabel = am5.Label.new(root, {
                centerX: am5.percent(0),
                height: am5.percent(100),
                width: am5.percent(100), // width of parent, in this case a node?
                dx: 15,
                dy: 15,
                text: dataItem.dataContext.name,
                oversizedBehavior: 'truncate',
                layer: 3
            })
    
            return am5.Bullet.new(root, {
                locationX: 0,
                sprite: myLabel 
            });
       }
    }
});
```

Firstly, the only way I could get the label in the upper left of a treemap "grouping" was to monkey with a bunch of height/width/location settings. Shouldn't there be a way to move a bullet (absolute wasn't working) to the upper left of a grouping of nodes without doing all of that?

Secondly, I would expect a bullet with a sprite of a Label to truncate if the label text exceeds the width of it's relative parent. In this case the bullet width itself. What Am I doing wrong here?

**Comment by martynasma** [comment]
The `oversizedBehavior: truncate` works against `maxWidth`, not `width`.

Unfortunately, `maxWdith` accepts only absolute values, so `am5.p100` won't do.

Here's a workaround using events:

```JavaScript
series.bullets.push(function (root, series, dataItem) {
  let depth = dataItem.get("depth");
  if (depth == 1) {
    let myLabel = am5.Label.new(root, {
      centerX: am5.percent(0),
      height: am5.percent(100),
      maxWidth: 100,
      dx: 15,
      dy: 15,
      text: dataItem.dataContext.name,
      oversizedBehavior: "truncate",
      layer: 3
    });
    
    myLabel.set("maxWidth", dataItem.get("rectangle").width() - 20);
    dataItem.get("rectangle").set("userData", myLabel);
    dataItem.get("rectangle").on("width", function(width, target) {
      target.get("userData").set("maxWidth", width - 20);
    });

    return am5.Bullet.new(root, {
      locationX: 0,
      sprite: myLabel
    });
  }
});
```

**Comment by btbritz** [comment]
Thanks! I'll try it out.

**Comment by btbritz** [comment]
Worked great btw.

**Comment by martynasma** [comment]
> Question: What would I need to do to get a tooltip to show up on that Label? I'm thinking because of the hight it might not be possible?

https://www.amcharts.com/docs/v5/concepts/common-elements/labels/#labels-as-interactive-elements
