### ISSUE TITLE
Feature request: horizontally scrolling chart legend

### ISSUE THREAD

**Issue by theoturner** [amcharts/amcharts5#1436]
It's possible to add vertical scrolling to chart legend:
```js
am5.Legend.new(root, {
  y: am5.percent(0),
  x: am5.percent(0),
  height: am5.percent(50),
  layout: root.verticalLayout,
  verticalScrollbar: am5.Scrollbar.new(root, {
    orientation: "vertical"
  })
})
```

It would be nice to have a horizontal scrolling option for charts with many different series, such that they could be rendered as a single line along the top. Notably, using the below does not achieve this:
```js
am5.Legend.new(root, {
  y: am5.percent(0),
  x: am5.percent(0),
  height: am5.percent(50),
  layout: root.horizontalLayout,
  verticalScrollbar: am5.Scrollbar.new(root, {
    orientation: "horizontal"
  })
})
```
Here the horizontal layout is rendered in full, overflowing the right side of the chart and not allowing any scroll.

**Comment by martynasma** [comment]
It can be achieved using [external legend](https://www.amcharts.com/docs/v5/concepts/legend/#external-container). Here's an example:

https://codepen.io/team/amcharts/pen/abxJvOB?editors=0010

**Comment by theoturner** [comment]
It would be nice to have without using an external legend, because:
1. Its within the canvas, which looks neat
2. External legends only seem to work with non-stock charts

**Comment by martynasma** [comment]
I understand that it would be nicer to have an internal horizontally-scrollable legend, but at this time we are not planning on implementing this feature, I'm afraid.

**Comment by theoturner** [comment]
OK, thank you for the fast response
