### ISSUE TITLE
Interval tree implemention with a Line Chart

### ISSUE THREAD

**Issue by anipr2002** [amcharts/amcharts5#1437]
**Question**

Given a set of datasets with a start date and end date, is there a way to plot this on a line chart? The x-axis is the Time range axis and y axis is the frequency of intervals which intersect at a given time. 

![image](https://github.com/amcharts/amcharts5/assets/131559231/aa659144-daa6-4902-822b-88c0c8d8bde1)
This is a very basic example. 

**Environment *

Amchart version : 5
Framework : React/Typescript

**Comment by martynasma** [comment]
This looks like a very basic floating bar chart, e.g.:
https://www.amcharts.com/demos/gantt-chart-dates/

You can make the columns thin by setting their absolute `height` value:
https://www.amcharts.com/docs/v5/charts/xy-chart/series/column-series/#Column_width

You can also add the dashed line as regular LineSeries.

**Comment by anipr2002** [comment]
Maybe I did not explain it the right way. I figured it out. 

[https://codesandbox.io/p/sandbox/amchart-test-dwj2rl?file=%252Fsrc%252Findex.mjs](Code Sandbox)
