### ISSUE TITLE
Can I remove the empty spaces between on the graphics with the inbuilt amcharts5 tools? 

### ISSUE THREAD

**Issue by vskorop** [amcharts/amcharts5#1438]
Hello!
So, I have some data which I have to show with amcharts5.

I have two options: with setTimeout for "cutting" spaces and zoom chart to min-max values of my line, and same without setTimeout. 
This seems like bad practice.
Can I do this using amcharts5's tools?

CodeSandbox example is here: (https://codesandbox.io/p/devbox/amcharts5-tooltip-issue-vzw2tz?embed=1&file=%2Fsrc%2FApp.tsx%3A15%2C1)

amCharts version: 5.8.2 or 5.8.4,
Google Chrome: v122.0.6261.69 or later,
Related frameworks and their versions are [React: 18.2.0, effector: 23.2.0]
Thanks.

**Comment by martynasma** [comment]
If you're looking for an event for when the data is ready, series' `datavalidated` should be the one you use:

https://www.amcharts.com/docs/v5/reference/xyseries/#datavalidated_event

**Comment by vskorop** [comment]
Thanks for response!
In my case, I don't want to use events. I'm looking to set my chart wide from min to max at once. But if it isn't possible, yes I should use `event.on('datavalidated', ...)`

**Comment by vskorop** [comment]
Yes, you got that right. 

I updated my code in the code sandbox by adding lines: 

```
   series.events.on("datavalidated", (event) => {
        const firstItem = event.target.data.values[0];
        const lastItem =
          event.target.data.values[event.target.data.values.length - 1];

        if (
          isValidChartDataRecord(firstItem) &&
          isValidChartDataRecord(lastItem)
        ) {
          xAxis.set("min", firstItem.x);
          xAxis.set("max", lastItem.x);
          xAxis.zoomToValues(firstItem.x, lastItem.x);
        }
      });
```
But I still can't get pre-zoom to actual values. Maybe I do something wrong?

**Comment by vskorop** [comment]
@zeroin Hi! I've already updated codesandbox example with "datavalidated" event. 

Could you look, please?
[CodeSandbox example is here](https://codesandbox.io/p/devbox/amcharts5-tooltip-issue-vzw2tz?embed=1&file=%2Fsrc%2FApp.tsx%3A15%2C1) (from 126 line in useFeatureChart.ts)

**Comment by vskorop** [comment]
@martynasma Yes it works, thanks a lot!
