### ISSUE TITLE
Base interval of stock chart.

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1441]
Generating 5 minute format random data as given by amchart example, just made a small tweak that instead of generating 1 minute format candles I am generating 5 minute format candles.
I have also changed the count to 5 in base interval.

The candles are overlapping.

you guys can try out : https://codepen.io/Ansh-m-the-reactor/pen/GRLyVqN

I believe this "checkChange" is not working in 5 minute format. 
 this line : 

>  if (am5.time.checkChange(date, previousDate, "minute"))

**Comment by anshmishra010** [comment]
Oh, sorry about that.

But checkChange should work to find if two timestamp are 5 minutes in interval, right?

if yes, where is it fetching count of 5, because we can get interval `minute`

**Comment by anshmishra010** [comment]
Oh, sorry about that.

But checkChange should work to find if two timestamp are 5 minutes in interval, right?

if yes, where is it fetching count of 5, because we can get interval `minute`

**Comment by workingbuddy10** [comment]
Oh, sorry about that.
 
But checkChange should work to find if two timestamp are 5 minutes in interval, right?
 
if yes, where is it fetching count of 5, because we can get interval `minute`

**Comment by martynasma** [comment]
`am5.time.checkChange()` function does not work with time unit increments.

**Comment by p3777dev** [comment]
So how can I show 5 minute interval Live (streaming) data ?
if the checkChange won't be able to handle count.

@martynasma

**Comment by martynasma** [comment]
I'm sorry, I don't quite get the issue.

If your data comes in 5 minute intervals, all you need is to set DateAxis `baseInterval` accordingly.

**Comment by p3777dev** [comment]
Let's say  I have a timestamp `A` and timestamp `B`. Currently `checkChange` can detect if the timestamps are interval apart (like 1 minute, 1 hour, 1day, etc).

I want to determine if the timestamps are 5 minute or 15 minute or 30 minute apart.

I want to determine this by manually calling `checkChange` and I can pass `timeOne` and `timeTwo`. 
However, there is no option for count. So I assume the `checkChange` can't determine if count is different than 1.

Am I correct? @martynasma 

https://github.com/amcharts/amcharts5/blob/fe09b747651ad3791f15ab7dade6c78116a87c0f/src/.internal/core/util/Time.ts#L165
