### ISSUE TITLE
StockChart + legend does not fill 100% of vertical space

### ISSUE THREAD

**Issue by theoturner** [amcharts/amcharts5#1442]
**Bug description**

When using a stock chart with a legend, the chart will not scale to fill the vertical space if the chart is taller than it is wide.

```js

const root = am5.Root.new("chart-div");
const chart = root.container.children.push(am5stock.StockChart.new(root, {}));
const mainPanel = chart.panels.push(am5stock.StockPanel.new(root, {}));
const yAxis = mainPanel.yAxes.push(
  am5xy.ValueAxis.new(root, {renderer: am5xy.AxisRendererY.new(root, {})})
);
const xAxis = mainPanel.xAxes.push(
  am5xy.DateAxis.new(root, {renderer: am5xy.AxisRendererX.new(root, {})})
);
const legend = chart.children.push(
  am5.Legend.new(root, {x: am5.percent(0), y: am5.percent(0)})
);
const series = mainPanel.series.push( ... );
// Add other series series ...
legend.data.setAll(mainPanel.series.values);
```

![Screenshot 2024-04-04 at 13 51 40](https://github.com/amcharts/amcharts5/assets/10600558/c1798d3e-d3fe-4fa3-b2f4-72e5484e1e9e)

If the legend is removed, the problem is not there. If the chart is wider than it is tall, the problem is also not there.

**Environment**

AmCharts 5.8
Problem exists in latest version of: Chrome, Brave, Firefox, Safari

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
