### ISSUE TITLE
Trend line color differently based on value

### ISSUE THREAD

**Issue by jiwonmik** [amcharts/amcharts5#1444]
**Question**

<img width="1145" alt="image" src="https://github.com/amcharts/amcharts5/assets/59993029/43157a1b-a952-4037-bcc0-3c156553a291">
I want to do something similar to the above, but for "Trend line". 

<img width="1435" alt="image" src="https://github.com/amcharts/amcharts5/assets/59993029/97ef8f4a-793e-4582-8188-a07683f6f038">
As above, I want to color the trend line with 'green' if the data value is above the trend line, and color it "red" if the data value is below the trend line.

This is the [Codepen link](https://codepen.io/pen).

**Environment (if applicable)**
amCharts version: 5
Related frameworks: Typescript

**Additional context**

**Comment by zeroin** [comment]
You can't do that with trend line, but you can add a StepLineSeries to your chart with all the same values, and use a similar aproach to the top example to color segments of a step line series in a way you want.
