### ISSUE TITLE
how to disable the on-demand loading candle zooming

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1445]
https://github.com/amcharts/amcharts5/assets/137867461/4807f818-fce6-48d9-9f90-54715c0b4c91

In the above video you can see in the first half ( which is amcharts) where I am using on-demand loading to load more data, when we load data the candles zoom to certain points. 
Whereas in the second half of video ( different web app) where I am using on-demand /panning to load more data, the candles doesn't zoom and this seem pretty good. 
On every pan I am simply loading 50 data points then lately incrementing the count. 

I am not asking for the same animation for the loading but at least if there is any I can stop this zooming this.  
> my valueAxis autoZoom is set to 0.

I am only doing this for loading data via panning: 
```
    const handleOnDemandDataLoading = () => {
      if (this.dateAxis.get("start") > 0) return;

      if (wheelTimeout) {
        wheelTimeout.dispose();
      }
     
      wheelTimeout = this.dateAxis.setTimeout(function () {
        $this.root.dataStore.requestMoreData($this);
      }, 50);
    };
   
    mainPanel.events.on("panended", function() {
      if (!skipNextPanEnded) { // Check if we should skip the next panended event
        handleOnDemandDataLoading();
      }
      skipNextPanEnded = false; // Reset the flag
    });
   
    mainPanel.events.on("pancancelled", function() {
      // Set the flag to skip the next panended event
      skipNextPanEnded = true;
    });
```

**Comment by workingbuddy10** [comment]
I don't know exactly what it calls, but in the below video you can see in the end it zoomed to the last most recent loaded candle.
And when we load data via panning you can see the candles shakes.

https://github.com/amcharts/amcharts5/assets/137867461/8a469fa5-fc53-4eb3-8141-807239680316

my valueAxis and mainPanel config : 
```
      this.valueAxis.set("autoZoom", false);
      this.valueAxis.set("maxDeviation", 1);
      this.mainPanel.set("panY", true);
      this.mainPanel.events.on("panstarted", () => {
        this.dateAxis.set("maxDeviation", 1)
      });
      this.mainPanel.events.on("panended", () => {
        this.dateAxis.set("maxDeviation", 0)
      });
      this.valueAxis.get("renderer").set("pan","zoom");
```

@martynasma

**Comment by martynasma** [comment]
We can take a look if you could produce a workable reproduction case of your setup. It does not need to be actual data loads, you can simulate it with random data. Once we have something to test on, we can try and figure out the issue for you.
