### ISSUE TITLE
Show only min and max date axis in line chart

### ISSUE THREAD

**Issue by jiwonmik** [amcharts/amcharts5#1446]
**Question**

How can I show only the min and max axis value for date axis? 

<img width="1431" alt="image" src="https://github.com/amcharts/amcharts5/assets/59993029/b79cba37-2d04-40f5-b022-70f3e371734c">

<img width="653" alt="image" src="https://github.com/amcharts/amcharts5/assets/59993029/bd5b7665-3bb7-43a8-9aeb-9201b0b6306e">
Seems like the above is quite related one,, 

**Environment (if applicable)**

amCharts version: 5
Related frameworks: Typescript

**Additional context**

**Comment by martynasma** [comment]
`minPosition`/`maxPostion` won't work in this case.

The two options I see, is:

1) Use axis ranges:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/axis-ranges/

Similar example:
https://www.amcharts.com/docs/v5/tutorials/force-the-last-label-on-a-dateaxis-using-axis-range/

2) Use an adapter on labels to selectively hide them based on their position:

```JavaScript
xAxis.get("renderer").labels.template.adapters.add("visible", function(visible, target) {
  if (target.dataItem) {
    var position = xAxis.valueToPosition(target.dataItem.get("value"));
    if (position < 0.05 || position > 0.95) {
      return true;
    }
  }
  return false;
});
```
