### ISSUE TITLE
How can I show tooltip when data is `null`?

### ISSUE THREAD

**Issue by jiwonmik** [amcharts/amcharts5#1449]
**Question**
<img width="160" alt="image" src="https://github.com/amcharts/amcharts5/assets/59993029/677f7202-40e0-46d0-b461-911fb5a3d6b5">

I created a customized tooltip to show all series values in one tooltip like in the above screenshot.
The thing is that if the last value field data is `null`, it doesn't show tooltip.
The above screenshot shows tooltip because the last value field - which is `f(x)` - data is not null.

Is there any way to force it to show a tooltip even if the data is `null`?

**Environment (if applicable)**
amCharts version: 5
Related frameworks: Typescript

**Additional context**

**Comment by martynasma** [comment]
> Is there any way to force it to show a tooltip even if the data is null?

No, I'm afraid. If there's no data - there's no tooltip 🙁

Why not add tooltip to all series, so that if there's at least one value available, the tooltip will show?

**Comment by jiwonmik** [comment]
Hmm,, no we want to show only one tooltip for each x-axis fields 

Then is it doable to reformat the data field `null` to `N/A` or '' as an empty string? 

From below
```
{
   field1: 10,
   field2: 12,
   field3: null
}
```

to below

```
{
   field1: 10,
   field2: 12,
   field3: 'N/A' or ''
}
```


I tried it but it seems like it's failing to plot a chart.,

**Comment by martynasma** [comment]
Are you using axis or series tooltip?

**Comment by jiwonmik** [comment]
<img width="1006" alt="image" src="https://github.com/amcharts/amcharts5/assets/59993029/715e1aef-86e9-4d6d-b00c-52c529f1290c">
I think it's both ? I'm creating this clustered bar chart.

**Comment by martynasma** [comment]
Can you post what you have so far on CodePen, so it's a bit clearer of what you are trying to do?
