### ISSUE TITLE
[Solved] Tooltips on multiple stacked series are difficult to display 

### ISSUE THREAD

**Issue by bereldhuin** [amcharts/amcharts5#145]
Hi,

I have a graph with multiple stacked series. I set tooltips but when the graph is displayed, it's very hard to make the tooltip show for a specific point on a serie.

I tried to play with stroke witdh and maxTooltipDistance but didn't get any satisfying results.
The best solution would be to display tooltip when hovering over the entire stacked area and not only the line.

Here is a an example : 
[tooltip.html.txt](https://github.com/amcharts/amcharts5/files/7711312/tooltip.html.txt)

Thanks for your help,

Fred

**Comment by martynasma** [comment]
Since you have irregular data, it would make sense to make cursor snap to neareast data items on nearest series.

```JavaScript
cursor.set("snapToSeries", chart.series.values)
```

https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/#Snapping_to_series

**Comment by bereldhuin** [comment]
Once again, a fast and precise answer :-)

Thank you very much.
