### ISSUE TITLE
XY chart cannot have more than two date axis (x-axis)

### ISSUE THREAD

**Issue by Garima-github-24** [amcharts/amcharts5#1451]
Hi,

I am using amcharts 5 to plot comparison graphs using XY chart. I have use cases to implement multiple date axes as well as multiple value axes. While I am able to implement more than 2 values axis for XY chart, more than 2 date axes doesn't seem to work. I tried to create three date axes with single value axis on XY chart. I can see three x-axis getting created but can't see three line series for the same. Looks like it's not possible to create more than 2 date axes for a XY chart. Kindly confirm on the same.

**Comment by martynasma** [comment]
It should be possible.

Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by Garima-github-24** [comment]
Hi,

We tried to create XY chart with 3 date axes using demo example code from https://www.amcharts.com/demos/multiple-date-axes/. Here is the code and the plotted graph

private createAM5Chart(root): void {
    var data = [];
    var price0 = 1000,
      price1 = 1200,
      price2 = 1400;

    for (var i = 0; i < 360; i++) {
      price0 += Math.round(
        (Math.random() < 0.5 ? 1 : -1) * Math.random() * 100
      );
      data.push({ date0: new Date(2015, 0, i).getTime(), price0: price0 });
    }

    for (var i = 0; i < 360; i++) {
      price1 += Math.round(
        (Math.random() < 0.5 ? 1 : -1) * Math.random() * 100
      );
      data.push({ date1: new Date(2017, 0, i).getTime(), price1: price1 });
    }

    for (var i = 0; i < 360; i++) {
      price2 += Math.round(
        (Math.random() < 0.5 ? 1 : -1) * Math.random() * 100
      );
      data.push({ date2: new Date(2019, 0, i).getTime(), price2: price2 });
    }

    // Create root element
    // https://www.amcharts.com/docs/v5/getting-started/#Root_element
    //var root = am5.Root.new('chartdiv');

    // Set themes
    // https://www.amcharts.com/docs/v5/concepts/themes/
    root.setThemes([am5themes_Animated.new(root)]);

    // Create chart
    // https://www.amcharts.com/docs/v5/charts/xy-chart/
    var chart = root.container.children.push(
      am5xy.XYChart.new(root, {
        panX: true,
        panY: true,
        wheelX: 'panX',
        wheelY: 'zoomX',
        pinchZoomX: true,
      })
    );

    // Add cursor
    // https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/
    var cursor = chart.set(
      'cursor',
      am5xy.XYCursor.new(root, {
        behavior: 'none',
      })
    );
    cursor.lineY.set('visible', false);

    // Create axes
    // https://www.amcharts.com/docs/v5/charts/xy-chart/axes/
    var xAxis0 = chart.xAxes.push(
      am5xy.DateAxis.new(root, {
        baseInterval: { timeUnit: 'day', count: 1 },
        renderer: am5xy.AxisRendererX.new(root, {
          minorGridEnabled: true,
        }),
        tooltip: am5.Tooltip.new(root, {}),
        tooltipDateFormat: 'yyyy-MM-dd',
      })
    );

    var xAxis1 = chart.xAxes.push(
      am5xy.DateAxis.new(root, {
        marginTop: 10,
        baseInterval: { timeUnit: 'day', count: 1 },
        renderer: am5xy.AxisRendererX.new(root, {
          minorGridEnabled: true,
        }),
        tooltip: am5.Tooltip.new(root, {}),
        tooltipDateFormat: 'yyyy-MM-dd',
      })
    );

    var xAxis2 = chart.xAxes.push(
      am5xy.DateAxis.new(root, {
        marginTop: 10,
        baseInterval: { timeUnit: 'day', count: 1 },
        renderer: am5xy.AxisRendererX.new(root, {
          minorGridEnabled: true,
        }),
        tooltip: am5.Tooltip.new(root, {}),
        tooltipDateFormat: 'yyyy-MM-dd',
      })
    );

    var yAxis = chart.yAxes.push(
      am5xy.ValueAxis.new(root, {
        maxDeviation: 1,
        renderer: am5xy.AxisRendererY.new(root, { pan: 'zoom' }),
      })
    );

    // Add series
    // https://www.amcharts.com/docs/v5/charts/xy-chart/series/
    var series0 = chart.series.push(
      am5xy.LineSeries.new(root, {
        name: 'Series',
        xAxis: xAxis0,
        yAxis: yAxis,
        valueYField: 'price0',
        valueXField: 'date0',
        tooltip: am5.Tooltip.new(root, {
          labelText: '{valueY}',
        }),
      })
    );

    var series1 = chart.series.push(
      am5xy.LineSeries.new(root, {
        name: 'Series',
        xAxis: xAxis1,
        yAxis: yAxis,
        valueYField: 'price1',
        valueXField: 'date1',
        tooltip: am5.Tooltip.new(root, {
          labelText: '{valueY}',
        }),
      })
    );

    var series2 = chart.series.push(
      am5xy.LineSeries.new(root, {
        name: 'Series',
        xAxis: xAxis2,
        yAxis: yAxis,
        valueYField: 'price2',
        valueXField: 'date2',
        tooltip: am5.Tooltip.new(root, {
          labelText: '{valueY}',
        }),
      })
    );

    // Add scrollbar
    // https://www.amcharts.com/docs/v5/charts/xy-chart/scrollbars/
    var scrollbar = chart.set(
      'scrollbarX',
      am5xy.XYChartScrollbar.new(root, {
        orientation: 'horizontal',
        height: 60,
      })
    );

    var sbDateAxis = scrollbar.chart.xAxes.push(
      am5xy.DateAxis.new(root, {
        baseInterval: {
          timeUnit: 'day',
          count: 1,
        },
        renderer: am5xy.AxisRendererX.new(root, {
          minorGridEnabled: true,
        }),
      })
    );

    var sbValueAxis = scrollbar.chart.yAxes.push(
      am5xy.ValueAxis.new(root, {
        renderer: am5xy.AxisRendererY.new(root, {}),
      })
    );

    var sbSeries = scrollbar.chart.series.push(
      am5xy.LineSeries.new(root, {
        valueYField: 'price0',
        valueXField: 'date0',
        xAxis: sbDateAxis,
        yAxis: sbValueAxis,
      })
    );

    series0.data.setAll(data);
    series1.data.setAll(data);
    series2.data.setAll(data);
    sbSeries.data.setAll(data);

    // Make stuff animate on load
    // https://www.amcharts.com/docs/v5/concepts/animations/
    series0.appear(1000);
    series1.appear(1000);
    series2.appear(1000);
    chart.appear(1000, 100);
  }

![image](https://github.com/amcharts/amcharts5/assets/163392636/91b8d3b1-db53-4d9a-a1fc-400f38500b29)

**Comment by martynasma** [comment]
Thanks.

No sure why that demo was implemented that way, but it does not seem right.

If series do not share the same time span, it's better to have separate data arrays for each of them.

The demo has been updated:
https://www.amcharts.com/demos/multiple-date-axes/

Please follow the code to add more series/axes.
