### ISSUE TITLE
Show last label on CategoryAxis

### ISSUE THREAD

**Issue by roman-gorkunenko** [amcharts/amcharts5#1453]
Hello.  For example, there is such a line chart

https://codepen.io/Roman-Gorkunenko-the-flexboxer/pen/ExJLdMV

How can I make labels where the min and max values on the X axis appear on the chart?
The last label on the chart is Year 2033, the last label is Year 2034. In xAxis.dataItems this is the last value, `visible: true` cannot be set
via `xAxis.get("renderer").labels.template.adapters.add("visible")` also does not work because this label is not there.

You have such an example
https://www.amcharts.com/docs/v5/tutorials/force-the-last-label-on-a-dateaxis-using-axis-range/
but selectionMax will not be in this case

This is how I also tried to force the last label to be shown, but when resizing, then the second to last label is not hidden
https://codepen.io/Roman-Gorkunenko-the-flexboxer/pen/OJGZrRP
```
xAxis.get("renderer").labels.template.setAll({
  maxPosition: 1
});

var rangeDataItem = xAxis.makeDataItem({
  category: "Year 2034",
  endCategory: "Year 2034"
});
  
var range = xAxis.createAxisRange(rangeDataItem);
  
range.get("label").setAll({
  text: "Year 2034",
  maxPosition: 1
});
```

**Comment by martynasma** [comment]
If you need to show only extreme labels (first and last category), axis ranges is a perfect way to do it. Your code seems to be fine, you just need to disable all axis labels, and enable them in axis range labels:

```JavaScript
xAxis.get("renderer").labels.template.setAll({
  maxPosition: 1,
  visible: false
});

// Create a range for the last value
var rangeDataItem = xAxis.makeDataItem({
  category: "Year 2034",
  endCategory: "Year 2034"
});
  
var range = xAxis.createAxisRange(rangeDataItem);
  
range.get("label").setAll({
  text: "Year 2034",
  maxPosition: 1,
  visible: true
});
```

**Comment by roman-gorkunenko** [comment]
Thanks.
