### ISSUE TITLE
dragged event on stockchart

### ISSUE THREAD

**Issue by p3777dev** [amcharts/amcharts5#1457]
I am trying to access the dragged event on StockChart, but it's not working.

Can you please tell me : 
- When this dragged event is fired.
- How to use this in stockchart , ( I tried using on mainpanel)

**Comment by martynasma** [comment]
StockChart does not use "dragged" event.

Can you clarify what are you referring to? E.g. panning the plot area, dragging a drawings, etc.

**Comment by p3777dev** [comment]
While the chart is being panned , in-between the panstart and panend event.

**Comment by martynasma** [comment]
For that, I would just watch X-axis' private `selectionMin` and `selectionMax` values:

```JavaScript
dateAxis.onPrivate("selectionMin", function(min) {
  console.log(min)
});

dateAxis.onPrivate("selectionMax", function(max) {
  console.log(max)
});
```
