### ISSUE TITLE
Bollinger band extend class for new indicator

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1459]
I am trying to create the Donchain Channel indicator which almost looks like Bollinger band, just the data calculations are different.

So I tried to use the am5stock.BollingerBands, it is showing the bands but the other properties but I want to display the name as donchian channel and it's properties.

I tried doing like this :
```
class DonchianChannel extends am5stock.BollingerBands {
        _editableSettings =[
        {
        key: "period",
		name: "Period",
		type: "number"
        },
        {
            key: "upperColor",
            name: "Upper",
            type: "color"
        },
        {
            key: "seriesColor",
            name:"Average",
            type: "color"
        }, {
            key: "lowerColor",
            name: "Lower",
            type: "color"
        },
    ]
    prepareData() {
        if (this.series) {
            const period = this.get("period", 20);
            const dataItems = this.get("stockSeries").dataItems;

            const upperChannelSeries = this.upperBandSeries;
            const lowerChannelSeries = this.lowerBandSeries;
            const middleChannelSeries = this.series;

            const donchianData = [];
            for (let i = 0; i < dataItems.length; i++) {
                if (i >= period - 1) {
                    let highestHigh = -Infinity;
                    let lowestLow = Infinity;

                    for (let j = i - period + 1; j <= i; j++) {
                        const dataContext = dataItems[j].dataContext;
                        highestHigh = Math.max(highestHigh, dataContext.High);
                        lowestLow = Math.min(lowestLow, dataContext.Low);
                    }

                    const middleChannelValue = (highestHigh + lowestLow) / 2;

                    const dataItem = {
                        valueX: dataItems[i].get("valueX"),
                        upper: highestHigh,
                        lower: lowestLow,
                        ma: middleChannelValue 
                    };

                    donchianData.push(dataItem);
                }
            }

            upperChannelSeries.data.setAll(donchianData);
            lowerChannelSeries.data.setAll(donchianData);
            middleChannelSeries.data.setAll(donchianData);
        }
    }
}



export default  DonchianChannel;

```

**Comment by workingbuddy10** [comment]
@zeroin really sorry for tagging you!
It would be really very helpful you if you can help me, I believe any minor field is only missing!

**Comment by zeroin** [comment]
Did you add all the same things to StockChartDefaultTheme? Many settings go there.

**Comment by workingbuddy10** [comment]
I didn't do any changes in the theme.
my chart theme looks like this only :
import * as am5 from "@amcharts/amcharts5";

class ChartTheme extends am5.Theme {
    setupDefaultRules() {
      super.setupDefaultRules();
      this.rule("Component").setAll({
        interpolationDuration: 1,
      });
      this.rule("RoundedRectangle", [
        "legend",
        "itemcontainer",
        "background",
        "stocklegend",
      ]).setAll({
        fillOpacity: 0,
      });
      this.rule("AxisTick").setAll({
        stroke: am5.color(0xffffff),
        visible: true,
      });
      this.rule("Container", ["legend", "itemcontainer", "stocklegend"]).setAll({
        paddingRight: 0,
        paddingTop: -20,
        paddingBottom: 17,
        paddingLeft: -10,
      });
      this.rule("DrawingControl").setAll({
        strokeWidth:1,
      })
      // this.rule("Graphics", ["series", "fill", "drawing"]).setAll({
      //   forceInactive: true,
      // });
    }
  }
  
  export default ChartTheme;

what changes I have to add to achieve this, so that my main bollinger band indicator doesn't get disturbed but new legend values apply to the donchian channel indicator ?
@zeroin

**Comment by workingbuddy10** [comment]
Any help/update on this @zeroin ?!

**Comment by zeroin** [comment]
Sorry but it's out of scope of free support to provide help like this, I can't provide a quick answer to your question.

**Comment by workingbuddy10** [comment]
> Sorry but it's out of scope of free support to provide help like this, I can't provide a quick answer to your question.

I was just trying to ask what approach you are trying!!

**Comment by workingbuddy10** [comment]
I tried overriding the properties of my indicator but it also got applied on the bollinger bands,
@zeroin
