### ISSUE TITLE
am5.math.boundsOverlap issue

### ISSUE THREAD

**Issue by sassomedia** [amcharts/amcharts5#146]
When I tried the utility function `am5.math.boundsOverlap`, it did not work as expected. If this utility is used internally as well, this might be causing bugs:
https://github.com/amcharts/amcharts5/blob/e572d66d0cae5eec6631009bb9908278b781d432/src/.internal/core/util/Math.ts#L311-L313

It uses `||` but should be using `&&`, otherwise when one condition is true it already exits. Two items can vertically be on the same level/overlap (in which case this function would already return true) but horizontally they could be miles apart, so the bounds wouldn't actually overlap. Both horizontal and vertical overlap would need to occur in order to return true. The `<` also seemed like it only covered one direction but needs to cover both to determine where an item starts and ends.

This is what ended up working for me:
```javascript
export function boundsOverlap (bounds1:IBounds, bounds2:IBounds) {
  const vOverlap = bounds1.top < bounds2.bottom && bounds1.bottom > bounds2.top;
  const hOverlap = bounds1.left < bounds2.right && bounds1.right > bounds2.left;

  return vOverlap && hOverlap;
}
```

**Comment by zeroin** [comment]
I must say I couldn't find where we use it in our code, maybe in some examples :) Or it's is a leftover from v4. 

But it does return false, not true if any of the conditions met, and from my point of view that is correct:
https://stackoverflow.com/questions/2752349/fast-rectangle-to-rectangle-intersection

**Comment by sassomedia** [comment]
Weird, for the longest time this did not work for me. I just tried it again and it does seem to work now. 🤔 Incidentally, the SO answer right below that is what I ended up with: https://stackoverflow.com/a/2752369/6276921.
