### ISSUE TITLE
Feature Request :  specify the logarithm base for ValueAxis

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1463]
There are multiple issues open regarding this, it would be great if you guys think of implementing this. As there many many products which are viewed in the different baseValues. Without adjusting this you can't view those products.

Something like this : 
![image](https://github.com/amcharts/amcharts5/assets/137867461/1f3395da-d068-41aa-b2a1-ac872fdd2846)

Is there any quick which I can do to achieve this via manipulating the properties of amcharts then do let me know I'll do it.

Issues where this feature is requested and added enhancement label  : #1368 , #1046

**Comment by martynasma** [comment]
Please avoid submitting duplicate requests. Thank you!
