### ISSUE TITLE
It is not possible to get the width of labels on the X axis if the labels on the Y axis are hidden

### ISSUE THREAD

**Issue by roman-gorkunenko** [amcharts/amcharts5#1464]
When on the Y axis I hide the labels this way
```JavaScript
yAxis.get('renderer').labels.template.set('forceHidden', true);
```

width of all labels along the X axis becomes zero:
```JavaScript
xAxis.onPrivate('cellWidth', function (cellWidth, target) {
     const xRenderer = xAxis.get('renderer');
     const labels = xRenderer.labels.values;
     const rotated = labels.some(label => {
         console.log(label, label.width(), cellWidth);
         return label.width() > cellWidth;
     });
});
```

Here's an example https://codepen.io/Roman-Gorkunenko-the-flexboxer/pen/OJGZrRP

How then can get the width of the labels along the X axis?

**Comment by martynasma** [comment]
It's not that they don't have width, it's just they don't have width at the moment the X-axis callucates and sets its `cellWidth`.

When there are Y-labels, they adjust width of the axis, and in turn width of the plot area as well as width of the X-axis, which in turn changes `cellWidth` and initiates an event again, at which point the labels already are initiated and have width.

The solution is to wait for the frame to finish before making any adjustments to those labels:

```JavaScript
xAxis.onPrivate('cellWidth', function (cellWidth, target) {
  root.events.on("frameended", function() {
     const xRenderer = xAxis.get('renderer')
     const labels = xRenderer.labels.values;
     const rotated = labels.some(label => {
        console.log(label, label.width(), cellWidth)
        return label.width() > cellWidth
     });
  })
});
```

**Comment by roman-gorkunenko** [comment]
Are there any other options?
This method for me doesn't work
Because I dynamically change `minGridDistance` depending on the width and height
`maxWidth` also changes + some other parameters for labels dynamically
As a result, the root.events.on("framed") event is called a lot of times
Before `yAxis.get('renderer').labels.template.set('forceHidden', true);` applied cellWidth works 2 times
the first time the widths were with 0 the second - with numbers
I also have a possible drag resize, then frameended is called an infinite number of times
Maybe this event can be called once? For example root.events.one("framed")(Edited)Restore original

**Comment by martynasma** [comment]
Yes, you can just use plain-ol' `setTimeout` 😉

**Comment by roman-gorkunenko** [comment]
Oh yes, thank you)

**Comment by martynasma** [comment]
Alternatively, you can use `once()` instead of `on()` so the event executes only once:

```JavaScript
xAxis.onPrivate('cellWidth', function (cellWidth, target) {
  root.events.once("frameended", function() {
     const xRenderer = xAxis.get('renderer')
     const labels = xRenderer.labels.values;
     const rotated = labels.some(label => {
        console.log(label, label.width(), cellWidth)
        return label.width() > cellWidth
     });
  })
});
```
