### ISSUE TITLE
Need Hover Event of pie chart

### ISSUE THREAD

**Issue by kirannarwade** [amcharts/amcharts5#1465]
![Screenshot from 2024-04-16 13-01-35](https://github.com/amcharts/amcharts5/assets/90048456/d4d812e1-617c-4f25-ac66-a5982b436894)

I need when user is hover that pie chart then the hover event fired i want that, means user hover pie chart then event will be like example console log 

please need its urgent buddy

**Comment by zeroin** [comment]
That would be:

```
series.slices.template.events.on("pointerhover", functione(e){
   console.log(e.target.dataItem)
}
```

**Comment by kirannarwade** [comment]
this pie chart calculate data and covert to 100% to show series slices, how can i change the 100 value from code can you please help me, like i want change that value of percentage

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.
