### ISSUE TITLE
Change calulate percent value in pie chart slices

### ISSUE THREAD

**Issue by kirannarwade** [amcharts/amcharts5#1467]
![Screenshot from 2024-04-16 13-01-35](https://github.com/amcharts/amcharts5/assets/90048456/6a4d560f-5f05-4ba3-ab6f-a029cff8b24c)
 i need the change the calculated value for slices, by default its 100 i want change that value using code, in setting i ll fill my value can you please help me buddy..

**Comment by kirannarwade** [comment]
![Screenshot (4)](https://github.com/amcharts/amcharts5/assets/90048456/cf743b51-5dcd-45a8-acf5-89e84cbb94d8)

    <script>
    am5.ready(function() {
    
    // Create root element
    // https://www.amcharts.com/docs/v5/getting-started/#Root_element
    var root = am5.Root.new("chartdiv");
    
    // Set themes
    // https://www.amcharts.com/docs/v5/concepts/themes/
    root.setThemes([
      am5themes_Animated.new(root)
    ]);
    
    // Create chart
    // https://www.amcharts.com/docs/v5/charts/percent-charts/pie-chart/
    var chart = root.container.children.push(
      am5percent.PieChart.new(root, {
        endAngle: 270
      })
    );
    
    // Create series
    // https://www.amcharts.com/docs/v5/charts/percent-charts/pie-chart/#Series
    var series = chart.series.push(
      am5percent.PieSeries.new(root, {
        valueField: "value",
        categoryField: "category",
        endAngle: 270
      })
    );
    
    series.states.create("hidden", {
      endAngle: -90
    });
    
    // Set data
    // https://www.amcharts.com/docs/v5/charts/percent-charts/pie-chart/#Setting_data
    series.data.setAll([{
      category: "Lithuania",
      value: 25
    }, {
      category: "Australia",
      value: 25
    }, {
      category: "Austria",
      value: 15
    }, {
      category: "UK",
      value: 25
    }]);
    
    series.appear(1000, 100);
    
    }); // end am5.ready()
    </script>


    this is my code in that code i have 4 counties but its 90 but the chart is calculated for 100 average then output will be calculated by 100, i want to the chart will be shown in 25, 25, 15, 25 values

    change the 100 value which is dividing calculation

**Comment by martynasma** [comment]
Did you check the links I provided? There's literally an example of how you can make labels display value:

```JavaScript
series.labels.template.set("text", "{category}: {value}");
```

https://www.amcharts.com/docs/v5/charts/percent-charts/pie-chart/pie-series/#label-content
