### ISSUE TITLE
Styling StockToolbar

### ISSUE THREAD

**Issue by xdajay** [amcharts/amcharts5#1468]
![Screenshot 2024-04-17 at 9 07 50 AM](https://github.com/amcharts/amcharts5/assets/760412/eb2b60ff-c066-4ca9-a05a-943ee3305450)

How do I style StockToolbar.new components ? dark theme has no effect on  am5stock-control-button, background, modal etc, etc. (Time interval you see is custom),  also tried everything.

https://codepen.io/team/amcharts/pen/vYvBwbW?editors=1000
^^ in above example dark theme working perfectly for  StockToolbar items, modals, setting menu etc, may be this is different version of v5

So far i have tried 

1

```
#charttools .am5stock-control-button {
  background-color: #222; /* Dark background color */
  color: #fff; /* Light text color for contrast */
}

```

 2
```
 class MyTheme extends am5.Theme {
    setupDefaultRules() {
        this.rule("InterfaceColors").setAll({
            secondaryButtonText: am5.Color.fromHex(0xffffff),
        });
    }
} 

 rootRef.current.setThemes([MyTheme.new(rootRef.current)]);
```
 
 
 3. Setting Default dark theme, working for everything expect StockToolbar
 
 
 
 Thank you Team

**Comment by workingbuddy10** [comment]
Where you are setting your theme on the root just also set Dark theme it will work.
```

import am5themes_Dark from "@amcharts/amcharts5/themes/Dark";
root.setThemes([
  am5themes_Dark.new(root),
]);

```

This should work @xdajay

**Comment by xdajay** [comment]
@workingbuddy10 Thanks 

root.setThemes([
  am5themes_Dark.new(root),
]);

This method is working only if dark mode is default,  if  user toggle between design (light, dark mode) it wont change, and remain whatever is default set.

**Comment by martynasma** [comment]
@xdajay Dark theme does affect Stock toolbar, as per your (updated) CodePen.

So the question is rather when you switch up themes on a live chart, the change does not get applied to stock toolbar?

Officially, we do not support hot-swapping of themes. It works, but might not work for certain elements, like colorsets etc.

Unofficially, you can try and call undocumented method to `StockToolbar`: `loadDefaultCSS()` after the new themes are applied.

Let me know if that worked.

Another alternative, is to completely override amCharts' default toolbar CSS, with your own:
https://www.amcharts.com/docs/v5/charts/stock/toolbar/#Styling_controls

**Comment by xdajay** [comment]
Thanks @martynasma 
Was able to fix theme switching, via theme hooks (React), so basically i'm re-rendering chart if user switches theme.

Secondly over-writing default  CSS seems good option for now, tested it, its working well.
