### ISSUE TITLE
Bug with formatDuration() in tooltip text?

### ISSUE THREAD

**Issue by morrow95** [amcharts/amcharts5#147]
Getting the wrong duration format value in my tooltip with the below code.

```
//duration format
chartReg['chart'].durationFormatter.setAll({
	baseUnit: "second",
	durationFormat: "hh'h' mm'm' ss's'",
	durationFields: ["Total"]
});

//series
var series = chart.series.push(am5xy.ColumnSeries.new(chartReg['chart'], {
	name: "Total",
	fill: am5.color(0x679fd0),
	xAxis: xAxis,
	yAxis: yAxis,
	valueYField: "Total",
	valueXField: "Timestamp",
	tooltip: am5.Tooltip.new(chartReg['chart'], {
		labelText: "{valueY}",
		getFillFromSprite: false
	})
}));

series.get("tooltip").get("background").setAll({
	fill: am5.color(0xffffff),
	fillOpacity: 1,
	strokeWidth: 2,
	stroke: am5.color(0xbbbbbb),
});

series.get("tooltip").label.adapters.add("text", function (text, target, key) {
	console.log(target);
	//have to check for empty
	if(target._dataItem) {
		var totalP = calcPercent(target._dataItem.dataContext.Total, target._dataItem.dataContext.TotalSum);
		return "Total : [bold]{Total.formatDuration()}[/]\nPercent : [bold]"+totalP+"[/]";;									
	} else {
		return null;
	}
});
```

`{Total.formatDuration()}` is the problem part.

In this example, 'Total' is equal to 1030 for this particular column in the data I supply to the chart, yet my tooltip returns 00h 28m 30s.  If I change the code to  `{valueY.formatDuration()}` the tooltip correctly shows 00h 17m 10s.  The other odd thing is visually the chart displays this column correctly right below the 18m mark on my y-axis both ways so the data being supplied is correct.  It is also exported correctly as 00h 17m 10s.

So, my question is... can we no longer directly reference data by 'name'?  Is 'Total' some kind of reserved name in the amcharts code that is causing a different value than intended to be returned?  I was accustomed to referencing values by the name I supply in my data in version 4 as it was much easier and sensible in my code plus not all the data I supply to the chart is used 'in' the chart, but might be used in a tooltip - so this is the only way to access that data.

**Comment by morrow95** [comment]
Okay, I think I figured out what is happening.

I changed my code to `return "Total : [bold]{Total}[/]\nPercent : [bold]"+totalP+"[/]";` and it correctly shows the tooltip as : 

```
Total : 00h 17m 10s
Percent : 99.5%
```

It would appear that : 
```
//duration format
chartReg['chart'].durationFormatter.setAll({
	baseUnit: "second",
	durationFormat: "hh'h' mm'm' ss's'",
	durationFields: ["Total"]
});
```

in my code above directly modifies the 'Total' value so I don't even have to pass any formatting in my tooltip text.  I'm not sure if that is a good or bad thing.  I might have to go back and re-evaluate the code I've done so far with version 5.  I'd prefer a way to access my data values as I originally passed them into the chart then format as needed.  I'd imagine some of my code thus far might be behaving incorrectly as it expects the unaltered values in certain places.

I also noticed that exporting in version 5 still requires its own durationFields and durationFormat values whereas version 4 used the chart defaults if not provided.  Seen above the tooltip text in version 5 now uses the chart defaults whereas version 4 you needed to format it.

**Comment by morrow95** [comment]
Got it behaving how I want now.

Changed my code to `return "Total : [bold]{Total.formatDuration(\"hh'h' mm'm' ss's'\")}[/]\nPercent : [bold]"+totalP+"[/]";` with the tooltip formatting inline.

Removed the chart default formatting : 

```
//duration format
chartReg['chart'].durationFormatter.setAll({
	baseUnit: "second",
	durationFormat: "hh'h' mm'm' ss's'",
	durationFields: ["Total"]
});
```

**Comment by martynasma** [comment]
Thanks for the updates. If you're all set, would you mind closing the issue?

**Comment by morrow95** [comment]
@martynasma Sure, no problem.  The behavior is what threw me off as it behaves differently than version 4 did.
