### ISSUE TITLE
Issue handling gaps in line charts

### ISSUE THREAD

**Issue by hernes45** [amcharts/amcharts5#1473]
**Question**
Hi all!

I want to handle gaps in chart with random periodicity. The samples that i have can come mainly in hours but some times the sample comes after several hours or days.

If I configure the chart with _connected: false_ and a _timeunit: 'hour'_ **it paints a Gap  between the points that are separated more than one hour.**

**Is there any way to draw a gap only  when the value is undefined??** 

Data of example: 
var data = [{
  "year": "1971",
  "value": -0.254
},
{
  "year": "1972",
  "value": -0.254
}, {
  "year": "1977",
  "value": 0.019
}, {
  "year": "1978",
  "value": -0.063
}, {
  "year": "1979",
  "value": 0.05
}, {
  "year": "1980",
  "value": 0.077
}, {
  "year": "1981",
  "value": 0.12
}, {
  "year": "1982",
  "value": 0.011
}, {
  "year": "1983",
  "value": 0.177
}, {
  "year": "1984"
}, {
  "year": "1989",
  "value": 0.104
}, {
  "year": "1990",
  "value": 0.255
},];

- The first sample start in 1972 and there is a gap until 1977 --> for this a I would like to link the points because there is no null between samples.
- In 1983 to 1989 there is a null sample in 1984 --> for this I would like to draw a gap between 1983 and 1989.

This is what I would like:

![image](https://github.com/amcharts/amcharts5/assets/32544910/402d8021-03b5-4e4f-aa19-d09bb76e9e63)

I've done a sample code to view the current behaviour: 
https://jsfiddle.net/b0r8n5js/1/

Kind regards!!

**Comment by martynasma** [comment]
You can set `autoGapCount` to a very large value, so that it never draws a gap because of a missing base interval, but only on data items with null value:

```JavaScript
var series = chart.series.push(am5xy.SmoothedXLineSeries.new(root, {
  minBulletDistance: 10,
  connect: false,
  autoGapCount: 1000000,
  xAxis: xAxis,
  yAxis: yAxis,
  valueYField: "value",
  valueXField: "year",
  tooltip: am5.Tooltip.new(root, {
    pointerOrientation: "horizontal",
    labelText: "{valueY}"
  })
}));

Docs: https://www.amcharts.com/docs/v5/charts/xy-chart/series/line-series/#Auto_gaps_with_dates
```
