### ISSUE TITLE
Facing an unknown error when we switch the timeInterval. 

### ISSUE THREAD

**Issue by p3777dev** [amcharts/amcharts5#1477]
In my stock chart, I am facing an error when I switch the time interval.
- Let's say I am in 5 min time interval and there is already some unserialze drawing.
- And then I switch to another time interval, let's say 1 hour.
- And some times it also happens if we load more data via panning, and switch the product. In some cases it gets stuck with the same error.
- I feel there is some issue while creating the new dateaxis.
- My whole app freezes with the below error: 

![image](https://github.com/amcharts/amcharts5/assets/153706487/24559c56-b308-4639-9604-31f1888c4286)

At this exact point  : 
![image](https://github.com/amcharts/amcharts5/assets/153706487/b2488a29-210e-4080-a36a-35062ff449a9)

Just please help what things I should focus to bypass this error.

**Comment by martynasma** [comment]
Are you setting a timezone for your chart? If you do, does the error happen if you disable it?

**Comment by p3777dev** [comment]
I have **already** disable the time Zone, earlier I was setting root.utc = true. 
@martynasma

**Comment by martynasma** [comment]
Do you mean the error is happening without timezone and `utc` set?

Would you be able to provide a reproducible case which we can run and test?

**Comment by p3777dev** [comment]
> Do you mean the error is happening without timezone and `utc` set?
Yes.
Steps to reproduce : 
- I am just trying to change the product / time interval after panning the chart. 

This issue doesn't happen in 5.8.7, whereas current issue I am facing in 5.9.2 version.

@martynasma

**Comment by martynasma** [comment]
We'll need to some way to reproduce it then. Can you whip up some kind of repro demo?

**Comment by p3777dev** [comment]
It got fixed . Thanks .
