### ISSUE TITLE
Treemap rectangle min size

### ISSUE THREAD

**Issue by c-ody** [amcharts/amcharts5#1478]
**Question**

Is there any way to force the nodes in a treemap to have some minimum size, despite their value? The `minWidth`/`minHeight` options for Rectangle seem to break the layout in treemaps. If making `minWidth`/`minHeight` work with the treemap layout isn't feasible, perhaps another way could be to have an option that, in the layout algorithm, squishes the values so they're closer together, so there aren't too-large or too-small extremes?

It would be helpful in cases where there's large rectangles, with a value like 100, and small rectangles, with a value like 2. The smaller rectangles become too small.

Example of the smallness using the demo drill-down treemap: https://jsfiddle.net/gj36k7eL/

**Comment by martynasma** [comment]
I'm afraid there's no option for that. We also are using 3rd party layout algorithm (D3) for layouts, which does not offer this capability, unfortunately.
