### ISSUE TITLE
Both truncate and fit label text

### ISSUE THREAD

**Issue by c-ody** [amcharts/amcharts5#1479]
**Question**

Currently there are `truncate` and `fit` options for a label's `oversizedBehavior`. Is there some way to have both behaviors, so the label text can scale down at most `minScale`, and then truncates the rest if it still does not fit? I see that there's a `maxChars` option, but I would not want to truncate every label, only the labels where the text would not fit.

It would be nice to have in a treemap with some very large rectangles and some small rectangles that have long text. Using `truncate`, only 1-3 characters of the text show in small rectangles. Using `fit`, the text is not legible because it has to scale down too much. Hiding the text is not desirable. It'd be nice if the text was able to scale down to a point, and then truncate the rest.

**Comment by martynasma** [comment]
No, I'm afraid there's no such option to combine `"fit"` and `"truncate"` functionality.

I suppose the closest thing is to combine `maxChars` setting with `"fit"` behavior. I know it's not exactly the same as you need, but it's the closest available option.
