### ISSUE TITLE
How to make scrollbar visible on chart hover?

### ISSUE THREAD

**Issue by dez1729** [amcharts/amcharts5#148]
Is there a way to make the scrollbar disappear and only transition to visible on hovering the chart?

**Comment by dez1729** [comment]
Nevermind, I can use states

    scrollbarY.thumb.states.create('hover', {}).setAll({ ... });

**Comment by zeroin** [comment]
You can listen for globalpointermove event and check if point coordinates are within the chart, then show/hide scrollbar depending on that:
https://codepen.io/team/amcharts/pen/eYGvOEQ
