### ISSUE TITLE
Encountered an error while using the polyfill and triangle drawing tool

### ISSUE THREAD

**Issue by p3777dev** [amcharts/amcharts5#1486]
Uncaught RangeError: Maximum call stack size exceeded  .

https://github.com/amcharts/amcharts5/assets/153706487/b4a7dddf-40c1-4be1-b030-50e2ed11a8d5

**Comment by martynasma** [comment]
I cannot seem to be able to reproduce this error on any of our demos.

Would you be able to provide a use case where it happens?
