### ISSUE TITLE
Tooltip doesn't work properly with no grouping and base interval set to 5 min

### ISSUE THREAD

**Issue by Garima-github-24** [amcharts/amcharts5#1489]
Hi,

I am using amcharts 5 XY series to plot line chart in my application. The default grouping is removed and the x-axis (date axis) has a data of 1 year. In 1 year data, I have data points for every hour. I have set the base interval to 5 min. Now when I try to hover over the line series, I rarely see the tooltip on it. Is this the default behavior of amcharts 5 or I am missing anything. Kindly suggest.

am5xy.DateAxis.new(root, {
        groupData: false,
        baseInterval: { timeUnit: 'minute', count: 5 },
      })

**Comment by workingbuddy10** [comment]
Have you added the tooltip property to your DateAxis? 
Some thing like this : `tooltip: am5.Tooltip.new(root, {}),`

@Garima-github-24

**Comment by Garima-github-24** [comment]
@workingbuddy10 Yes, I have added the tooltip property to my date axis.

**Comment by zeroin** [comment]
Whem base interval is less than your data items, the series doesn't show tooltip if your cursor is not over the baseInterval section.
You can: 

1) set `snapTooltip: true` for your series. This will make series to shot tooltip of nearest data point. But your axis tooltip will show time of cursor position. 

2) set snapToSeries on your cursor. This way cursor will be snapped to the nearest data point of your series:

```
var cursor = chart.set("cursor", am5xy.XYCursor.new(root, {
  behavior: "none",
  snapToSeries:[series]
}));
```
