### ISSUE TITLE
How do I force a change detection on the chart itself?

### ISSUE THREAD

**Issue by dez1729** [amcharts/amcharts5#149]
I want to make changes to the chart after it has been drawn, such as making changes to the series title, or change the series tension or change the axis position etc. 
I've only tried it with the series name change but it won't detect the changes until I hover over the chart at a part of a series where the legend will see the change and changes the name accordingly.

I have change detection set to OnPush and I've tried to manually invoke detectChanges() as well as try to run .appear() on the chart and the series to no avail.

**Comment by sassomedia** [comment]
Do you have an example perhaps? For my project, I do a number of changes after the chart has been drawn and they do update without any specific function call. My guess is you might not be updating the right item, maybe there is a child that needs the update.

**Comment by zeroin** [comment]
Legend won't detect change of a name of a series automatically. You might however manually update it like this:

`series.get("legendDataItem").get("label").set("text", "Blah")`

**Comment by dez1729** [comment]
thanks that will work
