### ISSUE TITLE
Is it possible to fix chart crashing for mobile devices if set useSafeResolution as false?

### ISSUE THREAD

**Issue by dmytro-kuz** [amcharts/amcharts5#1491]
**Question**
Is it possible to fix chart crashing for mobile devices if set [useSafeResolution](https://www.amcharts.com/docs/v5/getting-started/root-element/#Safe_resolution) as false?

```
 const resizeHandler = (newScale: number) => {
        if (!this.isRootInit) {
          this.root = am5.Root.new(`chart_${this.chartId}`, {
            calculateSize: (dimension: DOMRect) => ({
              width: dimension.width / newScale,
              height: dimension.height / newScale,
            }),
            useSafeResolution: false,
          });

          // add animation
          this.root.setThemes([am5themes_Animated.new(this.root)]);

          this.initAmCharts5();
          this.isRootInit = true;
        }
      };

      resizeHandler(this.windowResizeService.getInitialScaleFactor());
```

I used such root creation for my charts in the project. Because there is a need to use scaleFactor.
But when using the useSafeResolution parameter on mobile devices, the charts break the browser page(I am attached the video)
If useSafeResolution is enabled, the chart renders well on mobile, but some charts do not scale correctly. I haven't checked all cases, but I see at least one issue with the bar-stacked case. (for example stacked chart in the 2 video).

I understand that it is related to memory limits imposed on canvas rendering.

But anyway is there any fix for mobile devices? Or how can I fix it for my case?

**Environment (if applicable)**
https://stackblitz.com/edit/angular-ivy-fjjctu?file=src%2Fapp%2Fapp.component.ts  - simple version of issue

**Additional context**

video1 - https://drive.google.com/file/d/1Mnb3SOM41GqVJQ_Zzll3K2Ew0zpWNGdE/view?usp=sharing
video2 - https://drive.google.com/file/d/1D6pU7yVNf2V4tQsQ0j09Yr16eMbgNV1l/view?usp=sharing

**Comment by martynasma** [comment]
Is there a reason for your use of `calculateSize`? Chart should be able to calculate its own size unless you use `transform: scale` CSS.

I don't see anywhere in your stackblitz, but maybe you have it in your app?

**Comment by dmytro-kuz** [comment]
Yes, in my app I am using `transform: scale(scaleFactor)` . That is why `calculateSize` is used.  I forget to put this in my stackblits. Currently is updated.

Here is this page with charts: 
https://dmytro-kuz.dev.storied.co/charts1

**Comment by dmytro-kuz** [comment]
It doesn't reproduce in the emulators, only on a real device. I was tested on the IOS platform with version 17

**Comment by martynasma** [comment]
Thanks.

Works fine on iPhone 15 with iOS 17.4 Safari, though.

**Comment by dmytro-kuz** [comment]
I was tested on the iPhone 12 and 13. 
Can you try this one case? There are 11 simple charts per page.
https://dmytro-kuz.dev.storied.co/charts

**Comment by martynasma** [comment]
I was kinda able to reproduce this on a 12. I guess it has less memory than 15 and thus hits apple's limit sooner.

I don't think there's a lot we can do about it if Apple is not cool with playing nice with Canvas-based apps 🙁

**Comment by dmytro-kuz** [comment]
Got it. 
Well, in that case, thanks for the answer
