### ISSUE TITLE
Bug when loading the Map with specific geojson

### ISSUE THREAD

**Issue by luanrjjj** [amcharts/amcharts5#1493]
When attempting to load a map using a specific GeoJSON file representing the states of Brazil, I encounter a situation where sometimes I face the following issue:
![image](https://github.com/amcharts/amcharts5/assets/71605566/2ca0f33d-69fb-4d04-8c3a-0e8148bc72ae)

I have researched this problem, and typically, the issues reported here or on StackOverflow are related to the direction of GeoJSON coordinates. However, in my case, the loading process occurs normally. Despite this, even after a successful reload, a state may still break during subsequent reload attempts. I am using React with amCharts 5.

**Comment by martynasma** [comment]
Do you mean that exactly same GeoJSON sometimes produces proper map and sometimes this square?

Would you be able to post this as a runnable demo, e.g. on CodePen?

**Comment by luanrjjj** [comment]
Yes, Exactly. I'm going to do this CodePen in the next week and put the link here.

**Comment by luanrjjj** [comment]
So, I created a example in the following repository : 
https://gitlab.com/alfredofreitas/amcharts-map-test-debug/

It's a simple nextjs project with only 1 page, the dashboard page. So, to test the app you need only enter in localhost:3000/dashbaord. 

To install the package is necessary npx install and after to run npm run dev.

If the necessary I can deploy the project also to the vercel.

It was possible to reproduce the bug when I change the select state, as is possible to see in following picture:

![image](https://github.com/amcharts/amcharts5/assets/71605566/d1de4517-9d52-4a02-a2c5-0f77b6d5a7e7)

The geojson is in the maps_counties folder

**Comment by martynasma** [comment]
Can you post just the GeoJSON? I don't have a GitLab account and they are making me jump through all these hoops just to access a repo.

**Comment by luanrjjj** [comment]
If you want I can put in the github also.

**Comment by luanrjjj** [comment]
Here the link to github repo: https://github.com/luanrjjj/map-test/tree/main/amcharts-map-test-debug-main/my-app

**Comment by martynasma** [comment]
Getting this:

![image](https://github.com/amcharts/amcharts5/assets/1458520/1e812808-c29d-4fe5-8ca0-fca0dc303dd0)

**Comment by martynasma** [comment]
I think I know what's going on.

When you use `reverseGeodata: true` setting it mutates the source GeoJSON by modifying the order of coordinates in it.

If you set `geoJSON` with the same (mutated) object again, it reverses coordinates again, thus creating visual anomaly.

The solution would be to always create a shallow copy of the GeoJSON you set:

```
geoJSON: JSON.parse(JSON.stringify(object))
```

**Comment by luanrjjj** [comment]
I did some testes here. It's better, but a litte unstable: the reload is broken with a probability of more or less 30% - 50%. Some other tip?

**Comment by martynasma** [comment]
I can't seem to be able to reproduce this outside of your specific app.

Here's a very basic repro case using your GeoJSON:
https://codepen.io/team/amcharts/pen/wvbvYNa/112f2ef728e40bf60ea92ee32ed9af7c?editors=0010

Technically, shallow-copying GeoJSON should be enough, as per above demo.
