### ISSUE TITLE
Animating x axis range label

### ISSUE THREAD

**Issue by dangji** [amcharts/amcharts5#1495]
I would like to dynamically animate the x axis range label with d3 
Can it be done through html adapter ?

![image](https://github.com/amcharts/amcharts5/assets/1977918/bfcd42c0-cdb8-4371-aea3-a2b03baecdf6)

**Comment by martynasma** [comment]
You can animate any value-based (number, percent or color) via `animate()` method:
https://www.amcharts.com/docs/v5/concepts/animations/#Animating_settings

It supports a lot of settings, including tween functions, etc. So you might not need D3 animations after all.

If you absolutely need D3, you will need to create your own functions that iterate step through frames, request value from D3 animation functions, and set a relative setting on an amCharts object or dataitem.

In this case, updating `valueX` on an axis range data item should update its position.

**Comment by dangji** [comment]
I would like to tween x axis range label value from zero to the number:
I do not see how to that with animate(), I need to tween the number part of the axis range label from zero to it's final state

currently am using this code to achieve styling of label

`  setTimeout(() => {            
            chartConfig.current.range.get("label").adapters.add("html", (html, target) => {
                return `<div style="text-align: center;">
                        <h2>
                            ${superLabelPrefix ?? getListsTitle(resolution, "Last")}
                            <br />
                            <strong>
                                <span style="color: ${blinkColor}">${superlabel}</span>
                            </strong>
                        </h2>
                    </div>`;
            });

        }, timeout);`

**Comment by martynasma** [comment]
```JavaScript
rangeDataItem.animate({
  key: "value",
  to: value,
  duration: 3000,
  easing: am5.ease.inOut(am5.ease.elastic)
});
```

**Comment by dangji** [comment]
This would animate the range itself , but i need to animate the label value of the range, and not the range.

**Comment by martynasma** [comment]
I can't quite make it. In the video, is what you had in v3 or what you have so far in v5? 🤔

Can you post what you have so far on CodePen or jsFiddle?

**Comment by dangji** [comment]
In the video it is amcharts 3, where a use a selector and d3 to tween 
```
 select(target)
            .transition()
            .duration(2500)
            .tween("text", tweenText(prevSuperLabel, superLabel));
```

**Comment by martynasma** [comment]
Gotcha. Thanks.

Why can't you do the same to amCharts 5 label? I.e. set `chartConfig.current.range.get("label").set("html", ......)`

**Comment by dangji** [comment]
how exactly ?

**Comment by martynasma** [comment]
Well, you animate a value using D3 (sorry, it's beyond our scope of support) then just set label's `html` setting with the value being animated.

**Comment by dangji** [comment]
I do not need to use D3. But still not sure how to animate the label inside adapter function. Are there any examples ?
