### ISSUE TITLE
'EventDispatcher is disposed' error when refreshing bullets containing PieCharts

### ISSUE THREAD

**Issue by Cameramorphic** [amcharts/amcharts5#1496]
**Question**
Hi, I have a (quite complex) `XYChart` with two category axes and a `ColumnSeries` for the cells. On the series I'm using bullets to display the cell content. Each bullet is a container with multiple sprites, where I now added `PieChart`s to show more details.
These pie charts don't have to do anything, they basically act as a fancy `Circle` sprites.
I have to recalculate the bullet contents on data and chart size changes, but now I get the following error (which I believe is triggered by a 'datavalidated' event):
```
Uncaught Error: EventDispatcher is disposed
    at _SpriteEventDispatcher.isEnabled
    at PieSeries._afterChanged
    at PieSeries._afterChanged
    at @amcharts_amcharts5.js
    at Array.forEach (<anonymous>)
    at _Root._runDirties
    at _Root._renderFrame
    at _Root._runTicker
    at _ticker
```
This only happens on subsequent loads / data refreshes (not if the page loads initially), so I'm guessing it has to do with how the bullets are removed and regenerated in my event handlers. Maybe updating too rapidly, causing some race condition?
I tried disabling events on the `PieChart` and `PieSeries`, storing a reference to the pie charts and manually disposing them, and more, but unfortunately I can't figure out how to solve it.

Below is the handler for refreshing the bullets. Updating the data like this is most definitely wrong, but I couldn't get the refresh to work any other way (and it worked perfectly before adding the pie charts). It would probably make more sense to store the calculated `dimensions` separately (maybe the 'userData' of the series?) and just retrigger the bullet rendering, but I don't know how to do it...
Maybe you can help and point me in the right direction :)

```ts
const updateDimensions = () => {
	const width = xAxis.getPrivate('cellWidth');
	const height = yAxis.getPrivate('cellWidth');
	if (width && height) {
		const dimensions = calculateDimensions({...});
		series.bulletsContainer.children.clear(); // otherwise old bullets start accumulating at the top left of the chart when resizing the chart
		series.data.setAll(series.data.values.map(value => ({ ...value, dimensions })));
	}
};

xAxis.onPrivate('cellWidth', updateDimensions);
yAxis.onPrivate('cellWidth', updateDimensions);
series.events.on('datavalidated', updateDimensions);
```

**Environment**
amCharts: 5.9.4
Chrome: 122.0.6261.111 (Official Build) (64-bit)
Typescript/React

**Comment by martynasma** [comment]
I don't like this line:

```JavaScript
series.bulletsContainer.children.clear(); // otherwise old bullets start accumulating at the top left of the chart when resizing the chart
```

Normally, when data is updated and data items with bullets are discarded, related bullets are disposed as well. If you clear bulletContainer and thus effectively dispose those bullets items, a code that kicks in to clear them might generate the error since they are disposed already.

Technically, you would not need to do that.

Here's a very basic PieChart with bullets and data update:
https://codepen.io/team/amcharts/pen/bGJJoRv/84cfa47c996daad3db93aeb51ae28b1f?editors=0100

The bullets are properly removed and replaced with new ones after data update.

Maybe you can modify it to suit your setup better? Or create a new runnable demo case if that's easier.

**Comment by Cameramorphic** [comment]
Thanks for the quick reply!
I tried removing the line you mentioned, but unfortunately the error still occurs, and also now the issue happens that I mentioned in the comment on this line (why I added it in the first place). Maybe there's an unrelated bug where disposed bullets are still drawn somehow, or maybe that's another side effect of the kind of data update here?
Or maybe it doesn't discard it properly if the data gets replaced, but the data's `categoryXField`/`categoryYField` values didn't change?

Unfortunately, I can't share a demo at the minute, im not using bullets in a pie chart though my rough setup is like this:
```ts
const chart = root.container.children.push(am5xy.XYChart.new(...));
const xAxis = chart.xAxes.push(am5xy.CategoryAxis.new(...));
const yAxis = chart.yAxes.push(am5xy.CategoryAxis.new(...));
const series = chart.series.push(am5xy.ColumnSeries.new(...));
series.bullets.push(function() {
    const container = am5.Container.new(...);
    container.children.push(am5.Circle.new(...));
    container.children.push(createPieChartSprite(...));
    return am5.Bullet.new(root, {
        ...,
        sprite: container,
    });
});
// code snippet from original question here
```

Also, just FYI, I have a different variation of my `XYChart` with one category and one value axis. There, the pie chart sprite is used directly as the bullet and I don't need to do the `calculateDimensions({...})` update. This chart works just fine and refreshes/discards properly on data update.

**Comment by martynasma** [comment]
Thanks for additional details.

Unfortunately, we'll need some kind of repro case in order to look into this further.

**Comment by Cameramorphic** [comment]
Yes, of course. I currently don't have time to provide one, maybe I'll get to it later this week.

I think I found a partial fix, but now have an issue where a data refresh doesn't always render the new bullets. Resizing the chart then causes them to appear correctly, but I didn't have time to thoroughly test it yet:
```diff
- series.events.on('datavalidated', updateDimensions);
+ series.events.on('datasetchanged', updateDimensions);
```
I guess this works, because the bullets are now cleared/disposed before the 'datavalidated' event propagates to the pie charts, but I'll have to test further if that also caused the new issue I'm having...
