### ISSUE TITLE
Bug : Custom Indicator doesn't work with Series Switcher

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1497]
Steps to reproduce : 
- Switch the series to Line Series .
- Click on the my indicator from indicator list.
 
App will freeze, throwing error regarding Event Disposer disposed.

Code pen : https://codepen.io/Ansh-m-the-reactor/pen/jORRZae

**Comment by martynasma** [comment]
Series switcher functionality is something that is handled by user code. I'm afraid debugging custom code is beyond the scope of our support.

**Comment by workingbuddy10** [comment]
@martynasma  The code which you are seeing is from amcharts only.

Just merge below codepen  
Both of them are from amcharts: 
1) This codepen have custom indicator : https://codepen.io/team/amcharts/pen/vYvBwbW
2) This codepen have series switcher :  https://www.amcharts.com/demos/stock-chart/

In my codepen I have only copy pasted.

**Comment by workingbuddy10** [comment]
Getting this error : 
`Uncaught Error: EventDispatcher is disposed`

**Comment by workingbuddy10** [comment]
I hope this clears it @martynasma ?

https://github.com/amcharts/amcharts5/assets/137867461/34ffbaeb-bba3-4db0-a425-710a2131974a

**Comment by martynasma** [comment]
Easy fix. Just replace `stockSeries`  assignement to use current "stock series", not a reference to some global variable which does not get updated when series type is switched.

```JavaScript
stockSeries: stockChart.get("stockSeries")
```

We have updated our CodePens and docs accordingly.
