### ISSUE TITLE
Settings button visible, even after disabling it.

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1498]
We can disable the settings button from the legend by this :  `  valueLegend.settingsButtons.template.set("visible", false);
 `

But in One case it fails : 
- If I click on the legend color box on the ohlc/volume, so the candles drop.
- But if I again click on it, the candles comes as well as settings button too.

https://github.com/amcharts/amcharts5/assets/137867461/1a945f8f-246f-48dc-bbd8-bd347fc50a41

**Comment by martynasma** [comment]
Try using `forceHidden: true` instead.
