### ISSUE TITLE
How to edit bullets after they are created?

### ISSUE THREAD

**Issue by dez1729** [amcharts/amcharts5#150]
https://stackblitz.com/edit/js-faug7t?file=index.js

I expanded one of the demos "Highlighting Line Chart Series on Legend Hover" except I added bullets with each series. The highlight still dims the non-hovered series but the associates bullets will not get hidden. How can I reference these bullets to change the fill, stroke, opacity etc.?

**Comment by martynasma** [comment]
I suppose you would need to iterate via `series.dataItems` and then in each data item's `bullets`. Those will have actual bullet elements, which you can modify.

**Comment by dez1729** [comment]
Thanks, based on your suggestion, here is how I did it for my use-case:


    legend.itemContainers.template.events.on('pointerover', e => {
      const itemContainer = e.target;
      const series = itemContainer.dataItem.dataContext;
      chart.series.each((chartSeries: am5xy.LineSeries) => {
        if (!_.eq(chartSeries, series)) {
          chartSeries.strokes.template.setAll({
            strokeOpacity: 0.15,
            stroke: am5.color(0x000000),
          });

          chartSeries.dataItems.forEach(v => v?.bullets?.[0]?.get<any>('sprite')?.setAll({
            opacity: 0.15,
            fill: am5.color(0x000000),
          }));
        }
        else {
          chartSeries.strokes.template.setAll({
            strokeWidth: 3,
          });
        }
      });
    });

    legend.itemContainers.template.events.on('pointerout', e => {
      chart.series.each((chartSeries: am5xy.LineSeries) => {
        chartSeries.strokes.template.setAll({
          strokeOpacity: 1,
          strokeWidth: 1,
          stroke: chartSeries.get('fill'),
        });

        chartSeries.dataItems.forEach(v => v?.bullets?.[0]?.get<any>('sprite')?.setAll({
          opacity: 1,
          fill: chartSeries.get('fill'),
        }));
      });
    });
