### ISSUE TITLE
Setting Timezone to the root causes error

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1500]
- I am trying to set the timezone in my stock chart as "Europe/London". As I want to show the data in that format only.
- But when I switch the product to different time interval like 5 minute, 1 hour or change the product it throws `Invalid time format` .
- As similar mentioned in #1477 
- If I remove the below code, then it works fine but the timeformat is different : 
```
     // root.utc = true
    // root.timezone = am5.Timezone.new("Europe/London");
```

How can I achieve this, like setting London time or any user specific time which amcharts support and not getting error on change of product or time interval in stock chart. Like I am planning to give user the option to change the timezone accordingly, whichever they want.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
