### ISSUE TITLE
How do I prevent the forceDirected from going out of bounds?

### ISSUE THREAD

**Issue by ChyunKim** [amcharts/amcharts5#1501]
Hi, I'm using amCharts5.

I'm encountering an issue while drawing a forceDirected chart. The problem arises when the nodes overflow beyond the designated area. 
I've customized each circle and set a minRadius of around 40 to ensure that there's no overlap between circles.

```js
target.dataItem.on("circle", function (circle) {
        circle.on("radius", function (radius, item) {
          let ellipsis = item.getPrivate("customData");
          if (ellipsis) {
            ellipsis.setAll({
              radiusX: circle.get("radius"),
              radiusY: circle.get("radius") * 0.6,
            });
          } else {
            ellipsis = target.children.unshift(
              am5.RoundedRectangle.new(root, {
                radiusX: circle.get("radius"),
                radiusY: circle.get("radius") * 0.6,
                centerX: am5.p50,
                centerY: am5.p50,
                width: setWidth(depth, dataContext),
                height: depth === 0 ? 85 : 32,
                cornerRadiusBL: 999,
                cornerRadiusBR: 999,
                cornerRadiusTL: 999,
                cornerRadiusTR: 999,
                fill: item.get("fill"),
              })
            );
            circle.setPrivate("customData", ellipsis);
          }
        });
      });
```
```js
const series = container.children.push(
        am5hierarchy.ForceDirected.new(root, {
          valueField: "value",
          categoryField: "name",
          childDataField: "children",
          idField: "name",
          fillField: "color",
          paddingTop: 20,
          paddingBottom: 20,
          xField: "x",
          yField: "y",
          minRadius: 45,
        })
      );
```

It seems that setting the minRadius attribute is causing nodes to be drawn outside the screen area due to maxRadius. How can I draw each node so that they spread across the screen without overlapping and remain within the designated area?

**Comment by martynasma** [comment]
There's no setting to absolutely contain all nodes within chart area.

For a crowded chart, there might be a few options:

1) Increase center pull force:
https://www.amcharts.com/docs/v5/charts/hierarchy/force-directed/#Configuring_forces

2) Enable pan/zoom:
https://www.amcharts.com/docs/v5/concepts/common-elements/containers/#Zoomable_container

**Comment by ChyunKim** [comment]
I will take note. I appreciate your quick response.
