### ISSUE TITLE
Amcharts 5 - Horizontal scrollbar resets to random indexes

### ISSUE THREAD

**Issue by veerasaraha** [amcharts/amcharts5#1502]
Hello amcharts team,

I want to persist chart's scrollbar position in both horizontal and vertical axis.  I managed to get scrollbar's start and end positon from the scrolbar events "rangechanged".

**Problem** 
 When I tried to re-size the horizontal scrollbar, unforunately it resets to random indexes. This happens only when the data points are less than 8.

Codesanbox - [link](https://codesandbox.io/p/sandbox/amcharts-5-horizontal-scrollbar-issue-99ngw9?file=%2Fsrc%2FApp.js)

![Video GIF](https://github.com/amcharts/amcharts5/assets/68050313/1823fdca-a843-407d-be9a-fd323bdf0c61)

**Comment by martynasma** [comment]
I'm not sure what "resets to random indexes" is, but the built-in scrollbar behavior is to reset selection to at least include one cell of the related axis.

So, if you zoom in to have less than it, the other grip snaps back to a range of one full cell.
