### ISSUE TITLE
Labels in Responsive

### ISSUE THREAD

**Issue by roman-gorkunenko** [amcharts/amcharts5#1503]
For charts with small sizes, labels collapse into the chart
Here's an example

https://codepen.io/Roman-Gorkunenko-the-flexboxer/pen/ExJLdMV

How can I make the labels stay in place along the Y-axis instead of collapsing inward? For example, at a width of 300 pixels, they should remain in their positions.

**Comment by roman-gorkunenko** [comment]
And there's also a strange jump of the labels upwards.
Because of this, sometimes some labels are not visible.

https://github.com/amcharts/amcharts5/assets/91733660/66be5972-d1ab-4ef7-8e7d-c72922266a99

**Comment by martynasma** [comment]
I suggest you review all the default responsive rules listed in the ResponsiveTheme:
https://github.com/amcharts/amcharts5/blob/master/src/.internal/themes/ResponsiveTheme.ts#L311

Then write your own overrides as needed.

Alternatively, you can disable all default rules, and just add yours as needed:
https://www.amcharts.com/docs/v5/concepts/responsive/#Applying

**Comment by roman-gorkunenko** [comment]
Thanks.
