### ISSUE TITLE
Bellcurve in v5

### ISSUE THREAD

**Issue by priyanshuchauhan** [amcharts/amcharts5#1504]
In amcharts 4 bellcurve can be created by curvedColumnSeries, but I'm unable to figure out how to do the same with v5.

**Comment by zeroin** [comment]
Here is a demo:
https://www.amcharts.com/demos/curved-columns/

We do not have a special series type for this in v5, instead, a custom draw function is used:

```
series.columns.template.set("draw", function(display, target) {
  var w = target.getPrivate("width", 0);
  var h = target.getPrivate("height", 0);
  display.moveTo(0, h);
  display.bezierCurveTo(w / 4, h, w / 4, 0, w / 2, 0);
  display.bezierCurveTo(w - w / 4, 0, w - w / 4, h, w, h);
});
```
