### ISSUE TITLE
Overlapping charts when using the opposite option

### ISSUE THREAD

**Issue by bossbelle** [amcharts/amcharts5#1505]
If I use the opposite option for Yaxis to move the axis of Line Chart to the right
There is a phenomenon where Line Chart and Column charts overlap.
Is there a solution?

here is my CodePen
[CodePen](https://codepen.io/-bossbelle/pen/KKYJgjJ)

![1](https://github.com/amcharts/amcharts5/assets/122963338/28ea9bd6-1b6d-4881-9465-491b4d236ce4)

![2](https://github.com/amcharts/amcharts5/assets/122963338/5e13fda8-e61f-4453-9ca4-034ac2a4b82a)

**Comment by martynasma** [comment]
When you set `opposite: true` on an axis, they are moved to `rightAxesContainer`, so you need to set its layout to vertical:

```JavaScript
chart.rightAxesContainer.set("layout", root.verticalLayout);
```

**Comment by bossbelle** [comment]
After changing the rightAxesContainer settings, the chart overlap has been resolved.
However, the positions of Line Chart and Column Charts have changed.

![3](https://github.com/amcharts/amcharts5/assets/122963338/88d87ad7-1f02-4e19-860f-420f7ea62356)

**Comment by martynasma** [comment]
Try this:

```JavaScript
chart.rightAxesContainer.setAll({
  layout: root.verticalLayout,
  reverseChildren: true
});
```

Or simply add value axes in different order.
