### ISSUE TITLE
Making pdfmake.js optional

### ISSUE THREAD

**Issue by nicolaric** [amcharts/amcharts5#1507]
**Question**

We try to minimize our package size of the application to improve loading times. Since we migrated the whole project from AMCharts4 to AMCharts5 now, we saved a noteable amount of MBs. Now, one of the biggest packages left is pdfmake.js (close to 1MB), which is used by amcharts5. We don't use the PDF functionality in our project though. Is there a possibility to make this package optional or treeshakable in the project without going through webpack tweaks?

Thanks a lot in advance!  

<img width="573" alt="image" src="https://github.com/amcharts/amcharts5/assets/64309148/ac74de3c-efba-4427-963e-7ccc94d4818d">

**Comment by nicolaric** [comment]
maybe this could help as well?
https://github.com/bpampuch/pdfmake/issues/1374

**Comment by Pauan** [comment]
@nicolaric pdfmake is already optional, amCharts uses dynamic `import()` which will only load the file when you actually use it.

So if you never export to PDF, then the file will never be loaded, and so it will not have any performance penalty at all.

You can confirm this by using the Chrome / Firefox devtools (the Network tab).

So you don't have to worry about it, pdfmake will not increase the bundle size, and it won't hurt performance.

It has no impact at all on loading times.

----

However, if you really do want to avoid the file completely, then you will need to change your Webpack configuration to ignore those modules:

https://www.amcharts.com/docs/v4/getting-started/integrations/using-webpack/#Large_file_sizes

```js
  externals: function (context, request, callback) {
    if (/xlsx|canvg|pdfmake/.test(request)) {
      return callback(null, "commonjs " + request);
    }
    callback();
  }
```

**Comment by davidjb** [comment]
With Rspack, the callback signature slightly different but the same strategy from @Pauan works; `canvg` is no longer present in amCharts 5 so that can be removed from the regex below (and above if using Webpack):

```js
  externals: function ({ context, request, contextInfo, getResolve }, callback) {
    if (/xlsx|pdfmake/.test(request)) {
      return callback(null, "commonjs " + request);
    }
   callback();
  }
```

Analysing the bundle afterwards via Rsdoctor shows these have been fully omitted.
