### ISSUE TITLE
Security Issue with es5-ext in @amcharts/amcharts5

### ISSUE THREAD

**Issue by OliviaAk** [amcharts/amcharts5#1509]
We have an issue in GitHub security 
**Regular Expression Denial of Service (ReDoS) vulnerability in es5-ext**,  it comes from  @amcharts/amcharts5@5.9.3
Also we tried to update with the latest version  @amcharts/amcharts5@5.9.5. But  it still not updated. 
The GitHub Code scanning security supposed that this library es5-ext should be 0.10.63 or higher version.
Is there a possibility to upgrade this dependence es5-ext package to new version inside @amcharts/amcharts5 ?

![image](https://github.com/amcharts/amcharts5/assets/61189716/067f9cc2-4fd5-4d3a-a8c6-57b789a2f8c8)

Thanks a lot in advance!

**Comment by Pauan** [comment]
This issue has already been fixed. Please use `yarn upgrade` or `npm update`. Then you can confirm that the `es5-ext` package no longer exists.

**Comment by OliviaAk** [comment]
> This issue has already been fixed. Please use `yarn upgrade` or `npm update`. Then you can confirm that the `es5-ext` package no longer exists.

It doesn't help.
