### ISSUE TITLE
How to bind data to links?

### ISSUE THREAD

**Issue by MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM** [amcharts/amcharts5#1512]
Hello, I would like to bind data to the connection line between nodes, and then click on links to obtain the data value of the current links. How can I achieve this?

series.links.template.setup = function(target) {
                target.events.on("click", function(e){
                    //  I want to retrieve the data bound to the current link here, but now I am returning the data from the parent node
                    console.log('click==click===', e.target);
                });
            };

**Comment by martynasma** [comment]
Please confirm which chart type are you using. Both Hierarchy and Flow chart types use link templates, but their data model is fundamentally different.

**Comment by MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM** [comment]
> Please confirm which chart type are you using. Both Hierarchy and Flow chart types use link templates, but their data model is fundamentally different.

I am using Force directed

**Comment by martynasma** [comment]
Thanks for the clarification.

In Hierarchy-based charts, links do not have their own data context.

The link object (`e.target`) contains `source` and `target` properties, which are data items for source and target nodes respectively.

You can use them to pull any additional stuff that came with data via `dataContext`.

Hope this helps.

**Comment by MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM** [comment]
> Thanks for the clarification.
> 
> In Hierarchy-based charts, links do not have their own data context.
> 
> The link object (`e.target`) contains `source` and `target` properties, which are data items for source and target nodes respectively.
> 
> You can use them to pull any additional stuff that came with data via `dataContext`.
> 
> Hope this helps.

thanks~~
