### ISSUE TITLE
How to use custom categories in both Axis in Radar chart in amcharts5?

### ISSUE THREAD

**Issue by Nandreasyan** [amcharts/amcharts5#1513]
**Question**

I cannot achieve, that in both axis in radar chart I label them as custom defined categories.
And the values and the labels of the chart are corresponding to that categories.
Additionally, at the beginning only show one value 0 (or in my case very low, and the latest one instead of 1 very high.)
The documentation about this is poor, there are not any example like this.

**Comment by martynasma** [comment]
Here's an example of a `RadarChart` where both axes are `CategoryAxis`:
https://www.amcharts.com/demos/radar-heat-map/

**Comment by Nandreasyan** [comment]
> Here's an example of a `RadarChart` where both axes are `CategoryAxis`: https://www.amcharts.com/demos/radar-heat-map/

Unfortunately, it is not what I wanted. I want, that it is functioning like a numerical value with order. When a new categorical value  comes it puts in the corresponding in the axis, such as Low, Medium, High.
