### ISSUE TITLE
get valuePercentTotal returns undefined in pie charts

### ISSUE THREAD

**Issue by fruitbang** [amcharts/amcharts5#1514]
Hello. Today I encountered this behavior in pie charts.

slice.dataItem.get('value') returns value
slice.dataItem.get('valuePercentTotal') returns undefined
but in console.log(slice.dataItem) i can see both

is this fine?

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by fruitbang** [comment]
Sry my friend, I'm not a developer anymore😞
