### ISSUE TITLE
How can I infinitely scale the canvas?

### ISSUE THREAD

**Issue by MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM** [amcharts/amcharts5#1515]
Hello, I am currently using Force directed and have added the ZoomTools scaling tool. However, this tool has scaling restrictions and cannot make the canvas infinitely shrink. If I want to infinitely shrink, which parameter should I configure?

 var zoomTools = container.children.push(am5.ZoomTools.new(root, {
      target: container
  }));

**Comment by martynasma** [comment]
You can set [`minZoomLevel`](https://www.amcharts.com/docs/v5/reference/zoomablecontainer/#minZoomLevel_setting) value to something smaller than default `1`.

**Comment by MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM** [comment]
> You can set [`minZoomLevel`](https://www.amcharts.com/docs/v5/reference/zoomablecontainer/#minZoomLevel_setting) value to something smaller than default `1`.

thanks!

**Comment by martynasma** [comment]
Would you be able to share your whole code on CodePen? The zoom should not be constricted like that.

**Comment by MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM** [comment]
> Would you be able to share your whole code on CodePen? The zoom should not be constricted like that.

My configuration is the same as the official website use case. You can take a look at the example on the official website. After zooming in, the ZoomableContainer area has also become smaller. The red line area is the reduced area. Dragging the node clearly shows that the available area has become very small

https://www.amcharts.com/docs/v5/concepts/common-elements/containers/#Example

![ep](https://github.com/amcharts/amcharts5/assets/33676254/23742573-64e3-4037-b1d8-9e57f2c8d8b4)

**Comment by MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM** [comment]
> false



> Gotcha. That's easy to fix, just add `maskContent: false` to your series settings:
> 
> ```js
> var series = zoomableContainer.contents.children.push(am5hierarchy.ForceDirected.new(root, {
>   singleBranchOnly: false,
>   downDepth: 2,
>   topDepth: 1,
>   initialDepth: 1,
>   valueField: "value",
>   categoryField: "name",
>   childDataField: "children",
>   idField: "name",
>   linkWithField: "linkWith",
>   manyBodyStrength: -10,
>   centerStrength: 0.8,
>   maskContent: false
> }));
> ```

thanks~~
