### ISSUE TITLE
How to place ticks only for arbitrary values using axisRange

### ISSUE THREAD

**Issue by tapiamcclung** [amcharts/amcharts5#1516]
**Question**

Following this [tutoria](https://www.amcharts.com/docs/v5/tutorials/using-axis-ranges-to-place-labels-at-arbitrary-values-or-dates/) I have added arbitrary labels to a yAxis.
Now, I would like to show the ticks only for these newly created labels, but If I set them to visible inside the  `createRange` function, this overrides the setting for all ticks and all of them now visible instead of only the new ones.

Any pointers on how I could either clear the original ticks or only show the ones that I want?
Codepen [here](https://codepen.io/tapiamcclung/pen/OJYJgQp). I am using amcharts v5.
Thanks!

**Comment by zeroin** [comment]
You should set `visible` for the particular tick, not for the template in your `createRange` method:

`range.get("tick").set("visible", true)`

**Comment by tapiamcclung** [comment]
Awesome, thanks!
