### ISSUE TITLE
How can I achieve Month wise alternate candle color 

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1517]
I want to achieve this feature where user can view the candlestick stockchart in the month wise alternate candle color, it helps analyst to analyze better the long range historical market trends.
 
There will be a checkbox when checked then user can see the month wise alternate candle color , something like this :
![GetImage](https://github.com/amcharts/amcharts5/assets/137867461/2e32516d-cc24-44ee-b5d7-2f67fca822f3)

What are the possible ways I can look or try for ?

**Comment by zeroin** [comment]
Try looping through dataItems. Data item has `valueX` setting, which is date in timestamp. It also has `graphics` setting, which is a candlestick graphics. set fill/stroke for your graphics depending on your valueX.

**Comment by workingbuddy10** [comment]
Nice approach @zeroin !! Will try this.

**Comment by workingbuddy10** [comment]
I guess this will require a re-rendering of chart! If I want to apply the colors on the live chart.
Isn't it?

**Comment by zeroin** [comment]
Each change leads to a redrawing a chart, it's how Canvas works. Or I do not understand your question.
