### ISSUE TITLE
How to remove hover of ValueAxis pannel

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1518]
I want to remove this hover effect/background change of my valueAxis in stockChart.

![image](https://github.com/amcharts/amcharts5/assets/137867461/a4ff2353-513b-4586-ae97-1887a6246a99)

I tried adding these properties but it didn't worked        `hoverOnFocus: false,  focusable:false.`
```
    var valueAxis = mainPanel.yAxes.push(
      am5xy.ValueAxis.new(instance, {
        renderer: am5xy.AxisRendererY.new(instance, {
          strokeOpacity: 1,
          strokeWidth: 1,
          stroke: am5.color("#474747"),
          hoverOnFocus:false,
          focusable:false,
        }),
        extraMin: 0.2,
        maxDeviation:1,
        tooltip: am5.Tooltip.new(instance, {}),
        extraTooltipPrecision: 2,
        hoverOnFocus: false,
        focusable:false
      })
    );
```

I tired this too but it didn't worked :  `  this.rule("PanelControls").states.create("hover", {});`

**Comment by zeroin** [comment]
If you want just not to show it when hovered, then do this:

```
valueAxis.get("renderer").thumb.states.create("hover", {
  fillOpacity: 0
})
```

If you don't want the panning function, do not set pan: "zoom" for the axis.

**Comment by workingbuddy10** [comment]
Thanks it worked! @zeroin
