### ISSUE TITLE
how to change a certain range of spacing on the y-axis?

### ISSUE THREAD

**Issue by bossbelle** [amcharts/amcharts5#1519]
I have a chart like the image below.
The value of one of each series is greater than that of all other series, so that the value of the other series appears too close.

Is it possible to change the interval of valueAxis that is displayed too close due to a small value in this situation?

![image](https://github.com/amcharts/amcharts5/assets/122963338/ab611699-9a70-4219-8d49-d417147c7dd4)

here is my codepen
[code](https://codepen.io/-bossbelle/pen/KKYJgjJ)

**Comment by martynasma** [comment]
Please refer to this tutorial:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#grid-density
