### ISSUE TITLE
amchart5 Why is there a blank space next to the chart?

### ISSUE THREAD

**Issue by skulter** [amcharts/amcharts5#152]
I am making a lineChart using amchart5.
I am changing from amchart4 to amchart5, but only in amchart5, spaces are created on both sides of the chart.
For what reason is it made?
![image](https://user-images.githubusercontent.com/18344213/146331482-a79e972a-1f01-458c-b433-c8f7c3dafbea.png)

**Comment by martynasma** [comment]
Please refer to this documentation section:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#Axis_start_end_locations
