### ISSUE TITLE
Partially style axis line or limit axis length?

### ISSUE THREAD

**Issue by tapiamcclung** [amcharts/amcharts5#1520]
Is it possible to conditionally style axis lines or limit how far an axis extends? In this [pen](https://codepen.io/tapiamcclung/pen/eYaYoYX) I would like the top axis to reach up to, say, 30% with its labels aligned with the bottom ones and no blue line after that. 
Changing the min/max settings for the axis adjusts the spacing between values, but the axis fills the available space. I would like to limit how far it extends. I can set custom ticks to get rid of the unwanted ones, but that still leaves the axis line displaying in full. 

I tried adding a rectangular mask to the axis hoping to only see the portion of axis I wanted. It initially works, but because the mask is fixed, when I zoom and scroll, some desired values are masked out, but they should be visible. Also, if I scroll enough to the right, values outside of the desired range become visible. 

Is it possible to do this? Am I missing some axis setting? I am using v5.
Thanks!

**Comment by martynasma** [comment]
Mask should resize together with the element, and it does in your CodePen:

https://github.com/amcharts/amcharts5/assets/1458520/3ee41728-48fb-47a4-a379-7ca939bb9521

What am I missing?

**Comment by tapiamcclung** [comment]
Hi! I meant zooming on the chart, not changing the container size. So, for example, if I zoom on the chart a little bit, the mask covers up to, say, 12%, but I would like to show up to 30% regardless of the zoom level. 
![image](https://github.com/amcharts/amcharts5/assets/7925327/b3b83261-617c-40b8-894a-a583231e44ea)

**Comment by martynasma** [comment]
Gotcha.

No, I'm afraid masking won't work in that case.

I suppose you could us a `ColumnSeries` with a single bar to display the line, as well as axis bullets to display labels at certain places:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#axis-bullets

**Comment by tapiamcclung** [comment]
Thanks, will take a look into it.
