### ISSUE TITLE
How to set the display position of child nodes when initializing data in Force directed?

### ISSUE THREAD

**Issue by MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM** [amcharts/amcharts5#1521]
Hello, I am using Force directed. I would like to partition the node display during the initialization of the force diagram, such as displaying odd numbered nodes on the left and even numbered nodes on the right, instead of displaying them in a scattered manner like this. May I know which attribute should I configure to set the display position of the node?
 As shown in the following figure

![1715580086724](https://github.com/amcharts/amcharts5/assets/33676254/32494f47-dd3e-469e-8ff4-605067b63fb0)

**Comment by martynasma** [comment]
> ok~，How can we remove the official icon in the bottom left corner of our canvas? Do I need to pay to remove it?

Yes. You will need a commercial license to remove the branding.

**Comment by MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM** [comment]
> > ok~，How can we remove the official icon in the bottom left corner of our canvas? Do I need to pay to remove it?
> 
> Yes. You will need a commercial license to remove the branding.

thanks~~

**Comment by MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM** [comment]
> You may find this useful: https://www.amcharts.com/docs/v5/charts/hierarchy/force-directed/#Fixed_nodes

Hello, I have checked the official website API and I would like to obtain the (X, Y) values of the Cartesian coordinate system of the parent node, and then set the (x, y) values of the child node based on the parent node's coordinate axis. I am listening for data changes in the dataitemchanged event and using e.target. x(). e.target. y() to obtain the current value of the parent node's coordinate axis as (0,0) and the value of the child node's coordinate axis as (0,0). However, the e.target. y() values I obtained in the Dragstop event are the real coordinate system values. Therefore, when initializing the data, I want to obtain the real value of the parent node's coordinate axis as (0,0). How to obtain the X and Y of a node?
As shown below:


let  parent_x = null;
let parent_y = null;
target.events.on("dataitemchanged", function(e) {
  if(e.target.dataItem.dataContext.name === 'parent') {

      // I want to obtain the real coordinate values of the parent node on the screen，But The value of the coordinate axis 
         obtained here is (0,0)，

       parent_x = e.target.x();
       parent_y = e.target.x();
   }
    if(e.target.dataItem.dataContext.type === '1'){
          e.target.dataItem.setAll({
              x: (-100+parent_x)* Math.random(),
              y: (-100+parent_y)* Math.random(),
          });
      }else {
          e.target.dataItem.setAll({
              x: (100 + parent_x)*Math.random(),
              y: (100+ parent_y)* Math.random(),
          });
      }
});

**Comment by martynasma** [comment]
I suppose you can use target's [`toGlobal()`](https://www.amcharts.com/docs/v5/reference/sprite/#toGlobal_method) method to convert it's local coordinates to global ones.
