### ISSUE TITLE
Screen readers are announcing different data from the visible data on the Funnel chart.

### ISSUE THREAD

**Issue by msftedad** [amcharts/amcharts5#1522]
**Bug description**
Repro Steps:
1. Open URL https://www.amcharts.com/demos-v4/funnel-with-gradient-fill-v4/ in edge browser.
2. Trun on Narrator using 'Ctrl + Win + Enter' key.
3. Navigate to the chart present on the page using tab key.
4. Observe the narrator announcement.

Actual Results: Screen readers are announcing different data from the visible data on the chart bars, it is announcing page view 46.7% figure, but the visible data is 100%.

Expected Results: The narrator must announce the exact data information as it is visible.

https://github.com/amcharts/amcharts5/assets/93735775/1cd81886-663a-4d53-bd38-07732d63da0a

**Environment (if applicable)**
OS Build: Windows 11 Enterprise Insider Preview 22H2 (23541.1000)
Edge Browser: Version 115.0.1880.3 (Official build) dev (64-bit)

**Additional context**

**Comment by martynasma** [comment]
This is a repo for amCharts 5. If you're reporting an amCharts 4 issue, please use proper repo:
https://github.com/amcharts/amcharts4/
