### ISSUE TITLE
Drawing tools with live data stock chart

### ISSUE THREAD

**Issue by OstapchelaEst** [amcharts/amcharts5#1523]
I took the live data example from the demo and added drawing tools to it. 
https://jsfiddle.net/jr8g7yto/4/

If you draw something and then try to drag it with the “select” tool, it doesn't work with anything except a circle (but it also jerks every time you add new data).

The problem is clearly visible if you draw a rectangle, when you hover over it, it loses the hover effect.

Is there any solution for this?

**Comment by p3777dev** [comment]
@zeroin  We were also facing the same issue, and disabling drawing in the middle of the live chart doesn't make any sense.

I am showing the data in a live stream format ( via websocket/SSE), and there a product Crypto Btc ( which trade 24*7).
So user can never use the drawing in crpto btc or any product which updates continuously?

**Comment by zeroin** [comment]
Well, you can draw things, but the problem is with dragging, because when data is update, the series is redrawn so it's not the same object anymore which you were dragging and things get complicated.

**Comment by OstapchelaEst** [comment]
The interesting thing is that for the circle tool, drag and drop works, not perfectly, but it works 🤔
