### ISSUE TITLE
BUG : Custom Indicator data gets save Twice

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1524]
I am trying to save the custom indicator, but the data is getting saved twice.

I have used this : am5stock.registerClass("MyIndicator", MyIndicator);

https://github.com/amcharts/amcharts5/assets/137867461/ed19c777-c28e-4e98-afa3-9b55fcb3eb00

codepen : https://codepen.io/Ansh-m-the-reactor/pen/OJYVBEa
PS: above codepen code is from amcharts, nothing custom!

**Comment by zeroin** [comment]
I am afraid this is out of scope of free support, I can't tell why this happens without deep investigation.

**Comment by workingbuddy10** [comment]
I believe this is the bug in the code side, isn't it?

Don't look in my codepen/code.
You can try, just save any custom indicator, via Save control/Auto Save ( provided by amcharts) and you can see the bug.  It's that's simple!

@zeroin

**Comment by workingbuddy10** [comment]
I have handled this in my code only, in case of the duplicate indicator object. 
But this bug is still there in the amcharts.
