### ISSUE TITLE
Fix position of series bullet label to the top of the chart (XY) 

### ISSUE THREAD

**Issue by binaryartifex** [amcharts/amcharts5#1526]
**Question**

Ive done a fair bit of searching but can't seem to find an appropriate solution. Within the context of an XY column chart where the x axis is a category axis, i need the value of each series item to be fixed above the chart. I understand that for typical labels for a series item a label is placed within a bullet, where the bullet is positioned relative to the column and the label is positioned relative to the bullet. Its also my understanding that these bullets will position themselves relative to their parent container, which is the column whose height is derived from its value - hence my issue, as i need them fixed to the top of the chart, bonus points for a slight offset above the chart.

**Environment (if applicable)**

 - amCharts version v5
 - Chrome 
 - React v18.3.1

**Additional context**

![image](https://github.com/amcharts/amcharts5/assets/68464707/5ff85410-2dbd-4fae-8211-119a6a948a18)

**Comment by martynasma** [comment]
The easiest way is to just override `y` value of a label in bullet with an adapter:

```JavaScript
series.bullets.push(function () {
  var label = am5.Label.new(root, {
    text: "{valueY}",
    centerY: am5.p100,
    centerX: am5.p50,
    populateText: true
  });

  label.adapters.add("y", function() {
    return 0;
  });

  return am5.Bullet.new(root, {
    locationY: 1,
    sprite: label
  });
});
```

**Comment by binaryartifex** [comment]
thanks mate that worked perfectly
