### ISSUE TITLE
Is it possible to add space between items in built-in amCharts 5?

### ISSUE THREAD

**Issue by timbo-dev** [amcharts/amcharts5#1527]
**Is it possible to do that with space?**

I'm trying to create that layout:

![image](https://github.com/amcharts/amcharts5/assets/65836845/2eb2ea2f-5d70-4e4a-bef5-43af963e91c2)

I have searched everywhere in the documentation, but I can't find anything related to gaps in GridLayout.

So, my actual layout looks like this. It looks like a space-evenly layout:

![image](https://github.com/amcharts/amcharts5/assets/65836845/18e76281-8591-4353-a398-ccef32978f88)

**Comment by zeroin** [comment]
You can either set `maxColumns: 2` for your grid layout:
https://www.amcharts.com/docs/v5/reference/gridlayout/#maxColumns_setting

Or set marginLeft/marginRight for `legend.itemContainers.template`:

**Comment by timbo-dev** [comment]
The margin on itemsContainers works for me, thank you.
