### ISSUE TITLE
Gradient fill for line type chart

### ISSUE THREAD

**Issue by OstapchelaEst** [amcharts/amcharts5#1530]
When selecting a linear type of graph I want to make a gradient fill as in one of the examples. 
![image](https://github.com/amcharts/amcharts5/assets/90386861/61beaf79-bcf4-434b-86b5-64e2d3443c44)

But something goes wrong and I get this result and I can't fix it
![image](https://github.com/amcharts/amcharts5/assets/90386861/848c643a-eaed-42a2-ab07-f62bd3d41417)

Here's my code
https://jsfiddle.net/0awzmqot/2/

**Comment by martynasma** [comment]
If you need `LineSeries` fill to go to the axis line, you need to remove `openValueYField` from its settings, or otherwise it will fill to the open value rather than zero line.

```JavaScript
  var series;
  switch (seriesType) {
    case "line":
    	delete newSettings.openValueYField;
      series = mainPanel.series.push(am5xy.LineSeries.new(root, newSettings));
      series.fills.template.setAll({
        visible: true,
        fillOpacity: 0.2
      });   
      break;
    case "candlestick":
    case "procandlestick":
      newSettings.clustered = false;
      newSettings.openValueYField = "Open";
      series = mainPanel.series.push(am5xy.CandlestickSeries.new(root, newSettings));
      if (seriesType == "procandlestick") {
        series.columns.template.get("themeTags").push("pro");
      }
      break;
    case "ohlc":
      newSettings.clustered = false;
      newSettings.openValueYField = "Open";
			series = mainPanel.series.push(am5xy.OHLCSeries.new(root, newSettings));
      break;
  }
```
