### ISSUE TITLE
Use a DateAxis for the Y-Axis of an XY-Chart

### ISSUE THREAD

**Issue by kobL** [amcharts/amcharts5#1531]
**Question**
Hi!

I tried to switch the DateAxis and CategoryAxis on the "Gantt Chart with Dates" Demo: https://www.amcharts.com/demos/gantt-chart-dates/ as we need it in our application like this.

Unfortunately, the columns are now drawn incorrectly: https://codepen.io/kobL/pen/BaeKYaQ

![image](https://github.com/amcharts/amcharts5/assets/5527393/c36764a4-7d7b-470d-ba7f-6ebbbcfd1098)

Every column starts at the Y-Axis and is drawn into the middle of the category. For the first category it is almost correct and just shifted to the left. But all other categories overlap with the ones before.

What I tried:
- reordered data: no effect on columns, only on grid lines which are now incorrect. I assume the data is correctly ordered.
- switched openValueYField and valueYField, no effect.
- only used valueYField: no columns are drawn
- chart layout: no effect on horizontal or vertical

Is it simply not possible in AmCharts5 to use a DateAxis for the y-Axis? Or did I miss some settings? Any help is much appreciated. 

**Environment (if applicable)**

 - amCharts version : 5.9.9 
 - Browser and its version: Chrome  124.0.6367.202

**Additional context**

**Comment by martynasma** [comment]
You'll need to set `baseAxis` on your series:

```JavaScript
var series = chart.series.push(am5xy.ColumnSeries.new(root, {
  xAxis: xAxis,
  yAxis: yAxis,
  baseAxis: xAxis,
  openValueYField: "start",
  valueYField:"end",
  categoryXField: "category",
  sequencedInterpolation: true
}));
```

Docs: https://www.amcharts.com/docs/v5/charts/xy-chart/series/#Base_axis

**Comment by kobL** [comment]
That was it, thank you very much for the help!
