### ISSUE TITLE
Blank chart when exporting WordCloud chart

### ISSUE THREAD

**Issue by dritani** [amcharts/amcharts5#1532]
**Question**
Hello, when exporting a WordCloud chart I am getting a blank image since it takes some time to perform word arrangement. In AmCharts 4 there exists [this workaround](https://www.amcharts.com/docs/v4/tutorials/exporting-data-from-a-word-cloud/) but I could not get it to work with AmCharts 5.

Does someone know how to accomplish this? Thank you.

**Environment**

AmCharts 5.8.0
Chrome 124.0.6367.208

**Comment by martynasma** [comment]
Do you have a demo of where export of a chart does not work?

I tried it just now, and was able to export a PNG of a WordCloud just fine.

**Comment by dritani** [comment]
The code is pretty deep within a React.js app but the gist of it is:

```
    am5wc.WordCloud.new(root, {
        categoryField: 'customCategory',
        valueField: 'customValue',
        angles: [0, 90],
      }),
```
     
```
  const exporting = am5Exporting.Exporting.new(root, {
    extraImages,
    filePrefix: 'chart',
  });

  exporting.download('png');
```


I tried using _setTimeout_ or listening to the `datavalidated` event but it still did not work.

**Comment by martynasma** [comment]
Do you get any errors in console? Does this happen in all browsers?

Here's my test:
https://codepen.io/team/amcharts/pen/rNgLBxr/2a8992cb9cf2532733496ce8aeea3d96?editors=1000

**Comment by dritani** [comment]
Yes I tried adding multiple seconds delay for `exporting.download('png')` and removing `extraImages`. Have done extensive tests but nothing worked. The export is being triggered programmatically and not through the menu.

**Comment by martynasma** [comment]
Can you reproduce it on this CodePen?

https://codepen.io/team/amcharts/pen/rNgLBxr/2a8992cb9cf2532733496ce8aeea3d96?editors=0010

It triggers a download after 5 seconds.

**Comment by dritani** [comment]
I wasn't able to reproduce it. We deployed the feature without WordCloud export for now.

**Comment by martynasma** [comment]
Have you tried it with the latest version of amCharts? 5.9.11
