### ISSUE TITLE
Force pie chart width to cater for dynamic legend width to prevent legend clipping?

### ISSUE THREAD

**Issue by binaryartifex** [amcharts/amcharts5#1535]
**Question**

Is there a way to either

1. force the pie chart to adapt to the width of the legend or
2. format pie chart legend labels to be multiline?

i have a limited amount of space within the widget this chart is rendered so either way will help.

without setting anything...you can see the 'kg' unit has been clipped at the boundary of the component. Ideally id prefer that the legend does not clip and instead force the pie chart width to adjust to cater for the change.

![image](https://github.com/amcharts/amcharts5/assets/68464707/3723924e-9368-45cb-926d-411b51cba98c)

so as a temp fix ive guestimated a min width for the legend for the moment however larger numbers are also going to inevitably clip off the side. Now when i try to create a custom label adapter with the '\n' value to create new lines...i get the below wierdness where it doesn't wrap back to the start of the new line.

![image](https://github.com/amcharts/amcharts5/assets/68464707/e5b18a9c-cc59-4a92-ac0d-bbd56b617afa)

for context, this is the adapter im using for the pie chart legend label

```typescript
    legend.valueLabels.template.adapters.add("text", function (_, target) {
      if (target.dataItem && transform) {
        const item = (target.dataItem as am5.DataItem<IPieSeriesDataItem>).get("value");
        return item ? `\n[bold]${transform(item)}[/]` : undefined;
      }
      return undefined;
    });
```

**Environment (if applicable)**

 - amCharts 5.9.8
 - Chrome 125.0.6422.76
 - React 18.3.1

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
