### ISSUE TITLE
How to get the independent behavior between 2 panels.

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1536]
I have 2 panels.
- Stockpanel/ stockchart
- fundamentalPanel

If I zoom-in/zoom-out or scroll both the panel behave the same. But I don't want that.

**If I  zoom-in/zoom-out or scroll in stockpanel then fundamentalPanel should not move it should hold its state and vice-versa.**

For Reference I am using the below code to add panel : 
```
  addFundamentalDataSeries(product) {
    const fundamentalPanel = this.stockChart.panels.push(am5stock.StockPanel.new(this.instance, {
      wheelY: "zoomX",
      panX: true,
      panY: true,
      height: am5.percent(30)
    }));
  
    const fundamentalValueAxis = fundamentalPanel.yAxes.push(am5xy.ValueAxis.new(this.instance, {
      renderer: am5xy.AxisRendererY.new(this.instance, { pan: "zoom" })
    }));
  
    const fundamentalDateAxis = fundamentalPanel.xAxes.push(am5xy.GaplessDateAxis.new(this.instance, {
      baseInterval: { timeUnit: "day", count: 1 },
      renderer: am5xy.AxisRendererX.new(this.instance, {}),
      tooltip: am5.Tooltip.new(this.instance, {})
    }));
  
    const series = am5xy.LineSeries.new(this.instance, {
      name: product,
      valueYField: "Close",
      valueXField: "Timestamp",
      xAxis: fundamentalDateAxis,
      yAxis: fundamentalValueAxis,
      legendValueText: "{valueY.formatNumber('#.00')}",
      // tooltip: am5.Tooltip.new(this.instance, {
      //   labelText: "{valueY}"
      // })
    });
  
    fundamentalPanel.series.push(series);
  
    const fundamentalLegend = fundamentalPanel.plotContainer.children.push(am5stock.StockLegend.new(this.instance, {
      stockChart: this.stockChart
    }));
    fundamentalLegend.data.setAll([series]);
  
    const fundamentalCursor = fundamentalPanel.set("cursor", am5xy.XYCursor.new(this.instance, {
      yAxis: fundamentalValueAxis,
      xAxis: fundamentalDateAxis,
      behavior: "none" 
    }));
  
    fundamentalPanel.events.on("pointerover", function() {
      fundamentalCursor.show();
    });
  
    fundamentalPanel.events.on("pointerout", function() {
      fundamentalCursor.hide();
    });
  
   // now fetch & set the data to the series.
      } else {
        message.error("An error occurred: " + (response[product] ? response[product].status : "Unknown error"));
      }
    });
  }
```

**Comment by martynasma** [comment]
There's no way to do that.

Consider pushing an independent `XYChart` as a child of `StockChart`.

**Comment by martynasma** [comment]
On second thought, try setting `zoomable: false` on the second panels' X axis, first.

**Comment by workingbuddy10** [comment]
It didn't worked @martynasma !

```
    const fundamentalDateAxis = fundamentalPanel.xAxes.push(am5xy.GaplessDateAxis.new(this.instance, {
      baseInterval: { timeUnit: "day", count: 1 },
      renderer: am5xy.AxisRendererX.new(this.instance, { }),
      tooltip: am5.Tooltip.new(this.instance, {}),
      zoomable: false,
    }));
```

**Comment by martynasma** [comment]
OK. XYChart then.

**Comment by workingbuddy10** [comment]
The issue I am facing if I syncing the panel is this :

- I am directly using setAll to set the data in the new series added ( like in the below video I did setAll to all the points which was around 3000).
- Whereas in the mainseries initially I am having 50 points only, via lazy loading and panning I am adding new points.
- The issue arises when I am adding more data points on the mainpanel stock chart, the below Lineseries start crisscrossing sometimes.
- Whereas If I didn't load any points in the mainpanel it shows fine.


https://github.com/amcharts/amcharts5/assets/137867461/c0a0faa5-0461-4e91-926f-b957e89cd43b

@martynasma Any suggestion what possibly I'll doing wrong.

And does reversing this causing issue?
![image](https://github.com/amcharts/amcharts5/assets/137867461/026bb0f6-4edf-4664-8d9d-c85c65d12b45)

**Comment by martynasma** [comment]
The data always needs to be in ascending order.

If you data comes in descending order, make sure you reverse() it before setting on series.

**Comment by workingbuddy10** [comment]
True, I know this!;
See in the below image, the data is in the sorted order yet I get to see this : 
![image](https://github.com/amcharts/amcharts5/assets/137867461/8cecdc84-ed0c-499b-b00c-bd53560b9b8a)

I have highlighted 2 points which cause the abruption in the chart.
@martynasma

**Comment by workingbuddy10** [comment]
To get more clarity : 
This time I only added recent 300 points.
        fundamentalData.sort((a, b) => a.Timestamp - b.Timestamp);
          series.data.setAll(fundamentalData.slice(-300));

- Initially when I load the Lineseries it looks perfect, whether I zoom-in/out.
- Once I start loading the data in my panel / stock chart. You can see the disturbance in the below panel.


https://github.com/amcharts/amcharts5/assets/137867461/0de060d2-1638-4615-8ba8-8e46eda4a519

**Comment by martynasma** [comment]
I'll need a CodePen. Can't debug a video and a screenshot.

**Comment by workingbuddy10** [comment]
Below is codepen which has the code for adding the new panel with data already present,  You just have to paste the code, that's all in any envoriment which has stockchart + on-demand loading.

I didn't got any codepen which uses the stockChart & on-demand loading, I tried replicating in the amchart provided example in XY chart but it didn't worked.

I know stockchart is made by Xy chart, still I believe there is some issue with this config in stockchart.

codepen : https://codepen.io/Ansh-m-the-reactor/pen/eYadOKL

@martynasma

**Comment by workingbuddy10** [comment]
If I use the minDistance: 20, in the lineseries it looks good, but then If I zoom-in close to the candles I see the disturbance.

**Comment by workingbuddy10** [comment]
Just removed GaplessDateAxis to DateAxis and it worked perfectly!

Damm this single word!;

**Comment by workingbuddy10** [comment]
my axis is not synced properly, how should I do that @martynasma 

![image](https://github.com/amcharts/amcharts5/assets/137867461/96c938ea-4ac9-4022-b3d5-fbc1d04f4ed9)

**Comment by workingbuddy10** [comment]
I even tried adding mingridistance to 0.
Then too it didn't worked.

There can be irregularity in both the chart data. Can you suggest adding anyother property? @martynasma 

![image](https://github.com/amcharts/amcharts5/assets/137867461/f6f4b2db-0f9f-40eb-b158-1b56d5ac301e)

**Comment by workingbuddy10** [comment]
created a new issue for this
