### ISSUE TITLE
How to change legendRangeValueText dynamically?

### ISSUE THREAD

**Issue by ganzales** [amcharts/amcharts5#1537]
I want to change legendRangeValueText after live update, it possible?

**Comment by martynasma** [comment]
Yes. Though, I'd change it before data update so that it takes immediately.

**Comment by ganzales** [comment]
ok, change like this
```
chart.series.each(function(series) {
		series.set('legendRangeValueText', 4048);
});
```
but, value does not match format setting root.numberFormatter.set('numberFormat', '#,###.#b'), and show 4048 instead of 4KB. How it formatting according global settings?

**Comment by martynasma** [comment]
Only value fields are formatted via number formatter. If you are setting it to "4048" that's what it is - it accepts as a string.

If you absolutely need to set it like this, you will need to apply the formatting manually:

```JavaScript
chart.series.each(function(series) {
  series.set('legendRangeValueText', root.numberFormatter.format(4048));
});
```
