### ISSUE TITLE
chart with two y-axes Set the ratio of height on each axis

### ISSUE THREAD

**Issue by bossbelle** [amcharts/amcharts5#1539]
I have a chart with 1 x-axis and 2 y-axis.

Each y-axis has a series.

Currently, each y-axis is marked with 50:50 same height.

All I want is to set the ratio of each axis to 70:30.
Is there a way?

**Comment by martynasma** [comment]
I don't think there's a way to set specific ratio.

You can just make the axes sync:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/value-axis/#Syncing_grid

**Comment by bossbelle** [comment]
My chart is like the image below
Chart with two y-axes stacked vertically.

I don't need an axial synchronization.

![image](https://github.com/amcharts/amcharts5/assets/122963338/61046960-4fa0-4b3c-877f-2c7264d914d8)

**Comment by bossbelle** [comment]
I changed the Height value of each y-axis, but it doesn't work for me.

[myPen](https://codepen.io/-bossbelle/pen/KKYJgjJ)

**Comment by zeroin** [comment]
You changed height of axis renderer, not the axis.

https://codepen.io/team/amcharts/pen/bGyBXxZ
