### ISSUE TITLE
Sort legend items

### ISSUE THREAD

**Issue by HASSANDL** [amcharts/amcharts5#154]
I want reverse sort name series in legend items.

![image](https://user-images.githubusercontent.com/22093903/146432589-bf2b1acc-addb-48af-a1a3-f6c8fe97793f.png)

**Comment by xorspark** [comment]
The legend item order is dependent on how they are inserted into the `data` array.

If you want them in reverse order, simply reverse the data items:

```
legend.data.setAll(chart.series.values.slice().reverse());
```
