### ISSUE TITLE
MapChart: positionning chart in a clusteredBullet

### ISSUE THREAD

**Issue by pvougny** [amcharts/amcharts5#1541]
**Question**

I'm using `am5map.MapChart` with `am5map.ClusteredPointSeries` to draw `am5percent.PieSeries`.
This is no longer possible since version 5.8.3. I've opened an issue: https://github.com/amcharts/amcharts5/issues/1540.

Considering the version **5.8.0** which allows this feature, when zooming, the charts (Pie charts in my example) in clustered points are not positionned properly. You have to drag the map to refresh the correct positions. I thought it could be due to animation but actually not. See my codePen that has zomming enabled with no animation:

https://codepen.io/pvougny/pen/gOEGLjd?editors=0011

Correct:
<img width="247" alt="correct" src="https://github.com/amcharts/amcharts5/assets/34480075/164dea66-f9f9-4152-b71f-f6d129f72b6e">

Not correct:
<img width="491" alt="not-correct" src="https://github.com/amcharts/amcharts5/assets/34480075/1a8f1051-0143-4762-8ab2-cbb054d759b9">

**Environment**

- amCharts 5.8.0
- Angular 15

**Comment by zeroin** [comment]
We will fix the chart issue in next release, the position problem is already fixed in current release.

**Comment by pvougny** [comment]
Works fine in version 5.9.11. Thank you!
