### ISSUE TITLE
How to apply the minBulletDistance option immediately when I change it

### ISSUE THREAD

**Issue by bossbelle** [amcharts/amcharts5#1542]
I'm trying to change minBulletDistance in a similar way to the code below.
However, changing that option does not reflect that option until you zoom in and out of the chart.
Is there a way?

Or can I hide the bullets of the series or change the opacity?

If I click on a legend that I made separately (not provided by amchart), I want to hide the bullet of other series except those that correspond to that legend.

 this.myChart.series.each(function(series) {
  if(series.className == "LineSeries")
  {
    series.set("minBulletDistance", 999);
  }
 })

**Comment by martynasma** [comment]
If you need to toggle bullets, better just toggle series bullet container on and off:

```JavaScript
// Hide bullets
series.bulletsContainer.hide();

// Show bullets
series.bulletsContainer.show();
```

**Comment by bossbelle** [comment]
Is it possible to change the bullets opacity or color?

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.
