### ISSUE TITLE
clicks on drawn elements

### ISSUE THREAD

**Issue by MasterTatto** [amcharts/amcharts5#1543]
I’m using a react application and I need to click on any drawing element and get its ID, so that I can then click either delete or select the element, do any manipulations, I’ve been looking for an answer for a week now and can’t find anything, HELP. I use a stock chart

**Comment by MasterTatto** [comment]
not work 
![image](https://github.com/amcharts/amcharts5/assets/74793187/48172ff3-67a7-4981-b7d3-83df10d1fc2d)
![image](https://github.com/amcharts/amcharts5/assets/74793187/9951ed5e-c5ea-4358-b298-36bf7da919f3)
![image](https://github.com/amcharts/amcharts5/assets/74793187/8da31616-9fb8-4002-ac49-828b93bcbb5f)
when I click on any drawn element, I don’t see anything in the console

**Comment by martynasma** [comment]
Selection mode needs to be on.

**Comment by MasterTatto** [comment]
i cant find "Selection mode" in documentation , can you write where i can on selection mode ? i try this, but console clear again 
![image](https://github.com/amcharts/amcharts5/assets/74793187/abdc7b20-ffb8-4314-ab42-791a41feb62a)

**Comment by martynasma** [comment]
Yes, that should be enough.

Can you check which version of amCharts 5 are you using? That event was added fairly recently.

**Comment by MasterTatto** [comment]
in react im use script 
![image](https://github.com/amcharts/amcharts5/assets/74793187/88b4a553-abd6-4e97-8475-f7bc2c499c4d)

**Comment by martynasma** [comment]
Are you using StockChart toolbar at all? If you do, selection mode is toggled via a button in Drawing mode.
