### ISSUE TITLE
How to optimize/load large number of data points in stockchart

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1545]
I am using stockChart : 
- I am using Lazy Loading to load data via panning and mouse wheel.
- The issue comes when there is more than 1000/1500 data points are loaded on the canvas.
- The scroll feel via mouse wheel, feels laggy while loading more data or zoom-in/out.
- If user uses panning then its fine .

My question is : 
- What are the different options I can try to enhance this, increasing frame rate or anything?
- If there is anything else we can do incase of Large number of data points.

**Comment by martynasma** [comment]
1.5K data points does not sound like a lot for a `StockChart`. Can you share your full chart/data on CodePen?

**Comment by workingbuddy10** [comment]
Sorry @martynasma my bad, its above 6k points.

- You can see in the below video the cursor lags and I was continuously scrolling yet the chart is not moving or responding little late.
- 

https://github.com/amcharts/amcharts5/assets/137867461/0ecfea48-8153-4cf4-bbd3-c7a03fd34b45

**Comment by martynasma** [comment]
That chart does not seem to be using any data point grouping. I suggest adding it.

**Comment by workingbuddy10** [comment]
True I am not using the data point grouping. The data points which you are seeing is an Intraday data ( 5min format).
Ideally the data grouping won't be good in this case.

**Comment by martynasma** [comment]
> Ideally the data grouping won't be good in this case.

Why not? User won't be able to see 3000 candles crammed into a chart individually anyway.
