### ISSUE TITLE
how to change display that first valueYChangePrevious

### ISSUE THREAD

**Issue by bossbelle** [amcharts/amcharts5#1546]
I'm using valueYChangePrevious to draw a chart.
The problem is that from the first value of each series
I want valueYChangePrevious to be marked with "-" instead of 0.
Is there a way?

**Comment by martynasma** [comment]
> I want valueYChangePrevious to be marked with "-" instead of 0.

Could you please clarify what you mean by "marked"? Is it a bullet, tooltip content, something else?

**Comment by bossbelle** [comment]
I'm using the valueYChangePrevious value in the tooltip
I want to write "-" when this value is 0

**Comment by martynasma** [comment]
I suppose you can use tiered number format for that:

```
root.numberFormatter.set("numberFormat", "#,###|#,###|'-'");
```

More info:
https://www.amcharts.com/docs/v5/concepts/formatters/formatting-numbers/#Positive_negative_numbers
