### ISSUE TITLE
how to round down using numberFormatter

### ISSUE THREAD

**Issue by bossbelle** [amcharts/amcharts5#1549]
I am using NumberFormatter as below code.

Is it possible to change the numberFormatter's Roundoff to RoundDown?

ex)  18,500,000 =>19M X   18,500,000 =>18M O

root.numberFormatter.setAll({
  numberFormat: "#a",
  bigNumberPrefixes: [
    { "number": 1e+6, "suffix": "M" },
    { "number": 1e+9, "suffix": "B" }
  ],
});

**Comment by martynasma** [comment]
Yes, just add a dot in your format: `"#.a"`.
