### ISSUE TITLE
How to use Range only for a portion of a chart

### ISSUE THREAD

**Issue by bossbelle** [amcharts/amcharts5#1551]
I would like to use the Range only for the Line Chart part in the same situation as CodePen below.

[myCode](https://codepen.io/-bossbelle/pen/KKYJgjJ?editors=0011)

**Comment by martynasma** [comment]
I'm afraid that's not possible.

The workaround would be to create to separate `XYChart` isntances with two separate axes, so you can add the range to just one of them.

You can add several `XYChart` objects into the same `Root` element.

**Comment by bossbelle** [comment]
My chart is already using 2 x-axes.
Do you mean I need to add a Chart object?

**Comment by martynasma** [comment]
> Do you mean I need to add a Chart object?

Yes. Exactly.
