### ISSUE TITLE
Pie Chart Grouper - Label template reset whenever the Grouper is clicked

### ISSUE THREAD

**Issue by chirmac** [amcharts/amcharts5#1552]
**Bug description**

When creating a simple Pie Chart, with a slice grouper, and setting the label template on the series to hidden, whenever a user clicks the grouped slice to break it or zoom to it, it overrides the template definitions and shows them again. If we zoom out, they stay visible.
I made a simple demo to test:

https://codepen.io/axglxieg-the-scripter/pen/pomJYEb

**Environment (if applicable)**

 - amCharts version 5.9.11
 - No frameworks

**Additional context**

No additional context needed

**Comment by martynasma** [comment]
Using `visible` is not reliable since it may be overridden by data update animations.

Use `forceHidden` instead:

```JavaScript
series.labels.template.set("forceHidden", true);
series.ticks.template.set("forceHidden", true);
```

**Comment by chirmac** [comment]
> Using `visible` is not reliable since it may be overridden by data update animations.
> 
> Use `forceHidden` instead:
> 
> ```js
> series.labels.template.set("forceHidden", true);
> series.ticks.template.set("forceHidden", true);
> ```

Solved, yet again. Thank you very much. I suggest mentioning that in the documentation, as I just copied the code from there and didn't really understand the string variables. Unless that already exists somewhere I didn't notice.
Thank you for you speed.
