### ISSUE TITLE
MapChart with PieChart in clustered points and zero clusterDelay

### ISSUE THREAD

**Issue by pvougny** [amcharts/amcharts5#1554]
**Bug description**

I'm using `am5map.MapChart` with `am5map.ClusteredPointSeries` to draw `am5percent.PieSeries`.
Since version **5.9.11**, the pie charts do not render in clusters, unless I set `clusterDelay` to a non-zero value. It should still render even with non-delayed clustering. It used to work in version **5.8.2**, whilst `clusterDelay` property did not exist.

Here a CodePen. You can change `clusterDelay` value at line 2.
https://codepen.io/pvougny/pen/abrWdbM?editors=0011

- `clusterDelay > 0`

<img width="235" alt="clusterDelay-1" src="https://github.com/amcharts/amcharts5/assets/34480075/07bb868c-525e-4e97-bcdb-577497d1c57f">

- `clusterDelay === 0`

<img width="233" alt="clusterDelay-0" src="https://github.com/amcharts/amcharts5/assets/34480075/5b596b18-77df-4138-a1e6-7fda9ed2c327">

**Environment**

- amCharts 5.9.11

**Comment by zeroin** [comment]
It's a really complicated issue. I can offer you this workaround:

```
  dataItem.on("children", function (children) {
    root.events.once("frameended", () =>{
      if (children) {
        // pie data
        const pieData = [
          { category: 'A', value: 10 },
          { category: 'B', value: 10 },
          { category: 'C', value: 80 },
        ];
        pieseries.data.setAll(pieData);
        
        // label: number of points
        label.set("text", children.length);
      }
    })    
  });
```

You should create a pie chart when frame ends, this way it should work fine.
I will try to solve it without this workaround, but can't promise anything at this point.

**Comment by pvougny** [comment]
Just tried the workaround in the CodePen. It works fine, thank you.
What about making data available in `dataItem` from `pointSeries.set("clusteredBullet", (root, series, dataItem) => { ... }`?

As I couldn't draw the pie charts, I opened the issue https://github.com/amcharts/amcharts5/issues/1341 dealing with that and I implemented the workaround with `dataItem.on("children", function (children) { ... }` that allowed me to access the data.

Then we could avoid both workarounds. What do you think?

Thank you for you feedback.

**Comment by pvougny** [comment]
I would imagine that `dataItem.dataContext` contains what contains `children` in `dataItem.on("children", function (children) { ... });`

```typescript
pointSeries.set('clusteredBullet', (root, series, dataItem) => {
  console.log(dataItem.dataContexts); // [{a: 1}, {a: 2}];

  dataItem.on("children", function (children) {
    console.log(children); // [{a: 1}, {a: 2}];
  });
});

pointSeries.data.setAll([{a: 1}, {a: 2}]);
```

**Comment by zeroin** [comment]
Internally we could do this only after children is set on clustered data item, so this would just duplicate things, as you can loop through children, and access dataContext of each child in your `dataItem.on("children", function (children) {` function.

**Comment by pvougny** [comment]
Sounds good to me, but the event `'children'` is not allowed without cast, otherwise Typescript does not recognize it. Nothing's provided in the documentation. I wouldn't have been able to deal with cluster data without opening an issue on Github.
