### ISSUE TITLE
how to get Max Value from Yaxis

### ISSUE THREAD

**Issue by bossbelle** [amcharts/amcharts5#1555]
I used 2 axis ranges like CodePen below so that only LineChart shows axis ranges.
However, in the actual code, the final value of Y-axis 2 is not a fixed value.

Is there a way to get the maximum value of the y-axis?
Or is there a way to set the axial range throughout the axis without setting the maximum value?

[myCodepen](https://codepen.io/-bossbelle/pen/KKYJgjJ)

**Comment by martynasma** [comment]
It seems you are using `CategoryAxis`. So, getting a final category is as easy as checking the last item in your data.

**Comment by bossbelle** [comment]
I'm using ValueAxis as the Y-axis. I need a way to get the maximum of the axis because the maximum of the axis of ValueAxis is always larger than the maximum of my data.

**Comment by martynasma** [comment]
Gotcha.

You can use private setting `max` for that. And you can watch for any changes:

```JavaScript
yAxis2.onPrivate("max", function(max) {
  console.log(max)
});
```

**Comment by bossbelle** [comment]
Using the Legendary Hide() function
Even if the maximum value of the y-axis changes
yAxis2.getPrivate ("max") displays the same value.

Is the maximum value that changes to the Hide() function of the legend impossible to detect?

**Comment by martynasma** [comment]
If you need to find out max of the current zoom, you can use private setting `selectionMax` instead.
