### ISSUE TITLE
How to remove empty space on the left and right sides of a chart

### ISSUE THREAD

**Issue by bossbelle** [amcharts/amcharts5#1557]
I want the contents of the chart to be attached to the y-axis.
However, if you zoom out or drag the chart, you will see the empty space as shown in the image below, and it will move away from the y-axis.

Is there a way to make sure this empty space doesn't show up?
[codepen](https://codepen.io/-bossbelle/pen/KKYJgjJ)
![image](https://github.com/amcharts/amcharts5/assets/122963338/9d139848-55a5-471a-871e-a99bdb56353d)

**Comment by martynasma** [comment]
You can use `maxDeviation` setting for that.

More info: https://www.amcharts.com/docs/v5/charts/xy-chart/zoom-and-pan/#Over_zooming
