### ISSUE TITLE
Get valueYChangeSelectionPercent on event

### ISSUE THREAD

**Issue by martin-konstantinov** [amcharts/amcharts5#1558]
Hello, I have the following listener: 

`xAxis.onPrivate("selectionMaxFinal", function (value, target) {
       // do stuff
// get valueYChangeSelectionPercent
// do more stuff
    });`

Here, xAxis is a DateAxis.

I need to get the value of "valueYChangeSelectionPercent" inside the callback and use it there whenever "selectionMaxFinal" value is changed. Can you advise me how to do that? Many thanks!

Edit: Here is an example of what I am trying to do
![image](https://github.com/amcharts/amcharts5/assets/160145904/caa5f60c-e92c-43e1-9c82-b3e46a9ded43)

I want to show the calculated value of the selected period (as if the user hovered over the last data point) in the table below for each line in the series. Hope this helps!

**Comment by zeroin** [comment]
Here is how you can do it:

```
dateAxis.onPrivate("selectionMaxFinal", function (value, target) { 
  var lastItem = dateAxis.getSeriesItem(valueSeries, dateAxis.toAxisPosition(1));
  console.log(lastItem.get("valueYChangeSelectionPercent"));
});
```
