### ISSUE TITLE
Column/Bar Charts X-axis Labels misaligned on smaller screens

### ISSUE THREAD

**Issue by kvaldillez** [amcharts/amcharts5#1559]
**Bug description**
The labels on the X-axis become misaligned with their respective columns when viewed in smaller containers (approx. <= 430px wide in this case).

You can reproduce on the amCharts 5 documentation page [here](https://www.amcharts.com/docs/v5/concepts/common-elements/labels/) via the codepen example under "Interactive axis labels". It is also reproducible if you click "Edit on Codepen" and make the chart smaller there. I've attached a screenshot of both examples below with the alignment highlighted in red.

Note: It is easier to observe if you open dev tools to make the chart smaller vs. making the browser window smaller.

![amCharts-5-codepen-example](https://github.com/amcharts/amcharts5/assets/13121777/8820a4c0-2a21-4f8c-9447-9a12177b5aa8)
![amCharts-5-documentation-example](https://github.com/amcharts/amcharts5/assets/13121777/8451a5de-caf5-47e9-9137-9407fb355134)

**Environment (if applicable)**
- Reproducible in amCharts 5
- Browser: Google Chrome Version 124.0.6367.209 (Official Build) (x86_64)

**Comment by martynasma** [comment]
When there's too little space, and axis starts to skip grid/labels/categories, it moves labels to the start of the multi-category cell so that it does not misrepresent the data.

You can revert that using `multiLocation` setting for your axis labels:

```JavaScript
xRenderer.labels.template.setAll({
  tooltipText: "{category}",
  oversizedBehavior: "truncate",
  maxWidth: 100,
  multiLocation: 0.5
});
```

Related docs:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#multi-location

**Comment by kvaldillez** [comment]
That seems to have worked, thanks!
