### ISSUE TITLE
There seems to be a bug in amchart5.

### ISSUE THREAD

**Issue by skulter** [amcharts/amcharts5#156]
There seems to be a bug in amchart5.
The two charts below are charts using the same component.
The chart above shows values from 0 to 100,000,000,000, and the chart below is a chart with data from 0.0 to 100.0.
But the chart above shows the data properly and the chart below doesn't show the data properly.

![image](https://user-images.githubusercontent.com/18344213/146490755-909b1be6-ad5b-430b-8434-5b46c729673b.png)

code :
      var yAxis = chart.yAxes.push(
                     am5xy.ValueAxis.new(root, {
                          min:0.0,
                          max:100.0,
   
                         renderer: am5xy.AxisRendererY.new(root, {})
                     })
                 );

![image](https://user-images.githubusercontent.com/18344213/146490820-bfe4088a-bbd5-46cf-8315-cdf7006d25e7.png)

If I use the min and max values in the code, the chart is displayed, but what I want is the max value to be displayed as the max value of my data.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
