### ISSUE TITLE
ENHANCEMENT : Wheel event in the stockChart (on- demand loading)

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1561]
I am using the on-demand loading example for loading more data by wheel.
The issue I am facing is when the chart has large number of data points & then I scroll/wheel The chart firstly shifts back and then load more data and then move forward.
The  panning works perfectly fine!

https://github.com/amcharts/amcharts5/assets/137867461/4cf54cdc-59b4-4709-98cb-2cb58d2ee4df

Below is code I am using on the wheel event, and the data granularity is 1 min.
```
    let absoluteMin = new Date(1900, 0, 1);
 
    mainPanel.events.on("wheelended", function() {
      if (wheelTimeout) {
        wheelTimeout.dispose();
      }
    
      wheelTimeout = $this.chartInstance.dateAxis.setTimeout(() => {
        loadScrollData();
      }, 50);
    });
    
    function loadScrollData() {
      let start = $this.chartInstance.dateAxis.get("start");
      let selectionMin = Math.max($this.chartInstance.dateAxis.getPrivate("selectionMin"), absoluteMin);
      let min = $this.chartInstance.dateAxis.getPrivate("min");
    
      if (start < 0) {
        let timeDifference = min - selectionMin;
        let candleCount = Math.floor(timeDifference / (60 * 1000));
        if(candleCount >=300) candleCount = 300;
 
        $this.chartInstance.chartInstanceDataStore.requestMoreDataOnPan(candleCount);
        
        $this.chartInstance.dateAxis.set("min", min);
        $this.chartInstance.dateAxis.setPrivate("min", min); 
        $this.chartInstance.dateAxis.zoom(0,1,0);
      } 
    }

```

any event I can try of applying in dateAxis?

I want something like this : 

https://github.com/amcharts/amcharts5/assets/137867461/518a91dd-b7f0-4e5a-9202-5a2e9144420f

**Comment by workingbuddy10** [comment]
any event I can try of applying in dateAxis?

**Comment by workingbuddy10** [comment]
Below is the video of the amcharts example of the on-demand loading, inital when points are less it seems fine.
Once the data points are more and then scroll the whole candles firstly goes to the left then they shift/jump to the right.

https://github.com/amcharts/amcharts5/assets/137867461/61d0eafb-b002-4ae5-a688-eb6eae178e9b

https://www.amcharts.com/docs/v5/tutorials/incremental-on-demand-data-loading/

**Comment by workingbuddy10** [comment]
@martynasma any help / guidance on this will be very helpful on this!!

**Comment by martynasma** [comment]
We'll need some runnable repro case to check this. Can't debug a video.

If you'd do it, make it as simple as possible, so there's less moving parts.

**Comment by martynasma** [comment]
I'm afraid I don't understand what "right side data adding part" means.

Would you be able to make a CodePen that exhibits the issue?

**Comment by workingbuddy10** [comment]
- When there is more than 1000 data points and I scroll The candlesticks goes to the right to create the space and then shifts to left.

* Whereas the candles should have just shifted to the right side to create the space for the new candles ( like it happens in panning) and plot the new data points. 
something like this : 


https://github.com/amcharts/amcharts5/assets/137867461/1331e952-7b31-4771-b729-3f4278e445f7



codepen    : https://codepen.io/Ansh-m-the-reactor/pen/eYaGGbw



Just for reference :  when you do similar behaviour in the TradingView you can see the difference, just use there scroll feature. Load 1000 or more data points and scroll.
@martynasma

**Comment by martynasma** [comment]
I'm afraid we won't be able to accommodate this request.

BTW, TradingView allows overzooming in both directions using mouse wheel.

**Comment by workingbuddy10** [comment]
True @martynasma TradingView do allow overzooming.
My concern is not overzooming, I am only concern that when number of points in the chart exceeds after 1100 and then we try to scroll to load more data the behavior of the chart is not correct ( rest data gets plotted).

What happens in amcharts when load data via scroll ( mouse wheel) : 
 - Firstly the candles shrinks/move towards the right direction AND then shifts to the left direction

Whereas in TradingView : 
- The candles do shift to the right direction when we scroll to load more data, but it doesn't shifts back to the left direction.

Just see this video you get what I am trying to say : 
 - Initially I created a Vertical line in amcharts, and then loaded the data via scroll. You can see the Vertical line movement, it goes to right first then move to left.

- Then I did the same in the TradingView, the Vertical line just moved to the right to the fix position.


https://github.com/amcharts/amcharts5/assets/137867461/01eb6d07-3678-4cd2-ac9e-6661d6364796

**Comment by workingbuddy10** [comment]
Hope @martynasma you got the point !?

**Comment by martynasma** [comment]
I can see you closed this, but just in case, this is a very simple demo that shows smooth infinite loading of data for overzoom:
https://codepen.io/team/amcharts/pen/ZENawbv??editors=0010

**Comment by workingbuddy10** [comment]
Thanks for the help @martynasma 
Though I achieved the results, but surely you way looks more clean to me rather than my approach!!!
