### ISSUE TITLE
Date on the X-axis of LineChart don't match the date of the point

### ISSUE THREAD

**Issue by suu3** [amcharts/amcharts5#1565]
**Bug description**
  
Hello.
There are cases where the date on the X-axis of the LineChart don't match the date of the point, and I am curious why this happens.
This is a codepen example that reproduces the issue. (The date of the point is June 11, but it is plotted after Jun 15.)
https://codepen.io/suu3/pen/LYozybY?editors=0010

**Comment by workingbuddy10** [comment]
@suu3  maybe this issue helps you : #1560

**Comment by suu3** [comment]
> @suu3  maybe this issue helps you : #1560 

Thank you for your help.
But I think my situation seems to be different from that issue.
In my case:
1. It is strange that the position of the point on June 11 is to the right of the position of June 15 on the x-axis.
2. Since the two points have 90 days of spacing and the baseInterval is 30 days, I thought the spacing would be just right, but it is not.
