### ISSUE TITLE
Overlapping candles in stock chart

### ISSUE THREAD

**Issue by prackode** [amcharts/amcharts5#1566]
I am using stock chart of amcharts5, I am getting a stream data via SSE from a data source. The issue is sometimes the data source sends the duplicate data or the in incorrect order of data points. 
Which leads to overlapping candles.

So the issue is not on the amcharts side, its on my end. Just looking for a help anyhow I can handle this use-case ?

**Comment by martynasma** [comment]
amCharts does not have built-in handling of faulty data. Unless you can fix the data at the source, you will need to pre-process the data to weed out the duplicates, and sort it properly before supplying to the chart.
