### ISSUE TITLE
How to change default node behaviour on Chord Diagram in amcharts 5

### ISSUE THREAD

**Issue by ankurssharma96** [amcharts/amcharts5#1568]
Hello,

I am using amCharts to create a simple chord diagram. I would like to define a custom behaviour/tooltip when the user clicks/hover on a node.

To this end, I would also like to disable the default behaviour of collapsing a node when it is clicked.

**Comment by martynasma** [comment]
Please refer to this tutorial:
https://www.amcharts.com/docs/v5/charts/flow-charts/#Disabling_toggling

**Comment by ankurssharma96** [comment]
The above reference helped in collapsing the node on being clicked, Thank You!

Can you also provide some reference to capture the click event over node, have tried something like this, but it did not help

`series.nodes.nodes.template.events.on("click", (event)=>{console.log(get(event, 'target.dataItem.dataContext.id'))});`

**Comment by martynasma** [comment]
Try this:

```JavaScript
series.nodes.rectangles.template.events.on("click", (event) => {
  // ...
});
```

**Comment by ankurssharma96** [comment]
Hi @martynasma, thanks for providing the reference but its not helping. There's no event getting triggered on node being clicked.

**Comment by martynasma** [comment]
Make sure you set events **before** setting data on series.

**Comment by ankurssharma96** [comment]
It helped. Thanks a lot!
