### ISSUE TITLE
Tooltip changes color during fade

### ISSUE THREAD

**Issue by rywall** [amcharts/amcharts5#1569]
You can see this issue on the Mutating target element example here: https://www.amcharts.com/docs/v5/concepts/settings/adapters/#Mutating_target_element

Specifically this example: https://codepen.io/team/amcharts/pen/abjbZyr

Before the tooltip fades out it reverts to a blue color. It seems like an issue with `getFillFromSprite` not working correctly during the fade.

https://github.com/amcharts/amcharts5/assets/7904/25ef7c63-75f9-48a7-bd73-030e44aa82c9

**Comment by zeroin** [comment]
When cursor is out of plot area, tooltip uses series fill color, that's why it happens. You can fix it by changing series fill when tooltip data item changes:

```
series.on("tooltipDataItem", function(dataItem) {
  if (dataItem) {
    var column = dataItem.get("graphics");
    series.set("fill", column.get("fill"));
  }
})
```

**Comment by rywall** [comment]
@zeroin makes sense to me. Thanks for the quick response.
