### ISSUE TITLE
Pie series labels overlapping

### ISSUE THREAD

**Issue by paulo-lada** [amcharts/amcharts5#157]
Hello, i'm using the pie series, pretty solid graph btw.
I'm build the chart in a screen with tabs, and when the chart is built off screen cause another tab is showing, it's all good, but when i build the chart with it's tab visible the labels overlap each other and if I manually move the browser window they fit well again.
Is there a fix to this?
Thx in advance.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by paulo-lada** [comment]
Hello martynasma, I fixed it by adding 
        sequencedInterpolation: true,
        sequencedDelay: 100
and series.appear() to the pie series.
Thanks for you attention.

**Comment by martynasma** [comment]
Thanks for the update!

Feel free to close this if you're all set.
