### ISSUE TITLE
Mutli Date Axis with columnSeries 

### ISSUE THREAD

**Issue by pratham3164** [amcharts/amcharts5#1570]
I'm trying to build a multi-dateAxis ColumnSeries chart. I am able to load the data but the columns of the second dateAxis seem to overlap the first dateAxis column( attaching an image for reference)

![image](https://github.com/amcharts/amcharts5/assets/44560611/99badae7-abb9-47af-9de3-8b11caa8d96f)

Is there a way where I can have those columns next to each other in the same grid instead of overlapping ??

**Comment by zeroin** [comment]
Try to add two additional column series to the second axis with no data.

**Comment by pratham3164** [comment]
no it doesnt work.  I want it to be next to each other like (img2) instead of (img1)
![image](https://github.com/amcharts/amcharts5/assets/44560611/d6524fec-ae5f-48d1-936d-d0b91c7688bb)
(img1)
![image](https://github.com/amcharts/amcharts5/assets/44560611/efd35c0c-f5dd-4444-837b-8f15887e380d)
(img2)

**Comment by zeroin** [comment]
Here is modified pen:
https://codepen.io/team/amcharts/pen/WNBdERV

I added one empty series to the xAxis0 and two empty series to xAxis1. This way each axis has the same number of series added.

**Comment by pratham3164** [comment]
Hi @zeroin, thanks for the answer. but is there any other direct approach to achieve the desired output ?

**Comment by zeroin** [comment]
I am afraid no.

**Comment by pratham3164** [comment]
any possibilities of further updates to support this functionality inbuilt?

**Comment by zeroin** [comment]
No, I don't think so. It's a very rare setup and I think the solution we offered is simple enough.

**Comment by pratham3164** [comment]
@zeroin. oh ok. thanks for your time

**Comment by pratham3164** [comment]
@zeroin . With the above solution, I want to know that if I load legends for my chart then how  can I skip legends for the additional point that we added keeping other functionalities like disabling of legends to hide unhide  data  intact

**Comment by zeroin** [comment]
Data of the legend is array of series. So you simply just don't include these empty series into the array.

**Comment by pratham3164** [comment]
hi checked the documentation but could not find anything other than custom legends. If I use that I  don't get the functionality of hiding  the series data on clicking the respective legend.

**Comment by zeroin** [comment]
You don't need custom legend. Just pass array of series to the legend data:

`legend.data.setAll([series0, series1, series2])`

Do not include the fake series there.

**Comment by pratham3164** [comment]
@zeroin  thanks alot. This works .
