### ISSUE TITLE
GaplessDateAxis showing wrong year in axis after zooming

### ISSUE THREAD

**Issue by beeptheboop** [amcharts/amcharts5#1572]
**Question**
I'm having a problem with GaplessDateAxis where the axis is showing 2022 when there is only data from 2023 showing. I have data from 2022 in the chart but is not being showed by the current zoom. I've also noticed that this problem depends on the timezone of the user. When I set my timezone to Western European Time everything looks okay, but in Eastern Time I get this issue. Any ideas on how to fix it?

https://github.com/amcharts/amcharts5/assets/53227495/40d9c14f-309a-4934-a822-b36b6c1cd92e

Here is a demo with the same issue: https://codepen.io/M-rcia-Martins/pen/VwOyVbj
If you change your timezone to New York, for example, you can see 2021 showing in the axis even thought there is only data starting from 2022-01-01.

**Environment (if applicable)**
Latest version of amcharts5 in React

**Comment by martynasma** [comment]
You are using "YYYY" in period change format, which means "year of week". You should use "yyyy" to display actual year.

More info: https://www.amcharts.com/docs/v5/concepts/formatters/formatting-dates/#format-codes

**Comment by beeptheboop** [comment]
That was the problem, thank you! 🙏
