### ISSUE TITLE
How can the start day of a week on a DateAxis be specified for week grouping?

### ISSUE THREAD

**Issue by AericN** [amcharts/amcharts5#1573]
<img width="505" alt="Screenshot 2024-06-17 at 2 06 01 PM" src="https://github.com/amcharts/amcharts5/assets/16948082/7cf29c30-a33d-4e47-b0b4-7d2c4bc00a05">

Hi, I have a use case where I need to group data from a Sunday-Saturday range. In AmCharts 4 it looks like there was a field for 'firstDayOfWeek' that could be specified but I do not see that as an option for AmCharts 5. Currently it appears to be grouping by 7 days as 'weeks' with the current day being the end of the range. 

As a more specific example, Today is Monday 6/17 and the range on the chart shows the most recent week as 6/10-6/17. I'd like the ranges to always start on Sundays so the last range in the chart should show 6/16-6/23. Is there a built in way to do this without custom formatters/adapters?

**Comment by martynasma** [comment]
You can specify first day of week via locale in amCharts 5:
https://www.amcharts.com/docs/v5/getting-started/root-element/#First_day_of_week

**Comment by AericN** [comment]
Thank you!
