### ISSUE TITLE
Displaying xAxis labels for all vertically stacked axes chart;

### ISSUE THREAD

**Issue by VladutZsukan** [amcharts/amcharts5#1574]
Is it possible to display xAxis labels for all series? In the example below, when you move the cursor, the xAxis labels also moves.

https://www.amcharts.com/demos/vertically-stacked-axes-chart/

Why i need this behaviour? :  I need to sync 2 different charts to display the same xAxis labels and i manage to achieve half of the behaviour by using the xAxis from first chart on the second one but the second one does not have labels: 
![image](https://github.com/amcharts/amcharts5/assets/86416235/10d38fb5-490e-497c-ac20-e124ca88b732)

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by VladutZsukan** [comment]
Thanks for response @martynasma .

I need for this example to display the xAxis labels for all the charts,not only when you hover the mouse : https://codepen.io/pen?&prefill_data_id=ae8aeb8e-0eeb-4b7e-9c91-91d4a804f577

**Comment by martynasma** [comment]
Getting a 500 error on that link. Can you save the CodePen?

**Comment by VladutZsukan** [comment]
is the same example as the one made on this link : https://www.amcharts.com/demos/vertically-stacked-axes-chart/. 

Basically what I want to achieve is to display xAxis labels for all charts, not to move depending on which chart the cursor is on.

**Comment by martynasma** [comment]
Probably easier to just create multiple synced charts than use stacked axes for that.

Example:
https://www.amcharts.com/docs/v5/tutorials/syncing-axis-zooms-across-multiple-charts/
