### ISSUE TITLE
High memory usage warning

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1575]
When I hover on the app in chrome, initially it shows around 200-300 mb of memory usage. And when I keep open the app for a while ( maybe an hour or so) the memory usage grows to 1GB, and if I kept it overnight then sometimes it goes to 2gb too.

My JS heap memory is around 200 mb.
I have a Live stream data coming continuously via SSE endpoint.

What my app looks like :
- I have multiple workspace feature.
- I have multi-chart layout (which goes till 4*4) in a single workspace. And each chart instance is different root, so I don't just push the new stock chart.
-  Each UNIQUE product creates its SSE connection.
- And I hold the state, as in if a user switches from workspace 1 to workspace 2 and again switches back to workspace 1. Then I don't again re-create the root/amcharts & plot the data.   

I just wanted to know what can be a possible reason of this memory growth? Or which are the things I should look around! Is amcharts canvas is growing or increasing the memory consumption?

**Comment by martynasma** [comment]
It's impossible to tell just from the description. Can you create an isolated repro case?

**Comment by workingbuddy10** [comment]
I can understand appropriate answer would be hard, just from the description! Sorry @martynasma  for asking this to you!

Though there is not an very exact repro case, because of the different setup we have!

Can you help me with? 
Like when we hover on the tab we can see a memory usage number, Exactly how it is calculated and what all components it considers & as a developer where I can see? 
Because via the dev tools I can only cross-verify my JS heap memory size or cpu usage and all.

See this comes when I hover on my tab : 
you can see a multi-cross layout and memory usage info : 
![img](https://github.com/amcharts/amcharts5/assets/137867461/bb9bd961-8d69-4c23-83f8-b7b4d736f098)

**Comment by martynasma** [comment]
I understand that you might not be able to provide us with a 1:1 setup.

However, I'm sure you can replicate a single chart setup + very basic repro of what you are doing with the updates.

It's not necessary to reproduce a memory leak in the same scale. It's enough to reproduce it to be able to try to solve it.

We can't do that looking at a photo of your screen. Sorry, mate.
