### ISSUE TITLE
Mutli Date Axis with different date ranges for each date axis

### ISSUE THREAD

**Issue by pratham3164** [amcharts/amcharts5#1577]
Hi,
I am working on XYChart with multiple date Axis on the x-axis.

reference code : https://codepen.io/ErPratham/pen/oNRoroB .

In my  reference code I have 2 dateAxis on  the x-axis.
and both have different period range 
dateAxis 1 : from 1st January to 31st January 
and 
dateAxis 2: from 1st February  to  28th February. both axis with one record each day.
the chart adjusting the dates on the x-axis does not align the days day wise.
![image](https://github.com/amcharts/amcharts5/assets/44560611/42dd4ff7-360d-45b0-b27d-f94eeae36251)

As per my requirement I want the dates to be aligned aligned properly right above each other and the additional dates being pushed at the end with trailing empty  dates for the axis with  lesser dates to render 
For example.
![image](https://github.com/amcharts/amcharts5/assets/44560611/0c3e232e-1a7f-4f8d-9bf3-082f8d591179)

Any help would be appreciated.
Thanks in advance

**Comment by martynasma** [comment]
I'm afraid there's no way to make two separate DateAxis using two separate ranges align.

I'm not sure how that would even work with different months having different number of days.

I suppose you could create some fuzzy logic like this:

1. Find out the highest number of days present in both data sets.
2. Calculare and set `max` on an axis that has less days, to add the "missing" days, so that both axes have equal number of days, and therefore align.

**Comment by martynasma** [comment]
`max` should be set to a timestamp that corresponds start timestamp + X days.

**Comment by pratham3164** [comment]
@martynasma but this will show additional dates out of the range specified. is there a way where I can show "-" instead of the + Xdays

**Comment by martynasma** [comment]
Yes, it would.

I suppose you can use an adapter to selectively hide "out of range" labels:
https://www.amcharts.com/docs/v5/concepts/settings/adapters/

E.g.:

```JavaScript
xAxis.get("renderer").labels.template.adapters.add("visible", function(visible, target) {
  return target.dataItem && (target.dataItem.get("value") > maxTimestamp) ? false : visible;
});
```

**Comment by pratham3164** [comment]
@martynasma  This solution works but when i zoom in it shows the labels that were hidden but when i zoom out it hides back

**Comment by martynasma** [comment]
Try `forceHidden` instead:

```JavaScript
xAxis.get("renderer").labels.template.adapters.add("forceHidden", function(forceHidden, target) {
  return target.dataItem && (target.dataItem.get("value") > maxTimestamp) ? true : forceHidden;
});
```

**Comment by pratham3164** [comment]
@martynasma  this one too does not work.
and 

> I'm afraid there's no way to make two separate DateAxis using two separate ranges align.
> 
> I'm not sure how that would even work with different months having different number of days.
> 
> I suppose you could create some fuzzy logic like this:
> 
> 1. Find out the highest number of days present in both data sets.
> 2. Calculate and set `max` on an axis that has less days, to add the "missing" days, so that both axes have equal number of days, and therefore align.

this doesn't seem to work in case of  GaplessDateAxis.

**Comment by martynasma** [comment]
> this one too does not work.

It does work:
https://codepen.io/team/amcharts/pen/vYwjmRV/94873686ed24be9d3ccf57030fc1d288

> this doesn't seem to work in case of GaplessDateAxis.

`GaplessDateAxis` is not compatible with `max` or `extraMax`. The whole point of it is to display only those days/periods that have actual data items.

**Comment by pratham3164** [comment]
> It does work:
https://codepen.io/team/amcharts/pen/vYwjmRV/94873686ed24be9d3ccf57030fc1d288

will check it again.

>GaplessDateAxis is not compatible with max or extraMax. The whole point of it is to display only those days/periods that have actual data items.

OK

**Comment by pratham3164** [comment]
> https://codepen.io/team/amcharts/pen/vYwjmRV/94873686ed24be9d3ccf57030fc1d288

@martynasma  It doesn't,. If you zoom in to those dates that is. both solutions work normally but if we zoom in those hidden dates then those dates shows up.

**Comment by pratham3164** [comment]
yes this works thanks
