### ISSUE TITLE
How to handling jagged pie charts slices and spotty area line charts

### ISSUE THREAD

**Issue by SDVII** [amcharts/amcharts5#1578]
**Question**

* Is there a way to increase anti aliasing or reduce the jaggedness of Pie Charts?
![Screenshot 2024-06-19 at 14 21 12](https://github.com/amcharts/amcharts5/assets/10416702/602f8370-674b-4372-8019-9ad20571f938)
* Is there a way to mitigate area charts having rendering issues with fill?
![Screenshot 2024-06-19 at 13 48 30](https://github.com/amcharts/amcharts5/assets/10416702/ae6dfa5d-af31-4efe-95e6-49373c0cc8e7)

Thank you for your time

**Environment (if applicable)**

 - amCharts v5.8.0
 - Microsoft Edge v126.0.2592.61
 - React v18.2.0

**Comment by martynasma** [comment]
That does not look right. Can you provide a working demo?

**Comment by SDVII** [comment]
Here is a Codepen for the Pie Chart. As you can see, the stroke around each slice is quite jagged
https://codepen.io/team/amcharts/pen/eYWGPMJ

**Comment by SDVII** [comment]
Here is a Codepen for the Area Chart. This issues seems to only affect Mac devices

- Pen: https://codepen.io/SDVII/pen/YzbaYGV?editors=0010
- OS: Sonoma v14.5
- Browser: Chrome v126.0.2592.61
- Screenshot:
![Screenshot 2024-06-21 at 10 36 54](https://github.com/amcharts/amcharts5/assets/10416702/d6ff9251-5123-4d7e-89a9-2e9641e93f9d)
- Recording
https://github.com/amcharts/amcharts5/assets/10416702/16dfc249-8e6a-4a7d-862e-c29060f3439f

**Comment by martynasma** [comment]
> Here is a Codepen for the Pie Chart. As you can see, the stroke around each slice is quite jagged 

Unfortunately, there's nothing we can do about it. That's how canvas rendering works in browser.

**Comment by martynasma** [comment]
> Here is a Codepen for the Area Chart. This issues seems to only affect Mac devices

I can't seem to be able to reproduce it on a Macbook Pro.

Same OS version. Chrome: 126.0.6478.115.

Can you try upgrading Chrome?

**Comment by SDVII** [comment]
Upgraded the browser, still encountering the issue. Multiple people on my team are encountring it as well

**Comment by SDVII** [comment]
Safari & Firefox are working just fine

**Comment by martynasma** [comment]
Still not able to reproduce it. There's a newer version of Chrome now available. Maybe try an upgrade?

If it's still buggy, maybe you can provide more information about your setup? E.g. are you using external monitor? What is the resolution? Anything else?
