### ISSUE TITLE
Is it possible to transform all move-, wheel– and scroll-events to passive?

### ISSUE THREAD

**Issue by m4w** [amcharts/amcharts5#1579]
**Question**

Since I have many am charts on a single page (with cursor enabled), each chart possibly contains many data points. 
I noticed, that scrolling gets more laggy each time a chart is added. 
Also I get a warning by chrome, that I should use passive event-handlers.
So I was wondering, if you are able to increase the performance of AmCharts5 even more by using passiv eventhandlers.
I guess your listener functions do not use the `event.preventDefault`, therefore it should be a very minor change, with a big impact (hopefully).

I am using AmCharts 5.9.12

**Comment by martynasma** [comment]
We'd like to experiment with this.

Would you be able to post a sample of your chart including code and data, so that we can use it as a reference to your setup?
