### ISSUE TITLE
Tooltip on DateAxis

### ISSUE THREAD

**Issue by pratham3164** [amcharts/amcharts5#1581]
I am working on XYChart and have enabled the tooltip for the date axis as seen in the below-pasted image

 ![image](https://github.com/amcharts/amcharts5/assets/44560611/7e8fef7d-af5f-4235-b81e-c2d2affe5d8c)

there seems to be a mismatch in the dates shown on the tool tip when I hover over any of the data bars.
as per my expectation  both should show the same dates which is not happening

![image](https://github.com/amcharts/amcharts5/assets/44560611/b14cb4c7-d421-4838-ac05-dce15c8c51fb)

this is noticed when I have one a record of every alternate hours and when zoomed in to data it shows proper 
![image](https://github.com/amcharts/amcharts5/assets/44560611/ab45103d-f73c-4188-a6be-eec195cab01a)

and in the above image if you see the labels happen to overlap each other

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by pratham3164** [comment]
@martynasma  any updates ?

**Comment by martynasma** [comment]
Try enabling snapping of cursor to series:

```JavaScript
var cursor = chart.set(
  "cursor",
  am5xy.XYCursor.new(root, {
    behavior: "zoomX",
    snapToSeries: chart.series.values
  })
);
```

**Comment by pratham3164** [comment]
I'm afraid it does not work for me. if used it mismatch persists while showing only the points data tooltip on which I hover.
in the above case .  have 2 points so when hovering over the chart it shows a tooltip for both the points and the date on the axis but after using above suggested solution it shows only the point that is hovered open with the wrong date in the axis tooltip.

**Comment by martynasma** [comment]
Try adding `snapTooltip: true` to all series, too.

https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/#Irregularly_spaced_data

**Comment by pratham3164** [comment]
> Try adding `snapTooltip: true` to all series, too.
> 
> https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/#Irregularly_spaced_data

nope not working

**Comment by martynasma** [comment]
Can you actually reproduce it in the modified CodePen?

https://codepen.io/team/amcharts/pen/wvLBJmw/afc1f1d0e704db98df5613fcb38a8651

**Comment by pratham3164** [comment]
> Can you actually reproduce it in the modified CodePen?
> 
> https://codepen.io/team/amcharts/pen/wvLBJmw/afc1f1d0e704db98df5613fcb38a8651

@martynasma  It occurs in the given codepen url if you hover over any  column the dates shown are not much 
![image](https://github.com/amcharts/amcharts5/assets/44560611/9c51331b-c533-4a34-afd9-ac308d5a3576)

**Comment by martynasma** [comment]
Just add `snapTooltip: false` on your X-axes.
