### ISSUE TITLE
how to handling dataItem in labels template setup

### ISSUE THREAD

**Issue by kindunq** [amcharts/amcharts5#1582]
**Question**

I have questions

1. I want to use a custom color embedded in the data as the background color for a word cloud chart.
```
 series.labels.template.setup = function (target) {
        const targetColor = target.dataItem.dataContext.color; <===undefined
        const bg = target.set(
          "background",
          am5.RoundedRectangle.new(root.current, {
            fill: am5.color(targetColor),
          })
        );

        bg.states.create("hover", {
          fill: am5.color(targetColor),
        });
      };
```
const targetColor = target.dataItem.dataContext.color; 

That constant is output to the console. 

Why can't I access the dataItem to use it?

Also, when I take a picture of the console, it's incredibly slow and I can't figure out why.

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
At the moment the `setup` function kicks in, the data item is not yet set.

You may need to use an event `dataitemchanged`:

```JavaScript
target.events.once("dataitemchanged", function(ev) {
  console.log(ev.target.dataItem.dataContext.color);
});
```

**Comment by kindunq** [comment]
thank you so much,,,,,,,,,,,,,,,,,
