### ISSUE TITLE
DateAxis Labels overlapping

### ISSUE THREAD

**Issue by pratham3164** [amcharts/amcharts5#1583]
![image](https://github.com/amcharts/amcharts5/assets/44560611/a7c3dc38-c17c-4e80-873b-e8b83088025c)
Date axis labels overlap each other for groupData: false
baseInterval :{ timeUnit: "second", count: 1 }
groupIntervals : [
		{ timeUnit: "second", count: 1 },
            { timeUnit: "minute", count: 1 },
            { timeUnit: "hour", count: 1 },
            { timeUnit: "day", count: 1 },
            { timeUnit: "month", count: 1 },
            { timeUnit: "year", count: 1 }
        ]

**Comment by martynasma** [comment]
Your `minGridDistance` value might be too low.

More info: https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#grid-density
