### ISSUE TITLE
The Chrome browser is using more than 1 gigabyte of memory.

### ISSUE THREAD

**Issue by kindunq** [amcharts/amcharts5#1585]
**Question**

```
const drawChart = useCallback(() => {
    if (id) {
      root.current = am5.Root.new(`wordCloud_${id}`);
      const themeName = themes === "dark" ? am5themes_Dark.new(root.current) : am5themes_Animated.new(root.current);

      handleSetRootTheme(root.current, themeName);

      const container = root.current.container.children.push(
        am5.Container.new(root.current, {
          width: am5.percent(100),
          height: am5.percent(100),
          layout: root.current.verticalLayout,
        })
      );

      // background setting
      series.labels.template.setup = (labels) => settingBackground(labels, root.current);

      series.labels.template.events.on("click", function (ev) {
         ...some logic
      });

      series.labels.template.events.on("rightclick", function (ev) {
        ...some logic
      });

      // hover 이벤트
      series.labels.template.events.on("pointerover", function (ev) {
         ...some logic
      });

      series.labels.template.events.on("pointerout", function (ev) {
      ...some logic
      });

      series.labels.template.events.on("wheel", function (ev) {
      ...some logic
      });


      series.data.setAll(search);
    }

  }, [id, themes, search, color, selected]);

  useEffect(() => {
    if (root.current) root.current.dispose();
    drawChart();

    return () => {
      if (root.current) {
        root.current.dispose();
        root.current = null;
      }
    };
  }, [drawChart, id]);
```
Thank you for providing such a great open source.

I am using amchart5 in my nextjs application.

I keep getting memory leaks in the browser when I put multiple charts on one screen .

I searched and saw that it says to ref the root instance.

When useeffect's cleanup function is executed

"root.current = null", but it doesn't have any effect.

Is there something wrong with my code?

Is it because I'm not calling the event.off method?

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
You need to dispose the root element `root.dispose()`.

https://www.amcharts.com/docs/v5/getting-started/root-element/#disposing

**Comment by workingbuddy10** [comment]
Hello @kindunq , I am also facing a bit similar problem.
>I searched and saw that it says to ref the root instance.
How did you came to know this ?

When I hover on the tab I get to see this : 
![image](https://github.com/amcharts/amcharts5/assets/137867461/84f8a767-d2ef-46ab-ac7a-4f2b4540accb)
