### ISSUE TITLE
Unable to sync the cursor in multi-series in stock chart

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1587]
My Date axis is not synced properly, I even tried adding mingridistance to 0.Then too it didn't worked.

![image](https://github.com/amcharts/amcharts5/assets/137867461/f6f4b2db-0f9f-40eb-b158-1b56d5ac301e)

See this unusual behavior, if I am hovering on the same candle if I hover a little bit right it goes to 24th else it stays on 23rd.

https://github.com/amcharts/amcharts5/assets/137867461/82d71f65-f5d9-4111-add5-2af6ba0fceaf

I want If I am hovering on the 24th June candle then the below series cursor should point out to the 24th June only.

codepen to replicate the issue ( in comparison series tab Add APPLE ) : https://codepen.io/Ansh-m-the-reactor/pen/YzbvxbV?editors=1010

Note: There can be irregularity in both the chart data

**Comment by workingbuddy10** [comment]
Closing this issue, It got fixed when I applied filtration to the series data and used GaplessDateAxis.

**Comment by workingbuddy10** [comment]
@martynasma  
I don't want user to scroll or pan in the left side ( start < 0).
I added events in the panel but even if I click then too event gets fire. I don't want that. If I click it should react.

```
      fundamentalPanel.events.on("wheel", () => {
      start = fundamentalDateAxis.get("start");
      console.log(start);
      
      if (start <= 0) {
       console.log("Scroll on main chart to load more data")
        fundamentalDateAxis.set("maxDeviation", 0);
      }
    })

    fundamentalPanel.events.on("panended", () => {
      start = fundamentalDateAxis.get("start");
      console.log(start);
      
      if (start <= 0) {
       console.log("Scroll on main chart to load more data")
        fundamentalDateAxis.set("maxDeviation", 0);
      }
    })
```
I tried adding the event on series but it didn't worked.

codepen : https://codepen.io/Ansh-m-the-reactor/pen/YzbvxbV?editors=1111

**Comment by martynasma** [comment]
That seems like a totally different issue. Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.
