### ISSUE TITLE
Column Series not spanning the length of a Date Axis

### ISSUE THREAD

**Issue by btbritz** [amcharts/amcharts5#1588]
Given the following: https://codepen.io/BritzerToo/pen/YzbvQWB?editors=1111

For some reason the data points won't span the length of the x-axis and I'm not sure why. I added an extra point for testing purposes and you'll see the row with "Ben Britz" at the bottom has a point that should be on June 2024 but looks like it's placed on Feb 2020. Did I configure something incorrectly?

Screenshot:
![Screenshot 2024-06-25 at 7 41 17 AM](https://github.com/amcharts/amcharts5/assets/3333099/27b43775-8cc4-4d71-937c-475fd971c2fb)

**Comment by martynasma** [comment]
It's got to do with bullet centering. Right now, it centers bullets horizontally (because base axis is Y axis).

You can fix that like this:

```JavaScript
return am5.Bullet.new(root, {
    sprite: graphics,
    locationX: 1
});
```

**Comment by btbritz** [comment]
Thanks @martynasma ! Works great.
