### ISSUE TITLE
How to add text to the last date axis label value ?

### ISSUE THREAD

**Issue by dannycruz97** [amcharts/amcharts5#1589]
Hello. 

So I'm trying to add an '*' in the last date axis value.

Like this:
![image](https://github.com/amcharts/amcharts5/assets/49123785/a36830cf-6177-46d3-b092-977b93959328)

How can I achieve said result ?

Kind Regards

**Comment by martynasma** [comment]
You can do that with an adapter:

```JavaScript
xAxis.get("renderer").labels.template.adapters.add("text", function(text, target) {
  if (target.dataItem && new Date(target.dataItem.get("value")).getMonth() == 5) {
    return text + "*";
  }
  else {
    return text;
  }
});
```

**Comment by dannycruz97** [comment]
Thank you very much for your fast response.

Only facing one problem with that approach, i get an error accessing the : `target.dataItem.get("value"))`

![image](https://github.com/amcharts/amcharts5/assets/49123785/1b85f974-c026-4fa7-b097-d12e8adaeb7d)

**Comment by martynasma** [comment]
You might need hints:

```JavaScript
xAxis.get("renderer").labels.template.adapters.add("text", function(text, target) {
  const dataItem: am5.DataItem<am5xy.IDateAxisDataItem> = target.dataItem!;
  if (target.dataItem && new Date(dataItem.get("value")!).getMonth() == 5) {
    return text + "*";
  }
  else {
    return text;
  }
});
```

Or just 😅
![image](https://github.com/amcharts/amcharts5/assets/1458520/026c09ba-13ae-447e-99e3-64078f0bdaef)

**Comment by dannycruz97** [comment]
That totally worked... I really appreciate it, you helped me a lot ! Thank you !
