### ISSUE TITLE
Parameter order discrepancy in zoomToGeoBounds()

### ISSUE THREAD

**Issue by olneyMatt** [amcharts/amcharts5#159]
Hi,

Doing some work with map zooming and I noticed a discrepancy I think.

Line 894 of amcharts5/src/.internal/charts/map/MapChart.ts says

`public zoomToGeoBounds(geoBounds: { left: number, right: number, top: number, bottom: number }, duration?: number): Animation<this["_settings"]["zoomLevel"]> | undefined {`

but the documentation at

https://www.amcharts.com/docs/v5/reference/mapchart/#zoomToGeoBounds_method

lists it as 

{ bottom: number,
  left: number,
  right: number,
  top: number }

I think one should be changed to match the other, but I'm not sure which is the 'correct' one!

Cheers
Matt

**Comment by martynasma** [comment]
Our classref automatically orders all objects by keys to make it easier to find specific key.

As the actual order of keys in this particular instance has no effect on the functionality, you can safely ignore it. I'm afraid we won't be able to change this.

**Comment by olneyMatt** [comment]
Ah, understood - I had assumed it was only order-based, I didn't realise it needed/used the keys!

Thanks
Matt
