### ISSUE TITLE
Heat Rules not working on Polar

### ISSUE THREAD

**Issue by btbritz** [amcharts/amcharts5#1590]
Referencing this: https://codepen.io/BritzerToo/pen/RwmOwzo

Heat rules don't seem to be working for a Polar/Radar Chart. Everything looks correct when applying heat rules to a bullet via circleTemplate, and I have calculateAggregates set to true. I must have missed a step somewhere but don't see it.

**Comment by zeroin** [comment]
You are missing `valueField:"value"` in your series setup.

**Comment by btbritz** [comment]
Oh jeez. Thank you!
