### ISSUE TITLE
ENHANCEMENT Request : Comparison Series with new price scale

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1592]
Currently if the user applies the comparison series, it appears in the over lay mode with the change in the percent. Which is working right!

But If the user can have the option to view the comparison series in  overlay mode with new price scale just like the Trading View gives.

Though they give 3 options for viewing comparison series : Change in percent, New price Scale & New panel. (option 3 can be easily done by the developer end).
Just looking for the help for the new price scale.

Like If I pan in product A valueAxis, then only that series should and vice-versa.

Like this : 
![image](https://github.com/amcharts/amcharts5/assets/137867461/92a3509d-643f-4569-8226-2256f8758251)

**Comment by martynasma** [comment]
> Though they give 3 options for viewing comparison series : Change in percent, New price Scale & New panel. (option 3 can be easily done by the developer end).

The second option can be done just as well. Comparison series is added to chart via user code. So instead of creating a new series and adding it via `addComparingSeries()`, you create an additional Y axis, and assign it to compared series.

**Comment by workingbuddy10** [comment]
Thanks for this!
Will try to work around!

**Comment by workingbuddy10** [comment]
@martynasma 
Thanks to your idea, I am able to create the new valueAxis too!
Just one small concern, I am able to add the series and using the cancel button I am also able to remove series but not able to remove the valueAxis of that respective series.
How can achieve that?

Let's say I have this below combination where I have changed my main stock chart to lineseries for now ( using series switcher).
If I delete/remove any series then I want that its series valueAxis should also go.

I can get the all the yAxes using this : `this.chartInstance.stockChart.panels._values[0].yAxes._values`  and know that we can use `removeValue`. Just unable to sync it with the cancel button.

![image](https://github.com/amcharts/amcharts5/assets/137867461/e6f20f95-0e9c-4503-bd10-c9fec2df40ef)

**Comment by workingbuddy10** [comment]
I am only getting stuck in removing in both the case, rest everything is cracked!
