### ISSUE TITLE
Tooltip background colour getting removed after initial hover #amcharts5

### ISSUE THREAD

**Issue by Ashishvkale** [amcharts/amcharts5#1594]
I'm working with amcharts5. Implementing a world map for my site.
The tooltip background colour getting removed after initial hover.
And after refresh comes back for a single time.

This is what happening : 
<img width="476" alt="Screenshot 2024-06-28 at 7 01 49 PM" src="https://github.com/amcharts/amcharts5/assets/97302990/c8881359-7b95-4cce-a839-3ae4be3624ba">

This is whats expected: 
<img width="358" alt="Screenshot 2024-06-28 at 7 03 22 PM" src="https://github.com/amcharts/amcharts5/assets/97302990/fa1e00ac-b2d4-4e60-ae04-74e5bb7d4d42">

Below is the code :

```JavaScript
this.imageSeries.bullets.push(() => {
            if (this.root) {
                return am5.Bullet.new(this.root, {
                    sprite: am5.Picture.new(this.root, {
                        width: 20,
                        height: 30,
                        centerX: am5.p50,
                        centerY: am5.p100,
                        scale: 1,
                        templateField: "image",
                        tooltipText: "{title} \n {address}",
                        tooltip: am5.Tooltip.new(this.root, {
                            background: am5.PointedRectangle.new(this.root, {
                                fill: am5.color("#000")
                            })
                        })
                    })
                })
            }
        })
```

**Comment by martynasma** [comment]
I suggest not overwriting the whole tooltip for each item.

Rather modify series' tooltip:

```JavaScript
const tooltip = am5.Tooltip.new(this.root, {
  getFillFromSprite: false
});

tooltip.get("background").set("fill", am5.color("#000"));

this.imageSeries.set("tooltip", tooltip);
```

**Comment by Ashishvkale** [comment]
Thank you it worked !!
Can you please tell me how can I align the text 
as you can see there is a slight space for second line

**Comment by martynasma** [comment]
> Can you please tell me how can I align the text
> as you can see in image there is a slight space for second line

You have a space in your tooltip text after `\n`. Just remove it.

```
tooltipText: "{title} \n {address}"
```

**Comment by Ashishvkale** [comment]
Thank you !!
