### ISSUE TITLE
Overlapping charts in the same Root

### ISSUE THREAD

**Issue by bossbelle** [amcharts/amcharts5#1595]
I created 2 charts in the same root.
The problem was that what I wanted was two charts stacked vertically and displayed, but the two charts are overlapping.
Is there a way to stack two charts vertically and display them?

I would like to link two charts like the example below.
However, in the example below, each root is used for each Div.
I want to export two charts as one image, so I have to put two charts in one root.

https://www.amcharts.com/docs/v5/tutorials/syncing-axis-zooms-across-multiple-charts/

[codepen](https://codepen.io/-bossbelle/pen/KKYJgjJ)

**Comment by martynasma** [comment]
You need to add vertical layout to the main container so it knows how to arrange its children:

```JavaScript
root.container.set("layout", root.verticalLayout);
```
