### ISSUE TITLE
Clickable scatter plot canvasBullets

### ISSUE THREAD

**Issue by BrunoJ75** [amcharts/amcharts5#1596]
Hi,

I'm trying to adapt this exemple of scatter plot:
https://www.amcharts.com/demos/scatter-plot-with-tens-of-thousands-points

I would like to make each bullet clickable with a redirection to a webpage with a unique id : jdoe.php?uid=xxx
These uids are in my data array
But after hours, I can't manage to get it work
I tried passing uids to a userData property and use a click event but bullets all get the same uid ...

Any idea of how to do this?

Thank you

Bruno

**Comment by martynasma** [comment]
I would use series' `tooltipDataItem` to determine which item was clicked:

```JavaScript
canvasBullets.events.on("click", function() {
  console.log(series.get("tooltipDataItem"))
});
```

**Comment by BrunoJ75** [comment]
Thanks a lot, it works great!
I can't believe the solution is 3 liner...
