### ISSUE TITLE
Any possibility to configure the valueAxis

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1598]
I want to know the scope/possibilty to change the valueAxis config, as I want to show the valueAxis with base value of 1/32.

As the US Treasury products can only be traded/seen in the base 1/32 values. So I want to have this, please guide the scope of this or t: 

![image](https://github.com/amcharts/amcharts5/assets/137867461/4acdb1f5-7dc4-4630-9adb-8c9ac63173d2)
![image](https://github.com/amcharts/amcharts5/assets/137867461/2930a1fb-e268-4a7f-95b5-9fb8e8782892)

[why base 32 important](https://www.cmegroup.com/education/courses/introduction-to-treasuries/the-basics-of-treasuries-basis.html#:~:text=In%20U.S.%20Treasury%20futures%2C%20the%20basis%20is%20the%20price%20spread%2C%20usually%20quoted%20in%20units%20of%201/32%2C%20between%20the%20futures%20contract%20and%20one%20of%20its%20eligible%20delivery%20securities.%C2%A0)

Although there are multiple feature request issues related to this are open, so I want to know if you guys planning to implement it or not, if not then how can proceed. Because this is must to have feature.

**Comment by martynasma** [comment]
I'm afraid we do not have any plans on implementing base 1/32 scale for ValueAxis 🙁

**Comment by zeroin** [comment]
We do not plan to add support of base 1/32 or any other base, sorry.

**Comment by workingbuddy10** [comment]
I got your point @martynasma , that you won't be implementing it! No problem
Is there any way you can help/ direct me that what should I try to customize in the amcharts codebase to achieve it.

**Comment by martynasma** [comment]
No, I'm afraid. This is no trivial task with axis scales comprised out of so many moving parts.
