### ISSUE TITLE
Remove click event in the series

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1599]
I don't want user to scroll or pan in the left side ( start < 0).
I have added events in the panel but even if I click then too event gets fire. I don't want that. If I click it should react.

```
      fundamentalPanel.events.on("wheel", () => {
      start = fundamentalDateAxis.get("start");
      console.log(start);
      
      if (start <= 0) {
       console.log("Scroll on main chart to load more data")
        fundamentalDateAxis.set("maxDeviation", 0);
      }
    })

    fundamentalPanel.events.on("panended", () => {
      start = fundamentalDateAxis.get("start");
      console.log(start);
      
      if (start <= 0) {
       console.log("Scroll on main chart to load more data")
        fundamentalDateAxis.set("maxDeviation", 0);
      }
    })
```
I tried adding the event on series but it didn't worked.

codepen (try click on panel, after adding APPLE series) : https://codepen.io/Ansh-m-the-reactor/pen/YzbvxbV?editors=1111

**Comment by martynasma** [comment]
I'm sorry, I'm not sure what to suggest.

**Comment by workingbuddy10** [comment]
@martynasma  You can see when I click on the series, it automatically moves only by clicking : 

https://github.com/amcharts/amcharts5/assets/137867461/a8e1ec0e-f2a5-4acd-8ef7-31bb54cdde17
