### ISSUE TITLE
Variable radius on pie chart

### ISSUE THREAD

**Issue by tobias-berg** [amcharts/amcharts5#16]
Is it possible to set a variable radius on pie charts, similar to v4?

[https://codepen.io/team/amcharts/pen/OQeGmZ](https://codepen.io/team/amcharts/pen/OQeGmZ)

**Comment by martynasma** [comment]
Yes, here's a demo:
https://codepen.io/team/amcharts/pen/KKqwRWq

**Comment by tobias-berg** [comment]
Wow, thanks for the code! Unfortunately it doesn't work. I get error on this line:

var dataItem = target.dataItem;

"Property 'dataItem' does not exist on type 'O'

I'm on Beta 19

**Comment by martynasma** [comment]
Try type-casting `target` parameter:

```JavaScript
series.slices.template.adapters.add("radius", (radius, target: any) => {
  const dataItem = target.dataItem;
  const high = series.getPrivate("valueHigh");

  if (dataItem) {
    let value = target.dataItem.get("valueWorking", 0);
    return radius * value / high
  }
  return radius;
});
```

**Comment by tobias-berg** [comment]
Yes, of course, silly me! Thanks once again and keep up the good work! I'll do some more reading around adapters.
