### ISSUE TITLE
Replicating SmallMap in AM5

### ISSUE THREAD

**Issue by olneyMatt** [amcharts/amcharts5#160]
Hi,

I'm trying to reproduce the `SmallMap` functionality from AM4 (a birds-eye world map view of the current zoomed view in a parallel mapChart) in AM5.

However, I'm struggling to get the right event to trigger the recapture of the view dimensions and redraw - nothing I've been able to find waits until the zoom is complete before triggering.

Any suggestions please?

Thanks.

**Comment by martynasma** [comment]
I'm afraid `SmallMap` control is not available in amCharts 5 :(

It's a nasty resource-monging utility, that is not particularly useful.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by olneyMatt** [comment]
I've uploaded a rough (sorry!), cutdown version here:

[https://codepen.io/olneymatt/pen/oNGwrKz](url)

It loads with the left hand chart zoomed to the data, with nothing shown on the right hand map (can fix later).

Zooming out triggers the ZoomControl click event, which draws the view rectangle but it's always 'one click behind' - it draws the view window as it was at the start of the zoom animation rather than at the end.

Obviously I'd like it reflect the view window as it ends.

Any thoughts gratefully received. Thanks.

**Comment by martynasma** [comment]
Thanks!

I suppose you could just watch for `zoomLevel` change and update your small map there:

```JavaScript
dataMapChart.on("zoomLevel", function() {
  updateViewBoundsAsGeo();
  updateViewAreaMarker();
})
```

**Comment by olneyMatt** [comment]
Ah, perfect - I hadn't understood the '.on()' method.

Thanks!
