### ISSUE TITLE
How can I achieve the 7 hour candle ( timeUnit: "hour", count: 7) 

### ISSUE THREAD

**Issue by p3777dev** [amcharts/amcharts5#1600]
In Case of hour , its base Interval support only 1, 3 , 6 and 12 count . As I am building the timeframe from the user Input  by bundling the multiple data points into one . I can build 4H or 5H data by this but it doesn't support the base Interval count 7 ( 7H time Interval ) .  Please check by the given example below - 
CodePen (https://codepen.io/prince-work/pen/QWRegmb)

**Environment (if applicable)**

**Additional context**

**Comment by zeroin** [comment]
I think the candles are taking 7 hours (visible when you zoom-in). But I don't think it will work flawlessly. It's just against the nature :) I don't think I can suggest anything here.

**Comment by workingbuddy10** [comment]
@zeroin  You can see on the top right corner I have added the time frame as 7 hours


![image](https://github.com/amcharts/amcharts5/assets/137867461/0cf3bba1-86d9-48af-b2da-90d4b37580f2)


![image](https://github.com/amcharts/amcharts5/assets/137867461/961f7319-aa21-4e38-8091-e91b00e29782)

The images are from TradingView ( paid version)

**Comment by p3777dev** [comment]
Is it possible to achieve this thing or Is it the way the amchart is designed ?

**Comment by zeroin** [comment]
I must say I still don't get it - In you codepen I see 7 hour interval. But in general - yes, amcharts is designed like this, it will work properly with 12, 6, 3 hour intervals.
