### ISSUE TITLE
How to remove the volumeSeries

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1601]
I have the product list which some of them contains the volume data and some of them doesn't.

So I have to remove the volumeSeries including the volume axis. 
I tried both this but it didn't worked : 
```
stockChart.get("volumeSeries").set(null)
stockChart.remove("volumeSeries")
```

**Comment by zeroin** [comment]
You should also remove the series form `panel.series` list.

**Comment by workingbuddy10** [comment]
Okay @zeroin , as you said I tried doing this!
Below is my function which removes the volumeSeries ( ColumnSeries) in case of no volume data found.
```
  updateVolumeSeries() {
    if (this.isVolumeDataAvailable) {
      this.chartInstance.stockChart.set("volumeSeries", this.chartInstance.volumeSeries);
    } else {
      
 // Remove volumeSeries from stockChart
      this.chartInstance.stockChart?.get("volumeSeries")?.setAll({})
      this.chartInstance.stockChart.remove("volumeSeries")
  
      // Remove volumeSeries from panels 
      this.chartInstance.stockChart.panels._values.forEach(panel => {
        const seriesArray = panel.series._values;
        for (let i = 0; i < seriesArray.length; i++) {
          if (seriesArray[i] === this.chartInstance.volumeSeries) {
            seriesArray.splice(i, 1);
            break;
          }
        }
      });
    }
  }
```

Now If I try to console this : root.stockChart.panels._values[0].series._values  
It only gives the :  [CandlestickSeries]  ( it has removed the ColumnSeries)


But there are 2 issues : 
- It didn't removed the volumeValueAxis . 
![image](https://github.com/amcharts/amcharts5/assets/137867461/2508a980-730e-4b16-8a84-a80eaf2df3cd)

- And also the indicator list didn't updated.

**Comment by workingbuddy10** [comment]
Nope @zeroin  it didn't worked 
I tried this  :
![image](https://github.com/amcharts/amcharts5/assets/137867461/9f282c52-601c-4ab5-a061-bdc354c08f8b)


code : 
```
  updateVolumeSeries() {
    console.log(this.isVolumeDataAvailable);
    if (this.isVolumeDataAvailable) {
      
       
      this.chartInstance.stockChart.set("volumeSeries", 
                                       this.chartInstance.volumeSeries);
    } else {
      // Remove volumeSeries from stockChart
      this.chartInstance.stockChart.remove("volumeSeries");
      this.chartInstance.mainPanel.series.removeValue("volumeSeries");
      // Remove volumeSeries from panels
      this.chartInstance.stockChart.panels._values.forEach(panel => {
        panel.series.removeValue(this.chartInstance.volumeSeries);
      });
  
      // Remove volumeAxis from mainPanel if it is associated with the volumeSeries
      this.chartInstance.mainPanel.yAxes._values.forEach(axis => {
        if (axis.series.some(series => series === 
                                        this.chartInstance.volumeSeries)) {
          axis.dispose();
        }
      });
    }
  }
```

**Comment by zeroin** [comment]
Axis is not removed from a chart when you remove series. You must removed the axis in the same way as you remove series:

`panel.yAxes.removeValue(axis)`

**Comment by workingbuddy10** [comment]
Thanks @zeroin ,
It is now removing the valueSeries and valueAxis. 
But when I again switch back to the product which has the volume Data ideally it should set the both Series and axis. Using the below line  :  `this.chartInstance.stockChart.set("volumeSeries", this.chartInstance.volumeSeries);`
where,` this.chartInstance.volumeSeries is the ColumnSeries.`

Full code : 
```
  updateVolumeSeries() {
    if (this.isVolumeDataAvailable) {
      this.chartInstance.stockChart.set("volumeSeries", this.chartInstance.volumeSeries);
      
    } else {
      // Remove volumeSeries from panels
      this.chartInstance.stockChart.panels._values.forEach(panel => {
        panel.yAxes._values.forEach(axis => {
          if (axis.series.some(series => series === this.chartInstance.volumeSeries)) {
            panel.yAxes.removeValue(axis);
          }
        });
      panel.series.removeValue(this.chartInstance.volumeSeries);
      });
    }
  }
```

**Comment by workingbuddy10** [comment]
Do I re-render the app or is there any way to make it appear?

**Comment by zeroin** [comment]
Sorry, this is beyond the scope of our free support service.
