### ISSUE TITLE
How to remove Extra space in the left side of the stockChart

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1606]
- For the comparison series I am adding a new valueAxis. ( for more reference #1592)
- And when user clicks on the close button I remove that valueAxis, which is getting removed.
- But the space created by the valueAxis is not getting removed. 
I tried to set the paddingLeft to 0 when user removes the series, that too didn't worked for me. `this.chartInstance.stockChart.set("paddingLeft",0)`

https://github.com/amcharts/amcharts5/assets/137867461/80b4a2b9-1695-426f-8d9f-ab1314fc4c3a

This is how I am removing the axis : 
```
          if (axisType === 'New price scale') {
            comparisonPanel.yAxes.removeValue(comparisonYAxis);
            this.chartInstance.chartInstanceUpdateStore.triggerZoomToLastNPoints(this.chartInstance.data.length);
          }
```

Which property should I fire when the user closes the button to remove this extra space

**Comment by martynasma** [comment]
Try disposing the axis, too.

```JavaScript
comparisonYAxis.dispose();
```

**Comment by workingbuddy10** [comment]
Nope @martynasma  it didn't worked though it is disposing the axis but the space is there.

Full code of removing the aixs :
```
       // Add event listener to the close button to remove the y-axis
       let closeButton = comparisonSeries.get("legendDataItem").get("closeButton");
       if (closeButton && closeButton.events) {
        let originalClickListeners = closeButton.events._listeners.filter(listener => listener.type === 'click');
  
        closeButton.events.off('click');
  
        closeButton.events.on('click', (event) => {
          originalClickListeners.forEach(listener => {
            listener.callback.call(listener.context, event);
          });
  
          if (axisType === 'New price scale') {
            comparisonPanel.yAxes.removeValue(comparisonYAxis);
            comparisonYAxis.dispose();
          }        }); 
       } else {
         console.error("Unable to access closeButton or its events.");
       }
```

Below is the comparisonYAxis forming code :

```
      comparisonYAxis = am5xy.ValueAxis.new(this.chartInstance.instance, {
        renderer: comparisonYAxisRenderer,
        syncWithAxis: this.chartInstance.valueAxis,
        opacity: 0.7,
        extraMin: 0.03,
        maxDeviation: 1,
        tooltip: am5.Tooltip.new(this.chartInstance.instance, {}),
        extraTooltipPrecision: 2,
      });
      comparisonYAxis?.get("renderer").labels.template.setAll({
        paddingRight: 0
      });
      comparisonPanel.yAxes.push(comparisonYAxis);
```

**Comment by martynasma** [comment]
Could you whip up a CodePen with the simplified version of what you do with the addition/removal?

**Comment by workingbuddy10** [comment]
Sure @martynasma 
Codepen link : https://codepen.io/Ansh-m-the-reactor/pen/zYVvYRQ

Initially see the difference between the red border and the valueAxis ( where March 2021) written.
And after adding/removing the axis then see the difference between them.


https://github.com/user-attachments/assets/2bc3f8a5-151c-47fe-b407-f9edd114851c

**Comment by workingbuddy10** [comment]
- In the same codepen @martynasma you can see the ticks are overlapping over the valueAxis of the comparison series. Which I don't want.
- And if you add the second axis, then it comes very small.

Lastly I am updating the comparison series LIVE, with showing the label though the its updating perfect. Just the label changes which leads to the shifting of the valueAxis of the comparison  series

Something like this :

https://github.com/user-attachments/assets/c54ae180-8e0b-4bd3-b622-3f023c27455b

**Comment by workingbuddy10** [comment]
@martynasma Does this codepen helped you? Or should I provide anything else too..!

**Comment by workingbuddy10** [comment]
Perfect @martynasma it worked! Thanks a lot.
