### ISSUE TITLE
stockchart label issue

### ISSUE THREAD

**Issue by prackode** [amcharts/amcharts5#1608]
I have created a label to show the price in the stockchart, but sometimes the background values seems to override .

Even though I gave the opaque color, then too.
something like this : 

![image](https://github.com/amcharts/amcharts5/assets/72190853/39c0d89f-537d-47a0-a67a-6d4a61f6f957)

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by prackode** [comment]
Below is the code for creating label.
```
_createUpdateLabel(lastData) {
    if (!this.currentValueDataItem) {
      let currentValueDataItem =  valueAxis.createAxisRange(
         valueAxis.makeDataItem({ value: 0 })
      );
      this.currentValueDataItem = currentValueDataItem;
    }

    let currentLabel = this.currentValueDataItem.get("label");

    if (currentLabel) {
      currentLabel.setAll({
        fill: am5.color(0xffffff),
      })
    }

    let closeValue = lastData?.Close;
    let openValue = lastData?.Open;

    this.currentValueDataItem.animate({
      key: "value",
      to: closeValue,
      duration: 500,
      easing: am5.ease.out(am5.ease.cubic),
    });

    // Ensure the existence or update of the label
    if (!currentLabel) {
      // If the label doesn't exist, create it
      currentLabel = this.currentValueDataItem.set("label", am5.Label.new( root, {}));
    }

    currentLabel.set("text",  .stockChart.getNumberFormatter().format(closeValue));
    currentLabel.set("opacity", 1);
    var bg = currentLabel.get("background") || currentLabel.set("background", am5.Rectangle.new( root, {}));

    if(bg){
      if(closeValue < openValue){
        bg.set("fill", am5.color("rgba(235, 91, 60, 1)"));
      }else{
        bg.set("fill", am5.color("rgba(10, 187, 146, 1)"));
      }
    }
  }
```

I don't want this :

![image (1)](https://github.com/amcharts/amcharts5/assets/72190853/20af6542-1ad4-4ec9-8270-92f7da35d5cf)

- It should be opaque at any case.

**Comment by martynasma** [comment]
Have you tried setting `fillOpacity: 0` label's background?

```JavaScript
bg.set("fillOpacity", 1);
```

**Comment by prackode** [comment]
Did that @martynasma 
![image (2)](https://github.com/user-attachments/assets/4d10901e-9633-4860-ab64-917950284beb)

Now my full code looks like
```
_createUpdateLabel(lastData) {
    if (!this.currentValueDataItem) {
      let currentValueDataItem =  valueAxis.createAxisRange(
         valueAxis.makeDataItem({ value: 0 })
      );
      this.currentValueDataItem = currentValueDataItem;
    }

    let currentLabel = this.currentValueDataItem.get("label");

    if (currentLabel) {
      currentLabel.setAll({
        fill: am5.color(0xffffff),
      })
    }

    let closeValue = lastData?.Close;
    let openValue = lastData?.Open;

    this.currentValueDataItem.animate({
      key: "value",
      to: closeValue,
      duration: 500,
      easing: am5.ease.out(am5.ease.cubic),
    });

    // Ensure the existence or update of the label
    if (!currentLabel) {
      // If the label doesn't exist, create it
      currentLabel = this.currentValueDataItem.set("label", am5.Label.new( root, {}));
    }
    currentLabel.set("text",  this.chartInstance.stockChart.getNumberFormatter().format(closeValue));
    currentLabel.set("opacity", 1);
    currentLabel.set("fillOpacity", 1);
    var bg = currentLabel.get("background") || currentLabel.set("background", am5.Rectangle.new( this.chartInstance.instance, {}));
    // bg.setAll({
    //   fill: am5.color(closeValue < openValue ? "rgba(235, 91, 60, 1)" : "rgba(10, 187, 146, 1)"),
    // });
    bg.set("fillOpacity", 1);
    if(bg){
      if(closeValue < openValue){
        bg.set("fill", am5.color("rgba(235, 91, 60, 1)"));
      }else{
        bg.set("fill", am5.color("rgba(10, 187, 146, 1)"));
      }
    }
```

**Comment by martynasma** [comment]
Are you seeing the same issue here?
https://www.amcharts.com/demos/live-stock-data/

**Comment by prackode** [comment]
I got the issue, actually my valueAxis opacity was : 0.7 that's why it was giving the transparent look. Sorry @martynasma my bad.

But still I am able to see 2 ticks like this :
![image (3)](https://github.com/user-attachments/assets/9ab214cc-bb87-4c32-9550-6c0579f61bd0)


code pen to see : https://codepen.io/Ansh-m-the-reactor/pen/bGPNQBL?editors=1010

**Comment by prackode** [comment]
I don't want to see this two ticks in the label how can I achieve this ?
@martynasma

**Comment by martynasma** [comment]
Just disable it:

```JavaScript
currentValueDataItem.get("tick").set("forceHidden", true);
```

**Comment by prackode** [comment]
@martynasma  How can I fix the width of the label, currently its dynamic according to the the number.

**Comment by martynasma** [comment]
Have you tried setting `width` on it?

**Comment by prackode** [comment]
@martynasma  I want it to sync it with the valueAxis width, so whatever the width of the valueAixs I want the same to be of lablel.
I tried getting the width of valueAxis but it was undefined, I guess it is dynamically set.

- Either I can handle it dynamically and sync label width with the valueAxis.

OR 

- Sometime I get the value in decimals then it shows bigger label and sometimes it I get in whole number then it gets smaller. 

So If I can make it constant? Like if we get the decimal value then show it else show ZERO after decimal number by  this way the label size will be fixed.

**Comment by martynasma** [comment]
Maybe you can use an adapter:

```JavaScript
currentLabel.adapters.add("width", function(width, target) {
  return yAxis.width();
});
```
