### ISSUE TITLE
Change Legend And Label Direction

### ISSUE THREAD

**Issue by prfardin** [amcharts/amcharts5#161]
how i can change legend and lebel direction to right?
help me pls!
i wanna change orders and direction like amcharts4
https://www.amcharts.com/docs/v4/concepts/rtl/

**Comment by martynasma** [comment]
Do you mean you need legend to be like this?

![image](https://user-images.githubusercontent.com/1458520/149977192-ea34723e-4b99-43d6-abf5-33e61fe85558.png)

**Comment by prfardin** [comment]
yes

**Comment by prfardin** [comment]
but at top and horizontal

**Comment by martynasma** [comment]
Thanks for the confirmation.

We're working on some changes that would allow reversing the legend like that, as well as related documentation.

Will let you know when it's available.
