### ISSUE TITLE
Treemap not drilling down as expected with dynamic child updates

### ISSUE THREAD

**Issue by ArunPragadeeswar007** [amcharts/amcharts5#1610]
**Question**

First of all, thank you for this amazing addon! It's been incredibly useful for our project. However, I've encountered an issue with the treemap that I need some help with.

The tree map is not functioning as expected when dynamically updating child nodes upon drilling down. The initial level works fine, but when clicking on a specific node (e.g., the fourth node), it drills down and expands all its child nodes. However, after this drill down with dynamic child updates, the view resets to the root level, and the nodes are added into the parent node but not expanded.

Please check out this : [demo](https://codepen.io/Arunpragadeeswar/pen/ExBarjE)

**Steps to Reproduce:**

1. Click on a node at the first level (e.g., the fourth node).
2. Observe that it drills down and expands all its child nodes.
3. Notice that the view resets to the root level and the nodes are added into the parent node but not expanded.

**What I Have Tried:**

- Disabled the following properties:
 ```
 dataItem.set("value", undefined);
dataItem.set("valueWorking", undefined);
```
This improved the situation, but the parent node is still shown. Additionally, when clicking on breadcrumbs, the node values are undefined, which causes issues in bread crumbs.

- Updated the `selectedDataItem` when a node is clicked:

```
series.set("selectedDataItem", dataItem);
```
This resulted in nodes being added but introduced glitches.

- Tried setting `selectedDataItem` to the node's children:
```
series.set("selectedDataItem", dataItem.get("children"));
```
This threw an error.

**Expected Behavior:**

When a node is clicked, data should be fetched, its child nodes should be updated and expanded, and navigation should work seamlessly, including with breadcrumbs.

**Environment**

 - amCharts version : "[^5.4.5](https://npmjs.com/package/@amcharts/amcharts5)",
 - Browser and its version : Chrome (126.0.6478.127) 
 - Framework : Ember 5.9

**Comment by martynasma** [comment]
Your example adds a new child to the clicked node.

The same click also acts as a drill-down, but it kicks in before your custom click handler which adds new child, hence no drill-down.

Also, when end-point node (no children) gains a child, it's value changes to the sum of its children, hence layout changing.

I suggest [disabling the built-in drill-down](https://www.amcharts.com/docs/v5/charts/hierarchy/hierarchy-drill-down/#Disabling_drill_down) altogether, and just relying on your custom click handler.
