### ISSUE TITLE
How can I change the bullet position when the user zooms or drags the stock chart?

### ISSUE THREAD

**Issue by shishima123** [amcharts/amcharts5#1612]
Hello

I want to add a feature that signals the highest and lowest prices.
It worked when I manually added it using the `addBullet` function.

However, I want the chart to automatically change the position and text on the bullet based on the candlesticks displayed on the chart when the user zooms or drags.

I tried the following method, but it didn't work.

```
valueSeries.columns.template.on('userData', function() {
  console.log('userData trigger')
  addBullet()
})
```

Can you give me some advice?

[My JSFiddle](https://jsfiddle.net/shishima/h2onkf69/14/)

**Comment by martynasma** [comment]
If you need to change something on chart zoom, you may need to use events on your X axis:

```JavaScript
dateAxis.onPrivate("selectionMinFinal", function(min) {
  console.log(new Date(min));
});

dateAxis.onPrivate("selectionMaxFinal", function(max) {
  console.log(new Date(max));
});
```

**Comment by shishima123** [comment]
Thanks @martynasma 

Your sample code worked in the case of zoom
However, it doesn't work when I drag the candlestick chart to the left or right
For example, I want to drag to the left to see past data

 Do you have any advice for this?

**Comment by martynasma** [comment]
Try using `selectionMin` and `selectionMax` instead.
