### ISSUE TITLE
Application crashing when Zoom the Scrollbar in our application in 5.9.13 version which worked in 5.9.12

### ISSUE THREAD

**Issue by Manikandans-softura** [amcharts/amcharts5#1613]
Application crashing when Zoom the Scrollbar in our application specifically in 5.9.13 version which was worked correctly in 5.9.12

When zooming to minimum level(left) the freezing issue is happening by the time left most value was 0.0 but not all the time . it happens to specific date range and not happening for some dates.
![image](https://github.com/user-attachments/assets/6ccd53c7-0ee5-41da-ab59-4a12e9b22bfa)

While doing that the bar shows like being clicked but it was released. eventually it leads to application crash.
![image](https://github.com/user-attachments/assets/cd991857-1b3c-4427-adfc-436c6789b33d)

I solved this by downgrading @amcharts/amcharts5 version to 5.9.12!

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
