### ISSUE TITLE
Stocks Drawing Tool custom tooltips on selection

### ISSUE THREAD

**Issue by xdajay** [amcharts/amcharts5#1615]
So far was able to create custom component to indicator selectors,  Series Selector, I think most cleanest implementation of amCharts stocks, great learning curve!  (hehe, should I resell template ? kidding).

 
![Screenshot 2024-07-15 at 11 47 25 PM](https://github.com/user-attachments/assets/9b8cb00e-4567-4d74-9631-32b49de50c0d)
![Screenshot 2024-07-15 at 11 47 50 PM](https://github.com/user-attachments/assets/4748dcdc-570b-42f2-8be2-adb697e3f9da)

I'm able to create custom UI components  and invoke things via API for Series Selectors, Indicator Selectors,
Also invoking drawing tool via custom UI component is also pretty simple!

```
DrawingControlRef.current.setAll({
            active: true,
            tool: "Doodle",
            strokeColor: am5.color(0xff0000)
        });
```

Now how do I  have custom flaoting settings tooltip for selected drawing element? near selected element, 
example I've selected Horizontal line, and its setting tooltip(colors, stroke width etc)  is rendered near the horizontal line instead of fixed inbuilt toolbar.

My Logical plan,
1. know which drawing element is selected.
2. Know the X,Y positing of selected drawing element.
3. Invoke custom setting component near selected drawing element.

Any alternate method, which might be more efficient ?

Thanks

**Comment by martynasma** [comment]
> Now how do I have custom flaoting settings tooltip for selected drawing element? near selected element,
example I've selected Horizontal line, and its setting tooltip(colors, stroke width etc) is rendered near the horizontal line instead of fixed inbuilt toolbar.

I don't think we have anything like this built-in.

Your tentative plan sounds OK to me 🤔

**Comment by xdajay** [comment]
@martynasma  While building custom tooltip for drawing?

1. how to keep drawing -- select mode always on ?  so user can select  any drawing element after drawing?, currently select only works if you manually click on select (mouse icon from drwaing toolbar).

2. How to push new colors/settings/strokes  for selected drawing element ?

Thanks

**Comment by xdajay** [comment]
Thanks @martynasma  this is super helpful!
