### ISSUE TITLE
Individual sorting for  columns in a date group

### ISSUE THREAD

**Issue by pratham3164** [amcharts/amcharts5#1617]
how can I achieve some similar to
https://www.amcharts.com/docs/v4/tutorials/simulating-individual-order-of-columns-within-categories/
using  Gapless date axis

**Comment by martynasma** [comment]
There's no way to individually sort columns on a `GaplessDateAxis`, I'm afraid.

The demo from V4 does not use any kind of Date axis, though. It's a regular `CategoryAxis`. You can apply the same trick with a `CategoryAxis` on V5 just as well.

**Comment by pratham3164** [comment]
@martynasma  I needed this functionality on dateAxis where we can sort groups within a date. any workaround to achieve ??

**Comment by martynasma** [comment]
Do you mean you have clusters of columns from different series and want to re-order those columns individually within every single date?

I don't think that's possible I'm afraid.

I suppose you can simulate it by having several series, then just applying custom colors in preferred order to each individual column with [`templateField`](https://www.amcharts.com/docs/v5/concepts/settings/template-fields/).
