### ISSUE TITLE
ValueAxis is not displaying full value

### ISSUE THREAD

**Issue by p3777dev** [amcharts/amcharts5#1618]
I have removed the number formatter.
And then too my valueAxis in stock chart is not showing the full values.

I want it to be dynamic, like valueAxis can get any type of decimal values.

codepen  :https://codepen.io/prince-work/pen/ZEdbjzv

**Comment by martynasma** [comment]
The scale of your ValueAxis spans about 35 numbers. In this case, the axis will show grid at precise round numbers, like 520, 525, etc.

That scale does not relate to actual values of actual data items in any way, except that the scope is adjusted to fit all values.

If you need to show labels/grid at precise specific values, you can use axis ranges:
https://www.amcharts.com/docs/v5/tutorials/using-axis-ranges-to-place-labels-at-arbitrary-values-or-dates/
