### ISSUE TITLE
scale bullets on hover

### ISSUE THREAD

**Issue by morrow95** [amcharts/amcharts5#162]
How would one go about scaling the bullets on hover in version 5?  I see there is a `scale`, but not clear to me how to use it.

```
series.bullets.push(function() {
	return am5.Bullet.new(chartReg[name], {
		sprite: am5.Circle.new(chartReg[name], {
			radius: 5,
			fill: series.get("fill"),
			strokeWidth: 2,
			stroke: am5.color("#ffffff")
			
		})
	});
});
```

version 4 was : 

```
var bullethover = series.bullets.states.create("hover", {});
bullethover.properties.scale = 1.25;
```

**Comment by martynasma** [comment]
Something like this:

```JavaScript
series.bullets.push(function () {
  var circle = am5.Circle.new(root, {
    radius: 5,
    fill: series.get("fill"),
    stroke: root.interfaceColors.get("background"),
    strokeWidth: 2,
    interactive: true
  });
  
  circle.states.create("hover", {
    scale: 3
  });
  
  return am5.Bullet.new(root, {
    sprite: circle
  });
});
```

**Comment by morrow95** [comment]
@martynasma This works, but only if my mouse is directly over the bullet.  In the old version this hover effect happened the same time the tooltip and cursor would show for that point/entry.  In my case I am using `snapToSeriesBy: "x"` on my cursor so as long as my mouse is somewhere on the chart there will be a tooltip and cursor shown - and hopefully a scaled bullet.

Is it possible to still replicate this behavior in version 5?

**Comment by martynasma** [comment]
amCharts 5 does not apply hover on bullets automatically, unless hovered directly.

You would need to catch cursor's `cursormoved` event, then trigger hover on related bullets.

Here's a demo:
https://codepen.io/team/amcharts/pen/KKXvYqJ?editors=0010

**Comment by morrow95** [comment]
@martynasma Awesome - this is exactly what I was looking for.  Thank you for the example!

**Comment by morrow95** [comment]
How could I apply this same technique when using multiple series?

[https://codepen.io/scubapongo/pen/GRMmwKj](https://codepen.io/scubapongo/pen/GRMmwKj)

**Comment by martynasma** [comment]
Here's another example:
https://codepen.io/team/amcharts/pen/rNGKyRG

**Comment by morrow95** [comment]
@martynasma That helps a lot - thank you!
