### ISSUE TITLE
How to use the series legend buttons

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1620]
I am unable to use the close button in this case : 

https://github.com/user-attachments/assets/f6825d95-53e2-4039-b9ae-3d8f07ff15b1

WHY : 

- because of irregularity of data in series.
- At point A where data is not present when you hover on the series the button will shift to left ( as there is no OHLCV values).
- So I move the cursor to the left to click on the close button.
- But On that point there was data present, so the button shifts to right.

What should I do ?

And in this process I am just moving the cursor left and right but not able to catch the button 😂

**Comment by martynasma** [comment]
How about you just set minimum width for legend's items?

```JavaScript
legend.itemContainers.template.setAll({
  minWidth: 250
});
```

**Comment by martynasma** [comment]
Another option: move icons to the front of the items:

```JavaScript
valueLegend.settingsButtons.template.events.on("dataitemchanged", function(e){
  e.target.set("marginRight", 5);
  root.events.once("frameended", ()=>{
    e.target.toBack()
  })  
})

valueLegend.closeButtons.template.events.on("dataitemchanged", function(e){
  root.events.once("frameended", ()=>{
    e.target.toBack()
  })  
})
```

Example:
https://codepen.io/team/amcharts/pen/QWXybZN

**Comment by workingbuddy10** [comment]
2nd option is better @martynasma !
As if one uses the first option then too the problem remains the same.

By the way just asking can we do like this ? 
- Like if the user hover on the legend then show the series settings 
something like this or tradingview does :
![image](https://github.com/user-attachments/assets/a3cf75b1-bbbb-46fe-b2dd-5a56ca78bbde)

**Comment by martynasma** [comment]
I'm afraid no such option is available.

**Comment by workingbuddy10** [comment]
And how can I smaller the size of icons? @martynasma
