### ISSUE TITLE
Setting all data and keeping disposed data disposed or completely remove them post-cleanup

### ISSUE THREAD

**Issue by zoumath19** [amcharts/amcharts5#1622]
For context, I'm working with a Force Directed Graph

Hi, I have an issue with this, series.data.setAll( data )

This, will completely reset my data frame and enable disposed nodes as well, how can I work around this? Is it possible to actually remove a specific child from a specific spot which is disposed already?

=== Supplementary question

Also, another question, sometimes when adding children, I'm not able to have a collapsed clickable view, I can't really click them anymore!

series.addChildData( categoryNode,  [
            {
                fill: bank.uname,
                name: `{ bank.name }`,
                value: size
            }
        ] );
        
 Do I override the events like this?

**Comment by martynasma** [comment]
> This, will completely reset my data frame and enable disposed nodes as well, how can I work around this? Is it possible to actually remove a specific child from a specific spot which is disposed already?

I'm not sure I understand. Setting new data will remove all of the current data/nodes.

Do you want to keep some of them?

If you want to remove specific nodes, please refer to this:
https://www.amcharts.com/docs/v5/charts/hierarchy/hierarchy-api/#Removing_nodes

As for the other question, please post it as a separate issue, as per our one-question-per-issue rule.
