### ISSUE TITLE
Set series tooltip in a fixed position and higher than others series tooltips

### ISSUE THREAD

**Issue by dannycruz97** [amcharts/amcharts5#1623]
Hello,

I hope everything is going well with all of you.

I know for a fact that I will have three series represented in a chart, and I need to display the tooltip for one of those series higher than the others. However, I am not sure how to achieve this. I need to get the same result for both line series and column series. The tooltip can be in a fixed position at a certain height, but it’s not required as long as it appears higher than the others.

Desired result:
![image](https://github.com/user-attachments/assets/3214816d-8fb6-4cb7-83ea-6ecf342dc0ed)

Kind Regards !

**Comment by workingbuddy10** [comment]
@dannycruz97  Why don't you go try using legends?

**Comment by zeroin** [comment]
In all cases where you need to override some settin (y in this case) you should use adapters:

```
    tooltip.adapters.add("y", function(){
      return 50
    })
```

will make the tooltip to stay at 50 px from the top.

I would also set `extraMax:0.1` for value axis so that there would be enough space for the tooltip.

https://codepen.io/team/amcharts/pen/qBzZWaj

**Comment by dannycruz97** [comment]
Works like a charm ! Thanks !
