### ISSUE TITLE
Is it possible to avoid using the .setAll() method when adding data dynamically to a force directed chart?

### ISSUE THREAD

**Issue by zoumath19** [amcharts/amcharts5#1625]
I have some issues and I'm trying to look into the node_modules code to figure out if there is a way to internally handle the addition of nodes in a different manner, rather than using setAll()

Using Angular 18; installed via NPM; this is my import list for reference;

```
import * as am5 from "@amcharts/amcharts5";
import * as am5hierarchy from "@amcharts/amcharts5/hierarchy";
import am5themes_Animated from "@amcharts/amcharts5/themes/Animated";
```

Additionally here is the generic config I have for my chart to keep neat and organized;

```
this.#root = am5.Root.new(this.chart.nativeElement);

    this.#root.setThemes([am5themes_Animated.new(this.#root)]);
    
    let container = this.#root.container.children.push(
      am5.Container.new(this.#root, {
        width: am5.percent(100),
        height: am5.percent(100),
        layout: this.#root.verticalLayout
      })
    );

    this.#series = container.children.push(
      am5hierarchy.ForceDirected.new(this.#root, {
        downDepth: 1,
        initialDepth: 2,
        valueField: "value",
        categoryField: "name",
        childDataField: "children",
        minRadius: 20,
        maxRadius: 35,
        centerStrength: 0.5
      })
    );


```
Here is part of my code as of now that adds some data to my chart,
```

  addNode(item: any) {
    const data = this.#series.data.getIndex(0) as any;
    const categoryNode = data.children.find((node: any) =>
      node.name.toLowerCase() === item.type.toLowerCase()
    );

    if (categoryNode) {
      let mimeTypeNode = categoryNode.children.find((node: any) =>
        node.name === item.mime
      );

      if (!mimeTypeNode) {
        mimeTypeNode = { name: item.mime, children: [] };
        categoryNode.children.push(mimeTypeNode);
      }

      mimeTypeNode.children.push({
        name: `File_${mimeTypeNode.children.length + 1}`,
        value: item.data.size,
      });

      // THIS HERE IS THE BANE OF MY EXISTENCE!
      this.#series.data.setAll([data]);
    } else {
      console.error(`Category ${item.type} not found in the network structure.`);
    }
  }
```
  
 This is also my mock data generation function,
 
```
  simulateDataAddition() {
    const sampleData: Data[] = [
      { type: "gaming", mime: "application/pdf", data: { size: 1024 } },
      { type: "generic", mime: "image/jpeg", data: { size: 2048 } },
      { type: "gaming", mime: "application/pdf", data: { size: 3072 } },
      { type: "generic", mime: "text/plain", data: { size: 512 } },
      { type: "generic", mime: "application/pdf", data: { size: 1536 } },
      { type: "gaming", mime: "text/plain", data: { size: 768 } },
      { type: "generic", mime: "image/png", data: { size: 2560 } },
    ];

    const addDataWithDelay = (index: number) => {
      if (index < sampleData.length) {
        setTimeout(() => {
          this.addNode(sampleData[index]);
          console.log(`Added node: ${sampleData[index].type} - ${sampleData[index].mime}`);
          this.cdr.detectChanges();
          addDataWithDelay(index + 1);
        }, 2000);
      }
    };

    addDataWithDelay(0);
  }
```
  
 I'm looking for something like update(), which is possible to add nodes on demand respecting a specific path, using setAll() feels like a CRUDE solution for only simply adding data...
 
 Also for visual reference, this is how the chart looks; as of now I don't see this structure changing so I only have a 2-deep chart in terms of nodes
 
 
![image](https://github.com/user-attachments/assets/9f5cbece-b4f5-4a8d-81bb-b7e16f59c5bc)

Bonus question; Why isn't there a way to feed backwards the entire dataContext to the series in order to update it in case I wanna update it programmatically and directly... how can I make the series aware it's state changed?

**Comment by martynasma** [comment]
Yes: https://www.amcharts.com/docs/v5/charts/hierarchy/hierarchy-api/#Dynamically_adding_child_nodes

**Comment by zoumath19** [comment]
The thing you linked states that I need to pass a dataitem, in my screenshot above let's assume I want to select the text/plain node and then addChilData() to said node, is it possible to do that? I've seen the findNode() function as well, but I don't think this respects deep-nestedness of graph structures, I might be wrong though, thanks in advance!

**Comment by martynasma** [comment]
You can use the `findNode()` function to look up nodes at any level.

**Comment by zoumath19** [comment]
Great thank you! :)
