### ISSUE TITLE
Date Axis group data property

### ISSUE THREAD

**Issue by pratham3164** [amcharts/amcharts5#1627]
I am working on DateAxis and I have a huge data set to render in the chart. So I tried to group data it renders fewer records but it seems to render the last record in the group. Is it by design or I can change it to show other records as well like the first one in the group?

![image](https://github.com/user-attachments/assets/70052b78-7c40-4a13-a9f4-e32696ae837b)

codepen  for reference: https://codepen.io/ErPratham/pen/oNrzvGB

**Comment by martynasma** [comment]
It uses the value of the last data item in the group by default.

You can change it: https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#aggregation-function

**Comment by pratham3164** [comment]
@martynasma  even after using aggregation function. The datetime in the group is of the last data item . is it possible to show the  datetime of the first or aggregated value in case of max min .

**Comment by zeroin** [comment]
Yes, the time is of the last grouped value.  axis tooltip will show correct date:
https://codepen.io/team/amcharts/pen/gONwVXa

If you need correct date to be shown in tooltip, you will need to create adapter for labelText of a tooltip. This adapter should check what is current base interval and round or format date in a way you want, something like:

```
  tooltip.adapters.add("labelText", (labelText)=>{
    var baseInterval = xAxis0.getPrivate("baseInterval")
    
    if(baseInterval.timeUnit == "day"){
      // round or format date 
    }
    else if(baseInterval == "hour"){
      
    }
    
    return labelText
  })
```



By the way you have some incorrect setup - baseInterval should be minute, not hour:

**Comment by pratham3164** [comment]
the solution seems to work only for the series 0 and series 2 stills shows the same 
![image](https://github.com/user-attachments/assets/a57e8352-3bfc-4ae0-a94e-ebf0ada3efb4)

**Comment by zeroin** [comment]
Did you add the same tooltip and adapter for the second series? It should be a different instance of a tooltip.
