### ISSUE TITLE
Number.MAX_SAFE_INTEGER as AxisRange's endValue

### ISSUE THREAD

**Issue by piozygmunt** [amcharts/amcharts5#1628]
**Bug description**

I'm trying to create XYChart with one gradient for positive values and the same but reverted gradient for negative values. I managed to kinda get it working by using AxisRanges. Also to make it general i have used `Number.MAX_SAFE_INTEGER` and `Number.MIN_SAFE_INTEGER`, but it seems that setting `Number.MAX_SAFE_INTEGER`  as `endValue` in AxisRange doesn't work in Firefox (some smaller values like 500 etc work). Am i doing something wrong here or is it a bug? Also, maybe there is another way to make it work regardless of the data set ? :)

CodePen https://codepen.io/piozygmunt/pen/MWMjgqW

**Environment (if applicable)**

 - amCharts version 5.10.0
 - Browser and its version: Firefox 128.0 / Chrome 127.0.6533.73

**Comment by zeroin** [comment]
This ticket is about the same issue:
https://github.com/amcharts/amcharts5/issues/1633
