### ISSUE TITLE
How to change the modal title & legend of indicators stockchart

### ISSUE THREAD

**Issue by p3777dev** [amcharts/amcharts5#1629]
I want to change the name of the default name of the indicators in the modal as well as the legend.

For Example : 
1) I want to change the Typical Price to TP or anything.
![image](https://github.com/user-attachments/assets/74465213-5d57-48a9-ac76-8386b3dd8766)

2) Also the Indicator Legend of that indicator. 

3) And I have also created some of the custom Indicators by extending already existing indicator. In this case the parent Indicator name is shown in both modal and legend. I want to update/change it.

**Comment by martynasma** [comment]
Use custom theme to translate indicator name and legend:

```JavaScript
const myTheme = am5.Theme.new(root);

myTheme.rule("TypicalPrice").setAll({
  name: "My Funny Indicator",
  shortName: "MFI"
});

root.setThemes([
  am5themes_Animated.new(root),
  myTheme
]);
```

And add locale translation for the Indicator Control:

```JavaScript
root.language.setTranslationsAny({
  "Typical Price": "My Funny Indicator"
});
```
