### ISSUE TITLE
The tooltip above the amchart5 legend tooltip is not visible.

### ISSUE THREAD

**Issue by skulter** [amcharts/amcharts5#163]
Hello. It is being developed with amchart5.
There is a phenomenon in which the upper tooltip is not visible if there are 20 tooltips in the legend.
I want to show the upper tooltip first, but is there a way to show all the tooltips?
Please check the red square in the image.

thank you.
![image](https://user-images.githubusercontent.com/18344213/146898844-245cbe79-2c53-4802-ab81-7d840ddaa212.png)

**Comment by martynasma** [comment]
There's no way to make all tooltips show if they physically don't fit.

I suggest limiting number of tooltips shown:
https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/#Limiting_number_of_tooltips_shown_at_a_time

The above tutorial has a demo where data from multiple series is consolidated into a single tooltip. This might be a good idea for you to consider, too.
