### ISSUE TITLE
[XYChart] Possibiity to move series left or right with zoomX enabled

### ISSUE THREAD

**Issue by Lonli-Lokli** [amcharts/amcharts5#1631]
**Bug description**

It is impossible to move right or left line on XYChart with either right or left mouse when zoomX functionality on cursor enabled

**Environment (if applicable)** Windows

**Comment by martynasma** [comment]
Yes, with a scrollbar:
https://www.amcharts.com/docs/v5/charts/xy-chart/scrollbars/

Or mousehweel:
https://www.amcharts.com/docs/v5/charts/xy-chart/zoom-and-pan/#Mouse_wheel_behavior

**Comment by Lonli-Lokli** [comment]
@martynasma Thanks for quick look, but this is not what I was talking about.

I like the zoom functionality (when you click with left button, select area you want to zoom and then releasing the cursor and after that are is increased to the selection).


But I also liked the possibility to move line left or right without changing the zoom ratio.

You can check current behaviour here - just try to move it left or right, first it will move but as soons as you release the button zoomX will be applied
https://codepen.io/Lonli-Lokli/pen/RwzGGea

What I want to archieve with button is to at least have the possibility to move line with **right** mouse click

**Comment by martynasma** [comment]
I don't think that is possible.

How about you catch a SHIFT press, and change the settings accordingly?

```JavaScript
document.addEventListener("keydown", function(e) {
  if (e.shiftKey) {
    chart.set("panX", true);
    cursor.set("behavior", "none");
  }
});

document.addEventListener("keyup", function(e) {
  if (!e.shiftKey) {
    chart.set("panX", false);
    cursor.set("behavior", "zoomX");
  }
});
```

**Comment by Lonli-Lokli** [comment]
Yes, it worked, thanks for the idea. But could you also think about this feature - to allow this panX 'move' with right button drag?

**Comment by martynasma** [comment]
We'll consider it. Thanks for the suggestion!
