### ISSUE TITLE
Documentation enhancement : Indicator & drawing Calculation info

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1635]
Like there are lot of indicators & drawings, Is there any documentation about that in a single page?
- Like what logic and parameters are being used to calculate that indicator. In a single page[Like this](https://www.amcharts.com/stochastic-momentum-index-indicator/)
- Also same about drawings, like fibonacci drawings what levels amcharts is considering and all.

**Comment by martynasma** [comment]
There is a tutorial about creating custom indicators:
https://www.amcharts.com/docs/v5/tutorials/creating-custom-indicators-for-a-stock-chart/

There's no documentation about each specific indicator though.

You may take a look at their source code tho:
https://github.com/amcharts/amcharts5/tree/master/src/.internal/charts/stock/indicators

**Comment by workingbuddy10** [comment]
@martynasma I am not asking how to create the custom indicators. 
I am just asking, are there are more blogs like this  : https://www.amcharts.com/stochastic-momentum-index-indicator/
for each indicators/drawings present in the website.

**Comment by martynasma** [comment]
No that I know of.
