### ISSUE TITLE
TreeMap - Hover state based on depth

### ISSUE THREAD

**Issue by efitzkiwi** [amcharts/amcharts5#1638]
I would like to know if it is possible to set a hover state based on depth. For example, I would like the categories in an official demo to have a stroke hover effect when hovered:
https://www.amcharts.com/demos/simple-treemap/
Something like: when hovering the blue container, you can see the top left category has a stroke effect
![image](https://github.com/user-attachments/assets/4a68e63e-eccd-4594-b537-f1694cce0d68)

I have tried to implement depth rules based on
```
        seriesRef.bullets.push(function (root, _, dataItem) {
            var depth = dataItem.get("depth");

            if (depth == 1) {
                  // todo set stroke for this container?? how
                  // dataItem.component.states.create("hover", {})
            }
        });
```
But I am unsure/unable to get the sprite/container associated at this depth.

Using Amcharts 5.10.0

**Comment by martynasma** [comment]
I think this can be done using these steps:

1. Create custom "highlight" state for rectangles ("hover" is not good because it will be triggered by hover).
2. Add "pointerover" event to rectangle which applies "highlight" state to parent node.
3. Add "pointerout" event to rectangle which removes "highlight" state to parent node.

```JavaScript
  am5hierarchy.Treemap.new(root, {
    singleBranchOnly: false,
    downDepth: 1,
    upDepth: -1,
    initialDepth: 2,
    valueField: "value",
    categoryField: "name",
    childDataField: "children",
    nodePaddingOuter: 2,
    nodePaddingInner: 2
  })
);

series.rectangles.template.setAll({
  strokeWidth: 2,
  strokeOpacity: 1,
  interactive: true,
  stroke: am5.color(0xffffff)
});

series.rectangles.template.states.create("highlight", {
  stroke: am5.color(0x000000)
});

series.rectangles.template.events.on("pointerover", function(ev) {
  const target = ev.target.dataItem;
  const parent = target.get("parent");
  if (parent) {
    parent.get("rectangle").states.applyAnimate("highlight");
  }
});

series.rectangles.template.events.on("pointerout", function(ev) {
  const target = ev.target.dataItem;
  const parent = target.get("parent");
  if (parent) {
    parent.get("rectangle").states.applyAnimate("default");
  }
});
```

Example:
https://codepen.io/team/amcharts/pen/poXRzxQ?editors=0100
