### ISSUE TITLE
maskBullets on chart to "spill out" of the plot area

### ISSUE THREAD

**Issue by czogran** [amcharts/amcharts5#1639]
In amCharts 4, there is an option to mask bullets on the whole chart.
![image](https://github.com/user-attachments/assets/8283d7db-7794-438c-bcf0-3235197868e1)

 amCharts 5 provides the feature to mask bullets on a series.  
![image](https://github.com/user-attachments/assets/211876cc-ffe9-4ba0-9f09-deb039410deb)

I have a chart in amCharts 4 with extra labels for each column.  
![image](https://github.com/user-attachments/assets/e51b4817-6ad3-4375-8d91-d6f6f2a266ac)

I would like to achieve similar effects with amCharts 5. However, I am struggling because I do not see how to do it based on the tutorials below:
https://www.amcharts.com/docs/v5/tutorials/handling-bullet-masking/
https://www.amcharts.com/docs/v5/tutorials/column-labels-as-categories/

Am I missing the proper configuration option, or is it not currently doable?

**Comment by martynasma** [comment]
The second link from your post does exactly that. What specifically are you struggling with?

**Comment by czogran** [comment]
The problem is that in amchart4 when I indexed labels I was able to achiave this effect:  
![image](https://github.com/user-attachments/assets/c53b8adc-2c94-477a-b380-4b0ed3dfdd30)  

If I understand correctly in amchart5 flow of wrapping labels is other. I was able to achieve similar effect by moving labels "down", not by wrapping:  
https://codepen.io/czogran/pen/yLdgeKb

**Comment by czogran** [comment]
I was able to recreate problem in amchart5  
please change line 89
  https://codepen.io/czogran/pen/yLdgeKb 
  
  when for amchart4 it is working  
  line 36
  https://codepen.io/team/amcharts/pen/NMgBob

**Comment by martynasma** [comment]
I still don't get it what is the "problem"? Neither of those CodePens look like the screenshot you provided.

**Comment by czogran** [comment]
Excuse me for the inconvenience.
I am not used to CodePen and I did not click save after editing (since I am used to autosaving).

Here should be an example with which I am struggling:
https://codepen.io/czogran/pen/yLdgeKb

**Comment by martynasma** [comment]
Line 89 is `min: 0`?

I must be missing something, but what's the issue?

**Comment by czogran** [comment]
I hope that this time I properly saved code Pen example.

Amchart4:  
https://codepen.io/czogran/pen/QWXpPZj

Amchart5:
https://codepen.io/czogran/pen/yLdgeKb

In amchart4 I managed to have such screen.  
![image](https://github.com/user-attachments/assets/30ab2a64-8b90-4e6e-ac83-4cc72316c499)  

In amchart5 you have to change min: 0 to for example -10.   
Another question is that -Number.EPSILON and Number.epsilon work diffrently in Am4 and Am5. When I changed  from -Number.EPSILON to Number.EPSILON in Am5 it seems to work.  
![image](https://github.com/user-attachments/assets/fae18824-dd57-4127-b53c-4f5fa91e53f0)

**Comment by martynasma** [comment]
Once again, what is the problem? That the labels with 2021, 2022 are on top instead of bottom?

**Comment by czogran** [comment]
"L1" labels are the problem

**Comment by martynasma** [comment]
Why exactly are you using `Number.EPSILON` instead of just `0` (zero)?

**Comment by czogran** [comment]
I have inherited this piece of code.  
There is subtle diffrence between Number.EPSILON and 0 in amchart4, depending on series creation order (when

![image](https://github.com/user-attachments/assets/c19459af-5cb3-4353-9890-e46b74079c6a)

I have modified Am4 example to present this behaviour.
https://codepen.io/czogran/pen/QWXpPZj

**Comment by martynasma** [comment]
Negative `Number.EPSILON` is below zero. You have your Y-axis set `min: 0` meaning anything below zero is hidden, including bullets.

I'm not sure what else to say. Either fix your data to not have negative values, or remove the `min: 0` from axis configuration.
