### ISSUE TITLE
Triggering "hover" state for series' bullets on current cursor position

### ISSUE THREAD

**Issue by luktom** [amcharts/amcharts5#164]
Hi, in v4 it is possible to trigger the "hover" state for a series' bullet on current cursor position. It is described here: https://www.amcharts.com/docs/v4/concepts/chart-cursor/#Series_bullets 

Is it possible in v5, if not, do you plan to implement it?

**Comment by martynasma** [comment]
Maybe this demo will help:
https://codepen.io/team/amcharts/pen/VwMbpjQ

**Comment by luktom** [comment]
@martynasma thanks for the demo. It contains only one series, how to do that easily for multiple series? 

I need to manually find the closest series to current cursor position. Would be nice to have the reference to the current closest series already in the cursor object or to pass the hover event to the bullet like in v4.

**Comment by martynasma** [comment]
We're adding `tooltipSeries` to `XYChart` in next version, which you'll be able to refer to for a list of series that tooltip is being shown for.

**Comment by martynasma** [comment]
Implemented in [5.0.19](https://github.com/amcharts/amcharts5/releases/tag/5.0.19).

## [5.0.19] - 2021-12-27

### Added
- `groupDataDisabled` setting added to XYSeries. If set to `false` will exclude series from data grouping mechanism, even if it is enabled on related `DateSeries`.
- New plugin `SliceGrouper`. Can be used to automatically group small slices on percent charts like Pie, Funnel, etc. [More info](https://www.amcharts.com/docs/v5/charts/percent-charts/grouping-slices/).

### Fixed
- If data was added to percent series after initial data was already processed, the bew slices would get colors from the start of the color set.
- Multiple square bracket and apostrophe escaping was not working properly.
- A JS error could occur when changing `XYSeries` data with less data items then there were before.
- `PieSeries` were not arranging its labels properly in some cases.
- `XYCursor` taps were not working properly after chart zoom on touch devices.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by luktom** [comment]
@martynasma with that enhancement it is possible now to manipulate the bullets when there are multiple series. Many thanks for that :)
