### ISSUE TITLE
Сhange color of candlesticks

### ISSUE THREAD

**Issue by OstapchelaEst** [amcharts/amcharts5#1642]
I'm trying to implement a function to change the color of candlesticks in the chart after clicking on a button and encountered a problem. As an example I used the code provided [here](https://www.amcharts.com/docs/v5/charts/xy-chart/series/candlestick-series/#Modifying_colors) in the documentation. However, following it, I have not been able to change the initial color of candlesticks and also change it after pressing the button

Here my [code](https://codepen.io/Limyr-Zbagoinii/pen/gONgvjm?editors=0010)

**Comment by zeroin** [comment]
If you push "pro" theme tag, you should use "riseFromPrevious" / "dropFromPrevious" themes:

```
series.columns.template.states.create("riseFromPrevious", {
  fill: am5.color(0xffda44),
  stroke: am5.color(0xffda44)
});

series.columns.template.states.create("dropFromPrevious", {
  fill: am5.color(0x2c344b),
  stroke: am5.color(0x2c344b)
});
```

Same for changing colors on button click, but you also need to mark series values as dirty for the color to change:

```
  series.markDirtyValues();
```
