### ISSUE TITLE
How to stick Title for column group to the left most position of chart

### ISSUE THREAD

**Issue by Ashishvkale** [amcharts/amcharts5#1649]
I have grouped my column in column series
Each group has tittle and those are moving when horizonatl scrollbar is moved.

I want **Title for column group** to stick to left most to the chart (no matter chart is getting scrolled left or right) 
Below is the code pen for the same:

https://codepen.io/ashish-kale-ak/pen/KKjWqKB?editors=0010

**Comment by martynasma** [comment]
I'd just use axis ranges to add those titles:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/axis-ranges/
