### ISSUE TITLE
Hover state is not working correctly on the series bullet

### ISSUE THREAD

**Issue by luktom** [amcharts/amcharts5#165]
Hover state is not working correctly on the series bullet, i.e. it is correctly applied on mouse hover, but bullets stays in "hover" state even if mouse pointer is out of the bullet area.

I modified one of your demo examples on jsFiddle to show the problem, please see: https://jsfiddle.net/rcgs7h5y/14/ (bullet is on the last data item).

**Comment by martynasma** [comment]
I would recommend using `fillOpacity` on a bullet circle, rather than `opacity` on a container.

```JavaScript
series.bullets.push(function(root, series, dataItem) {  
  if (dataItem.dataContext.bullet) {    
    var container = am5.Container.new(root, {
    });
    var circle0 = container.children.push(am5.Circle.new(root, {
      radius: 10,
      fillOpacity: 0,
      interactive: true,
      fill: am5.color(0xff0000)
    }));
    
    circle0.states.create("hover", {
      fillOpacity: 1
    });

    return am5.Bullet.new(root, {
      sprite: container
    })
  }
})
```

**Comment by luktom** [comment]
@martynasma that solves my problem. Thanks!
