### ISSUE TITLE
Add current volume label to stock chart

### ISSUE THREAD

**Issue by shishima123** [amcharts/amcharts5#1659]
Hello

I want to add a label that displays the volume similar to the price label. Its position will change based on the height of the last volume column.

I don't know how to convert the height value of the volume to the corresponding price on the value axis.

Can you give me some advice?

[My JSFiddle](https://jsfiddle.net/shishima/rtzw4ged/1/)

it will look like this
![image](https://github.com/user-attachments/assets/d242b74c-944d-417d-83b3-72ee857b9572)

**Comment by martynasma** [comment]
Well, you don't have to convert anything. You just need to add an axis range to the same value axis that your volume series uses.

https://jsfiddle.net/gt68j0mr/1/

**Comment by shishima123** [comment]
Genius! It's working perfect
Thanks
