### ISSUE TITLE
Hierarchy charts - Tree Map - Data processor will work for one level ?

### ISSUE THREAD

**Issue by ArunPragadeeswar007** [amcharts/amcharts5#1660]
**Bug description**

I am using a random color for the treemap, and I expect the tooltip color to pick the alternative color from the background. However, this approach fails because I missed converting the color code to a color object. While I found that a data pre-processor can convert the color code to a color object, it only works for the parent level. I need this functionality to apply to the children as well. I believe using adapters might solve this issue but is it possible to fix using the data pre-processor?

**Example** : https://codepen.io/Arunpragadeeswar/pen/QWXgPvz

**Environment (if applicable)**
Version : Amcharts 5
Browser : Chrome
Framework : Ember

**Comment by martynasma** [comment]
That is correct. DataProcessor will only process top-level of data, and will not do recursive processing.

I hope it's not a huge issue.

**Comment by ArunPragadeeswar007** [comment]
@martynasma  how can convert the color codes to color object for nested data ?

**Comment by martynasma** [comment]
You can build your own data iterator and just convert colors to Color objects via static function `am5.Color.fromAny(....)`.
