### ISSUE TITLE
Adding button with tooltip of valueAxis stock chart

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1663]
I am using the stock chart, where there is a movable tooltip with cursor on dateAxis and valueAxis.

Just adjacent to that I want to add a button too, and on clicking that we will create/initiate a horizontal line.
This helps to create more accurate levels, at that price.

My concern is : 
- I am able to display the button inside the tooltip, but : 
- I am not able to place the button just outside to the tooltip (as shown in the image). It should be attached & synced with the tootlip.

Codepen  : https://codepen.io/Ansh-m-the-reactor/pen/JjQyrqB

How can we add a button ? Like this : 
![image](https://github.com/user-attachments/assets/f1d18ca7-1bb1-4f41-894b-97b8f4000049)

`I just want a sticky button on the container of the tooltip of the valueAxis.`

**Comment by martynasma** [comment]
I suggest using built-in buttons:

```JavaScript
tooltip.setAll({
  layout: root.horizontalLayout
});

var button = tooltip.label.children.unshift(am5.Button.new(root, {
  //isMeasured: false,
  centerX: am5.p100,
  // width: 40,
  // height: 20,
  x: am5.p0,
  y: am5.p0,
  dx: -50,
  label: am5.Label.new(root, {
    text: "BT"
  })
}));

button.events.on("click", function() {
  console.log("Clicked");
});
```

**Comment by workingbuddy10** [comment]
Did exactly what you said @martynasma , but the button is not appearing :
The codepen : https://codepen.io/Ansh-m-the-reactor/pen/JjQyrqB

**Comment by zeroin** [comment]
You created a tooltip but did not assign it to valueAxis. So it's just an instance which is not used anywhere.

Try adding: `valueAxis.set("tooltip", tooltip);`

**Comment by workingbuddy10** [comment]
Genius @martynasma & @zeroin it worked!!
