### ISSUE TITLE
Column series getting clustered after adding more data

### ISSUE THREAD

**Issue by Ashishvkale** [amcharts/amcharts5#1668]
Here I'm trying to show more data on horizontal scroll but it's getting clustered, even after making clustered false and giving height.
here's a dummy video:

**It gets messed up on horizontal scroll. I want to keep it clean on scroll as previous.**

Code for same:
```

              columnseries = this.chart.series.push(
                am5xy.ColumnSeries.new(this.root, {
                    xAxis: this.dateAxis,
                    yAxis: this.categoryAxis,
                    openValueXField: "start",
                    valueXField: "end",
                    categoryYField: "categorySeries",
                    paddingLeft: 0,
                    clustered: false,
                    sequencedInterpolation: true
                })
            )

            columnseries.data.processor = am5.DataProcessor.new(this.root, {
                dateFields: ["start", "end"]
            })

            columnseries.data.setAll(activities)
 
```

**It gets messed up on horizontal scroll. I want to keep it clean on scroll as previous.**

And if I make it manually then vertical scrollbar is not able to scroll all the way down, gets freezed...

**Comment by martynasma** [comment]
Isn't this the same as here?: https://github.com/amcharts/amcharts5/issues/1643#issuecomment-2263316275

**Comment by Ashishvkale** [comment]
@martynasma 
No that was issue regarding autozoom of date axis,
Here you can see columns are getting messed up 
Not maintaining clean interface

**Comment by martynasma** [comment]
Can you post your chart as a CodePen?

**Comment by Ashishvkale** [comment]
Sure

**Comment by martynasma** [comment]
Not really. The CodePen you shared does not resemble the behavior in your demo.

I'm sorry, but please understand we cannot dedicate a lot of time for guesswork. In order for us to be able to swiftly provide solutions, we need a repro case as refined and distilled as possible.

Please make sure the issue is reproducible in your CodePen, and there's no redundant code to sift through.

I hope that sounds reasonable.

**Comment by Ashishvkale** [comment]
Got It. 
I am closing this question as of now. 
I will open another one with minimal exact reproducible code pen.
Thanks for understanding
