### ISSUE TITLE
Legend label oversizedBehaviour without maxWidth

### ISSUE THREAD

**Issue by eldair** [amcharts/amcharts5#1669]
**Question**

Hello, is it possible to make legend label have oversizedBehavior without maxWidth? Entire legend has maxWidth of 200 and I want valueLabel to always be visible so something like flex where the text label is dynamically resized to fit without affecting valueLabel.

**Comment by martynasma** [comment]
> Hello, is it possible to make legend label have oversizedBehavior without maxWidth?

No, I'm afraid.

**Comment by eldair** [comment]
@martynasma thanks for getting back to me. And what about percent? I tried but it didn't have any effect.

**Comment by martynasma** [comment]
`maxWidth` accepts only absolute pixel values 🙁

**Comment by eldair** [comment]
@martynasma okay, thanks for your answers, I'll find some solution :)
