### ISSUE TITLE
Chart exporting size under different resolutions

### ISSUE THREAD

**Issue by koorizhizhi** [amcharts/amcharts5#167]
Hi, I am trying to export multiple gauge charts with `exporting.exportImage("png")` and putting them on a Html canvas as image objects for further presentation. Size of div elements for Amcharts are set to 100%.

Because my Html canvas has a fixed size, I need to clip(chop off the blank part of the exported images) and scale down what I've got from the exporting. 

The point is that it seems charts are differently sized under different resolutions(the lower the resolution is , the bigger the chart is). If I use a fix value for parent div element,  the original chart might be chopped off before being exported.  

So it is very difficult for me to make them sized correctly on canvas. The clipping and scaling operation works properly under one certain resolution but can be a mess under a different one since I can only handle their sizes on a relative level. 

Is there any way to make the size of exported charts be an absolute value?

**Comment by martynasma** [comment]
You can make images export at the same size as the chart appears on screen:
https://www.amcharts.com/docs/v5/concepts/exporting/exporting-images/#Pixel_ratio

However, doing so might reduce quality.

You're probably better off sizing your target canvas taking `window.devicePixelRatio` into account, this way you will not be losing any image quality.

**Comment by koorizhizhi** [comment]
It seems works with exporting options and set the size of parent div to be fixed...

**Comment by koorizhizhi** [comment]
> You can make images export at the same size as the chart appears on screen: https://www.amcharts.com/docs/v5/concepts/exporting/exporting-images/#Pixel_ratio
> 
> However, doing so might reduce quality.
> 
> You're probably better off sizing your target canvas taking `window.devicePixelRatio` into account, this way you will not be losing any image quality.

Thank you very much. I'll try to make it this way.
