### ISSUE TITLE
Can't add tooltip on hover on X axis item

### ISSUE THREAD

**Issue by sme-solo004** [amcharts/amcharts5#1670]
**Bug description**

https://codepen.io/sme-solo004/pen/abgLrKJ
**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
Please refer to this tutorial:
https://www.amcharts.com/docs/v5/concepts/common-elements/labels/#interactive-axis-labels

**Comment by sme-solo004** [comment]
@martynasma may I ask you to sent working example in codepen or similar, because using that instructions I can't get expected result, thanks.

**Comment by sme-solo004** [comment]
@martynasma any updates?

**Comment by martynasma** [comment]
The examples on the link I provided are pretty straightforward. Is there something you have trouble with?
