### ISSUE TITLE
Violin Chart Possible with amcharts5?

### ISSUE THREAD

**Issue by btbritz** [amcharts/amcharts5#1672]
I noticed there are a number of charts that are really close to a violin chart similar to this one:

<img width="554" alt="Screenshot 2024-08-14 at 1 58 45 PM" src="https://github.com/user-attachments/assets/445274d6-0685-4f55-9d73-a2b8db0d4e42">

Is it possible to get a violin chart using a custom configuration on an existing amchart series? Maybe SmoothedXLinesSeries (?) mixed with something else?

Thanks

**Comment by martynasma** [comment]
Yes, just posted this demo:
https://www.amcharts.com/demos/violin-chart/
