### ISSUE TITLE
The word cloud graphic presents the blurred emojis in the Firefox browser

### ISSUE THREAD

**Issue by oterVs** [amcharts/amcharts5#1675]
**Bug description**
The word cloud graphic presents the blurred emojis in the Firefox browser

**Environment**
amCharts: 5.10.1
Firefox: 129.0.1
Framewook: React

**Additional context**
https://codesandbox.io/p/sandbox/cloud-amcharts-2qnyp9

![imagen_2024-08-15_123103022](https://github.com/user-attachments/assets/ec1c8807-fbc9-4ae0-bea3-c9167e66b91b)

**Comment by martynasma** [comment]
This might be due to a bug in Firefox:
https://bugzilla.mozilla.org/show_bug.cgi?id=1912431

It seems like it is being fixed in future versions - namely 130 an d131. Let's see if it's fixed when those versions for FF release.
