### ISSUE TITLE
Tooltip - customization

### ISSUE THREAD

**Issue by barrygwhite** [amcharts/amcharts5#168]
Hi, 
Is there a way to customize the tooltip as it was in am4? I know the html tooltip is not ready, but can we manipulate the tooltip a bit more than how it is shown in the tooltip documentation? https://www.amcharts.com/docs/v5/reference/tooltip/
````
	var tooltip = am5.Tooltip.new(root, {
		getFillFromSprite: false,
		getStrokeFromSprite: false,
		autoTextColor: false,
		getLabelFillFromSprite: true,
                height: 40,
                width: 100,
		labelText: "[#f00]{name}[/]\n{value}"
	});
````	
For example, I would like to change shape of tooltip, add some separator between elements in labelText etc.
 Is it possible in am5?

**Comment by martynasma** [comment]
Well, the `background` of the tooltip is an element of type `PointedRectangle`. You can use it to modify some parameters like corner radius and pointer length.

```JavaScript
tooltip.get("background").setAll({
  cornerRadius: 2,
  pointerLength: 5
});
```

Refer to class ref for a list of available settings:

https://www.amcharts.com/docs/v5/reference/pointedrectangle/#Settings

As for separator, do you mean like horizontal line?

You could use a Unicode character "Continuous line":
https://www.compart.com/en/unicode/U+23AF

E.g.:

```
labelText: "{name}\n⎯⎯⎯⎯⎯⎯⎯⎯\n{value}"
```

**Comment by barrygwhite** [comment]
> Refer to class ref for a list of available settings:
> 
> https://www.amcharts.com/docs/v5/reference/pointedrectangle/#Settings

This is exactly what I was looking for, thank you.

Yes, horizontal line. I'll need to find something else but thanks. 
Regarding the labelText - can we do some modification with the position of the label in the tooltip, some padding etc?

**Comment by martynasma** [comment]
You can set padding settings on tooltip's label of course.

```JavaScript
tooltip.label.setAll({
  paddingLeft: 10,
  paddingRight: 10
});
```

**Comment by barrygwhite** [comment]
Prefect, thank you.
