### ISSUE TITLE
`maxPanOut` does not work with mouse wheel

### ISSUE THREAD

**Issue by martynasma** [amcharts/amcharts5#1681]
Example: https://www.amcharts.com/demos/stock-chart/

**Comment by martynasma** [comment]
Fixed in [5.10.3](https://github.com/amcharts/amcharts5/releases/tag/5.10.3).

## [5.10.3] - 2024-08-23

### Fixed
- The chart would not allow overzooming using mouse wheel since `5.10.2`. It will now allow overzoom based on axis' `maxDeviation` setting.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by workingbuddy10** [comment]
@martynasma  Do I have to do any change in the codepen too?
https://codepen.io/team/amcharts/pen/ZENawbv
