### ISSUE TITLE
Can we sync the multiple stockchart

### ISSUE THREAD

**Issue by prackode** [amcharts/amcharts5#1685]
I know we can sync the charts if we push multiple charts in the same panel, but in my case I have multiple charts instances. Each has its own **root**, valueAxis, dateAxis and its properties.

How can we sync cursor/zooming and other properties

**Comment by martynasma** [comment]
Please refer to this demo: https://www.amcharts.com/docs/v5/tutorials/syncing-axis-zooms-across-multiple-charts/

It uses simple XYCharts but, you can do exact same with stock panels on different StockCharts.
