### ISSUE TITLE
Chart stock with large data

### ISSUE THREAD

**Issue by shishima123** [amcharts/amcharts5#1686]
Hello, is there a way to reduce lag and increase performance for stock charts when handling large data?

My chart can accommodate up to 15,000 candles, and it can display up to 3,000 candles on the screen at a time.

Since I need to display additional information, I can't group the data.

Are there any options to limit events? Or any way to enhance performance?

[Demo Fiddle](https://jsfiddle.net/shishima/7nxajeo4/5/)

**Comment by martynasma** [comment]
It doesn't look like you have data item grouping enabled. I strongly advise to do so.

https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#dynamic-data-item-grouping

It'll not only solve the performance issue, but also increase UX (try making a sense of 3000 candles crammed into 1000px chart).

**Comment by shishima123** [comment]
I understand the magic of the "data item grouping" feature; however, since our data includes lines on the screen, enabling the "data item grouping" feature will cause these lines to no longer display accurately.

Do you have any other ideas?

![image](https://github.com/user-attachments/assets/38b82368-c330-4248-a2f6-18ba473b81ba)

**Comment by martynasma** [comment]
You can disable data item grouping for each series selectively. Try enabling grouping generally, but disabling it for the line series.

https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#selectively-disabling-grouping

**Comment by martynasma** [comment]
Would you be able to update your jsFiddle as per above?
