### ISSUE TITLE
ValueAxis tooltip position

### ISSUE THREAD

**Issue by prackode** [amcharts/amcharts5#1687]
I need to hide the valueaxis and its tooltip to be aligned right.

     var valueAxis = mainPanel.yAxes.push(
        am5xy.ValueAxis.new(instance, {
          renderer: am5xy.AxisRendererY.new(instance, {
            opposite: true
          }),
          extraMin: 0.1,
          extraTooltipPrecision: 2,
          tooltip: am5.Tooltip.new(instance, {}),
          numberFormat: "#,###.00",
          // visible: false
        })
      );

![image](https://github.com/user-attachments/assets/2a25b7ce-df1b-43b7-8daf-e40b7654960d)

visible: false
![image](https://github.com/user-attachments/assets/cf981b25-ae20-410c-8b19-045548cbfc0f)

Is there any alternative to show tooltip on the right other than `opposite: true` ?

**Comment by martynasma** [comment]
Just use `inside: true` instead, and hide only labels:

```JavaScript
var valueAxis = mainPanel.yAxes.push(
  am5xy.ValueAxis.new(instance, {
    renderer: am5xy.AxisRendererY.new(instance, {
      inside: true
    }),
    extraMin: 0.1,
    extraTooltipPrecision: 2,
    tooltip: am5.Tooltip.new(instance, {}),
    numberFormat: "#,###.00"
  })
);

valueAxis.get("renderer").labels.template.set("forceHidden", true);
```
