### ISSUE TITLE
Responsive chart issue

### ISSUE THREAD

**Issue by prackode** [amcharts/amcharts5#1690]
Responsive theme doesn't utilize the grid space completely, although it works fine with full screen but I need to display as a widget

![image](https://github.com/user-attachments/assets/c936fd0c-ca32-4023-84d6-e1544033a934)

**Comment by martynasma** [comment]
If your chart is less than 100px in height, there should not be padding on top and bottom, unless you have default rules disabled or changed.

Do you have an working example?
