### ISSUE TITLE
Unable to create Axis range in stockchart

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1694]
As suggested here https://github.com/amcharts/amcharts5/issues/1673#issuecomment-2320337507,  I was trying to create the axis range.

But the issue is, I have a toggle button where user can remove the grid in the background if they want.

In this case, I am unable to create the axis range if the user has turned off the grid in the stockchart.

I did this  :
If user turn off the grid lines, I just toggle the below boolean :
```
valueAxis?.get("renderer")?.grid.template.set("forceHidden", true);
dateAxis?.get("renderer")?.grid.template.set("visible", false);
```

for creating the axis range :
```
// Create axis ranges
  var rangeDataItem = valueAxis.makeDataItem({
    value: 500,
  });
  
  var range = valueAxis.createAxisRange(rangeDataItem);
```

**Comment by martynasma** [comment]
In this case you need to turn on grid for axis range.

```JavaScirpt
range.get("grid").set("forceHidden", false);
```

**Comment by workingbuddy10** [comment]
That's the issue @martynasma , I can't !
It's a user level option.

So is there any way to draw a line with the label. On dbclick on the valueAxis. https://github.com/amcharts/amcharts5/issues/1673#issuecomment-2320311353

**Comment by martynasma** [comment]
Yes, you can just add an axis range to the axis. Axis range can both have grid and label. You can configure the way you need to, including adding a button to the label.

https://www.amcharts.com/docs/v5/charts/xy-chart/axes/axis-ranges/

**Comment by workingbuddy10** [comment]
Did the same @martynasma  in the codepen : https://codepen.io/Ansh-m-the-reactor/pen/ZEPrbrb?editors=0010
It's written in the last part of the code.

What I want :
- On the dbclick on the valueAxis, create a line & label showing the price where user clicked.

**Comment by workingbuddy10** [comment]
And also @martynasma , using the same code in codepen. If I add the grid it works, but I don't want to make it dependent on the chart grid.

**Comment by martynasma** [comment]
What are you having issue with? Finding an Y-axis value where click occurred?

**Comment by workingbuddy10** [comment]
Yes @martynasma , can you please check the codepen !
If you are able to create that line by clicking on the valueAxis or even by giving the default value. The code for this is written in the last part of the code!

**Comment by martynasma** [comment]
This might help:
https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/#tracking-cursor-movement

**Comment by workingbuddy10** [comment]
See I have added only below part of the code for creating a static axis range :
```
valueAxis?.get("renderer")?.grid.template.set("forceHidden", true);
dateAxis?.get("renderer")?.grid.template.set("visible", false);
var rangeDataItem = valueAxis.makeDataItem({
  value: 1210
});


// Create a range
var range = valueAxis.createAxisRange(rangeDataItem);
range.get("grid").setAll({
  stroke: am5.color(0xff621f),
  strokeOpacity: 1,
  location: 0.5
});
```
In my stockChart
and @martynasma according to what you say, it should have created the line and label at 1200 level. But it is not creating.

My Goal is : 
- Create that line by clicking on the valueAxis, that will create Label + Line ( infinite).
- So just to head start I added a static value to the range at least it should create a line with label. Then I'll make it dynamic on the user click.

**Comment by workingbuddy10** [comment]
It will look like this @martynasma : 
video from Trading Technologies software.

https://github.com/user-attachments/assets/4a839488-6a67-4ef9-9f50-d6e3583cbd74

It's similar to this : https://www.amcharts.com/docs/v5/charts/stock/toolbar/drawing-control/#Adding_line_drawings
It's just in this case you won't clicking on the plus button, instead you will be clicking on the valueAxis.
