### ISSUE TITLE
XY Chart with categories not showing all categories after upgrade from 5.9.13 to 5.10.x

### ISSUE THREAD

**Issue by upsite4k** [amcharts/amcharts5#1695]
I got an XY chart as shown below, which was working till upgrading from 5.9.13 to 5.10.x .
I attached a jsFiddle. https://jsfiddle.net/upsite/wp1qcL5y/4/
What has changed? What do i need to change

![image](https://github.com/user-attachments/assets/cd708d8e-43c8-486c-ab78-5135547780b5)

vs

![image](https://github.com/user-attachments/assets/a8c38d5a-abb3-42b3-aa7d-b2188be37288)

jsFiddle here https://jsfiddle.net/upsite/wp1qcL5y/4/

**Comment by zeroin** [comment]
We assume that series and category axis data is sorted in the same manner, this is done to optimize performance. So you should inverse data of your yAxis. To inverse the order of the axis, just set `inversed:true` for your yAxis renderer.

https://jsfiddle.net/bfwpxLr2/
