### ISSUE TITLE
Rangechanged event not firing as expected

### ISSUE THREAD

**Issue by alienbuild** [amcharts/amcharts5#1697]
Aggregation and detailed views aren't changing on zoom in/out and doesn't appear that the `rangechanged `event is being triggered by lack of console logs. I've also tried adding in some additional events for testing.

https://jsfiddle.net/g0y5uc98/

 - Latest AmCharts 5 
 - React

**Comment by martynasma** [comment]
Axis does not have `rangechanged` event, only `Scrollbar` does.

https://www.amcharts.com/docs/v5/?s=rangechanged

**Comment by alienbuild** [comment]
> Axis does not have `rangechanged` event, only `Scrollbar` does.
> 
> https://www.amcharts.com/docs/v5/?s=rangechanged

Thanks - I've also tried 'wheel', 'boundschanged' and a few other events but nothing seems to trigger the aggregation/explosion of the bars.

https://www.amcharts.com/docs/v5/reference/dateaxis/#Events

**Comment by martynasma** [comment]
I'd say you're better off monitoring private setting for `selectionMin` and `selectionMax`:

```JavaScript
xAxis.onPrivate("selectionMin", function(min) {
  console.log(min)
});

xAxis.onPrivate("selectionMax", function(max) {
  console.log(max)
});
```
