### ISSUE TITLE
In Bar chart how to align Labels to Bar when few labels are shown on axis?

### ISSUE THREAD

**Issue by shailendrativrekar97** [amcharts/amcharts5#1698]
In Amcharts bar chart or Column Chart, when lot of data is plotted in graph to avoid clutter or overlap few labels are shown on X-Axis which are uniformly aligned with equal spaces in between each label, thus the labels are moved  from the bar it belongs to, how to align the label to that particular bar.

Example for Codepan [https://codepen.io/shylen97/pen/zYVmaxv](url)

**Comment by zeroin** [comment]
Add `minorGridEnabled:true` for your x axis renderer:

`am5xy.AxisRendererX.new(root, { minGridDistance: 80, minorGridEnabled:true }),`
