### ISSUE TITLE
Possible to sync Orderflow chart with the stockChart

### ISSUE THREAD

**Issue by p3777dev** [amcharts/amcharts5#1699]
I am already using StockChart of amcharts5. I want to add a orderflow chart in that, which is created using the Time and sales data.
It looks like this :
![image](https://github.com/user-attachments/assets/3464d916-9de3-45ec-a3bb-f08b25f1e4eb)
[Image](https://www.trader-dale.com/wp-content/uploads/2020/05/Screenshot_25.png)
I want to show the additional information (like buyVolume, sellVolume) attached with the individual candlesticks. And also I don't want to hinder my ongoing features of stockcharts like lazy loading, panning Live updates etc.

full description :
NOTE : I am only interested to show the additional info with respective to candle like shown in the image. 
https://www.trader-dale.com/beginners-guide-to-order-flow-part-1-what-is-order-flow/

So my question is how can I achieve this feature? What all components should I use of amcharts, excluding stockcharts.

**Comment by martynasma** [comment]
I'm afraid we don't have any examples or guidance on how to implement this.

**Comment by p3777dev** [comment]
Thanks @martynasma for your response!
Let's talk about bare minimum part which I require : 
- Is there any way, where I can show some info on/around individual candles? Like writing **text** around the individual candles? Kinda sticky notes around each candle.

**Comment by martynasma** [comment]
> Is there any way, where I can show some info on/around individual candles? Like writing text around the individual candles? Kinda sticky notes around each candle.

Yes. Bullets :)

https://www.amcharts.com/docs/v5/concepts/common-elements/bullets/

**Comment by workingbuddy10** [comment]
@martynasma I got the way where I can adjust and show that info.
Its the combination of heatmap + stockchart.

Although everything is working, I have only 2 doubts :
- I want the cell size to be small, just limited to the candlesticks. 
- And I am unable to pan/zoom the chart.

I am trying to make something like the below image: Its the combination of the Heatmap and candlesticks on Echart library.
![image](https://github.com/user-attachments/assets/f045bca1-0e44-4786-99e9-196bbae2900c)

Each green/red gradient cell is an individual value of that with respect to that price point. So multiple cells of the heatmap is getting stack upon eachother. As the date is same of that cell.
Data looks like this : 
You can see 2 data points with the same date. 
```
            [
                "26-08-2024",
                3.0,
                0.0,
                303.0,
                303.0,
                303.0,
                "303x0x0",
                "0x0x303",
                0.0
            ],
            [
                "26-08-2024",
                4.25,
                0.0,
                6.0,
                6.0,
                6.0,
                "6x0x0",
                "0x0x6",
                0.0
            ],
```
