### ISSUE TITLE
How to define node colors in Sankey diagram?

### ISSUE THREAD

**Issue by vaibhavad** [amcharts/amcharts5#17]
amcharts4 way of [defining colors ](https://www.amcharts.com/docs/v4/chart-types/sankey-diagram/#Node_color_via_color_data_field)of the nodes doesn't work in amchart5. How can I set the color of each node?

**Comment by martynasma** [comment]
Take a look here:
https://www.amcharts.com/docs/v5/charts/flow-charts/sankey-diagram/#Node_colors_via_data

You'll need to upgrade to the latest version for this to work, though.

**Comment by vaibhavad** [comment]
Thanks a lot!
