### ISSUE TITLE
What happenend to createFromConfig?

### ISSUE THREAD

**Issue by RainerAtSpirit** [amcharts/amcharts5#170]
In v4 we've been able to store JSON configurations on the server or build them on the fly. I was expecting that in v5 there's still a `createFromConfig` method. However, it looks like it's gone. What is the recommended upgrade path when it comes to building v5 charts based on JSON?

**Comment by martynasma** [comment]
I'm afraid JSON configs are not available in amCharts 5. At this time we do not have plans to implement those.

Sorry for the inconvenience.
