### ISSUE TITLE
Enhance the selection capability of the drawing

### ISSUE THREAD

**Issue by shishima123** [amcharts/amcharts5#1706]
I think changing the method of selecting a drawing from clicking the entire shape, as it is currently, to only being able to select from the border would be better.
With the old method, you wouldn't be able to select a line drawing when it's beneath a square drawing.
With the new method, you can overcome this.

Additionally, changing the cursor to a hand would make the selection process more intuitive

Amcharts

https://github.com/user-attachments/assets/f793b538-75e7-4b7b-bdbb-a3c0bc9fd6c0

Other Chart

https://github.com/user-attachments/assets/c7b0d981-22b4-43f8-bbed-8a6b5ddd894c

**Comment by zeroin** [comment]
You can disable fill interactivity by adding adapter to a custom theme:

```
myTheme.rule("Graphics", ["series", "fill"]).adapters.add("forceInactive", ()=>{
  return true
})
```

However this will result that you will be able to only drag most of the drawings by the bullets (because rectangles and many others, except lines) do not have a shape which is draggable. I am afraid we are not changing this.

**Comment by shishima123** [comment]
yes, i see
I hope that one day you will think about this issue and improve it. A small change will make your chart library much better
Thank you
