### ISSUE TITLE
Small white line between fills

### ISSUE THREAD

**Issue by sisao** [amcharts/amcharts5#171]
It seems that there is a sometimes a very small white line between fills or gradient sections on a line series in a XY chart:
![Screenshot 2021-12-23 174348](https://user-images.githubusercontent.com/514609/147272013-07a98a40-16e8-4a8f-acbf-785bb687c8da.png)

Can this line get disabled or hidden?

**Comment by xorspark** [comment]
The white lines look like axis grid lines. Are you setting the grid's stroke to white or are you setting their `visible` property to false? Setting the `visible` property should not result in those lines, for example:

```
var xRenderer = xAxis.get('renderer');
xRenderer.grid.template.setAll({
  visible: false
});
```

If you are setting `visible` to false, can you provide a codepen of your setup?

**Comment by sisao** [comment]
Hi, here is a link to a code pen example:
https://codepen.io/sisao/pen/bGoYVEV

**Comment by martynasma** [comment]
Here's the deal. When you use `templateField` on a `LineSeries`, every time it encounters a value for it in data, it creates a separate masked copy of a line series.

Needless to say, this is not good for performance. So you should really make an effort to use it only where necessary, i.e. where color change actually occurs.

The vertical lines are additional side-effect of series consisting of multiple segments stitched together. Those are not very prominent where color change occurs, but visible where there are segments of the same color. This is another reason to avoid that.

If you absolutely need to have those, you may try a workaround: applying a stroke for fills:

```JavaScript
series.fills.template.setAll({
  fillOpacity: 1,
  visible: true,
  strokeWidth: 1,
  strokeOpacity: 1,
  templateField: "foo"
});
```

Data:
```JavaScript
var data = [
  {
    date: new Date(2012, 1, 1).getTime(),
    value: 8,
    foo: { fill: am5.color(0xff0000) }
  },
  {
    date: new Date(2012, 1, 2).getTime(),
    value: 10,
    foo: { fill: am5.color(0xff0000) }
  },
  {
    date: new Date(2012, 1, 3).getTime(),
    value: 12,
    foo: { fill: am5.color(0xff0000) }
  },
  {
    date: new Date(2012, 1, 4).getTime(),
    value: 14,
    foo: { fill: am5.color(0xff0000) }
  },
  {
    date: new Date(2012, 1, 5).getTime(),
    value: 11,
    foo: { fill: am5.color(0xff0000) }
  },
  {
    date: new Date(2012, 1, 6).getTime(),
    value: 6,
    foo: { fill: am5.color(0xff0000) }
  },
  {
    date: new Date(2012, 1, 7).getTime(),
    value: 7,
    foo: { fill: am5.color(0xff0000) }
  }
];
```

**Comment by sisao** [comment]
Thx, adding stroke to templateField solved the problem.
