### ISSUE TITLE
addLicense() does not hide amcharts logo

### ISSUE THREAD

**Issue by bdsettrade** [amcharts/amcharts5#1710]
refer to https://github.com/amcharts/amcharts5/issues/74, I do add license already

```
am5.addLicense("xxxxxxxx");
```

but I got this amcharts logo on StockChart

<img width="410" alt="image" src="https://github.com/user-attachments/assets/baa9208f-9514-400f-8c8c-b9ea03a51552">

how do I know that license work correctly ?
or this amcharts logo unremovable ?

**Comment by martynasma** [comment]
Please contact us directly at contact@amcharts.com for license-related issues.
