### ISSUE TITLE
Responsive issue of the multiple charts

### ISSUE THREAD

**Issue by prackode** [amcharts/amcharts5#1711]
I am having some issue while chart resize like  :

 - I am unable to do push the panels in the 2x2 manner. Currently its in 3x1. I can do it via creating multiple roots, but then in small screen  size the charts doesn't resize.
 
codepen to test : https://codepen.io/Prakhar-Agarwal-the-styleful/pen/bGPOWwM

**Comment by prackode** [comment]
In continuation with #1690

**Comment by prackode** [comment]
Ok then, if I have multiple amchart instances being displayed in a grid and I need to sync their cursors. Please suggest an effective way.

**Comment by martynasma** [comment]
The only way would be to track cursor position on one chart and manually place on the same timestamp on the other charts.

This doc has more info and exmaples:
https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/#tracking-setting-position
