### ISSUE TITLE
Change the legend value and tooltip labelText dynamically 

### ISSUE THREAD

**Issue by prackode** [amcharts/amcharts5#1716]
I want to dynamically change the values of the legend values as well as tooltip lables. 
I am using stockcharts.

my valueseries and valuelgend config :
```
    var valueSeries = mainPanel.series.push(
      am5xy.CandlestickSeries.new(root, {
        name: tproduct,
        clustered: false,
        valueXField: "Date",
        valueYField: "Close",
        highValueYField: "High",
        lowValueYField: "Low",
        openValueYField: "Open",
        calculateAggregates: true,
        forceInactive: true,
        xAxis: dateAxis,
        yAxis: valueAxis,
        legendValueText:
          "O: [bold]{openValueY}[/] H: [bold]{highValueY}[/] L: [bold]{lowValueY}[/] C: [bold]{valueY}[/]",
        legendRangeValueText: "",
      })
    );
    var valueLegend = mainPanel.plotContainer.children.push(
      am5stock.StockLegend.new(root, {
        y: am5.percent(0),
        centerX: am5.percent(0),
        stockChart: stockChart,
        layout: am5.GridLayout.new(instance, {
          maxColumns: 1,
          fixedWidthGrid: false,
        }),
        opacity: 0.7,
      })
    );
// get the values 
// for example this: 
let currentValues = {Open : 100, High:150, Low: 190 CLose: 200, 
let convertedValue = this.changeValues(currentValues ) // this function will do the mathematical calculations kind of helper function

// now set the converted values to the legend.

```
And when I say conversion i want to do some mathematical calculations before showing the values in the 
- legend text 
- tooltip label text.

And whenever user hovers it will show the converted values

**Comment by martynasma** [comment]
You will need to create [adapters](https://www.amcharts.com/docs/v5/concepts/settings/adapters/) for those settings.

```JavaScript
valueSeries .adapters.add("legendValueText", function(text, target) {
  // Use target.dataItem to access original data item and construct your dynamic value
  return "dynamic " + text;
});
```

**Comment by prackode** [comment]
Yes @martynasma , I tried using the adapters but `target.dataItem` is giving me undefined when I hover on any candle.
You can see in the below image : 
![image (5)](https://github.com/user-attachments/assets/4cebd43f-43c9-4aba-af92-331467d56158)

the flow is  : 
- I get the ohlc values which ever candle I am hovering
- Then I'll compute it.
- Last set it to legend value text and labeltext

**Comment by prackode** [comment]
I was able to do for the valueSeries legend @martynasma 
In case of the tooltip text converstion, I am getting `maximum call exceed error`
I am using the below  code to get the data item and do the computation

```
let tooltip;
    if (type === "valueTooltip") {
      tooltip = am5.Tooltip.new( this.chartInstance.instance, {
        getFillFromSprite: false,
        getStrokeFromSprite: true,
        autoTextColor: false,
        pointerOrientation: "left",
        animationDuration: 0,
        labelText:
          " O: [bold]{openValueY}[/]\n H: [bold]{highValueY}[/]\n L: [bold]{lowValueY}[/]\n C: [bold]{valueY}[/]",
      });
      tooltip.adapters.add("labelText", (text, target) => {
        const tooltipDataItem = target.get("tooltipDataItem"); // this is getting undefined
       let tooltipData = target.get("labelText"); // If I add this line I get the error
      
          // Return the updated text with the formatted values
          return `O: [bold]${formattedValues.Open}[/]\n H: [bold]${formattedValues.High}[/]\n L: [bold]${formattedValues.Low}[/]\n C: [bold]${formattedValues.Close}[/]`;
        }
 
        // If tooltipDataItem is undefined, return the default text
        return text;
      });
```

**Comment by martynasma** [comment]
Well, you are requesting `labelText` inside an adapter for `labelText` which creates dead loop.

Don't do that 😉

Instead, rely on the `text` parameter that was passed into adapter.

**Comment by prackode** [comment]
Got it @martynasma 
I want to get the tooltip OHLC values which I am not getting :
```
tooltip.adapters.add("labelText", (text, target) => {
    console.log(text)
})
```

And similary I tried for the tooltip of the valueAxis which comes with the cursor, I want to get that value too  and modify it
I tried this :
```
valueSeries .adapters.add("tooltip", function(text, target) {
  console.log(target.get("tooltipDataItem"));
  return "dynamic " + text;
});
```

**Comment by martynasma** [comment]
E.g.:

```JavaScript
valueSeries.adapters.add("legendValueText", function(text, target) {
  var dataItem = target.get("tooltipDataItem")
  if (dataItem) {
    return dataItem.get("highValueY");
  }
  return text;
});
```

For axis tooltip, you will need to target the series:

```JavaScript
dateAxis.get("tooltip").adapters.add("labelText", function(text, target) {
  var dataItem = valueSeries.get("tooltipDataItem")
  if (dataItem) {
    return dataItem.get("highValueY");
  }
  return text;
});
```

Example:
https://codepen.io/team/amcharts/pen/qBzgzWa/a4d0a579534c75cf2bc6538fef644dce?editors=0010

**Comment by prackode** [comment]
Thanks @martynasma for giving the codepen.
You can see in the image the tooltip of the valueAxis is showing the value as 586.73
whereas in the console it is showing the 593.25, 
![image (6)](https://github.com/user-attachments/assets/fd0838f2-3d78-40e7-baa7-2159784505f3)

 I basically want to get and update values of these  2 places only :
 - Tooltip box  ( I want to get the ohlc values and update) 
![image](https://github.com/user-attachments/assets/474463aa-5d54-4691-9222-089a8d665dfe)

 - valueSeries Tooltip 
![image](https://github.com/user-attachments/assets/ed8f4b1e-cbf9-4fe1-a77f-6153c8d6f38d)


So for valueSeries tooltip I tried this :
```
valueAxis.get("tooltip").adapters.add("labelText", function(text, target) {
  var dataItem = valueSeries.get("tooltipDataItem")
console.log(dataItem?.get("highValueY"))
  return text;
});
```

And for the Tooltip box I tried this : 
```

 tooltip.adapters.add("labelText", (text, target) => {
    console.log(text)
})
```

Both of them didn't gave me the values of the current state.

**Comment by martynasma** [comment]
```JavaScript
valueAxis.get("tooltip").label.adapters.add("labelText", function(text, target) {
  var dataItem = target.dataItem;
  console.log(dataItem?.get("highValueY"))
  return text;
});
```

```JavaScript
valueAxis.get("tooltip").adapters.add("labelText", function(text, target) {
  var dataItem = valueSeries.get("tooltipDataItem")
  if (dataItem) {
    return dataItem.get("highValueY");
  }
  return text;
});
```

**Comment by prackode** [comment]
Lastly, @martynasma I want to get the data like this tooltip
- Tooltip box  ( I want to get the ohlc values and update) 
![image](https://github.com/user-attachments/assets/474463aa-5d54-4691-9222-089a8d665dfe)

**Comment by prackode** [comment]
@martynasma  I want to get the cursor tooltip which being hovered over the valueAxis.
 specified that we can get the value of the tooltip like this :
```
 valueAxis.get("tooltip").label.adapters.add("labelText", function(text, target) {
  var dataItem = target.dataItem;
  console.log(dataItem?.get("highValueY"))
  return text;
});
```

But you can see in the video that I am getting the high value of the candle, I want that cursor tooltip value which is changing when we are moving the cursor. Only the valueAxis tooltip (box)


https://github.com/user-attachments/assets/c9c1813c-787d-4477-94bb-6699374be792

**Comment by martynasma** [comment]
You want to display "high value" of a hovered candle in a value axis tooltip?

**Comment by prackode** [comment]
No @martynasma 
Whatever the value is shown on the cursor tooltip which is on valueAxis, when I hover all over the chart weather I am hovering over the candle or not. 
As you can see in the video that, when I move my cursor upwards the cursor tooltip is showing the values

**Comment by martynasma** [comment]
I'm sorry I'm still not getting what you need.

Value axis tooltips displays whatever value corresponds to the position of the cursor.

You need it to snap to candle? Something else?

**Comment by prackode** [comment]
@martynasma 
I want to get this value : 
![image](https://github.com/user-attachments/assets/c13a3951-8623-4a96-88e7-b98a6cfb1344)

How can I get the what value is showing on this tooltip? What's the property/field is shown.

So for example in the image it is showing 376.90 , I want to get that.

**Comment by prackode** [comment]
Or in this video the cursor tooltip is showing the price, I only want to get that price .

https://github.com/user-attachments/assets/9612ad0f-68e9-47d2-a0f3-1e4e0eda3bc1

**Comment by martynasma** [comment]
```JavaScript
var y = ev.target.getPrivate("positionY");
var valueY = yAxis.positionToValue(y);
```

**Comment by prackode** [comment]
Tried this @martynasma but it is not giving the exact  value which is being shown on the cursor tooltip.
![image (8)](https://github.com/user-attachments/assets/fcdcb845-e837-42cf-ab1a-3b66fe8409dd)

As you can see in the below image, the cursor tooltip on valueAxis is showing the value as 393.59
but on console it is not printing.

**Comment by martynasma** [comment]
You probably have snapping of cursor to candles enabled.

In such case the value will be shown as physical location of cursor.

```JavaScript
cursor.events.on("cursormoved", function(ev) {
  var y = ev.target.getPrivate("positionY");
  var valueY = valueAxis.positionToValue(y);
  console.log(valueY)
})
```

If you want a value cursor is snapped to, then you will need to use `tooltipDataItem`.

```JavaScript
cursor.events.on("cursormoved", function(ev) {
  var dataItem = valueSeries.get("tooltipDataItem")
  valueY = dataItem ? dataItem.get("valueY") : 0;
  console.log(valueY)
})
```

**Comment by prackode** [comment]
It still didn't worked @martynasma  I am providing you the codepen for the better testing and understanding

https://codepen.io/Prakhar-Agarwal-the-styleful/pen/gONVRpb?editors=1011

**Comment by martynasma** [comment]
```JavaScript
valueAxis.get("tooltip").label.adapters.add("text", function(text, target) {
  var dataItem = valueSeries.get("tooltipDataItem")
  var valueY = dataItem ? dataItem.get("valueY") : 0;
  return valueY * 2 + "";
})
```

**Comment by prackode** [comment]
@martynasma , have you tried on that codepen ?
The above code will only display the high value of the hovered candle only.

I want to get the cursor tooltip showing price that's it, irrespective of which candle is being hovered. 
In the below image  the cursor in not hover on any candle then too it showing the value 
![image](https://github.com/user-attachments/assets/c13a3951-8623-4a96-88e7-b98a6cfb1344)

**Comment by prackode** [comment]
This worked for me by the way  @martynasma 

```

cursor.events.on("cursormoved", function(ev) {
  var y = ev.target.getPrivate("positionY");
  var valueY = valueAxis.positionToValue(y);
  var yMax = valueAxis.positionToValue(1);
  var yMin = valueAxis.positionToValue(0);
  console.log(yMax + yMin - valueY)
})

```

**Comment by prackode** [comment]
But there issue that when we put this code on the Live updating chart, I  am continously getting the values even though I am not moving the cursor 
@martynasma

**Comment by martynasma** [comment]
`cursormoved` will not kick in if cursor is not over the chart. If it's over the chart, it will kick in whenever something updates.

**Comment by prackode** [comment]
What do now ? 
The cursor is on the chart, but I am not moving it & it is getting live update.

As the name suggest cursormoved , so it should work when the cursor moved.
Isn't it? @martynasma

**Comment by martynasma** [comment]
It's not a huge problem. You can just verify if the `positionY` is the same as previous and ignore event invocation.
