### ISSUE TITLE
How to change color for only 1 specific candle area in stock chart?

### ISSUE THREAD

**Issue by shishima123** [amcharts/amcharts5#1717]
Is there a way to set the candlesticks within a square area to a different color (for example: yellow or black), while keeping the candlesticks outside the square area in their default color?

![image](https://github.com/user-attachments/assets/eae81c0e-5df5-4bc9-a4fe-9d5e6b1d4cf7)

**Comment by martynasma** [comment]
I'm afraid we don't have such built-in functionality or a custom demo 🙁

**Comment by shishima123** [comment]
Okay, i see
Do you plan on adding this in the future?

**Comment by martynasma** [comment]
At this moment there are no such plans.

**Comment by shishima123** [comment]
thank you
hope you think about adding it in the future 😇
