### ISSUE TITLE
How to serve this repo locally

### ISSUE THREAD

**Issue by HawtinZeng** [amcharts/amcharts5#1718]
Hi, amcharts teams, thanks for your great work, I want to dive deep into the source code, but I found I can't start a local server to run these exmaples and docs. 
How do you start a dev workspace?

**Comment by Pauan** [comment]
There are a lot of web servers available, probably the easiest is Python's built-in server:

https://realpython.com/python-http-server/

```sh
python3 -m http.server
```

Now just open up `http://localhost:8000/` in your browser.

**Comment by HawtinZeng** [comment]
OK, webpack offer a dev server, I like this kind of dev server

**Comment by Pauan** [comment]
Sure, we use Webpack dev server a lot, it also works fine.
