### ISSUE TITLE
How to prevent several decimal points in total bullet value?

### ISSUE THREAD

**Issue by dmytro-kuz** [amcharts/amcharts5#1721]
**Question**
Is there a way to turn off the animation for the bullet label or a way to remove the extra decimal in the total bullet value during chart animation? Or may this value follow the format of the values ​​on the axis?

**Environment (if applicable)**

**Additional context**
Codepen: https://codepen.io/team/amcharts/pen/dyJdQjW?editors=1010
Screenshot:
![Знімок екрана 2024-09-12 093428](https://github.com/user-attachments/assets/cba04988-f056-4db0-b490-ff277bb3e617)

**Comment by martynasma** [comment]
I suppose you can set a global number format:

```JavaScript
root.numberFormatter.set("numberFormat", "#.#");
```

**Comment by martynasma** [comment]
Maybe you can just hide the "totals" series, and show it with a delay?

https://codepen.io/team/amcharts/pen/ExBJKRM/fe422d7a79583783d62ad20d466b6bf0

**Comment by dmytro-kuz** [comment]
This is probably the best solution. I think I can optimize it for my code and use it. Thank you for your help.
