### ISSUE TITLE
Initiate fills in stock chart

### ISSUE THREAD

**Issue by prackode** [amcharts/amcharts5#1723]
There is a option of fills in the setting button in stockchart for activation of fills.
But i want to initiate the fills option initally only, when the chart launches.

I got know there is a function name _setFills which is protected method, and it does the job.

Please let me know how can initiate the fills on the starting without giving the access to the user.

I tried this but it didn't worked
`SettingControl._setFills(true)`

**Comment by martynasma** [comment]
Please refer to this doc:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#enabling-fills
