### ISSUE TITLE
Issue with amCharts5 Exporting Library: 'uncaught (in promise) TypeError' When Generating PDFs

### ISSUE THREAD

**Issue by abhay-jain03** [amcharts/amcharts5#1724]
I am using amcharts5 exporting library (https://cdn.amcharts.com/lib/5/plugins/exporting.js), but while generating pdf, I am getting below issue:- 

**Using exporting.js is causing below mentioned error in console and charts are not also exporting.** Instead of chart, we are getting the attached exporting menu option in the place of each chart. 

Any possible root cause and solution for it ? @martynasma 

"uncaught (in promise) TypeError: 'caller', callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them"

![366567242-5c0770af-e2f8-4b30-89f8-0a505b53397d](https://github.com/user-attachments/assets/57bc66ce-e5b0-4438-b4c0-3403d46231a3)

**Comment by martynasma** [comment]
Are you getting the error on this demo?
https://www.amcharts.com/demos/exporting-chart-to-image/

If not, can you provide your chart setup which leads to error when exporting to PDF?
