### ISSUE TITLE
Gridlines highlight

### ISSUE THREAD

**Issue by prackode** [amcharts/amcharts5#1725]
The valueAxis gridlines are highlighted and I can't find any specific pattern as such but mostly the `value = 0` line is being highlighted. How can I make sure that all gridlines are displayed with uniform color?

![image](https://github.com/user-attachments/assets/0a29200c-7358-41a9-8015-cd6e2e63baff)

**Comment by martynasma** [comment]
Please refer to this documentation on how to configure the "base grid":
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#base-grid
