### ISSUE TITLE
V5 JSON config: display legend label and value with display-flex space-between style

### ISSUE THREAD

**Issue by flaming-cl** [amcharts/amcharts5#1727]
**Question**

Hey, to display the legend value and label following **display flex, space-between** CSS style, do you think there is a simple way to do it? (So far the solution seems to be setting valueLabel => x: 80% and text align: right.  

Also, do you think whether there is something like border-bottom (or stroke bottom) of the legend, like the picture below specified?

![image](https://github.com/user-attachments/assets/083dd4a0-2176-4de8-b2fe-25f793374569)

**Comment by martynasma** [comment]
I'm not entirely sure how to do that with JSON config. Sorry.

**Comment by flaming-cl** [comment]
> I'm not entirely sure how to do that with JSON config. Sorry.

No worries. Do you think it's possible to do it with TypeScript?

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.
