### ISSUE TITLE
unable to add label in percent mode

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1730]
In stock chart, while applying to comparison series I want to have the label of both [ base product + comparison product] . But it not coming/working specifically when its in percentage mode. Rest in other scenarios ( like new price scale or panel) it works.

Codepen : https://codepen.io/Ansh-m-the-reactor/pen/Rwzzawq?editors=0011

**Comment by martynasma** [comment]
I'm afraid I'm not sure what "label" you are referring to. Can you explain?

**Comment by workingbuddy10** [comment]
The last candle close price label @martynasma

**Comment by martynasma** [comment]
Yes, it's possible. Feel free to modify your code to add such label for each required series accordingly.
