### ISSUE TITLE
Toggle ColumnSeries stacked property

### ISSUE THREAD

**Issue by sourcecodeit** [amcharts/amcharts5#1731]
I don't know if it's a bug but it's actually not possible to set the property `stacked` at runtime. You have to clear the series and then create from scratch

Codepen: https://codepen.io/sourcecodeit/pen/xxooBPN

**Comment by martynasma** [comment]
`stacked` is not just a setting, it affects data parsing as well as other series on the chart. I'm afraid your "rebuild" approach is the way to go about it.
