### ISSUE TITLE
Value axis tooltip values

### ISSUE THREAD

**Issue by prackode** [amcharts/amcharts5#1732]
I want to get the cursor tooltip which being hovered over the valueAxis.
In this issue https://github.com/amcharts/amcharts5/issues/1716#issuecomment-2340361424
@martynasma  specified that we can get the value of the tooltip like this :
```
 valueAxis.get("tooltip").label.adapters.add("labelText", function(text, target) {
  var dataItem = target.dataItem;
  console.log(dataItem?.get("highValueY"))
  return text;
});
```

But you can see in the video that I am getting the high value of the candle, I want that cursor tooltip value which is changing when we are moving the cursor. Only the valueAxis tooltip (box)

https://github.com/user-attachments/assets/c9c1813c-787d-4477-94bb-6699374be792

**Comment by martynasma** [comment]
Let's continue in the original thread https://github.com/amcharts/amcharts5/issues/1716. No need to open a new one for the same stuff.
