### ISSUE TITLE
Enhancement : Moving average cross indicator 

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1733]
There is no option of choosing Type and Field in MA cross indictor.

Whereas in Moving Average indicator one can choose the Type and field. 

In MA cross the library is directly using simple ma  https://github.com/amcharts/amcharts5/blob/1700061a162a22e57cb0c201271add7304243278/src/.internal/charts/stock/indicators/MACross.ts#L133

It would be great if user can get the feasibility to choose/change. 

![image](https://github.com/user-attachments/assets/f7218626-51c6-425b-a150-8ce8d08b6815)
![image](https://github.com/user-attachments/assets/b0d2bde1-2366-4ec0-a91b-6030e98b29e4)

**Comment by martynasma** [comment]
We have looked into this and came to conclusion that we won't be able to implement this, I'm afraid.

Thanks for the suggestion.

**Comment by martynasma** [comment]
I'm afraid I can't provide the reasoning behind it. At the moment of making of this indicator it was decided not to have those properties, but I can't work out the reason. Sorry.

**Comment by workingbuddy10** [comment]
No issues, Thanks for the help!
