### ISSUE TITLE
Bug : Indicator class method render multiple time

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#1736]
I have created multiple custom indicators, but one thing was common in that : `prepareData` gets call 4 times. 
Even though : 
- Neither the chart was updating live
- Nor I was scrolling/panning etc.

I just clicked on the custom indicator and prepareData method was called 4 times.

Ideally which is not the good practice. 
And in my case I don't use the data for custom indicators from the stockSeries /valueSeries as those indicators don't use the OHLCV data. I fetch it from an api. So if the prepareData method is running **4 times Initially then it is making 4 API calls.** 

![image](https://github.com/user-attachments/assets/5a52ca02-8434-4009-a0a4-66814a812c6b)

**Comment by workingbuddy10** [comment]
@martynasma  It is not a custom code.

you can go on this amcharts doc https://www.amcharts.com/docs/v5/tutorials/creating-custom-indicators-for-a-stock-chart/
And just add a` console.log("coming here")` in prepareData method and then add that custom indicator on chart.

You will see the `coming here` is getting printed 4 times.

Is that a good thing? 


As prepareData is a core method for the logical operations of the indicators, and it is getting rendered multiple time.

**Comment by martynasma** [comment]
Well, it is what it is. I'm afraid we won't be able to underlying structure.

If multiple invocation creates an issue for you, you may implement some kind of flag property in your class to log whether init stuff has already been done and simply ignore subsequent calls.

**Comment by workingbuddy10** [comment]
That's what I have done for now! I was looking for something standard, above than a hack/fuzzy logic.
