### ISSUE TITLE
series.data.pushAll(data) - only adds to the last series created

### ISSUE THREAD

**Issue by morrow95** [amcharts/amcharts5#174]
I have an XYChart that contains 4 LineSeries.  I initially create each series with a function and pass series specific values to it.

```
//create series in a function
function createSeries(name, field, color) {

	series = chart.series.push(am5xy.LineSeries.new(chartReg['chart'], {
	//series = chart.series.push(am5xy.SmoothedXLineSeries.new(chartReg['chart'], {
		name: name,
		stroke: color,
		xAxis: xAxis,
		yAxis: yAxis,
		valueYField: field,
		valueXField: "Timestamp",
	}));

	//series stroke
	series.strokes.template.setAll({
		strokeWidth: 1.5,
	});

	//bullets with hover event
	series.bullets.push(function () {
		var circle = am5.Circle.new(chartReg['chart'], {
			radius: 5,
			fill: color,
			stroke: am5.color("#ffffff"),
			strokeWidth: 2,
			interactive: true
		});
	  
		circle.states.create("hover", {
			scale: 1.25
		});
	  
		return am5.Bullet.new(chartReg['chart'], {
			sprite: circle
		});
	});

	//formatting
	series.data.processor = am5.DataProcessor.new(chartReg['chart'], {
		numericFields: [field],
		dateFields: ["Timestamp"],
		dateFormat: "xxxxxxxxxx"
	});

	series.data.setAll(data);
	series.appear();
}
```

This works fine, but later on I want to add data.

```
series.data.pushAll(data);
```

It works, but it only adds data to the last series I created with my function rather than all 4 of them.  I'm assuming this is because `series` gets overwritten each time I create one.  So, is there some other way to add data to my chart for multiple series and still use a function to create each series?  I'd prefer not to write the code out to create each series individually.  Perhaps some sort of 'series iterator' I can use to add data to each one?

**Comment by zeroin** [comment]
Sure: 

`chart.series.each(function(series){
  series.data.setAll(data);
})`

**Comment by morrow95** [comment]
@zeroin - Thank you!
