### ISSUE TITLE
Using amcharts as dependency

### ISSUE THREAD

**Issue by vskorop** [amcharts/amcharts5#1742]
**Aloha!**

I have developed a package that includes a chart component, which can be seen in this [example](https://stackblitz.com/edit/vitejs-vite-mihw2b?file=vite.config.ts).

When I run the project locally, everything works perfectly, just like in the example. However, when I build the project and use the component as a dependency (with the same data), I encounter the following error:

```Cannot read properties of undefined (reading 'get')```

This error points to the following amCharts code line:

```bash
_handleRangeChange() {
  je(this.series, (e) => {
    let n10 = this.dataItems[this.startIndex()].get("category"),
    i = this.dataItems[this.endIndex() - 1].get("category"),
    a10 = e.get("baseAxis"),
    u = e.get("xAxis"),
    f = e.get("yAxis");
    if (u instanceof _vc && f instanceof _vc) { ... }
  });
}
```

It seems like amCharts doesn't recognize the data during the UPDATE_CHART_DATA case.

Temporary Workaround
I found a workaround by modifying the **_vite.config.ts_** file and removing amCharts from the external dependencies, as shown below:

```bash
external: [
  'react',
  'react/jsx-runtime',
  '@amcharts/amcharts5',  # <--- Deleted amCharts from externals
]
```

This approach causes the bundle size to increase significantly (several times larger than before).

Request for Help
Is there a better way to resolve this issue without massively increasing the bundle size? How can I properly use amCharts as a dependency inside my package while avoiding this error?

Any insights or recommendations would be greatly appreciated!

**Comment by Pauan** [comment]
Why are you marking the packages as `external`?

It's normal to bundle npm dependencies with your app, `external` is for advanced use-cases.

**Comment by vskorop** [comment]
As I've written above - I use my own package with amcharts inside (as peer dep). For decrease bundle size, I made amcharts as ```external```. And I encounter with error in this setup.

**Comment by Pauan** [comment]
amCharts should work with `peerDependencies`, so we'll need more details on your setup.

P.S. Even if you use `peerDependencies`, the final application will still be bundling amCharts, so it doesn't really decrease bundle size.
