### ISSUE TITLE
Horizontally Synced Cursors for Multiple Y-Axis Tooltips

### ISSUE THREAD

**Issue by jeinhorn787** [amcharts/amcharts5#1743]
**Question**

I need to sync cursors across multiple charts laid out _horizontally_ to render a tooltip on each chart on the Y-axis.  When the user hovers their mouse on 1 chart, a tooltip shows as well as tooltips on the other charts in the same position on their respective charts.  

I understand that using `syncWith` only tracks the XY position of the cursor on screen and NOT by axis position as outlined [in the docs](https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/#syncing-cursors) and therefore, the cursors will not sync when tracking a cursor on the Y axis with horizontally laid out charts.

Is there any other way you can suggest to achieve this?  Below is a codepen that is actually a copy of the [codepen](https://codepen.io/team/amcharts/pen/zYPwdGj) in your docs but I altered it to render the charts horizontally to show a very similar setup I will have in my project.

https://codepen.io/jeinhorn787/pen/RwXPRMe

**Visual description of what I need**
![Screen Shot 2024-09-26 at 4 56 35 PM](https://github.com/user-attachments/assets/f6eaec6e-2b22-43c1-b924-6601de8e6c17)

**Environment (if applicable)**

Version: `@amCharts5: "^5.8.7"`
Browser: Chrome (129.0.6668.60)
Framework: React

**Comment by martynasma** [comment]
The solution would involve:

1) Adding `cursormoved` event to all cursors.
2) Simulating move of teh cursor to the same local x/y position.

Here's a modified pen:
https://codepen.io/team/amcharts/pen/XWvbMOx?editors=0010

**Comment by jeinhorn787** [comment]
> Here's a modified pen: https://codepen.io/team/amcharts/pen/XWvbMOx?editors=0010

This is on the right track but it's a bit unstable. In the screen recording here, I am moving the cursor back and forth very slightly on the bullet point, you can see the other tooltips flickering.

https://github.com/user-attachments/assets/4b544bb2-17d0-4a4e-8106-17d7f827ede8

**Comment by jeinhorn787** [comment]
> Here's a modified pen: https://codepen.io/team/amcharts/pen/XWvbMOx?editors=0010
This is on the right track but it is unstable. In the screen recording below, I am moving the cursor very slightly across the bullet point and the other tooltips flicker erratically.

https://github.com/user-attachments/assets/e45a82c2-e6e0-4c6b-8e3e-27a12c0f0632

**Comment by martynasma** [comment]
Indeed. CodePen updated.

**Comment by jeinhorn787** [comment]
> Indeed. CodePen updated.

Sweeeeeet, thanks so much!!
