### ISSUE TITLE
Text of bullets in a line chart

### ISSUE THREAD

**Issue by roman-gorkunenko** [amcharts/amcharts5#1744]
Hello.
Is there a functional to identify overlapping labels for bullets on a line chart and either adjust their spacing or hide them altogether?
Maybe there is some kind of automatic alignment or perhaps a setting like minBulletDistance to hide them?

<img width="671" alt="Monosnap JSFiddle - Code Playground 2024-09-28 16-57-23" src="https://github.com/user-attachments/assets/abe6285d-10fe-4f10-8d3c-9b8d5e6ab820">

Code example: https://jsfiddle.net/roman_gorkunenko/2gs9nk8z/4/

Thanks.

**Comment by martynasma** [comment]
I'm afraid there's no built-in functionality to avoid bullet overlapping 🙁
