### ISSUE TITLE
Tooltips are not visible 

### ISSUE THREAD

**Issue by Daredevil749** [amcharts/amcharts5#1745]
I am having one issue with the column series.So for some of the columns its corresponding tooltip is not visible as it get cropped of from the top.please refer the attached image for more info.
![tmp_bdbd156d-d518-4087-abd3-0ef1a9c692a6](https://github.com/user-attachments/assets/169fa4d6-e657-4b94-8720-4da3fd891fbe)

**Comment by martynasma** [comment]
You may consider a few options, like allowing tooltips outside chart area:
https://www.amcharts.com/docs/v5/concepts/common-elements/tooltips/#Tooltips_outside_chart_area

Or disabling tooltip arrangement (and risk them overlapping):
https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/#auto-arranging-tooltips

But, honestly, displaying a bunch of tooltips like this looks messy and probably not super useful to the user.

If you need to display some kind of information related to each column all at the same time, I suggest making this chart horizontal, and adding bullet labels to each column. E.g.: https://www.amcharts.com/demos/clustered-bar-chart/
