### ISSUE TITLE
How does custom themeTag work

### ISSUE THREAD

**Issue by aryan-dixit-26** [amcharts/amcharts5#1746]
I am trying to customize theme for all my charts. I have multiple types of charts with different colors, opacity, typography. I want to generalize them for all charts. 
One solution i tried implementing was creating custom themes with custom theme tag.
**example**: 
![image](https://github.com/user-attachments/assets/543ec549-d82a-4a85-a39a-104c8f05ef84)

But this does not seem to work. Is there something that I am missing?. I tried to add the **themeTags** attribute at the chart level also but it did not work.
Also is there a way to generalize theming for multiple charts. I understand theming for colors can be done with **InterfaceColors**, but I could not find anything generalized for properties like fillOpacity, storkeOpacity, fontSize ... etc.

**Comment by martynasma** [comment]
`ColorSet` is not an element and thus will not inherit theme tags from other objects. Furthermore, `ColumnSeries` does not have own color sets. `XYChart` does.

So you might want to do something like this:

```JavaScript
am5xy.XYChart.new(root, {
  // ...
  colors. am5.ColorSet.new(root, {
    themeTags: ["vertical-bar-chart"]
  });
});
```

**Comment by aryan-dixit-26** [comment]
Thanks!!, it solves my issue.
