### ISSUE TITLE
Show Chart as SVG - Like amcharts4

### ISSUE THREAD

**Issue by prfardin** [amcharts/amcharts5#175]
there is any way to show chart as svg like amcharts4?
i think quality is better in version 4!
maybe it can be future request, Like apache charts, we can select render mode to svg or canvas, here is a example: https://echarts.apache.org/examples/en/editor.html?c=line-simple!
any ide or help!

**Comment by martynasma** [comment]
I'm terribly sorry, but at this time we do not plan on implementing SVG rendering for amCharts 5. Maintaining two rendering engines is a lot of overhead, with little benefits. Besides, Canvas is way faster.

I understand that this might not be suitable for everyone, but this is the situation. I hope it is OK with you.
