### ISSUE TITLE
GaplessDateAxis - Display grid start data; animation live stock doesn't works

### ISSUE THREAD

**Issue by paulodfavero** [amcharts/amcharts5#1750]
Hi there!
When I'm using `GaplessDateAxis` and set `maxDeviation`, the grid after live candle disappear.
And the transition, when create a new candle, is not working.

PS: `extraMax` doesn't works for me because I have to keep the same margin right  (zoom in or out).
![Screenshot 2024-10-05 at 09 58 16](https://github.com/user-attachments/assets/436670c7-cba0-4025-91d4-929df11dbe51)

https://codepen.io/Paulo-Favero/pen/GRVqqYE?editors=1010

![image](https://github.com/user-attachments/assets/54c052e6-d8d0-4f9e-8220-5dd365a91118)

https://github.com/user-attachments/assets/50513c4e-b712-4bce-adf7-f30ea179b73d

**Comment by zeroin** [comment]
I am afraid this is how gapless date axis works - grid is displayed only where we have data.

**Comment by paulodfavero** [comment]
> I am afraid this is how gapless date axis works - grid is displayed only where we have data.

Me too. But it doesn't make sense because future data will never exist.

**Comment by paulodfavero** [comment]
@martynasma could you help me?
Is this a bug or something in the configuration?

**Comment by zeroin** [comment]
No, it's by design. It's how gapess date axis works - we only display grid/labels on the dates which are available in the data.  Martynas will not provide a different answer.

**Comment by zeroin** [comment]
No, there is no way. And from my observations It works the same way for the past.
