### ISSUE TITLE
Handling responsive design: updating JSON config after initiation

### ISSUE THREAD

**Issue by flaming-cl** [amcharts/amcharts5#1751]
We are handling desktop and mobile design for pie charts with V5 JSON config. 

**If possible, would you please let us know how to update the settings (layout) and the position of the piechart/legend, after initiated the chart?**

**Comment by martynasma** [comment]
You may use a Responsive` theme:
https://www.amcharts.com/docs/v5/concepts/responsive/

**Comment by flaming-cl** [comment]
> https://www.amcharts.com/docs/v5/concepts/responsive/

Thanks @martynasma, 

We are using itemContainer to customize our own legend.
Do you know how I can get the itemContainer instance? (for setting up its x/y)
![Screenshot 2024-11-03 at 4 07 58 PM](https://github.com/user-attachments/assets/9c18fafa-8423-4be0-a11b-28a765d4d2e7)

**Comment by martynasma** [comment]
```JavaScript
responsive.addRule({
  name: "Container",
  tags: ["legend", "item", "itemcontainer"],
  relevant: am5themes_Responsive.widthM,
  settings: {
    // ...
  }
});
```
