### ISSUE TITLE
Last axis label is not aligned correctly with a Gapless Date axis and "week" timeunit

### ISSUE THREAD

**Issue by cheryllaird** [amcharts/amcharts5#1752]
**Bug description**
Setting the chart to display a "week" timeunit, the last axis label is not aligned correctly:
![image](https://github.com/user-attachments/assets/a85060a6-65dd-4324-8cae-a4e67726335a)

Other granularities seem ok so not sure how to fix this one.

**Codepen**: https://codepen.io/cheryllaird/pen/jOgMPMP

**Environment (if applicable)**
amCharts version 5

**Comment by martynasma** [comment]
Are you sure `GaplessDateAxis` is a good fit for this chart? Regular `DateAxis` works better in this case.

Let me know if you have a specific reason for using `GaplessDateAxis.`

**Comment by cheryllaird** [comment]
I would be more than happy to use `DateAxis`, however I would like to center the labels below the column. Using `DateAxis` displays the axis label for "week" at the start of the column even if I set `location: 0.5` and `multiLocation: 0.5` on the labels.

Codepen for DateAxis: https://codepen.io/cheryllaird/pen/WNVGZpN

Using `GaplessDateAxis` allow the labels to be cantered but with the bug of the label label of the axis as described above.

**Comment by martynasma** [comment]
Weekly base interval is a special case. From axis standpoint, it's still uses days as base cell width, so using `location: 3.5` should do the trick:

```JavaScript
dateAxis.get("renderer").labels.template.setAll({
  location: 3.5
});
```

**Comment by cheryllaird** [comment]
Great this works nicely! It also means I can use `DateAxis` which is preferred. 👍 

It might be worth keeping this issue open for the `GaplessDateAxis` though as this is still a bug if anyone needed the Gapless functionality.

**Comment by martynasma** [comment]
Indeed. Let us try and figure this out.

**Comment by zeroin** [comment]
You can solve this with adapter:

https://codepen.io/team/amcharts/pen/rNXMgae

```
renderer.labels.template.adapters.add("location", (location, target) => {
    if(dateAxis.getPrivate("gridInterval").timeUnit === "week"){
        return 3.5;
    }
    else{
        return location;
    }
});
```
