### ISSUE TITLE
customized legend texts with JSON config

### ISSUE THREAD

**Issue by flaming-cl** [amcharts/amcharts5#1756]
![Screenshot 2024-10-10 at 10 11 29 PM](https://github.com/user-attachments/assets/690b98dd-ab73-413e-b047-87acaa98e417)

Hey, is V5 JSON config possible to customize chart legend with a bold title and multiple lines of values like the  screenshot?

**Comment by martynasma** [comment]
Yes, you can use in-line formatting to style your labels, as well as `\n` character to add line-breaks.

Docs: https://www.amcharts.com/docs/v5/charts/percent-charts/legend-percent-series/#Legend_label_content
