### ISSUE TITLE
How to change the xAxisLabel on the fly?

### ISSUE THREAD

**Issue by lianghua1987** [amcharts/amcharts5#1758]
**Question**

Anyone knows how to change the xAxisLabel, yAxisLabel or legends on the fly once the chart has been rendered? The purpose is to show base on different language selected.

I am using angular18 with am5.10.1. Any suggestion is welcomed:)

**Comment by martynasma** [comment]
Could you please be more specific about your chart setup, and what exactly you want to change in it?
