### ISSUE TITLE
V5: overwrite legend click event

### ISSUE THREAD

**Issue by flaming-cl** [amcharts/amcharts5#1759]
Hey for V5, do you know how to replace each legend label's click event with our own user event?

**Comment by martynasma** [comment]
You can disable built-in toggle events by setting `clickTarget: "none"`:
https://www.amcharts.com/docs/v5/concepts/legend/#disabling-toggling

Then you can just add your own click events:

```JavaScript
leged.itemContainers.template.events.on("click", function(ev) {
  console.log(ev.target);
});
```

**Comment by flaming-cl** [comment]
Thanks! clickTarget: "none" also works if I set it with JSON config for legend.settings, right?

**Comment by martynasma** [comment]
> Thanks! clickTarget: "none" also works if I set it with JSON config for legend.settings, right?

Yes.

**Comment by flaming-cl** [comment]
@martynasma, doesn't seem to work while setting up legend.itemContainers.template.events
codePen: https://codepen.io/flaming-cl/pen/dyxXRQX?editors=1010

**Comment by martynasma** [comment]
This is because by the time you add the event, item containers are already created.

You may need to add to actual items:

```JavaScript
legend.itemContainers.each(function(container) {
  container.events.on("click", .....);
});
```

**Comment by flaming-cl** [comment]
Thanks @martynasma, the above solution works.

one small question on `clickTarget: "none"`:    
this also disables the hovering (curser: pointer) effect on legend. Do you know how to show the cursor while disable the original click event?
<img width="328" alt="Screenshot 2024-11-04 at 7 46 35 PM" src="https://github.com/user-attachments/assets/cba535de-e3c2-4649-968c-5d0b447cf5b3">

**Comment by martynasma** [comment]
```
itemContainers: {
  properties: {
    template: {
      settings: {
        x: { type: 'Percent', value: 0 },
        centerX: { type: 'Percent', value: 10 },
        width: { type: 'Percent', value: 98 },
        height: 50,
        cursorOverStyle: "pointer",
        interactive: true
      }
    }
  }
},
```
