### ISSUE TITLE
Chart Slow/Lagging When Handling Big Data

### ISSUE THREAD

**Issue by sknhkrn** [amcharts/amcharts5#176]
Hi, may I know is there any solution for the slow/lagging to display the chart when the data is big. 

For example, I have 10 series in one chart and each series consists of more than 100k point of data. To display the chart, the speed is good however when Im trying to zoom in/out or scroll the chart. It become slow and lag. 

![image](https://user-images.githubusercontent.com/57323027/147647820-00dd3619-71f5-42c6-8639-29d32a5ba495.png)

Is there any solution for it? Thanks in advance.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by sknhkrn** [comment]
Sure, here is jsFiddle for the example:

https://jsfiddle.net/zjwyvho8/4/

The lag/slow only happen when the data of 100k point (more/less) is displayed at once on the chart. If I zoom in, only a few hundreds is displayed at one time then the chart speed is normal.

**Comment by martynasma** [comment]
I would suggest using data grouping:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#Dynamic_data_item_grouping

Initial chart load will still take a few seconds (got to parse a million of data items), but from that point onwards the chart will be fast.

**Comment by sknhkrn** [comment]
Thanks, it works well by adding data grouping. 

However, is there another way than grouping? 
Since by doing grouping, some of the pattern in the chart is not shown if all data is being displayed at once.

**Comment by martynasma** [comment]
There's no other way.

However, I'm not sure how you can display 100K * 10 data points at once in any way that would be perceivable to the user.

I mean if the chart is, say 1000px wide, that would be 10 data points per pixel.

**Comment by sknhkrn** [comment]
Thats okay, data grouping is good enough. 

Thank you!
