### ISSUE TITLE
Exporting AmChart 5 chart png images

### ISSUE THREAD

**Issue by rulhadi** [amcharts/amcharts5#1760]
Hi all kind people, I am using Javascript and AmChart5, is it possible to export the chart to produce png image and store it on local environment folder?

eg)
![image](https://github.com/user-attachments/assets/eb03f253-21f0-4330-b5b1-2b1a3c69f051)

I want the user to press this button (made by me)
![image](https://github.com/user-attachments/assets/f9a55d0d-6e26-4d68-b642-0b7157d12f4f)

rather than make the user to press the button here
![image](https://github.com/user-attachments/assets/ab963385-6a5f-4174-9d87-27bc6e3925e3)

**Comment by martynasma** [comment]
Yes: https://www.amcharts.com/docs/v5/concepts/exporting/exporting-api/#getting-data-uri
