### ISSUE TITLE
Add border/stroke around the staked series 

### ISSUE THREAD

**Issue by YehosuaEs** [amcharts/amcharts5#1761]
Hello!
Im struggling to add borders (strokes) to my series, they are stacked so if I would like to add border aonly around/outside the stacked columns and not inside the stacked series column 

I know this will add the border/strokes around on each serie
```bash
series.columns.template.setAll({
  strokeWidth: 1,
  strokeOpacity: 1,
  stroke: am5.color('#000000')
});
```

but as they are stacked  series I only want: for exmaple if iIhave three series , then the border in the bottom should be in the bottom and right and left, then the serie in the middle should have the border only in the left and right  and the top only should have the border in the left right and top 
| What I want  | What I have but I don't want |
| -------- | ------- |
| ![image](https://github.com/user-attachments/assets/16496876-9328-4267-aa3c-27f54f124930) |    ![image](https://github.com/user-attachments/assets/373522b6-47fa-4916-96f8-68d185821f18)  |

Im using amCharts 5 and angular 18+

**Comment by martynasma** [comment]
The only workaround would be to add a separate un-stacked and un-clustered `ColumnSeries` with the outline and and transparent fill, as well as remove any borders for other series. The value for the "outline" series should be the sum of all series values so that it is as high as the stack.

I hope that makes sense.

**Comment by YehosuaEs** [comment]
Thanks I will check.!
Regards!

**Comment by YehosuaEs** [comment]
Thanks I will check.!
Regards!
