### ISSUE TITLE
number formatter prefix for legend

### ISSUE THREAD

**Issue by flaming-cl** [amcharts/amcharts5#1764]
hey, would you please let us know how to dynamically add number formatter prefix for the legend values? assume my values are 

USD $1,000, 
GBP £2,000,
EUR €3,000

```
data: [
            { currency: "$", country: 'U', sales: 1000 },
            { currency: "£", country: 'G', sales: 2000 }, 
            { country: '€', country: 'E', sales: 3000 }
          ]
```
<img width="1386" alt="Screenshot 2024-10-15 at 10 14 41 PM" src="https://github.com/user-attachments/assets/f4c6466f-0f25-49fe-ae22-f19ffc3c9af4">

**Comment by martynasma** [comment]
You can set what is displayed in legend using `legendLabelText` and `legendValueText`.

Docs: https://www.amcharts.com/docs/v5/charts/percent-charts/legend-percent-series/#Setting_content

E.g.:

```JavaScript
var series = chart.series.push(
  am5percent.PieSeries.new(root, {
    name: "Series",
    valueField: "sales",
    categoryField: "country",
    legendValueText: "{currency}{valuePercentTotal.formatNumber('0.00p')}"
  })
);
```

**Comment by flaming-cl** [comment]
> https://www.amcharts.com/docs/v5/charts/percent-charts/legend-percent-series/#Setting_content

Thanks! btw, where can we get "valuePercentTotal"?

**Comment by martynasma** [comment]
Yes, you can include external value using `${yyy}` notation. Or if you want to reference to a key in data you can use just curly brackets `{customValueFromData}`.
