### ISSUE TITLE
Is it possible to set a Custom Axis Label on a DateAxis?

### ISSUE THREAD

**Issue by cheryllaird** [amcharts/amcharts5#1765]
I am trying to customise the axis label for a given date column. 
![image](https://github.com/user-attachments/assets/372c87be-d3c4-4118-9464-dbefc470d4b5)

I have set my data on both axis and the series.
I have been able to customise for Tooltips by using an adapter to access the `dataItem.dataContext`
```
const tooltip = valueSeries.get("tooltip");
tooltip.label.adapters.add("text", (text, target) => {
    return target?.dataItem?.dataContext?.dateLabel || text;
});
```

However when trying to access the `dataContext` on the AxisLabel it is coming back as undefined and therefore not displaying my custom label:
```
// This is not working as dataContext is undefined
renderer.labels.template.adapters.add("text", (text, target) => {
    return target?.dataItem?.dataContext?.dateLabel || text;
});
```

CodePen: https://codepen.io/cheryllaird/pen/MWNmRWJ

**Question**
Is it possible to set a Custom Axis Label on a DateAxis?

**Comment by zeroin** [comment]
If you want all the labels to be some custom strings, not dates, then I would suggest using CategoryAxis instead. If you just want some custom date format, then try to modify date format: https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#date-formats

Adapters do not work for Date axis. 

Another option would be to disable axis labels at all and add axis ranges with custom texts.

**Comment by cheryllaird** [comment]
My main goal is to display a No Value column for any null data.

Given I have the following data, I'd like to display the first column as "No Value":
```
[
  { "date": null, "value": 651 },
  { "date": "01/02/2020", "value": 623 },
  { "date": "01/03/2020", "value": 628 }
]
```

In order to try and achieve this but with using DateAxis (this has other benefits over Category Axis within our product)
I am parsing the data to plot the nulls for the previous date (in this case "01/01/2020") but with a custom label to show on the axis.
```
[
  { "date": "01/01/2020", "value": 651, dateLabel: "No Value" } },
  { "date": "01/02/2020", "value": 623 },
  { "date": "01/03/2020", "value": 628 }
]
```

It would be good if this worked or if there was another way to show `null` column that I am not aware of?

**Comment by cheryllaird** [comment]
It might be worth noting that `GaplessDateAxis` supports the Custom Label
https://codepen.io/cheryllaird/pen/PoMROwg?editors=0010

**Comment by zeroin** [comment]
Ok, so here is an adapter which will do the thing:

```
renderer.labels.template.adapters.add("text", (text, target) => {
  var seriesItem = dateAxis.getSeriesItem(valueSeries, dateAxis.valueToPosition(target.dataItem?.get("value")), 0.5)

  if (seriesItem) {
    if (seriesItem.dataContext.dateLabel) {
      return seriesItem.dataContext.dateLabel;
    }
  }

  return text;
});
```

Items of date axis do not match series items (as only few are created, also there might be many series). So you need to search for the corresponding series item and check it's context.

**Comment by cheryllaird** [comment]
Great, this works. Thank you!
