### ISSUE TITLE
number format bytePrefixes

### ISSUE THREAD

**Issue by flaming-cl** [amcharts/amcharts5#1767]
```
 root.numberFormatter.setAll(
    {
      numberFormat: '#.0b',
      bytePrefixes: [{ number: 0.1, suffix: 'MB' }]
    }
  )
```

If go with the above code, 0.1MB will be displayed as 1MB. Possible to show 0.1MB?
(If I set `bytePrefixes: [{ number: 1, suffix: 'MB' }]`, byte < 1MB will not show the suffix)

Codepen: https://codepen.io/flaming-cl/pen/dyxXRQX

**Comment by martynasma** [comment]
I'm trying to make a sense of your example. The data values what exactly they mean? Are they bytes, kilobytes,  or megabytes?

If they're anything more than `bytes`, using `"b"` formatter does not make sense. And if they're megabytes, then you don't need format modifier at all. You can just slap "MB" onto format and be done with it:

```
numberFormat: "#.##'MB'"
```
