### ISSUE TITLE
ClusteredPointSeries zoomToCluster Fails Near Map Edges in geoMercator Projection

### ISSUE THREAD

**Issue by hudaif747** [amcharts/amcharts5#1768]
Hello!

I’m not sure if this is a bug or if I’m implementing something incorrectly. Any guidance would be appreciated. Thanks in advance!

Issue
====
When using ClusteredPointSeries to cluster map data items in a MapChart with a geoMercator projection, the clusters near the edges of the map do not respond correctly to the zoomToCluster(dataItem) method. Clicking these cluster points either recenters the map or does nothing. The issue is resolved when setting the rotate boolean to true in zoomToCluster, but I don’t want to enable map rotation.

This behavior occurs in both React and Vanilla JS implementations.

Here are two examples to demonstrate the issue:

React TypeScript: https://codesandbox.io/p/sandbox/sharp-rubin-27d6pk
Vanilla JS: https://jsfiddle.net/hudaif/0z4co6nb/2/

Environment
=========
amCharts version: 5.9.11
Browser: Edge 130 on Windows 10
React: 18.2.0
TypeScript: 4.9.5

**Comment by zeroin** [comment]
This can be solved by adding affectsBounds:true to the series. By default it's false for the MapPointSeries and your points are out of the bounds of land area.

`var pointSeries = chart.series.push(am5map.ClusteredPointSeries.new(root, {affectsBounds: true}));`
