### ISSUE TITLE
Axis range on "y" axis - label is not displayed inside the plot when corresponding property is set

### ISSUE THREAD

**Issue by luktom** [amcharts/amcharts5#177]
There is property "inside" on the label object. When set on the label of "x" axis range it is working correctly (e.g. https://www.amcharts.com/demos/stacked-area/) but it is not working for labels of axis ranges on "y" axis, please check: https://jsfiddle.net/z1gdc3ou/21/ (this is one of your demos, modified to show the problem) - label is not rendered inside the plot area.

**Comment by zeroin** [comment]
To fix this, you should also set: `centerX: 0` for the label. Unfortunately we can not do that automatically as this would break some things.

**Comment by zeroin** [comment]
And probably the most easy way to place the label above the columns would be to set a layer for this label:

`layer:30`

**Comment by luktom** [comment]
@zeroin thanks for your answers. Setting the `centerX: 0` positions the label inside the chart but then I am losing the ability to position the label horizontally. In my case I would like to have a label positioned on the right side of the axis range, but I cannot use the the `centerX` for that. 

There is workaround for this, using `dx` setting, but this only works when you have static width of the chart.

Thus I would still consider this as a bug, label can be placed inside, but then `centerX` setting cannot be used for positonig the label horizontally.

**Comment by zeroin** [comment]
Aligning the label to the right would require an adapter, as the label is in the container which width is limited to the axis width, so you can't do that with any settings. You will also need to mark labels position as dirty when width of a plot container changes:

https://jsfiddle.net/gpcedfwh/

```
const label = rangeDataItem.get("label");
label.setAll({
  inside: true,
  text: "Test label",
});

label.adapters.add("x", (x, target)=>{
  return chart.plotContainer.width();
})

chart.plotContainer.onPrivate("width", ()=>{
  label.markDirtyPosition();
})```
