### ISSUE TITLE
Programmatically scrollbar scrolling

### ISSUE THREAD

**Issue by fruitbang** [amcharts/amcharts5#1772]
Is there way to scroll legend verticalScrollbar by added buttons?
I need to make something like this:
![image](https://github.com/user-attachments/assets/916ca181-3384-40ec-b62a-5ce41c60f8c7)

**Comment by martynasma** [comment]
You can set `start` and `end` settings of a `Slider` or a `Scrollbar`. E.g.:

```JavaScript
legend.get("verticalScrollbar").setAll({
  start: 0.5,
  end: 0.5
});
```

This will position the scrollbar at the middle.

**Comment by fruitbang** [comment]
wow, cool. tnx
