### ISSUE TITLE
Change column alignment

### ISSUE THREAD

**Issue by Zahar661** [amcharts/amcharts5#1774]
Hello everyone I can't find a solution anywhere(( 
It is possible somehow in a graph with column clustering disabled, provided that there are only 6 columns, 3 need to be positioned to the left and 3 to the right. I can't use categories (It seems to me it should be like that, but it doesn't work.

```JavaScript
column1.columns.template.setAll({
            width: am5.percent(48),
            fillOpacity: 0.4,
            strokeOpacity: 0,
            align: "left"
        });
column2.columns.template.setAll({
            width: am5.percent(35),
            fillOpacity: 0.7,
            strokeOpacity: 0,
            align: "left"
        });
column3.columns.template.setAll({
            width: am5.percent(15),
            fillOpacity: 1,
            strokeOpacity: 0,
            align: "left"
        });
column4.columns.template.setAll({
            width: am5.percent(48),
            fillOpacity: 0.4,
            strokeOpacity: 0,
            align: "right"
        });
column5.columns.template.setAll({
            width: am5.percent(35),
            fillOpacity: 0.7,
            strokeOpacity: 0,
            align: "right"
        });
column6.columns.template.setAll({
            width: am5.percent(15),
            fillOpacity: 1,
            strokeOpacity: 0,
            align: "right"
        });
```

align, centerX, pading not work((

**Comment by martynasma** [comment]
If you need to have two separate stacks, you can set `stacked: false` on the series that you want to start a new stack on.

Here's a demo: https://www.amcharts.com/demos/stacked-clustered-column-chart/

**Comment by Zahar661** [comment]
@martynasma Thanks, but it doesn't work. It looks as it should, but it sums up the values of the columns
![image](https://github.com/user-attachments/assets/0d111bb2-2641-4d61-8e21-132998b143da)

As in this example, only 2 columns are needed.
https://www.amcharts.com/demos/layered-column-chart/

**Comment by martynasma** [comment]
I'm not sure what you're asking. If you need columns overlapping, you set `clustered: false`, if you need them stacked, you use `stacked: true`.

**Comment by Zahar661** [comment]
I want there to be 2 columns without clustering. next to each other. I think you need to use categories, but how to do it with DateAxis. Here is an example, if I set DateAxis, then there are no categories, if I set CategoryAxis, then the graph is not formed.

https://codepen.io/Zahar661/pen/PoMOggX

**Comment by martynasma** [comment]
If you don't want clustering, you need to set `clustered: false` on all ColumnSeries.

**Comment by martynasma** [comment]
The only way to do that is to use two X-axes: one for blue columns and the other for purple.

You can make them displayed to the side by manipulating `cellStartLocation` and `cellEndLocation` for two axes:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#cell-start-end-locations
