### ISSUE TITLE
Adding a background to a Tooltip breaks the adapter update

### ISSUE THREAD

**Issue by cheryllaird** [amcharts/amcharts5#1778]
**Bug description**
Adding a background to the Tooltip causes the text adapter to stop updating the values within the tooltip.

Using the example for the Free-floating tooltip on this page:
https://www.amcharts.com/docs/v5/tutorials/combining-tooltip-values-from-multiple-series/

Bug shown here:
Codepen: https://codepen.io/cheryllaird/pen/BaXYmXR?editors=0010

**Comment by martynasma** [comment]
`fill` accepts only `Color` objects, whereas you are setting to a string, which results in error, and stops the update.

Here's a correct way to set the background color of a tooltip:

```JavaScript
tooltip.get("background").set("fill", am5.color(0x000000));
```

**Comment by cheryllaird** [comment]
Great I had missed this - is there a way I can see internal amCharts error to spot this next time?
Thank you for the quick response!
