### ISSUE TITLE
add icon (svg) in legend container

### ISSUE THREAD

**Issue by flaming-cl** [amcharts/amcharts5#1780]
Hey there, do you know how to add an icon (> in the screenshot is the icon) in the legend container?

![image](https://github.com/user-attachments/assets/e9635baa-f849-4526-ab4c-37314b5ef83b)

**Comment by martynasma** [comment]
This might help:
https://www.amcharts.com/docs/v5/concepts/legend/#Images_as_markers

The example pushes into marker, but you can push into label, too.

**Comment by flaming-cl** [comment]
> This might help: https://www.amcharts.com/docs/v5/concepts/legend/#Images_as_markers
> 
> The example pushes into marker, but you can push into label, too.

Thanks @martynasma, do you think it's possible to do it with JSON config?

For example something like 
![image](https://github.com/user-attachments/assets/c35a57b1-5904-42a5-8566-cc4a0ae492a9)

Codepen: https://codepen.io/flaming-cl/pen/dyxXRQX?editors=0010

**Comment by flaming-cl** [comment]
> This might help: https://www.amcharts.com/docs/v5/concepts/legend/#Images_as_markers
> 
> The example pushes into marker, but you can push into label, too.

Yes, this can add icon to label, but the icon is placed in front if the text values, like this:
![image](https://github.com/user-attachments/assets/57f7fece-700d-4fd7-9c6a-c52e36b5cad4)

Since we won't be able to know the length of the label text, do you know how we can replace the icon after the value text?

**Comment by martynasma** [comment]
> Yes, this can add icon to label, but the icon is placed in front of the label text, like this:

Hm, not entirely sure how to do that. Maybe you should consider using HTML for the labels instead.

**Comment by flaming-cl** [comment]
> > Yes, this can add icon to label, but the icon is placed in front of the label text, like this:
> 
> Hm, not entirely sure how to do that. Maybe you should consider using HTML for the labels instead.

Thanks @martynasma. Since we are adding another child under label, possible to get the Text child and get its width before pushing the icon child?

**Comment by martynasma** [comment]
> Thanks @martynasma. Since we are adding another child under label, possible to get the Text child and get its width when adding the icon child?

I don't think so. The underlying Text will inherit parent Label's hardcoded width.
