### ISSUE TITLE
How to prevent tooltips being cut off in scrollable containers?

### ISSUE THREAD

**Issue by AericN** [amcharts/amcharts5#1781]
Hi, I'm using amcharts 5 in my vue 3 project and I'm running into an issue where the tooltips are being cut off. I realize my use case is a bit weird but I hope you can point me in the right direction.

I have a fixed width chart (it's a heatmap) in a div that can change width and when the chart is wider than the parent div then the parent div scrolls. For instance say the chart is 1000px wide and the div is 750px wide so the chart can scroll. The issue I'm having is that the tooltip gets cut off when the chart is scrolled at all. I've tried setting the tooltipContainerBounds but that just makes it so it can render past the edge of the chart but still gets cut off by the parent div.

I was wondering if either of these options are realistic:
1. Is there a way to have the tooltip render on a different element? like the document body or something higher up so it doesn't get cut off by the parent div?
2. Is there a way to make a chart scrollable in such a way that the Y-axis is fixed in place and always shows but the X-axis can scroll?

Some additional context:
I couldn't find a way to make the Y-axis sticky so that it's always visible so I rendered a list of the category names in a separate div and hid the y-axis on my chart and put the chart in a scrollable div.
<img width="792" alt="Screenshot 2024-11-04 at 2 04 41 PM" src="https://github.com/user-attachments/assets/37925afa-c3f4-4a81-9252-85ae63c9725e">
<img width="919" alt="Screenshot 2024-11-04 at 2 00 45 PM" src="https://github.com/user-attachments/assets/d6842c59-7f73-4091-8dc2-a2ca6539a04a">

**Comment by martynasma** [comment]
I'm afraid there's no way to make tooltips use any other DOM element than the chart's container.

The only workaround I can think of is disabling built-in tooltips, then using `pointerover` and `pointerout` events to display a custom tooltip.

Unfortunately, I don't have a ready-made example like that.

**Comment by AericN** [comment]
Thank you for your response, I'll look more into that. What about option 2? Is there a way to make the Y-axis sticky so it doesn't scroll? I'm imagining something like setting a fixed width on the chart but having the data area be scrollable. I had thought about setting an initial zoom on the chart but I want to be able to have it show everything if the viewport is big enough.

**Comment by martynasma** [comment]
Well, you can add a horizontal scrollbar on your chart so the X-axis is scrolled, but the Y-axis will always be visible.

https://www.amcharts.com/docs/v5/charts/xy-chart/scrollbars/

**Comment by AericN** [comment]
Ok sounds good, thank you again for your fast responses. I'll close this now.
