### ISSUE TITLE
How to get the click event of the Drill-Down Treemap chart

### ISSUE THREAD

**Issue by nayane95** [amcharts/amcharts5#1782]
I'm using the Drill-Down Treemap chart in my next project and I need to load children node data in a lazy approach . issue is that I cannot get the dataItem of the clicked data node. here is the used approach.

```JavaScript
series.nodes.template.events.on("click", function (e) {
			console.log({ e });

			const dataItem = e.target.dataItem;

			if (dataItem) {
				console.log("Node clicked:", dataItem.get("name"));

				// Check if children are already loaded
				if (!dataItem.get("childrenLoaded")) {
					const children = transformDataForLazyLoading(
						MOCK_DATA,
						dataItem.get("name")
					);
					dataItem.set("children", children);
					dataItem.set("childrenLoaded", true);
				}
			}
		});
		
```

But, sadly this event is not triggering at all.

Any suggestions  to fix this

**Comment by martynasma** [comment]
The event trigger code looks ok to me and should work.

Do you have a full example?

**Comment by martynasma** [comment]
Just a quick node: all events need to be added before data. Is yours perhaps being added after?
