### ISSUE TITLE
Can't fully disable tooltip animation on a pie chart

### ISSUE THREAD

**Issue by jonaspohren** [amcharts/amcharts5#1783]
I'm trying to disable all animation on the tooltip, but there is still a subtle fade in effect when the mouse hovers on a slice in a pie chart.

Here is an example:  https://codepen.io/jonaspohren/pen/yLmRwbR

**Comment by martynasma** [comment]
If you're trying to disable all animations, perhaps you should not use animated theme?

```JavaScript
root.setThemes([
  am5themes_Animated.new(root)
]);
```

Or you want to keep some of the animations?

**Comment by jonaspohren** [comment]
Disabling all animations works for me, but my tooltip background brakes for some reason: https://codepen.io/jonaspohren/pen/yLmRwbR

**Comment by martynasma** [comment]
You should not set `background` on a tooltip:

```JavaScript
const tooltip = am5.Tooltip.new(root, {
  labelText: "Tooltip",
  autoTextColor: false,
  animationDuration: 0,
  stateAnimationDuration: 0,
  getFillFromSprite: false,
  // Commenting out the following line
  // background: am5.RoundedRectangle.new(root, {})
});
```

**Comment by jonaspohren** [comment]
How can I remove the tooltip's pointer without changing the background?

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.
