### ISSUE TITLE
How to add Sticky tooltips on Hierarchy

### ISSUE THREAD

**Issue by choconutzy** [amcharts/amcharts5#1785]
- I've tried Search for similar issues on other site
    https://codepen.io/team/amcharts/pen/gOGwgZO

 - Also tried to read documention
    https://www.amcharts.com/docs/v5/concepts/common-elements/tooltips/
**Question**
  Any other ways to make sticky tooltip/ make the tooltip show not only when nodes hovered?

**Comment by martynasma** [comment]
Do you have a demo of you actual chart?

**Comment by martynasma** [comment]
Two things:

1. `showTooltipOn` is Sprite's setting, not tooltip's.
2. You need to created a tooltip for each individual node if you want to show them all at once:

```JavaScript
series.nodes.template.setup = function(target) {
  target.setAll({
    showTooltipOn: "always",
    tooltip: am5.Tooltip.new(root, {
      labelText: "[bold]{name}xxx",
    })
  });
}
```
