### ISSUE TITLE
Unable to apply zoom programmatically on vertical axis when both x and y axes are value axis.

### ISSUE THREAD

**Issue by Garima-github-24** [amcharts/amcharts5#1786]
Hi,

I have created an XY chart with both x and y axes as vertical axis. I haven't used the vertical scrollbar but I am trying to apply zoom programmatically on vertical axis and horizontal axis. While xAxis.zoomToValues() is working properly and horizontal axis gets zoomed as expected. But I am not able to use yAxis.zoomToValues() to zoom the vertical axis. Kindly tell if this is by design or an issue.

```JavaScript
xAxis.zoomToValues(
        start,
        end
      );

let yAxis = chart.yAxes.push(
      am5xy.ValueAxis.new(this.root, {min: 0,
      maxDeviation: 0.1, renderer: am5xy.AxisRendererY.new(this.root, {}))
    );

    yRenderer.grid.template.set('strokeOpacity', 0.05);
    yRenderer.setAll({
      strokeOpacity: 1,
      opacity: 1,
    });

yAxis.ghostLabel.set('forceHidden', true);
```

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by Garima-github-24** [comment]
Hi,

Here is the complete code. I have figured that yAxis.ghostLabel.set('forceHidden', true); is causing this issue. When I removed this line of code, vertical axis zoom is working properly.

this.root = am5.Root.new('1');
      this.root._logo.setAll({
        x: 25,
        y: 8,
        centerX: am5.p0,
        centerY: am5.p50,
        interactive: false,
      });

      // Set themes
      // https://www.amcharts.com/docs/v5/concepts/themes/
      this.root.setThemes([am5themes_Frozen.new(this.root)]);

      // Create chart
      // https://www.amcharts.com/docs/v5/charts/xy-chart/
      let chart = this.root.container.children.push(
        am5xy.XYChart.new(this.root, {
          focusable: true,
          panX: false,
          panY: false,
          wheelX: 'none',
          wheelY: 'none',
          pinchZoomX: false,
          pinchZoomY: false,
          paddingLeft: 0,
          paddingBottom: 0,
        })
      );

      // Create axes
      // https://www.amcharts.com/docs/v5/charts/xy-chart/axes/
      let xAxis = chart.xAxes.push(
        am5xy.ValueAxis.new(this.root, {
          renderer: am5xy.AxisRendererX.new(this.root, {}),
          tooltip: am5.Tooltip.new(this.root, {}),
          min: 0,
          maxDeviation: 0.1,
        })
      );

      let yAxis = chart.yAxes.push(
        am5xy.ValueAxis.new(this.root, {
          renderer: am5xy.AxisRendererY.new(this.root, {}),
          tooltip: am5.Tooltip.new(this.root, {}),
          min: 0,
          maxDeviation: 0.1,
        })
      );

      yAxis.ghostLabel.set('forceHidden', true);

      let xDateAxis = chart.xAxes.push(
        am5xy.DateAxis.new(this.root, {
          ...{
            maxDeviation: 0.1,
            renderer: am5xy.AxisRendererX.new(this.root, {}),
            tooltip: null,
            markUnitChange: false,
          },
          groupData: false,
          baseInterval: { timeUnit: 'minute', count: 5 },
          visible: false,
        })
      );
      // Hide grid lines for date axis
      xDateAxis.get('renderer').grid.template.setAll({ forceHidden: true });

      this.xAxis = xAxis;
      this.yAxis = yAxis;

      // Create series
      // https://www.amcharts.com/docs/v5/charts/xy-chart/series/
      let series = chart.series.push(
        am5xy.LineSeries.new(this.root, {
          xAxis: xAxis,
          yAxis: yAxis,
          valueYField: 'valueY',
          valueXField: 'valueX',
          valueField: 'value',
          tooltip: am5.Tooltip.new(this.root, {
            labelText: 'x: {valueX}, y: {valueY}, value: {value}',
          }),
        })
      );

      series.strokes.template.set('visible', false);

      let dateSeries = chart.series.push(
        am5xy.LineSeries.new(this.root, {
          xAxis: xDateAxis,
          yAxis: yAxis,
          valueXField: 'timestamp',
          valueYField: 'valueY',
          tooltip: am5.Tooltip.new(this.root, {}),
          visible: false,
        })
      );

      // Add cursor
      // https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/
      chart.set(
        'cursor',
        am5xy.XYCursor.new(this.root, {
          xAxis: xAxis,
          yAxis: yAxis,
          snapToSeries: [series],
        })
      );

      // Add scrollbars
      // https://www.amcharts.com/docs/v5/charts/xy-chart/scrollbars/
      chart.set(
        'scrollbarX',
        am5.Scrollbar.new(this.root, {
          orientation: 'horizontal',
        })
      );

      let data = [];
      var date = new Date();
      date.setHours(0, 0, 0, 0);
      for (var i = 0; i < 15000; i++) {
        am5.time.add(date, 'day', 1);
        data.push({
          timestamp: date.getTime(),
          valueX: Math.random() * 100,
          valueY: Math.random() * 100,
          color: am5.Color.fromString(
            '#' + Math.floor(Math.random() * 16777215).toString(16)
          ),
          value: Math.random() * 20,
        });
      }

      // add graphics to line series which will contain bullets
      let canvasBullets = series.children.push(am5.Graphics.new(this.root, {}));

      canvasBullets.set('draw', (display) => {
        // loop through all data items
        am5.array.each(series.dataItems, (dataItem) => {
          // set fill style from data context
          let dataContext = dataItem.dataContext;
          if (dataContext) {
            const point = dataItem.get('point');
            if (point) {
              display.beginPath();
              display.beginFill('#0951B0');
              display.drawCircle(point.x, point.y, 3);
              display.endFill();
            }
          }
        });
      });

      // user data is set on each redraw, so we use this to mark draw as dirty
      series.strokes.template.on('userData', drawBullets);

      function drawBullets() {
        canvasBullets._markDirtyKey('draw');
      }

      series.data.setAll(data);

      dateSeries.data.setAll(data);

      // Make stuff animate on load
      // https://www.amcharts.com/docs/v5/concepts/animations/
      series.appear(1000);
      chart.appear(1000, 100);

**Comment by zeroin** [comment]
Try to add `autoZoom:false` for your y axis, as by default this axis is zoomed automatically to show all the data in the selection

**Comment by Garima-github-24** [comment]
Thanks, that solved my problem
