### ISSUE TITLE
"EventDispatcher is disposed" error when data updates after Template background is updated

### ISSUE THREAD

**Issue by cheryllaird** [amcharts/amcharts5#1788]
**Bug description**
I have a use case where I need to update the background of a bullet's Label on demand. The initial update seems to work ok, but then on any subsequent data updates an error is thrown.

In the codepen example, click the "Update background" button and then click the "Update data" button.

See console error:
```
Uncaught Error: EventDispatcher is disposed
    at g.copyFrom (index.js:1:290419)
    at d._apply (index.js:1:319294)
    at o._applyTemplate (index.js:1:283198)
    at index.js:1:283855
    at Module.o (index.js:1:241481)
    at o._eachTemplate (index.js:1:283701)
    at o._applyTemplates (index.js:1:283831)
    at o._applyThemes (index.js:1:285407)
    at index.js:1:47274
    at l.eachChildren (index.js:1:52743)
```

https://codepen.io/cheryllaird/pen/poMYqmq?editors=1010

**Comment by martynasma** [comment]
OK, you are reusing the same template/background across data updates. When previous data items are disposed, so is the background, resulting in the error.

For reusable templates, you need to disable the disposing of template background that will be reused:

```JavaScript
const labelTemplate = am5.Template.new({
    fill: am5.color("#00ff00"),
    background: am5.RoundedRectangle.new(root, {}),
});

labelTemplate.get("background").enableDispose = false;
```

**Comment by cheryllaird** [comment]
This seems to stop the initial error - the background is not being applied to the first data item though. Do you know why this might be, is this a related issue?

https://codepen.io/cheryllaird/pen/rNXgLOe?editors=0010

**Comment by martynasma** [comment]
You're right. The issue with this is that the same element is shared as background for multiple elements. Let's refactor your code to use a separate template for background:

```JavaScript
const labelTemplate = am5.Template.new({
  fill: am5.color(theme[currentTheme].text)
});

const labelBackgroundTemplate = am5.Template.new({
  fill: am5.color(theme[currentTheme].background),
  stroke: am5.color(theme[currentTheme].border)
});

labelTemplate.setup = function(target) {
  target.set("background", am5.RoundedRectangle.new(root, {}, labelBackgroundTemplate));
}

// ...

function updateBulletBackground() {
  currentTheme = currentTheme === "light" ? "dark" : "light";
  labelTemplate.set("fill", am5.color(theme[currentTheme].text));
  labelBackgroundTemplate.setAll({
    fill: am5.color(theme[currentTheme].background),
    stroke: am5.color(theme[currentTheme].border),
  });
}
```

Updated CodePen:
https://codepen.io/team/amcharts/pen/zYggqEe/6ae5f95780f91ecfc4a8c29ef39385ce

**Comment by cheryllaird** [comment]
Fantastic! Thank you for your help, this was really making my head scratch but makes sense having the background as a separate template 👍
