### ISSUE TITLE
How to hide indicators toolbar?

### ISSUE THREAD

**Issue by carlosh-dev** [amcharts/amcharts5#1790]
**How to hide indicators toolbar?**

Hi, guys!

I'm trying to custom my indicators and I need to hide this toolbar:

![Captura de Tela 2024-11-18 às 10 57 25](https://github.com/user-attachments/assets/054c7269-6ea0-4f31-a88c-88dd7ffc821f)

I can't find some setting for this in documentation. Can someone help me? 

Development environment:
 - amCharts version 5.6.1
 - NextJS 14.0.3

**Comment by martynasma** [comment]
This:

```JavaScript
_afterNew() {
  super._afterNew();
  this.panel.panelControls.set("forceHidden", true);
}
```
