### ISSUE TITLE
the visibility of outerCircle is automatically determined by the length of the children array of a node

### ISSUE THREAD

**Issue by nontimebomala** [amcharts/amcharts5#1791]
**Question**
Is there a way to manually control the visibility of the outerCircle

**Environment (if applicable)**
amcharts5

**Additional context**

i has been tried this way,its not working。

```JavaScript
chartSeries.outerCircles.template.adapters.add('visible', (_, target) => {
     return true;
 });
```

**Comment by martynasma** [comment]
Here's a little workaround:

```JavaScript
series.outerCircles.template.adapters.add('visible', (_, target) => {
  target.setPrivate("visible", true);
  return true;
});
```

**Comment by nontimebomala** [comment]
> Here's a little workaround:
> 
> ```js
> series.outerCircles.template.adapters.add('visible', (_, target) => {
>   target.setPrivate("visible", true);
>   return true;
> });
> ```
its worked！thanks a lot

**Comment by nontimebomala** [comment]
> Here's a little workaround:
> 
> ```js
> series.outerCircles.template.adapters.add('visible', (_, target) => {
>   target.setPrivate("visible", true);
>   return true;
> });
> ```

How can I determine the expansion state of a node, whether it is collapsed or expanded?

**Comment by nontimebomala** [comment]
> Here's a little workaround:
> 
> ```js
> series.outerCircles.template.adapters.add('visible', (_, target) => {
>   target.setPrivate("visible", true);
>   return true;
> });
> ```

@martynasma by the way, do u know How can I determine the expansion state of a node, whether it is collapsed or expanded?

**Comment by martynasma** [comment]
You can check node's `disabled` setting.

**Comment by nontimebomala** [comment]
> Here's a little workaround:
> 
> ```js
> series.outerCircles.template.adapters.add('visible', (_, target) => {
>   target.setPrivate("visible", true);
>   return true;
> });
> ```

Why is the outerCircles a solid line instead of a dashed line after the settings? It will only turn into a dashed line when I expand the next level and then collapse it again.

**Comment by martynasma** [comment]
I'm not entirely sure. Do you have a demo?

**Comment by nontimebomala** [comment]
> I'm not entirely sure. Do you have a demo?

I have achieved my requirement by using other methods. Thank you. Besides, currently the lines are connected to the inner circle. If I want to change it to connect to the outer circle, any advices?

**Comment by martynasma** [comment]
No, I'm afraid. The links go to the center of the node.

You can add `fill` and `fillOpacity` to the outer circle to go over it.
