### ISSUE TITLE
I am getting error- Uncaught TypeError: Cannot read properties of undefined (reading '__esModule')

### ISSUE THREAD

**Issue by JinsMampuzha** [amcharts/amcharts5#1799]
**Question**

Gauge chart (Radar Chart), why I am getting error- Uncaught TypeError: Cannot read properties of undefined (reading '__esModule') 

**Environment (if applicable)**
- amcharts v(5.8.3)
- cefsharp chromium browser (119.4.3)

**Additional context**

I am trying to integrate Gauge chart into my web project. I am  loading my webpage inside chromium browser using cefsharp. while loading the page I am getting the following error,

amcharts_radarcharts.js:2 Uncaught TypeError: Cannot read properties of undefined (reading '__esModule')
    at amcharts_radarcharts.js:2:28786
    at t (amcharts_index.js:2:561797)
    at amcharts_radarcharts.js:2:69 

my piechart and xy charts are working properly.

I downloaded the sample gauge chart and it is working. It is working in my machine.

**Comment by Pauan** [comment]
How are you loading amCharts? Are you using the script version, or the npm version? Are you using a bundler?

**Comment by JinsMampuzha** [comment]
Scripts downloaded to local folder.  and added in html like following 

<script src="../../Scripts/amCharts/amcharts_index.js"></script>
<script src="../../Scripts/amCharts/amcharts_piecharts.js"></script>
<script src="../../Scripts/amCharts/amcharts_radarcharts.js"></script>
<script src="../../Scripts/amCharts/amcharts_xycharts.js"></script>
<script src="../../Scripts/amCharts/Animated.js"></script>

**Comment by martynasma** [comment]
Are those files a script version (available via ZIP download or CDN) or module versions (installed from NPM)?

**Comment by JinsMampuzha** [comment]
I downloaded zip file.

**Comment by martynasma** [comment]
Can you download the latest version again, and try?

**Comment by JinsMampuzha** [comment]
Tried latest also,
Uncaught TypeError: Cannot read properties of undefined (reading '__esModule')
    at radar.js:1:25134
    at t (radar_index.js:1:504280)
    at radar.js:1:64
    getting above error.
    
  `  var t = e.O()
      , i = window;
    for (var s in t)
        i[s] = t[s];
    t.__esModule && Object.defineProperty(i, "__esModule", {
        value: !0
    })`
    here value of **t** us undefined

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by Pauan** [comment]
Try changing the order of your imports:

```html
<script src="../../Scripts/amCharts/amcharts_index.js"></script>
<script src="../../Scripts/amCharts/amcharts_xycharts.js"></script>
<script src="../../Scripts/amCharts/amcharts_piecharts.js"></script>
<script src="../../Scripts/amCharts/amcharts_radarcharts.js"></script>
<script src="../../Scripts/amCharts/Animated.js"></script> 
```

Note that we recommend using our npm package, since it's the most modern way of writing JS code.

**Comment by JinsMampuzha** [comment]
Thank you. Its working now
