### ISSUE TITLE
How we can give padding between nodes

### ISSUE THREAD

**Issue by hrpatidar** [amcharts/amcharts5#1802]
https://codepen.io/team/amcharts/pen/OJmBxXo

In above given example, you can see, third layer child are overlap. In my case, on third layer counts around 10 and more.. How it is possible to render without touch each other? I tried to given padding, but it's not working at all. 

```JavaScript
series.nodes.template.setAll({
      paddingTop: 10,
      paddingBottom: 10,
      paddingLeft: 10,
      paddingRight: 10,
      width: 100, // Fixed node width
      height: 50, // Fixed node height
      draggable: true,
    });
```

See attached screenshot from my local. I want to avoid overlap.. I really need it for my running product.

![Screenshot 2024-12-10 at 5 10 54 PM](https://github.com/user-attachments/assets/7b9de776-4e95-47d6-b03b-0582b09e0ac7)

**Comment by hrpatidar** [comment]
@martynasma  any inputs, please?

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by martynasma** [comment]
On second thought, I don't think what you need is possible. The space is divided for each node based on its immediate children count. It does not take sub-children into account, and it cannot make sub-child nodes go under non-own parents.

Sorry, but we won't be able to to suggest anything for it.

**Comment by hrpatidar** [comment]
np, thanks for your comment.
