### ISSUE TITLE
Hover the closest bullet to the cursor along the X axis of a chart - snapToSeries not having the desired effect

### ISSUE THREAD

**Issue by cheryllaird** [amcharts/amcharts5#1811]
Based on this example here: https://codepen.io/team/amcharts/pen/rNGKyRG?editors=0010
Is it possible to just hover the closest bullet to the cursor but still respecting the snap to X axis?

I have tried playing around with `snapToSeries` and `snapToSeriesBy` but unable to create the desired effect.

I am trying to achieve the following
- Cursor is where the Red `x` is (2016)
- Closest bullet along the same X location (2016) should be the bullet highlighted with yellow circle
![image](https://github.com/user-attachments/assets/a47aa2da-78b3-415d-89c5-6701c8c258fa)

Issues I am seeing:
- Without `snapToSeries`, all of the bullets for 2016 show hovered state
- Having `snapToSeries` set highlights the 2017 bullet (instead of 2016).
- With `snapToSeriesBy: "x"` only the first series hovers (unless bullet is hoevred directly)

https://codepen.io/cheryllaird/pen/raByQRP?editors=0010

**Comment by zeroin** [comment]
Here it is: https://codepen.io/team/amcharts/pen/ogvWBgJ?editors=0010
It's a bit complicated though: I set `maxTooltipDistance:0` for the chart, this makes only one tooltip to be visible at a time. 
I call `hover()` on the bullet only if tooltip is visible. For it to be actually not visible, I set dy to -1000.

**Comment by cheryllaird** [comment]
This works - thank you! 

It does feel like a bit of a workaround that would benefit from being fixed in amCharts internally. I raise this because it is not intuitive/documented for our developers so in the longer term bugs may creep in and the feature regress.

**Comment by zeroin** [comment]
We will think about it, thanks. But I can promise this approach will not regress in any way.
