### ISSUE TITLE
Correction Needed: Misspelling of 'Divvied' in amCharts 5 Documentation 

### ISSUE THREAD

**Issue by alokkumar95** [amcharts/amcharts5#1816]
**Bug description**

I found a spelling mistake in the "Getting Started" documentation for amCharts 5.

Link - https://www.amcharts.com/docs/v5/getting-started/

Error - The word "divvied" is misspelled.

Correct Spelling - The correct spelling should be "divided".

amCharts 5

<img width="729" alt="image" src="https://github.com/user-attachments/assets/6b840d19-a273-495f-95f8-14e1aa291b17" />

**Comment by martynasma** [comment]
https://www.merriam-webster.com/dictionary/divvy 😉
