### ISSUE TITLE
How to hover in multiple series

### ISSUE THREAD

**Issue by byseop** [amcharts/amcharts5#184]
I'm writing the code referring to [example](https://codepen.io/team/amcharts/pen/VwMbpjQ?editors=1010). There is only one serie in this example.

Please check the [example](https://codepen.io/byseop/pen/jOGKrWp?editors=1011) that i worte.
I'm using `snapToSeries` for `Cursor` being always show. In this situation, I can't access the other series dataItems. because the tooltip is disabled (or hidden?).

My real code here
```typescript
let prevSprites: am5.Sprite[] = [];
cursor.events.on('cursormoved', () => {
  const sprites = seriesArr.map((serie) => serie.getTooltip()?.dataItem?.bullets?.[0].get('sprite'));
 // sprites = [Circle, undefined, undefined] or sprites = [undefined, Circle, undefined]
 // HERE: I can't getting dataItems from series array. because tooltip of series that didn't snapping cursor is disabled

  for (let i = 0; i < sprites.length; i++) {
    if (prevSprites[i] !== sprites[i]) {
      sprites.forEach((sprite) => sprite?.hover());
      prevSprites.forEach((sprite) => {
        sprite?.unhover();
      });
      prevSprites = sprites as am5.Sprite[];
      break;
    }
  }
});
```

Is multi series hover states possible?

**Comment by martynasma** [comment]
Here's an updated CodePen:
https://codepen.io/team/amcharts/pen/rNGKyRG?editors=0010

Hope you find it useful.

**Comment by byseop** [comment]
It works. thx!!

**Comment by byseop** [comment]
It works. but...
Is there any way to use it with the `snapToSeries` option?

**Comment by byseop** [comment]
I was using DateAxis and I had to use `baseInterval = 'day'`. But data didn't exist every day, so tooltips could not be seen always. Therefore, using `snapToSeries`, the cursor automatically snaps the dataItem.

However, the example you uploaded can't be applied when using `snapToSeries`. So, I decided to solve this issue by changing axis to `CategoryAxis`.

Thank you for your help in solving it.
