### ISSUE TITLE
Point Series Tooltip issue

### ISSUE THREAD

**Issue by DeepKarmakar** [amcharts/amcharts5#185]
I'm using Am5 with Angular. I'm getting list of points from an API and loading it on the map dynamically. For that I have used `pointSeries.pushDataItem()`. Now points are coming perfectly but the tooltip is not coming up. 

I have created one [Stackblitz](https://stackblitz.com/edit/angular-ivy-rapc2j?file=src%2Fapp%2Fapp.component.ts) for that. In line number 75 I have added "name" but it is giving error. Can you please have a look.

**Comment by martynasma** [comment]
You are pushing a data item directly to series. `IMapPointSeriesDataItem` does not have the `name` setting, hence the error.

Try pushing to series data, instead of data item:

https://www.amcharts.com/docs/v5/charts/map-chart/map-point-series/#Using_custom_data_fields

**Comment by DeepKarmakar** [comment]
I got your point, and that helped. Just like in Am4 we have "tooltipHTML", do we have the same in Am5?

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.

**Comment by DeepKarmakar** [comment]
Yeah sure, will keep in mind. Thank you so much for your time
