### ISSUE TITLE
Export not working

### ISSUE THREAD

**Issue by wsdt** [amcharts/amcharts5#187]
Exporting a chart via the ExportingMenu works just fine, but when we try to access the export() or exportImage() function directly, we just receive a blank image (= no data, can be seen when exporting as CSV). 

 ```
import * as am5 from "@amcharts/amcharts5";
import * as exp from "@amcharts/amcharts5/.internal/plugins/exporting/Exporting"
import * as am5percent from "@amcharts/amcharts5/percent";
import {ExportingMenu} from "@amcharts/amcharts5/.internal/plugins/exporting/ExportingMenu";

... // building the chart and adding to root

 let exporting = exp.Exporting.new(root, {
    ExportingMenu.new(root, {}), // exporting works fine
  });

  const uri = await exporting.exportImage("jpg") // returns a blank image, empty base64
  await exporting.download("jpg") // also just returns a blank image
  console.log("IMAGE-data: ", uri)
```

Would really appreciate some help here. 

Thank you in advance.

**Comment by Jo-Chris** [comment]
Discovered the same issue. Returns a blank page for pdf or blank image for exportImage.

**Comment by martynasma** [comment]
Hard to tell without seeing your complete code, but if you are calling export immediately after you create the chart, then it just exports unrendered chart. You should probably wait until chart is fully rendered by adding `setTimeout()` or [monitoring chart frames](https://www.amcharts.com/docs/v5/getting-started/root-element/#Chart_ready_event).

**Comment by Jo-Chris** [comment]
`  await chart.appear(1, 1);`

seems to fix the problem, though its located under "// Make stuff animate on load" in here: 
https://www.amcharts.com/demos/exporting-chart-to-image/

is this the default behaviour? is it the preferred way to call  ` await chart.appear(1, 1);` before exporting it?

**Comment by martynasma** [comment]
> is this the default behaviour? is it the preferred way to call await chart.appear(1, 1); before exporting it?

Yup, that is a good way to ensure the chart is fully rendered and finished initial animations, so, ready to be exported.

**Comment by wsdt** [comment]
Working with appear(), thanks guys!
