### ISSUE TITLE
tooltipHTML in Am5

### ISSUE THREAD

**Issue by DeepKarmakar** [amcharts/amcharts5#189]
In Am4 we have "tooltipHTML" but in Am5 how we can use that? I found in this [article](https://www.amcharts.com/docs/v5/concepts/common-elements/tooltips/) that we can do bold and line break. Here I need to add change text color for specific word and font size as well. Can you please suggest how we can achieve that in Am5?

**Comment by martynasma** [comment]
Please refer to [this tutorial](https://www.amcharts.com/docs/v5/concepts/formatters/text-styling/) for in-line text formatting.

**Comment by DeepKarmakar** [comment]
How to give padding and margin?

**Comment by martynasma** [comment]
Padding and margin around specific word or tooltip in general?

**Comment by DeepKarmakar** [comment]
Margin to the word in tooltip.

**Comment by martynasma** [comment]
Nope. Can't do that, I'm afraid.

Maybe pad the word with some non-breaking space chars?

**Comment by DeepKarmakar** [comment]
Is there any Line Hight? if so we can use that.

**Comment by martynasma** [comment]
Well, there's a [`lineHeight`](https://www.amcharts.com/docs/v5/reference/label/#lineHeight_setting) setting for the `Label`.

**Comment by DeepKarmakar** [comment]
Can we use that for Text Styling within tooltip?

**Comment by martynasma** [comment]
> Can we use that for Text Styling within tooltip?

No, I'm afraid.

**Comment by DeepKarmakar** [comment]
okay, no problem. I'll try to manage. Thanks 👍

**Comment by otliievnia** [comment]
can any pictures be added in tooltips?

**Comment by sassomedia** [comment]
@otliievnia Yes, you could indeed do that. The Tooltip is a Container, which has children. You can push pretty much anything into a [Container](https://www.amcharts.com/docs/v5/concepts/common-elements/containers/). Picture example here: https://codepen.io/sassomedia/pen/abEdraB?editors=0010
