### ISSUE TITLE
Legend in Sankey not properly formatted

### ISSUE THREAD

**Issue by vaibhavad** [amcharts/amcharts5#19]
Hi,

I am trying to add a custom legend to Sankey plot. For some reason, the text and the marker are not getting properly aligned. Here is an example.

https://codepen.io/vaibhavad/pen/VwWVbPV

**Comment by martynasma** [comment]
Pushing legend into series as a child is not right.

I would suggest creating a wrapper container which you would use to put both series and the legend to:

https://codepen.io/team/amcharts/pen/qBjQxbx?editors=0010
