### ISSUE TITLE
Sankey traceable - highlight link in different order amchart 4 vs 5

### ISSUE THREAD

**Issue by aniov** [amcharts/amcharts5#191]
Hy,

 I'm trying to create a continuous traceable link from left to right and for that i've order the data.
 It seems that using same data, amchart 5 is rendering links not is same order as amchart 4.

![image](https://user-images.githubusercontent.com/21243081/148441529-205f872f-597a-40e1-b3ca-d025108aa3da.png)

Here is a codepen: https://codepen.io/aniov/pen/eYGjJbg?editors=0110

Thanks in advance.

**Comment by martynasma** [comment]
amCharts 5 Sankey uses different algorithm when arranging nodes. However, it still depends on an order of links in data, albei differently.

I suppose you could try re-arranging the data to better fit your tracing requirements.

**Comment by aniov** [comment]
Ok.
Thank you.
