### ISSUE TITLE
piechart - grouping- click behaviour zoom doesn't show previous slices when clicking back

### ISSUE THREAD

**Issue by oliverlj** [amcharts/amcharts5#193]
when I click other with a zoom behavior and clicking the "-", I have only 100% other and other slices are hidden

First shown
![image](https://user-images.githubusercontent.com/1826498/148534634-543239c9-6660-42ca-9be6-95957b524555.png)

Click on other
![image](https://user-images.githubusercontent.com/1826498/148534734-0790bb4c-72d3-4021-8621-e7e314a20ee1.png)

Click on "-"
![image](https://user-images.githubusercontent.com/1826498/148534806-fc9053a7-ea72-4a30-a06e-0614cb25d877.png)

**Comment by martynasma** [comment]
Could you verify you are running the latest version (5.0.20)?

If you do, can you please post your chart on CodePen so that we can test? I'm afraid I can't reproduce this.

**Comment by oliverlj** [comment]
https://codepen.io/oliverlj/pen/eYGjjjo

I don't know why, not all tool tip shown on hover. but this reproduce the bug.

**Comment by martynasma** [comment]
Thanks. Seems like the issue is about "small" slices not being at the end.

We'll need to fix this.
