### ISSUE TITLE
Can amcharts5 objects be included in a Vue component?

### ISSUE THREAD

**Issue by rmwever** [amcharts/amcharts5#194]
Hi, I have a general use question for amcharts5. In amcharts4, there was a recommendation [not to include the amcharts4 objects in Vue components](https://www.amcharts.com/docs/v4/getting-started/integrations/using-vue-js/). 

> Do not include the chart object inside your Vue component's data property. Vue's reactivity system conflicts with how amCharts manages updates to the chart object and can cause errors if you do this. If you need to store a reference to the chart object in your component, create your reference variable inside the created hook, then assign your chart instance to it in your  mounted hook.

Do you have the same recommendation for when using amcharts5?

**Comment by Pauan** [comment]
Yes, we have the same recommendation. You should use regular object properties inside of the `mounted` hook (like shown in that tutorial), then it will be fine.

Of course you can have reactive data (or props) as well, but you will need to use a watcher or lifecycle hook in order to update amCharts when that data changes:

```js
export default {
  name: 'HelloWorld',

  data() {
    return {
      foo: 5,
    };
  },

  mounted() {
    let root = am5.Root.new(this.$refs.chartdiv);
    ...
    this.root = root;
  },

  updated() {
    if (this.root) {
      // Update chart using the component's data
    }
  },

  watch: {
    foo(oldVal, newVal) {
      if (this.root) {
        // Update chart when the foo data changes
      }
    },
  },

  beforeDestroy() {
    if (this.root) {
      this.root.dispose();
    }
  }
}
```

**Comment by educob** [comment]
How can `let root = am5.Root.new(this.$refs.chartdiv);` without importing it?

`import * as am5 from "@amcharts/amcharts5";
`

When I run it with SSR the browser crashes with error: `Unexpected token 'export'
`

Thanks.
