### ISSUE TITLE
How to show map point tooltip on hover of external element(Outside of map)

### ISSUE THREAD

**Issue by DeepKarmakar** [amcharts/amcharts5#195]
I have two map points and having tooltip on them. That's working fine. Now I have two button outside of the map and on hover of those button that tooltip need to show up. I have found one API `columnSeries.columns.getIndex(1).showTooltip()` but not sure how to use this in my case. I have created one [Stackblitz](https://stackblitz.com/edit/angular-ivy-rapc2j?file=src%2Fapp%2Fapp.component.ts) and at the bottom I have MouseEnter and MouseLeave method. Can you please suggest something here?

**Comment by martynasma** [comment]
It's more like this:

```JavaScript
pointSeries.dataItems[0].bullets[0].get("sprite").hover();
```

**Comment by DeepKarmakar** [comment]
That's perfect. Thank you so much 👍
