### ISSUE TITLE
Date axis ticks line up on the middle of the month instead of end of month

### ISSUE THREAD

**Issue by dez1729** [amcharts/amcharts5#196]
When Date axis ticks was visible, it is on the middle of the month instead of end of month, so it doesn't line up with the grid lines at all.

![image](https://user-images.githubusercontent.com/20635596/148885770-101c5610-fc2c-418c-998d-cbf5c804f2d9.png)

**Comment by zeroin** [comment]
Just set location:0 for the ticks:
https://codepen.io/team/amcharts/pen/04d3ee52f4648f0d41513b154db8ed44

**Comment by dez1729** [comment]
Thanks!
