### ISSUE TITLE
mappositionchanged event in Am5

### ISSUE THREAD

**Issue by DeepKarmakar** [amcharts/amcharts5#199]
In Am4 we can add our event on mappositionchanged, like this, `chart.events.on('mappositionchanged', customEvent);`

how we can do in Am5?

**Comment by zeroin** [comment]
You can monitor change of properties, like `chart.on("translateX", customEvent)`

**Comment by DeepKarmakar** [comment]
do we have anything that will detect any change in map regardless of translateX or translateY?

**Comment by zeroin** [comment]
No, you should monitor all the properties.

**Comment by DeepKarmakar** [comment]
"mappositionchanged " and "translateX / translateY" they don't looks same. Actually I need a event handler where we are dragging the map, I mean if any map position are getting change by drag or zoom. Do we have any event for that?

**Comment by zeroin** [comment]
No, we don't. Depending on your setup, when you drag the map, translateX/translateY/rotationX/rotationY can be updated. So you need to monitor all 4 or them.

**Comment by DeepKarmakar** [comment]
I tried with all 4, now it's coming good, but lagging a lot. sometime after dragging position is not coming properly. can you please just have a look on this [stackblitz](https://stackblitz.com/edit/angular-ivy-rapc2j?file=src%2Fapp%2Fapp.component.ts)?

Note: earlier in Am4 it was happening perfectly with "mappositionchanged" and no lagging at all

**Comment by zeroin** [comment]
Why don't you simply add this custom marker to your bullet? That would work perfectly and you wouldn't need any of this. Instead of a Circle, add `Picture` to your bullet, specify `src` and that will do the job.

https://www.amcharts.com/docs/v5/reference/picture/

**Comment by DeepKarmakar** [comment]
Can you please share an example of "Picture", how to use that

**Comment by zeroin** [comment]
https://www.amcharts.com/demos/line-with-custom-bullets/

**Comment by DeepKarmakar** [comment]
I got it. just one thing how can I put color on svg icons? fill is not accepting.

**Comment by sassomedia** [comment]
You can change the fill/stroke color of an SVG inside of itself. Open the SVG in your editor to change the color there. You could use two SVGs with different colors if you have on/off states. If you need something more dynamic, you could try something like this: https://stackoverflow.com/a/27596977/6276921.

**Comment by DeepKarmakar** [comment]
I have done like you said, it's coming perfectly. But after that point tooltip is not working which I'm opening on hover of an external element by using this code. `pointSeries.dataItems[0].bullets[0].get("sprite").hover()`

**Comment by sassomedia** [comment]
Which part is undefined? Is `pointSeries.dataItems[0].bullets[0].get("sprite")` actually a `container`?
Could you put this into a simple code example on codepen or jsfiddle?

**Comment by DeepKarmakar** [comment]
I have created [Stackblitz](https://stackblitz.com/edit/angular-ivy-rapc2j?file=src%2Fapp%2Fapp.component.ts), Here I have two points one of them is normal circle and another one I made like you suggested. Yo will find in line number 61-82. 

I have external button and on hover on those button I'm opening the same tooltip. For normal circle(Point B) it's working perfectly, but point with an Picture it's failing.

**Comment by sassomedia** [comment]
Ok thanks, that helps. So the issue is that you're conditionally adding different things to the sprite, one is a container, the other a circle. The tooltip is only on the circle however. So you can't trigger a tooltip on the container. Rather than conditionally add different types, conditionally add different children to the container. The circle will always be on index 0 for both points.
```javascript
pointSeries.bullets.push(function (_root, _series, dataItem: any) {
  let circle = am5.Circle.new(root, {
    radius: 5,
    fill: am5.color(0xff0000),
    tooltipText: `{name}`,
  });
  var container = am5.Container.new(root, {
    centerX: am5.p50,
    centerY: am5.p50,
  });
  container.children.push(circle);

  if (dataItem.dataContext.name == 'Point A') {
    container.children.push(
      am5.Picture.new(root, {
        centerX: am5.p50,
        centerY: am5.p50,
        width: 20,
        height: 20,
        dx: 0,
        dy: -10,
        src: 'assets/person_pin_circle.svg',
      })
    );
  }

  return am5.Bullet.new(root, { sprite: container });
});
```
Then on the button handler, find the circle with:
```javascript
const container = this.pointSeries.dataItems[id].bullets[0].get('sprite');
containter.children.getIndex(0).hover();
```
Now, TypeScript gave me a lot of grief as it thinks that "sprite" is of the type `Sprite` since that's what the button accepts. This is not true in this case as the type is `Container`. If you were to disable the typescript warning or temporarily assign the type to `any` for this particular instance, you will get access to the children and the hover works.

@martynasma the incorrect prototype for the `Button` seems like a bug.

**Comment by DeepKarmakar** [comment]
I tried that, and this is working perfectly. Thank you so much 👍
