### ISSUE TITLE
Migration Documentation

### ISSUE THREAD

**Issue by xbaha** [amcharts/amcharts5#2]
Would be nice if you can add V.4 to V.5 migration docs on release instead of rewriting everything from scratch.

**Comment by martynasma** [comment]
Frankly, there is nothing to migrate. The two versions are fundamentally different. We'll keep in mind if we can maybe create some generic guideline document.

Thanks for the suggestion.

**Comment by Eduardo-Julio** [comment]
Okay, nothing to migrate then because they are fundamentally different, it would still be useful for this to be somewhere in the documentation so people like me searching for migration info know that there is nothing we can do.

**Comment by martynasma** [comment]
FYI, we've posted this article:
https://www.amcharts.com/docs/v5/migrating-from-amcharts-4/

We will be updating it when we think there's some information that needs to be posted.

In the interim, I'm going to go ahead and close this thread. You can follow documentation updates here:
https://www.amcharts.com/docs/v5/changelog/
