### ISSUE TITLE
geoPointToSVG in Am5

### ISSUE THREAD

**Issue by DeepKarmakar** [amcharts/amcharts5#200]
Do we have similar of "geoPointToSVG" in Am5?

**Comment by martynasma** [comment]
Yes:
https://www.amcharts.com/docs/v5/reference/mapchart/#convert_method

**Comment by DeepKarmakar** [comment]
Actually I have a custom marker for one of the map point. I used "Convert" function to get the points but it's not placing to the exact position. Here is the [Stackblitz](https://stackblitz.com/edit/angular-ivy-rapc2j?file=src%2Fapp%2Fapp.component.ts), on line number 136 converting the lat and long. Can you please have a look why marker not coming to the exact place?

**Comment by martynasma** [comment]
Well, coordinates returned by `convert()` are relative coordinates to the chart div, not document. You might need to factor that in.

**Comment by DeepKarmakar** [comment]
Do you mean that "geoPointToSVG" and "convert" are different?

**Comment by martynasma** [comment]
Nah, they both return relative coordinates.

**Comment by DeepKarmakar** [comment]
I understood. Thanks
