### ISSUE TITLE
Draw single lines with given start/end points(or positions)

### ISSUE THREAD

**Issue by koorizhizhi** [amcharts/amcharts5#201]
Hi, I need to draw (dashed)lines which can be generated dynamicly on the chart as shown below:
![image](https://user-images.githubusercontent.com/83855880/148936239-7a305f8c-8e40-492b-9648-3b474c16a166.png)
The brackets should be dynamic to follow the first 2 points on the XY chart.

I tried to use AxisRanges to draw a single line on the chart, but I cannot set its start/end points. What I get is always a line spanning the whole chart.
I also found a class named Line that I think could help... However I don't know how to get it shown on the chart.
I've also checked docs about the cursor. I do think there is something in common but I don't know how to modify these components to reach that.

Is there any way to make it? I'd greatly appreciate some help.

**Comment by koorizhizhi** [comment]
I used 4 more series to make a shift. 
![image](https://user-images.githubusercontent.com/83855880/149077043-3272340e-5e30-49ad-a89c-30d36c813bef.png)
Is there any better way to do make it?

**Comment by martynasma** [comment]
I think your approach is best (and probably the only) option. That's how I would do it.

**Comment by koorizhizhi** [comment]
> I think your approach is best (and probably the only) option. That's how I would do it.
OK, thanks for your reply.
One more question, is it possible to show the table as below with amcharts only?
![image](https://user-images.githubusercontent.com/83855880/149084789-3a25c0f4-d823-4705-aa70-391d74673448.png)

**Comment by martynasma** [comment]
> One more question, is it possible to show the table as below with amcharts only?

No, I'm afraid. We do not offer visualization of data as a data table.

**Comment by sassomedia** [comment]
I guess you could create a manual table with containers if the chart has enough spacing on the right.
https://codepen.io/sassomedia/pen/ExwObyQ?editors=0010

**Comment by koorizhizhi** [comment]
> I guess you could create a manual table with containers if the chart has enough spacing on the right. https://codepen.io/sassomedia/pen/ExwObyQ?editors=0010

Yeah, it's really an inspiration to me!
Currently I took a clumsy solution exporting the chart and then draw a table with canvas directly...
You give me a new direction to follow. Appreciate it.
