### ISSUE TITLE
How to resize plane according to Map zoon in/out

### ISSUE THREAD

**Issue by DeepKarmakar** [amcharts/amcharts5#205]
How can we control the plane size when user will zoom in/out to the map?

**Comment by sassomedia** [comment]
By plane, are you referring to the plane in the [map example](https://codepen.io/team/amcharts/pen/jOmzZLY?editors=0010)? What are you expecting to happen with the plane? You could control the size by adjusting the `scale: 0.06` on line 70 of that example. You could attach a zoom-listener to the chart like in this example: https://www.amcharts.com/docs/v5/charts/map-chart/map-pan-zoom/#Control_scroll and adjust the scale accordingly.

**Comment by DeepKarmakar** [comment]
Yes you are correct. I meant that plane. How can I adjust the scale of plane depending on zoom in/out proportion?

**Comment by sassomedia** [comment]
Right, as suggested, you could adjust the scale with a zoom-listener. Although, as the example currently works, when the chart is zoomed in/out, the plane scales with it. What would you expect to happen instead?

**Comment by DeepKarmakar** [comment]
I can't see any scale change of plane when the map getting zoom in/out. Please have a look once again

**Comment by sassomedia** [comment]
You are right, it seemed to scale but it went out of view quickly. If the plane is pulled into the center of the chart, it's easier to see as it scales from the center.

Here's a suggestion with zoom controls, that gives you fairly consistent control over the scale of things. When clicking the zoom control buttons, they scale the chart by the [`zoomStep`](https://www.amcharts.com/docs/v5/reference/mapchart/#zoomStep_setting). The same can be used to scale the plane: https://codepen.io/sassomedia/pen/vYevBrR?editors=0010

**Comment by DeepKarmakar** [comment]
Yeah I got the zooming control, but in my case I don't have any button. I have to fire an event when user will zoom by using mouse scroll button. Can you suggest an event for that?

**Comment by sassomedia** [comment]
Yeah, that's in this example: https://www.amcharts.com/docs/v5/charts/map-chart/map-pan-zoom/#Control_scroll. Just get the `chart.get("zoomStep")` whenever the event fires and use that to apply it to the plane scale.

**Comment by DeepKarmakar** [comment]
I didn't get any refence for `chart.get("zoomStep")`, if you have any example of this code and how to use that will be good

**Comment by sassomedia** [comment]
My bad, I meant `chart.get("zoomLevel")`. You could set the `zoomStep` in the beginning to control the chart zoom speed.

**Comment by DeepKarmakar** [comment]
in this code I'm always getting "Zoom Out" in console. I need both the cases, Zoom In and Zoom Out. So I'll scale the plane accordingly.

`
    chart.events.on("wheel", function(ev) {
      if (ev.originalEvent.ctrlKey) {
        ev.originalEvent.preventDefault();
        chart.set("wheelY", "zoom");
        console.log('Zoom In');
      }
      else {
        chart.set("wheelY", "none");
        console.log('Zoom Out');
      }
    });
`
