### ISSUE TITLE
Performance measurement

### ISSUE THREAD

**Issue by olneyMatt** [amcharts/amcharts5#207]
Hi,

I'm bringing together a few different charts (such as those described [here](https://github.com/amcharts/amcharts5/issues/102) and [here](https://github.com/amcharts/amcharts5/issues/160)) on one page with some fairly heavy datasets.

The performance is acceptable when working on each individually but it becomes sluggish when all are combined.

Is there an easy tool to see which charts / events / monitors are taking the most resources please?

Thanks
Matt

**Comment by olneyMatt** [comment]
Thank for the reply. Sure - of course 'big' is relative! 🤪

The most complex chart has about 8,000 samples of about 20 variables, all of which are being plotted in parallel on the same `XYChart`. The JSON file is about 3.9MB on disk.

A map chart has a `MapLineSeries` with about 4,000 lat/lon coordinates.

I've had the sad face on Chrome with error 5. The total physical RAM on this machine is 128 GB so that shouldn't be a limitation.


Without any interaction, the memory footprint for the tab starts about 600MB, rises to 1GB, then up to 2GB after about a minute. It climbs slowly (over minutes) to around 2.5GB with some spikes of significant CPU activity (and fans).

MacOS Activity Monitor shows that that the process using the resources is Google Chrome Helper (Renderer).

Let me know what more information you need.

Thanks
Matt

**Comment by olneyMatt** [comment]
Extra datapoint....

When I access the page hosted on a website with the JSON data served in a different way, the memory footprint is about 250MB.

When I load the html on my local machine (which is when I get the large RAM usage) I'm using MAMP to serve the JSON file so that might be a source?

Cheers
Matt

**Comment by martynasma** [comment]
@olneyMatt Could you perhaps post your actual chart on CodePen or jsFiddle so that we know what we're dealing with?
