### ISSUE TITLE
Migrate v4 complex tooltipText

### ISSUE THREAD

**Issue by nseb** [amcharts/amcharts5#21]
Hello , in previous v4 , we use : 

series.adapter.add('tooltipText', function () {
        var text = '{text}\n'
        chart.series.each(function (item) {
          text += '[' + item.stroke.hex + ']●[/] [bold]' + item.name + ':[/] {' + item.dataFields.valueY + '}\n'
        })
        return text
      })
to aggregate values in single tooltip like : 
![image](https://user-images.githubusercontent.com/6363226/135213830-138e247d-f185-4e0d-9836-8062a9591ac4.png)

How do i v5 ?

**Comment by martynasma** [comment]
You can use adapter in V5, too. Here's a demo:
https://codepen.io/team/amcharts/pen/ExXrXYo?editors=0010

**Comment by nseb** [comment]
Thanks
