### ISSUE TITLE
Using Theme to set AxisLabels will not allow setting stroke in Typescript

### ISSUE THREAD

**Issue by dez1729** [amcharts/amcharts5#213]
If I were to set the stroke and fill via renderer it will work:

    renderer.labels.template.setAll({
        stroke: am5.color('#ccccdc'),
        fill: am5.color('#ccccdc'),
      });

but if I were to do this with the Theme method, like so:

    const axisTheme = am5.Theme.new(this.root);
    axisTheme.rule('AxisLabel').setAll({
      stroke: am5.color('#ccccdc'),
      fill: am5.color('#ccccdc'),
    });

    this.root.setThemes([ axisTheme ]);

I'm getting this typescript error in intellisense:

    Argument of type '{ stroke: am5.Color; fill: am5.Color; }' is not assignable to parameter of type 'Partial<IAxisLabelSettings>'.
    Object literal may only specify known properties, and 'stroke' does not exist in type 'Partial<IAxisLabelSettings>'.ts(2345)

**Comment by sassomedia** [comment]
I have a bit of a different implementation. Maybe something like this would work for you:

`myTheme.js`
```javascript
import * as am5 from "@amcharts/amcharts5";
import { fontFamily } from "./chartUtils";

class MyTheme extends am5.Theme {
  setupDefaultRules() {
    this.rule("Label").setAll({ fontFamily });
  }
}

export default MyTheme;
```
`chart.js`
```javascript
import * as am5 from "@amcharts/amcharts5";
import * as am5xy from "@amcharts/amcharts5/xy";
import am5themesAnimated from "@amcharts/amcharts5/themes/Animated";
import myTheme from "../../util/myTheme";

const root = am5.Root.new(div);
root.setThemes([am5themesAnimated.new(root), myTheme.new(root)]);

const chart = root.container.children.push(am5xy.XYChart.new(root, {}));
...
```

**Comment by martynasma** [comment]
`Label` does not have `stroke` setting. Does error go away if you remove it? It does not do anything anyways.
