### ISSUE TITLE
am4core.options.minPolylineStep missing in am5

### ISSUE THREAD

**Issue by ovsleep** [amcharts/amcharts5#214]
It seems that the minPolylineStep option is missing in am5. According to this: [https://www.amcharts.com/docs/v4/concepts/performance/#Simplifying_paths](url) 
It was the way to make a Line Series performant with thousands of data points. I know there's the Data Grouping option, but that only works for a Date axis. 
What options do we have to make it performant with a Value axis?

**Comment by sassomedia** [comment]
I think this is what you are looking for:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#Dynamic_data_item_grouping

**Comment by sassomedia** [comment]
Ah never mind, that does seem just for dates. Maybe the value axis option will be added in the future.

**Comment by ovsleep** [comment]
> I think this is what you are looking for: https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#Dynamic_data_item_grouping

Yes, this is just for dates. I think the minPolylineStep option had a different approach. More like the "minGridDistance" option for grids. I need something like that, but for data

**Comment by martynasma** [comment]
At this point we do not plan on adding this setting to amCharts 5, which is generally much faster than amCharts 4 as it is.

As @sassomedia suggested, much better approach is to use data grouping, if you are plotting time-based data.

**Comment by ovsleep** [comment]
That's too bad. I have a chart with around 20K items and it feels really slow. I tried to make an interpolation between the value axis (frequencies) and a date axis to use the data grouping. That works great. But I have other charts on top (using the value axis) and can't match the two axis exactly. 
It's really dissapointing that you advertise data grouping for 50K+ points, but that would only work for a small set of charts

**Comment by martynasma** [comment]
I'm gonna refactor this as an enhancement request. Might come back to it at some point. Not ETA, tho :(

**Comment by martynasma** [comment]
We somehow missed this issue. LineSeries have had `minDistance` setting for quite a while now:
https://www.amcharts.com/docs/v5/charts/xy-chart/series/line-series/#Simplifying_the_lines

Sorry about failing to notify.
