### ISSUE TITLE
Line series legend in external container issues

### ISSUE THREAD

**Issue by crypto-services** [amcharts/amcharts5#215]
When attempting to move the legend of a line series type graph to an external container the stroke/color indicators are missing and bullets are not aligned with their corresponding key name.

<img width="130" alt="Jepretan Layar 2022-01-16 pukul 23 26 38" src="https://user-images.githubusercontent.com/90644502/149666386-9fdd902c-6ef0-4904-894a-380ac12cc0e1.png">

Moving the legend back in to the the main root div corrects the issue.

<img width="112" alt="Jepretan Layar 2022-01-16 pukul 23 28 54" src="https://user-images.githubusercontent.com/90644502/149666454-39414f2a-d585-4f0c-9f4a-f5aa7d27711f.png">

I have checked all of the available docs on the subject, however they are all using pie series so there maybe some nuance to setting it up that I am missing.  

To test the issue I moved the legend of one of the am5 demos (https://www.amcharts.com/demos/highlighting-line-chart-series-on-legend-hover/) in to an external container as per the docs with the same result - [JS fiddle here.](https://jsfiddle.net/6yzvoe4k/8/)

**Comment by martynasma** [comment]
It's due to how defaults are being applied to series. When legend is not child element of the `XYChart`, its defaults are not being applied.

We will need to figure out a workaround. Will keep you posted.

**Comment by crypto-services** [comment]
Thank you!

**Comment by martynasma** [comment]
OK, so to fix this, you need to do two things:

1) Update to 5.12. (just released).
2) Apply XY's default theme to legend's root element.

```JavaScript
legendRoot.setThemes([
  am5themes_Animated.new(legendRoot),
  am5xy.DefaultTheme.new(legendRoot)
]);
```

More info:
https://www.amcharts.com/docs/v5/concepts/themes/#default-themes

**Comment by crypto-services** [comment]
<img width="339" alt="Jepretan Layar 2022-02-02 pukul 16 07 26" src="https://user-images.githubusercontent.com/90644502/152116087-f36aaea2-b7a3-4e37-9e1f-8cfc982453ce.png">

Thanks Marty! Much appreciated. The colours do now show which is great but the bullets are still not aligned with the lines.

**Comment by martynasma** [comment]
Do you have a fiddle or codepen?

**Comment by aniznik1** [comment]
@martynasma I think I have a fiddle regarding a similar problem

[https://jsfiddle.net/xy1cL794/1/](https://jsfiddle.net/xy1cL794/1/)

You can see some weird shapes (I guess they are trying to match the series' bullets) on top of the markers, and if you click on a legend item, the shape will stay disabled while the other element will change from disabled to enabled.

**Comment by martynasma** [comment]
Thanks.

The issue is that bullet is being created using different Root object.

We need to use legend root to create bullets. The Root object is being passed in as a first parameter to bullet functions, so we can use that:

```JavaScript
latitudeSeries.bullets.push(function(root) {
  var graphics = am5.Circle.new(root, {
    strokeWidth: 2,
    radius: 5,
    stroke: latitudeSeries.get("stroke"),
    fill: root.interfaceColors.get("background"),
  });

  graphics.adapters.add("radius", function(radius, target) {
    return target.dataItem.dataContext.townSize;
  })

  return am5.Bullet.new(root, {
    sprite: graphics
  });
});
```
