### ISSUE TITLE
How to show only one shared tooltip over multiple series?

### ISSUE THREAD

**Issue by dez1729** [amcharts/amcharts5#218]
I'm using the example given here:
https://www.amcharts.com/docs/v5/tutorials/combining-tooltip-values-from-multiple-series/

While this shows all the series data in one tooltip, if the series overlaps then the tooltips will show multiple tooltips each with the same shared data.

![image](https://user-images.githubusercontent.com/20635596/149997175-81cb0668-53d8-4b67-8ddd-3c744371264f.png)

Is there a way to show just one "shared" tooltip?

**Comment by martynasma** [comment]
Setting `maxTooltipDistance: -1` in cursor's settings should fix that.

**Comment by dez1729** [comment]
It works when I put the above settings on the chart config as opposed to the cursor's.

That being said, is it possible to create the above tooltip attached to the cursor instead, similar to this:

![image](https://user-images.githubusercontent.com/20635596/150006639-6da6951a-2874-4a0a-85ec-aef7b9fb53d7.png)

So it doesn't snap to a specific series, but the tooltip moves where the cursor is and snaps to the closest points in the series.

**Comment by dez1729** [comment]
Also, doesn't really work properly when there are multiple series that have different x-axis:
![image](https://user-images.githubusercontent.com/20635596/150046267-2c393f91-1e04-4c8c-8469-919604c460b5.png)

**Comment by dez1729** [comment]
I think I found a workaround for the not two axis issue.
I compare the series' valueYField with the data column name to only show the ones that are contained in the axis.

**Comment by martynasma** [comment]
> So it doesn't snap to a specific series, but the tooltip moves where the cursor is and snaps to the closest points in the series.

I suppose you can create a separate series (make it invisible) with all-zero values for each date, then attach tooltip to it and no other series.

You would probably need to attach that series to its own Y axis, and make it invisible as well.

Does that make sense?
