### ISSUE TITLE
Adding patterns via an adapter does not appear to work if the adapter creates a new pattern.

### ISSUE THREAD

**Issue by buggedcom** [amcharts/amcharts5#220]
https://codepen.io/buggedcom/pen/dyVEbqP

In the pen above notice this

```js
series2.columns.template.set("fillPattern", am5.CirclePattern.new(root, {
  color: am5.color(0xffffff),
  checkered: true
}));
```

Now that works of course, but setting a pattern via a template adapter does not, unless setting the same pattern from the arguments. For example:

```js
// this works
series2.columns.template.adapters.add("fillPattern", (value) => value);
```

but this does not

```js
// this does not
series2.columns.template.adapters.add("fillPattern", (value) => am5.CirclePattern.new(root, {
  color: am5.color(0xffffff),
  checkered: true
}));
```

Why is this? Am I doing something wrong?

**Comment by buggedcom** [comment]
In addition, though, this ordering would work.

```js
const p = am5.RectanglePattern.new(root, {
  color: am5.color(0xff0000),
  checkered: true
});
series2.columns.template.adapters.add("fillPattern", () => p);
```

**Comment by martynasma** [comment]
Adapters kick in only when there's a value to mutate. If you don't initially set `fillPattern` on the template then it does not try to apply adapter to it.

Applying adapters to **all** possible settings every time would be huge waste of resources. So yeah, you need to set initial `fillPattern` then you can modify it with an adapter.

**Comment by buggedcom** [comment]
I don't think that is what I was asking.

In the example codepen, it does set the initial value, but also has an adapter. The adapter creates a new instance of a pattern, but new instance of that pattern is not then applied even when returned.

![Screenshot 2022-01-19 at 13 45 12](https://user-images.githubusercontent.com/2810/150123636-dfc56b05-ecd4-44aa-a971-3e44c71af3ce.png)

So as you can see in the screenshot the second columns do not have the new instance of the pattern applied.

**Comment by sassomedia** [comment]
@buggedcom I think the issue is that adapters get called an unknown amount of times in whatever processing cycle the chart goes through. In your pen, I got 54 calls to the adapter function which would essentially return 54 new instances of patterns. It only needs 1 though, so maybe some overload occurs. However, when you create the pattern externally and then pass back that same pattern instance over and over, it works fine:
```javascript
const circlePattern = am5.CirclePattern.new(root, {
  color: am5.color(0xffffff),
  checkered: true
});

series2.columns.template.adapters.add("fillPattern", () => circlePattern);
```

Generally though, the way how you would want to use adapters is by altering the value that the adapter gives you and then return that same instance back to the adapter. In this case, the `value` is the original pattern that was supplied on instantiation. This works as expected:
```javascript
// white-colored dots in grid pattern
series2.columns.template.set("fillPattern", am5.CirclePattern.new(root, {
  color: am5.color(0xffffff),
  checkered: false
}));

// red-colored dots in checkered pattern
series2.columns.template.adapters.add("fillPattern", (value) => {
  value.setAll({
    color: am5.color(0xff0000),
    checkered: true,
  });

  return value;
});
```

@martynasma correct me if I'm wrong here

**Comment by buggedcom** [comment]
Thanks @sassomedia .

Whilst the number of calls and creations of new patterns is an issue, at the moment I'm not overly concerned about that but I will address it in the future.

We're using react and passing down props to these functions in order to change `fillPattern` and other styles, and other things. We currently have a `useEffect` setup to re-run based on the `fillPattern` prop change. What would the best way to trigger the adapter to re-fire in this circumstance then?

Is the only way to re-create the chart? I would want to avoid this if possible, but I feel like this might be the only way.

**Comment by martynasma** [comment]
I think best way to manually re-trigger an adapter is to set a setting to its current value:

```JavaScript
column.set("fillPattern", column.get("fillPattern"));
```
