### ISSUE TITLE
How to trigger a reflow/reposition of a pie's slices labels?

### ISSUE THREAD

**Issue by buggedcom** [amcharts/amcharts5#221]
<img width="607" alt="Screenshot 2022-01-19 at 15 18 43" src="https://user-images.githubusercontent.com/2810/150138563-c9d10736-ebc1-4972-aa4f-8861b992a66d.png">

What would be best practice for hiding/showing labels and ticks for Pie slices?

We have the above pie, where slices labels are automatically hidden if they are smaller than a certain percentage, for example:

```js
            kpiValueSeries.ticks.each((tick) => {
                const slice = tick.dataItem.get('slice');
                const arc = slice.get('arc');
                tick.set('visible', arc > 15);
            });
            kpiValueSeries.labels.each((label) => {
                const slice = label.dataItem.get('slice');
                const arc = slice.get('arc');
                label.set('visible', arc > 15);
            });
```

We then have an option for the user to force show all labels for all slices if they want to and the code essentially does this

```js
        kpiValueSeries.ticks.each((tick) => tick.set('visible', true));
        kpiValueSeries.labels.each((label) => label.set('visible', true));
```

However, the problem we run into is that the labels are kind of squished together like below

<img width="581" alt="Screenshot 2022-01-19 at 15 24 37" src="https://user-images.githubusercontent.com/2810/150139522-eacfe7d6-0e06-4a7b-8576-4b9d60d676d1.png">

Is there a way to call for a reflow/reposition of the labels and ticks so that they position a little better?

**Comment by buggedcom** [comment]
Also, notice how one of the labels on the bottom right is positioned of the screen?

**Comment by sassomedia** [comment]
Not sure whether there's a reposition option (not per docs anyway) but I would figure most of that position logic happens on chart initialization. Easiest option is to re-render the chart, it's fast since it's canvas. I would think this will also take care of the one that goes off screen.

**Comment by martynasma** [comment]
Try calling `series.appear()`.

**Comment by buggedcom** [comment]
Thanks. `series.appear()` does work.
