### ISSUE TITLE
ForceDirected - Circles - Events - "rightclick" is captured by tooltip canvas

### ISSUE THREAD

**Issue by lancegliser** [amcharts/amcharts5#222]
[ForceDirected circle docs](https://www.amcharts.com/docs/v5/charts/hierarchy/force-directed/#Circles)
[Circle event docs](https://www.amcharts.com/docs/v5/reference/forcedirected/#Events)

I attempted to add two events handler for testing purposes:
```ts
const series = container.children.push(
  ForceDirected.new(root, {
    ...defaultForceDirectedSettings
  })
);
series.circles.template.events.on("click", (event) => {
  debugger;
});
series.circles.template.events.on("rightclick", (event) => {
  debugger;
});
```

The `"click"` handler worked immediately. The `"rightclick"` did not.
I was able to trace that down to the a second `canvas` element being created that contains tooltips for the first `canvas`. The right click would produce the browser standard context menu.

After a bit of hunting, I found I could use the [chart ready event](https://www.amcharts.com/docs/v5/getting-started/root-element/#Chart_ready_event) to target that second canvas and prevent `"contextmenu"` events even before I use the `series.data.setAll()`:

```ts
root.events.once("frameended", () => {
  console.info("frameended root.dom", root.dom);
  root.dom.querySelectorAll("canvas").forEach((canvas) => {
    console.info(canvas);
    canvas.addEventListener("contextmenu", (event) => event.preventDefault());
  });
});
```

Maybe this is just a documentation up to suggest the approach if required? Maybe this is a standard thing that needs handled in tooltip layers?

**Comment by martynasma** [comment]
I'm struggling reproducing this. Here's a very basic implementation:
https://codepen.io/team/amcharts/pen/1068148e8780963a61c4731e2c799f50?editors=0010

Both "click" and "rightclick" events kick in.

amCharts 5 does not use actual on-screen canvases for click detection, so their order should not affect interaction events.

**Comment by lancegliser** [comment]
From your codepen example, I show 3 "click" events, and a right click `canvas` context menu.

![image](https://user-images.githubusercontent.com/12085479/150568499-0408814a-2b68-4655-a912-c2eab6623f46.png)

With a bit of JS magic:
![image](https://user-images.githubusercontent.com/12085479/150569015-0725ead1-d9e8-4586-b6ce-74f2556bb25b.png)

```js
document.querySelectorAll('canvas')[1].addEventListener("contextmenu", (event) => event.preventDefault());
```
We now have rightclick events.

Chrome: Version 97.0.4692.71 (Official Build) (x86_64)

**Comment by martynasma** [comment]
There's an easier way:

```JavaScript
root.dom.addEventListener("contextmenu", function(event) {
  event.preventDefault();
});
```

Just posted this tutorial:
https://www.amcharts.com/docs/v5/tutorials/disabling-context-menu-on-chart/

Thanks for the ideas!

**Comment by lancegliser** [comment]
That's a lot cleaner, for sure. Especially the disposing. Thanks for adding that tutorial. I updated and can confirm that has the same effect. I'll close this question based on that. Thanks for the hand!

A couple follow up thoughts:
* You [tutorial](https://www.amcharts.com/docs/v5/tutorials/disabling-context-menu-on-chart/) uses `console`. Most devs will know to open tools and look, would `alert` work without that extra step?
* The breadcrumbs for that tutorial place it at V5 > Tutorials & Demos > Chord.
  It feels like this is more of a "Utilities" or even a concern that will come up for every chart and might belong in the Root documentation or an instantiation option?

**Comment by martynasma** [comment]
> You tutorial uses console. Most devs will know to open tools and look, would alert work without that extra step?

Makes sense.

> The breadcrumbs for that tutorial place it at V5 > Tutorials & Demos > Chord.

Thanks for the heads up about breadcrumbs. Fixed :)
