### ISSUE TITLE
tooltipDateFormat axis setting doesn't work

### ISSUE THREAD

**Issue by DavidSvetlik** [amcharts/amcharts5#223]
Hello,

so I am trying to set custom `tooltipDateFormat` for my DateAxis which I believe should affect output of `valueX.formatDate()` in tooltip's text (although documentation doesn't mention it and pages are not linked). 

However date format in tooltip stays the same and doesn't reflect my setting.

I think it's supposed to be working (and also documentation pages should refer to each other). But if - for some reason - `tooltipDateFormat` isn't related to `valueX.formatDate()`, then:

1. How can I change format of `valueX.formatDate()`?
2. What does `tooltipDateFormat` actually do?

Thank you for your work.

**Comment by martynasma** [comment]
I'm not entirely sure what you mean about `tooltipDateFormat` being related to `formatDate()` method, but it needs to be set to a string representation of the date format

```
var xAxis = chart.xAxes.push(
  am5xy.DateAxis.new(root, {
    tooltipDateFormat: "MMM d, yyyy",
    renderer: am5xy.AxisRendererX.new(root, {})
  })
);
```

Formatting codes are described [here](https://www.amcharts.com/docs/v5/concepts/formatters/formatting-dates/#Format_codes).

**Comment by DavidSvetlik** [comment]
@martynasma Yes, I am doing exactly that. But it just doesn't work and date format in tooltip stays the same. Therefore I think it's a bug.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by martynasma** [comment]
> Which I now understand as tooltipDateFormat is related to axis only.

Yes, `tooltipDateFormat` affects axis' tooltip only.

To format series tooltip you have a number of options, e.g.:

1) Setting date format globally:
https://www.amcharts.com/docs/v5/concepts/formatters/formatting-dates/#Global_date_format

2) Using in-line formatting functions:
https://www.amcharts.com/docs/v5/concepts/formatters/data-placeholders/#In_line_formatting

**Comment by DavidSvetlik** [comment]
@martynasma First option is not viable as this is specific to axis. But second option is exactly what I need, thank you very much! I could swear I have tried it before starting this issue, but it didn't work - maybe I forgot apostrophes as I didn't saw that data placeholder documention page and just tried "guessing" and wrote something like `valueX.formatDate(yyyy)`, then I assumed it's not a way to go and it will have to do with `tooltipDateFormat`, which was apparently a wrong asumption ony my side. :-)

Thank you again and sorry about invalid report, you can close it.
