### ISSUE TITLE
Combining tooltip values from multiple series in a 100% stacked column chart only show values from the hovered series

### ISSUE THREAD

**Issue by Prismatecs** [amcharts/amcharts5#224]
Following this example
https://www.amcharts.com/docs/v5/tutorials/combining-tooltip-values-from-multiple-series/
On a 100% stacked column chart
https://www.amcharts.com/demos/100-stacked-column-chart/

Results in the tooltip showing only the value from the hovered series on all series when changing the "valueYField" to "valueYShow"

You can find it here
https://codepen.io/ehabsherif/pen/XWeLERG

**Comment by zeroin** [comment]
It should be like this:

```
  tooltip.label.adapters.add("text", function(text, target) {
    chart.series.each(function (series) {
      //{name}, {categoryX}:{valueYTotalPercent.formatNumber('#.#')}%
      let dataItem = series.getTooltip().dataItem;
      if(dataItem){
        let value = dataItem.get("valueYTotalPercent");
        let formatted = series.getNumberFormatter().format(value, "#.#") + "%"
        text += '\n[' + series.get("stroke").toString() + ']●[/] [bold width:100px]' + series.get("name") + ':[/] ' + formatted
      }
    })
    return text
  });
```

You should get value from data item, not series. And currently hovered data item can be retrieved from the tooltip of a series.
