### ISSUE TITLE
Use the same root for multiple chart containers?

### ISSUE THREAD

**Issue by dez1729** [amcharts/amcharts5#229]
If I have multiple div containers, each with its own chart, should I be using the same root and chart variables or should I be having a new root and chart variables for each (or set up in an array). If its the former, how can I reference the specific container.

**Comment by martynasma** [comment]
What @lancegliser said :)

I can add that there is no right way, and it's solely up to your app/dashboard/website layout/functionality.

For example, if you add multiple charts to the same `Root` you can easily dispose them all in one go, but you are losing ability to control layout/sizing/grid using means of CSS/HTML.

**Comment by dez1729** [comment]
Would there be a performance hit with multiple vs one root? Each chart will be in its own container and would respond based on the container's size.

**Comment by martynasma** [comment]
> Would there be a performance hit with multiple vs one root?

Theoretical. I'm sur overhead associated with multiple root elements is negligible, if at all: maintaining multiple resize sensors versus maintaining much more complex layout structure in a single root.
