### ISSUE TITLE
No way to dynamically position x-axis below baseline when having negative y-values (xy-chart)

### ISSUE THREAD

**Issue by wsdt** [amcharts/amcharts5#231]
Currently it doesn't seem to be possible to positionate the labels of the x-axis just below the baseline (y=0) when also displaying negative y-values. 

At this moment the chart only shows the values at the bottom of the chart. 

![image](https://user-images.githubusercontent.com/28724551/150639998-3d8f1ac6-8f20-4d73-affa-d1e17287d014.png)

The labels (0..20) should be aligned just below the thicker line at y=0 (baseline).

**Comment by zeroin** [comment]
You can do this by adding adapter for labelsContainer of the axis, here is a quick demo:
https://codepen.io/team/amcharts/pen/dyZbONm

These lines does the trick:

```
chart.plotContainer.children.push(xAxis.labelsContainer);
xAxis.labelsContainer.set("position", "absolute");
xAxis.labelsContainer.adapters.add("y", function(y){
  return Math.max(0, Math.min(yAxis.get("renderer").positionToCoordinate(yAxis.valueToPosition(0)), chart.plotContainer.height() - 20));
})

root.events.on("framestarted", function(){
  xAxis.labelsContainer.markDirtyPosition();
})
```
