### ISSUE TITLE
[Bug] StrokeWidth above 3 doesn't work

### ISSUE THREAD

**Issue by wsdt** [amcharts/amcharts5#232]
Using strokeWidth for xycharts with a value higher than 3 doesn't work. 
When setting a higher value the line isn't visible anymore.

**Comment by martynasma** [comment]
I'm afraid I can't reproduce this. Here's a `LineSeries` with stroke width set to 10:
https://codepen.io/team/amcharts/pen/68ed2f1eacc14f1b40885359a3d519d2?editors=0010

Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by wsdt** [comment]
thanks!
