### ISSUE TITLE
Hiding the gridlines for xAxis and yAxis in amCharts5 is not visible 

### ISSUE THREAD

**Issue by NiyatiR** [amcharts/amcharts5#233]
Hello,

amCharts 4 had a real straightforward solution to hide the axis lines as follows:

categoryAxis.renderer.grid.template.disabled = true;
valueAxis.renderer.labels.template.disabled = true;
 
However, when trying a similar approach in amCharts 5, it hides the y axis line left most line as well along with the other vertical lines.
var yRenderer = yAxis.get("renderer");
		yRenderer.grid.template.setAll({
			visible: false
		});
		var xRenderer = xAxis.get("renderer");
		xRenderer.grid.template.setAll({
			visible: false
		});

Could someone please advise on how to keep just the axis line intact but remove other grid line.

Thanks in advance!
![image](https://user-images.githubusercontent.com/94170772/150649467-c06e1150-d8e5-4294-9ae9-5f22ecf42d66.png)

**Comment by martynasma** [comment]
Please refer to this tutorial:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#Axis_line
