### ISSUE TITLE
Scale not updating when changing baseInterval without animations

### ISSUE THREAD

**Issue by mlomb** [amcharts/amcharts5#236]
When I change `baseInterval` dinamically and update the data accordingly without the Animated theme, the scale does not update. Note that with the Animated theme the scale updates as expected.

Example: [https://codepen.io/mlomb/pen/rNGXXQO](https://codepen.io/mlomb/pen/rNGXXQO). Modifications are at the end of the JavaScript file.
To replicate, click "BY DAY" → "BY MONTH" → "BY DAY".

Maybe this is related to zoom? I would expect to show 100% of the scale like it was before switching.
In my real graph, I tried solving it using `min: 0` in the `ValueAxis` but the problem persist at the top.

**Comment by zeroin** [comment]
This can be solved by adding:

```
series.events.on("datavalidated", function(){
  yAxis.zoom(0,1);
})
```

This is not needed with animated theme, as when you change data, xAxis animates to new extremes and this makes yAxis to zoom-out. Without animation, you need to call zoom method.
