### ISSUE TITLE
Help with Creating an SVG icon for force-directed nodes?

### ISSUE THREAD

**Issue by jonofoz** [amcharts/amcharts5#238]
Hi there :)

I'm trying to append icons to the nodes of a force directed tree based on an `svgPath` property. I'm new to AMCv5, so please bear with me. 

Here's an example where I've begun an attempt to replace `Image` objects with `Graphics` objects, aiming just to see simple checkmarks instead of browser icons: no luck yet. I wonder if I have to use the `draw` property somehow...

https://codepen.io/jonofoz/pen/GROKGRG?editors=0010

Any help is appreciated! Cheers :)
Jon

**Comment by martynasma** [comment]
A few things:

1) This is not a valid JSON:

```
{
    name: "Chrome",
    value: 1,
    svgPath
}
```

This is :)

```
{
    name: "Chrome",
    value: 1,
    svgPath: svgPath
}
```

2) `Graphics` needs to have color in order to draw anything, so you're lacking `fill` setting:

```JavaScript
series.nodes.template.setup = function(target) {
  target.events.on("dataitemchanged", function(ev) {
    var icon = target.children.push(am5.Graphics.new(root, {
      width: 70,
      height: 70,
      centerX: am5.percent(50),
      centerY: am5.percent(50),
      scale: 0.1,
      isMeasured: false,
      svgPath: ev.target.dataItem.dataContext.svgPath,
      fill: am5.color(0x000000)
    }));
  });
}
```

3) Finally, `Graphics` won't autoscale SVG path to `width`/`height` so you will need to work on your `scale` value as per above.

**Comment by jonofoz** [comment]
Ah, perfect! Thank you so much for the help! :D

**Comment by martynasma** [comment]
Glad we could help!

Feel free to close this when ready.
