### ISSUE TITLE
Add action event on each node tree

### ISSUE THREAD

**Issue by ali0707** [amcharts/amcharts5#239]
Hello , I just wondering how can i add on each node an action button? for example for each node we have an alert or popup : 

https://codepen.io/ali2332/project/editor/XWzqJG

Thanks

**Comment by zeroin** [comment]
You should add click listener to the nodes of the series (before setting data):

```
series.nodes.template.events.on("click", function(e){
  console.log(e.target)
})
```

**Comment by ali0707** [comment]
> You should add click listener to the nodes of the series (before setting data):
> 
> 
> 
> ```
> 
> series.nodes.template.events.on("click", function(e){
> 
>   console.log(e.target)
> 
> })
> 
> ```
@martynasma @zeroin 
I already added the buttons but it dose not get the exact target for each node(each node has a different alert),i just updated the link 

https://codepen.io/ali2332/project/editor/XWzqJG

**Comment by martynasma** [comment]
What is `result` variable? I don't see it defined anywhere in your code.

If you need to access a data item of a clicked node, try `ev.target.dataItem`.

**Comment by ali0707** [comment]
> You should add click listener to the nodes of the series (before setting data):
> 
> ```
> series.nodes.template.events.on("click", function(e){
>   console.log(e.target)
> })
> ```

i just added the buttons but it's applayed 

> What is `result` variable? I don't see it defined anywhere in your code.
> 
> If you need to access a data item of a clicked node, try `ev.target.dataItem`.

the variable result to return the name in each action button by the way (I tryed for the button ev.target.dataItem.dataContext.action but it it doesn't work either)
![sss](https://user-images.githubusercontent.com/35613425/151140806-54df18cb-4fd4-40e8-b447-5c0bef853f26.png)

**Comment by sassomedia** [comment]
You shouldn't need to search the tree, there is almost always a way to get internal information. You can add IDs to elements if necessary. In this case, just look at the `dataItem` event and get the information from there: https://codepen.io/sassomedia/project/editor/Zyvdje

Also, make sure that your data is named correctly.

**Comment by ali0707** [comment]
> You shouldn't need to search the tree, there is almost always a way to get internal information. You can add IDs to elements if necessary. In this case, just look at the `dataItem` event and get the information from there: https://codepen.io/sassomedia/project/editor/Zyvdje
> 
> 
> 
> Also, make sure that your data is named correctly.

Thank you 🤗 i just have one more questions it is possible to delete the first pushed button for the node 0 ?

**Comment by sassomedia** [comment]
Sure, just check for the `dataItem.dataContext.id` there as well:
Updated pen: https://codepen.io/sassomedia/project/editor/Zyvdje
