### ISSUE TITLE
Bullets documentation has extra 'new' keyword

### ISSUE THREAD

**Issue by samkristoff** [amcharts/amcharts5#24]
On the [docs page for bullets](https://www.amcharts.com/docs/v5/concepts/common-elements/bullets/) the first two code snippets incorrectly use **new**. 

![image](https://user-images.githubusercontent.com/1994983/135513485-e869c7ee-80fb-4be9-aec8-91262e5c2cef.png)

**Comment by martynasma** [comment]
Thanks for the heads up! Fixed now.
