### ISSUE TITLE
Question: How to offset the start of a series?

### ISSUE THREAD

**Issue by buggedcom** [amcharts/amcharts5#240]
I have a grouped column chart, that also shows a line series over the top as the target level indicator for the chart. The question is, how do I align the target line series with the start of the grouped column as indicated in the screenshot. The whole series would be offset and not just the bullets, so that each bullet lines up with the centre of the respective grouped columns

I understand that this chart format is questionable, but it's what I've been asked to accomplish so there we are.

![Screenshot 2022-01-26 at 12 51 10](https://user-images.githubusercontent.com/2810/151150820-3a8415c9-fef0-47d3-9a3b-dc32b51c1dd3.png)

**Comment by buggedcom** [comment]
I'm answering my own question, sorry to use the issue as a rubber duck.

For anyone else searching and coming here, the solution is to either use [`dx`](https://www.amcharts.com/docs/v5/reference/lineseries/#dx_setting) or [`locationX`](https://www.amcharts.com/docs/v5/reference/lineseries/#locationX_setting)

**Comment by martynasma** [comment]
Let me just add that `locationX` is better, since it is relative, wherease `dx` is an absolute pixel value so it would not work for variable-width charts.

More information about `locationX` here:
https://www.amcharts.com/docs/v5/charts/xy-chart/series/line-series/#Data_item_location
