### ISSUE TITLE
Radar chart categories with multiple independent data

### ISSUE THREAD

**Issue by rferreira98** [amcharts/amcharts5#241]
i'm trying to render a Radar chart with categories on xAxis with a xAxis range.
The problem is that I'm trying to join data like:

Category X:
 Sub-category X1, value 20
 Sub-category X2, value 30
 Sub-category X3, value 15
 Sub-category X4, value 40
Category Y
 Sub-category Y1, value 50
Category Z
 Sub-category Z1, value 50

With this data, I can't use Series because it implies that X1 is present in every category, X2 as well, and so on...
I end up getting a chart with Category X, Y and Z where Y and Z have wrong values of X1, X2, X3 and X4.

AmChart V5
React framework
Codepen: https://codepen.io/r_ferreira/pen/MWOYwdy

Expected result
![Screen Shot 2022-01-26 at 14 39 03](https://user-images.githubusercontent.com/24259712/151208018-30463f81-87aa-4cb1-9f87-a1c1285da3fc.png)

**Comment by sassomedia** [comment]
Hmm, not sure if I understand this right. The expected result looks like just one series:
https://codepen.io/sassomedia/pen/XWzJRmW?editors=0010

Where would you expect sub-categories to be? Do you want them to be [stacked](https://www.amcharts.com/docs/v5/charts/xy-chart/series/column-series/#Stacking)?
https://codepen.io/sassomedia/pen/zYPxZpb?editors=0010

If you want it to be multidimensional, you could create the parent series first and then on click, redraw the chart with the child series. Or use the [innerRadius](https://www.amcharts.com/docs/v5/charts/radar-chart/#Inner_radius) to leave space for a second chart you can place in the middle.

**Comment by rferreira98** [comment]
I don't know if it's 1 series. But the problem with the first solution is that if I needed two slices on red, I'm considering slices as the sub-categories and the axisRange the parent category, if I wanted two slices on red i.e. how could I achieve that without repeating data with a new series?

**Comment by sassomedia** [comment]
Yeah, so you do want multiple Series then. Just change the data for individual series:
https://codepen.io/sassomedia/pen/rNYaQwm?editors=0010

Setting them side-by-side won't give you much space though. I would still suggest having them stacked/clustered. Turn on line 78 to see what that looks like.
