### ISSUE TITLE
Bullets color is not inherited from Line series color

### ISSUE THREAD

**Issue by cmt-ermit** [amcharts/amcharts5#242]
when a new series is created within a for loop and bullets are pushed into it, the color is not inherited from the series itself. 

 `
      series.bullets.push(() =>

    am5.Bullet.new(root, {
      sprite: am5.Circle.new(root, {
        radius: 3,
        fill: series.get('fill'),
        stroke: root.interfaceColors.get('background'),
        strokeWidth: 2,
      }),
    })
  );`

An exampe here: https://stackblitz.com/edit/js-txuxjp?file=index.js

**Comment by sassomedia** [comment]
The colors will be inherited... if proper scoping is used. There shouldn't be any reason to use `var` anymore, which is what causes this issue. _Always_ use `const`, except when needing reassignments then use `let`.

This will fix it for you: `const series = chart.series.push(`
