### ISSUE TITLE
Custom styling of scrollbar grips works but is forgotten when scrolling and interacting with them

### ISSUE THREAD

**Issue by buggedcom** [amcharts/amcharts5#245]
See the attached pen and screenshots. I have custom styled the scrollbar but noticed a bug when you interact with the grip. The grip icons are hidden, but become visible again and also the dy position adjustment is also forgotten.

https://codepen.io/buggedcom/pen/QWOwoJK

![Screenshot 2022-01-27 at 15 22 31](https://user-images.githubusercontent.com/2810/151367430-089f3821-827e-4c75-b762-92ceda467707.png)
![Screenshot 2022-01-27 at 15 22 14](https://user-images.githubusercontent.com/2810/151367435-2b6e4190-67af-467a-af0b-dd5b50138385.png)

**Comment by martynasma** [comment]
It's best to use `forceHidden: true` instead of `visible: false` as the latter might be knocked off by theme/states.

This should work as expected:

```JavaScript
scrollbar.endGrip.get('icon').setAll({
    forceHidden: true
});
```

**Comment by buggedcom** [comment]
Thanks, yes that does fix the issue.
