### ISSUE TITLE
Call of function inside Button event of amchart using angular

### ISSUE THREAD

**Issue by ali0707** [amcharts/amcharts5#246]
I just Integrated amchart5 with Angular 13 ( it's a hierarchy chart with nodes)  every thing works fine the problem is in the call of the function that i did ( by the way when i call the function from html like this (<button (click)="function()"></button>) it works But i don't like to call it there, i want to call the function inside the component file ( in the amchart5 button action ) 
i tried to call it by (this.function) i tried also to put the fucntion in the Bottom  function fn(){ }  :/

![buttonnnnn](https://user-images.githubusercontent.com/35613425/151514699-c6b31101-8795-4f42-b268-bfaddab4cbde.png)
![function](https://user-images.githubusercontent.com/35613425/151514764-d2e1b49e-b121-474f-813a-24fc59c6d350.png)
![Screenshot 2022-01-28 092622 - Copie](https://user-images.githubusercontent.com/35613425/151514766-bbd0ac14-f01c-464d-961e-924d47fa9b8c.png)

**Comment by ali0707** [comment]
![image_2022-01-28_105100](https://user-images.githubusercontent.com/35613425/151525366-60575e5e-943b-4c91-8dc2-8f5f434ca817.png)

**Comment by sassomedia** [comment]
Yeah, I can't see how that would work. `refresh` isn't part of the event. Did you try calling the function directly?
```javascript
button.events.on(click, refresh);
```

**Comment by ali0707** [comment]
> 

yes i tried to call it directry but it didn't know the function , i just found a stupid solution which is leaving the function and declaring let service = this.myservice  and this.data to let Mydata=this.data in the ngOnInit and call it  like this  
button.events.on('click',(ev)=>{
        service.Myobservabledata().subscribe((data: PeriodicElement[]) => {
          Mydata.data = data;  
        })
    
      })
