### ISSUE TITLE
Placing icons at top right of nodes, taking into account their sizes?

### ISSUE THREAD

**Issue by jonofoz** [amcharts/amcharts5#247]
Hi again :)

Here's my Codepen, which builds upon a question I had before (regarding building SVG icons per node, thanks again for the help there!)
https://codepen.io/jonofoz/pen/RwjPOaz?editors=0010

I'm trying to place my checkmark icons at the top right of the nodes. I tried grabbing the size of the nodes themselves. Even after digging through the docs and the console.log of different objects, I couldn't quite find the things to grab. Any ideas?

Cheers!
Jon

**Comment by martynasma** [comment]
Just use `centerX` and `centerY` to identify center of the image. `isMeasured: false` must also be removed:

```JavaScript
    var icon = target.children.push(am5.Graphics.new(root, {
      centerX: am5.p50,
      centerY: am5.p50,
      scale: 0.1,
      svgPath: ev.target.dataItem.dataContext.svgPath,
      fill: am5.color(0x000000)
    }));
```

**Comment by sassomedia** [comment]
@martynasma I think this is a bit more involved. The `centerX/Y` would just center the icon, which works fine but he wants them top-right of the circle. One thing is that the there's `minRadius` set, so we can account for that with `value < minRadius ? minRadius : value` but it looks like the values aren't translating to pixels while `x`/`y` or `dx`/`dy` are in pixels.
https://codepen.io/sassomedia/pen/gOXPPdb?editors=0010

When measured, the smaller circles are pretty much 60pixels in diameter (based on 30 `minRadius`) but the large circle is only 130pixels (based on 100 value). There seems to be an overall scaling happening, is there a way to translate that relative size into pixels so it would work for the offset?

**Comment by martynasma** [comment]
@sassomedia Indeed. I jumped the gun reading the description.

I know it's now super straightforward, but this seems to work:

```JavaScript
series.nodes.template.setup = function(target) {
  target.events.on("dataitemchanged", function(ev) {
    var icon = target.children.push(am5.Graphics.new(root, {
      centerX: am5.p0,
      centerY: am5.p100,
      scale: 0.1,
      isMeasured: false,
      svgPath: ev.target.dataItem.dataContext.svgPath,
      fill: am5.color(0x000000)
    }));

    target.dataItem.on("circle", function(circle) {
      circle.on("radius", function(radius) {
        icon.setAll({
          x: radius,
          y: -radius * 2
        })
      })
    })
  });
}
```

The reason for those events is that circles do not have their target radius right from the start.

**Comment by jonofoz** [comment]
Thank you both so much for the help so far on this!

@martynasma I'm not sure that's quite the solution either, though: I've updated my Codepen with your snippet, and while it's certainly yards better than my attempt, the bubble with the higher value seems to have its icon a bit further out:

![image](https://user-images.githubusercontent.com/29444592/151815821-b92a6e98-f3fc-4101-bd0b-34f61ad11ed1.png)

**Comment by martynasma** [comment]
Well, you can tweak it with `centerX`/`centerY` as well as `dx`/`dy`.

**Comment by jonofoz** [comment]
@martynasma That sounds great: honestly, in retrospect, what I was envisioning beforehand wouldn't be possible without some some small adjustments. The way the code currently is might actually suitable. Thanks again!
