### ISSUE TITLE
Hiding tooltips on hovering over a node's icon? (Continued from AMCv4 question)

### ISSUE THREAD

**Issue by jonofoz** [amcharts/amcharts5#248]
Hi there :)

Here's my Codepen attempt to hide a node's tooltip when hovering over its icon. I still haven't cracked it here in AMCv5, but it's got to be possible somehow.
https://codepen.io/jonofoz/pen/abVOxQX?editors=0010

This question is continued from my question here for AMCv4:
https://github.com/amcharts/amcharts4/issues/3961

Any suggestions would be appreciated! 

Thank you :)
Jon

**Comment by martynasma** [comment]
The following will disable tooltips on nodes:

```JavaScript
series.nodes.template.setAll({
  tooltipText: ""
});
```

**Comment by jonofoz** [comment]
Hey @martynasma,

Sorry, I should've been clearer about my desired functionality 🙃 The suggested code _does_ work, but it hides the node's tooltips permanently... so the last part to figure out is some way to restore those tooltips on the icon's `"pointerout"` event

**Comment by martynasma** [comment]
```JavaScript
series.nodes.template.setAll({
  tooltipText: "{category}: {sum}"
});
```

**Comment by jonofoz** [comment]
@martynasma Thanks for the suggestion :) It doesn't seem to work, unfortunately, as the icon tooltip doesn't disappear anymore and the node tooltip won't re-appear.

I admit this is a very strange feature request, and it may be more straightforward to supply a supplementary key / legend to the icons than to try to force the components into doing things they might not be meant to do. As always, thank you again for your help!

**Comment by martynasma** [comment]
Wait so you want to display **both** node's built-in and icon's tooltips?

**Comment by jonofoz** [comment]
It's a little more finessed than that. If I don't attempt to use the `icon.events`, I _do_ see both tooltips at the same time; what I'm hoping to achieve, however, is to only show tooltips on one or the other at a time, depending on which element the mouse is currently hovering over. If the mouse is over the node, show the node's tooltip; if over the icon; show the icon's tooltip

**Comment by martynasma** [comment]
Ummmm, that makes sense now. I think it's doable with some event trickery.

Though, I'd have to say this seems like bad UX to me. How user is to know that he/she needs to move around the node to get appropriate dual information. Not to mention this would be extremely tricky on touch devices.

I wholeheartedly advice to include all the information user would need to know in a single (node) tooltip.

It would be much more intuitive for the user, and less tricky to implement for you.

**Comment by jonofoz** [comment]
@martynasma Very valid concerns! I will venture away from double tooltips, then. Yes, I think either supplying all required information into a single tooltip or providing some kind of icon legend would be the preferable route. Cheers!
