### ISSUE TITLE
Radar with SmoothedRadarLineSeries

### ISSUE THREAD

**Issue by nseb** [amcharts/amcharts5#25]
Hi ,

I have a different render v4 vs v5  when I have NaN values, I want fill like v4
V4 : 
![image](https://user-images.githubusercontent.com/6363226/135527147-12d0acbd-b630-444a-b9a8-cf6f8b26690d.png)
V5:
![image](https://user-images.githubusercontent.com/6363226/135527192-3912566d-a3e6-4e50-85b8-79d40fafc011.png)

Best Regards

**Comment by martynasma** [comment]
It looks like you don't have fill set up at all.

Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by nseb** [comment]
I have make several test : 
with RadarLineSeries , works with connect: false , and remplace NaN values par null , you test null value not NaN , like v4.

Same conffiguration SmoothedRadarLineSeries , not working,  connect property is never taken into consideration

**Comment by martynasma** [comment]
If you could post your chart with config that does not work as expected on CodePen, we'd be able to check it out. Thanks!
