### ISSUE TITLE
Classes, Interface, Standalone module docs gone

### ISSUE THREAD

**Issue by sassomedia** [amcharts/amcharts5#250]
Looks like the most recent update (v5.1.1) wiped the API:
<img width="1394" alt="Screen Shot 2022-01-31 at 9 49 41 PM" src="https://user-images.githubusercontent.com/5614099/151796526-982dc8a4-5837-4fcc-9337-a49ea69dfa01.png">

**Comment by martynasma** [comment]
You must've hit precise moment when new classref was being imported. Looks good to me now.

Can you verify?

**Comment by sassomedia** [comment]
Yup, works now, all good 👍
