### ISSUE TITLE
Category X-Axis labels when combined with truncation and max width do weird things

### ISSUE THREAD

**Issue by buggedcom** [amcharts/amcharts5#252]
I'm sorry but the internal logic and data is too complicated for me to setup a codepen for this one.

But take these two videos.

In the first

```js
            renderer.labels.template.setAll({
                oversizedBehavior: "truncate",
                maxWidth: 150,
                location: 0.5,
                textAlign: 'right'
            });
 ```

https://user-images.githubusercontent.com/2810/151845267-a0b9411e-2d66-4e3d-ad55-20d18e4989e9.mov

Notice how the labels for the stacked columns to the right of Education Institution are working. They appear to have a wrong centre point or something like that.

Now removing the `oversizedBehavior` changes it.

```js
            renderer.labels.template.setAll({
                // oversizedBehavior: "truncate",
                // maxWidth: 150,
                location: 0.5,
                textAlign: 'right'
            });
```

https://user-images.githubusercontent.com/2810/151845558-8d2cbdb1-6cbe-455d-89f8-f83d4c5de926.mov

This is a large complicated chart that can be configured to do many things so it could well be a setup issue of some sort, but this doesn't feel like it is.

**Comment by zeroin** [comment]
I've tried to reproduce something like this without luck, so I am afraid I can only help if you could provide a working codepen.

**Comment by buggedcom** [comment]
I've tried to get a reproducible case for you but even with every thing added to a codepen it works fine. However in this instance in my code, it is the presence of `textAlign: "right"` that causes this odd shifting behaviour.

Which is additionally weird in this instance because actually textAlign right does not appear to be having any affect anyway and everything is center aligned.

I'll leave this open for a little while to try to find a reproducible codepen combination.
