### ISSUE TITLE
How to create a dynamic maxWidth for xy chart column labels

### ISSUE THREAD

**Issue by buggedcom** [amcharts/amcharts5#253]
https://codepen.io/buggedcom/pen/JjOGLGG?editors=1010

If you resize the slider to "zoom in", my aim is to get the maxWidth and truncation (and possibly other properties) to dynamically update when the available space for the column changes according to the zoom in.

In the above pen, I have tried to do this, it's probably not the best way, but the main thing is that the `maxWidth` doesn't appear to update. exact portion of code is below.

```js
xAxis.get('renderer').labels.template.adapters.add('maxWidth', (value, target) => {
    const [a, b] = target.parent.children.values.map(c => [
        c.get('x'),
        c.get('oversizedBehavior')
    ])
        .filter(([, ob]) => ob === undefined)
        .map(([x]) => x)
        .slice(0, 2);
    const gridSize = Math.round(b-a);
    console.log(value, gridSize)
    return gridSize;
});
```

Is this on purpose? or a bug?

More over what would the best way to apply dynamic properties according to the "zoom" level of the chart?

**Comment by sassomedia** [comment]
I don't think the `maxWidth` would be changing, more like the `width` of the columns. Based on the `width` of the columns, you should be able to set the `maxWidth` of the label.

**Comment by buggedcom** [comment]
@sassomedia I'm trying to change the `maxWidth` though to prevent label overflow through truncation. This is basically what the code is doing above:

- finding all grid lines
- selecting the first to results
- calculating the distance between the two grid lines using their x position
- returning that distance as the `maxWidth` in the adapter

However the returned `maxWidth` has no effect.

**Comment by zeroin** [comment]
The problem is that the adapter doesn't set the maxWidth value on the element, so it is not marking this setting as dirty. And our code for a Label checks if it's dirty. So you can solve it by setting maxWidth on a target in your adapter:

`target.set("maxWidth", gridSize)`

**Comment by buggedcom** [comment]
Thanks @zeroin. 

Here is a codepen for people coming here looking for the same answer https://codepen.io/buggedcom/pen/WNXrBBz?editors=1010

**Comment by buggedcom** [comment]
@zeroin my solution for finding the width between the grid ticks does not work when the scrollbar is scrolled. What is the best way to calculate the width between grid items?

**Comment by zeroin** [comment]
Here it is:
https://codepen.io/team/amcharts/pen/bGYpKag??editors=1010

**Comment by buggedcom** [comment]
Thanks @zeroin , I noticed however that the columns that are "going out" or "coming in" from each side don't behave quite correctly. As ideally I don't think these labels should be truncated anymore than the max width of their column when fully on the screen.

https://user-images.githubusercontent.com/2810/152152943-b83413d0-d4cc-4b5b-b5e1-d67b57491c0c.mov

.

**Comment by zeroin** [comment]
Well this would require adjusting not only `maxWidth` but also position of the label, quite a lot of complicated math to calculate this properly.
