### ISSUE TITLE
OnClick event on BreadcrumbBar

### ISSUE THREAD

**Issue by gitramro** [amcharts/amcharts5#256]
I'm trying to make an event that executes some code when a click on the navigation

![image](https://user-images.githubusercontent.com/17560424/152234442-f63b1186-e95a-4c89-87d6-6c979c4f396d.png)

It's not working, this is what I'm trying to do

```javascript
 container2.children
      .unshift(
        am5hierarchy.BreadcrumbBar.new(root2, {
          series: series2,
        })
      )
      .events.on('click', (ev) => {
        console.log('clicked');
      });
```

I cant see the 'clicked' text anywhere

supposing there is a solution to make it work, I guess this will replace the original behavior, is there a way to have the original behavior and also a new behavior added in the handler?

**Comment by sassomedia** [comment]
You'd probably have to attach the event to the `BreadcrumbBar`, not the children. `unshift` is not supposed to return an object but `BreadcrumbBar` does:
```javascript
const breadcrumbBar = am5hierarchy.BreadcrumbBar.new(root2, { series: series2 });
breadcrumbBar.events.on('click', (ev) => {
  console.log('clicked');
});

container2.children.unshift(breadcrumbBar)
```
