### ISSUE TITLE
Plane id throwing error

### ISSUE THREAD

**Issue by DeepKarmakar** [amcharts/amcharts5#257]
I have plane within map, for that I used this code with an ID.

```JavaScript
let plane = am5core.Graphics.new(root, {

      id: "planeShape",
      svgPath:
        "m2,106h28l24,30h72l-44,-133h35l80,132h98c21,0 21,34 0,34l-98,0 -80,134h-35l43,-133h-71l-24,30h-28l15,-47",
      scale: 0.28,
      centerY: am5core.p50,
      centerX: am5core.p50,
      fill: am5core.color('#3b45b0')
    });
```

Now this map is coming on a popup, when I'm closing it and open it for 2nd time it's throwing this error. 
**Uncaught Error: An entity with id "planeShape" already exists.**

**Comment by martynasma** [comment]
If you are creating a new map anew every time you open the popup, you need to make sure you dispose the previous map using `dispose()` method on its `Root` element.

Better yet, create the map only once, so that you can show same map without the overhead of creating anew one.

**Comment by DeepKarmakar** [comment]
Got your point and it's working now. Thank you so much 👍
