### ISSUE TITLE
bug - y-axis is 'lost' on all values end up in straight line... might be related to updating chart data?

### ISSUE THREAD

**Issue by morrow95** [amcharts/amcharts5#262]
I came across this today and I can only assume it is some sort of bug in the amcharts code.  I cannot replicate it on demand and have yet to find anything consistent or similar when it happens - it is totally sporadic.

I am adding a new data point every 15 seconds to this chart with a total (integer) value on y-axis and a timestamp value for x-axis.  Sometimes it will run fine for 10-15 minutes and other times it will act up within a minute.

What happens is the y-axis labels disappear and all my points, regardless of their value, end up on the same y-axis line - as if all the values are the same, but they aren't.

I took some screenshots to show what happens.  As I said earlier this happens sporadically with no consistency at all.  I've watched it run fine for 15 minutes before bugging out.  Other times it happens within a minute.  Once it bugs out all future data points added just end up in the same y-axis line regardless of their value and the y-axis labels completely disappear.  There are no errors being reported in the console either.  The same code, using amcharts 4, does not have this issue (although the actual charting code for amcharts 4 is quite different) - I pass the same data, from the same source, and version 4 does not experience this.  I am quite confident this is some sort of bug in version 5.

As I can't replicate it on demand or find any similarities between when it happens (totally sporadic) I don't know if an example would do any good or not.  It does not matter if the page with the chart is 'on' my screen or running in the background of the browser either.  Does not happen after a set amount of data points or time has passed.  I can't find or think of anything consistent that occurs when it bugs out like this.

In this example the first data point shows correctly and then when the second is added the bug happens.  Other times I've added 30-40+ data points before this occurs.  The first image is the first data point shown correctly and the following show when the y-axis disappears and points are shown incorrectly.  All the points are different values in these pictures yet show straight across.  Note the 'zoom' button also shows by itself when the bug happens, but clicking on it does nothing.

![chart-bug](https://user-images.githubusercontent.com/626244/152482844-807f6bc7-a593-44ff-820e-584521765088.jpg)

If you have any ideas please pass them on.  Do I need to be using `markDirtyValues()` on my y-axis?  And if so, why is it not consistent when it 'breaks' and this bug happens?  I'm at a loss what is causing this to happen.

**EDIT :** I am using amcharts-5.1.2 when this occurs.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by morrow95** [comment]
@martynasma I'll come up with something to replicate the same code we are using today when I have time.  Hopefully the same issue occurs in that environment.

**Comment by morrow95** [comment]
@martynasma  I was able to duplicate the behavior and code in codepen and luckily this problem still happens, but as I said earlier sometimes it will go for minutes or more before it happens and other times it is almost immediate.

[https://codepen.io/scubapongo/pen/GROjwyj](https://codepen.io/scubapongo/pen/GROjwyj)

Here is a screenshot after it happened in codepen : 
![chart-bug2](https://user-images.githubusercontent.com/626244/152621006-e8099023-cea1-439d-bbec-acab14ea98b8.jpg)

**Comment by martynasma** [comment]
Thanks for the CodePen.

This seems to have caused by you having set `maxZoomFactor: 0` on both axes, which does not make a lot of sense. It just causes the scale of the axis to reset to zero whenever new value comes into play that requires re-scaling the axis.

Just remove those lines from your chart config to fix.

**Comment by morrow95** [comment]
Without that the 'zoom' button would keep showing on its own in the chart.  I want to prevent that from happening and not allow zooming of any kind.  Is there no way to prevent that?

**Comment by martynasma** [comment]
How about just disabling zoom button?

```JavaScript
chart.zoomOutButton.set("forceHidden", true);
```

**Comment by morrow95** [comment]
Was able to make it work this way.
