### ISSUE TITLE
Problem with XYChart mouse events

### ISSUE THREAD

**Issue by ghost** [amcharts/amcharts5#263]
In amCharts 5, for example 'pointerout' event on XYChart is fired each time when pointer is moved over some element contained in a chart. In amCharts 4 it was fired only when pointer was really out of the chart.
I also have similar problem with 'click' event on XYChart. It often doesn't fire when I'm clicking on some places in the chart and I have to click a few times to trigger it.
Is is a bug or I am missing some configuration?

**Comment by martynasma** [comment]
Neither of described things should be happening, and I don't thing they do.

If you found a place where it happens, can you please post a CodePen/jsFiddle so that we can test?
