### ISSUE TITLE
Dynamic Map position depend on points

### ISSUE THREAD

**Issue by DeepKarmakar** [amcharts/amcharts5#264]
I have two points in map and have homeZoomLevel: 10, Is there any way so that the map points will come center of view port automatically on first load? here is the [StackBlitz](https://stackblitz.com/edit/angular-ivy-yxxwd9?file=src%2Fapp%2Fapp.component.ts)

**Comment by martynasma** [comment]
You can use `homeGeoPoint` to specify lat/long coordinates to center the map on when it loads.

https://www.amcharts.com/docs/v5/charts/map-chart/map-pan-zoom/#Initial_position_and_zoom

**Comment by martynasma** [comment]
Well, then you should use a lat/long that is roughly center between the two points.
