### ISSUE TITLE
Can't center content inside container.

### ISSUE THREAD

**Issue by rferreira98** [amcharts/amcharts5#265]
Trying to use a container, with 2 labels and a button inside.
`const container = root.tooltipContainer.children.push(am5.Container.new(root,
            {
                layout: root.verticalLayout,
                x: am5.p50,
                y: am5.p50,
                centerX: am5.p50,
                centerY: am5.p50
            }
        ));
        const label1 = am5.Label.new(root,
            {
                text: "5 %",
                fontSize: 40,
            }
        );
        const label2 = am5.Label.new(root,
            {
                text: "Zero engagement",
                fontSize: 16,
                fill: am5.color(0xB2BEB5)
            }
        );

        const button = am5.Button.new(root, {
            label: am5.Label.new(root, {
                text: "See all",
                fontWeight: 600
            }),
            cursorOverStyle: "pointer",
            background: am5.Rectangle.new(root, {
                fill: am5.color(0x000000),
                fillOpacity: 0.9,
            })
        });
        container.children.push(label1);
        container.children.push(label2);
        container.children.push(button);`
        
Instead of having the container with centered elements inside, but some they appear to be left aligned instead of center aligned.

![Screen Shot 2022-02-04 at 11 10 22](https://user-images.githubusercontent.com/24259712/152521775-97a007c9-6736-47bb-ae85-2c36444dc5e6.png)

**Comment by martynasma** [comment]
Try setting `centerX: am5.p50` and `x: am5.p50` on all labels as well.

**Comment by rferreira98** [comment]
> Try setting `centerX: am5.p50` and `x: am5.p50` on all labels as well.

`centerX: am.p50`
Worked like a charm. What I think was the problem is that those properties need to be set equally in all of the elements inside the container, else they'll misalign.

`const container = root.tooltipContainer.children.push(am5.Container.new(root,
            {
                layout: root.verticalLayout,
                x: am5.p50,
                y: am5.p50,
                centerX: am5.p50,
                centerY: am5.p50
            }
        ));
        const label1 = am5.Label.new(root,
            {
                text: "5%",
                fontSize: 40,
                lineHeight: 1,
                paddingBottom: 10,
                centerX: am5.p50
            }
        );
        const label2 = am5.Label.new(root,
            {
                text: "Zero engagement",
                fontSize: 15,
                lineHeight: 1,
                paddingTop: 0,
                fill: am5.color(0xB2BEB5),
                centerX: am5.p50
            }
        );

        const button = am5.Button.new(root, {
            label: am5.Label.new(root, {
                text: "See all",
                fontWeight: 600
            }),
            cursorOverStyle: "pointer",
            background: am5.Rectangle.new(root, {
                fill: am5.color(0x000000),
                fillOpacity: 0.9,
            }),
            centerX: am5.p50
        });
        container.children.push(label1);
        container.children.push(label2);
        container.children.push(button);
`
