### ISSUE TITLE
How to get cursor vertical line to snap to datapoints

### ISSUE THREAD

**Issue by aymather** [amcharts/amcharts5#267]
Here's the [codepen](https://codepen.io/aymather/pen/KKyNNap?editors=0010) associated with my question.

My goal is to get the vertical line (that shows up as a result of the cursor hover) to snap to points on the xAxis. According to the [documentation](https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/) it says that I should be able to set 2 properties of the `am5xy.XYCursor` object like so:

```
var cursor = chart.set("cursor", am5xy.XYCursor.new(root, {
  behavior: "none",
  snapToSeries: chart.series.values,
  snapToSeriesBy: 'x'
}));
```

As you'll see in my codepen, I do this on lines 108-109. However, the vertical line is still not snapping to the datapoints.

The example I've used in my codepen was taken from one of the [demos](https://www.amcharts.com/demos/highlighting-line-chart-series-on-legend-hover/).

Another solution I saw somewhere in the docs is to just assign the `xAxis` property, but I also tried that and that didn't work either.

```
var cursor = chart.set("cursor", am5xy.XYCursor.new(root, {
  behavior: "none",
  xAxis
}));
```

Am I doing this completely wrong? How do I get that vertical line to snap to points?

**Comment by martynasma** [comment]
If you need the vertical line to also snap, you need to enable snapping of cursor to axis:
https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/#snapping-to-axis-cells

**Comment by aymather** [comment]
Yeah I mean that's the same documentation that I linked as well, which is why I'm asking the question. Because I followed the documentation and I'm still not getting the result. I linked a [codepen](https://codepen.io/aymather/pen/KKyNNap?editors=0010) with an attempted implementation of the docs, if I'm doing something wrong in that implementation could you let me know what that is specifically?

**Comment by martynasma** [comment]
As per the link above, you need to set `xAxis` on the cursor for it to snap to cells:

```JavaScript
var cursor = chart.set("cursor", am5xy.XYCursor.new(root, {
  behavior: "none",
  snapToSeries: chart.series.values,
  snapToSeriesBy: 'x',
  xAxis: xAxis // <-- you're missing this
}));
```

**Comment by aymather** [comment]
Oh wow, I really thought I tried both at the same time.. but I guess not.. that fixed the issue, thank you!
