### ISSUE TITLE
Looking for a feature: bar chart with time evolution

### ISSUE THREAD

**Issue by mehdichaouch** [amcharts/amcharts5#269]
Hello,

With this [sample data](https://github.com/mehdichaouch/election-presidentielle-francaise/blob/main/data/parrainagessum.json), I'm looking to do a bar chart like [this one](https://www.amcharts.com/demos/columns-with-moving-bullets/), but I also need to add a scrollbar to see ranking evolution date after date, with specified dates like 21 jan, 23 jan, 26 jan, 27 jan, 30 jan, 31 jan...

_Here is an exemple of what I'm looking for:_
![image](https://user-images.githubusercontent.com/861701/152715583-ee22c69c-da1e-490b-bb4e-f4e8c534f287.png)
Or like here in [Excel](https://youtu.be/qCLfhwLHRPc?t=397).

Do you think that is possible and is there a demo like this?

Thank you 🙏

**Comment by martynasma** [comment]
Gere's a good similar example:
https://www.amcharts.com/demos/radar-timeline/

It uses `RadarChart`, but it would work exactly the same way on an `XYChart`:

You watch for slider events, then update data on series accordingly.

**Comment by mehdichaouch** [comment]
@martynasma thank you for anwser.
As I understand radar chart is just to ilustrate, what I need to focus on this example is the timeline?
If you look this [video](https://youtu.be/qCLfhwLHRPc?t=397), you see you have the step by step where each gap is a year.
Do you know a place with this kind of graph? Or maybe a better keyworks to found help?

**Comment by martynasma** [comment]
OK, so you just need to add scrollbar to chart and pre-zoom to several categories.

https://www.amcharts.com/docs/v5/charts/xy-chart/scrollbars/
https://www.amcharts.com/docs/v5/charts/xy-chart/zoom-and-pan/#Pre_zooming_axes

**Comment by mehdichaouch** [comment]
Oh I found this [Dynamic_updates for v4](https://www.amcharts.com/docs/v4/concepts/data/#Dynamic_updates), is that similar in v5?
I also see [Updating_existing_data for v5](https://www.amcharts.com/docs/v5/concepts/data/#Updating_existing_data), maybe it can update [Columns with Moving Bullets](https://www.amcharts.com/demos/columns-with-moving-bullets/)?

**Comment by sassomedia** [comment]
In v5, similar would be setting new data with `setAll`: https://www.amcharts.com/docs/v5/concepts/data/#Setting_data.

In order to get a similar effect as in the Excel video, I would create an external scrollbar (not the one that's built into amCharts). Then use the scrollbar events to grab new sets of data and trigger the `setAll` method with new data.
