### ISSUE TITLE
Zoom-out button visibility documentation error

### ISSUE THREAD

**Issue by samkristoff** [amcharts/amcharts5#27]
On the [Zoom and pan page](https://www.amcharts.com/docs/v5/charts/xy-chart/zoom-and-pan/#Zoom_out_button) it says to use the following to hide the zoom-out button:

![image](https://user-images.githubusercontent.com/1994983/135662360-a232895d-2d36-43eb-8360-e01fabfe505f.png)

This property appears to exist (setting it doesn't throw an error and in TS the typings suggest it exits) but setting it does not affect the button visibility.  

Using **setPrivate** seems to work. ex:
```
chart.zoomOutButton.setPrivate("visible", false);
```

**Comment by martynasma** [comment]
Thanks for the heads up!

It's better to use this:

```JavaScript
chart.zoomOutButton.set("forceHidden", true);
```

Docs updated.
