### ISSUE TITLE
strokeWidth in custom theme does affect series

### ISSUE THREAD

**Issue by aniznik1** [amcharts/amcharts5#270]
This codepen I found on the tutorial [page](https://www.amcharts.com/docs/v5/concepts/themes/creating-themes/#Theme_tags)  does not seem to work when changing the default `strokeWidth`. 

[https://codepen.io/team/amcharts/pen/vYmepgG](https://codepen.io/team/amcharts/pen/vYmepgG)

I would expect the LineSeries to have the corresponding stroke width.

**Comment by martynasma** [comment]
Thanks for the heads up.

CodePen was missing some tags. The following should work:

```JavaScript
class MyTheme extends am5.Theme {
  setupDefaultRules() {
    this.rule("Graphics", ["line", "series", "stroke"]).setAll({
      strokeWidth: 2,
      strokeDasharray: [10, 5]
    })
  }
}
```
