### ISSUE TITLE
XYChart autoscaling not working when hiding series via legend

### ISSUE THREAD

**Issue by mikuni123** [amcharts/amcharts5#271]
In amcharts5 there is dynamic autoscaling of y axis values that sometimes (when values are big enough) results in not showing the 0 value on axis. In my case I have to always show 0 value so as a workaround I implemented solution mentioned in the documentation with additional condition check for negative values:
```
series.events.on("datavalidated", function() {
    yAxis.setAll({
      min: yAxis.getPrivate("min") >= 0 ? 0 : yAxis.getPrivate("min"),
      max: yAxis.getPrivate("max") <= 0 ? 0 : yAxis.getPrivate("max")
    });
  });
```
The problem is that when hiding series via legend the y axis **does not autoscale**, how should I implement similar solution like above in this case in order to trigger autoscaling? 
Here is codepen with live example https://codepen.io/mikuni123/pen/abVpzXd - after disabling second series with negative values the "min" value should become 0 and the "max" value should be autoscaled to max value from first series.

**Comment by sassomedia** [comment]
Hmm, that's a bit tricky but maybe something like this could work?
https://codepen.io/sassomedia/pen/QWOdVEa?editors=0010

**Comment by mikuni123** [comment]
I think that this solution doesn't cover all cases, for example disabling "Asia" then disabling "Europe" and then bringing back "Europe" results in broken scale and missing 0 value. However, in my real implementation I use custom html legend so I can't use the proposed `initMin` parameter as my chart doesn't reload when I disable an item. Here comes one more question - is it possible to trigger chart reload so that private properties like "min" or "max" can also be reloaded?

**Comment by sassomedia** [comment]
Well, this is an example approach, I'm sure you can figure out the rest of the cases.

You're saying that your legend is completely separate from the chart? Not in an external container as described here: https://www.amcharts.com/docs/v5/concepts/legend/#external-container?
In that case, you could just [set the data](https://www.amcharts.com/docs/v5/concepts/data/#Setting_data) on the respective series to have the chart redraw. You basically would create two data sets for each series. One with actual data and the other with "disabled" data where all values are just 0. Based on your external legend triggers, you can just set the appropriate data on each series and you should get the dynamic scaling.

**Comment by zeroin** [comment]
You can solve this by adding an axis range to y axis and telling it that it should affect min  and max:
```
var dataItem = yAxis.makeDataItem({});
dataItem.set("value", 0);
dataItem.set("affectsMinMax", true);
```

This is quite fresh feature (the `affectsMinMax` setting, so be sure to use latest version.
