### ISSUE TITLE
Alpha channels on colors?

### ISSUE THREAD

**Issue by jonofoz** [amcharts/amcharts5#272]
Hi again :)

In AMCv4, I was able to apply alpha to different colors through `rgba(n,n,n,n)`; is that not the case with AMCv5? From the docs I read here, it seems alpha isn't supported:
https://www.amcharts.com/docs/v5/reference/color/

Am I just looking in the wrong place? If alpha isn't available at the moment, are there any plans to implement it at a later time? It might be a limitation of the Canvas API, I'm not sure myself. ¯\_(ツ)_/¯

Cheers!

**Comment by lancegliser** [comment]
Would the [`fromCss`](https://www.amcharts.com/docs/v5/reference/color/#fromCSS_method) method work?
```
Color.fromCSS("rgba(255, 0, 0, 1)") // red
```

**Comment by jonofoz** [comment]
Thanks for your help, guys! <3 `fillOpacity` and `strokeOpacity` should work perfectly.
