### ISSUE TITLE
Adding a Tooltip to an Axis Title

### ISSUE THREAD

**Issue by keegandonley** [amcharts/amcharts5#273]
I'm attempting to add a tooltip to my y-axis title. 

I've found this documentation on label tooltips: https://www.amcharts.com/docs/v5/concepts/common-elements/labels/#interactive-axis-labels, and this documentation on axis titles: https://www.amcharts.com/docs/v5/concepts/common-elements/labels/#interactive-axis-labels, however I can't find anything explaining how to put the tooltip on the axis title created. 

Currently, I'm attempting it as such with no luck:
```javascript
    const displayTitle = shouldTruncate
      ? `${this.yAxisTitle.slice(0, 40)}...`
      : this.yAxisTitle;

    const label = am5.Label.new(this.root, {
      rotation: -90,
      text: displayTitle,
      y: am5.p50,
      centerX: am5.p50,
      background: am5.Rectangle.new(this.root, {
        fill: color(grayScale.medium)
      }),
      tooltip: am5.Tooltip.new(this.root, {
        pointerOrientation: 'left'
      }),
      tooltipText: this.yAxisTitle
    });

    this.yAxis.children.unshift(label);
```

**Comment by xorspark** [comment]
Weird, your code seems to work fine for me [here](https://codepen.io/team/amcharts/pen/BampYwM/36e0cb89d9d0a02c8f8a000b919b34fc?editors=0010).

![image](https://user-images.githubusercontent.com/2679427/152908355-65fddf18-54de-4d11-a9d7-960d1b89043d.png)

**Comment by keegandonley** [comment]
@xorspark weird indeed. Thanks for the reproduction; I'll go through my chart carefully and compare it to make sure I'm not doing anything wrong that might be conflicting or causing a problem.

**Comment by keegandonley** [comment]
Took a closer look, turns out this was due to Brave browser's shields being up and trying to prevent user fingerprinting
