### ISSUE TITLE
Chart Zoom Out Button Not Clickable

### ISSUE THREAD

**Issue by keegandonley** [amcharts/amcharts5#274]
I'm having an issue where the zoom-out button is not clickable on a chart. 

```javascript
 this.chart.set(
      'cursor',
      am5xy.XYCursor.new(this.root, {
        behavior: 'zoomX'
      })
    );
```

The zoom out button shows up, but doesn't change styles on hover and isn't clickable:
<img width="219" alt="Screen Shot 2022-02-07 at 1 03 57 PM" src="https://user-images.githubusercontent.com/12700819/152854759-a094ae3f-5856-4054-955b-755fdbe3c38a.png">

**Comment by xorspark** [comment]
Could you share more details about your environment/browser version where you're able to reproduce this? The zoom out button changes styles and is clickable for me on the latest versions of Firefox and Chrome in [this codepen](https://codepen.io/team/amcharts/pen/jOayZyj/0764eab87d3e883f32316b2b89b5927a?editors=0010).

**Comment by keegandonley** [comment]
@xorspark Sure, tomorrow I'll try to make a smaller reproduction and see if I can pin it down. FWIW I'm using Brave instead of Chrome but AFAIK there shouldn't be any discernible difference.

**Comment by keegandonley** [comment]
Weirdly enough, this is an issue with Brave's shields. If I turn off the shields, the button is clickable, but with them on it's no longer interactive. It's specifically the fingerprinting protection that is causing a problem. I suppose this is no longer an issue with amcharts, but I'm curious exactly what behavior is being blocked.

**Comment by oliverlj** [comment]
Related to block fingerprinting feature of brave

![image](https://user-images.githubusercontent.com/1826498/166427686-8cc16dbf-c637-4b77-a0f2-8fdcd9211c86.png)
