### ISSUE TITLE
tooltipText padding inside tooltip

### ISSUE THREAD

**Issue by barrygwhite** [amcharts/amcharts5#275]
Hi, is there a way to set tooltipText padding inside tooltip? 
![tooltip](https://user-images.githubusercontent.com/10283897/152854063-43f9ea3c-a48c-4401-9ef4-762bc1522531.png)

I would like to be able to manipulate position of text - for example close to left border, center or right border. 
I know there are some options for label but what about tooltipText itself?

````
var tooltipText = '[#5B6372 fontSize: 13 fontFamily: Poppins fontWeight: 600]Text1[/]
		[#4AC748 fontSize: 13 fontFamily: Poppins fontWeight: 600]{name}[/]
		[#5B6372 fontSize: 13 fontFamily: Poppins fontWeight: 600]{category}[/]
		[#4AC748 fontSize: 13 fontFamily: Poppins fontWeight: 600]{firstValue}[/]
		[#5B6372 fontSize: 13 fontFamily: Poppins fontWeight: 600]{secondCategory}[/]
		[#4AC748 fontSize: 13 fontFamily: Poppins fontWeight: 600]{secondValue}[/]';
		
var testTemplate = am5.Template.new({
		tooltipText: tooltipText
	  });

````		
It's based on this one -> https://codepen.io/team/amcharts/pen/gOGwgZO?editors=1011

**Comment by sassomedia** [comment]
For more control over layout inside a tooltip, I would use containers with labels inside of them:
https://www.amcharts.com/docs/v5/concepts/common-elements/containers/#Layout

You can position and arrange them in any way you need. It's a bit boilerplate-y but it works.

**Comment by martynasma** [comment]
What @sassomedia said.

Or, if it's truly just about padding of the tooltip contents, you can use padding settings of the tooltip's label, e.g.:

```JavaScript
series.get("tooltip").label.setAll({
  paddingTop: 20,
  paddingRight: 20,
  paddingBottom: 20,
  paddingLeft: 20,
})
```
