### ISSUE TITLE
What is the common between creating custom themes in v4 and in v5?

### ISSUE THREAD

**Issue by someden** [amcharts/amcharts5#276]
Are there settings that still have the same names?
Could you add some tips about this to your migration guide?

**Comment by martynasma** [comment]
There's nothing common between themes in both versions, I'm afraid.

I suggest you follow tutorial on creating themes for amCharts 5, as there is no way to automatically convert v4's themes:

https://www.amcharts.com/docs/v5/concepts/themes/creating-themes/

**Comment by someden** [comment]
Understood, thanks
