### ISSUE TITLE
How to get `start` and `end` position on `selectended`?

### ISSUE THREAD

**Issue by someden** [amcharts/amcharts5#281]
With v4 it was:
```
cursor: {
  behavior: 'selectX',
  events: {
    selectended: (ev) => console.log(ev.target.xRange.start, ev.target.xRange.end),
  },
},
```

How it will looks like with v5?

**Comment by martynasma** [comment]
You can use `selectedstarted` to log cursor's `positionX`. Then `selectended` to grab end `positionX`, so you know the range.

Then you you can use related axis' methods to convert position into actual values (category, value, date, etc.).

More info here:
https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/#events
https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/#tracking-cursor-movement

**Comment by someden** [comment]
Is there some way to get range using just one event/callback?
Because in your example we need to store `positionX` somewhere outside `started` callback and then get it in another `ended` callback.

**Comment by martynasma** [comment]
That's because we don't consider selection started until cursor moved some pixels after down. This is to avoid triggering selection event on simple clicks.

It shouldn't be too much difference between `downPositionX` and `positionX` on `selectstarted` event.
