### ISSUE TITLE
How to limit only one active slice per Pie chart?

### ISSUE THREAD

**Issue by AComasSamcla** [amcharts/amcharts5#283]
Hi, already opened this question on stackoverflow but no answers:
https://stackoverflow.com/questions/70956215/how-to-limit-only-one-active-slice-per-pie-chart-on-amcharts5

Basically I want to migrate this v4 code to v5: https://www.amcharts.com/docs/v4/tutorials/one-pulled-slice-per-pie-chart/

Is it possible? v5 has very few tutorials at this time.

Thanks

**Comment by martynasma** [comment]
Just posted similar tutorial for amCharts  5 here:
https://www.amcharts.com/docs/v5/tutorials/one-pulled-slice-per-pie-series/

Enjoy :)

**Comment by AComasSamcla** [comment]
Awesome! That's it, thank you
