### ISSUE TITLE
Where can I find default settings? For example, for paddings?

### ISSUE THREAD

**Issue by someden** [amcharts/amcharts5#284]
Where can I find default settings? For example, for paddings?
Didn't find it in docs:
![Screenshot 2022-02-14 at 19 03 42](https://user-images.githubusercontent.com/7009699/153900449-39ea9b16-9b42-4951-b4e6-40f85478022a.png)

But it looks like it's not zero paddings.

**Comment by martynasma** [comment]
Most of defaults are in the `DefaultTheme`:
https://github.com/amcharts/amcharts5/blob/master/src/.internal/themes/DefaultTheme.ts

Additional XY chart defaults are here:
https://github.com/amcharts/amcharts5/blob/master/src/.internal/charts/xy/XYChartDefaultTheme.ts

Though, `Container` does not have any default padding. Some other elements that extend it might have it.

You may also need to read how theme rules work:
https://www.amcharts.com/docs/v5/concepts/themes/creating-themes/#rules
