### ISSUE TITLE
amcharts5: amchart4 code to amchart5

### ISSUE THREAD

**Issue by snasir3** [amcharts/amcharts5#288]
Hi @martynasma @amcharts  , Could the below be converted in amcharts5 please? Much appreciated!
chart.legend.itemContainers.template.togglable = false;

chart.legend.itemContainers.template.events.on("hit", function(event){
var target = event.target;
var switching = target.isActive;
chart.legend.itemContainers.each(function(item) {
var series = item.dataItem.dataContext;
if (item.dataItem == target.dataItem || (item.isActive && !switching)) {
item.isActive = false;
series.show();
}
else {
item.isActive = true;
series.hide();
}
})
});

**Export Menu** 

Please could someone help me convert the below amcharts4 export menu code to amcharts5 please. It's really urgent.
Amcharts4 code version:
const chartExportMenu = [
{
label: '...',
menu: [
{
label: 'Image',
menu: [
{ type: 'png', label: 'PNG' },
{ type: 'jpg', label: 'JPG' },
{ type: 'svg', label: 'SVG' },
],
}, {
label: 'Data',
menu: [
{ type: 'json', label: 'JSON' },
{ type: 'csv', label: 'CSV' },
{ type: 'xlsx', label: 'XLSX' },
],
},
],
},
]
chart.exporting.menu = new am4core.ExportMenu()
chart.exporting.menu.items = chartExportMenu

**Comment by snasir3** [comment]
hi, could please covert the amcharts4 code to amcharts5 pls? when i tried to convert the above i wasn't able to

**Comment by snasir3** [comment]
Hey @amcharts, @sassomedia @martynasma,
I was trying randomly beecause I don't know how i can convert it. so i deleted and created this issue to get some help. I don't know how I can convert the above amchart 4 code into amchart 5.Therefore need some help here please. I have pasted what I have below. 

for example:

**Legend filter**
works with amchart4 but I am using amchart5 for some charts and don't know how this can be converted into amchart5 so that it works with amchart5 lib.

chart.legend.itemContainers.template.togglable = false;

chart.legend.itemContainers.template.events.on("hit", function(event){
var target = event.target;
var switching = target.isActive;
chart.legend.itemContainers.each(function(item) {
var series = item.dataItem.dataContext;
if (item.dataItem == target.dataItem || (item.isActive && !switching)) {
item.isActive = false;
series.show();
}
else {
item.isActive = true;
series.hide();
}
})
});
------**legend amchart5**-------

Here's the legend code in amchart5. I want this to work same as amchart4 code above

    const legend = chart.children.push(am5.Legend.new(root, { clickTarget: 'none' }))
    legend.data.setAll(chart.series.values)



-------
**Same goes for Export menu** 

Amcharts4 code version:
const chartExportMenu = [
{
label: '...',
menu: [
{
label: 'Image',
menu: [
{ type: 'png', label: 'PNG' },
{ type: 'jpg', label: 'JPG' },
{ type: 'svg', label: 'SVG' },
],
}, {
label: 'Data',
menu: [
{ type: 'json', label: 'JSON' },
{ type: 'csv', label: 'CSV' },
{ type: 'xlsx', label: 'XLSX' },
],
},
],
},
]
chart.exporting.menu = new am4core.ExportMenu()
chart.exporting.menu.items = chartExportMenu

---------- **Amchart 5 Export code** ---------
Currently i got only this line of code but how i can i make to work same as amchart4 code above.

 const exporting = am5exporting.Exporting.new(root, { menu: am5exporting.ExportingMenu.new(root, {}) })

**Comment by martynasma** [comment]
@snasir3 The following documentation explains on how to customize menu items:
https://www.amcharts.com/docs/v5/concepts/exporting/export-menu/#Customizing_menu_items

Hope you find it useful.

**Comment by snasir3** [comment]
@martynasma  firstly thanks a lot!
I have got this far but this dosen't show options for label  image and Data. Could you please inform me where i have gone wrong and also please assist me with the legend as well. Thanks kindly! I really need to complete this task on time please.

const exporting = am5exporting.Exporting.new(
      root, { menu: am5exporting.ExportingMenu.new(root, {}) },
    )
    exporting.get('menu').set('items', [{
      label: 'Image',
      menu: [
        { type: 'format', format: 'png', label: 'PNG' },
        { type: 'format', format: 'jpg', label: 'JPG' },
        { type: 'format', format: 'svg', label: 'SVG' },
      ],
    },
    {
      label: 'Data',
      menu: [
        { type: 'format', format: 'json', label: 'JSON' },
        { type: 'format', format: 'csv', label: 'CSV' },
        { type: 'format', format: 'xlsx', label: 'XLSX' },
      ],
    }])

    exporting.get('menu').close()

**Comment by martynasma** [comment]
I don't think you've read the documentation carefully. Take a look on how "items" data should be structured:

https://www.amcharts.com/docs/v5/concepts/exporting/export-menu/#Completely_custom_menu

**Comment by snasir3** [comment]
ok so with this code as suggested in the documentation 
const exporting = am5exporting.Exporting.new(
      root, { menu: am5exporting.ExportingMenu.new(root, {}) },
    )
    exporting.get('menu').set('items', [
      { type: 'format', format: 'png', label: 'PNG' },
      { type: 'format', format: 'jpg', label: 'JPG' },
      { type: 'format', format: 'svg', label: 'SVG' },
      { type: 'separator' },
      { type: 'format', format: 'json', label: 'JSON' },
      { type: 'format', format: 'csv', label: 'CSV' },
      { type: 'format', format: 'xlsx', label: 'XLSX' },
    ])
I get 
<img width="123" alt="Screenshot 2022-02-16 at 10 30 02" src="https://user-images.githubusercontent.com/81321771/154246289-fa50b55c-185f-40c1-9727-ca2ca63c28b8.png">
whereas i am looking to achieve 
<img width="110" alt="Screenshot 2022-02-16 at 10 30 36" src="https://user-images.githubusercontent.com/81321771/154246332-4c67a5ff-c08a-40d5-a81e-47bdab6ba185.png">

**Comment by martynasma** [comment]
amCharts 5 export menu does not support nested items, I'm afraid.

**Comment by snasir3** [comment]
Could you inform me why this doesn't show all the menu items 
exporting.get('menu').set('items', [
{ type: 'format', format: 'png', label: 'PNG' },
{ type: 'format', format: 'jpg', label: 'JPG' },
{ type: 'format', format: 'svg', label: 'SVG' },
{ type: 'separator' },
{ type: 'format', format: 'json', label: 'JSON' },
{ type: 'format', format: 'csv', label: 'CSV' },
{ type: 'format', format: 'xlsx', label: 'XLSX' },
])

**Comment by snasir3** [comment]
Hey, could you help me with legend please? Really appreciate your help!!

**Comment by snasir3** [comment]
@martynasma @sassomedia @amcharts 
Is it possible to add scroll bar in the export menu becuase it appears like this 
<img width="104" alt="Screenshot 2022-02-16 at 11 50 03" src="https://user-images.githubusercontent.com/81321771/154259107-8638bf3a-12e4-4633-be50-58e4e6082fe6.png">

**Comment by martynasma** [comment]
I think it's possible by adding your own custom CSS.

More details here:
https://www.amcharts.com/docs/v5/concepts/exporting/export-menu/#Appearance

**Comment by snasir3** [comment]
@martynasma @sassomedia 
Any update on this please 

**Legend filter**
works with amchart4 but I am using amchart5 for some charts and don't know how this can be converted into amchart5 so that it works with amchart5 lib.

chart.legend.itemContainers.template.togglable = false;

chart.legend.itemContainers.template.events.on("hit", function(event){
var target = event.target;
var switching = target.isActive;
chart.legend.itemContainers.each(function(item) {
var series = item.dataItem.dataContext;
if (item.dataItem == target.dataItem || (item.isActive && !switching)) {
item.isActive = false;
series.show();
}
else {
item.isActive = true;
series.hide();
}
})
});
------legend amchart5-------

Here's the legend code in amchart5. I want this to work same as amchart4 code above

const legend = chart.children.push(am5.Legend.new(root, { clickTarget: 'none' }))
legend.data.setAll(chart.series.values)

**Comment by martynasma** [comment]
Let's not mix multiple unrelated questions in a single issue. Please post a separate issue.

Thank you for understanding.
