### ISSUE TITLE
Can't guarantee xAxis scope on resize

### ISSUE THREAD

**Issue by rferreira98** [amcharts/amcharts5#289]
I want to show data from last 6 months. On resize the line chart shows labels from 1 or 2 months and not the 6 I want.

Expected (on any resolution):
![Screen Shot 2022-02-16 at 14 30 36](https://user-images.githubusercontent.com/24259712/154285893-fe889bec-329c-4f83-9c08-08c05601b237.png)

What I got on smaller resolution:
![Screen Shot 2022-02-16 at 14 31 00](https://user-images.githubusercontent.com/24259712/154285944-6e4d64ac-b28b-4cb1-af0a-7d366044580e.png)

**Comment by martynasma** [comment]
Please read here:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#grid-density

**Comment by rferreira98** [comment]
> Please read here: https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#grid-density

It does solve the problem.
Just wondering if I understood it right, by changing this setting we're saying the grid lines need to have a specific number of pixels between them which means they cant overlap each other?

**Comment by martynasma** [comment]
No. It means minimum number of pixels to have between grid lines. Axis renderer will choose grid granularity in such a way that ensures grid lines are never closer than `minGridDistance` pixels.

**Comment by rferreira98** [comment]
For example, in order to maintain the 20% step on the left yAxis. Is there a way besides minGridDistance?

**Comment by martynasma** [comment]
> For example, in order to maintain the 20% step on the left yAxis. Is there a way besides minGridDistance?

Automatically, no.

You could disable grid/labels, and place axis range(s) on precisely the values you want it appear on, though.

https://www.amcharts.com/docs/v5/charts/xy-chart/axes/axis-ranges/

**Comment by rferreira98** [comment]
Thank you!
