### ISSUE TITLE
Wrong documentation for Axes

### ISSUE THREAD

**Issue by MurhafSousli** [amcharts/amcharts5#29]
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#Basic_location

I am using `"@amcharts/amcharts5": "^5.0.0-beta.29"`

The code shown in the documentation does not work, there is no `gridTemplate` property on the `xRenderer`
```ts
let xRenderer = xAxis.get("renderer");
xRenderer.gridTemplate.setAll({
  location: 0.5
});
```

The following is correct

```ts
xAxis.get('renderer').grid.template.setAll({
   location: 0.5
});
```

**Comment by martynasma** [comment]
Oops, I'm not sure how this early syntax (replaced before v5 went into Beta) managed to slip through the cracks in the docs.

The doc is now fixed with correct syntax.

Thanks for the heads up!
