### ISSUE TITLE
Lazy Loading in AmCharts 5 

### ISSUE THREAD

**Issue by mburaksayici** [amcharts/amcharts5#290]
Hi,
Is lazy loading available for Amcharts 5 for React? Or, are there any option to put a delay of loading to each graph, in pages that contains multiple graphs?
It's not well documented yet.

**Comment by martynasma** [comment]
There's no lazy-loading or daisy-chaining functionality available in amCharts 5, I'm afraid.

Those features were introduced in amCharts 4, to fight multi-chart performance issues. amCharts 5 is equipped to cope with such situations much better, and generally lazy-loading is not required in most setups.
