### ISSUE TITLE
Amchart 5: legends

### ISSUE THREAD

**Issue by snasir3** [amcharts/amcharts5#292]
Hi @martynasma @amcharts, 

Could the below be converted in amcharts5 please? Much appreciated!
chart.legend.itemContainers.template.togglable = false;

chart.legend.itemContainers.template.events.on("hit", function(event){
var target = event.target;
var switching = target.isActive;
chart.legend.itemContainers.each(function(item) {
var series = item.dataItem.dataContext;
if (item.dataItem == target.dataItem || (item.isActive && !switching)) {
item.isActive = false;
series.show();
}
else {
item.isActive = true;
series.hide();
}
})
});

**amcharts 5 code for legend** 

    const legend = chart.children.push(am5.Legend.new(root, {}))
    legend.data.setAll(chart.series.values)

**Comment by snasir3** [comment]
Hi @martynasma @amcharts,

Please could you look into this issue?

**Comment by martynasma** [comment]
I suppose you're looking for this:
https://www.amcharts.com/docs/v5/tutorials/show-only-one-series-at-a-time/

**Comment by snasir3** [comment]
@martynasma 
No, same as you suggested before for amcharts4 but i need it in amcharts 5 for some charts 
**The goal is** 

> when you first click on the legend it only shows data for that legnd and hide other legends
> clicking the same legend reset everything

Question is how I can turn the below into amcharts5 please

chart.legend.itemContainers.template.togglable = false;

chart.legend.itemContainers.template.events.on("hit", function(event){
var target = event.target;
var switching = target.isActive;
chart.legend.itemContainers.each(function(item) {
var series = item.dataItem.dataContext;
if (item.dataItem == target.dataItem || (item.isActive && !switching)) {
item.isActive = false;
series.show();
}
else {
item.isActive = true;
series.hide();
}
})
});

Any help is much appreciated!

**Comment by snasir3** [comment]
@martynasma 

I have made some progress but need your help to fix some errors and to make it work properly

**so far** 
const legend = chart.children.push(am5.Legend.new(root, { clickTarget: 'none' }))
    legend.data.setAll(chart.series.values)
    legend.events.on('click', (event) => {
      const { target } = event
      const switching = target.isActive
      legend.data.each((item) => {
        const state = item
        const legendSeries = item.dataItem
        if (item.dataItem === target.dataItem || (item.isActive && !switching)) {
          state.isActive = false
          legendSeries.show()
        } else {
          state.isActive = true
          legendSeries.hide()
        }
      })
    })
this code excutes but gives **Uncaught TypeError: Cannot read properties of undefined (reading 'show')**

I would really appreciate ur help here. I have to complete this task today and i am stuck at this stage.

**Comment by martynasma** [comment]
I believe what you're asking is for us to debug your code, which falls under premium support area.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).
