### ISSUE TITLE
FR: sunray plot

### ISSUE THREAD

**Issue by stla** [amcharts/amcharts5#297]
Hello,

  I didn't find any library (JavaScript, R, Python, Julia) which allows to produce such a plot, only some PowerPoint templates. It would be nice if AmCharts5 allowed that.

![sunray](https://user-images.githubusercontent.com/4466543/154970833-bab51845-9d7e-4f00-a36a-c43eedc7a8fd.png)

**Comment by martynasma** [comment]
I'm afraid we do not have plans on implementing this :(
