### ISSUE TITLE
How to fix excessing `extraMin` and `extraMax` for `DurationAxis`?

### ISSUE THREAD

**Issue by someden** [amcharts/amcharts5#298]
I need a little whitespace (+1%) on start and end of `DurationAxis`
But `extraMint: 0.01` and `extraMax: 0.01` settings add much more than 1%. Why it's so? And what settings should I use?

<img width="403" alt="Screenshot 2022-02-21 at 17 39 43" src="https://user-images.githubusercontent.com/7009699/154976689-aee751f9-b603-4b53-8c94-ca20b198076d.png">

Example: https://stackblitz.com/edit/react-np61p6?file=src/Chart.js

Also, why setting column width is not working?
```js
    series.columns.template.setAll({
      width: am5.percent(90),
      templateField: 'columnSettings',
    });
```

**Comment by someden** [comment]
It works fine with `DateAxis`:
https://stackblitz.com/edit/react-n3kqzw?file=src%2FChart.js

**Comment by martynasma** [comment]
Well, the axis scale is adjusted to round up to "pretty numbers". So if your actual data starts at 0 and you add even slight `extraMin` it goes into negative to a next increment, which in your case is 6 hours.

You can increase granularity of your X axis grid to make the increments smaller:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/value-axis/#Relative_scope_extension

Another option is to pre-calculate and set `min` and/or `max` values for your axis.

As for the other question, please do post another issue. Let's keep this clutter free with one question per issue.

**Comment by someden** [comment]
I didn't find how to increase granularity of X axis grid to make the increments smaller.
Calculate and set `min` and/or `max` values also didn't affect anything.
But I found `strictMinMax: true` and it works, thanks anyway.

**Comment by martynasma** [comment]
OK. Feel free to close this when ready.
