### ISSUE TITLE
Dynamically adding and  removing series with amChart5

### ISSUE THREAD

**Issue by mkdudeja** [amcharts/amcharts5#3]
Hi Team,

I am trying to use amChart5 with react and With amChart5 every element is separately created like root, chart, xAxis, yAxis, legend etc.

Now the issue is while creating a series, we need to provide the reference to xAxis and yAxis. 

Add series can be a generic and re-usable function. To make this work, one has to store the reference of every entity (root, chart, xAxis, yAxis, legend), so that the series function can use this to add series to the chart and update legends.

This seems too much unnecessary work on the developer end. Whereas "chart.series.push" should be intelligent enough to get bonded with the default xAxis, yAxis until specified otherwise. Same for the legends as well, while adding new series the legend should get updated automatically, but that doesn't seem to happen right now.

As I checked the typed definition of chart and root, there are no functions as well, by which one can get the reference to different pieces of the chart at run time.
For example: chart.getxAxis(), chart.getxAxisById()

Can you help with your inputs on this, if there is any other way to get around with building a dynamic chart (add series, removing series) without keeping a reference of all different entities?

Can you please help me with codepen or pointer to documentation for dynamically adding/ removing the series from chart?

Thanks,
Manish

**Comment by amcharts** [comment]
Hi,

you can simply get first (or any other x or y axis) like this:

`chart.xAxes.getIndex(0)`

Sorry, but we do not plan to make assigning axes automatically.

**Comment by mkdudeja** [comment]
Hi,

Doing the same to get the default xAxis or yAxis.

But the problem with this approach when you have multiple dynamically added xAxis or yAxis, we can't reply on an index-based approach. There should be a more reliable approach something may be `id` based lookup.

Thanks,
Manish

**Comment by martynasma** [comment]
We are considering adding some global registry for user-id'ed entities for lookup.

Stay tuned.

**Comment by martynasma** [comment]
Implemented in 5.0.0-beta.9.

## [5.0.0-beta.9] - 2021-09-06

### Added
- `id` setting to all entities. If set, will also appear in `am5.registry.entitiesById`.
- `show()` and `hide()` methods of `DataItem` now accept duration param.

### Fixed
- Stacking of horizontal bars was not working properly.
- Children of a `Container` were not being disposed properly together with the container itself.
- Tooltip for a series close to the top/bottom of a plot area sometimes was not being displayed.
- `PieSeries` was overriding label `textType` setting.
- `XYChart` and `MapChart` were taking over mouse wheel action even when `wheelY` and `wheelX` were set to `"none"`.
- `XYCursor` was not showing series tooltips if Y axis was not a `ValueAxis`.
- `XYCursor` was showing previous data point tooltip if currently hovered position did not have data item or value was null.
- Percent chart could go to SO if there were no values in data.
- Changing `layer` value dynamically was not working properly.
