### ISSUE TITLE
calculateTotals is not always working

### ISSUE THREAD

**Issue by datafoo** [amcharts/amcharts5#302]
### Steps to reproduce

1. Configure a chart with a combination of data grouping, several stacked `StepLineSeries` and `calculateTotals: true` on the `yAxis` (see https://codepen.io/jackfoo/pen/mdqLNNW)
2. Hover over the series to display the tooltips

### Expected result:
The tooltip for the total series should display the calculated value.

### Actual result
The tooltip for the total series only display the calculated value after some interaction with the chart: clicking in the legend, zooming.

**Comment by zeroin** [comment]
I confirm it's a bug, it will be fixed in next release.
