### ISSUE TITLE
Error: EventDispatcher is disposed

### ISSUE THREAD

**Issue by keegandonley** [amcharts/amcharts5#305]
I'm running into an issue with some of my events, where I get an error thrown of `Error: EventDispatcher is disposed`. Some context:

I'm using React and the events that are causing the problem are used to update some external state outside the chart. For example, I have one event:
```js
this.xAxis.onPrivate('width', (width) => setWidth(width))
```
and anther:
```js
this.chart.get('scrollbarY').thumb.events.on('positionchanged', this.handleScrollbarPosition)
```

In some situations, as soon as the callback is called and the external state is updated, I get the above-mentioned error. My best guess is that this isn't anything React-specific, because I'm always calling `root.dispose()` before re-rendering the chart. I'm at a loss as to what could be causing this error.

**Comment by zeroin** [comment]
I tried to reproduce this using some basic scenario, but without luck. I am afraid I need this to be reproduced outside react with a working code in order to help.

**Comment by sassomedia** [comment]
@keegandonley I can almost definitely tell you that this is React related. Especially in the second case where you listen on `positionchanged` event that may fire 5-10x per second and then triggering some React state which by itself can cause renders 5-10x per second on its own. My guess is that your chart is re-rendering too fast, too many times and it can't keep up, expectedly so. The chart is quite a complex object with a lot of setup and tear down code that takes time to run, so you want to make sure you prevent React from re-rendering the chart at all cost.

I would suggest that you only have a few props that actually can cause a re-render of the chart. Stick those into a `memo` and export that as the component. Example; only if your `data` or `currencyCode` prop changes, should the chart re-render. Something like the following (haven't tested this particular code, but similar):
```javascript
import React, { memo, useRef, useState } from "react";
import { Root } from "@amcharts/amcharts5";
import { XYChart } from "@amcharts/amcharts5/xy";

const Chart = ({
  data,
  currencyCode,
  foo,
  bar,
  ... // more props
}) => {
  const elemRef = useRef();
  const [chart, setChart] = useState();

  useEffect(() => {
    if (!chart) {
      const root = Root.new(elemRef.current);
      const chartInstance = root.container.children.push(XYChart.new(root, {}));
      ... // more chart code

      setChart(chartInstance);
    }

    return () => {
      if (chart && !chart.isDisposed()) {
        chart.dispose();
        chart.root.dispose();
        setChart(null);
      }
    };
  }, [currencyCode, data]);

  return <div ref={elemRef} style={{ width: "100%", height: "100%" }} />;
}

export default memo(
  Chart,
  // Only render component on data or currencyCode change
  (prevProps, nextProps) =>
    prevProps.data === nextProps.data &&
    prevProps.currencyCode === nextProps.currencyCode
);
```

**Comment by keegandonley** [comment]
@sassomedia That makes sense, thanks for the detailed explanation. I was tearing down the chart pretty frequently and wasn't aware that could cause a problem. Re-writing to protect against rapid re-renders solved my issue.

**Comment by sassomedia** [comment]
Great, glad that worked 👍
