### ISSUE TITLE
Synced Axes Do Not Share Gridlines

### ISSUE THREAD

**Issue by keegandonley** [amcharts/amcharts5#306]
I have a chart with two opposite y-axes that I want to be in sync, however in some situations they don't share gridlines.

Here's how I sync the axes: 
```javascript
this.secondaryYAxis.set('syncWithAxis', this.yAxis);
```

And the result:
<img width="924" alt="Screen Shot 2022-02-22 at 4 19 38 PM" src="https://user-images.githubusercontent.com/12700819/155229421-2acbfe8f-7559-4cf4-8f42-e03194a757b9.png">

**Comment by zeroin** [comment]
Yes, there are cases when axes can not be synced. We have a note about this in our docs:

`syncWithAxis setting is experimental and is not guaranteed to work perfectly in 100% of scenarios.`

**Comment by keegandonley** [comment]
@zeroin  I did notice that comment, but I took that to mean most scenarios would work with a few edge cases. It seems to me most of my charts don't work, with one or two that do. However, this morning I've been messing with the zoom settings on my two axes and seem to have it in a place where it works in most scenarios. Is the intention for this to improve over time, or is this as good as you intend for it to get? In my case, I'd prefer to prioritize the axes being in sync and would be fine with the scales looking weird, etc

**Comment by zeroin** [comment]
Well, I must say I really spent a lot of time on this topic during many years and kept coming back to it. And I don't think I have ideas of how to make it better at the moment. And yes, playing with zoom settings / gridCount of the axis might help, but I can't promise it will always work.

**Comment by keegandonley** [comment]
Thanks for the insight! After some more work today I seem to have it pretty stable at least at the default zoom levels. I'll keep tinkering if I run into trouble again.
