### ISSUE TITLE
Stacked Series Drag to resize? 

### ISSUE THREAD

**Issue by cwooldridge1** [amcharts/amcharts5#307]
First off I like to thank you for so quickly fixing and deploying the previous comment I made.

I noticed that on some of your competitor's charts they allow the user when there are stacked series to be able to drag the axis header to resize the size of each stacked y-axis. Here is an example: https://www.highcharts.com/demo/stock/stock-tools-gui you'll notice here if you drag the bar it will resize both the volume y-axis and the price y-axis height.

I noticed that on amcharts you guys have an onDrag property that can be associated with axis headers but I couldn't find anything on using that to resize y-axis heights. 

Before I went to the trouble of making something that would emulate this on the drag to resize the y-axis effect I thought I would ask if you guys had any examples on how to do this or have some type of built-in function that I might of missed for doing this. 

If not I feel like this would be a feature worth adding or a demo worth adding

Thanks for your time

**Comment by zeroin** [comment]
We plan to add this feature in upcoming Stock chart. We expect beta version to be released during 2-3 weeks.

**Comment by cwooldridge1** [comment]
Any updates on this?

**Comment by zeroin** [comment]
Sorry, it took some more time than we expected, but we are really finishing, we will release it until the end of April.

**Comment by cwooldridge1** [comment]
Wow guys just now check out the new stock charts and amazing job. Can't wait to dive into these. Thanks so much.
