### ISSUE TITLE
How to align both axes titles and labels in stacked axes chart?

### ISSUE THREAD

**Issue by datafoo** [amcharts/amcharts5#309]
I would like the same stacked axes chart as https://codepen.io/jackfoo/pen/mdqjOLM where labels of both y axes are nicely aligned to the right.
But I would also like to have the axes titles aligned on the same x location. In the example, "Axis title 1" should be shifted to the left at the same position as "Axis title 2".

Can we achieve that with amCharts 5?

**Comment by zeroin** [comment]
It's quite complicated, I could not think of a better way except to measure width of the `ghostLabel` of the axis (it is there doing some secret job) and making with of both of them the same:
https://codepen.io/team/amcharts/pen/gOXjWVe

**Comment by datafoo** [comment]
Great. Thank you.

Is this documented somewhere? Is there more than https://www.amcharts.com/docs/v5/reference/axis/#ghostLabel_property?

**Comment by zeroin** [comment]
No it is not yet, we will think where to put it.

**Comment by martynasma** [comment]
Just posted the above demo here:
https://www.amcharts.com/docs/v5/tutorials/syncing-axis-widths-across-multiple-charts/

No extensive documentation, though.

**Comment by BudgieInWA** [comment]
These days in am5, this can be achieved by setting both `x` and `centerX` to 100% on all of the Y-Axes like so:

```js
am5xy.ValueAxis.new(root, {
  renderer: am5xy.AxisRendererY.new(root, {}),
  marginTop: 16,
  height: am5.percent(30),
  // Align the labels to the right of the container:
  x: am5.p100,
  centerX: am5.p100,
})
```

**Comment by BudgieInWA** [comment]
Sorry @datafoo, I hadn't fully understood your problem (I was just trying to get the numbers to line up on the right).

I looks like the solution that involves keeping the width of the Y Axes in sync with the ghost label is the only way to do what you are trying to do in a generic way.

If you know how tall each axis will be though, you could add another container to the chart, and set the y location of the labels manually like this (which works well in your CodePen):

```js
var labelContainer = chart.yAxesAndPlotContainer.children.unshift(
  am5.Container.new(root, {
    layout: root.verticalLayout,
    height: am5.p100,
  })
);
var labelRotation = { rotation: -90, centerX: am5.p50, centerY: am5.p50 };
labelContainer.children.push(
  am5.Label.new(root, {
    text: "Axis title 1",
    y: am5.percent(25),
    ...labelRotation
  })
);
labelContainer.children.push(
  am5.Label.new(root, {
    text: "Axis title 2",
    y: am5.percent(75),
    ...labelRotation
  })
);
```
