### ISSUE TITLE
Custom fonts are only loaded after chart resize

### ISSUE THREAD

**Issue by rferreira98** [amcharts/amcharts5#316]
I'm using OpenSans and Metropolis, two custom fonts.
Open sans is being imported this way:

```

@import url('https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap')

```

While, Metropolis is being loaded locally:

``` 

@font-face
  font-family: 'Metropolis'
  font-weight: 400
  font-style: normal
  font-display: swap
  src: local('Metropolis'), url(../public/Metropolis.woff) format('woff')

```

As I use these fonts for drawing, e.g. inside a pie chart just like this:

![Screen Shot 2022-03-03 at 10 13 59](https://user-images.githubusercontent.com/24259712/156544069-d5d0bfd8-7754-4376-a920-9a1e10dbc109.png)

When I load the page the fonts are not loaded, like this:

![Screen Shot 2022-03-03 at 10 15 11](https://user-images.githubusercontent.com/24259712/156544251-65d00898-b5f4-4c6e-87a3-a29e196d7bcf.png)

Metropolis on "5%", "70%", and "see all" are not correct.
Neither OpenSans  on "Zero engagement" and "Overall Engagement".
All I'm doing is applying fontFamily on these elements, and on resize the font actually renders correctly.
I've tried preload/prefetching them but no success.

**Comment by martynasma** [comment]
The issue is that when you import font there's a delay, so the chart is build before font is actually loaded.

Try enveloping your chart code into ready statement:

```JavaScript
am5.ready(function() {
  // chart code
});
```

**Comment by rferreira98** [comment]
That did not solve it. Here's a sandbox: https://codesandbox.io/s/dawn-shape-g0xfno
Maybe it helps to understand the environment.

**Comment by sassomedia** [comment]
Not sure if this is an issue with codesandbox. I first tried delaying the whole code execution from loading for 10secs, to make sure fonts are definitely loaded but that didn't work. Then I removed all existing font imports and definitions and used a new [Google Font](https://fonts.google.com/share?selection.family=Smooch%20Sans:wght@500) instead, one that would be very obvious to recognize if it loaded. Even with Google's link code and CSS definitions, this font is not visible even for anything in the html body or the "This header renders correctly...".

Have you tried this in a codepen, at least with the external Google Font?

**Comment by rferreira98** [comment]
Couldn't achieve this in codepen, however I added an external Google Font (League Gothic) which is quite noticeable and it only loads the font when I hover the chart. @sassomedia

**Comment by sassomedia** [comment]
@rferreira98 This looks to be an issue with that particular font. I made a pen of a simple pie chart and if you check the settings (HTML) of the pen, the header loads two fonts (Smooch Sans and League Gothic). The default shows the Smooch Sans font displaying both outside and inside the chart. When you switch the position of the fonts in the CSS and the commented lines in the Javascript, you will see that League Gothic displays fine outside the chart but not inside:
https://codepen.io/sassomedia/pen/jOaoVGd?editors=0010

My suggestion would be to use an alternative font or try to download and repair the League Gothic font with some tools. It's not uncommon that fonts can sometimes become corrupted or be simply incompatible with a certain application or even the OS.

**Comment by rferreira98** [comment]
I've tried with RobotoCondensed (local font downloaded from google fonts) and it happens the same. I believe the problem is when using local fonts.

https://user-images.githubusercontent.com/24259712/157229739-9fdbc576-c8cc-4a3d-a5cd-2261549ea3dc.mp4

**Comment by rferreira98** [comment]
@sassomedia Hey, any news on this?

**Comment by sassomedia** [comment]
Hmm, other than trying to load that font from your live server rather than localhost, I unfortunately don't have any other suggestions.

@martynasma, have you encountered this issue before?

**Comment by martynasma** [comment]
@rferreira98 

I can't seem to be able to reproduce this.

I tried open-source Metropolis font, and it shows up just fine when set on chart elements. Both when loaded locally and from a web server.

Perhaps, you can try if using OS Metropolis works for you?
https://www.1001fonts.com/metropolis-font.html

Here's the CSS I used:

```CSS
@font-face {
  font-family: "Metropolis-Regular";
  font-weight: 400;
  font-style: normal;
  font-display: swap;
  src: local("Metropolis-Regular"),
    url("./Metropolis-Regular.otf") format("opentype");
}
```

**Comment by rferreira98** [comment]
@martynasma it doesn't solve the problem.

**Comment by martynasma** [comment]
Does this happen on both Safari and Chrome?

**Comment by rferreira98** [comment]
Apparently it does not. Safari is working.

**Comment by martynasma** [comment]
Thanks for the info.

This seems like a limited case scenario. I wonder whether wrapping amCharts code into some sort of `setTimeout()` would help.

**Comment by rferreira98** [comment]
It does work, as a workaround.

**Comment by martynasma** [comment]
OK. I'm not entirely sure what else to suggest :(

**Comment by rferreira98** [comment]
I'll be sticking to this one. Does look consistent and does not consume a tremendous time to work. 200ms  or less are enough since font is loaded much earlier.
