### ISSUE TITLE
How to add series tooltipText individually  series data in column.

### ISSUE THREAD

**Issue by purellarohith** [amcharts/amcharts5#319]
![Screenshot 2022-03-06 at 12 12 34 PM](https://user-images.githubusercontent.com/55445230/156922947-8e3b0374-b074-4f62-95d4-f3ad27a1a2c4.png)

Is there any way get each series in column data to add tooltipText manually through loop ?

**Comment by martynasma** [comment]
I'm not entirely sure what you're asking.

You can set tooltipText directly on each series column template:

```JavaScript
series.columns.template.setAll({
  tooltipText: "....."
});
```

https://www.amcharts.com/docs/v5/charts/xy-chart/series/#Tooltips_on_series_elements

**Comment by hsharma1996** [comment]
@martynasma thanks for your response. 
The requirement is 
1) We should be able to configure tooltip for each column of every series
2) We should be able to add custom key value pair in tooltip details. 
Thanks for your help :)

**Comment by sassomedia** [comment]
> 1. We should be able to configure tooltip for each column of every series

Isn't that what the link above accomplishes?

> 2. We should be able to add custom key value pair in tooltip details.

You could use different key-value pairs with data placeholders:
https://www.amcharts.com/docs/v5/concepts/formatters/data-placeholders/

**Comment by hsharma1996** [comment]
@sassomedia Thanks a lot. 
Missed placeholders. 
That's something we were looking for. 
Thanks for your help.
