### ISSUE TITLE
LineSeries Y-axis pre-zoom not working

### ISSUE THREAD

**Issue by sassomedia** [amcharts/amcharts5#32]
Seems like the LineSeries Y-axis pre-zoom is not working:
```javascript
series.events.once("datavalidated", function(ev) {
  xAxis.zoomToValues(0, 100); // does work
  yAxis.zoomToValues(0, -100); // does not work
});
```
Setting the `start: 0.5` property on Y-axis creation also does not work. The `yAxis.zoomToValues` issue is seen here in this [CodePen](https://codepen.io/sassomedia/pen/QWgXgmX?editors=0010) on line 287. The Y-axis zoom does work however when called after a delay on line 298.

**Comment by martynasma** [comment]
Calling `series.appear(1000)` triggers own value axis zoom which knocks off the `zoomToValues()`.

I suggest removing that line.

Or delaying pre-zoom by X ms, as you have in your CodePen.

**Comment by sassomedia** [comment]
Ah I see, thanks for the confirmation 👍
