### ISSUE TITLE
When Axis has date figures the tooltip showing empty box

### ISSUE THREAD

**Issue by sabinasu** [amcharts/amcharts5#320]
We set axis value date. Added tooltip to it (we needed it to category and value axis as well) and if its date is showing us empty tooltip. See below 
![image](https://user-images.githubusercontent.com/101180745/157216502-4cc6595f-699c-4ab8-95e1-02f9c1d5be19.png)

**Comment by sassomedia** [comment]
This would need some more information to investigate further. Could you please create a simple Codepen or similar of your setup?

**Comment by Barteczek** [comment]
Hi, please find below the codepen link. We have a tooltip invoked by the cursor at the top of the chart, but additionally we need a tooltip for xAxis value on hover the actual value. The setup works for both category and value axes but not for date.
https://codepen.io/bart92/pen/zYPQZXQ

**Comment by sassomedia** [comment]
Hey there, sorry for the delay. Still not quite sure what the ultimate goal is on this. Are you trying to display a custom date when you hover over the date on the Axis? You could do it on hover of the label, you get the value of the label which you could format and then add it as a tooltip value:
```javascript
xAxisRenderer.labels.template.events.on("pointerover", (evt) => {
  evt.target.set("tooltipText", evt.target.get("text"));
});
```
Not sure if that's what you are trying to achieve but here's an example of the above:
https://codepen.io/sassomedia/pen/popgXXr?editors=0010

**Comment by Barteczek** [comment]
Hi, thanks for your response
The goal is to have the same on tooltip what is on the axis, so your example solves the problem, but...
when we delete (or comment) the line, that threw error
`// xAxis.get("tooltipDateFormats")["day"] = "MMM dd"; // this throws an error`

then, the tooltip which is invoked by cursor (on top) has different format than "MMM dd"
![image](https://user-images.githubusercontent.com/23141501/159000889-bfcd940b-bca7-4aa9-89c1-0838eff334b0.png)

**Comment by sassomedia** [comment]
Ok, so what if you were to add ` tooltipDateFormat: "MMM dd"` to the DateAxis properties, would that work?
Updated pen: https://codepen.io/sassomedia/pen/popgXXr?editors=0010

**Comment by Barteczek** [comment]
Yes, works perfectly! Thank you!

**Comment by sassomedia** [comment]
Excellent, glad that worked for you 👍
