### ISSUE TITLE
Value of the property "selectionMaxFinal" is not properly calculated after making previously hidden series visible

### ISSUE THREAD

**Issue by luktom** [amcharts/amcharts5#322]
Hello,

value of the property "selectionMaxFinal" from value axis is not properly calculated after showing hidden series again. I prepared jsFiddle using one of your demos to show the problem. 

Please check: https://jsfiddle.net/3yokfe0q It contains three series, below the chart there are buttons which are toggling the visibility of particular series. After showing/hiding series is finished, I am reading the property "selectionMaxFinal" from value axis and it is displayed below the buttons.

Please click on button "Series 1", then on "Series 2", current maximum value is properly displayed. Then please click on the buttons in reverse order "Series 2" (the value 1001.5 is displayed instead of 70000) and "Series 1" (the value 70000 is displayed instead of 200000).

**Comment by zeroin** [comment]
This is by design. When showing series axis animates `selectionMin` and `selectionMax` after the series is shown. So you try to get the selectionMaxFinal before it is changed. I would simply recommend to monitor it  directly:

```
yAxis.onPrivate("selectionMaxFinal", (x)=>{
  console.log("max", x)
})
```
