### ISSUE TITLE
Scrollbar customisation unselectedOverlay

### ISSUE THREAD

**Issue by alienbuild** [amcharts/amcharts5#323]
I'm trying to style up the xychartscrollbar and noticed that in amcharts 4 we have the unselectedOverlay property to style the unselected area of the xyscrollbar. Is there a replacement property for this in amcharts 5? 

Thanks,

ref:
https://www.amcharts.com/docs/v4/tutorials/customizing-chart-scrollbar/#Unselected_area
https://www.amcharts.com/docs/v5/reference/xychartscrollbar/

**Comment by CHANDRAMOHANnegi** [comment]
@alienbuild did you solve it in am5
