### ISSUE TITLE
"No Data" message

### ISSUE THREAD

**Issue by abhaypatil87** [amcharts/amcharts5#324]
This seems more of a question. I found a few examples for AMCharts version 3 as below:
https://codepen.io/team/amcharts/details/GpLXzY/f77d12b464b2a6a99ec0278ccd65dced

But couldn't find any such provision for v5. Is there a way to keep the basic chart skeleton as a layer but still show a "No Data" message over the empty chart in Amcharts V5?

**Comment by martynasma** [comment]
There you go:
https://www.amcharts.com/docs/v5/tutorials/show-no-data-warning-on-a-chart/

**Comment by abhaypatil87** [comment]
Thank you!
