### ISSUE TITLE
Question: Group Series to single legend child

### ISSUE THREAD

**Issue by cwooldridge1** [amcharts/amcharts5#325]
Is there a way to connect multiple series to a single child in a legend? For example, say I have a legend, and let's say I had plotted 3 LineSeries, instead of having a child for each of these line series I want one child to reference them all.  So instead of this:
Legend:
plot 1: value 123
plot 2: value 231
plot 3: value 321

I want this:
Legend:
plot: value 123 value 231 value 321

So when I click on the child called "plot" all three series will disappear at once instead of me having to click on each child to disappear. The child in the legend I want should be able to reflect the values of each of the series as well.

Thanks

**Comment by martynasma** [comment]
Well, you could add series to legend selectively, then watch their `visible` setting change and `show()/hide()` related series.

Here's a prototype:
https://codepen.io/team/amcharts/pen/OJOKXrq??editors=0010

**Comment by cwooldridge1** [comment]
Thanks this is just what I was looking for
