### ISSUE TITLE
Line chart zooming&scaling issue

### ISSUE THREAD

**Issue by koorizhizhi** [amcharts/amcharts5#326]
Hi there,
I’m working on a report generating functionality by exoporting all pre-plotted charts onto a canvas.
Every thing works as expected when I put a canvas alone on the page：
<img width="337" alt="image" src="https://user-images.githubusercontent.com/83855880/157581262-2ff932c3-4c37-4171-acb0-308520080e52.png">

However these line charts on the bottom left seem to be zoomed out when another part wrote by a team member has been added in the page:
<img width="333" alt="image" src="https://user-images.githubusercontent.com/83855880/157581960-4c1143c1-55c0-451d-a972-798c328205db.png">
The same data has been used to be populated into the charts.
And the zoom-control button showed itself on the top right which I have  no intend to show.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by koorizhizhi** [comment]
> Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
I’m not sure if I can share the codes.
I need to confirm that first.

**Comment by martynasma** [comment]
That would be great. We need something that we can test. Otherwise it's just guesswork :(
