### ISSUE TITLE
can tooliptext include any pictures?

### ISSUE THREAD

**Issue by otliievnia** [amcharts/amcharts5#328]
**Question**
is it available to add any pictures on tooltip?

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
No, I'm afraid. We might introduce HTML-enabled tooltips in the future, though.

Please subscribe to the following issue for any updates: https://github.com/amcharts/amcharts5/issues/35

**Comment by sassomedia** [comment]
@otliievnia You could add an SVG to it, if that works for you: https://github.com/amcharts/amcharts5/issues/189#issuecomment-1072297977
