### ISSUE TITLE
chart.dateFormatter.inputDateFormat is missing in AmCharts 5

### ISSUE THREAD

**Issue by BabakAmini** [amcharts/amcharts5#331]
I have time-series data that are formatted as "HH:mm:ss" which I want to be rendered in my template and used by AmCharts to display. However, AmCharts needs dataset times to be as JavaScript time (milliseconds elapsed from 1970 Jan 1) so I have to convert them to the proper format. I heard that I can do this by setting **chart.dateFormatter.inputDateFormat** to something like **"H:mm:ss"** in AmCharts 4, but it seems that there is no such an attribute in version 5.

Am I missing something, or is there another attribute to use for this purpose?

Any help would be appreciated.

**Comment by xorspark** [comment]
The equivalent in v5 is to create a [DataProcessor](https://www.amcharts.com/docs/v5/concepts/data/#Parsing_dates) to parse your dates:

```
// Processor needs to be set before data
series.data.processor = am5.DataProcessor.new(root, {
  numericFields: ["value"],
  dateFields: ["date"],
  dateFormat: "yyyy-MM-dd"
});

series.data.setAll([{
  date: "2021-01-01",
  value: "1000"
}, {
  date: "2021-01-02",
  value: "800"
}]);
```

**Comment by BabakAmini** [comment]
@xorspark Thanks for the reply. There is a good sample code in that document. However, my dataset has only time values, so I forked that code and changed something to get the date parser to work, but I didn't get any success in solving the problem.

Would you please check [this](https://codepen.io/BabakA/pen/VwyvwJv) out

**Comment by xorspark** [comment]
Your value fields don't match; your data has the timestamps stored in the `year` field, but your code is referencing an unknown field called `second`. You can either change the field in your data to `second` or change the config to use `year`.

Codepen with the data updated: https://codepen.io/team/amcharts/pen/NWXGwXb/67a7d714e7cb5430a813a74d6c28e8c9

**Comment by BabakAmini** [comment]
@xorspark Thank you for your time, it worked.
