### ISSUE TITLE
Why does scrollbar overlap title and axis headers?

### ISSUE THREAD

**Issue by cabintech** [amcharts/amcharts5#336]
Following example of how to add a title to a chart at [https://www.amcharts.com/docs/v5/concepts/common-elements/labels/](https://www.amcharts.com/docs/v5/concepts/common-elements/labels/) results in the title overlapping the scroll bar:

	// Chart title
	chart.children.unshift(am5.Label.new(root, {
	  text: "This is a chart title",
	  fontSize: 25,
	  fontWeight: "500",
	  textAlign: "center",
	  x: am5.percent(50),
	  centerX: am5.percent(50),
	  paddingTop: 0,
	  paddingBottom: 0
	}));

	// Add scrollbar
	chart.set("scrollbarX", am5.Scrollbar.new(root, {
		orientation: "horizontal"
	}));

![image](https://user-images.githubusercontent.com/31935300/158652697-117b6b5e-697d-4e10-9844-71a22379a759.png)

Same happens if I try to use a x-axis header. I also changed the order (add scroll bar first, then title) and they all get the same result. How to get this to display correctly?

**Comment by xorspark** [comment]
You'll need to add the label to the topAxesContainer in order for the title to appear above the scrollbar:

```
chart.topAxesContainer.children.unshift(am5.Label.new(root, {
  text: "This is a chart title",
  fontSize: 25,
  fontWeight: "500",
  textAlign: "center",
  x: am5.percent(50),
  centerX: am5.percent(50),
  paddingTop: 0,
  paddingBottom: 0
}));
```
