### ISSUE TITLE
Gradient line position using x1, x2, y1, y2

### ISSUE THREAD

**Issue by wrenzi** [amcharts/amcharts5#339]
Hey **folks**, 

I'm testing the **amCharts** to understand if it works better than **recharts** for our current project.

I was not able to position my gradient line using x1, x2, y1, y2 as we do using recharts:
```
<linearGradient x2="0" y1="0" x1="100%" y2="100%">
  <stop offset="0%" stopColor="#0058B7" stopOpacity="0.15" />
  <stop offset="100%" stopColor="#e4f9ec" stopOpacity="0.05" />
</linearGradient>
```
The closest thing I found was this question asked in 2018:
https://github.com/amcharts/amcharts4/issues/292#issuecomment-416906042

Is it something possible to be accomplished today?

**Comment by martynasma** [comment]
Well, there's no option to custom-position gradients.

That being said, amCharts 5 has more control on what target element to be used for positioning.

Can you explain what you are trying to achieve, and I'll assess whether that is doable?
