### ISSUE TITLE
Is there any way to get a star bullet rotated on a gauge?

### ISSUE THREAD

**Issue by koorizhizhi** [amcharts/amcharts5#340]
I have a gauge chart which has 2 star bullets:
https://codepen.io/koorizhizhi/pen/jOGbGGV
I’m asked to make the left star always be vertical(its top tip should always point to the north).
Is thera any setting that works like what "textType" property does for labels?

**Comment by martynasma** [comment]
You can lock in the `rotation` setting using an adapter:

```JavaScript
bullet2.get("sprite").adapters.add("rotation", function() {
  return 0;
});
```

**Comment by koorizhizhi** [comment]
> You can lock in the `rotation` setting using an adapter:
> 
> ```js
> bullet2.get("sprite").adapters.add("rotation", function() {
>   return 0;
> });
> ```

Thank you very much!
