### ISSUE TITLE
Set Stacked as true not working when data field with double question marks like "2.5"

### ISSUE THREAD

**Issue by RosaShellPicker** [amcharts/amcharts5#341]
When numeric data field with double quotation marks like below, the stacked as true is not working.
`var data = [{
  "year": "2021",
  "europe": "2.5",
  "namerica": "2.5",
  "asia": "2.1",
  "lamerica": "1",
  "meast": "0.8",
  "Africa": "0.4"
}, {
  "year": "2022",
  "Europe": "2.6",
  "namerica": "2.7",
  "asia": "2.2",
  "lamerica": "0.5",
  "meast": "0.4",
  "Africa": "0.3"
}]`

**Comment by RosaShellPicker** [comment]
<img width="1911" alt="Screen Shot 2022-03-18 at 4 52 06 pm" src="https://user-images.githubusercontent.com/6779277/158945428-642c4bcd-8cfb-44a6-8e37-a962284e1de1.png">

**Comment by RosaShellPicker** [comment]
Can't change the data structure manually do to it's coming from the server, can this bug be fixed, please?

**Comment by martynasma** [comment]
You can use data processor to convert string fields into number fields:
https://www.amcharts.com/docs/v5/concepts/data/#Parsing_numeric_values

**Comment by RosaShellPicker** [comment]
It works, thanks!
