### ISSUE TITLE
Delay between boundschanged event and update of ghostLabel width

### ISSUE THREAD

**Issue by datafoo** [amcharts/amcharts5#342]
I am trying to [Syncing axis widths across multiple charts](https://www.amcharts.com/docs/v5/tutorials/syncing-axis-widths-across-multiple-charts/) on a chart with data updates.

### Steps to reproduce

1. Launch https://codepen.io/jackfoo/pen/popgmaM
2. Click on the "Update data" button

### Expected result:
The ghostLabel width is synchronized on all Y axes.

![Screenshot 2022-03-18 at 12-27-43 Syncing ghostLabel width](https://user-images.githubusercontent.com/34766150/158995348-e56bca4f-bb34-4f66-9744-1aa379808425.png)

### Actual result
The ghostLabel width is not always synchronized on all Y axes.

![Screenshot 2022-03-18 at 12-28-35 Syncing ghostLabel width](https://user-images.githubusercontent.com/34766150/158995532-ed8fe5b9-1ba2-4053-b53f-cc56157a096e.png)

### Additional information
I believe that the reason is that there is a little delay between the moment the `boundschanged` event and the moment the width of the `ghostLabel` is updated. Uncomment the lines `119` and `128` to add an arbitrary 100 ms delay and the problem seemed to be worked around.

**Comment by zeroin** [comment]
I think it would be better if you add event listener to ghostLabel itself, not to the axis:

`axis.ghostLabel.events.on("boundschanged", syncYAxes);`

**Comment by datafoo** [comment]
> I think it would be better if you add event listener to ghostLabel itself

That seems to work great.

Perhaps the [demo](https://www.amcharts.com/docs/v5/tutorials/syncing-axis-widths-across-multiple-charts/) should be updated to reflect that.
