### ISSUE TITLE
chart with many x/y data points

### ISSUE THREAD

**Issue by paulflo150** [amcharts/amcharts5#343]
Any thoughts on how I could create a chart like the one in the screenshot below?

![image](https://user-images.githubusercontent.com/8136504/159017662-f61b0165-f1da-412c-8af3-a2d7a7b977db.png)

I have been working on this codepen, however I am nowhere close:

https://codepen.io/paul100/pen/MWryWPo

**Comment by martynasma** [comment]
Can you be more specific, what are you having trouble with?

**Comment by paulflo150** [comment]
What I have looks unreadable/ unusable, I have provided the codepen above

![image](https://user-images.githubusercontent.com/8136504/159030022-a8381cf8-11af-44c4-b415-bd5786bb035b.png)

**Comment by martynasma** [comment]
I'm sorry, but we here don't take requests to implement charts.

I suggest you take a look at documentation, and if you have any specific questions, we'll be happy to guide you.

Hope that sounds reasonable.

**Comment by martynasma** [comment]
I'm just trying to set a frame of reference what kind of help you can expect in this public and free space.

If you'd like a more thorough approach, you may consider purchasing support service:
https://www.amcharts.com/support/support-info/free-support/

Please note, while we go to great lengths to help our subscribers, we still don't have the capacity to do custom development, like "Here's a screenshot of the chart. Please make one for me in amCharts".

It's rather "I can't figure out how to remove padding around the chart. Any suggestions?".

Hope that sounds reasonable now.
