### ISSUE TITLE
How to get horizontalGap for legend labels side by side

### ISSUE THREAD

**Issue by rferreira98** [amcharts/amcharts5#345]
Couldn't find anything in documentation nor amcharts5 github.
Term ```horizontalGap```turned up on amcharts4 github.

Is there a way to set the gap between legend labels. In order to occupy less space I would love to reduce the gap they have between each other. Vertical gap is acceptable but horizontal is very large.

![Screen Shot 2022-03-21 at 14 56 48](https://user-images.githubusercontent.com/24259712/159289061-93c95e80-c457-4ac8-96c7-0430a59af07f.png)

Setting ```horizontalGap: 0``` on legend setup does not work.

**Comment by martynasma** [comment]
Try this:

```JavaScript
legend.valueLabels.template.set("forceHidden", true);
```

**Comment by rferreira98** [comment]
Perfect! Thank you!
