### ISSUE TITLE
Radial Gradient - Issue with Negative radius

### ISSUE THREAD

**Issue by RT404** [amcharts/amcharts5#346]
**Question**

<!---

When implementing a **Radial Gradient** on a **Radar Chart** in Amcharts 5, the chart doesn't render, and the error given in the console is as follows:
_"ERROR DOMException: CanvasRenderingContext2D.createRadialGradient: Negative radius"_

        series.fills.template.setAll({
            visible: true,
            fillGradient: am5.RadialGradient.new(root, {
            stops: [{
                opacity: 1,
                color: am5.color(0xff0000),
            }, {
                opacity: 0.5,
               color: am5.color(0x0000ff),
            }],
        })
    });

**Of Note:** Switching over to a LinearGradient returns the chart without issue. The problem is occurring only with a RadialGradient.

**Additional info:**
- AmCharts5
- Framework Angular in .ts component.
- Issue in ALL browsers.

Thanks in advance for any help.

**Comment by RT404** [comment]
When using a Radar Chart with a Radial Gradient, the chart does not appear, and the console reveals the following error:

ERROR DOMException: CanvasRenderingContext2D.createRadialGradient: Negative radius

Of interest, when switching from a Radial to a Linear Gradient, the chart appears without issue.

        series.fills.template.setAll({
            visible: true,
            fillGradient: am5.RadialGradient.new(root, {
            stops: [{
                opacity: 1,
                color: am5.color(0xff0000)
            }, {
                opacity: 0.2,
                color: am5.color(0x0000ff)
            }],
        })
    });

**We are using:**
AmCharts5
Angular / .ts
Occurs in ALL browsers.

**Comment by martynasma** [comment]
What is a negative radius in this case? Would you be able to post an example of such chart on CodePen?
