### ISSUE TITLE
Chart jumps when created

### ISSUE THREAD

**Issue by DanielScholte** [amcharts/amcharts5#350]
**On creation of a chart, it jumps around for a few frames before it settles**

When creating a new chart, it jumps around for a few frames. Unsure if this is a global issue, but it happens consistently within Angular 12.  
The issue can be seen with a simple chart in the following CodeSandbox:
https://codesandbox.io/s/amcharts-5-initialization-bug-2320vu

On refreshing the page (or more easily visible by spamming `ctrl+s` to rebuild) it jumps around for a few frames.  
The issue is more striking when using a legend.

**Environment (if applicable)**
- Amcharts 5.1.9
- Angular 12.2.16
- Typescript 4.3.5

**Comment by martynasma** [comment]
The jumping can be fixed by applying `appear()` method to the chart:

```JavaScript
chart.appear(1000, 100);
```
