### ISSUE TITLE
Tooltips goes missing ....

### ISSUE THREAD

**Issue by flat-linex** [amcharts/amcharts5#352]
I'm modifying one of the examples provided by Amcharts (5) in their download package ([xy-line-highlight-on-legend-hover](https://www.amcharts.com/demos/highlighting-line-chart-series-on-legend-hover/)) by using am5.net.load to load data from a csv file [data_pc.csv](http://osservatorio.energia.provincia.tn.it/APRIE/OPENDATA/data_pc.csv) and the zip file ([index.zip](https://github.com/amcharts/amcharts5/files/8343026/index.zip)) includes the modified index.js that is currently used at [http://osservatorio.energia.provincia.tn.it/charts/amcharts5/examples/APRIE-ss-pc/](url):
everything is working apart from the tooltips that have gone missing in action.
My modifications to the series/data of the original example are:
- only 3 series
- the name of the value field of each series is different (and corresponds to the name of the series): I read a single csv file for all of them and this way each of them can extract its own data when I invoke `my_series[i].data.setAll(data2);`

Any hint on what I am doing wrong?
Thanks a lot

**Comment by xorspark** [comment]
The issue is that you're setting `reverse` to true in your parser. The data is already in correct order (ascending), so setting reverse to true is not needed and will cause issues with tooltips.

**Comment by flat-linex** [comment]
That was it! Thx a LOT!
