### ISSUE TITLE
Setting XYchart attribute interactive = true disables zoom out

### ISSUE THREAD

**Issue by ccrasmus** [amcharts/amcharts5#353]
**Bug description**

Setting XYChart interactive = true disables/breaks the chart.zoomOutButton.

The expected behaviour for us is that the chart is interactive (i.e. buttons work) if that setting is true, and that they are disabled if the setting is false.

This is amplified if the cursor is set to not be dashed and have a width, the zoomOutButton appears to be blocked by the cursor. 
With a default cursor the button works if the mouse pointer is not placed on the cursor-line.

It's reproduceable in the codepen demo for https://www.amcharts.com/demos/simple-column-chart/ with the following change:
```
var chart = root.container.children.push(am5xy.XYChart.new(root, {
  panX: false,
  panY: false,
  wheelX: "panX",
  wheelY: "zoomX",
  interactive: true
}));
```

Set width of cursor stroke for more severe issues.
```
cursor.lineX.setAll({
  stroke: am5.color(0x000000),
  strokeWidth: 100,
  strokeOpacity: 0.2,
  strokeDasharray: []
});
```

**Comment by ccrasmus** [comment]
Thanks you for the reply, i wonder if i'm having issues with this due to semantics or language.

Do you mean that if the attribute "interactive" (or root._renderer.interactionsEnabled) is set to true that will disable all interactivity? Isn't that semantically/logically reversed? 

The documentation says that setting the attribute to true it will accept user interaction.
https://www.amcharts.com/docs/v5/reference/chart/#interactive_setting

For our specific case we don't need to disable the interactivity, and can achieve it by other means,  so we don't have an issue currently. But i thought this was a bug/might cause issues in the future, since the zoomOutButton breaks when setting the attribute on chart.

I made a fiddle if you are interested to see it: https://jsfiddle.net/93v5uczg/

**Comment by martynasma** [comment]
> Do you mean that if the attribute "interactive" (or root._renderer.interactionsEnabled) is set to true that will disable all interactivity? Isn't that semantically/logically reversed?

Gah, yeah, my bad. It's supposed to be `false` :)
