### ISSUE TITLE
 Legend label text overlaps

### ISSUE THREAD

**Issue by takutok** [amcharts/amcharts5#355]
If many characters in legendValueText,  legend label  will overlap.

![legend2](https://user-images.githubusercontent.com/1034808/160414982-5c82fe71-0f0d-4912-9016-8739b65aca76.png)

I also tried gridLayout, but I can't find a way around it.
Recalculate coordinates including legendValueText, or
want to reserve display area even with [width: xxx].

or Currently, in gridLayout,  child elements are not evenly spaced inside width.
One of the ideas add an option to specify the number of columns. The width is divided into equal intervals and displayed. not maxColumns.

 - amCharts version
 amCharts 5 (main package)	5.1.9
 Geodata (maps)	5.0.2
 Fonts	5.0.1

**Comment by takutok** [comment]
https://codepen.io/takutok/pen/YzYQXvJ

I changed  text values ​​of legendValueText and legendRangeValueText.

**Comment by zeroin** [comment]
You can solve this issue by setting:

`legend.valueLabels.template.set("width", null)`

default value is 50.

**Comment by takutok** [comment]
Thank you for the solution.
I want you to adjust the width automatically if possible.
Please close this.
