### ISSUE TITLE
want to set tooltipDateFormats for CategoryDateAxis

### ISSUE THREAD

**Issue by takutok** [amcharts/amcharts5#356]
I found tooltipDateFormats in DateAxis. I also want to use it in CategoryDateAxis.
I tried it with Data placeholders, but the parameters didn't work.

https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#base-interval-based-format

**Comment by martynasma** [comment]
If you need to skip empty periods, I suggest you use `GaplessDateAxis` instead.

It supports `tooltipDateFormats`.

https://www.amcharts.com/docs/v5/charts/xy-chart/axes/gapless-date-axis/

**Comment by martynasma** [comment]
> It seems not compatible with CategoryDateAxis. Investigate the cause of it problem.

Yup. `CategoryDateAxis` works as a `CategoryAxis`.

`GaplessDateAxis` works as `DateAxis`, and should be configured as such, including using proper field descriptors in series (`valueXField` vs `categoryXField`).

**Comment by takutok** [comment]
Replacement has been resolved.
Please close this.
