### ISSUE TITLE
Can one make line series not overlap column series?

### ISSUE THREAD

**Issue by rferreira98** [amcharts/amcharts5#357]
**Question**

I have a stacked column chart which has a darker color on the below values and brighter one on the upper values(these ones are irrelevant, they're for design purposes).
And I also have a line series that overlaps these columns. What I'm trying to achieve is the line series just follow darker column values and stay on top of those instead of rendering in the middle of the chart.

Desired result is something like this:

![image](https://user-images.githubusercontent.com/24259712/161028307-eec64d1b-7e5b-46ef-b271-b62eeb6da44e.png)

Here's a codesandbox for this example: https://codesandbox.io/s/line-over-column-o6r46p

**Environment**

amCharts version:     "@amcharts/amcharts5": "^5.1.9"
React version:    "react": "^17.0.2"

**Comment by martynasma** [comment]
Why not make the LineSeries use all the same data fields and axes?

```JavaScript
    var lineSeries = chart.series.push(
      am5xy.SmoothedXYLineSeries.new(root, {
        name: "Series",
        xAxis: xAxis,
        yAxis: yAxis,
        valueYField: "value",
        valueXField: "date",
        valueYShow: "valueYTotalPercent",
        stroke: am5.color("#ff0000")
      })
    );
```

It will follow darker column's tops.

**Comment by rferreira98** [comment]
Doing so the chart size shifts up, like it's stacking 2 series vertically.

**Comment by martynasma** [comment]
Gotcha. So solution is to replicate the whole setup (Y axis, two series) for the line series as well.

Here's modified demo:
https://codesandbox.io/s/line-over-column-forked-k5i4qu

Hope the code makes sense.

**Comment by rferreira98** [comment]
Perfect, as usual. Thank you so much, for the effort and for the solution as well!
