### ISSUE TITLE
'hiddenInLegend' not available in amcharts5

### ISSUE THREAD

**Issue by erYasar** [amcharts/amcharts5#361]
[hiddenInLegend](https://www.amcharts.com/docs/v4/tutorials/toggling-multiple-series-with-a-single-legend-item/#Hiding_series_from_legend)

Looking for equivalent hiddenInLegend in amcharts 5?

**Comment by martynasma** [comment]
There's no need for that in amCharts 5 since you are setting legend's `data` manually, so you can control which series to include there.

E.g.:

```JavaScript
legend.data.setAll(series1, series3);
```
