### ISSUE TITLE
Making series without any initial x/y axis and root

### ISSUE THREAD

**Issue by BdDragos** [amcharts/amcharts5#362]
Hello there,
I am currently doing the update from amcharts4 to amcharts5 for some big and full of options generic charts.
Before in the old version it was possible for me to create standalone series. (new LineSeries(), new ColumnSeries() and so on), without setting an initial axis or setting a root element. These generic series I passed later to a chart that pushed them to its array and assigned xAxis and yAxis to them before being pushed according to some conditions.

Right now when I try to create this:

LineSeries.new(chartRoot, {
      name: "Series",
      xAxis: undefined,
      yAxis: undefined,
      valueYField: "rate",
      valueXField: "date",
      categoryXField: "category",
      fill: color(this.barColors[0]),
      stroke: color("#000000"),
    });
    
I receive:
-> TypeError: Cannot read properties of undefined (reading 'series') 
-> TypeError: Cannot read properties of undefined (reading 'getPrivate')

Since a page can have multiple charts, there can be multiple axis and the series are created in a parent component (using Angular) and passed to a child one (the chart itself), how can I make some generic series? It would also help if I could remove the chartRoot element since I needed to do some complicated Output logic to predict when all the charts will be rendered.,

**Comment by zeroin** [comment]
Sorry, but it is not possible, an axes should be set for the series to work.

**Comment by BdDragos** [comment]
I see. I already found a workaround to wait for the charts to load and to emit to the parent component the axes and the root so I can draw them after. Unfortunately this downgrade from amcharts 4 is pretty bad, hopefully it will be possible in the future to create standalone series and setting the root and the axes later.
