### ISSUE TITLE
Column Series Legend for y axis category

### ISSUE THREAD

**Issue by erYasar** [amcharts/amcharts5#366]
I am trying to use column series as gantt chart. i am trying to list the y axis data items as legends like Donald,Melania, Peter,Jane and John

Actual:
![image](https://user-images.githubusercontent.com/11607757/162957243-3609b007-6563-476f-8b9e-a95162fc5709.png)

In amcharts 4, achieved this with 'dataitemsvalidated' event. Not sure how it can be done for amcharts 5. i don't see any events exposed.

**Comment by zeroin** [comment]
Do you need the legend to show a separate item for a category of for a column?

**Comment by erYasar** [comment]
@zeroin exactly!

**Comment by zeroin** [comment]
Then I would recommend simply to provide data for the legend, as series will have more data items (a separate for each column), and categoryAxis data items won't be good, as they will not contain color information.

Here is more info: https://www.amcharts.com/docs/v5/concepts/legend/#standalone-data

**Comment by erYasar** [comment]
> Then I would recommend simply to provide data for the legend, as series will have more data items (a separate for each column), and categoryAxis data items won't be good, as they will not contain color information.
> 
> Here is more info: https://www.amcharts.com/docs/v5/concepts/legend/#standalone-data

in that case i would not able to toggle the legends right ?

**Comment by zeroin** [comment]
Right. the only way to keep the toggling feature would be to add a separate series for each different category and then pass data to the legend in the usual way: `legend.data.setAll(chart.series.values)`

**Comment by erYasar** [comment]
> Right. the only way to keep the toggling feature would be to add a separate series for each different category and then pass data to the legend in the usual way: `legend.data.setAll(chart.series.values)`

If we do this we will get one legend item for series. My concern is to have categorie data items in the legend as mentioned in the issue.

**Comment by zeroin** [comment]
Now you have one series for all data items. You could create many series and each of the series would only have data items for one category. Note, even you will do this, hiding the series through legend won't result category to be hidden, there is no such a feature as to hide category of the axis.

**Comment by erYasar** [comment]
> Now you have one series for all data items. You could create many series and each of the series would only have data items for one category. Note, even you will do this, hiding the series through legend won't result category to be hidden, there is no such a feature as to hide category of the axis.

hiding category is possible in amcharts 4.
![image](https://user-images.githubusercontent.com/11607757/163556210-8cba31f0-c671-4655-ad69-cf1a10cf8e13.png)
![image](https://user-images.githubusercontent.com/11607757/163556265-d7b8eb5e-bb84-426d-a676-fba1dba1156d.png)

`serie.events.on('dataitemsvalidated', function () {
            const categoryYData = [];
            const legendData = [];
            serie.dataItems.each(function (dataItem) {
                const item = categoryYData.find((i) => i.name === dataItem.categoryY);
                if (!item) {
                    categoryYData.push({ name: dataItem?.categoryY, fill: dataItem?.column?.fill, seriesDataItems: [dataItem] });
                    return;
                }
                item.seriesDataItems.push(dataItem);
            });

            if (!chart.legend) {
                return;
            }
            chart.legend.data.forEach((dataItem) => {
                if (dataItem._yField !== ChartAxisType.CategoryY) {
                    legendData.push(dataItem);
                }
            });

            if (categoryYData.length > 0) {
                legendData.push(...categoryYData);
            }

            chart.legend.data = legendData;

            chart.legend.itemContainers.template.events.on('toggled', function (event) {
                const context = event.target.dataItem.dataContext;
                const isActive = event.target.isActive;

                if (!context.seriesDataItems) {
                    if (isActive) {
                        context.hide();
                    } else {
                        context.show();
                    }
                    return;
                }

                context.seriesDataItems.forEach((seriesDataItem) => {
                    if (isActive) {
                        seriesDataItem.hide();
                    } else {
                        seriesDataItem.show();
                    }
                });
            });
        });`
        
        I am expecting the same in amchart5 but i could not find any events similar to this.

**Comment by zeroin** [comment]
Could you create a working codepen in v4 so I could see how it works? As I think it will hide columns only, but the category will remain.

**Comment by erYasar** [comment]
> Could you create a working codepen in v4 so I could see how it works? As I think it will hide columns only, but the category will remain.

Example shared:
https://codepen.io/eryasar/pen/qBpLrML?editors=0010

**Comment by zeroin** [comment]
So it's like I guessed, you hide columns, not the category itself, so my suggestion stands - you can have separate series for each category and set series as a data for your legend.

**Comment by erYasar** [comment]
> I guessed, you hide columns, not the category itself, so my suggestion stands - you can have separate series for each category and set series as a data for your legend.
any other options i can't make it individual series.
@martynasma @zeroin

**Comment by zeroin** [comment]
Sure, you can use this event if you want, but I don't see how it would benefit in your case.

**Comment by erYasar** [comment]
> Sure, you can use this event if you want, but I don't see how it would benefit in your case.


Could you help me with codepen for individual series. 

i am not sure how to category y axis as individual item when there are more series.

**Comment by erYasar** [comment]
@zeroin any updates on this?

**Comment by zeroin** [comment]
Here it is: 
https://codepen.io/team/amcharts/pen/zYpbzKV/8d28ac1ce3463ae70f2de70081fa85f8

**Comment by erYasar** [comment]
@zeroin Thanks it works like charm.

I would like to  know how to reduce the size of the series respective to category and center alignment.
![image](https://user-images.githubusercontent.com/11607757/164417603-9b61c6d1-f656-455d-8bbc-24644c0c508a.png)

**Comment by zeroin** [comment]
You should set `clustered:false` on all series.
