### ISSUE TITLE
Unable to set theme

### ISSUE THREAD

**Issue by lukedukeus** [amcharts/amcharts5#367]
I am getting the following errors when I try to apply a theme:
```
am5themes_Animated.new is not a function
TypeError: theme._lookupRules is not a function 
```

demo: https://codesandbox.io/s/lucid-water-5v6hqt?file=/src/App.js

I am using nextjs with am5 and chrome

the code in question:
```    
var theme = am5themes_Animated.new(root);
root.setThemes([theme]);
```

Please let me know what I am doing wrong!

**Comment by xorspark** [comment]
You need to access the `new` method through the `default` property to work around the error. Changing the require line should be enough:

```
am5themes_Animated = require("@amcharts/amcharts5/themes/Animated").default;
```

**Comment by lukedukeus** [comment]
Thanks, That works!

**Comment by neapolis79** [comment]
> You need to access the `new` method through the `default` property to work around the error. Changing the require line should be enough:
> 
> ```
> am5themes_Animated = require("@amcharts/amcharts5/themes/Animated").default;
> ```

thanks a lot worked also for me....in the documentation was not mentioned
