### ISSUE TITLE
Date Axis Base Interval count property is not optional as docs state

### ISSUE THREAD

**Issue by bryceremick** [amcharts/amcharts5#375]
**Bug description**

The docs clearly state that the `count` property in `baseInterval` on a `DateAxis` is **optional**, however my editor indicates that it is a required parameter.

Doing This:
```typescript
am5xy.DateAxis.new(this.root, {
        baseInterval: { timeUnit: 'millisecond', /* count */ },
        groupData: true,
        renderer: am5xy.AxisRendererX.new(this.root, {}),
      }),
``` 
Gives this syntax error:
<img width="514" alt="Screen Shot 2022-04-18 at 11 00 32 AM" src="https://user-images.githubusercontent.com/17426081/163852343-c4cac025-1951-40c7-b27c-aa7beb9837b2.png">

This is the interface declared in `Time.d.ts`:
```typescript
export interface ITimeInterval {
    timeUnit: TimeUnit;
    count: number;
}
```

Clearly `count` is not an optional property as the docs state. 

[Link to Docs](http://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#Data_granularity)

**Environment**

 - amCharts version: 5.1.13
 - Browser and its version: N/A
 - Related frameworks and their versions: `vue - 3.2.31`, `typescript - 4.5.5`

**Comment by martynasma** [comment]
Thank you for pointing this discrepancy in docs! It has been fixed.
