### ISSUE TITLE
Forcedirected Hierarchy must have a hidden root node - why?

### ISSUE THREAD

**Issue by wernerdaehn** [amcharts/amcharts5#376]
Summary of my complaint:
1. Inconsistency: Tree and ForceDirected render the same data object differently. In the first the root node is visible, in the latter it is not
2. ForceDirected requires an artificial root node under which all visible elements are added as children.
3. Support data.setAll() with arrays and objects as parameters.

Details:

Looking at your provided example
https://codepen.io/team/amcharts/pen/OJmoWzR
the data consists of 
```
[{
  name: "Root",
  value: 0,
  children: [{
    name: "A0",
```
and it renders A0, not the Root. In contrast the Tree example does not require the "Root" node, the array with A0, B0, C0 is enough.
Or in other words, Tree renders the root node, Forcedirected does not. This is inconsistent, isn't it?
https://codepen.io/team/amcharts/pen/poPxojR

Frankly, as I user I would like to provide either an array [] of nodes or a root {} node as data and in all charts the visible elements should be the same. So data.setAll() should work with objects and arrays as parameters.

In my case the data comes from a database backend and I had to wrap the Json data into the expected format. And differently for Tree and Forcedirected. I started with the Tree and the data had to be [ A0, B0, C0 ], then I switched to ForceDirected and the data required to render it correctly was [ {name: "root", children: [ A0, B0, C0 ] }

**Comment by zeroin** [comment]
It's all in the configuration. In the force directed example, there is this setting:

`topDepth: 1`

It makes the root node not to be rendered.

In a Tree example you have:

`topDepth: 0` 

this makes the top depth to be visible.

As for the data, I am afraid we are not going to change that, a single top node must be present, but you can play with topDepth setting to achieve what you expect.
