### ISSUE TITLE
Range gradient

### ISSUE THREAD

**Issue by Mikanoshi** [amcharts/amcharts5#378]
Is it possible to make strokeGradient of a range to have step offsets 0 and 1 correlated with the start and end of a range itself, not the whole chart? Zooming chart in/out changes the gradient otherwise, which makes it pretty useless as it no longer represents the data correctly.
https://codepen.io/Mikanoshi/pen/MWrxKZp

**Comment by zeroin** [comment]
Unfortunately I don't see any possibilities to make this work.

**Comment by zola-25** [comment]
I have this problem too. I'm trying to have a temperature scale from hot (red) to cold (blue) but as soon as you zoom in suddenly everything with only a few degrees difference comes either red or blue.
