### ISSUE TITLE
Specify range of  Y axis when all data are zero.

### ISSUE THREAD

**Issue by takutok** [amcharts/amcharts5#379]
If all data is 0, I want to specify the range of the Y axis so that display does not look strange compared to the case where it is value.

I also tried using ValueAxis.max.
The display axis has been fixed.
However, If there is value that exceeds max, it will not be displayed properly.

Normal: https://codepen.io/team/amcharts/pen/vYmyqGJ
![amchart01](https://user-images.githubusercontent.com/1034808/164342698-01755d11-1c86-468f-bb85-3b6c7315188c.png)

When all data are zero: https://codepen.io/takutok/pen/abEMmYL
![amchart02](https://user-images.githubusercontent.com/1034808/164342740-cce6d25d-2861-4ba6-8648-e36a72115982.png)

When max is specified: https://codepen.io/takutok/pen/LYeaRgr
![amchart03](https://user-images.githubusercontent.com/1034808/164342772-7c654aa6-b0e8-43fe-b0e6-41e2229a60e0.png)

Is there a way to specify axis scale that is valid only when the data is zero?

 - amCharts version
5.1.13

**Comment by xorspark** [comment]
You can use the `datavalidated` event on the last series to adjust your axis based on your data values.

```
series2.events.on('datavalidated', () => {
  if (data.every((item) => item.value1 == 0 && item.value2 == 0)) {
    yAxis.set('max', 2500);
  }
  else {
    yAxis.set('max', undefined);;
  }
});
```
