### ISSUE TITLE
Tooltip for multi points not available when hover

### ISSUE THREAD

**Issue by erYasar** [amcharts/amcharts5#380]
Tooltips are not available when hover.
For example below screenshot, tooltip displayed only on the mouse pointer. but cursor has multiple has selection of multiple elements.
![image](https://user-images.githubusercontent.com/11607757/164450415-ef691a8b-1314-41ff-b10c-dfabd4346c92.png)

Expected: Something as below based on the cursor position need to display all the tooltips.
![image](https://user-images.githubusercontent.com/11607757/164450667-d5241e6d-17ee-415a-b01e-dbb1581da715.png)

Let me know how can i achieve this?

**Comment by zeroin** [comment]
No, with Gantt chart you can not have this.
