### ISSUE TITLE
How to dynamically change theme?

### ISSUE THREAD

**Issue by zdm** [amcharts/amcharts5#381]
Is it possible to do this without re-create root and without current data loss?

**Comment by martynasma** [comment]
I'm afraid dynamic change of themes is not supported.

**Comment by zdm** [comment]
And never be added?

Please, answer and close this issue.

Thank you.

**Comment by martynasma** [comment]
> And never be added?

Never say never, right? :)

At this point we do not have any plans on implementing it. But who knows what future will bring.

**Comment by zdm** [comment]
Understood.

**Comment by zdm** [comment]
Still not possible?

**Comment by martynasma** [comment]
@zdm Nope

**Comment by nehamangal123** [comment]
now is it possible?
@martynasma
