### ISSUE TITLE
Empty columns taking unnecessary space

### ISSUE THREAD

**Issue by rferreira98** [amcharts/amcharts5#382]
**Question**

When I'm using a stacked + clustered chart the columns that are not present on all categories take unnecessary space and ruin the charts.

I want to have all the bars as close as possible instead of having big white spaces between them, like on the example on amcharts 5 website.

**Environment (if applicable)**

https://codesandbox.io/s/empty-columns-space-g9hdj7

**Comment by martynasma** [comment]
I'm afraid there's no way to collapse space reserved for zero-value columns.

**Comment by rferreira98** [comment]
Is there another way I can achieve the same result? with a different setup?

**Comment by martynasma** [comment]
Well, you could have different category for each column/stack. Then group them using axis ranges.

Something like in this demo:
https://www.amcharts.com/demos/grouped-and-sorted-columns/
