### ISSUE TITLE
Trends lines don't have tooltip and pie chart in Micro chart sparkline

### ISSUE THREAD

**Issue by Jainsdev** [amcharts/amcharts5#383]
We are using Micro Charts Sparklines(amchart V4- https://www.amcharts.com/demos-v4/micro-charts-sparklines-v4/). Now we want to use the same functionality in amchart V5 by using https://www.amcharts.com/demos/micro-charts-sparklines/, but we didn't find the same functionality which we have in V4. For Example:- In V5 we didn't find trend lines with tooltip and pie chart also.
Could anyone please provide some solution to that?

**Comment by martynasma** [comment]
Well, you just need to add XYCursor to those charts, as well as set up tooltips for series:
https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/

Here's an example:
https://codepen.io/team/amcharts/pen/jOYRVVM/52db7407bbbbe7ec98be48d3c1ef096e?editors=0010

You can add Pie chart just like you would add any pie chart. However, for a very small chart, the tooltip might not fit.
