### ISSUE TITLE
heatRules does not accept any value for the dataField setting other than 'value'

### ISSUE THREAD

**Issue by Jake-Thomas-Hall** [amcharts/amcharts5#384]
**Bug description**

When setting the value field for `heatRules` to use within a `MapPolygonSeries` - it does not seem to accept any value for the `valueField` apart from 'value', even when the value field is set to be looking at another value within the series setup and the provided data.

Given this series setup:

```ts
    this.series = this.chart.series.push(
      MapPolygonSeries.new(
        this.root, {
        geoJSON: am5geodata_worldLow,
        exclude: ["AQ"],
        valueField: "test",
        calculateAggregates: true,
        fill: color("#d1d1d1")
      }
      )
    );
```

The heatRules setup:

```ts
    this.series.set("heatRules", [{
      target: this.series.mapPolygons.template,
      dataField: "value",
      min: color("#eda6b0"),
      max: color("#EE334E"),
      key: "fill"
    }]);
```

And some data: 

```ts
    this.series.data.setAll([
      {
        id: 'FR',
        test: 500,
        CountryID: 67
      },
      {
        id: 'ES',
        test: 1000,
        CountryID: 170
      },
      {
        id: 'GB',
        test: 1500,
        CountryID: 191
      }
    ]);
```

It produces a map with heat highlighting:

![image](https://user-images.githubusercontent.com/25041735/164988525-9ae80666-70f1-4769-9cf9-37115af6a3ef.png)

However, as soon as you change the heatRules to expect the value in the `test` field:

```ts
    this.series.set("heatRules", [{
      target: this.series.mapPolygons.template,
      dataField: "test",
      min: color("#eda6b0"),
      max: color("#EE334E"),
      key: "fill"
    }]);
```

It no longer works:

![image](https://user-images.githubusercontent.com/25041735/164988569-ac63aad3-c933-424c-8076-43dc422d8b9d.png)

This seems like odd behaviour? Especially when the docs for the `IHeatRule` interface specify this:

![image](https://user-images.githubusercontent.com/25041735/164988668-7c446712-6f7e-4714-b3f4-13763214b53c.png)

**Environment**

- amCharts 5.1.14
- amCharts-geodata 5.0.3
- Angular 13.3.1
- Typescript 4.4.3

**Comment by Jake-Thomas-Hall** [comment]
To add onto this; I'm running into an issue where I'm setting the data later after a HTTP call, which is resulting in an issue where the map just doesn't load then... I'm guessing that isn't a bug though and is just me not understanding something properly.

**Comment by zeroin** [comment]
This is not od behavior, it's by design. `test` is a name of your data field in your raw data and then you tell your series that it should use it to get `value`: `valueField: "test"` When processing data and creating data items it sets "value" to be the same as your "test" in your raw data. And then the heat rule is applied we do not look at the raw data at all, just at the dataItem. 

In case for some reason you need to use some different value, then instead of heat rules you should create your custom adapter for fill and then access your original data through `dataItem.dataContext.text`, dataContext is a reference to your original data object.

**Comment by Jake-Thomas-Hall** [comment]
Ah I see, thank you for explaining.

This really should be made clearer in the docs somewhere, I was highly confused.
