### ISSUE TITLE
How can I get the name of column stack on stacked column charts?

### ISSUE THREAD

**Issue by byseop** [amcharts/amcharts5#387]
How can I get the name of column stack on stacked column charts?

[here is the example code](https://codepen.io/byseop/pen/oNprWoq?editors=1111)

If I click on a stack a particular column, I want to get name of the stack.
for example, If I click the Asia stack, I want to get 'Asia'.

Is there any way how find out?

**Comment by xorspark** [comment]
You can access the series through the event target dataItem's component property. From there you can call `get` to retrieve the series name:

```
  series.columns.template.events.on('click', (e) => {
    console.log(e.target.dataItem.component.get('name'));
  });
```

**Comment by byseop** [comment]
@xorspark 
```javascript
serie.columns.template.events.on('click', (e) => {
  console.log(e.target.dataItem?.component.get('name'));
});
```
This works well, but there is a type check issue.
`Argument of type '"name"' is not assignable to parameter of type 'keyof IComponentSettings'`

So I changed the code a little bit and used it as below
```typescript
serie.columns.template.events.on('click', (e) => {
  console.log(e.target.dataItem?.component.get('name' as any));
});
```
The desired feature works, but can I solve this type check issue?

**Comment by xorspark** [comment]
The documentation for [dataItem.component](https://www.amcharts.com/docs/v5/reference/dataitem/#component_property) states that the component is the data item's owner; in this case the owner is the series associated with the data item. Casting it as the ColumnSeries should do the trick.

```
console.log((e.target.dataItem?.component as am5xy.ColumnSeries).get('name'));
```
