### ISSUE TITLE
Sum label inside a donut chart is not updating

### ISSUE THREAD

**Issue by mcourteix** [amcharts/amcharts5#390]
**Bug description**

With amChart 5, when toggling on elements of the legend of a pie chart, the sum of the values inside the donut chart is not updating. Is it a bug or a new behavior ?

To illustrate :

Code pen of tutorial [Sum label inside a donut chart V5](https://www.amcharts.com/docs/v5/tutorials/sum-label-inside-a-donut-chart/) --> when clicking on one element of the legend, the sum is not updated

Code pen of tutorial [Sum label inside a donut chart V4](https://www.amcharts.com/docs/v4/tutorials/sum-label-inside-a-donut-chart/) --> when clicking on one element of the legend, the sum is updated

**Environment (if applicable)**

 - amCharts 5.1.14
 - React 18.0.0

**Comment by zeroin** [comment]
Thanks for the heads up, I updated the codepen so it now does the thing.
I added the following lines:
```
series.onPrivate("valueSum", function(){
  label.text.markDirtyText();
})
```

and also some formatting of the number to avoid numbers after comma.

**Comment by mcourteix** [comment]
Thanks @zeroin for your high reactivity !
Have a nice day !
