### ISSUE TITLE
Tooltip format not showing proper suffix for small numbers

### ISSUE THREAD

**Issue by aniznik1** [amcharts/amcharts5#393]
**Bug description**

Reproduce: [https://codepen.io/aniznik/pen/rNpXydb](https://codepen.io/aniznik/pen/rNpXydb)

You will see the second element has the proper suffix as it is a very large number.
The third element will display `280m` but I would expect to see it display `0.28` with no prefix.

**Comment by xorspark** [comment]
There are two ways to remove the prefix for the small number:

1) Set `smallNumberPrefixes` to an empty array in   the root object's number formatter [(docs](https://www.amcharts.com/docs/v5/concepts/formatters/formatting-numbers/#Custom_big_small_number_grouping)):

```
root.numberFormatter.setAll({
  // Do not use small number prefixes at all
  smallNumberPrefixes: []
});
```

or

2) Set the `smallNumberThreshold` to a small threshold such that the formatter will only kick in when the value is smaller than your threshold ([docs](https://www.amcharts.com/docs/v5/concepts/formatters/formatting-numbers/#Small_number_threshold))

```
root.numberFormatter.setAll({
  // only format small numbers less than 0.001
  smallNumberThreshold: 0.001
});
```
