### ISSUE TITLE
Legend text is too long

### ISSUE THREAD

**Issue by sknhkrn** [amcharts/amcharts5#394]
Hi, how to shorten or hide some words on the legend text?
Currently, it is as shown below:

![image](https://user-images.githubusercontent.com/57323027/165658631-3de19cc4-c00a-435c-8917-075237d8cbf8.png)

Is it possible to make it like this ? note: This is how the legend in am4charts:

![image](https://user-images.githubusercontent.com/57323027/165658812-b80d2f97-9260-4d46-9527-9b72b1a8045b.png)

Thank you in advance.

**Comment by xorspark** [comment]
You have to set the [`oversizedBehavior`](https://www.amcharts.com/docs/v5/concepts/common-elements/labels/#behavior) on the legend labels template to `"truncate"` along with the desired `maxWidth`:

```
legend.labels.template.setAll({
  oversizedBehavior: 'truncate',
  maxWidth: 200
});
```

[Demo](https://codepen.io/team/amcharts/pen/yLpmEvL/1a9ceda419e397aeddebf2e4e1938ef1?editors=0010)

**Comment by sknhkrn** [comment]
Hi, thank you for the solution. It works well now.
