### ISSUE TITLE
"valueSum" in amCharts5 calculate in a different way then {values.value.sum} in amcharts4

### ISSUE THREAD

**Issue by wechselstube** [amcharts/amcharts5#395]
**Question**

Hello, I would like to sum the values of a PieCharts, for this I also found the necessary information in the doc. However, the function in amCharts5 sums differently than in amCharts4. Especially if some slices are deactivated via the legend.

I have created an example in the CodeSandbox.

https://codesandbox.io/s/late-pine-8kq6ud?file=/src/app/app.component.ts

Doc Link:
https://www.amcharts.com/docs/v5/reference/ipercentseriesprivate/#valueSum_property

Doc Example (amCharts5):
https://www.amcharts.com/docs/v5/tutorials/sum-label-inside-a-donut-chart/

Doc Example (amCharts4):
https://www.amcharts.com/docs/v4/tutorials/sum-label-inside-a-donut-chart/

**Environment (if applicable)**

**Additional context**

**Comment by xorspark** [comment]
The demo has been updated per https://github.com/amcharts/amcharts5/issues/390. The following was added to the demo in order to update the text:

```
series.onPrivate("valueSum", function(){
  label.text.markDirtyText();
});
```

**Comment by waahhhh** [comment]
First of all, thanks for the temporary fix.  

The behavior should still be considered as a bug.  
Injecting a fix to update a defined label is not a solution.  
Ps. This fix also fixes rendering problems when toggling single elements.

**Comment by zeroin** [comment]
No, it's not a bug, it's by design, we are not fixing it.
