### ISSUE TITLE
Scrollbar issue

### ISSUE THREAD

**Issue by erYasar** [amcharts/amcharts5#397]
After integrating scrollbar, could not render chart properly.

https://codepen.io/eryasar/pen/bGaXVvw

`
var sbxAxis = scrollbarX.chart.xAxes.push(
  xAxis
);

`

instead of xAxis , when explicitly create the axis it worked. i am not sure why the already created axis cannot be used here.

**Comment by martynasma** [comment]
Same axis cannot be used across two chars (`XYChartScrollbar` is a chart in itself). You need to create a new axis for it.

**Comment by erYasar** [comment]
@martynasma is there any option to copy existing axis and recreate a new axis?

**Comment by martynasma** [comment]
> @martynasma is there any option to copy existing axis and recreate a new axis?

No, I'm afraid.
