### ISSUE TITLE
ForceDirected Circle Fill?

### ISSUE THREAD

**Issue by labriola** [amcharts/amcharts5#4]
Docs seem to show that we can manipulate the circles of a ForceDirected Chart like any other... most properties seem to work, however, I cannot find any combination of manual settings, nor templateField that will ever let me change the fill color of these circles from default.

```
series.circles.template.setAll({
  fill : am5.color(0x67B7DC)
});
```

Is this a bug is there just a more obscure way of doing this related to the hierarchical data? Tried hooking templates for nodes as well but so far with no luck.

**Comment by zeroin** [comment]
Chart assigns colors for each data item automatically from `colors`  of the series and overrides the ones set in template. So I see two ways to solve this:

1) modify colors array:
`series.get("colors").setAll({colors: [am5.color(0xff0000)], reuse:true})`

2) add adapter which will override a color:
```
series.circles.template.adapters.add("fill", ()=>{
  return am5.color(0xff0000)
})
```

**Comment by labriola** [comment]
Thanks. I will give the adapter route a try. I appreciate all the hard work on this.

I do believe its worth pointing out then that this is both a documentation issue: 

> Circles
> circles.template can be used to configure node circles. All nodes have them.
> The template accepts all Circle settings.
> 

And likely some form of enhancement request as it seems unlikely those upgrading from 4 are going to be okay losing the ability to configure this in a templated way... Also though, this makes this chart work differently than the others, which is certainly a barrier to learning this complex library.

Cheers

**Comment by martynasma** [comment]
We're just in first stage of our docs development for amCharts 5.

Your suggestion does make sense. We're going to consider adding a note about it to ForceDirected docs. Thanks!

**Comment by martynasma** [comment]
FYI: https://www.amcharts.com/docs/v5/charts/hierarchy/hierarchy-node-colors/
