### ISSUE TITLE
calculateAggregates not working in RadarColumnSeries

### ISSUE THREAD

**Issue by wernerdaehn** [amcharts/amcharts5#404]
I have copied your demo RadarChart for the "cycled per year" and I am trying to simplify it as much as possible.
(Goal is to integrate amCharts with the SAPUI5 framework - the entire SAP community would be in desperate need of amChart like visualizations)

One thing I noticed is that the `calculateAggregates: true` does not seem to have an effect.
To make that more obvious I have reduced the data items to just three, two identical rides with 15k on one day and a 30k ride in a different week. I have removed all the functionality to aggregate the data manually, so this data is assigned directly.
As you can see no aggregation is happening, it does not even show three items. One week shows 15k, the other week 30k while actually both are 30k in sum per week.

https://codepen.io/wernerdaehn/pen/xxYxOjp

The RadarSeries has a valueaxis assigned, a dateaxis with a baseInterval of week so I would assume it does aggregate the values per week automatically.
I would really like to avoid preparing the data precisely as the series requires and aggregate the data manually upfront.

Thoughts?

**Comment by wernerdaehn** [comment]
<img width="354" alt="image" src="https://user-images.githubusercontent.com/13607767/166114923-032a6864-a545-4ddd-ab39-03ee7afbccc2.png">

```
var data = [
		{
			"Distance": 15000,
			"day": 1554595200000,
			"weekday": "Sun"
		},
		{
			"Distance": 15000,
			"day": 1554595200000,
			"weekday": "Sun"
		},
		{
			"Distance": 30000,
			"day": 1562112000000,
			"weekday": "Wed"
		}
	];
```

```
var distanceSeries = chart.series.push(
  am5radar.RadarColumnSeries.new(root, {
    calculateAggregates: true,
    xAxis: dateAxis,
    yAxis: distanceAxis,
    valueYField: "Distance",
    valueXField: "day",
    tooltip: am5.Tooltip.new(root, {
      labelText: "week {valueX}: {valueY}"
    })
  })
);

distanceSeries.data.setAll(data);
```

**Comment by zeroin** [comment]
If you expect values of the same date to be summed, then it's not what `calculateAggregates` does. And I don't see a way to do it within a chart, you'll have to pre-process your data and create a single data item for each date in order to see totals on the chart.

**Comment by wernerdaehn** [comment]
Thanks
