### ISSUE TITLE
Bottom Scrollbar - unused space 

### ISSUE THREAD

**Issue by erYasar** [amcharts/amcharts5#409]
When trying to integrate bottom scrollbars. there were unused space, how can solve the chart to occupy full space?

`let scrollbar = chart.get('scrollbarX') as am5xy.XYChartScrollbar;
    if (!scrollbar) {
      scrollbar = chart.set(
        'scrollbarX',
        am5xy.XYChartScrollbar.new(root, {
          orientation: 'horizontal',
          height: 30,
        })
      );
    }`

    `chart.bottomAxesContainer.children.push(scrollbar);`

![image](https://user-images.githubusercontent.com/11607757/166206908-60ef2b33-8952-4abd-88e9-9a9aa52f1c88.png)

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

Normally, there shouldn't be any gap.

**Comment by erYasar** [comment]
@martynasma , Please find the codepen https://codepen.io/eryasar/pen/OJQLOVq?editors=0010

**Comment by zeroin** [comment]
You have to create a separate x and y axes for the scrollbar. You are using the ones created for the chart, this won't work properly.
