### ISSUE TITLE
How to turn all fixed nodes into non-fixed ones on the force directed chart?

### ISSUE THREAD

**Issue by Mechman** [amcharts/amcharts5#411]
Hi!
For example here https://codepen.io/team/amcharts/pen/QWvVpeR I need to create a setInterval(function() ... which will turn A0,B0,C0 into unfixed.
Without redrawing the chart and resetting node positions.
The d3force should act on these nodes again. And all nodes become "alive".
How to do it?

**Comment by zeroin** [comment]
Here is a bit of a hack:

```
setTimeout(function() {
  am5.array.each(series.dataItems[0].get("children"), function(dataItem) {
    dataItem.set("x", undefined);
    dataItem.set("y", undefined);
    dataItem.get("d3ForceNode").fx = undefined;
    dataItem.get("d3ForceNode").fy = undefined;
  })
}, 1000)
```

We will handle this better in next release, it will be enough to set:

```
    dataItem.set("x", undefined);
    dataItem.set("y", undefined);
```

**Comment by Mechman** [comment]
Thank you. This only works for the first level of the node hierarchy.
How to do this for all levels?
Here is an [example ](https://codepen.io/mechman/pen/rNJVjKO). It has fixed elements A0A1 and A0A0A2.
It seems impossible to do without recursion. But how to do it in this case?

**Comment by zeroin** [comment]
Just get children of each dataItem and run the same thing on them. You can do this recursively until no children are found on the dataItem.

**Comment by Mechman** [comment]
Sorry, I'm not really familiar with JavaScript. I tried to do this, but I got an error.

index.js:1 Uncaught TypeError: t is not a function
    at Module.s (index.js:1:238342)
    at unfix (graph.js:535:17)
    at HTMLAnchorElement.onclick (VM918 index.html:232:75)

Here is the code:
`function tryto(target){
 each(target, function(dataItem) {
  free(dataItem);
  if(dataItem.get("children").length > 0) tryto(dataItem.get("children"));
  });
}

function free(item){
    item.set("x", undefined);
    item.set("y", undefined);
    item.get("d3ForceNode").fx = undefined;
    item.get("d3ForceNode").fy = undefined;
}

tryto(am5.array.each(series.dataItems[0].get("children")));`
