### ISSUE TITLE
StockChart pan event

### ISSUE THREAD

**Issue by alienbuild** [amcharts/amcharts5#412]
I'm converting my code from an XYChart to the new stock chart and im having issues getting 'panended' event to fire, just wanted to check that this event is supported on the StockChart instance?

```
const chart = chartRef.current.container.children.push(
    am5stock.StockChart.new(chartRef.current, {
          panX: true,
          panY: false,
          wheelX: 'zoomX',
          wheelY: 'zoomX',
          layout: chartRef.current.verticalLayout,
          valueXField: "date",
      }),
);
```

```
chart.events.on('panended', function () {
     console.log('Loading more data')
     loadSomeData();
});
```

Thanks

**Comment by alienbuild** [comment]
P.S Additionally, my license is not hiding the AM5 logo in StockChart but works fine on all other charts.

**Comment by zeroin** [comment]
You should add `panended` on panels, not the chart itself. 
For license-related queries contact us directly at [contact@amcharts.com](mailto:contact@amcharts.com)
