### ISSUE TITLE
Examples for Line chart date range selector

### ISSUE THREAD

**Issue by erYasar** [amcharts/amcharts5#414]
Share some examples of line chart date range selector.
![image](https://user-images.githubusercontent.com/11607757/167073610-05fc5aee-3ffc-4dfa-bdb1-7b872a6b78cd.png)

I could not find any examples on amcharts 5

**Comment by martynasma** [comment]
I suggest looking into StockChart, which has such controls built-in:
https://www.amcharts.com/stock-chart/

**Comment by erYasar** [comment]
@martynasma , to understand better stock chart can hold different variety of series with built-in controls rather plain charts could not much built-in controls? is that right ?

**Comment by martynasma** [comment]
Yes, StockChart's panel is essentially an `XYChart` so you can do anything on it. Plus you can use stock toolbar.

Toolbar/range selector is not available for regular charts.
