### ISSUE TITLE
Colored worldmap with countries available in multiple series

### ISSUE THREAD

**Issue by WillyReyno** [amcharts/amcharts5#416]
**Question**

Hello,

I've been trying to use AmCharts to display a worldmap where countries would be colored depending on groups they are in

For example : 
- Group A (red) -> **France**, Belgium, Switzerland
- Group B (green) -> UK, Sweden
- Group C (blue) -> Spain, **France**, Portugal

After checking all the demos I decided to use [Grouped Countries Map](https://www.amcharts.com/demos/grouped-countries-map/) which seemed to better fit my need.

Everything works well except when I toggle two groups' legends. In my above example Groups A & C both share "France". But when rendering, France will take the color of Group C as it was declared last.

The best for me would be to be able to define a color when multiple groups contain the same country. 
For example, if I click on the following legends : 
* Legend "Group A" only => Shows France in red
* Legends "Group A" & "Group C" => Shows France in a custom color
* Legend "Group B" only => Show France in gray (default worldmap color)

So my questions are : 
* Is there a way to handle color for countries listed in multiple groups?
* Or is there another chart that could be a better fit for my need?

Thanks for your help!

**Comment by martynasma** [comment]
Well, the "grouping" is not a built-in feature of amCharts. It's a custom code. I suppose it would be up to you to modify the code of the demo to suit your specific needs, as it's a bit outside the scope of our support.

Hope you find it reasonable.
