### ISSUE TITLE
Error: Could not find HTML element with id "chartdiv"

### ISSUE THREAD

**Issue by karissadong** [amcharts/amcharts5#417]
am getting the error **Could not find HTML element with id 'chartdiv'**, despite setting up (as instructed in documentation) with `const root = am5.Root.new("chartdiv");` and using the corresponding id in the html. 

I tried wrapping it with `am5.ready(function() { })` and also tried setTimeout. I'm assuming the issue might be that the <div> element is being created before the chart code. Any tips on how to overcome this?

**Comment by martynasma** [comment]
Is your div element being created by JavaScript code?

**Comment by karissadong** [comment]
yes

**Comment by karissadong** [comment]
yes, that's what i'm trying to do. I think I'm having an issue similar to this one: https://github.com/amcharts/amcharts4/issues/1324

I tried the solutions in that thread, but it didn't seem to work. Any suggestions for amcharts 5?

**Comment by karissadong** [comment]
nvm, figured it out!

**Comment by mehmetkadri** [comment]
Hi, I'm currently having the same issue and I don't have any idea on how to handle this. Could you help me out?

**Comment by karissadong** [comment]
@mehmetkadri 

Saw your email and thought I'd write a reply here. I did a workaround like this:

````
useEffect(() => {
  const root = am5.Root.new("name");
  if(data) {
    start(root, data);
  }
  return () => root.dispose();
}, [data])

function start(root, data) { 
 // my stuff
 }

return (
  <div id="name" ></div>
)
````

I believe the original issue had to do with hoisting and initializing variables in JS.

**Comment by karissadong** [comment]
Hey there, I wrote a quick reply on Github. I hope it helps

**Comment by xamesLab** [comment]
если вы используете React, то в документации указано, как обернуть код в useEffect
