### ISSUE TITLE
Stock chart - Legend position

### ISSUE THREAD

**Issue by erYasar** [amcharts/amcharts5#418]
Trying to implement regular legend in stock chart. Could you help me how can position(bottom) the legend?

![image](https://user-images.githubusercontent.com/11607757/168250351-2781488b-5a95-465a-87d4-1e8f4c47bc8b.png)

Tried legend layout : grid but not working.

![image](https://user-images.githubusercontent.com/11607757/168249338-0f0b0275-5165-4119-9865-30e311a3f40d.png)

Also need  margin settings, it's overlapping

![image](https://user-images.githubusercontent.com/11607757/168252637-b86d8063-c5e0-4458-9f27-355a625534b1.png)

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by erYasar** [comment]
@martynasma , i don;t see any codepen works for stock chart, could you help me sharing working link?

https://codepen.io/team/amcharts/embed/MWrmBoV?default-tab=result&editable=true&theme-id=dark

![image](https://user-images.githubusercontent.com/11607757/168461653-44316411-4981-4717-911a-ebf73c78fd07.png)

**Comment by erYasar** [comment]
@martynasma , FYI https://jsfiddle.net/softwareCraftman/gL7pxzdn/26/

Few things:
1. How would i position the legend to bottom?
2. How would i disable indicators?
3. As per understanding stock toolbar is rendered as a separate div element, is it possible to seperate legend at bottom and other tools in top of the chart ?

**Comment by erYasar** [comment]
@zeroin

**Comment by martynasma** [comment]
If you need legend at the bottom, you need to push it to panel's children, as well as set a layout to the panel:

```JavaScript
var mainPanel = stockChart.panels.push(am5stock.StockPanel.new(root, {
   // ...
  layout: root.verticalLayout
}));

// ...

var valueLegend = mainPanel.children.push(am5.Legend.new(root, {}));
```

https://jsfiddle.net/xy8dafLo/
