### ISSUE TITLE
How can I get and set the node property "expanded/closed" in a force-directed-network graph?

### ISSUE THREAD

**Issue by Mechman** [amcharts/amcharts5#425]
Hi!

I run through all the nodes and I need to find out which ones are collapsed, which ones are expanded.
Here is an example: https://codepen.io/mechman/pen/rNJVjKO

I'm trying to get the disabled property, but I don't understand its logic and what it reflects.

`var prop = item.get("disabled");`

And then I need to set the previously collected values of this property to the nodes.
I tried "collapsed: true" and "disabled:true". It didn't work.

It's all not working. What am I doing wrong?
How to do it?

**Comment by zeroin** [comment]
`disabled` only indicates if the data item is disabled/enabled. You should use `hierarchySeries.disableDataItem(dataItem)` or `hierarchySeriesenableDataItem(dataItem)` to achieve what you want.

https://www.amcharts.com/docs/v5/reference/forcedirected/#disableDataItem_method
