### ISSUE TITLE
Feature request: option to disable the included Flatpickr CSS, or update to newer Flatpickr theme

### ISSUE THREAD

**Issue by dnewkerk** [amcharts/amcharts5#426]
Would it be possible to add an option to allow skipping calling `_loadDefaultCSS` in:
https://github.com/amcharts/amcharts5/blob/master/src/.internal/charts/stock/toolbar/DateRangeSelector.ts#L77

I already use Flatpickr on my site, and have the library's theme CSS loaded. The default and other optional themes for Flatpickr look really clean and modern, and I'd like to use that for the Flatpickr instances in amCharts. The current embedded Flatpickr CSS doesn't do justice to the clean and beautiful look of the rest of amCharts.

Examples:
https://flatpickr.js.org/themes/

If not, then would it be possible to at least update the version of the Flatpickr CSS embedded in amCharts to the latest version?

Thanks!

**Comment by martynasma** [comment]
Implemented in [5.2.4](https://github.com/amcharts/amcharts5/releases/tag/5.2.4).

## [5.2.4] - 2022-05-17

### Added
- `handleWheel()` method added to `XYChart`. Use it to mirror the same behavior as if the wheel was used on plot area.
- `useDefaultCSS` (default: `true`) setting added to `DateRangeSelector`.
- `inversed` added to `Tree` series. If set to `true`, will flip the direction of the tree.

### Fixed
- `StockToolbar` default CSS was using unnecessarily high `z-index` for its buttons.
- `StockToolbar` datepicker's style was off in some cases.
- `GaplessDateAxis` could display the same month name label two times in a row in some cases.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
