### ISSUE TITLE
Multi panel - multi axes chart

### ISSUE THREAD

**Issue by erYasar** [amcharts/amcharts5#428]
Trying to use Multi- panel chart with multi axes.

![image](https://user-images.githubusercontent.com/11607757/168743902-f9d5b66e-63db-4389-95f8-2bfb6aa61e42.png)

Scenario: I have 4 y-axes with partitioned as multi panel. when i need to add one or more y-axes dynamically in the bottom partition how can I do that?
https://codepen.io/eryasar/pen/PoQWMZY?editors=0010

**Comment by erYasar** [comment]
@martynasma , My scenario is having multi-y-axes at bottom partition right side and not to disturb the top partition chart? will it be possible to achieve ?

**Comment by martynasma** [comment]
I'm not aware of a way to achieve that. But maybe we're thinking of different things. Could you maybe post a mockup of what you're trying to achieve?

**Comment by erYasar** [comment]
@martynasma , Attached mockup from high charts.
Below partition chart has one or more y-axes at right side.
![image](https://user-images.githubusercontent.com/11607757/168960819-7121cfbb-20e0-40c2-93b6-9156d8198065.png)

**Comment by martynasma** [comment]
Thanks. I'm still not sure the nature of the issue.

How is this different from the amCharts CodePen you already have? Do you need labels for the axes of upper "panels" to be hidden like in the HC screenshot?

**Comment by erYasar** [comment]
@martynasma , labels can be achieved, if you see the bottom partition chart there are 3 series(different color highlighted) but 3 series label and axis line is hidden.

Basically we show one left y-axes and multi-y-axes in right side. more than one axes in right side we will show only first label but we still show the series

**Comment by martynasma** [comment]
Gotcha. So there are multiple axes on the right, but they are all hidden, but one.

I don't think we can achieve that in an `XYChart`, sorry.

**Comment by erYasar** [comment]
@martynasma , i am fine with multi y-axis labels at right side.
similar to this.
![image](https://user-images.githubusercontent.com/11607757/168970959-076ac3c8-0aee-45d5-8f6f-e15fb09830bc.png)

Only concern is we need to add more axis at bottom partition chart. i believe i have achieved the same in amcharts4.

**Comment by martynasma** [comment]
Do you have a CodePen for the amCharts 4 chart? I'd like to check out how it's implemented. I bet the same can be done in amCharts 5, too.

**Comment by erYasar** [comment]
@martynasma you are right!, now i am trying to have one axis used on right side with different series. this way i could achieve what is needed for me.

https://codepen.io/eryasar/pen/wvyezEv?editors=0010
