### ISSUE TITLE
Axis Label right side after the axis bar

### ISSUE THREAD

**Issue by erYasar** [amcharts/amcharts5#429]
How to make Axis Label  on right side after the axis bar?

![image](https://user-images.githubusercontent.com/11607757/169002692-6a646324-908e-4203-b647-c3caf074bb55.png)

**Comment by zeroin** [comment]
When axis is on the left you should unshift Label to the axis, and when axis is on the right, simply push it:

`yAxis.children.push(am5.Label.new(root, {text:"title", rotation:90}))`

**Comment by zeroin** [comment]
My suggested solution does the thing:
https://codepen.io/team/amcharts/pen/oNEZREX/59e6f361fbbc13b781d6a366214deb0f?editors=1010

If it's not, then you should provide the codepen of your situation.

**Comment by erYasar** [comment]
But now i am afraid that it did not work for me in left side?
https://codepen.io/eryasar/pen/XWZRzzb

previously i was using `yAxis.children.moveValue(am5.Label.new(root, {text:"title", rotation:90}),0)`

**Comment by zeroin** [comment]
So use moveValue for the left and unshift for the right.
