### ISSUE TITLE
porting moveHtmlContainer

### ISSUE THREAD

**Issue by GypsyyCode** [amcharts/amcharts5#44]
In my application I'm using vuejs3 and am4charts. To take advantage of the vue setup hook, which is called before or while the dom is rendered, i'm using a lot of `chart.moveHtmlContainer('chartdiv')` after the charts and series and everything are created and then set the data.
I created the charts like that `create(undefined, XYChart)`

But in version 5 I can't create a Root element without a htmltag or html element and I can't create a chart without a root element.

Im looking for some kind of setup and render later solution.
Will there be a way to do it like I did it in version 4?

**Comment by martynasma** [comment]
Implemented in [5.0.5](https://github.com/amcharts/amcharts5/releases/tag/5.0.5).

## [5.0.5] - 2021-11-15

### Added
- New root element method: `moveDOM()` (accepts element id or reference as a parameter). Can be used to move whole chart to some other container within DOM.

### Fixed
- `ExportingMenu` was interfering with functionality of form elements on the same page (e.g. select).
- Fixed issues with text kerning with styling blocks mid-word.
- Animating values of `width`/`height` settings using percent values was not working properly.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download-v5/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
