### ISSUE TITLE
Bubble chart is not pre-zoomed correctly

### ISSUE THREAD

**Issue by pablo3443** [amcharts/amcharts5#440]
**Bug description**
Create bubble chart with extraMin and extraMax

I would be to nice to have this chart already pre-zoomed without having zoom button.

If you put start = 0, end = 1, the chart is overzoomed (zoom button is shown). The only way to fix is to make manual zoomOut, or delete extraMin, extraMax values. Can you keep both of them?

I guess it should be fixed within the library

**Environment**
Amcharts 5

**Comment by zeroin** [comment]
Could you provide a codepen with this problem reproduced?
