### ISSUE TITLE
Bubble chart ticks (on rotation)

### ISSUE THREAD

**Issue by pablo3443** [amcharts/amcharts5#441]
When applying rotation to labels  on bubble chart, ticks are not connected to grid.

![image](https://user-images.githubusercontent.com/47576929/170273379-b9de157c-3de0-44f6-b852-45b9f8b30700.png)

**Environment**
Amcharts5
Chrome

**Comment by martynasma** [comment]
That's because they are rotated using right side as a center.

You can make the labels rotate using center using `centerX` setting:

```JavaScript
yRenderer.labels.template.setAll({
  rotation: 45,
  centerX: am5.p50
});
```

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by pablo3443** [comment]
@martynasma found solution using different centerX combintions, thanx, pls close the issue
