### ISSUE TITLE
Stock Charts Custom Indicators Legend Creation

### ISSUE THREAD

**Issue by cwooldridge1** [amcharts/amcharts5#444]
I've been playing around with the new stock charts and I've liked it a lot so far. In the application, I have been working on I have created a lot of custom indicators that I want to implement in the new stock charts. I can get them to plot how I want them to be plotted however what I have noticed is that the pre built indicators have these really cool custom legends where it shows the name and then the current values for each series in the panel e.g.
<img width="340" alt="image" src="https://user-images.githubusercontent.com/85259389/170636666-d6255107-ca69-4764-ae77-074ed101cbf9.png">

Then when you click the setting button on the indicator you can customize the colors of all the other series in the panel as the below photo depicts
<img width="232" alt="image" src="https://user-images.githubusercontent.com/85259389/170638616-6990623d-fdc4-49c9-a492-7949524bc25f.png">

I essentially want to be able to create this legend that groups the series in the panel and displays the values just how the above MACD indicator you guys provide does.

Do you guys plan on eventually allowing a way for users to create their own custom indicators and or allowing them to customize legends and how they are displayed as the pre-built indicators demonstrate? 

Note that I asked a similar question in https://github.com/amcharts/amcharts5/issues/325  however I decided to open this question because of the new functionality that legends can offer and provide in the new stock charts is far more advance then any other legends in Amcharts

**Comment by martynasma** [comment]
Thank you for this issue.

It's all doable right now, but warrants a proper tutorial. Give us a week or so to whip it up :)

**Comment by cwooldridge1** [comment]
Awesome thanks. Just an idea, in the tutorial, it would also be appreciated if you added documentation for creating event listeners for when an input/color/ on save event happens in the legend input settings so users could create custom events based on these input changes as I am sure a lot of users will be using there own custom indicators that will be able to respond to user input.

**Comment by cwooldridge1** [comment]
Any updates on this?

**Comment by martynasma** [comment]
Sorry for the wait.

We now have a custom indicator tutorial ready:
https://www.amcharts.com/docs/v5/tutorials/creating-custom-indicators-for-a-stock-chart/

It also deals with legend and settings dialog.

Hope you find it useful.
