### ISSUE TITLE
Dropdown list control feature

### ISSUE THREAD

**Issue by ankit-mercer** [amcharts/amcharts5#448]
When can we expect to have the Dropdown list control feature added to the Amcharts stock charts.

Below is the link for reference:
https://www.amcharts.com/docs/v5/charts/stock/toolbar/dropdown-list-control/

**Comment by martynasma** [comment]
Sorry, but there's no ETA set in stone. I'll let you know when it's up.

**Comment by martynasma** [comment]
There you go:
https://www.amcharts.com/docs/v5/charts/stock/toolbar/dropdown-list-control/
