### ISSUE TITLE
Customize the parent-child connecting branches length and thickness

### ISSUE THREAD

**Issue by hiorti** [amcharts/amcharts5#451]
I want to know if on hierarchy tree chart it is possible to customize the length and the thickness of the branches between parent and child nodes. 

The goal is to use the upside down tree chart as described in https://github.com/amcharts/amcharts5/issues/423 
and by customizing the length and thickness of the branches to get a chart imitating a real lifelike tree chart.
In other words, on each level instead of nodes aligned  horizontally in one line, to get the center branches longer, and side branches shorter - so the nodes on each level will be positioned in convex form - curved upwards.

Thank you in advance.

**Comment by zeroin** [comment]
Unfortunately I don't see a way to do this. Maybe you could try to achieve this with ForceDirected and fixed nodes:
https://www.amcharts.com/docs/v5/charts/hierarchy/force-directed/#Fixed_nodes

**Comment by hiorti** [comment]
Thanks for the reply. I will look into it. Would it be possible to use the ForceDirected and fixed nodes in hierarchy tree? I mean by giving the specific X and Y coordinates in hierarchy tree. Thanks again.

**Comment by zeroin** [comment]
There is no such a feature.
