### ISSUE TITLE
Adding text/data to parent-child connecting lines/branches

### ISSUE THREAD

**Issue by hiorti** [amcharts/amcharts5#452]
I was wondering if, on the hierarchy tree chart, there is a way to add text or data along the lines/branches that connect parent-child nodes.
Thank you in advance.

**Comment by zeroin** [comment]
I don't see a way to do that.

**Comment by hiorti** [comment]
Well, I'm sorry to hear that. I was hoping that it could at least be an idea to be considered and possibly to be include in the next release.
Thanks anyway.

**Comment by martynasma** [comment]
There's already an enhancement request for that. I suggest you follow https://github.com/amcharts/amcharts5/issues/83 to receive an update if we implement it in the future.
