### ISSUE TITLE
Date axis Increment bug on uncommon increment sizes

### ISSUE THREAD

**Issue by cwooldridge1** [amcharts/amcharts5#453]
I noticed that if I use a minute based increment that exceeds 60 the date axis plots them as hourly bars

For example, the second to last data point in my data array looks like this:
![image](https://user-images.githubusercontent.com/85259389/172464516-073b8633-1b1a-4dd0-8b72-8f7eab5c6e59.png)
However, the x-axis will display the point as 12:00 instead of 12:55:
![image](https://user-images.githubusercontent.com/85259389/172464701-85af1d3e-1548-4195-934b-c22110e29d63.png)
Here are the settings for my date axis:
![image](https://user-images.githubusercontent.com/85259389/172464796-83ad0ef8-d96e-49f1-aa57-db16dd725ec2.png)

I think this is an issue with the stock charts as I don't remember having this issue on other charts. Also If the cursor is not snapping to a series there will be blips where you can see the correct time increment but quickly moves the inaccurate one.

Here is a link to a code pen for further investigation: https://codepen.io/cwooldridge1/pen/KKQxeYX

**Comment by martynasma** [comment]
I'm afraid we cannot reliably support such "unnatural" base intervals. Handling such weird increments would bloat up the algo, and would make it harder to maintain and thus prone to other issues. I hope you can choose some base interval that is more natural for time scales.
