### ISSUE TITLE
How to dynamically set the size of the `radius` in `am5.Circle`

### ISSUE THREAD

**Issue by lgf196** [amcharts/amcharts5#454]
```
      let pointSeries = chart.series.push(
        am5map.MapPointSeries.new(root, {
        })
      );

  pointSeries.data.setAll([
        {
          geometry: {
            type: "Point",
            coordinates: [-73.778137, 40.641312],
          },
        },
        {
          geometry: {
            type: "Point",
            coordinates: [-0.454296, 51.47002],
          },
        },
        {
          geometry: {
            type: "Point",
            coordinates: [116.597504, 40.072498],
          },
        },
      ]);

      pointSeries.bullets.push(function () {
        return am5.Bullet.new(root, {
          sprite: am5.Circle.new(root, {
            radius: 5,
            fill: am5.color(0xffba00),
          }),
        });
      });
```
![image](https://user-images.githubusercontent.com/29600558/172799446-ba9ecf92-e6d8-4b93-b386-c6ce71692c08.png)

**I want to dynamically change the punctuation size of each city**

**Comment by lgf196** [comment]
> There are at least two ways to do that:
> 
> 1. heat rules:
>    https://www.amcharts.com/demos/map-bubbles/
>    https://www.amcharts.com/demos/map-with-animated-bubbles/
> 2. add settings to your data and set templateField:
>    https://codepen.io/team/amcharts/pen/oNEadXL/49195dbb8934ba858535dd9210f38398

Thank you. Does the dot support the effect of flicker amplification, similar to the 'scale' attribute of CSS

**Comment by lgf196** [comment]
> 至少有两种方法可以做到这一点：
> 
> 1. 热规则：
>    [https ://www.amcharts.com/demos/map-bubbles/ ](https://www.amcharts.com/demos/map-bubbles/)
>    https://www.amcharts.com/demos/map-with-animated-bubbles/
> 2. 将设置添加到您的数据并设置模板字段：
>    [https ://codepen.io/team/amcharts/pen/oNEadXL/49195dbb8934ba858535dd9210f38398](https://codepen.io/team/amcharts/pen/oNEadXL/49195dbb8934ba858535dd9210f38398)

Thank you. Does the dot support the effect of flicker amplification, similar to the `scale` attribute of `CSS3`

**Comment by lgf196** [comment]
> I am afraid I don't understand your question.

### ![image](https://user-images.githubusercontent.com/29600558/173170831-aeb3a90d-61e8-435d-ac77-06f414290392.png)
I want to animate the marked dots in the figure, like a breathing light. In `html`, you can use `animation` in `css3` to achieve, the code is as `follows:`
```
@keyframes warn {
    0% {
      transform: scale(0.5);
      opacity: 1;
    }
    30% {
      opacity: 1;
    }
    100% {
      transform: scale(1.4);
      opacity: 0;
}
}
```
### But I don't know how to use `am5map.MapPointSeries` to achieve the `css3` breathing light effect. My label dots are set with the following code:
```
var data = [
  {
    id: "US",
    name: "United States",
    circleTemplate: {
      radius: 30
    }
  }, {
    id: "GB",
    name: "United Kingdom",
    circleTemplate: {
      radius: 50
    }
  }
];
```

**Comment by zeroin** [comment]
Here is a demo illustrating how you can animate bullets of a map. You can use single circle and adjust time and effect of the animation to achieve the effect you want: https://www.amcharts.com/demos/map-with-pulsating-bullets/

**Comment by lgf196** [comment]
thank you very much
:rose: :rose: :rose: :rose: :rose: :rose:
