### ISSUE TITLE
tree chart linked lines height

### ISSUE THREAD

**Issue by basit3040** [amcharts/amcharts5#456]
Hi,

is there any way to manage height of link lines in tree chart?

as in picture there are three images leaf and apples, i am able to set position of circle, node and image but for link i am unable to set height of line 
as you see leaf attaching line is fine but i change the positions of apples the line ends early 
i just want to set custom line height
@amcharts 
@martynasma 
@Pauan 
@zeroin 
thanks in advance
![Screenshot from 2022-06-13 02-36-49](https://user-images.githubusercontent.com/106885620/173254815-1a3a0ace-6bef-4edd-98a4-872a28770d78.png)
s

**Comment by zeroin** [comment]
There is no way to do this, unless you use ForceDirected series with all nodes fixed and manually set x and y for each node.
