### ISSUE TITLE
Wrapping text in tooltip not working

### ISSUE THREAD

**Issue by amartinez1224** [amcharts/amcharts5#457]
I am trying to wrap text inside the tooltip of a ColumnSeries, however the tooltip (correct size) is shown but the text does not wrap. The oversizedBehavior: "wrap" setting is not working for the tooltip label.

var tooltip = am5.Tooltip.new(rootRef.current, {
    width: am5.percent(20),
    labelText : "vkdfnbjngkjbn jfgnbjkl gsfnjkb nfgjksbnjksgdnbjksdngljkbnsjdn",
});

tooltip.label.setAll({
    oversizedBehavior: "wrap",
    maxWidth: am5.percent(20)
});

series.columns.template.setup = function(target) {
    target.set("tooltip", tooltip);
};

series.columns.template.setAll({
    templateField: "columnSettings",
    width: am5.percent(10),
    fillOpacity: 0.2,
    strokeOpacity: 0.2,
    tooltipText: " ",
});
<img width="558" alt="Screen Shot 2022-06-12 at 6 58 19 PM" src="https://user-images.githubusercontent.com/44838230/173258887-cac5a97e-12f5-4a83-b715-b7267054f13e.png">

**Comment by martynasma** [comment]
Well, you should not set `width` on the tooltip directly. `maxWidth` and `oversizedBehavior` on its label should be enough.

**Comment by amartinez1224** [comment]
> Well, you should not set `width` on the tooltip directly. `maxWidth` and `oversizedBehavior` on its label should be enough.

I have removed the tooltip `width` setting. However, now the size of the tooltip extends to cover the entire text, but there is no wrapping. It is as if the `maxWidth` and `oversizedBehavior` were not taken into account. Changing the `oversizedBehavior` to "truncate" has no effect, nor does changing the `maxWidth`.

```
var tooltip = am5.Tooltip.new(rootRef.current, {
    //width: am5.percent(20),
    labelText: "vkdfnbjngkjbn jfgnbjkl gsfnjkb nfgjksbnjksgdnbjksdngljkbnsjdn",
});
```

<img width="489" alt="Screen Shot 2022-06-13 at 8 09 40 AM" src="https://user-images.githubusercontent.com/44838230/173360977-e0897efe-cefe-4c39-8c56-6e337ee686e4.png">

**Comment by amartinez1224** [comment]
I am working on a big React project so I will isolate the component and recreate the issue so that I can share it with you on CodePen.
