### ISSUE TITLE
GroupData + animation chart Error

### ISSUE THREAD

**Issue by Alexk05m** [amcharts/amcharts5#458]
On Line Chart Adding Data Every Second with groupData:true When the chart groups data

I get this TypeError :

Uncaught TypeError: Cannot read properties of undefined (reading 'get') on line :
newDataItem.bullets[0].get("sprite").dataItem = newDataItem;

Here is the code to reproduce the problem :

https://jsfiddle.net/alexk05m/qbf8t5c7/1/

**Comment by martynasma** [comment]
I'm not getting this error in your fiddle on Chrome.

Can you verify if you are still seeing the error, and whether this is happening in a particular browser?

**Comment by Alexk05m** [comment]
If you zoom on the fiddle chart, you will get the error: 

"<a class='gotoLine' href='#237:26'>237:26</a> Uncaught TypeError: Cannot read properties of undefined (reading 'get')"

**Comment by martynasma** [comment]
Gotcha. Was able to reproduce this.
