### ISSUE TITLE
Stacked bar chart sorting

### ISSUE THREAD

**Issue by mcr85** [amcharts/amcharts5#459]
In Stacked Column Chart example (https://www.amcharts.com/demos/stacked-column-chart/), how do I arrange pieces of bar (smaller categories), so they are stacked from highest value to lowest (from bottom to top)?

Thanks!

**Comment by martynasma** [comment]
There's no way to alter order of columns in each stack individually, I'm afraid.

They will always be stacked in the same order as the series have been added to `chart.series`.
