### ISSUE TITLE
chart hangs the tab on some systems or phones

### ISSUE THREAD

**Issue by AngadRajput** [amcharts/amcharts5#460]
The chart hangs on some systems or phones, whenever there is any chart interaction or while loading the chart. It hangs up the system and fires an unresponsive alert, especially when using themes.

[CodePen](https://codepen.io/getangad/pen/jOZeoWO)
[Video on the issue](https://nimb.ws/JryZf1)

**Comment by martynasma** [comment]
It looks like it's happening because of the `oversizedBehavior` setting. Can you confirm?

**Comment by AngadRajput** [comment]
> oversizedBehavior
Yes, I checked and verified, was fixed after I had removed the `oversizedBehavior` property.
Thanks for this.

**Comment by martynasma** [comment]
Thanks for confirming. We'll need to address this anyway, but at least there's a temporary fix.

**Comment by martynasma** [comment]
OK, so the issue here is not with amCharts wrapping, but rather malformed in-line text formatting. There's a stray closing tag `[/]` in the text of your label:

![image](https://user-images.githubusercontent.com/1458520/173754278-6937add9-6ff6-4d49-9a78-d84fdc353d0f.png)
