### ISSUE TITLE
Match up axis ticks and grid lines with date/time interval values

### ISSUE THREAD

**Issue by wimcoosemans** [amcharts/amcharts5#461]
Not so much of a question anymore (so feel free to close this), but I think this could help someone out in the future as its not super obvious.

When using a DateAxis and setting a base interval bigger than 1, or when you're setting custom gridIntervals to only render grid lines say max every 5 minutes, the axis ticks are shown at the start of each grid cell while values and tooltips are shown in the middle of each cell. This seems to align everything:

```
xAxis.get("renderer").labels.template.setAll({
    location: 0.5, // labels in middle
    multiLocation: 0.5 //labels in middle when grid lines skipped
 })
```

```
  xAxis.get("renderer").grid.template.setAll({
    location: 0.5, // grid lines in middle
  })
```

Here's an example with 5 minute data, showing axis ticks and grid lines exactly on each 5 minute interval.
https://codepen.io/wiiiim/pen/wvyOjQd

**Comment by martynasma** [comment]
Thanks for sharing this. Related docs:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#location-of-axis-elements
