### ISSUE TITLE
Force-Directed Network's `enableDataItem` method does not work.

### ISSUE THREAD

**Issue by byseop** [amcharts/amcharts5#462]
[Here is my example](https://codepen.io/byseop/pen/gOvJKwr?editors=0011)
Please check the Line 528 on JS.

`dataItem` and `dataContext` come out well, but `enableDataItem` does not work.
With `initialDepth: 0`, I want to expand a specific 1 depth node.

Please let me know what I should do.

**Comment by byseop** [comment]
> [Here is my example](https://codepen.io/byseop/pen/gOvJKwr?editors=0011) Please check the Line 528 on JS.
> 
> `dataItem` and `dataContext` come out well, but `enableDataItem` does not work. With `initialDepth: 0`, I want to activate a specific 1 depth node.
> 
> Please let me know what I should do.

**Comment by zeroin** [comment]
You should do this with some timeout:

```
setTimeout(() => {
  const node = series.nodes.getIndex(1);
  if (node) {
    console.log(node.dataItem.dataContext);
    series.enableDataItem(node.dataItem);
  }
}, 1000)```

**Comment by byseop** [comment]
> You should do this with some timeout:
> 
> ```
> setTimeout(() => {
>   const node = series.nodes.getIndex(1);
>   if (node) {
>     console.log(node.dataItem.dataContext);
>     series.enableDataItem(node.dataItem);
>   }
> }, 1000)```
> ```

It works!! Thx!!
