### ISSUE TITLE
Map twitches on zooming after setting data

### ISSUE THREAD

**Issue by Kirigetov** [amcharts/amcharts5#465]
Hi!
I try to create world map with country names. I added country name to the polygon when event `datavalidated` fired.
The main problem is when you zooming by mouse wheel or click on country polygon that all map is pulling (freezing).

If no data everything looks fine, but map without country names isn't useful. 

Here is my example on codepen: https://codepen.io/foobarbuz/pen/OJQqrPJ

I also want to note that when I add a map to my component on VUE, all the twitching is greatly enhanced.

How I can optimize it?

**Comment by martynasma** [comment]
We can't seem to be able to reproduce any twitching when zooming.

**Comment by Kirigetov** [comment]
Thank you for your time. I tried to record it on video so that it could be compared. I understand that this difference is not critical, but it is present. I will leave the development of this feature in this form. I will attach the video for reference.
[my-example.webm](https://user-images.githubusercontent.com/14583720/176487094-b4997d98-8fc8-4379-9088-1e30c7d4cbb0.webm)
[demo-example.webm](https://user-images.githubusercontent.com/14583720/176487100-f64146b6-8ab3-46ee-814d-85705e115447.webm)
