### ISSUE TITLE
How change a centerX point of zoomed country

### ISSUE THREAD

**Issue by Kirigetov** [amcharts/amcharts5#466]
Hi! 

Is there exist opportunity to change the center of zooming map? I mean, that when you click on country for zoom by `zoomToDataItem(target.dataItem)` country has offset to left for example.

In my case I have a small popup above a map that situated on right side of map container. When country zoomed this popup overlaps the name of the country and most of their territory. 

I reassigned `zoomToPoint` method from the lib and it works that I want but after this ZoomControl stopped working:
`if (center) {
    cx = level === 1 ? CHART_ELEMENT.width() / 2 : CHART_ELEMENT.width() / DIVIDER_FOR_OFFSET_CENTER_OF_MAP;
    cy = CHART_ELEMENT.height() / 2;
}`

**Comment by martynasma** [comment]
I'd probably start by making own version of `zoomToDataItem()`. It's pretty straightforward:
https://github.com/amcharts/amcharts5/blob/master/src/.internal/charts/map/MapPolygonSeries.ts#L150-L159

You'd just need to adjust the geobounds a little bit as needed.

**Comment by Kirigetov** [comment]
Yes, I did. However, I redefined another method - `zoomToPoint`. I adjusted the required center point and the required zoom level. thanks
