### ISSUE TITLE
How to customize ZoomControl buttons

### ISSUE THREAD

**Issue by Kirigetov** [amcharts/amcharts5#467]
Hi!
I want to customize zoomControls buttons. And I don't find any examples for this case. I done it but I have doubts that my version is correct. Maybe exist a more easy way for customize this buttons?

`const zoomControl = CHART_ELEMENT.set('zoomControl', am5map.ZoomControl.new(ROOT_ELEMENT, {}));
const zoomButtons = ['minusButton', 'plusButton'];

zoomButtons.forEach((button) => {
    zoomControl[button].get('background').setAll({
        cornerRadiusTL: 2,
        cornerRadiusTR: 2,
        cornerRadiusBR: 2,
        cornerRadiusBL: 2,
        fill: am5.color(this.colors.white),
        stroke: am5.color(this.colors.greyDefault),
    });

    zoomControl[button].get('icon').setAll({
        stroke: am5.color(this.colors.greyDark),
        scale: 2,
    });

    zoomControl[button].get('background').states.create('hover', {}).setAll({
        fill: am5.color(this.colors.greyActive),
        stroke: am5.color(this.colors.greyActive),
    });

    zoomControl[button].get('background').states.create('down', {}).setAll({
        fill: am5.color(this.colors.greyDark),
        stroke: am5.color(this.colors.greyDark),
    });

    zoomControl[button].get('icon').states.create('hover', {}).setAll({
        stroke: am5.color(this.colors.white),
    });
});`

**Comment by martynasma** [comment]
Your code looks good to me.

**Comment by Kirigetov** [comment]
For some reason I thought I was complicating the code) Thx!
