### ISSUE TITLE
rotating RadarChart moves it off screen (V5)

### ISSUE THREAD

**Issue by dsinger376** [amcharts/amcharts5#469]
Hello,

My team is using a licensed version of Amcharts v5.2.10, and I am **having trouble rotating the entire chart (axes and series)**.  The desired effect is to have the 'First' label, xAxis grid line, and yAxis 'First' series value (4) at the 12 o'clock position
**I have included a screenshot and codepen link** for reference.  Really appreciate any help you can provide.  Thanks!

https://codepen.io/dansinger456/pen/abYbYWR?editors=1010

**Environment **
React app running v18.1.0
Amcharts Version: 5.2.10

<img width="1589" alt="rotation issue" src="https://user-images.githubusercontent.com/88509443/176335548-526bdf36-07ea-4bc6-94d2-2f3fab1c0e89.png">

**Comment by zeroin** [comment]
Hi,

Here is a pen which solves the issue:
https://codepen.io/team/amcharts/pen/xxWxJKz/21971120326bd00629e03e379733aa0e?editors=1010

it doesn't rotate the chart. I set grid and label location to 0 and also set locationX of a series to 0.

**Comment by dsinger376** [comment]
Thanks for your help!
