### ISSUE TITLE
How to display custom marker with a tooltip ?

### ISSUE THREAD

**Issue by sauravgaursmith** [amcharts/amcharts5#473]
**Question**

how do I can display a custom marker in Amchart 5 map ? Please, see image below.
![image](https://user-images.githubusercontent.com/25001992/177164753-99cbea4b-4621-4864-9e44-0b4b6512d103.png)

**Environment (if applicable)**
OS: Linux
Angular: 8.x.x version
Amchart 5

**Additional context**

Was able to do it with Amchart 4.

**Comment by sassomedia** [comment]
Did you check out at the [demos](https://www.amcharts.com/demos/#maps)?
There's a weather map example: https://www.amcharts.com/demos/weather-map/

**Comment by martynasma** [comment]
Use `MapPointSeries` to add any kind of image to lat/long coordinates:
https://www.amcharts.com/docs/v5/charts/map-chart/map-point-series/#Points_on_a_line

**Comment by sauravgaursmith** [comment]
Thanks Guys. Solved!
