### ISSUE TITLE
How to display in Arrow with direction on the line in map?

### ISSUE THREAD

**Issue by sauravgaursmith** [amcharts/amcharts5#474]
**Question**
How can display an arrow with a direction in map ? please see image attached.
![image](https://user-images.githubusercontent.com/25001992/177166201-a088ea18-10d5-4e18-a1ca-cd953ac6d23c.png)

**Environment (if applicable)**

OS: Linux
Angular 8
Amchart 5

**Additional context**

**Comment by sassomedia** [comment]
Same here, there's an example in the [demos](https://www.amcharts.com/demos/#maps): https://www.amcharts.com/demos/map-with-curved-lines/

**Comment by martynasma** [comment]
The idea is to attach items from `MapPointSeries`, to items in `MapLineSeries`. This is all explained thoroughly here:
https://www.amcharts.com/docs/v5/charts/map-chart/map-point-series/#Points_on_a_line

**Comment by sauravgaursmith** [comment]
Thanks Guys. Solved!
