### ISSUE TITLE
Deviation of the candle's body to the right

### ISSUE THREAD

**Issue by BabakAmini** [amcharts/amcharts5#475]
Here is a simplified version of my code:

https://codepen.io/BabakA/pen/ZExbLwy

I have two issues with the displayed chart:

1. Candle's bodies have deviated to the right. This is because of setting `minWidth` and `maxWidth` of the series template. If you replace them with a fixed width, then candles draw fine. Removing all width settings by the way will display narrow candles in which the body and shadow widths are almost equal.
2. Zooming in will resolve the above issue even if you use minimum and maximum widths, but at some zoom levels, you can see that the entire candle is not displayed in the right place. For example, while we have data for a candle at 09:01:00, the candle isn't drawing at that time. Below is a screenshot for a better understanding of what I'm talking about.

![image](https://user-images.githubusercontent.com/85762931/177199774-8fa4a8b8-198b-4440-a3f9-77f424eb58d1.png)

I'm not sure if the candlestick series are based on column series, but this also happened for column series in another project with data like the one used in this example.

![01](https://user-images.githubusercontent.com/85762931/177200129-ac79cf3a-8921-4a11-9498-6ad5d6409dec.png)

**Comment by BabakAmini** [comment]
@amcharts [Here](https://codepen.io/BabakA/pen/ZExWwOx) is another bug that's related to this topic. I have a dataset similar to the one I used above (both have time series as their x values).

This time, without **width** parameters, column series will not be displayed at all. In this example, if you don't set the `width` or `minWidth` parameter in the column template, the columns will not be displayed. In this case, if you move the mouse pointer near the X-axis, you may have luck seeing some tooltips. Setting one of those parameters will cause the columns to be displayed as we expected.

Another way to solve this problem is to change X-Axis and X-Values to category data types! I'm afraid this problem is related to the time series data points.

**Comment by zeroin** [comment]
I think the main problem in your case is that you set baseDuration to a second while your data is minutely. If you set:
`baseInterval: { timeUnit: "minute", count: 1 },` you will have candles in a right position and of a correct width. 

As for the second issue - this is expected behavior with both axes being value axes. If you need both of them to be value axes, you must either specify `openValueXField` for your series and add values to your data which would not be equal to the your actual values (otherwise it will still be the same result) or use CategoryAxis instead.

**Comment by zeroin** [comment]
Columns are not displaced, they are shown in the middle of the cell of a second. And grid line shows the beginning of a second. If you add locationX:0 to the ColumnSeries, the column will be shown around the grid line. More about locations of axis elements: https://www.amcharts.com/docs/v5/charts/xy-chart/axes/

As for the both axes being value axes, I am afraid I don't see any possibilities to change that. And yes, with Value axis the zoom is not auto-adjusted.
