### ISSUE TITLE
Can Amchart v4 License key work on Amchart v5 ?

### ISSUE THREAD

**Issue by sauravgaursmith** [amcharts/amcharts5#476]
**Question**
Can Amchart v4 License key work on Amchart v5 ?
If yes, it's not working. I'm adding license as below lines -

`am5.addLicense("<MY_LICENSE>")`

**Environment (if applicable)**
Amchart 5 version.

**Additional context**

I'm using CDN to use Amchart 5.

**Comment by martynasma** [comment]
No, I'm afraid. Please email us at contact@amcharts.com to discuss license-related stuff.
