### ISSUE TITLE
Popups in v5

### ISSUE THREAD

**Issue by BabakAmini** [amcharts/amcharts5#478]
Hi, Amcharts team,

I was looking for popups in Amcharts documents and reached [this page](https://www.amcharts.com/docs/v4/concepts/popups-and-modals/). That's a v4 document, and I'm looking for v5, but there is only documentation for the modal window. Did you remove popups from v5?

**Comment by BabakAmini** [comment]
Thanks @martynasma, I found it. Now it's showing in the search results too.

By comparing between v4 and v5 source code, I found out that there are no separate modal and popup classes in v5. Also, it seems that new modal popups are just modals because the user can not interact with the chart around the modal (except zooming for an unknown reason). So, did you remove the ability to interact with the chart while a popup window is displayed?

I'm also wondering if there is a way to disable any interaction with the chart including zoom operation and just show a curtain on the chart. I need this in case the connection between the web application and the server is lost for a while and the user needs to be informed and prevented from doing anything with the chart until the connection is re-established.

**Comment by martynasma** [comment]
For now there's only Modal functionality. We might add other functionality in the future.

We will add the option to disable all chart interactions when modal is open in the next version. Will let you know when it's out.

**Comment by martynasma** [comment]
Implemented in [5.2.11](https://github.com/amcharts/amcharts5/releases/tag/5.2.11).

## [5.2.11] - 2022-07-18

### Added
- A new setting `deactivateRoot` (default: `true`) added to `Modal`. Indicates if any interactivity on the underlying chart should be disabled when modal is open.
- A new setting `html` added to `Container`. Set it to a string with HTML to be used as container's content. Will work on any element inheriting from `Container`, e.g. `Label`. [More info](https://www.amcharts.com/docs/v5/concepts/common-elements/html-content/).
- A new setting `labelHTML` added to `Tooltip`. If set, will ne used as HTML content for the tooltip. [More info](https://www.amcharts.com/docs/v5/concepts/common-elements/html-content/).
- A new setting `tooltipHTML` added to `Sprite`. If set, will ne used as HTML content for the tooltip when element is hovered. [More info](https://www.amcharts.com/docs/v5/concepts/common-elements/html-content/).
- `wheelZoomPositionX` and `wheelZoomPositionY` added to `XYChart`. This value is not set by default, but you can use it to fix wheel zooming, to the end (if you set it to 1) or to the start (0) or middle (0.5). In `StockChart`, it is set to 1 by default, as this is common practice in financial charts.
- "Volume-Weighted Average Price (VWAP)" indicator added to `StockChart`.

### Changed
- Setting `id` setting when creating an object will not register it in `am5.registry.entitiesById` immediatelly, without waiting for the next frame.

### Fixed
- `RadialGradient`'s `x` and `y` settings were being ignored.
- Labels as bullets with `oversizedBehavior` set were not being displayed properly in some cases.
- `DateAxis` with `startLocation = 0.5` and `endLocation = 0.5` and single value only was showing a really big date range.
- Resizing `PieChart` to a very small size with a legend positioned on the left or right could cause some anomaly in layout.
- Updating `CategoryAxis` data with less items than there was originally was causing old columns/bullets to be shown.
- Setting `verticalScrollbar` on `Container` to `undefined` to remove a previously set scrollbar was not working.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
