### ISSUE TITLE
Wrong alignment between CategoryAxis and value on the LineSeries

### ISSUE THREAD

**Issue by marnits** [amcharts/amcharts5#479]
**Question**

I'm trying to render a Line chart. I'm having troubles with aligning the CategoryAxis and the actual value on the chart. Please take a look at a screenshot. 

Is there any option to block this kind of behaviour? 

As You can see - the value is not in the line with the CategoryAxis Label and the grid line.

<img width="1393" alt="Screenshot 2022-07-08 at 13 26 32" src="https://user-images.githubusercontent.com/2494128/177985119-20ce67be-13df-4dc1-b5f6-3376d5d5329a.png">

It also appears when I'm resizing the chart:

![amcharts-bug](https://user-images.githubusercontent.com/2494128/177984548-c03f591e-890b-4659-8060-f0fca8c9e3cd.gif)

This is what I have so far.

```
useLayoutEffect(() => {
    const root = Root.new(id);
    root.setThemes([Theme.new(root)]);

    chart.current = root.container.children.push(
      XYChart.new(root, {
        focusable: true,
        panX: true,
        panY: true,
        wheelX: 'panX',
        wheelY: 'zoomX',
        pinchZoomX: true,
      })
    );

    chart?.current?.set('cursor', XYCursor.new(root, {}));

    chart?.current
      ?.get('colors')
      ?.set('colors', [
        color(StaticColor.BlueMarguerite),
        color(StaticColor.SeaBuckthorn),
        color(StaticColor.Malibu),
        color(StaticColor.Emerald),
        color(StaticColor.Calypso),
      ]);

    const yAxis = chart.current.yAxes.push(
      ValueAxis.new(root, {
        renderer: AxisRendererY.new(root, {}),
      })
    );

    const xAxis = chart.current.xAxes.push(
      CategoryAxis.new(root, {
        categoryField: xKey as unknown as string,
        renderer: AxisRendererX.new(root, {}),
      })
    );

    if (data.length) {
      data.forEach((data) => {
        const tooltip = Tooltip.new(root, {
          labelText: '{categoryX}\n[bold]{valueY}[/]',
        });

        tooltip.label.setAll({
          textAlign: 'center',
        });

        const series = chart.current?.series.push(
          LineSeries.new(root, {
            name: 'Series',
            xAxis,
            yAxis,
            valueYField: yKey as unknown as string,
            categoryXField: xKey as unknown as string,
            tooltip,
          })
        );

        series?.strokes.template.setAll({
          strokeWidth: 2,
        });

        series?.bullets.push(function () {
          return Bullet.new(root, {
            sprite: Circle.new(root, {
              radius: 4,
              fill: root.interfaceColors.get('background'),
              stroke: series?.get('fill'),
              strokeWidth: 2,
            }),
          });
        });

        xAxis.data.setAll(data);
        series?.data.setAll(data);
      });
    }

    return () => {
      chart.current && chart.current.dispose();
    };
  }, []);
```

I've also saw this behaviour on one of Your example charts.

<img width="1177" alt="Screenshot 2022-07-08 at 13 41 08" src="https://user-images.githubusercontent.com/2494128/177985759-6afb8152-535f-453d-9998-00b8b41d56b9.png">

<img width="1165" alt="Screenshot 2022-07-08 at 13 41 16" src="https://user-images.githubusercontent.com/2494128/177985786-a6f76cbc-3357-42c7-8794-3c7454ee0a0b.png">

As You can see - the grid with label are not accurate to the value on the chart.

**Comment by martynasma** [comment]
Please refer to this tutorial:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#location-of-axis-elements

And this:
https://www.amcharts.com/docs/v5/charts/xy-chart/series/line-series/#Data_item_location

**Comment by marnits** [comment]
@martynasma thank You for such a quick response! 

I solved it by using:

```
xAxis.get('renderer').labels.template.setAll({
  location: 0,    
  multiLocation: 0,
});
```
