### ISSUE TITLE
Line Chart: How to create Axis Range when clicking on DateAxis label

### ISSUE THREAD

**Issue by dsinger376** [amcharts/amcharts5#480]
Hello,

My team is using a licensed version of Amcharts v5.2.10, and I am trying to achieve the following:

**Desired Behavior**
I want to enable DateAxis labels to be clickable, and when a user clicks on a particular date, an axis range is created directly above the clicked label that  'highlights' that date (screenshot attached).  (For some context as to why I am trying to achieve this, future state would plot multiple values (prices) per day, and clicking on the DateAxis for, say Jan 14th, would show the axis range for Jan 14th, and also show a modal or something with the average price for that day.  For example, Jan 14th has 3 prices: $10, $17, $14.5, with an average price of $13.83)

**Current Behavior**
In order to prevent DateAxis labels from overlapping, I have set the maxGridDistance to a higher number (i.e. 100).  This solves the overlapping issue, but now labels are skipped.  Axis Range doesn't appear directly above the clicked DataAxis label, rather it progressively becomes more and more vertically misaligned as you click on higher and higher dates. (screen recording attached).

Can you please show me how to ensure that when a user clicks on, i.e. Jan 14th, that the axis range is created for Jan 14th and appears directly above the label?  Any help would be much appreciated, thanks.

**Elements Used**
chart: XYChart (line chart)
yAxis: ValueAxis (renderer: AxisRendererY)
xAxis: DateAxis (renderer: AxisRendererX)
series: SmoothedXLineSeries

**CODEPEN**
https://codepen.io/dansinger456/pen/YzaWQyG
**SCREEN RECORDING**
https://user-images.githubusercontent.com/88509443/178179699-c9e53c07-c1d2-4c40-90b5-df6a57090075.mp4
**DESIRED BEHAVIOR**
<img width="1005" alt="desired behavior" src="https://user-images.githubusercontent.com/88509443/178180281-0af6994c-7b6b-40eb-921a-497d08acefa2.png">

**Environment **
React app running v18.2.0
Amcharts Version: 5.2.10

**Comment by martynasma** [comment]
I would not use data item's `dataContext`, but rather `value` setting:

```JavaScript
const unixTimestamp = ev.target.dataItem?.get("value");
```

It holds correct timestamp of the label.

**Comment by dsinger376** [comment]
That did the trick, thanks for the swift reply!
