### ISSUE TITLE
How to Hide Licence Key in Vanilla JavaScript?

### ISSUE THREAD

**Issue by mukeshbadgujar** [amcharts/amcharts5#482]
I have added Licence Key as you said in Docs, But it is easily showing in Browser Inspect,
how i can hide Licence Key? because anyone can see it in view source code on browser if i add key in javascipt.

i followed https://www.amcharts.com/docs/v5/reference/registry_module/

**Comment by mukeshbadgujar** [comment]
then how you can recognise if someone uses the same licence key on his website also i am using same on my website.

> License key does not reveal any personal details, or give access to any systems, so it's pretty safe to have it out in the open.
> 
> Hope that sounds reasonable.

then how you can recognise if someone uses the same licence key on his website also i am using same on my website.

**Comment by mukeshbadgujar** [comment]
i have tried the licence key on two different  systems and it removes am-chart logo on both, so it should't be private?

> then how you can recognise if someone uses the same licence key on his website also i am using same on my website.
> 
> > License key does not reveal any personal details, or give access to any systems, so it's pretty safe to have it out in the open.
> > Hope that sounds reasonable.

**Comment by martynasma** [comment]
Please contact us at contact@amcharts.com to discuss this further.
