### ISSUE TITLE
Jumping chart on quick zoom

### ISSUE THREAD

**Issue by rabamaba** [amcharts/amcharts5#483]
**Animated chart jumps far out on fast zoom**

We have an animated linechart wich can zoom out very far (maxDeviation 250) and it also might have multiple series with a lot of values (50k+). On some clients the chart is somewhat laggy, which is kind of expected considering the amount of data, but when zooming in very quick (repeatedly mouse wheel forward) the chart starts jumping further out again, usually until the maxDeviation is reached.
It works fine if you scroll very carefully and wait until the scrolling-animation has ended after every mousewheel, though it is a very annoying bug.

We tried updating from [5.1.14] to [5.2.10], but no changes.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by rabamaba** [comment]
Thanks for the quick reply. The whole chart is populated from the backend, so testing it is difficult. I might find some time tomorrow to reconstruct the basic functions for CodePen, if that helps.

**Comment by rabamaba** [comment]
Seems that it was not necessary to rebuild my project. All I had to do to reproduce this issue was setting the maxDeviation to 250 and generate 50k Datas:
https://codepen.io/rabamaba/pen/KKogPQv

**Comment by rabamaba** [comment]
I found this starts happening if maxDeviation is greater than 5 actually.

**Comment by rabamaba** [comment]
I understand it being unusual, but I wasn´t able to find a workaround yet. 
What I wanted to achieve is that the user can choose start and end for the xAxis, and there might or might not be much data for it - nonetheless the timespan the user sees in the beginning should be the whole timespan, even if there is no data at the start or end. So I used a high maxDeviation to be able to use xAxis.zoomToDates() over the whole timespan.

Any help with this would be highly appreciated.

**Comment by martynasma** [comment]
How about creating a secondary series with data for the first and last date in user-set range?

**Comment by rabamaba** [comment]
Thank you. 
I was thinking about that, but it might be confusing because the user can add multiple other series. I reckon there is no other way though!

**Comment by martynasma** [comment]
![elmo-well](https://user-images.githubusercontent.com/1458520/178465987-08e82b97-2234-460d-a21f-34f62f0826a8.gif)
