### ISSUE TITLE
Syncing cursors does not work when charts are not below each other

### ISSUE THREAD

**Issue by kind3r** [amcharts/amcharts5#486]
**Bug description**

When charts are displayed next to each other, cursors syncing using `cursor.set("syncWith", [...])`.

To reproduce, simply change the `#chartdiv1, #chartdiv2, #chartdiv3` width to `40%` in the default example:
https://codepen.io/team/amcharts/pen/zYPwdGj

Charts 1 and 3 sync the cursor but not with chart 2.

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/1621814/178813716-659cc82a-4390-42ae-9dec-856566fb6f4c.png">

**Environment (if applicable)**

amCharts: 5.2.10

**Additional context**

**Comment by martynasma** [comment]
Syncing of cursors with `syncWidth` is performed using actual screen X/Y coordinates, not relative positions within the axes.

This is why your vertical cursor line does not "sync" to the chart placed on the right.

We're updating the docs to explicitly state that as we speak.

There's currently no built-in way to sync cursors via relative position on the axes. It would require creating cursor events, then placing cursors manually via API.

**Comment by kind3r** [comment]
Hi @martynasma , 
Any workaround for this ? 

I've tried using `cursormoved` event on one chart (A) and `cursor.set("positionX", ...)` on the other (B), but as soon as the first position is set on chart B hovering over that chart does not move the cursor anymore. 
Besides, `cursormoved` event is triggered when programatically setting `positionX` which means I can't sync both ways (from A to B and from B to A).

Maybe using `onmouseover` chart area to start/stop sync would be a solution, but how can I clear the effect of  `cursor.set("positionX", ...)` to make the cursor move with the mouse again ?

**Comment by kind3r** [comment]
Managed to make it work by using chart's `pointerover` and `pointerout` events to determine which of the charts is the "master". 
The "master" chart listens to `cursormoved` events, sets `alwaysShow` property and sends `positionX` updates to the other charts.
When there is no "master" chart, `positionX` and `alwaysShow` properties are removed from cursors so that the cursor does not get stuck on the chart and resumes normal operations.

Hope someone finds this logic useful in the future.

**Comment by someden** [comment]
Here is my example: https://codepen.io/someden/pen/ZExKGBE
@martynasma I will be glad if you could find some time to take a look and maybe give some advices what we can optimize?

**Comment by someden** [comment]
Here is my example: https://codepen.io/someden/pen/ZExKGBE
It's freeze sometimes if you will move cursor quickly.
@martynasma I will be glad if you find time to take a look and maybe give some advice of what we can optimize? Thanks!
