### ISSUE TITLE
'startendchanged' Event not available for Date Axis in charts 5

### ISSUE THREAD

**Issue by avithemad** [amcharts/amcharts5#492]
**Bug description**

In AM charts 4, we had events like startchanged, endchanged, startendchanged to which we were able to add handlers.
In charts 5 these events for date axis are not available. 

Is there any way to get the scrolled/panned date ranges in the chart?

Adding events listener to all the events, I see only 'boundschanged' event triggered.
`dateAxis.events.onAll((ev) => console.log(">> Start changed", ev));`

![image](https://user-images.githubusercontent.com/25084977/180022191-088b7cf4-0616-4058-9cd6-28bbb0830281.png)

Please refer this modified demo of stocks: https://codepen.io/avithemad/pen/bGvWBGK

**Environment (if applicable)**

Angular 13
AmCharts5 

**Additional context**

We needed a chart with zoom by controls, as well as some way to get the zoomed date ranges when user performs any action on the chart. With stock chart Zoom by controls are available but a way to get the zoomed ranges is not available, if there is some other way to achieve this, please let me know.

**Comment by martynasma** [comment]
I would use an event on private/readonly setting change:

```JavaScript
xAxis.onPrivate("selectionMin", function(timestamp) {
  console.log("from", timestamp)
});

xAxis.onPrivate("selectionMax", function(timestamp) {
  console.log("to", timestamp)
});
```

**Comment by avithemad** [comment]
Thank you, I tried this and it works!
