### ISSUE TITLE
In React JS graph gets redrawn whenever data changes in useEffect

### ISSUE THREAD

**Issue by AbhishekDigitalSalt** [amcharts/amcharts5#494]
I am implementing am chart in React JS. To update the chart we need to update the state as per react architecture, and whenever I update the state with new data, useLayoutEffect runs again and whole chart gets redrawn. Is there any way to prevent redrawing of whole chart in React JS?

**Comment by martynasma** [comment]
Are you creating the whole chart in `useLayoutEffect`? You should only update changes in it:

https://www.amcharts.com/docs/v5/getting-started/integrations/react/#Using_with_hooks

**Comment by shanqq** [comment]
in useEffect create one dependency and if that dependency gets change you will update the chart by first disposing the chart and creating it right.

**Comment by AbhishekDigitalSalt** [comment]
> in useEffect create one dependency and if that dependency gets change you will update the chart by first disposing the chart and creating it right.
yes. but whenever dependency updates charts gets redrawn with new values. but I don't want it to get redrawn on every update.

**Comment by shanqq** [comment]
but the data is getting change right then how you will get that done. by not redrawing that part.
