### ISSUE TITLE
Custom Y axis labels

### ISSUE THREAD

**Issue by AbhishekDigitalSalt** [amcharts/amcharts5#495]
am chart automatically adds label on y axis with same interval. I want to add custom label at different interval of time.
I tried creating axis range to show custom label but if I try to hide Y axis default labels then axis range also gets hidden.

**Comment by martynasma** [comment]
You might need to set `visible: true` on the range's label (or `forceHidden: false` depending on how you are hiding your axis labels).

**Comment by AbhishekDigitalSalt** [comment]
> You might need to set `visible: true` on the range's label (or `forceHidden: false` depending on how you are hiding your axis labels).

Can you give me syntax for it.

the syntax I am using is below



createRange(30, undefined);
createRange(20.5, undefined);
createRange(13, undefined);
createRange(0, undefined);
createRange(-13, undefined);
createRange(-20.5, undefined);
createRange(-30, undefined);

yRenderer.labels.template.set("forceHidden", true);

**Comment by martynasma** [comment]
I could look at your code if you posted your working chart on CodePen.
