### ISSUE TITLE
Sunburst font-color label of each node can we change.

### ISSUE THREAD

**Issue by shanqq** [amcharts/amcharts5#497]
I want to change the font-color changes in label of the sunburst node. for each node i want to have different color.
 - amCharts 5
-- TypeScript, etc.

**Comment by martynasma** [comment]
You can use [template fields](https://www.amcharts.com/docs/v5/concepts/settings/template-fields/) for that.

E.g.:

```JavaScript
series.labels.template.setAll({
  templateField: "labelSettings"
});
```

And in data you could have this in each node:

```
....
labelSettings: {
  fill: am5.color(0x0ff000)
}
...

**Comment by shanqq** [comment]
okay thanks
