### ISSUE TITLE
Customize ZoomOut button

### ISSUE THREAD

**Issue by nseb** [amcharts/amcharts5#5]
How customize zoomOut Button , example like Rectangle with border radius.

**Comment by martynasma** [comment]
Button object is accessible via chart's `zoomOutButton` setting. It's an object of type `Button`. You can use it to configure it any way you see fit.

More info:
https://www.amcharts.com/docs/v5/charts/xy-chart/zoom-and-pan/#Zoom_out_button

**Comment by franz-86** [comment]
Hi, I re-open this post if possible.

I would like to know what is the event that controls the disappearance of the zoomOutButton when the plot is completely zoomed out. I would like to customise the functionality of the button and make it zoom at a particular x-range when clicked, but I would keep it always visible, so I need to deactivate the event that hides the button.

Many thanks
