### ISSUE TITLE
Disabling wheelY zoom does not work

### ISSUE THREAD

**Issue by samkristoff** [amcharts/amcharts5#50]
Hey all,

I have an XY chart with `wheelY` action is set to `zoomX`.  Zooming with the scroll wheel works as expected.

However setting `zoomX` to `none`  as shown below does not disable the scroll wheel zoom action.  The pan action is disabled as expected

```
chart.setAll({
    panX: false,
    wheelY: "none"
});
```

[Here is a demonstration video](https://share.vidyard.com/watch/sEjPS15zCowAWMLseKeRvY?).

And [Here is a JSfiddle](https://jsfiddle.net/samkristofftulu/d63oehLx/13/) demonstrating this.

**Comment by martynasma** [comment]
Your jsFiddle has `wheelY: "zoomX"` set. If I change it to `"none"` mouse wheel does nothing.

**Comment by samkristoff** [comment]
Yes, `wheelY: "zoomX"` is set when the chart is created on line 12.  Clicking the **Disable Zoom/Pan** button below the chart triggers the `disableZoomPan()` function on line 95 which sets `wheelY: "none"`, but this does not disable the chart.

The Disable zoom/pan button is just below the chart and may be off the bottom of the screen depending on how jsfiddle decides to organize the frames.

**Comment by martynasma** [comment]
Ah ok, I was viewing fiddle on a laptop screen which made bottom part not visible, hence missing the point.

Sorry.

We'll look into this.

**Comment by zeroin** [comment]
This can be solved by setting bot wheelX and wheelY to "none". The thing is that there is one listener for both events, so if either is not none, the default behavior of wheel is disabled. We will think if we want to change the defaults.

**Comment by samkristoff** [comment]
I set both to `"none"` and it works.  Thank you!
