### ISSUE TITLE
Can we access the sunburst levels in amcharts 5 as we can access in amcharts 4

### ISSUE THREAD

**Issue by shanqq** [amcharts/amcharts5#500]
I am trying to find the method that can give me the each level node of sunburst. particular i want each level node as separate variable. i tried finding it but was not able to find. in amcharts 4 i can find that but not in amcharts 5

**Comment by martynasma** [comment]
Just to make sure: you need get nodes in specific level OR you need to get specific node in a level OR you need to get level of the node?

**Comment by shanqq** [comment]
i need to disable hover effect on specific nodes

**Comment by martynasma** [comment]
How do you identify which nodes to disable hover on?

Do you disable hover effect on all nodes of some level? Or individual nodes within one level?

If you had a working CodePen on how it is implemented in amCharts 4, I'd be asking less questions ;)

**Comment by shanqq** [comment]
i just need to access nodes if i got three children of root node. like in amcharts 4 how we access levels.

**Comment by martynasma** [comment]
Thanks.

You can iterate through series' `nodes` and collect required ones based on their "depth":

```JavaScript
var level1nodes = [];
series.nodes.each(function(node) {
  if (node.dataItem.get("depth") == 1) {
    level1nodes.push(node);
  }
});
console.log(level1nodes);
```

**Comment by shanqq** [comment]
thanks alot

**Comment by shanqq** [comment]
I want to make the hover off at specific node via level setting. can we do
that right ?
