### ISSUE TITLE
Range Axis the tooltip are showing the series background colour in the rangeitem. how can we change the tooltip background in both the range different.

### ISSUE THREAD

**Issue by shanqq** [amcharts/amcharts5#501]
Was trying to make the tooltip change color in the rangeitem but it is by default taking the series color in the tooltip bg. 
how can we distinguish the color in the range item. 
It will be very helpful if you can tell me i tried hard enough to find this in amcharts 5 but was not able to.

**Comment by martynasma** [comment]
Take a look at this doc, which explains how to stop color inheritance:
https://www.amcharts.com/docs/v5/concepts/common-elements/tooltips/#Colors

**Comment by shanqq** [comment]
https://codepen.io/team/amcharts/pen/XWRoPVB?editors=1010 
i amtrying to change on this rangeseries the tooltip bg but it is only accepting the first main series one bg color.

**Comment by martynasma** [comment]
Just to make sure: you need tooltip to be blue over blue sections of the series, and orange over orange sections?

**Comment by shanqq** [comment]
Yeah thanks

**Comment by zeroin** [comment]
Here is a demo:
https://codepen.io/team/amcharts/pen/wvmyoYG/8b5cc7ea69164a872be3811670c2fd52

You muse set:
`series.get("tooltip").set("getFillFromSprite", false);`

And then, on tooltipDataItem change loop through all the ranges and use color from the range.

**Comment by enjoywithouthey** [comment]
> Here is a demo: https://codepen.io/team/amcharts/pen/wvmyoYG/8b5cc7ea69164a872be3811670c2fd52
> 
> You muse set: `series.get("tooltip").set("getFillFromSprite", false);`
> 
> And then, on tooltipDataItem change loop through all the ranges and use color from the range.

How would you change the background colors of the axis tooltips to match the fillFromSprite?

**Comment by zeroin** [comment]
Just do the same as for the series tooltip:

`xAxis.getTooltip().get("background").set("fill", fill);`

https://codepen.io/team/amcharts/pen/wvmyoYG/8b5cc7ea69164a872be3811670c2fd52
