### ISSUE TITLE
"Selectended" cursor event not triggered on small drags

### ISSUE THREAD

**Issue by cwooldridge1** [amcharts/amcharts5#502]
I noticed that when using "selectstarted" and "selectended" on XYcursor if the drag movement is very small such as 1 element "selectended" event is not triggered. Here is an screen shot from the demo on your guys [website](https://www.amcharts.com/demos/selecting-and-marking-multiple-ranges/):
<img width="987" alt="image" src="https://user-images.githubusercontent.com/85259389/180589586-863efe00-0161-4f06-bf02-c0d71b84c20f.png">
It is slightly hard to see but you'll notice it is to the left of the cursor you will see what looks like a discrepancy in the grid line which in reality is actually the result of "selectended" not being called. You can tell when in this demo when you scroll the highlight does not stick to the range in where it is placed and rather sticks to the relative percentage also when cursor moves on/off of the chart it will appear/reappear until new drag occurs

**Comment by martynasma** [comment]
This is actually by design. When you click, some small movement will occur. Distance between pointer down and up points is how we distinguish between actual drag/move and a "click". I believe that distance is hardcoded at 5px.
