### ISSUE TITLE
Bubble Chart export image issue

### ISSUE THREAD

**Issue by mayurhotwani** [amcharts/amcharts5#503]
**Bug description**
- When I use exporting menu OR exporting API's download/exportImage/export function on the Bubble XY chart, the chart gets distorted

**Environment (if applicable)**
amcharts latest version - 5.2.14
Angular 12

**Additional context**
Attaching the video recording of the bug I am facing: 

https://user-images.githubusercontent.com/89910982/180799343-d85aae59-61e5-4717-ae63-05a62e3b95e2.mov

**Comment by martynasma** [comment]
Ummm, I'm stumped. It looks like the chart gets resized indefinitely. However, we don't do that on export.

Is there any way you can reproduce this on a runnable CodePen or jsFiddle?

**Comment by mayurhotwani** [comment]
@martynasma Thank you for your response, but when u said that the chart is getting resized, I set the **root.autoResize to false** and it worked for me 😄
