### ISSUE TITLE
Area bullet when there's no data is not 0 

### ISSUE THREAD

**Issue by justine-mlss** [amcharts/amcharts5#505]
Hello, 

Here is my issue : when I calculate Y-axis in percent, when there is no data, the bullet is not at 0% but higher than 100% and no bullet tooltip : 
![no-data](https://user-images.githubusercontent.com/66368359/180804629-52d91dc4-ca1f-445e-936a-37e8df1c279f.png)

When I'm not in percent, I've got bullet on 0 and a tooltip : 
![no-percent](https://user-images.githubusercontent.com/66368359/180804740-ae098e76-6538-46be-a6a4-879b7e71f0e1.png)

I want to have my bullet at 0 if there is no data in percent 

y-axis configuration : 
```
const yRenderer = am5xy.AxisRendererY.new(root, {});
const yAxis = chart.yAxes.push(
        am5xy.ValueAxis.new(root, {
          renderer: yRenderer,
          calculateTotals: true,
          numberFormat: "#'%'",
          min: 0,
          max: 100,
          strictMinMaxSelection: true,
          opacity: 0.5,
        }),
      );
```

bullet configuration : 
```      // Configure data bullets
      series.bullets.push(function() {
        const circle = am5.Circle.new(root, {
          radius: 3,
          fill: am5.color(color),
          fillOpacity: 1,
        });
        circle.adapters.add('fill', function(fill) {
          return fill;
        });
        return am5.Bullet.new(root, {
          sprite: circle,
        });
      });
```

Thank you !!

**Comment by martynasma** [comment]
I'm assuming that by "there's no data" you mean zero values in data.

I would say that the behavior is mathematically correct. If all values in stack result in 0 (zero), then any zero value is 100%, hence it is drawn at the top.

The correct "no data" behavior would be to completely omit the value key in data. In such case the bullet would not be shown altogether, correctly indicating lack of value.

Here's an example to illustrate what I mean:
https://codepen.io/team/amcharts/pen/xxWYqGZ/3cd4c6ec6315abd7910551d112f387a6?editors=0010

**Comment by justine-mlss** [comment]
@martynasma ok i understand, thank you :)
