### ISSUE TITLE
Zoom callback

### ISSUE THREAD

**Issue by hahatulk** [amcharts/amcharts5#509]
Are there any zoom events to pass callbacks for XYChart?

**Comment by martynasma** [comment]
No directly on `XYChart`. I would use events on your axis, e.g.:

https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#events

**Comment by hahatulk** [comment]
> No directly on `XYChart`. I would use events on your axis, e.g.:
> 
> https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#events

i mean callback for `.zoom()` or `.zoomToDates()` functions

**Comment by martynasma** [comment]
I might be missing something, but what do you mean?

Both of those are methods to `DateAxis`. Calling them both will invoke axis' zoom-related private property change events, such as `selectionMin`, as mentioned in the tutorial I linked to.

**Comment by hahatulk** [comment]
> I might be missing something, but what do you mean?
> 
> Both of those are methods to `DateAxis`. Calling them both will invoke axis' zoom-related private property change events, such as `selectionMin`, as mentioned in the tutorial I linked to.

`selectionMin `also is triggered with mouse zoom, in my case mouse should not trigger it but only zoom() like functions

**Comment by martynasma** [comment]
Well, there's no separate events for zoom triggers via API function.

That said, you are calling those functions from your code. You can adjust your handler function code to react only once after `zoom` or `zoomToDates` method was called, and ignore it the rest of the time.

Does that make sense?

**Comment by hahatulk** [comment]
> Well, there's no separate events for zoom triggers via API function.
> 
> That said, you are calling those functions from your code. You can adjust your handler function code to react only once after `zoom` or `zoomToDates` method was called, and ignore it the rest of the time.
> 
> Does that make sense?

i have no idea how to do this 😅

**Comment by martynasma** [comment]
Something like this:

```JavaScript
var zoomedByAPI = false;

xAxis.onPrivate("selectionMin", function(value, target) {
  if (zoomedByAPI) {
    // do what you have to do here
    // ...
  }
  zoomedByAPI = false;
});
```

Now, you just have to set `zoomedByAPI = true` before any `zoomToDates()` call.

**Comment by hahatulk** [comment]
> Something like this:
> 
> ```js
> var zoomedByAPI = false;
> 
> xAxis.onPrivate("selectionMin", function(value, target) {
>   if (zoomedByAPI) {
>     // do what you have to do here
>     // ...
>   }
>   zoomedByAPI = false;
> });
> ```
> 
> Now, you just have to set `zoomedByAPI = true` before any `zoomToDates()` call.

thanks, but i think its not my case. Thanks for response
