### ISSUE TITLE
Is it possible to duplicate date axis labels?

### ISSUE THREAD

**Issue by samkristoff** [amcharts/amcharts5#51]
Hi,

I have an XY chart with a date (x) axis and several value (y) axes for different data types.  When several axis are stacked the chart may become too tall to fit on the page.  In this case it would be useful to see the date axis labels at the top **and** bottom of the chart or better yet beneath each Y axis group.  Is this possible?

Here is an example with one date axis and several Y axes groups.  I have a single current axis, severnal on/off axis (an axis group if you will) and one temperature axis.  The Date labels only appear below the bottom most axis:

![image](https://user-images.githubusercontent.com/1994983/140227258-d78464a5-f218-4cb2-b982-eaa314cbae52.png)

Is it possible to insert a copy of the date axis labels between some of the y Axis like the image below?
![image](https://user-images.githubusercontent.com/1994983/140229307-05969e7d-d935-45bd-bb8e-7f9a3f096736.png)

I was able to add labels to the Y Axes using the `axisHeader` but don't know how I would get the values and spacing to match the grid and date axis.

Thanks

**Comment by martynasma** [comment]
No, I'm afraid there's no way to do that. Sorry :(

**Comment by zeroin** [comment]
So we thought about this and we can offer this solution - move xAxis labels to the panel over which currently cursor is. I've updated our demo to illustrate this, it's actually quite a cool idea: https://www.amcharts.com/demos/vertically-stacked-axes-chart/

Even if you don't have a cursor, you could detect window scrolling and update axis position based on which page position your user currently is.

**Comment by samkristoff** [comment]
Awesome, thanks!

**Comment by samkristoff** [comment]
For my use case I had to updat the event handler code to use `chart.leftAxesContainer.children` rather than `chart.yAxes` since I re-order the Y axis in leftAxesContainer after pushing them to the chart.

**Comment by samkristoff** [comment]
Also, when calculating the Y offset you may want to include the top and bottom margin of the YAxis.

Ex.
```
...
 const marginBottom = yAxis.get("marginBottom");
 const marginTop = yAxis.get("marginTop");
 const y = yAxis.y() + yAxis.height() + marginBottom + marginTop;
...
```
