### ISSUE TITLE
cursor selectended event incorrectly fires

### ISSUE THREAD

**Issue by JonathanWylie** [amcharts/amcharts5#510]
If you enable selection on an XYChart and single click with no drag to select an area then the selectionended event still fires even though no selection was actually made.
In such a case the target.selection.localBounds() for the selection comes out as this nonsense:

{left: 10000000, top: 10000000, right: -10000000, bottom: -10000000}

Amcharts: 5.2.7
React: 18

**Comment by martynasma** [comment]
Can you post your chart on CodePen so that we can test?

I'm afraid I'm having trouble reproducing this behavior:
https://codepen.io/team/amcharts/pen/oNqoPOa/9e0b6a262075a49f92d029b50976768b?editors=0010

"selectended" event does not fire for me when I just click on the chart.

**Comment by JonathanWylie** [comment]
@martynasma did you create a click handler as well?

**Comment by martynasma** [comment]
No. What click handler?

**Comment by JonathanWylie** [comment]
I can't recreate the problem in you're codepen, so I'll have to have a look more closely to see other things may be causing this.
I have a click handler and a selectended handler, I thought maybe the combination of both handlers was causing the problem, but it isn't. So I will try to find what the combination is that causes it.

**Comment by martynasma** [comment]
Sounds good. A repro CodePen would be vey helpful.
