### ISSUE TITLE
Migrate Amcharts 4 to Amcharts 5

### ISSUE THREAD

**Issue by mikius** [amcharts/amcharts5#512]
Hello,
I work on a web project that contains the armcharts 4 library and I have to pass it to version 5 except that in the documentation, there are not many elements or examples to put this in place on my project.
Is there anyone who has this problem in order to guide me on my project?

Thank you,

**Comment by martynasma** [comment]
If you do have an amPlus support subscription, you can contact us at contact@amcharts.com and we'll do our best to help you out with the issues you are having when converting to amCharts 5.
