### ISSUE TITLE
Year on xAxis in stock chart Amcharts5

### ISSUE THREAD

**Issue by ankit-mercer** [amcharts/amcharts5#514]
How to display year on dateAxis instead of minutes or days in stock chart and also what does the date in the below line justifies: { Date: 1642024800000, Open: 86.940002, High: 86.940002, Low: 79.889999, Close: 80.309998, Volume: 13677500 }

**Comment by martynasma** [comment]
Please refer to this tutorial about setting date formats on a date axis:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#date-formats

`1642024800000` is a JavaScript timestamp for Thu Jan 13 2022.

**Comment by ankit-mercer** [comment]
[IdCard_178275.pdf](https://github.com/amcharts/amcharts5/files/10330387/IdCard_178275.pdf)

**Comment by ankit-mercer** [comment]
[ClaimForm_B.pdf](https://github.com/amcharts/amcharts5/files/10334821/ClaimForm_B.pdf)
[Clam_Form_A.pdf](https://github.com/amcharts/amcharts5/files/10334822/Clam_Form_A.pdf)

**Comment by ankit-mercer** [comment]
[FS1227171.zip](https://github.com/amcharts/amcharts5/files/10352655/FS1227171.zip)

**Comment by ankit-mercer** [comment]
[Report (1).pdf](https://github.com/amcharts/amcharts5/files/10352704/Report.1.pdf)
