### ISSUE TITLE
Is it possible to use tooltipHTML with combined series

### ISSUE THREAD

**Issue by tscislo** [amcharts/amcharts5#515]
Is it possible to use tooltipHTML in following example: https://codepen.io/tscislo/pen/poLdNaa

**Comment by xorspark** [comment]
Yes it's possible. As mentioned in the [docs](https://www.amcharts.com/docs/v5/concepts/common-elements/html-content/#Tooltips), you need to set the `labelHTML` property in the tooltip, so the adapter needs to be on that property:

```
  tooltip.adapters.add("labelHTML", function(text, target) {
    text = ''
    chart.series.each(function (series) {
      text += '<span style="color: ' + series.get("stroke").toString() + ';">●</span> <b>' + series.get("name") + ':</b> {' + series.get("valueYField") + '}<br>'
    })
    return text
  })
```

[Updated codepen](https://codepen.io/team/amcharts/pen/VwXrbbo/5bcadffe211eacd0aef157e867eb71a1?editors=0010).

**Comment by tscislo** [comment]
Thanks that works nicely!
