### ISSUE TITLE
Y axis does not dynamically adapt scope when x-axis is ValueAxis

### ISSUE THREAD

**Issue by franz-86** [amcharts/amcharts5#516]
**Bug description**

The auto adaptation of min and max when the plot is zoomed ( https://www.amcharts.com/demos/line-chart-with-scroll-and-zoom/ ) is not working when the x-axis is a ValueAxis.

I also tried applying "strictMinMaxSelection: true" on yAxis but nothing happens

var yAxis = chart.yAxes.push(am5xy.ValueAxis.new(root, {
      strictMinMaxSelection: true,
      renderer: am5xy.AxisRendererY.new(root, {})
    }));

Any suggestion? 
Thanks

**Comment by zeroin** [comment]
It's by design, we do not adjust min and max in any way when both axes are ValueAxes.

**Comment by franz-86** [comment]
thanks for your reply. 
Is there a way to customize it and force the auto-zoom? 
The main difficulty is that `MinMaxSelection` does not work on the visible range but takes min and max of the entire plot. Are there any functions that return the visible x-range? In this way I might evaluate local min and max from the data array...

**Comment by zeroin** [comment]
Well, It would be quite complicated, the rough idea would be to monitor start and end settings of the axis, and when they change, loop through all your data, pick values which fall into the selected range, get min/max values and then zoom to these values.

**Comment by cwooldridge1** [comment]
@franz-86 After having the same issue I came up with a pretty simple but effective solution
First, have these event listeners:
```
    chart.plotContainer.events.on('wheel', func);
    chart.events.on('panended', func);
    chart.events.on('boundschanged', func);
```
Inside of the func callback, you should first find what data is currently in the x-axis zoom scope/visible x-range:
```
      const chartRelativeStartPosition = xAxis.get('start');
      const chartRelativeEndPosition = xAxis.get('end');
      const chartStartValue = xAxis.positionToValue(chartRelativeStartPosition);
      const chartEndValue = xAxis.positionToValue(chartRelativeEndPosition);
```

Once you have the start and end value of the current x-axis scope just search for/calculate the corresponding y value and zoom to those values:
`
      yAxis.zoomToValues(correspondingYValueStart, correspondingYValueEnd);
`

**Comment by zeroin** [comment]
Glad it worked!

**Comment by franz-86** [comment]
Hi, 
thanks for the suggestion, but I'm getting a weird behavior when invoking `xAxis.get('start')` or `xAxis.get('start')` when xAxis is a ValueAxis: when I console.log xAxis and manually dig into its _settings I can see some floating point value, but when I console.log xAxis.get('start') I always get 0 and xAxis.get('end') always give me 1.  
Similar weird behavior when I use `xAxis.getPrivate('selectionMin')` or selectionMax: I see different values when I directly inspect xAxis rather then those printed out when I console.log the private value

Any idea?

**Comment by zeroin** [comment]
I guess you do console.log before values change. you can monitor the change of all values like this:
```
xAxis.on("start", (start)=>{
   console.log(start)
})
```

**Comment by franz-86** [comment]
Super-pro :D 
Is this a way to set an event handler on Settings change?

**Comment by zeroin** [comment]
The code above is event handler. It will be called each time start changes.
