### ISSUE TITLE
Cursor on click event does not work reliably

### ISSUE THREAD

**Issue by franz-86** [amcharts/amcharts5#517]
**Bug description**

I'm trying to trigger an event based on cursor position when click. 
I've added this eventHandler:

cursor.events.on("click", function(ev){
      var x = ev.target.getPrivate("positionX")
      var value = Math.round(xAxis.positionToValue(x))
      alert("Clicked on round " + value)
    })

Two issues noticed:
 1) the alert is not always triggered when click. Some click works fine, sometimes not .. 
 2) the conversion from x to value, using positionToValue() as suggested in the docs, is not working properly when the plot is zoomed or panned. The function always converts the xPosition to the xValue of the un-zoomed plot

**Comment by martynasma** [comment]
I would not set click event on cursor, but rather on `chart.plotContainer`.

I'm not entirely sure about how to convert relative position into zoomed position. Will get back to you on that.

**Comment by franz-86** [comment]
many thanks for your suggestion!

This eventHandler solve my problem:

chart.plotContainer.events.on("click", function(){
      const dataItem = series.get("tooltip").dataItem
      const round = dataItem.dataContext.round
      alert("Clicked on round " + round)
    })

**Comment by zeroin** [comment]
In order to convert cursor's position to a zoomed axis position, you can use `axis.toAxisPosition(position)` method. Or you can use coordinate of the click and do it like this:

`var value = yAxis.positionToValue(yAxis.coordinateToPosition(point.y));`

Here is a working example:
https://www.amcharts.com/demos/drawing-chart-series-with-mouse-or-touch/

**Comment by ijpatricio** [comment]
@franz-86 thank you so much for posting this here

@martynasma thank you so much for also pointing me in the right direction

This should be in the docs somehow!
