### ISSUE TITLE
Incorrect value in legendLabelText placeholder

### ISSUE THREAD

**Issue by olimexsmart** [amcharts/amcharts5#519]
I've modified the Step Line Chart example to include a legend that updates its text to the Y value currently pointed by the cursor:

[Here the jsfiddle](https://jsfiddle.net/g09qwdbv/)

The problem is that the value is correct only in the first half of the step, while in the second half it updates already to the next value.

![correct](https://user-images.githubusercontent.com/17432947/181754596-8273bfb4-749e-4f19-82dd-3b7a90a14eff.PNG)
![wrong](https://user-images.githubusercontent.com/17432947/181754609-ef0db629-1abf-4af0-b916-52a11697083b.PNG)

**Comment by martynasma** [comment]
Both of your screenshots show same value in series tooltip and legend. Same thing in the jsFiddle.

What am I missing?

**Comment by olimexsmart** [comment]
The problem is that in both screenshots the cursor is on the same "step". 

The expected behavior is that the value (in tooltip and legend both) is 0.019 in both screenshots.

I did not notice that the same problem is on the tooltip too, my guess at this point is that the bug is not on the legend but rather on the cursor or placeholder.

**Comment by zeroin** [comment]
This is how ValueAxis works, it shows tooltip of the nearest data point. To solve your problem, you should change your xAxis type to DateAxis and then set xAxis for your cursor. This way the line will snap to the position where the tooltip is: 
https://codepen.io/team/amcharts/pen/rNdJWzG

I don't see a way to solve this with ValueAxis.

**Comment by olimexsmart** [comment]
Thanks, let's see what the authors decide to do about this
