### ISSUE TITLE
How to customize tooltip based on YAxis value

### ISSUE THREAD

**Issue by samkristoff** [amcharts/amcharts5#52]
Hey,

I have some data on an XY plot.  The values are all 0 or 1 representing On or Off.  In amcharts4 I used the following code to make the tooltip show "On" or "Off" rather than 0 or 1.  

````
this.yAxisSecondary[context].series.tooltip.label.adapter.add(
  "textOutput",
  (text, target, key) => {
    if (!isNil(target.dataItem)) {
      const value = target.dataItem.values.valueY.value;
      return `${text} ${value === 1 ? "on" : "off"}`;
    }
    return text;
  }
);

````
I thought the Amcharts5 equivalent would be something like the following but the code below only seems to trigger once and the On/Off value calculated gets applied to all points (rather than each point getting it's own on/off text based on its values).

```
 tooltip.label.adapters.add("tooltipText", (text, target) => {
    const dataItem = get(target, "dataItem", null);
    if (isNil(dataItem)) {
        return text;
    }

    const yValue = get(dataItem, ["dataContext", "val"], null);

    if (isNil(yValue)) {
        return text;
    }

    return `${text} ${yValue === 1 ? "On" : "Off"}`;
});

```

What is the best way to accomplish this?

Thanks!

**Comment by martynasma** [comment]
Well, you should probably use an adapter for "text" rather than "tooltipText":

```JavaScript
tooltip.label.adapters.add("text", (text, target) => {
   ...
```

**Comment by samkristoff** [comment]
Thank you, that works!
