### ISSUE TITLE
how to access bullets property of a series?

### ISSUE THREAD

**Issue by franz-86** [amcharts/amcharts5#520]
I'm trying to access the bullets property of a series, in order to change the style of a single bullet on my plot.

At the moment I attempted, unsuccessfully, like this:
`
series.events.once("datavalidated", function(ev) {
      console.log(series.dataItems[0].bullets)
    });
`

This logs undefined even if, when inspecting `series.dataItems[0]`, bullets property is there.

Any suggestion?
thanks

**Comment by martynasma** [comment]
Bullets are created at a later stage than data is validated.

If you need to modify a bullet when it is created, why not do that in bullet creation function itself?

**Comment by franz-86** [comment]
you're right, but how can I know what bullet is being created when I execute `series.bullets.push` ?

**Comment by martynasma** [comment]
You push a function, which is executed whenever a bullet is created. It receives a target data item as third parameter, which you can use for whatever customization you need to do. E.g.:

https://www.amcharts.com/docs/v5/concepts/common-elements/bullets/#selectively-displaying-bullets
