### ISSUE TITLE
how to position axisBullets?

### ISSUE THREAD

**Issue by franz-86** [amcharts/amcharts5#521]
I'm trying to add labels on the xAxis, but I can't position them where I need. 
I created an array of dataLabels like in this example:

```JavaScript
const dataLabels = [{xValue: 10, color:"#f00"}, {xValue: 18, color:"#0f0"}]
```

and pushed the bullet function as in the documentations:

```JavaScript
var xAxis = chart.xAxes.push(am5xy.ValueAxis.new(root, {
      renderer: am5xy.AxisRendererX.new(root, {}),
      bullet: function (root, axis, dataItem) {
        if(dataItem.dataContext){
          return am5xy.AxisBullet.new(root, {
            location: 0.5,
            sprite: am5.Circle.new(root, {
              radius: 5,
              fill: dataItem.dataContext.color
            })
          });
        }
      }
    }));
    xAxis.data.setAll(dataLabels);
```

How can I let xAxis know to use dataLabels.xValue to position the bullets?
Many thanks

**Comment by martynasma** [comment]
Axis bullets are placed on each grid. You can't use axis data to specify where bullets are placed.

If you need to place bullets at arbitrary values on a `ValueAxis`, I suggest you use axis ranges:

https://www.amcharts.com/docs/v5/charts/xy-chart/axes/axis-ranges/#bullet

**Comment by franz-86** [comment]
what if I need to add axis ranges at dynamical values depending on the visible scope of the plot? For example only 2 vertical lines at 1/3 and 2/3 of the visible x range. I would like this feature to behave like `minGridDistance` so that, when the user zooms in or out, the axis ranges shown update automatically

**Comment by martynasma** [comment]
You would need to update values of the axis ranges dynamically, then.

However, if you need to place some sort of icon at a fixed position within plot area, you can just push those elements into `chart.plotContainer.children`.

**Comment by franz-86** [comment]
thanks, that's a good idea. I might still need to dynamically change the label text but the icon remains fixed
