### ISSUE TITLE
How to justify area legend labels ? 

### ISSUE THREAD

**Issue by justine-mlss** [amcharts/amcharts5#522]
Hello :) 

I've juste got a question about my Area legend labels, is there a way to center aligning or justify content label in container ?

Exemple : there is a lots of blank space at the right of green label. 
![amcharts-legend](https://user-images.githubusercontent.com/66368359/182118656-e09485d9-6f5e-4988-9660-cf505dd4efc5.png)
 
I configured a left padding of legend because I don't want legend labels below y-axis labels. 

My legend configuration is : 

```
  const legend = chart.children.push(
    am5.Legend.new(root, {
      minWidth: containerWidth,
      x: am5.p50,
      centerX: am5.p50,
      y: am5.percent(98),
      height: am5.percent(80),

      paddingTop: 20,
      paddingLeft: 60,

      verticalScrollbar: am5.Scrollbar.new(root, {
        orientation: 'vertical',
      }),
    }),
  );

  legend.labels.template.setAll({
    fontSize: areaFontSize,
  });
  legend.valueLabels.template.setAll({
    width: 0,
  });
  legend.markers.template.setAll({
    width: 10,
    height: 10,
  });
  legend.itemContainers.template.setAll({
    paddingTop: 0,
    paddingBottom: 0,
  });
  legend.data.setAll(chart.series.values);
```

Thank you

**Comment by zeroin** [comment]
Do you want the two bottom legend items to be in the middle (not possible) or just all the legend like it is now to be center-aligned?

**Comment by justine-mlss** [comment]
Hello @zeroin , i want all the legend center-aligned

**Comment by zeroin** [comment]
Not sure if I'll be able to help, but a codepen with the exact chart would help.
