### ISSUE TITLE
Pie tooltip text color (autoTextColor) with custom background tooltip color

### ISSUE THREAD

**Issue by justine-mlss** [amcharts/amcharts5#524]
Hello, 

I have customized pie slices background color and tooltip text color isn't a contrasting color. For example : 

![tooltip-pie](https://user-images.githubusercontent.com/66368359/182386115-c4c12a11-e603-4251-8aac-9c1b0af4c634.png)

I did the same thing in Area chart and i don't have the issue. 

* Creation of series : 
```
const series = chart.series.push(
      am5percent.PieSeries.new(root, {
        valueField: 'count',
        categoryField: 'label',
        fillField: 'color',
        alignLabels: false,
      }),
    );
```
* Configuration of tooltip : 
```
const tooltip = am5.Tooltip.new(root, {
      labelText: "{category}: [bold]{valuePercentTotal.formatNumber('0.00')}%[/] ({value})",
    });
    tooltip.get('background').setAll({
      fillField: 'color',
      fillOpacity: 0.6,
    });
    series.set('tooltip', tooltip);
    series.data.setAll(data);
```

I don't want to manually set the tooltip text color but, like in Area, the color of text tooltip should be readable (whatever the background color of the tooltip) : 

![area-tooltip](https://user-images.githubusercontent.com/66368359/182387193-2b41029f-29c2-4de4-80f2-2980a0e9f43b.png)

is it a bug ? 

Thanks
Justine

**Comment by justine-mlss** [comment]
@martynasma 

Shorter example of the issue : https://codepen.io/Justinemlss/pen/yLKKQgz

**Comment by martynasma** [comment]
Thanks for the link.

The issue is that you have set colors as strings, rather than `Color` objects. The code that calculates contrasting color can't work with strings.

This fixes it:

```JavaScript
series.data.setAll([
  { value: 10, category: "One", color: am5.color(0xE6E61C) },
  { value: 9, category: "Two", color: am5.color(0xC64C33) },
  { value: 6, category: "Three", color: am5.color(0x44D52A) },
  { value: 5, category: "Four", color: am5.color(0x1B211B) },
  { value: 4, category: "Five", color: am5.color(0xF3F5F3) },
]);
```

**Comment by justine-mlss** [comment]
@martynasma  thanks It's working well !
