### ISSUE TITLE
How to customise legend behavior

### ISSUE THREAD

**Issue by franz-86** [amcharts/amcharts5#525]
I would like to customise the onclick behavior of the legend.

Is it possible to reproduce this tutorial https://www.amcharts.com/docs/v4/tutorials/activate-deactivate-a-pie-slice-on-legend-click-instead-of-toggling/ with Amcharts5 ?
`legend.itemContainers.template.togglable = false;`. has no effect

**Comment by martynasma** [comment]
Follow this tutorial on how to disable toggling in legend:
https://www.amcharts.com/docs/v5/concepts/legend/#disabling-toggling

You can then add own click events if needed:

```JavaScript
legend.itemContainers.template.events.on("click", function(ev) {
  console.log(ev.target);
});
```

**Comment by martynasma** [comment]
If you set `clickTarget: "none"` on a legend, the related hover effects should be disabled as well:

```JavaScript
var legend = chart.children.push(am5.Legend.new(root, {
  centerX: am5.percent(50),
  x: am5.percent(50),
  layout: root.horizontalLayout,
  clickTarget: "none"
}));
```

**Comment by franz-86** [comment]
yes, clear, but I would like to customise click and hover behavior, after setting `clickTarget:"none"`

As you suggested 
```
legend.itemContainers.template.events.on("click", function(ev) {
  // do whatever needed
});
```
controls the onClick.

Now, I would like to control onHover and show the tooltip on the slice. How can I do it?
```
legend.itemContainers.template.events.on("pointerover", function(ev) {
        // How can I activate the series tooltip on the corresponding slice?
});
```

**Comment by martynasma** [comment]
Oh, I thought you didn't want the tooltip.

I suppose, something like this should bring hover effect back:

```JavaScript
legend.itemContainers.template.events.on("pointerover", function(ev) {
  var item = ev.target.dataItem.dataContext;
  var component = item.component;
  if (component && component.hoverDataItem) {
    component.hoverDataItem(item)
  }
});

legend.itemContainers.template.events.on("pointerout", function(ev) {
  var item = ev.target.dataItem.dataContext;
  var component = item.component;
  if (component && component.hoverDataItem) {
    component.unhoverDataItem(item)
  }
});
```

**Comment by franz-86** [comment]
Brilliant!!! It works fine
many many thanks
