### ISSUE TITLE
X axis labels are not responsive

### ISSUE THREAD

**Issue by AbhishekDigitalSalt** [amcharts/amcharts5#528]
Hi,

I am plotting a chart in React Js with the help of am chart, my chart width is half of screen. Columns are getting plotted exactly the way I want but labels with respect to columns are not align. If I zoom out the screen then It works perfectly.

I am attaching both cases in image format so you will get better look at it.

Any solution for this. Thank you in advance
![Screenshot (56)](https://user-images.githubusercontent.com/100406190/183022679-63b6aab5-d37c-4615-b7f7-7e426067bd57.png)
![Screenshot (55)](https://user-images.githubusercontent.com/100406190/183022691-ee5a9e1f-14da-4dc2-ae09-2e7e3d40c014.png)
.

**Comment by martynasma** [comment]
Looks like you need to increase granularity of your grid/labels:

https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#grid-density

**Comment by AbhishekDigitalSalt** [comment]
> Looks like you need to increase granularity of your grid/labels:
> 
> https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#grid-density

I have already tried it. But it didn't help. Any other solution I should be trying?

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle?

**Comment by AbhishekDigitalSalt** [comment]
> Looks like you need to increase granularity of your grid/labels:
> 
> https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#grid-density

hey, thanks. It worked. I was doing it wrong. your solution worked.
