### ISSUE TITLE
Add extra space to both left and right to x axis in GaplessCandleStickSeries

### ISSUE THREAD

**Issue by AbhishekDigitalSalt** [amcharts/amcharts5#531]
Hi, I am creating a gapless candle stick series. I couldn't use normal candle stick series because my data might have gaps in date / days. Hence I am chose gapless. But I want to add extra space on left and right horizontally. I tried extra min and extra max on x axis but it didn't help. any other option should I try. Thanks in advanced.

**Comment by zeroin** [comment]
Hi,

This is by design, it's how Gapless date axis works. The only way to add extra space would be to add data items to the end of your data with dates but no values.

**Comment by zeroin** [comment]
An alternative would be to set `end` for the xAxis after the data is validated:
https://codepen.io/team/amcharts/pen/zYWaZrM/2b24c6da2096035e560c36ea5068999b?editors=0010

```
series.events.on("datavalidated", function(){
  xAxis.set("end", 1.1)
})
```

but the dates for the extra space won't be displayed.

**Comment by AbhishekDigitalSalt** [comment]
Thanks it worked.

**Comment by AbhishekDigitalSalt** [comment]
> Remember, contributions to this repository should follow our [GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines).

Thanks it worked
