### ISSUE TITLE
Animate PieSeries

### ISSUE THREAD

**Issue by plojewski** [amcharts/amcharts5#532]
Hi there, how can I animate datas array change like in ColumnSeries https://codepen.io/team/amcharts/pen/poPMJVE but for PieSeries ?
I update all data after ajax success: series.data.setAll($chartData)

My series:
<pre>
series = chart.series.push(am5percent.PieSeries.new(root, {
	valueField: "value",
	categoryField: "label"
}));
</pre>

I changed to:
<pre>
series = chart.series.push(am5percent.PieSeries.new(root, {
	valueField: "value",
	categoryField: "label",
	interpolationDuration: 1000,
	interpolationEasing: am5.ease.inOut(am5.ease.elastic)
}));
</pre>

and update data like:
<pre>
$chartData.forEach(function(element,i) {
	series.data.setIndex(i, {
		value: element.value
	});
});
</pre>

In an old amCharts responsible for it is:
<pre>
chart.animateData($chartData, {
	duration: 1000
});
</pre>

but I doesn't work. Could you help please?

**Comment by zeroin** [comment]
Hi,

A codepen would help to understand. Here is an example of a pie chart with data being updated:
https://codepen.io/team/amcharts/pen/NWYBGyq/63e8dc8785de08ef7b6fb8cefc7b8b4d

**Comment by plojewski** [comment]
@zeroin Thank you. That's right now!
