### ISSUE TITLE
Align fixed-width columns in the center of a cell

### ISSUE THREAD

**Issue by DanielScholte** [amcharts/amcharts5#536]
**Question**

I'm trying to align fixed-width columns in the center of a cell, regardless of the cell width. I've looked through the documentation but have been unable to find such a feature. Is this possible with amCharts 5?

I did come across [the Cell start/end locations](https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#cell-start-end-locations) section of the documentation.  
This would allow me to center the columns in the cell by setting the width of the columns to 100% and setting the `cellStartLocation` and `cellEndLocation` of the axis renderer.  
This, however, would not work in my situation, as these properties only allow a percentage offset for the start and end location. This would either change the width of the columns if the width of the cell changes, or would cause space between the columns if you set a fixed width.

Is there a different option for centering the columns within the cells?

**Environment (if applicable)**

amCharts version 5.2.15

**Comment by martynasma** [comment]
Columns should be centered within the cell regardless of whether their width is relative or fixed.

If you have a setup that acts otherwise, maybe you can post it on CodePen?

**Comment by DanielScholte** [comment]
My apologies for the confusion.  
What I'm looking for is centering the fixed-width columns, but removed the gap between the columns in a cell.  
Take [the following codepen](https://codepen.io/danielscholte/pen/mdxjKqB) as an example.  
I would like to remove the space in between the columns:  
![image](https://user-images.githubusercontent.com/22204349/183899144-e95aeaf9-215a-4ac7-a5bd-bf430c732a71.png)
So it would look like the following picture in your documentation:
![](https://www.amcharts.com/docs/v5/wp-content/uploads/sites/7/2021/07/cell_width_reduced.png)

The last image is taken from [the previously mentioned section](https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#cell-start-end-locations) in your documentation. This would allow the columns to be centered without space in between them. But it would not allow the columns to have a fixed width, as that would require you to add a `cellStartLocation` and `cellEndLocation` to the axis renderer and to give the columns a width of 100%.

**Comment by martynasma** [comment]
Gotcha. It makes sense now.

Unfortunately, I'm not aware of a way to enable it, save for dynamically calculating `cellStartLocation`/`cellEndLocation` based on `chart.plotContainer.width()` and number of categories in your chart.

However, if chart is zoomable, you would need to watch zoom events and re-apply updated values.

From the sound of it, it looks like it can be done, but I don't have a ready-made demo for you.

Hope it make sense.

**Comment by DanielScholte** [comment]
I see, thanks for the response.  
Calculating it could work, but as it isn't critical for me I'd rather not have an over complicated implementation and just use a fixed `cellStartLocation`/`cellEndLocation` for now.  
Is something like an alignment setting for the AxisRenderer possible in a future release of AmCharts?

**Comment by martynasma** [comment]
Wait, it just hit me: we can set both `cellStartLocation` and `cellEndLocation` to middle (0.5), then shift one column slightly to the left, and the other to the right using `dx` setting.

```JavaScript
var xAxis = chart.xAxes.push(am5xy.CategoryAxis.new(root, {
  categoryField: "year",
  renderer: am5xy.AxisRendererX.new(root, {
    cellStartLocation: 0.5,
    cellEndLocation: 0.5
  })
}));

......

series.columns.template.setAll({
  tooltipText: "{name}, {categoryX}:{valueY}",
  tooltipY: 0,
  width: 30,
  dx: -15
});

.....

series2.columns.template.setAll({
  tooltipText: "{name}, {categoryX}:{valueY}",
  tooltipY: 0,
  width: 30,
  dx: 15
});
```

Here's a working prototype:
https://codepen.io/team/amcharts/pen/JjLBBmL??editors=0010

**Comment by DanielScholte** [comment]
That seems to work, thanks!  
I assume this implementation wouldn't work with something like `width: 100%` and `max-width: 30px`?  
As it would currently overlap with other cells if there isn't enough space.  
Regardless, this is great, thank you very much for the example.

**Comment by martynasma** [comment]
Yeah, the `dx` pixel value is directly based on pixel width of column, so it would not work with relative column width.
