### ISSUE TITLE
disable fading pixels in Line series?

### ISSUE THREAD

**Issue by hahatulk** [amcharts/amcharts5#538]
How do i disable this fading pixels above and below the Line series?
Where is problem that kind of shadow created when 2 or more series are on the same position

![image](https://user-images.githubusercontent.com/32220397/183892794-1b2a81fa-b9f4-4f34-9a06-a1ca07cf6fa1.png)
![image](https://user-images.githubusercontent.com/32220397/183893203-ea8c3d3b-57cf-407d-8254-15f9d3197fc7.png)

**Comment by martynasma** [comment]
There's no way to disable it. It's how computer graphics deal with elements placed at not exact coordinates.

Without anti-aliasing the plots would looked very jagged.

**Comment by hahatulk** [comment]
> There's no way to disable it. It's how computer graphics deal with elements placed at not exact coordinates.
> 
> Without anti-aliasing the plots would looked very jagged.

i there way to disable anti-aliasing only for series?

**Comment by martynasma** [comment]
No, I'm afraid.

**Comment by hahatulk** [comment]
> No, I'm afraid.

thanks for help😅
