### ISSUE TITLE
Microchart date value

### ISSUE THREAD

**Issue by alienbuild** [amcharts/amcharts5#54]
I'm currently migrating from Amcharts 4 to 5 and going through implementing the updated microcharts/sparklines.

I seem to be having trouble getting Amcharts 5 to play ball with me date value though, which is formatted as:
`date: '2021-11-05T20:59:15.717Z'`

I noticed that the example Microchart of Amcharts 5 uses a unix timestamp (ref: https://codepen.io/team/amcharts/pen/KKqMbQL?editors=1111) ie:
`1637884800000`

If on line 90 of the codepen example I remove `.getTime()` so that a unix stamp is returned then the charts fail. 

Can anyone confirm if the date value has to be a unix timestamp in Amcharts 5 or if I'm doing something silly (quite possible as i've been at this a while now) ? If it is the case that my api needs to return a unix timestamp now is there any suggestions on how to tackle that ? Thanks

P.S I have tried setting
`root.dateFormatter.set("dateFormat", "yyyy-MM-dd HH:mm:ss")`

**Comment by alienbuild** [comment]
I also just noticed that whilst inspecting the output markup in the codepen, and my own, there are 4 duplicate canvas elements, is that expected?

**Comment by alienbuild** [comment]
Solved by using the date parser documented here:

https://www.amcharts.com/docs/v5/concepts/data/#Parsing_dates

Will leave the issue open though just with regards to the multiple canvas elements.

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.
