### ISSUE TITLE
Using axis ranges to place labels at arbitrary values or dates

### ISSUE THREAD

**Issue by Triskae** [amcharts/amcharts5#540]
I everyone,

I'm trying to reproduce [this](https://www.amcharts.com/docs/v4/tutorials/using-axis-ranges-to-place-labels-at-arbitrary-values-or-dates/) tutorial from amchartsV4, but I was unable to find an equivalent for amcharts V5.

Someone can help me please ? The particular part I'm trying to reproduce is the range to only have the first and last value in the xAxis.

FYI, I'm using a DateAxis and I also use the micro theme.

Thanks a lot in advance,

Filipe

**Comment by franz-86** [comment]
Did you checked #521 ? There is a link to the amcharts5 docs in the replies

**Comment by martynasma** [comment]
As per @franz-86's comment, you should use axis ranges to place grid/labels at any value you need.
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/axis-ranges/

**Comment by Triskae** [comment]
Thanks a lot for your answers, I'll try your solutions !

**Comment by Triskae** [comment]
I succeded to display the label at a random location, the problem is that I think Micro theme hide some elements in the chart, because with Micro theme the label doesn't display, but without it does ...

**Comment by martynasma** [comment]
Yes, micro theme hides some elements. Here's it's code:
https://github.com/amcharts/amcharts5/blob/master/src/.internal/themes/MicrochartTheme.ts

You may need to explicitly set `visible: true` on some elements to override the theme.

**Comment by Triskae** [comment]
The microchart code really helped, thanks a lot !!
