### ISSUE TITLE
Setting a minWidth on Slices in Pie/Sunburst Charts for very small Slices

### ISSUE THREAD

**Issue by luii** [amcharts/amcharts5#542]
**Question**

I'm trying to set a `minimum Width` on all of my Slices in my Drill-Down Sun Burst chart, but for some reason it doesnt affect it wheter 10 nor 100. Is there such Option to restrict the Element from shrinking to much when the given Value is small? In fact so small that it is very hard to click on it.

**Environment (if applicable)**

- AMCharts 5: Version 5.2.15
- Browser: Firefox 103.0.2 (Non Nightly Build)
- Framework: Angular / Typescript

**Additional context**

**Comment by martynasma** [comment]
There's no way to set minimum size of a Sunburst slice, I'm afraid.

`minWidth` is a generic `Sprite` setting, which does not affect Sunburst as it is not managed by `width`/`height` but rather than `radius` setting.

**Comment by luii** [comment]
Okay, thank you for the quick answer, i think im going with hiding portions that are too small than.
