### ISSUE TITLE
unreliable tooltip on axisBullets

### ISSUE THREAD

**Issue by franz-86** [amcharts/amcharts5#545]
Dear All,

I created some Axis Bullets, positioned on the x-axis using the AxisRange feature.
Its sprite is a Container, containing a couple of shapes (a Circle and a Picture). 
On the Circle I set `tooltipText: "This is the tooltip"` but I got a weird behavior:
If the pointer goes over the bullets from below (without never touching or getting over the plot area) the tooltips show correctly. After passing through the plot with the cursor, however, the tooltip doesn't show anymore

**Comment by zeroin** [comment]
We could take a look, but we'll need a working codepen with exact situation.

**Comment by zeroin** [comment]
The best way to solve this would be to create a separate tooltip and set it for the bullets:
https://codepen.io/team/amcharts/pen/poLxXWm/e40b1ca7574d1f66f367ad88017e3771

**Comment by franz-86** [comment]
many many thanks!! Problem solved
