### ISSUE TITLE
StockChart Stock toolbar Series type control, not working properly when mainPanel having Multiple Charts.

### ISSUE THREAD

**Issue by mukeshbadgujar** [amcharts/amcharts5#548]
I have a mainPanel, i added multiple series in that, and i want to add series type control, but default functions are not working properly,
so i use custom method to get the series from the stockChart.

You have 
```
stockChart.get("stockSeries");
```
https://codepen.io/team/amcharts/pen/jOYJOeJ (reference)
but this only get the lastly added panel's chart.

so, i able to manage it by 
```
stockChart.children._container.panels._values[0].children._container.series._values[0]
```
for the multiple panels, and it worked.

but i want to ask you, is this the right way for doing it to change the series type, (also is this the right way to apply toolbar controls for multiple panels) 

see my code:
https://jsfiddle.net/mukeshbadgujar/w4zcL6xy/1/

**Comment by xorspark** [comment]
Generally speaking, you should never need to resort to using `_underscored` properties; not only are they private, there usually is a way to access them through the API.

`panels` and `series` are stored as list objects, so you can access and manipulate them using the standard [list methods](https://www.amcharts.com/docs/v5/reference/list/#Methods), allowing you to access each panel and their associated series using `each` and `getIndex` as needed.

I've cleaned up your setSeriesType method and also added code to update the valueLegends [here](https://jsfiddle.net/tu8ve1z3/4/) to illustrate this.

**Comment by mukeshbadgujar** [comment]
@xorspark Thank you for clearing my doubts, and your solution is working as needed.
