### ISSUE TITLE
Amchart 5 Line chart

### ISSUE THREAD

**Issue by ankit-mercer** [amcharts/amcharts5#549]
How can we enable the bullets on hover for line series in amchart5. I did this in previous version of amchart.

**Comment by xorspark** [comment]
Building on the [trigger bullet hover effects](https://www.amcharts.com/docs/v5/tutorials/triggering-bullet-hover-effects-with-chart-cursor/) sample, you can use the bullet's `default` and `hover` states to adjust the bullet's `fillOpacity` and `strokeOpacity` values to show/hide the bullet as needed. You'll also need to listen to the `cursorhidden` event to hide the bullets once the cursor is off the chart.

```
  series.bullets.push(function() {
    var circle = am5.Circle.new(root, {
      // ...
      strokeOpacity: 0,
      fillOpacity: 0
    });
    
    circle.states.create('default', {
      strokeOpacity: 0,
      fillOpacity: 0,
    });

    circle.states.create('hover', {
      strokeOpacity: 1,
      fillOpacity: 1,
    });
    // ...
  });

cursor.events.on("cursorhidden", cursorHidden);

function cursorHidden() {
  for(var i = 0; i < previousBulletSprites.length; i++) {
    previousBulletSprites[i].unhover();
  }
  previousBulletSprites = []; 
}
```

[Demo](https://codepen.io/team/amcharts/pen/QWmzgjQ/13824635f2799093eb48a72f08527824?editors=0010)
