### ISSUE TITLE
Setting column height by data item property in XY chart

### ISSUE THREAD

**Issue by senchden** [amcharts/amcharts5#550]
Hello.
I would like to know whether there is a way to set horizontal column height in a category based on a data item property.
I have tried using an adapter like
```javascript
series.columns.template.adapters.add("height", function(height, target) {... handler here...});
```
and callback was being called, but `target.dataItem` is `undefined`. If using another template property like "fill", data item is defined as expected.
I was using this example as a base: https://www.amcharts.com/demos/gantt-chart-dates/

Thank you in advance.

**Comment by martynasma** [comment]
Maybe try `templateField`?

```JavaScript
series.columns.template.setAll({
  templateField: "columnSettings"
});
```

More info:
https://www.amcharts.com/docs/v5/concepts/settings/template-fields/

**Comment by senchden** [comment]
Just tried it out and it seems to be working. Thanks. I wonder why the adapter wasn't working though...
Anyway, I'm marking the issue as closed.

**Comment by martynasma** [comment]
It's probably about the timing.

Column is created before data item is set. Setting data item does not dirty its height/width, so adapter is not called again.
