### ISSUE TITLE
is amcharts5 suppots Server Side Rendering?

### ISSUE THREAD

**Issue by mukeshbadgujar** [amcharts/amcharts5#552]
i dont want to show any data on client side browser inspect, for that server side rendering is needed.

**Comment by mukeshbadgujar** [comment]
I have Searched about it, but cant find exact what is needed.

can you give any example for that.

**Comment by martynasma** [comment]
The following tutorial is for amCharts 4, but the same principle would apply for amCharts 5, too.

https://www.amcharts.com/docs/v4/tutorials/automating-report-generation-using-selenium-webdriver/

Hope it helps.

**Comment by mukeshbadgujar** [comment]
thanks i will check this.
