### ISSUE TITLE
Amchart world map

### ISSUE THREAD

**Issue by RafikBoubaker** [amcharts/amcharts5#554]
i'm creating a project using the amcharts world map.
as you can see in this demo: https://www.amcharts.com/demos/selecting-multiple-areas-map/#code
we can select multiple countries (countries selected become active), can someone guide me here and tell me where i can find all the selected countries??? where are they stored ??(is their an array containing the countries names or their codes) ???

**Comment by xorspark** [comment]
There's no array of selected countries, so you'll have to maintain your own. You can monitor the polygon's `active` setting to add/remove it from the list:

```
let selectedPolygons = [];
polygonSeries.mapPolygons.template.on('active', (active, target) => {
  if (active) {
    selectedPolygons.push(target);
  }
  else {
    selectedPolygons = selectedPolygons.filter((polygon) => {
      return polygon !== target; 
    });
  }
});
```

**Comment by RafikBoubaker** [comment]
the problem is that i want to limit the number of active countries to only two in order to make a comparison using an external api in my angular project, so if the user click on a third countries i will either make all countries inactive / or make the first coutry i've clicked inactive and the third active instead (FIFO) is there any solution to achieve that ???



> There's no array of selected countries, so you'll have to maintain your own. You can monitor the polygon's `active` setting to add/remove it from the list:
> 
> ```
> let selectedPolygons = [];
> polygonSeries.mapPolygons.template.on('active', (active, target) => {
>   if (active) {
>     selectedPolygons.push(target);
>   }
>   else {
>     selectedPolygons = selectedPolygons.filter((polygon) => {
>       return polygon !== target; 
>     });
>   }
> });
> ```

**Comment by xorspark** [comment]
You can add a conditional to check if the array size is larger than two and then manipulate the countries' state and active flag that you want removed (either the first or all of them).

```
let selectedPolygons = [];
polygonSeries.mapPolygons.template.on('active', (active, target) => {
  if (active) {
    selectedPolygons.push(target);
    if (selectedPolygons.length > 2) {
      selectedPolygons[0].states.apply('default');
      selectedPolygons[0].set('active', false);
    }
  }
  else {
    selectedPolygons = selectedPolygons.filter((polygon) => {
      return polygon !== target; 
    });
  }
});
```

The event will fire again once active is set to false and it will get removed from the array in the else case.
