### ISSUE TITLE
Custom legends in Amchart 5

### ISSUE THREAD

**Issue by spiral2k** [amcharts/amcharts5#555]
Hey guys, I couldn't find any answers in the docs (v5) so I'm asking here.

I'm trying to render custom legends,
are there any methods that expose the ability to turn on/off series on the chart?

in the docs, I've found the '[external_container](https://www.amcharts.com/docs/v5/concepts/legend/#external-container)' section, but it's not helping me to achieve.

I'm searching for a solution similar to '[legendSelect](https://echarts.apache.org/en/api.html#action.legend.legendSelect)' of Echarts

thanks,
geart library!

**Comment by martynasma** [comment]
You can just do `series.hide()` or `series.show()` to hide or show it respectively.
