### ISSUE TITLE
get a map polygon by id without nodejs

### ISSUE THREAD

**Issue by SylvainArd** [amcharts/amcharts5#556]
Hello,
I am using amcharts 5 in a PHP application (so not nodejs). I want to get a map polygon by its id to change its color so I do :

var hex = parseInt(couleur.replace(/^#/, ''), 16);
am5.registry.entitiesById(code).set("fill",am5.color(hex));	

but I get the error :

Uncaught TypeError: am5.registry.entitiesById is not a function

and I can't do

import * as am5 from "@amcharts/amcharts5";

because it is a Typescript code

How to import the function am5.registry.entitiesById then or please give me another method to get the polygon by its id and changing its color ?

Thank you

Best regards

**Comment by martynasma** [comment]
`entitiesById` is an object, not a function.

The key is object id. You can do this:

```JavaScript
am5.registry.entitiesById[code].set("fill",am5.color(hex));
```

**Comment by SylvainArd** [comment]
I have now the message :
Uncaught TypeError: am5.registry.entitiesById[code] is undefined
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers


Le jeu. 18 août 2022 à 12:03, Martynas Majeris ***@***.***> a
écrit :

**Comment by SylvainArd** [comment]
in what file registry is defined please ?

**Comment by SylvainArd** [comment]
the id is "africa" for map "am5geodata_continentsHigh"

**Comment by martynasma** [comment]
If you need to get a polygon by its ID, better use `getDataItemById()` method onMapPolygonSeries:

```JavaScript
polygonSeries.getDataItemById("africa").get("mapPolygon")
```

**Comment by SylvainArd** [comment]
in my function :

polygonSeries.mapPolygons.template.events.on("click", function (ev) {
var data = ev.target.dataItem.dataContext;	var
couleur=getCouleur();	var code=data.id;	console.log(couleur+" :
"+code);	var hex = parseInt(couleur.replace(/^#/, ''),
16);	polygonSeries.getDataItemById(code).get("mapPolygon").set("fill",am5.color(hex));	$.ajax({	
 url: "ajax_enregistre_zone_couleur.php?carte=5&code="+code+"&couleur="+getCouleurId()	})});

it works but in the root of

am5.ready(function() {
(...)

// Create polygon seriesvar polygonSeries =
chart.series.push(am5map.MapPolygonSeries.new(root, {  geoJSON:
am5geodata_continentsHigh,  valueField: "value",  calculateAggregates:
true}));

(...)polygonSeries.getDataItemById("northAmerica").get("mapPolygon").set("fill",am5.color(0x000000));polygonSeries.getDataItemById("oceania").get("mapPolygon").set("fill",am5.color(0x000000));polygonSeries.getDataItemById("antarctica").get("mapPolygon").set("fill",am5.color(0x000000));polygonSeries.getDataItemById("southAmerica").get("mapPolygon").set("fill",am5.color(0x000000));polygonSeries.getDataItemById("europe").get("mapPolygon").set("fill",am5.color(0x000000));polygonSeries.getDataItemById("africa").get("mapPolygon").set("fill",am5.color(0x000000));polygonSeries.getDataItemById("asia").get("mapPolygon").set("fill",am5.color(0x000000));

I have the message :
Uncaught TypeError: polygonSeries.getDataItemById(...) is undefined
please help me !
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers


Le jeu. 18 août 2022 à 12:55, Martynas Majeris ***@***.***> a
écrit :

**Comment by SylvainArd** [comment]
I have changed the code to :

polygonSeries.mapPolygons.template.events.on("appeared", function (ev) {
polygonSeries.getDataItemById("northAmerica").get("mapPolygon").set("fill",am5.color(0x000000));polygonSeries.getDataItemById("oceania").get("mapPolygon").set("fill",am5.color(0x000000));polygonSeries.getDataItemById("antarctica").get("mapPolygon").set("fill",am5.color(0x000000));polygonSeries.getDataItemById("southAmerica").get("mapPolygon").set("fill",am5.color(0x000000));polygonSeries.getDataItemById("europe").get("mapPolygon").set("fill",am5.color(0x000000));polygonSeries.getDataItemById("africa").get("mapPolygon").set("fill",am5.color(0x000000));polygonSeries.getDataItemById("asia").get("mapPolygon").set("fill",am5.color(0xff00ff));
});

I have no error but the polygons are not colored

Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers

**Comment by SylvainArd** [comment]
I finally succeed by :

polygonSeries.events.on("geodataprocessed", function (ev) {

Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers
