### ISSUE TITLE
Change the position of tooltip in a pie chart

### ISSUE THREAD

**Issue by marcelog5** [amcharts/amcharts5#558]
Hello,
I am using amcharts 5 in a react application. I want to know if is there a way to change the position of a tooltip in a pie chart.

The tooltip that I'm using it's like a donut chart, but always that I try to change the position using tooltipX or tooltipY the tooltip remains in the middle of the chart.

I already tried the pointerOrientation but the tooltip remain in the middle as the same.

Is that a way that I can movie the tooltip in a donut chart?

**Comment by martynasma** [comment]
Normally, tooltip would display in the middle of the slice.

Where would you like to move it to?
