### ISSUE TITLE
Seems lighten & saturate methods doesn't works as expected

### ISSUE THREAD

**Issue by jdim** [amcharts/amcharts5#559]
**Bug description**

Hello, seems `Color`s lighten & saturate static methods return strange random colors or transparent or black

Example (look for a line `series.columns.template.adapters.add("fill")`):
https://codepen.io/dm-khabarov/pen/RwMvWGa?editors=0010

**Environment (if applicable)**

 - amCharts 5

Thanks

**Comment by martynasma** [comment]
The value parameter to those functions is expecting a number less than 1.

E.g. using `lighten` with -0.5 will make the color darker by 50%. Using values like -70 does not make a lot of sense.

**Comment by jdim** [comment]
Seems the problem is with Color.saturate method.

For example, the desaturation of color #67D908 to 0.5 (i.e. `am5.Color.saturate(fill, -0.5);`) should return #6ca53c.

The `am5.Color.saturate(fill, 0.5);` returns desaturated color, but should saturate it.

Online tool for check:
https://mdigi.tools/desaturate-color/#67d908
https://mdigi.tools/saturate-color/#67d908

Modified example:
https://codepen.io/dm-khabarov/pen/RwMvWGa

![Screenshot 2022-08-24 at 12 45 02](https://user-images.githubusercontent.com/8625641/186387216-066b9b1c-be9f-430b-bfc9-0e8961197324.png)

**Comment by martynasma** [comment]
Turns out we had an error in our class reference. `saturate()` method accepts saturation parameter in range of 0 to 1, with 0 being fully desaturated.

We're fixing docs as we speak.
