### ISSUE TITLE
Why Series Type Control is Not Working in Incremental Stock Chart?

### ISSUE THREAD

**Issue by mukeshbadgujar** [amcharts/amcharts5#565]
Please check the code, 
i have checked it many time but cant find why Series Type is not changing properly.

https://jsfiddle.net/mukeshbadgujar/y6hanbuz/69/

please let me know the problem.

**Comment by martynasma** [comment]
It does work for me. But it looks like you are using same value for open and close.

Perhaps you are not setting relative fields in series settings, or your data has incorrect values.

I hope you'll be able to find the issue.

**Comment by mukeshbadgujar** [comment]
Ok, Thanks for quick reply, i will check

**Comment by mukeshbadgujar** [comment]
yes it is working... thanks
