### ISSUE TITLE
How to listen for StockToolbar events and refetch data?

### ISSUE THREAD

**Issue by rodgeTech** [amcharts/amcharts5#567]
Hello,

Awesome library. I'm trying to figure out how to listen for events on the stock toolbar controls and refetch the chart data accordingly. For example, if I select 1M or 5D using the period selector or select a new date range, how can I listen for this event so that I can refetch, potentially missing, data from my backend, and then update the chart data with the new data?  

I know there's the `net.load` utility but I'm not sure if this is the right way to do it as I have a graphql api.

Many thanks

**Comment by martynasma** [comment]
`net.load()` utility is helpful to load external data, but if you have any other means you are already using, that will work, too.

It's probably best to monitor `selectionMin` and `selectionMax` private settings on the axis:

```JavaScript
function handleZoom(ev) {
  // do your thing
  // ...
}

xAxis.onPrivate("selectionMin", handleZoom);
xAxis.onPrivate("selectionMax", handleZoom);
```

`DateRangeSelector` or `PeriodSelector` do not have own events.

**Comment by rodgeTech** [comment]
I see, thanks for the reply, I'll give that a try...

So while it seems it's not possible to do this with the `DateRangeSelector` or `DateRangeSelector`, I did come across an example of on-demand data loading: https://www.amcharts.com/demos/on-demand-data-loading/

This could be an alternative as well? Be it that I will have to drop the `DateRangeSelector` and `DateRangeSelector` entirely and create my own components for these.
