### ISSUE TITLE
In Incremental Data Loading Chart, Problem after changed the Series Type

### ISSUE THREAD

**Issue by mukeshbadgujar** [amcharts/amcharts5#568]
I have a chart with ondemand incremental data, also compare series included, and series type control.

my code:
https://jsfiddle.net/mukeshbadgujar/kx0stan1/

Steps for the issue:
1. Add any Compare Series (zoom in and zoom out the chart to see the added comparing series on proper position)
2. till you can zoom out to load incremental data.
3. now, change the series type to any.
4. now zoom out to load incremental data
5. you will see it is not working. (because the start and end data is getting same, i dont know why?)

please check.

**Comment by martynasma** [comment]
This is a quite an elaborate setup and reproduction process. I'm afraid we won't be able to look into it unless you distill the issue, e.g. find a way to reliably reproduce it in an initial setup.

Or if you have an amPlus service subscription, please reach out to us directly at contact@amcharts.com

**Comment by mukeshbadgujar** [comment]
thanks for reply.

Solved the problem...
