### ISSUE TITLE
XY chart axis range for series's segments doesn't work as expected

### ISSUE THREAD

**Issue by jdim** [amcharts/amcharts5#569]
**Question**

Hello, I have ColumnSeries and GaplessDateAxis on X.
My range starts before date of the first item and ends after last. All columns must have the style of range, but they don't.

If I'm changing the class of X axis to DateAxis it works.

My CodePen example(the source example from demo): 
https://codepen.io/dm-khabarov/pen/VwXNyyK

**Environment (if applicable)**

 - amCharts 5
 - Browser Google Chrome 104.0.5112.101

**Comment by zeroin** [comment]
You should use dates which are the same or really close to min/max dates of your data:
https://codepen.io/team/amcharts/pen/ExEJQXZ

**Comment by jdim** [comment]
What if chart was initially created and data items were with dates which are close to axis range. But later we load another data list, with future dates far from axis range.
Do I need to create chart object again if my new data list doesn't close to min/max dates of range?

**Comment by zeroin** [comment]
You can simply monitor private min and max of the axis and update value and end value of the rangeDataItem:
https://codepen.io/team/amcharts/pen/zYWXmvr
