### ISSUE TITLE
Word cloud ignores settings

### ISSUE THREAD

**Issue by andrei-at-work** [amcharts/amcharts5#570]
- When populated with series data, word cloud ignores settings (e.g. excludeWords, maxCount, minValue, etc...)
- When populated with text, it works as expected

**Comment by martynasma** [comment]
> When populated with series data, word cloud ignores settings (e.g. excludeWords, maxCount, minValue, etc...)

This is by design.

Those settings are for the text parser. The chart expects data to be exactly what you need it to be, that is pre-filtered.
