### ISSUE TITLE
Saint Kitts and Nevile is marked in countries2 as being part of Asia

### ISSUE THREAD

**Issue by andreipradan** [amcharts/amcharts5#571]
**Bug description**

Saint Kitts and Nevile is marked in countries2 as being part of Asia
in here: https://github.com/amcharts/amcharts5/blob/master/src/geodata/data/countries2.ts#L738-L739

**Additional context**
It should actually be part of North America

Probably the Asia geometry from continentsLow includes it too because when I use `zoomToDataItem` on a series with am5geodata_continentsLow it includes it

**Comment by martynasma** [comment]
Good catch. We'll include the change in the next update of geodata package.

Please note that it is in a separate release schedule than the main amCharts 5 package.

**Comment by andreipradan** [comment]
Thank you, and great job on these packages, they're awesome!
I'm not a frontend dev, but if you need any help I can try and give it a go at a PR for fixing this.

**Comment by martynasma** [comment]
Thanks for the offer. We can't accept PRs in this repo - it's not used for development.

**Comment by martynasma** [comment]
Heads up, 5.0.5 fixes the issue.
