### ISSUE TITLE
Stock chart data aggregation

### ISSUE THREAD

**Issue by itsnia232** [amcharts/amcharts5#572]
I setup using a basic line chart using 'value' and 'date' and i now want to convert to a stock chart with candles. Is it possible to do the data manipulation using the processors in amcharts 5 ? Or will I need to completely rewrite my database and backend to get the additional things I need like open, close, high, low etc ?

Thanks

**Comment by zeroin** [comment]
I am afraid no, but I'd say you can do this with some JavaScript methods after loading your data, no need to change database and backend.
