### ISSUE TITLE
Amcharts 5 Map. get current position of map.

### ISSUE THREAD

**Issue by lasivtech** [amcharts/amcharts5#573]
Is there any way to get current position of map. (exact lat,lon,zoom). and restore it?

**Comment by zeroin** [comment]
Sure - you should save zoomLevel and geoPoint of map center and then call `map.zoomToGeoPoint` method to restore it.

To save:
```
var geoPoint = chart.invert({x:chart.width() / 2, y:chart.height() / 2})
var   zoomLevel = chart.get("zoomLevel", 1);
```

To restore:
```
chart.zoomToGeoPoint(geoPoint, zoomLevel, true);
```
Working codepen:
https://codepen.io/team/amcharts/pen/mdxYdMZ

**Comment by lasivtech** [comment]
> Sure - you should save zoomLevel and geoPoint of map center and then call `map.zoomToGeoPoint` method to restore it.
> 
> To save:
> 
> ```
> var geoPoint = chart.invert({x:chart.width() / 2, y:chart.height() / 2})
> var   zoomLevel = chart.get("zoomLevel", 1);
> ```
> 
> To restore:
> 
> ```
> chart.zoomToGeoPoint(geoPoint, zoomLevel, true);
> ```
> 
> Working codepen: https://codepen.io/team/amcharts/pen/mdxYdMZ

WOW!.. that works great!.  Thank you :)

**Comment by martynasma** [comment]
BTW, we're adding a `MapChart` method `geoPoint()` which will return current center coordinates.
