### ISSUE TITLE
amCharts license - github docs vs website license page

### ISSUE THREAD

**Issue by mkdudeja** [amcharts/amcharts5#574]
Hi Team,

Looking forward to your response on below query:

Use Case:  Website hosted in private network

License docs (https://github.com/amcharts/amcharts5/blob/master/packages/shared/LICENSE) says, amChart5 can be used without acquiring commercial license given the condition are met as stated in the doc above.

However, website license page(https://www.amcharts.com/online-store/), doesn't mention anything about free usage.

Really confused if i should try the package.

Also, would like to know if amChart5 usage is permitted only with the license, does that hold true for amChart4 as well ,or, amChart4 can be used without acquiring commercial lincense.

Waiting for your response!

Thanks,
Manish Kumar

**Comment by martynasma** [comment]
You can use publicly available amCharts 5 and 4 for free as per the LICENSE file available in GitHub.

It's fully functional, can be used in any project, but displays a small amCharts logo.

If you need unbranded version, you need a commercial license as per Online Store you linked to.

It's best to start with the free version, see if it works for you as expected, then acquire a commercial license to remove the branding.

Hope that makes sense.

**Comment by mkdudeja** [comment]
Thanks for the quick response!

Since, ours is the internal application only, branding works for us. We'll keep it as-is.

Thanks
