### ISSUE TITLE
Amchart stockchart

### ISSUE THREAD

**Issue by ankit-mercer** [amcharts/amcharts5#575]
Is there anyway by which we can hide the legends for first series in amchart.
https://www.amcharts.com/demos/stock-chart-comparing-prices

**Comment by zeroin** [comment]
You only add items to the legend you want to be there. This adds both valueSeries and volume series:

`valueLegend.data.setAll([valueSeries, volumeSeries]);`

this will add only volume series:

`valueLegend.data.setAll([volumeSeries]);`
