### ISSUE TITLE
Documentation Error: link to ListData class reference

### ISSUE THREAD

**Issue by jkrk678** [amcharts/amcharts5#577]
The href in the last sentence of [this section](https://www.amcharts.com/docs/v5/concepts/data/#The_data_object) is incorrect.

It is https://www.amcharts.com/docs/v5/reference/datalist/#Methods, but should be https://www.amcharts.com/docs/v5/reference/listdata/#Methods.

**Comment by martynasma** [comment]
Thanks for the heads up! Fixed.
