### ISSUE TITLE
Issue with DateRangeSelector showing incorrect Dates in calendar

### ISSUE THREAD

**Issue by rodgeTech** [amcharts/amcharts5#582]
Hi,

I've noticed something with the date range selector that I think is an issue but please correct me if I'm wrong in the case that it's actually the expected behavior.

This issue is as follows:

1. Let's say I select the following date range: 2022-08-21 - 2022-08-24
2. After hitting apply the range label show the correct range
3. Opening up the range selector dropdown again will also reveal the correct labels for the From (2022-08-21 ) and To dates (2022-08-24)
4. However,  the issue is that the From and To dates appear to be incorrect in the Calendars

You can see a depiction of this here:

<img width="476" alt="Screen Shot 2022-08-26 at 10 54 36 PM" src="https://user-images.githubusercontent.com/10326733/187015777-2ae1367a-ec80-40c2-9ab9-182d29e5c585.png">

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

I tried something similar on our demos and could not trigger a mismatch between input fields and the calendar pickers.

**Comment by rodgeTech** [comment]
Sure, you can find the chart here, it's also using the exact same dataset that I'm using:

https://codepen.io/rodgeTech/pen/vYRoNWa

You'll notice immediately when you open the range selector that the start date is off by 1 day. Selecting a range will then cause the aforementioned issue.

Many thanks!

**Comment by martynasma** [comment]
Thanks. It looks good to me tho:

![image](https://user-images.githubusercontent.com/1458520/187382381-21d7a3fd-6b7d-4eac-b8c0-0c4f92d90f1b.png)

Could be a timezone thing. Which timezone are you on?
