### ISSUE TITLE
Amcharts 5 Stock Candle is flashing

### ISSUE THREAD

**Issue by itsnia232** [amcharts/amcharts5#583]
Are there any known or common issues where the candlestick chart (using react) is flashing on and off ? 

The data is only being loaded and updated once on load which I've confirmed with a console log on that event. 
I've also ruled out CSS by putting it in its own full screen fixed div. 
I've also stripped it down to just use the one main panel incase the scroll bar or volume was causing any issues.

I'm not entirely sure what else could be the issue ?

Any pointers appreciated

**Comment by itsnia232** [comment]
Just for reference if i use the amcharts 5 demo data and CSVParser instead of my own data and the JSONParser it works fine without flashing

**Comment by zeroin** [comment]
If you could create a codepen with this issue reproduced, we could take a look.

**Comment by zeroin** [comment]
My guess is that your data is not sorted in ascending order.
