### ISSUE TITLE
Having issue with Stock Legend, Can't Close added Series.

### ISSUE THREAD

**Issue by mukeshbadgujar** [amcharts/amcharts5#584]
This is not a bug or error,
many times when the data is loaded on chart, the OHLC values are changes according to cursor.
and this makes to move the position on the Buttons on Stock Legend. so sometimes i cant able to click on button,
because the cursor continuously changes the values of OHLC on legends. 

Please let me know how to fix this.
## Please Check the Video
https://user-images.githubusercontent.com/32473209/187027857-bc897aa5-670e-4ea7-8252-4f5335e07701.mp4

**Comment by zeroin** [comment]
To prevent wrapping you can set layout of a legend to HorizontalLayout:

`legend.set("layout", root.horizontalLayout)`

if you need wrapping, then I could suggest to set some minWidth for the valueLabels of a legend:
`valueLegend.valueLabels.template.set("minWidth", 100)` this way the size of a legend item will not change.

**Comment by mukeshbadgujar** [comment]
I have added `legend.set("layout", root.horizontalLayout)` but it makes problem if i added more series. (they are plot on right side)
![Screenshot from 2022-08-29 16-58-16](https://user-images.githubusercontent.com/32473209/187191375-41a36a3f-be73-4f10-8939-e01807eea054.png)

Also i added `valueLegend.valueLabels.template.set("minWidth", 100)` but it will not do any thing other-than making unwanted  extra space
![Screenshot from 2022-08-29 17-01-29](https://user-images.githubusercontent.com/32473209/187191790-9a7b936f-4054-441d-b878-76cac11048de.png)

please provide proper solution.

**Comment by zeroin** [comment]
Hi,

Another solution which I could suggest to try would be to set minWidth on itemContainers:

`legend.itemContainers.template.set("minWidth", 200)` 200 should be the approximate size of your legend item, with values displayed. This, however will make gaps between legend items, but I don't see another way to solve this.

**Comment by mukeshbadgujar** [comment]
`legend.itemContainers.template.set("minWidth", 200)`
this is also working similar to `valueLegend.valueLabels.template.set("minWidth", 100)` still same problem.

cant able to close series.

Please provide proper way to do it, or make something to colse series by

**Comment by martynasma** [comment]
Hold on. We're going to work on some kind of better solution.

**Comment by zeroin** [comment]
The only reliable solution which I could think of was to hide cursor and axis tooltips when hovering legend items. Here is the code which does the thing:

https://codepen.io/team/amcharts/pen/dyeypKg/50c8a5ae9370919ca6424fcdcf9533f1

I check how yahoo does it, so they simply do not wrap legend items at all, so the ones out of the screen remain not visible.

An alternative could be to use vertical layout, meaning you will have a single column for all legend items.

**Comment by mukeshbadgujar** [comment]
> hide cursor and axis tooltips when hovering legend items

yes, i think this should be best solution for now.
