### ISSUE TITLE
How to Hide Licence Key in JavaScript?

### ISSUE THREAD

**Issue by dvinci-klfr** [amcharts/amcharts5#589]
I have the same concerns as  in https://github.com/amcharts/amcharts5/issues/482. How that got resolved? No security through obscurity plz :)

**Comment by mukeshbadgujar** [comment]
> I have the same concerns as  in https://github.com/amcharts/amcharts5/issues/482. How that got resolved? No security through obscurity plz :)

You can encrypt your whole js code (you will find solutions for it on internet) or just encrypt the one line of your licence key and put in your code where it is not noticeable.

I am saying this because, in js there is no security to hide keys.

**Comment by dvinci-klfr** [comment]
The question is, do I have to do this? Is this an requirement of Amchart? Is Amchart is suing my company if some of our user is `stealing` the key and I was not `obfuscating` it propperly?

**Comment by martynasma** [comment]
@dvinci-klfr Relax. amCharts is not suing anyone :)

I understand license-related issues are pretty sensitive. You can reach out to us directly at contact@amcharts.com should you wish to discuss this further.

P.S. closing this.
