### ISSUE TITLE
Tooltips staying after clear

### ISSUE THREAD

**Issue by t-legrand** [amcharts/amcharts5#593]
### **Context**

I'm using amchart5 on a Symfony project. I have 5 charts on the same page (1 clustered column chart, 3 pie charts & 1 line graph), all using axios to reload their data after submitting a form. Functions reloading charts have root(s) and form as argument.

**Bug description**
Only one of them (the line graph) is part of the bug. After getting the data with my ajax request, I clear previous data with root.container.children.clear(); and then do the whole code (as in the demo source of the amcharts website) except defining the root (I always keep the same). Everything is fine for the first 4 but for the line graph (also tried with a Column with Rotated Labels) **the tooltips of the previous chart still appears**. So each time I submit the form, one tooltip is added but the ancients one are staying, making the chart unreadable.

![Screenshot from 2022-09-01 15-57-01](https://user-images.githubusercontent.com/71838343/187944080-aa83d640-611c-4b1e-8e19-7e10e8a34b92.png)

### **Environment**

 - amCharts 5
 - Tested on Chromium & Firefox
 - Symfony -> TypeScript

### **Additional context**

Found some guy with the same problem on SO [here](https://stackoverflow.com/questions/73391014/amcharts-5-legend-stays-when-chart-is-deleted)

**Comment by martynasma** [comment]
Have you tried disposing the charts instead of just clearing root container's children?

**Comment by t-legrand** [comment]
I managed to do it with a root.dispose() by following [this example](https://www.amcharts.com/docs/v5/getting-started/root-element/#disposing).

Thank you for your help.
I would still like to understand why is my solution working for my first 4 charts and not for the last one. Isnt't clear() supposed to be used in this case to avoid re-definition of my roots each update ?

**Comment by martynasma** [comment]
I'm not entirely sure TBH. If you could produce some kind of runnable demo, we could take a look.

**Comment by AzuraGit** [comment]
Here's a runnable demo of what my code was doing before I fixed it : [CodePen](https://codepen.io/leevanox/pen/qBYBQPZ?editors=0010)

**Comment by t-legrand** [comment]
Here's a demo of what my code was doing before the fix : [CodePen ](https://codepen.io/leevanox/pen/qBYBQPZ?editors=1010)

**Comment by t-legrand** [comment]
Here's a demo of what my code was doing before the fix : [CodePen](https://codepen.io/leevanox/pen/qBYBQPZ?editors=1010)

**Comment by martynasma** [comment]
Thanks. OK, so running `clear()` on `root.container.children` just removes those children, but does not dispose them.

This is definitely not a way to go, unless you are disposing those charts separately.

It means that charts remain active, albeit without parent, which means they may still react to user interactions, and/or influence tooltip display.

**Comment by t-legrand** [comment]
Thanks for your help, I used `dispose()` on every chart of my project now, should be good !

**Comment by t-legrand** [comment]
Thanks for your help, I used `dispose()` on every chart of my project, should be good !
