### ISSUE TITLE
Drag and drop in Stacked Bar Chart

### ISSUE THREAD

**Issue by ankit-mercer** [amcharts/amcharts5#594]
Hi Team,

I am trying to add drag and drop feature in stacked bar chart but when I try to drag and drop a bar it drops at random location in between the other bars, also after repeating few times it hides the random bar and remove data from that bar.

**Comment by martynasma** [comment]
I'm afraid drag-ordering of the columns is not a standard feature of amCharts, so can't provide any insights into that. Sorry.
