### ISSUE TITLE
Label treemap auto color 

### ISSUE THREAD

**Issue by justine-mlss** [amcharts/amcharts5#595]
Hello,

In this demoo : [https://www.amcharts.com/demos/drill-down-treemap](https://www.amcharts.com/demos/drill-down-treemap/), especially datas of mercedes, I notice that the color of the labels does not seem to be automatically adjusted with respect to the background color. In this case, it would be more appropriate if the labels were in black. Is there a way to get this adjustment?

![mercedes](https://user-images.githubusercontent.com/66368359/188103597-c6d52bc7-8445-4df1-946f-3142d4dbe2b3.png)

I took this example but I've the same issue in my project

Thanks

**Comment by martynasma** [comment]
It can be achieved with an adapter:

```JavaScript
series.labels.template.adapters.add("fill", function(fill, target) {
  if (target.dataItem) {
    var bgcolor = target.dataItem.get("rectangle").get("fill");
    return am5.Color.alternative(bgcolor, am5.color(0x000000), am5.color(0xffffff))
    
  }
  return fill;
});
```

https://codepen.io/team/amcharts/pen/mdLdRoL

**Comment by justine-mlss** [comment]
it works, thank you :)
