### ISSUE TITLE
Multiple children color treemap

### ISSUE THREAD

**Issue by justine-mlss** [amcharts/amcharts5#596]
Hello,

Is there a way in amcharts5 to set multiple color of treemap children ?
Like this in amcharts4 [https://github.com/amcharts/amcharts4/issues/1484](https://github.com/amcharts/amcharts4/issues/1484) ? 

Thank you

**Comment by martynasma** [comment]
This can be achieved using an adapter:

```JavaScript
series.rectangles.template.adapters.add("fill", function(fill, target) {
  var customColor = target.dataItem.dataContext.color;
  return customColor || fill;
});
```

**Comment by justine-mlss** [comment]
Thanks !!
