### ISSUE TITLE
geoJSON type error

### ISSUE THREAD

**Issue by okram2k** [amcharts/amcharts5#6]
When creating a map using amcharts5-geodata there is a type error when assigning it to geoJSON value (even when following the example shown in the documentation) 

`Type 'FeatureCollection' is not assignable to type 'GeoJSON | undefined'.
  Type 'FeatureCollection' is not assignable to type 'FeatureCollection<Geometry, GeoJsonProperties>'.
    Types of property 'features' are incompatible.
      Type 'Feature[]' is not assignable to type 'Feature<Geometry, GeoJsonProperties>[]'.
        Type 'Feature' is not assignable to type 'Feature<Geometry, GeoJsonProperties>'.
          Types of property 'geometry' are incompatible.
            Type 'Polygon | MultiPolygon | MultiLineString | null' is not assignable to type 'Geometry'.
              Type 'null' is not assignable to type 'Geometry'.ts(2322)
MapSeries.d.ts(13, 5): The expected type comes from property 'geoJSON' which is declared here on type 'IMapPolygonSeriesSettings'`

using //@ts-ignore above the type error and the map works perfectly fine. However something that should be addressed in the future for sure.

**Comment by martynasma** [comment]
We've just released a new version both geodata and main package. Try updating and let us know if the issue persists.
