### ISSUE TITLE
Treemap DrillDown change children color 

### ISSUE THREAD

**Issue by justine-mlss** [amcharts/amcharts5#600]
Hello,

I've a question about Treemap : I have a drill down treemap and I want to set another color of children. But it doesn't work. 
When I drill down, children have the same color as parent.

Can you help me about this issue ?  

Here a testing code :  https://codepen.io/Justinemlss/pen/gOzbzPK

Thank you

**Comment by martynasma** [comment]
Duplicate of: #596
