### ISSUE TITLE
Applying heat rules to chord node bullets

### ISSUE THREAD

**Issue by bisejdiu** [amcharts/amcharts5#601]
I have created a  `ChordNonRibbon` chart using the provided [demo](https://www.amcharts.com/demos/non-ribbon-chord-diagram/) as a starting point. 

Now I would like to add a heat rule to the node bullets, but I cannot figure out how to get it to work. I understand that `bullets` have specific requirements when it comes to applying heat rules as outlined [here](https://www.amcharts.com/docs/v5/concepts/settings/heat-rules/#bullets), and I have been testing using the provided example code, but without success. 

A minimal example showing this is available here: https://jsfiddle.net/besiani/cykxm5sf/62/ 
I'd appreciate some pointers to help guide me in the right direction!

**Comment by zeroin** [comment]
I am afraid heat rules will not work on flow charts, they are different. As a solution I could offer to create an adapter. Here is a demo: https://jsfiddle.net/q83vLmc9/

**Comment by bisejdiu** [comment]
Works like a charm! Thank you so much! I will also try to get more familiar with the `adapter` feature.
