### ISSUE TITLE
Stock chart close first series

### ISSUE THREAD

**Issue by ankit-mercer** [amcharts/amcharts5#603]
I was wondering if you could add an option where user can change the base comparator as it is useful. This feature was available in previous version as it allows to set an base comparator of their own choice.

**Comment by ankit-mercer** [comment]
When can we except this feature to be added.

**Comment by martynasma** [comment]
We've just updated this demo:
https://www.amcharts.com/demos/stock-chart-comparing-prices/

It now uses generic controls to add switching of the main series.

Please note that you will need to update to the latest amCharts 5 (5.2.21) for it to fully work properly.
