### ISSUE TITLE
How to set scrollbar thumb hover color?

### ISSUE THREAD

**Issue by nothing-personal-gh** [amcharts/amcharts5#604]
I would like to set a custom color for the thumb area of the scrollbar. 

This is my code - https://codepen.io/trooper-isa/pen/NWMqwga?editors=0010

 - I tried what's explained in this existing issue - https://github.com/amcharts/amcharts5/issues/534 and it didn't work for me. See lines 115 to 112 in my code above.
 - I tried using the theme (https://www.amcharts.com/docs/v5/concepts/themes/creating-themes/#scrollbar) as well but no effect. See lines 21 to 25 in my code above.

The hover color is still grey. I want it to be red as well. I am okay with either the theme option or setting the color directly.

<img width="535" alt="image" src="https://user-images.githubusercontent.com/111722528/188582175-2cc548b3-110c-459b-b0e5-e7af71658a48.png">

 - amCharts version - v5
 - Browser and its version - Chrome latest

**Comment by martynasma** [comment]
Probably easier to modify existing "hover" state:

```JavaScript
scrollbarX.thumb.states.lookup("hover").setAll({
  fill: am5.color(0xff0000),
  opacity: 1
});
```

With creating a new one, you end up with two hover states: one native and one custom. There's no guarantee yours will be applied last.

**Comment by nothing-personal-gh** [comment]
@martynasma 

That code throws this error:

<img width="949" alt="image" src="https://user-images.githubusercontent.com/111722528/188641533-c364e20c-ecbe-4a5b-9faa-91c561831f62.png">

Updated codepen - https://codepen.io/trooper-isa/pen/NWMqwga?editors=0010

**Comment by martynasma** [comment]
Right. Themes are applied when an element gains parent. And it does not happen until next frame after you set `scrollbarX` of the chart.

That's why your custom theme is applied before default one.

An easiest, albeit a bit hacky workaround would be to force a parent for the scrollbar before you run the theme lookup code:

```JavaScript
const scrollbarX = am5.Scrollbar.new(root, {
  marginTop: 20,
  orientation: "horizontal"
});

chart.topAxesContainer.children.push(scrollbarX);

scrollbarX.thumb.setAll({
  fill: am5.color(0xff0000)
});
scrollbarX.thumb.states.lookup("hover").setAll({
  fill: am5.color(0xffff00),
  opacity: 1
});
scrollbarX.thumb.states.create("down", {
  fill: am5.color(0xff0000)
});
```

BTW, you can't use strings like `"red"` in place where an object of type `Color` should go. It works to some extent, but in some cases will fail.

Proper syntax for red is `am5.color(0xff0000)`.

**Comment by nothing-personal-gh** [comment]
@martynasma Gotcha. I got that working now. I am now trying to set the same colouring for the grip buttons as well.

I have this code (lines 123 and 124 in my codepen):

```
console.log(scrollbar.startGrip.get("background").states);
console.log(scrollbar.startGrip.get("background").states.lookup("hover"));
```

The first log prints the states including 'hover'. So I would expect I can lookup hover state. But the 2nd log prints undefined:

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/111722528/189312918-393628af-0d47-4387-a4a6-7aff70a760e7.png">

Updated codepen: https://codepen.io/trooper-isa/pen/NWMqwga?editors=0010

So how do I set the hover background color and down background color for `startGrip` and `endGrip` buttons.

**Comment by martynasma** [comment]
I'm starting to think that you'd be better off adding that stuff to a custom theme, you seem to already have in your code:

```JavaScript
class MyTheme extends am5.Theme {
  setupDefaultRules() {
    
    this.rule("RoundedRectangle", ["scrollbar", "thumb"]).setAll({
      fill: am5.color(0xff8888)
    });
    
    this.rule("RoundedRectangle", ["scrollbar", "thumb"]).states.create("hover", {
      fill: am5.color(0xff0000)
    });
    
    this.rule("RoundedRectangle", ["scrollbar", "button", "background"]).setAll({
      fill: am5.color(0xff8888)
    });
    
    this.rule("RoundedRectangle", ["scrollbar", "button", "background"]).states.create("hover", {
      fill: am5.color(0xff0000)
    });

  }
}

const customTheme = MyTheme.new(root, {});

root.setThemes([
  am5themes_Animated.new(root),
  customTheme
]);
```

https://codepen.io/team/amcharts/pen/gOzMdrp/c6d7bae4cbadf0724ef334bfb7949704?editors=0010
