### ISSUE TITLE
cursorOverStyle option doesn't work for Button

### ISSUE THREAD

**Issue by OLLanhNguyen** [amcharts/amcharts5#605]
Following the tutorial https://www.amcharts.com/docs/v5/concepts/common-elements/buttons/#In_line_image
but look like the cursorOverStyle option doesn't work on Chrome.
Tested with the example:
https://codepen.io/team/amcharts/pen/qBXQzmq
![image](https://user-images.githubusercontent.com/112942173/188609276-2f1d471f-0465-4120-93aa-ba539fc777fe.png)

**Comment by martynasma** [comment]
The icon in a button is not an interactive element. The button itself is.

So you need to set `cursorOverStyle: "pointer"` in button's settings, not the icon:

```JavaScript
var button = chart.plotContainer.children.push(am5.Button.new(root, {
  dx: 10,
  dy: 10,
  layer: 40,
  cursorOverStyle: "pointer",
  icon: am5.Picture.new(root, {
    width: 32,
    height: 32,
    src: "data:image/svg+xml;base64,.........",
  })
}));
```
