### ISSUE TITLE
Axes Tooltip width

### ISSUE THREAD

**Issue by ankit-mercer** [amcharts/amcharts5#607]
Hello,

I am trying to show a very long text on hovering axis label but due to the length of the tooltip label text it goes outside the chart, I tried applying width to the tooltip but it does not work. I have also tried the method in which we fix width for the series tooltip but that too did not worked in axes label case.

Is there any way through which we can fix the width and apply oversizedBehavior: "wrap" to the tooltip of axis labels, so that long text breaks to the new line if it goes beyond the given width of tooltip.

Attached is the screenshot for your perusal. 

![image](https://user-images.githubusercontent.com/96469108/188679323-fb26598c-3e60-4295-b852-493114ba6bf4.png)

**Comment by martynasma** [comment]
Try setting `maxWidth` instead of `width`.

**Comment by ankit-mercer** [comment]
I tried maxWidth too but it did not worked. Below is the code I'm using for axis label tooltip.

var yRenderer = am5xy.AxisRendererY.new(root, {
            minGridDistance: 30,
            strokeOpacity: 0.2,
            strokeWidth: 1,
            fill: am5.color(0x002c77)
        });
        var yAxis = chart.yAxes.push(am5xy.CategoryAxis.new(root, {
            maxDeviation: 0,
            categoryField: "skillname",
            renderer: yRenderer
        }));        

        yAxis.labelsContainer.set("tooltip", am5.Tooltip.new(root, {
            pointerOrientation: "left",
            maxWidth: 200,
            oversizedBehavior: "wrap"
        }));
        
        var yRenderer1 = yAxis.get("renderer");

        yRenderer1.labels.template.setAll({
            tooltipText: "[fontFamily: NotoSans-regular][fontSize: 14px] {definition}",
            width: 250,
            maxWidth: 250,
            textAlign: "left",
            fontFamily: "NotoSans-Regular",
            fontSize: 14,
            fill: am5.color(0x002c77),
            oversizedBehavior: "wrap"
        });

        yRenderer1.labels.template.setup = function (target) {
            target.set("background", am5.Rectangle.new(root, {
                fill: am5.color(0x000000),
                fillOpacity: 0,
            }));
        };

        yAxis.data.setAll(data);

**Comment by martynasma** [comment]
Is there a reason why you are setting a tooltip to `yAxis.labelsContainer`, and not the axis itself?

Also, you would need to set `maxWidth` on tooltip's label, not the tooltip itself:

```JavaScript
var tooltip = am5.Tooltip.new(root, {
  pointerOrientation: "left",
});

tooltip.label.setAll({
  maxWidth: 200,
  oversizedBehavior: "wrap"
});
```

**Comment by ankit-mercer** [comment]
I've seen a demo on amcharts website regarding interactive axes, that is why I used this method because I need tooltip with interactive labels which can be modified as per need.

I'm unable to set the width using the method you shared in previous comment may be we have a different method of setting tooltip to an axes.

I'm sharing a code of that demo in which is used on amcharts website for axes tooltip and I've tweaked the codepen according to my requirement. Here you can see that width or maxWidth are not working on tooltip.

https://codepen.io/ankitkumar-mmc/pen/eYrNyxz?editors=0010

**Comment by martynasma** [comment]
Well, this works just fine for me on your CodePen:

```JavaScript
var tooltip = xAxis.labelsContainer.set("tooltip", am5.Tooltip.new(root, {  
  pointerOrientation: "right"
}));

tooltip.label.setAll({
  maxWidth: 200,
  oversizedBehavior: "wrap"
});
```
