### ISSUE TITLE
Scroll Bar's click event to return point

### ISSUE THREAD

**Issue by lasivtech** [amcharts/amcharts5#609]
https://www.amcharts.com/demos/line-different-colors-ups-downs/

from the above example, is it possible to get point by clicking in slider area?

for ex : on clicking somewhere on Scroll Bar. it should return it's X & Y value.

Thanks

**Comment by martynasma** [comment]
Do you mean screen XY value in pixels? Scrollbar XY value in pixels? Or actual X and Y axis value?
