### ISSUE TITLE
Is it possible to use fillField on ColumnSeries ?

### ISSUE THREAD

**Issue by justine-mlss** [amcharts/amcharts5#613]
Hello :) 

I'm trying to use the *fillField* on a ColumnSeries to change the color of the column and it doesn't work. Is it possible to do that ? 

Simple example : https://codepen.io/Justinemlss/pen/abGmbbB  with *fillField: am5.color(0xff0000)* 

I have also tried to use 
```
      series.columns.template.adapters.add('fill', function(fill, target) {
        const customColor = target.dataItem.dataContext.color;
        return customColor || fill;
      });
```
.. and It works but the tooltip text color isn't constrasting with the background. => 

![oups](https://user-images.githubusercontent.com/66368359/189694896-973c0826-0c94-4eea-a095-312c010268ce.png)

Thank you ! :)

**Comment by martynasma** [comment]
There is no `fillField` on a `ColumnSeries`.

You can use `templateField` instead:
https://www.amcharts.com/docs/v5/concepts/settings/template-fields/
