### ISSUE TITLE
How to disable show tooltip when hover on legend on Pie chart

### ISSUE THREAD

**Issue by trungthangdk** [amcharts/amcharts5#614]
Dear support,
I want to disabled tooltip when hover legend on PieChart. I was research on amchart4 and get solution in https://www.amcharts.com/docs/v4/tutorials/disabling-toggling-of-items-in-legend/
Please support me to this in amchart5.
Thanks

**Comment by martynasma** [comment]
This should do the trick:

```JavaScript
legend.itemContainers.template.setup = function(item) {
  item.events.disableType("pointerover")
};
```

**Comment by trungthangdk** [comment]
Thanks  you
