### ISSUE TITLE
How to show tooltipHTML on LineChart

### ISSUE THREAD

**Issue by trungthangdk** [amcharts/amcharts5#616]
Dear support.
I want to show tooltipHTML on LineChart. 
Please help me to check it.
Thanks

**Comment by sassomedia** [comment]
Which part are you struggling with?

**Comment by martynasma** [comment]
The following doc has a code snippet and a demo with HTML tooltip on a `ColumnSeries`:

https://www.amcharts.com/docs/v5/concepts/common-elements/html-content/#Tooltips

It will work exactly the same on a `LineSeries`.
