### ISSUE TITLE
How to assign type for setAll() method?

### ISSUE THREAD

**Issue by intaek-h** [amcharts/amcharts5#618]
I am drawing a map chart to set markers at certain coordinates. However, my typescript warns me for putting my data type into `unknown[]`.

```
const visitedRestaurantPointSeries = chart.series.push(
      am5map.MapPointSeries.new(root, {
        latitudeField: "latitude",
        longitudeField: "longitude",
      })
    );

    visitedRestaurantPointSeries.data.setAll(visitedRestaurants); <--- this here.
```
![스크린샷 2022-09-15 오후 8 38 51](https://user-images.githubusercontent.com/108341074/190394208-e2d3e375-955e-47f9-8acb-e79f2373eb12.png)

If I put exclamation mark at `visitedRestaurants!` like this, it stops. However, I don't think this is the best solution.

I have read the docs and it doesn't seem to have a guide for this. 

I'm using amcharts5, nextjs 12.2.
Thanks.

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
Well, `setAll()` method does not accept `undefined`.

So if the `!` workaround is not good enough, you can do a check like this:

```JavaScript
visitedRestaurantPointSeries.data.setAll(visitedRestaurants || []);
```

**Comment by intaek-h** [comment]
Hmm I was expecting using generic to somehow fix the allowed type for `setAll()` method. Are there any?

**Comment by martynasma** [comment]
`setAll()` needs an `Array`. Not entirely sure how generics could help you work around it to allow passing in anything else.
