### ISSUE TITLE
OutOfMemory Exception after upgrading to amcharts5

### ISSUE THREAD

**Issue by Zordiac** [amcharts/amcharts5#619]
Hi,

we have an application that is running 24/7 and periodically changing the current chart and the data behind it. It worked fine with amcharts3, but now we have upgraded to amcharts5, and after like half an hour, the app crashes because of an out of memory exception. Seems like there are memory leaks within amcharts5 that were not present in amcharts3. 

We didn't change anything from our code, except drawing an amcharts5 chart instead of the old amcharts3 one.

Can be reproduced by creating a new chart, populating it with lots of data and destroying it. Rinse and Repeat and you will see the out of memory exception.

Any ideas how to work around this? Or if this can be fixed from amcharts side?

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by alienbuild** [comment]
are you following the live data demo to constantly update the data? 
https://www.amcharts.com/demos/live-data/

if not and you are changing the charts completely make sure you're disposing of the old ones correctly. For example if you're using react


```
  useEffect(() => {
    if (chartRef.current) {
      chartRef.current.dispose();
    }
    if (am5 && am5exporting && am5stock && am5themes_Animated) {
      drawChart();
    }
  }, [am5, am5exporting, am5stock, am5themes_Animated]);

```

**Comment by Zordiac** [comment]
Hi, thanks for the quick response.

Here is a CodePen example:

https://codepen.io/Zordiac/pen/WNJRVWr

Please see the Memory Tab and the increasing heap space, which leads to an eventuel out of memory exception.

**Comment by martynasma** [comment]
@sassomedia is right. You need to `dispose()` the chart before creating anew.

That said, creating the new chart is always more costly resource-wise than just updating its data or config.

Do you need to delete whole chart every two seconds? Or maybe it's just data that is being updated.

https://www.amcharts.com/docs/v5/concepts/data/#Incremental_updates
