### ISSUE TITLE
How to get sum value in combine tooltip from serie line chart

### ISSUE THREAD

**Issue by vanvt** [amcharts/amcharts5#620]
Hello
I'm developing a feature related to the tooltip in the line chart
I want to show the total value when hovering on the tooltip
Is any way to do that?
https://codepen.io/vanvt6/pen/gOzgqXr
![image](https://user-images.githubusercontent.com/12226958/190557494-280078f5-fb26-474a-9faf-4408ecaf4962.png)

**Comment by xorspark** [comment]
You need to set [`calculateTotals`](https://www.amcharts.com/docs/v5/reference/ivalueaxissettings/#calculateTotals_property) to true in your value axis to enable `{valueYSum}` .

More info in [this tutorial](https://www.amcharts.com/docs/v5/tutorials/totals-on-column-stacks/#Preparing_value_axis).
