### ISSUE TITLE
Column ListTemplate is not refreshed properly in-time

### ISSUE THREAD

**Issue by LumineLittlelight** [amcharts/amcharts5#622]
Hi,

I am visualizing column charts that comprise of 100-200 columns of data. 
I'm using Vue 2 and ensured that I do not store any chart object in data property.

I added pre-zooming condition on the xAxis to just display the first 15 columns.
```
xAxis.events.on("datavalidated", function (ev) { 
          if (ev.target.dataItems.length >= 15) { 
            ev.target.zoomToIndexes(0, 15);  
          } else { 
            ev.target.zoomToIndexes(0, ev.target.dataItems.length); 
          } 
        });

```

My objective is to manipulate some of the label bullets explained like in this tutorial below.
[https://www.amcharts.com/docs/v5/tutorials/hide-or-relocate-label-bullets-for-small-columns/](url)

When the chart is first initialised (i.e initialise the root, axes and charts during mounted lifecycle) and go through first data update, the way from tutorial above works because the column ListTemplate somehow managed to get all children columns. 
![ListTemplateFirstRender](https://user-images.githubusercontent.com/112674127/190840873-375bf8f9-b87c-4fee-a70a-ce7bfab83e24.JPG)

However, after that, during subsequent data updates (i.e when receiving even similar payload from API) and refreshing the chart data using chart.data.setAll, 
the ListTemplate did not manage to refresh in-time, returning undefined and cause an error.

![ListTemplateUponDataRefresh](https://user-images.githubusercontent.com/112674127/190840872-cd632f44-5e98-4808-b466-b3c0f08ed756.JPG)

Also if it is refreshed, it seems only retrieve the rendered column in pre-zoomed axis, not all of them (values shown only 18 out of initial 183). 

The sequence of the data update code is like this. I am putting the bullet event handler at last to ensure list template has been updated, but it seems not to. trainRankingData is the data we receive from API.

```
this.xAxis.data.setAll(this.categoryData);
this.seriesBarChart.data.setAll(this.trainRankingData);
this.legend.data.setAll(this.legendBody);
this.addBulletEventHandler();
```

where adding Bullet Event handler code is like below:

```
addBulletEventHandler() {
        console.log(this.seriesBarChart.columns);
        this.seriesBarChart.columns.template.onPrivate(
          "height",
          function (height, target) {
            am5.array.each(target.dataItem.bullets, function (bullet) {
              if (height> 20) {
                 bullet.set("locationY", 0.5);
                 bullet.get("sprite").set("centerY", am5.p50);
              } else {
                bullet.set("locationY", 1);
                bullet.get("sprite").set("centerY", am5.p100);
              }
            });
          }
        );
      },
```

The error is that am5.array.each (which i believe is a for-loop) seems cannot get the length because it is undefined.
I would like to know further on how is the behavior of column ListTemplate when .data.setAll is invoked and there is pre-zooming axis imposed. 

Is my understanding correct that ListTemplate will not get all columns if pre-zooming is imposed?
Seems to me this is a component lifecycle issue.

I may have misunderstanding on the concept of ListTemplate.  Not too sure, whether we need to re-define the bullet event handler everytime the chart updates, or just initialise it at the beginning only (at mounted) and thats it. Will the event handler even applied to new introduced bullets if we put it at mounted?

I have tried moving the addBulletEventHandler to mounted lifecycle instead, but the error keeps happening anyway.

Your clarification will be very appreciated.
Thank you.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by LumineLittlelight** [comment]
Hi Martynas 

See if this codesandbox below works for you.
I'm simulating the API calls by making a dummy data in store.

https://codesandbox.io/s/sample-amcharts-train-rank-eeqdlc?file=/src/components/ChartTest.vue

**Comment by zeroin** [comment]
bullets ListTemplate is created on DataItem only when series comes to the situation it needs to display them. This is done for performance reasons, as for example, you might not display bullets if the distance between bullets is < minBulletDistance of a Series. This means that you need to check if this list template exist before doing something with it. datavalidated is fired before bullets are created. 

My suggestion would be to work with adapters, for example - you can add adapter for your bullet for a "x", meaning it will be called each time position of the bullet changes. You can return the same value but before returning you can modify other settings of a bullet.

**Comment by zeroin** [comment]
Here is how I'd do that:
https://codepen.io/team/amcharts/pen/LYmygKa/b77861f361aa260aa16548dddfe2eadc

The bullet with adapter:

```
series.bullets.push(function() {
  var label = am5.Label.new(root, {
    populateText: true,
    text: "{value}",
    centerX: am5.p50,
  });

  label.adapters.add("y", function(y, target) {
    var dataItem = target.dataItem;
    if (dataItem) {
      var column = dataItem.get("graphics");
      if (column) {
        if(column){
          var y = column.y();
          var plotHeight = chart.plotContainer.height();
          // can't use column height, as there might be invisible part of a column, if axis doesn't start at 0.
          console.log(y)
          if (y < plotHeight - 100) { // adjust 100 to some other number
            return y - target.height();
          }
          else {
            // middle
            return y + (plotHeight - y) / 2 - target.height() / 2;
          }
         }
      }
    }

    return y;
  })

  return am5.Bullet.new(root, {
    sprite: label
  })
})
```

**Comment by LumineLittlelight** [comment]
Hi zeroin. Thank you for the thorough example. Let me try to implement that code.

**Comment by LumineLittlelight** [comment]
Hi zeroin.  I tried to simplify the condition by alter the condition a bit to ease the observation.
Seems the interaction is not applied to whole columns when we expanding the scrollbarX.

If the column width is lesser than 25, hide the bullets (using "visible" settings on the adapter instead). 
If we expand the scrollbarX, it seems the bullets are only displayed on the columns that are inside the pre-zoomed condition. 

[https://codesandbox.io/s/sample-amcharts-train-rank-eeqdlc?file=/src/components/ChartTest.vue](url)
(Its on line 170-202)

```
this.seriesBarChart.bullets.push(() => {
        var label = am5.Label.new(vm.root, {
          populateText: true,
          fontSize: "0.75rem",
          text: "{valueY}",
          centerX: am5.p50,
          centerY: am5.p100,
        });

        label.adapters.add("visible", function (visible, target) {
          var dataItem = target.dataItem;
          if (dataItem) {
            var column = dataItem.get("graphics");
            if (column) {
              if (column) {
                var x = column.width();
                if (x > 25) {
                  return true;
                } else {
                  return false;
                }
              }
            }
          }
          return false;
        });

        return am5.Bullet.new(vm.root, {
          locationY: 1,
          sprite: label,
        });
      });
```

**Comment by zeroin** [comment]
The adapter for "visible" is only called once or when something hides/shoes the item. So in order for the adapter to set visibility, I would use adapter for x  (because x position will always change when you zoom or scroll the chart), return the same x which was passed and modify visibility before that.

**Comment by LumineLittlelight** [comment]
Ah got it! It works! Thank you, zeroin for the guidance. 
Learned some new ways and concept today :) 

Closing the thread.
