### ISSUE TITLE
Scroll bar's start and end data items.

### ISSUE THREAD

**Issue by lasivtech** [amcharts/amcharts5#623]
https://www.amcharts.com/demos/simple-column-chart/

from the above sample. is it possible to get data item of start and end position of scroll on "globalpointerup" event?

for ex. I zoomed Oct 9 to Oct 24. I want data item for start and end position of it. is it possible?

Thanks

**Comment by martynasma** [comment]
I would use axis' `getSeriesDataItem()` method:

```JavaScript
xAxis.on("start", getStartEnd);
xAxis.on("end", getStartEnd);

function getStartEnd() {
  var startDataItem = xAxis.getSeriesItem(series, xAxis.get("start")) || series.dataItems[0];
  var endDataItem = xAxis.getSeriesItem(series, xAxis.get("end"));
  if (startDataItem && endDataItem) {
    console.log(new Date(startDataItem.get("valueX")), new Date(endDataItem.get("valueX")))
  }
}
```

https://codepen.io/team/amcharts/pen/zYjwjYY
