### ISSUE TITLE
Can't align the legend in an external container

### ISSUE THREAD

**Issue by jdim** [amcharts/amcharts5#625]
**Question**

Seems properties `centerX` and `x` don't effects on alignment of the legend if it in an external container

Example:
https://codepen.io/dm-khabarov/pen/PoemRME

**Environment (if applicable)**

 - amCharts version 5
 - Browser Chrome 105

Thanks.

**Comment by zeroin** [comment]
If you set width to 100%, the legend takes all the available space. If you remove the `width: am5.percent(100)`, the legend will be centered.

**Comment by jdim** [comment]
Thanks a lot!
