### ISSUE TITLE
tooltipHTML blinks when hovering on stacked ColumnChart

### ISSUE THREAD

**Issue by trungthangdk** [amcharts/amcharts5#626]
Dear support,
I get some issue with ticket https://github.com/amcharts/amcharts5/issues/608
I've updated the latest version 5.2.22, but the issue is still happening now.
Please help me to check this.
Thanks

**Comment by martynasma** [comment]
Let's not duplicate stuff. If you have something to add, like a new demo or something to the original issue, please post a comment there.
