### ISSUE TITLE
Can we automate amchart 5

### ISSUE THREAD

**Issue by swapnilh-cognologix** [amcharts/amcharts5#627]
Can we automate amchart 5 like we automate amchart 4 using ID attribute

**Comment by zeroin** [comment]
Sure, you can.

**Comment by swapnilh-cognologix** [comment]
Can you please point me to the documentation link for this.

Thanks in advance

**Comment by martynasma** [comment]
@swapnilh-cognologix Do you mean attaching custom id attribute to individual chart elements for testing?

amCharts 5 works differently. It uses canvas element, which means that there are no individual elements.

**Comment by swapnilh-cognologix** [comment]
Oh yes this is what I want to confirm we are using canvas to draw the chart.

Thank you so much @martynasma
