### ISSUE TITLE
Does gapless date axis approximate the date time granularity?

### ISSUE THREAD

**Issue by avithemad** [amcharts/amcharts5#628]
**Question**
In case of gapless date axis, does the time get approximated?
For example, the dataset is below
{date: 1663732800000, value: 200, tooltipText: '200 KWH'}
{date: 1663754400000, value: 350, tooltipText: '350 KWH'} 
{date: 1663756320000, value: 450, tooltipText: '450 KWH'}

Here the third data point's exact date time is: Wed Sep 21 2022 16:02:00 GMT+0530 (India Standard Time)
But this approximated to 4 PM IST in the graph, 
![image](https://user-images.githubusercontent.com/25084977/191434219-16ffd452-0279-446f-9f2a-cf97a6ed8a8b.png)

Is it possible to have it exactly on the given time?

**Environment (if applicable)**

**Additional context**

**Comment by zeroin** [comment]
It shouldn't, unless you set baseInterval not to 1 minute. If you could post a codepen of your chart, I could take a look.

**Comment by avithemad** [comment]
Yes I have set it to 1 minute, should I remove it?

**Comment by zeroin** [comment]
1 minute is correct. I will need a codepen in order to tell why this happens.
