### ISSUE TITLE
Stock chart comparing series

### ISSUE THREAD

**Issue by ankit-mercer** [amcharts/amcharts5#629]
This seems to be a bug as when the searchcallback is triggered on the main or comparing series and user searches for any item and then clears the search using backspace without or with selecting any item on the list, the list do not refresh itself. Moreover, later user can add any number of items in the chart even if the condition is applied.

<img width="903" alt="Capture" src="https://user-images.githubusercontent.com/96469108/191469987-4e67d1eb-be5a-4cbd-8e35-e1d286e90c91.PNG">

**Comment by zeroin** [comment]
I checked and deleting symbols works fine for me, the list is updated. As for the possibility to add more than one comparing series, we will most likely fix this.

**Comment by ankit-mercer** [comment]
Hi @martynasma @zeroin There is a confusing as I meant the following: 

1) There is a glitch wherein the search tab gets frozen when you are selecting cities from the drop down as shown below. Moreover, it does not grays out the item which is already selected.
![image](https://user-images.githubusercontent.com/96469108/191705789-7701b9c1-6a70-40da-912f-d7bca6df1f33.png)

2) This happens when you type and delete something on the search tab.
3) Once the search bar glitches you are able to select as many items you want as shown below we have selected multiple items and validation for duplication also stops working screenshot for reference below:
![image](https://user-images.githubusercontent.com/96469108/191706203-a0a65d28-2c3b-4b45-bb9d-58a24b88f199.png)

**Comment by martynasma** [comment]
@ankit-mercer I'm having trouble reproducing the issue based on your description on this demo:

https://www.amcharts.com/demos/stock-chart-comparing-prices/

Are you getting the issue on this demo, or something else?

**Comment by ankit-mercer** [comment]
https://mmcglobalind-my.sharepoint.com/:v:/g/personal/gurkirat_turna_mercer_com/EcHGek82P3JNluc-1Ol6waIB80cb6oOTy6Nw-I3JL1_26w

**Comment by ankit-mercer** [comment]
@martynasma I have created a video depicting the issue.
https://user-images.githubusercontent.com/96469108/191907616-076eae03-27f1-42cd-8c20-64272c180281.mp4

I look forward to hear from you soon.

**Comment by zeroin** [comment]
I am afraid there is no video in your post. What browser do you use? Does the same happen on other computers?

**Comment by ankit-mercer** [comment]
I had just updated the comment.

**Comment by martynasma** [comment]
@ankit-mercer Thanks.

We've updated the demo. It would not disable main series in comparison selection, too.
