### ISSUE TITLE
Is it possible to create multiple axis cursors?

### ISSUE THREAD

**Issue by alienbuild** [amcharts/amcharts5#63]
I'm trying to add multiple lineY cursors so that I can have one sticky/always showing and another free use as a point of reference for the user. 

I can't see in the documentation if that's possible to do, or if it's possibly to use lineX as a Y axis instead as a work around. 

```
        const cursor = chart.set("cursor",
            am5xy.XYCursor.new(chartRef.current, {
                alwaysShow: true
            }));
        cursor.lineY.set("visible", true);
        cursor.lineX.set("visible", false);
```

I appreciate this is perhaps more of a stackoverflow question but also appreciate that amcharts 5 is extremely niche at the moment, so if anyone can offer an answer i'd be extremely grateful.

Thanks,

**Comment by martynasma** [comment]
No, I'm afraid chart does not support multiple cursors.

If you need to point out certain position on the chart, maybe just add an axis range?

https://www.amcharts.com/docs/v5/charts/xy-chart/axes/axis-ranges/

**Comment by alienbuild** [comment]
Thank you, that actually works perfectly for my needs
