### ISSUE TITLE
AMcharts5 heatRules customFunction set sprite key error

### ISSUE THREAD

**Issue by athir13en** [amcharts/amcharts5#630]
Getting error when trying to set sprite's key - fill.
"Argument of type '"fill"' is not assignable to parameter of type 'keyof ISpriteSettings'"
reference - https://www.amcharts.com/docs/v5/concepts/settings/heat-rules/
using react-typescript
![Screenshot 2022-09-21 194715](https://user-images.githubusercontent.com/16775402/191496161-982c06aa-af26-4db6-90dc-883b34ac4f38.jpg)

**Comment by zeroin** [comment]
Try to add `sprite as am5.Graphics` into you function attributes.

**Comment by athir13en** [comment]
It works after casting sprite to am5.Graphics.
Thanks!
![Screenshot 2022-09-22 121041](https://user-images.githubusercontent.com/16775402/191656754-16c90e3b-3ee2-4dbe-84df-2b3c4ec8746d.jpg)
