### ISSUE TITLE
Amchart Stock chart comparing series

### ISSUE THREAD

**Issue by ankit-mercer** [amcharts/amcharts5#631]
Could you please help me in fixing the value axis when the axis scale is changed to percent. This issue occurs for those series that have value at x axis very close to zero. I am sharing a code pen for reference. 
https://codepen.io/ankitkumar-mmc/pen/QWrqqzL?editors=0010

**Comment by zeroin** [comment]
Could you explain what do you mean by fixing, what issue do you have in mind? If its the negative values, then you should not set extraMin value.
