### ISSUE TITLE
Clockhand fill in gradient gauge

### ISSUE THREAD

**Issue by justine-mlss** [amcharts/amcharts5#632]
Hello :) 

Is there a way to fill the clock hand with the corresponding color of the gradient color ?
![gradient_gauge](https://user-images.githubusercontent.com/66368359/191963259-453bbf9e-8b32-4a3e-b71a-ae8aaa3f7a1f.png)

Here, I don't want black but the orange of the gradient. 

```
  const clockHand = am5radar.ClockHand.new(root, {
    radius: am5.percent(100),
    innerRadius: 0,
    pinRadius: 45,
  });
    const bullet = axisDataItem.set(
      'bullet',
      am5xy.AxisBullet.new(root, {
        sprite: clockHand,
      }),
    );

    const label = chart.radarContainer.children.push(
      am5.Label.new(root, {
        fill: am5.color(0xffffff),
        centerX: am5.p50,
        textAlign: 'center',
        centerY: am5.p50,
        fontSize: '3em',
      }),
    );
    bullet.get('sprite').on('rotation', () => {
      const value = axisDataItem.get('value');

      // const fill = am5.color('#90bb39'); // Here I want to have the correct color 

      label.set('text', value);

      clockHand.pin.animate({ key: 'fill', to: fill, duration: 500, easing: am5.ease.out(am5.ease.cubic) });
      clockHand.hand.animate({ key: 'fill', to: fill, duration: 500, easing: am5.ease.out(am5.ease.cubic) });
    });
```

Thank you :)

**Comment by zeroin** [comment]
You should create an adapter for fill of pin and hand sprites of ClockHand. And then pick intermediate color based on a value. Its not very straightforward, so I made a demo:

https://codepen.io/team/amcharts/pen/QWrOYeR

**Comment by Vadim-Podlevsky** [comment]
A bit off-topic but please give me a hint if the gradient of a gauge can be made circular but not linear?
