### ISSUE TITLE
Gauge Clockhand value 0 not centered 

### ISSUE THREAD

**Issue by justine-mlss** [amcharts/amcharts5#633]
Hello , 

I created a gauge with a clockhand. I noticed that when the value is 0, the text is off center. 

`axisDataItem.set('value', 0)`
![0](https://user-images.githubusercontent.com/66368359/191978103-092c03a7-25f2-4a6f-b7e7-20c12fc6346b.png)

`axisDataItem.set('value', 1)`
![1](https://user-images.githubusercontent.com/66368359/191978138-8492fab0-1aff-4680-b990-d062e140b2f4.png)

Is it a bug ? :thinking: 

Thanks and good luck
Justine

**Comment by xorspark** [comment]
I forced a zero value on a couple of our gauge demos and the zero is centered correctly for me on Firefox and Chrome. Can you provide a codepen?

**Comment by justine-mlss** [comment]
@xorspark sorry for the long time.
Here an example : https://codepen.io/Justinemlss/pen/oNdrMYR

**Comment by justine-mlss** [comment]
i fixed it, using string` text: '0',` unstead of number ` text: 0,`
It's weird because all types number word , but not 0
