### ISSUE TITLE
Cant find styling for Legend Container

### ISSUE THREAD

**Issue by mukeshbadgujar** [amcharts/amcharts5#638]
Can you please suggest me what should i use to resize **height** of the  Legend Container .
in below image i can resize text size, width of Legend Container, but not the height.

the [width: 100] can able to increase Legend Container width.

what for the height ? (I need it for, when i plot chart in small size that time chart is smaller but this legends are still bigger.) 

![image](https://user-images.githubusercontent.com/32473209/192694819-805169b1-9f31-4a84-90d9-a03e0145be0a.png)

ref: https://www.amcharts.com/docs/v5/concepts/formatters/text-styling/

**Comment by zeroin** [comment]
Height of legend item depends on the children height in it. So you have to 
1) make text smaller
2) resize marker:
`valueLegend.markers.template.setAll({height:10, width:10})`
3) resize settings icon:
`valueLegend.settingsButtons.template.set("scale", 0.5);`

This will make legend item smaller in height.

**Comment by mukeshbadgujar** [comment]
Working Good... Thanks for Solution.. @zeroin
