### ISSUE TITLE
What are the equivalents for "ready"/"visibilitychanged" events for pie series labels in amCharts 5?

### ISSUE THREAD

**Issue by DmitryOganezov** [amcharts/amcharts5#64]
**Question**
I'm trying to port some pie charts from amCharts 4 to amCharts 5,
What I need is to hide small slice labels, as it's described in this tutorial:
https://www.amcharts.com/docs/v4/tutorials/hiding-small-pie-slices/#Hiding_labels

Unfortunately, none of the familiar pieSeries.labels.template.events fire up in amCharts 5, including "ready" and "visibilitychanged".

BTW, is there a sort of migration guide awailable?

**Comment by martynasma** [comment]
I believe this is better achieved with adapters:

```JavaScript
series.labels.template.adapters.add("visible", function(visible, target) {
  return target.dataItem.get("valuePercentTotal") > 5;
});

series.ticks.template.adapters.add("visible", function(visible, target) {
  return target.dataItem.get("valuePercentTotal") > 5;
});
```

IMPORTANT: these need to come before setting data on series.

https://codepen.io/team/amcharts/pen/vYJVOPW

**Comment by DmitryOganezov** [comment]
Thank you!
