### ISSUE TITLE
Can you fix the dialog box size based on the chart size?

### ISSUE THREAD

**Issue by mukeshbadgujar** [amcharts/amcharts5#640]
if i used indicator control to plot indicator, it is going out of that chart area.
in some cases there should not extra space outside the chart. that time it will give me problem.

image shows, i am plotting one indicator on 1st chart, so the settings dialog should be in 1st chart.

![image](https://user-images.githubusercontent.com/32473209/192697050-41cfd13c-302a-4117-908f-dbc446d8b9ac.png)

**Comment by martynasma** [comment]
How would you "fix" it? Make the popup scroll?

**Comment by mukeshbadgujar** [comment]
i have fixed it with css, just removing some padding, reducing fontsize.
