### ISSUE TITLE
Stockchart hiding series when one value at x-axis is zero

### ISSUE THREAD

**Issue by gurkirat-turna** [amcharts/amcharts5#641]
Hi Team,

There are some issue in the functionality of this chart, if it is viewed in percent. The issue occurs in the below cases:

1) Value at x-axis is zero or near to zero.
2) Using the gear icon, user switches to change percent.
3)  The data gets hidden, moreover in some cases the labels at y-axis changes to like 1500000000% which is mathematically incorrect.

Sharing a codepen for reference.
https://codepen.io/gurkirat_turna/pen/wvmLZzG?editors=0010

Thanks :)

**Comment by zeroin** [comment]
When you change view to a percent view, it shows how much values changed comparing to your initial value. So if your initial value is 0, the change is infinity, so this can't be displayed. If your first value is close to 0 and the other values are way biggere, than 1500000000 is a possible value.

**Comment by gurkirat-turna** [comment]
Can we that be fixed anyway. Moreover, the data also gets hidden sometimes. Kindly check codepen for reference.

**Comment by zeroin** [comment]
It can't be fixed, you can't show a graph where all the values are equal to Infinity. If your values can be 0, then you should simply remove the option to change to percent.
