### ISSUE TITLE
Chart gets overpainted when series gets hidden/shown

### ISSUE THREAD

**Issue by dkdev030** [amcharts/amcharts5#643]
Hello Team,

I've setup a XYChart with multiple series in it. Some of them have `visible = false` and I've provided a `type`-attribute to distinguish them from the other series, when created. When created the chart looks fine, but as soon as I change the property (`applyNelsonRules`) that controls whether or not the hidden series should be shown I get a weird kind of overpaint issues with the chart.

To change the state of the given series I loop over all the series in the chart itself
```javascript
this.chart.series.each(async (series) => {
  if (series._settings.type != "nelson-rule") return;
  if (this.applyNelsonRules) {
      await series.show()
  } else {
      await series.hide();
  }
});
```
Unfortunately, I can't provide a more detailed code-example at the moment.

_Initial Chart_
![image](https://user-images.githubusercontent.com/43716136/192759956-27e242cc-b773-4d7b-b010-877c4c57ae79.png)

_Chart when property gets set to show the hidden series_
![image](https://user-images.githubusercontent.com/43716136/192761090-13489973-cda3-4f0f-be5a-89bef5ef339f.png)

_Desired Chart_
![image](https://user-images.githubusercontent.com/43716136/192761230-ca791d15-77f0-4c86-a561-5e96b4bd7ebc.png)

**Environment (if applicable)**
* @amcharts/amcharts5: "^5.2.26"
* vue: "^3.2.36"

**Comment by martynasma** [comment]
Do you get any errors in browser console when this is happening?

Also, have you tried not using `async` and `await`?

Technically, this would wait for each series hiding/showing animation to finish before going on to another. But I'm not entirely sure that `.each()` iterator is async-proof, or if there are any other potential issues associated with it.

**Comment by dkdev030** [comment]
Unfortunately there are no errors in the console. 
Are there any debug options i can set to get further informations?

Removing `async/await` isn't changing the outcome, unfortunately.

**Comment by zeroin** [comment]
Can you try to create the same chart without vue and see if this happens?

**Comment by dkdev030** [comment]
Sure, I try to get it done by tomorrow and will get back to you.

**Comment by dkdev030** [comment]
So I had a little bit of time right now and made a fiddle. 
@zeroin as it seems you are on the right track with your assumption and it is most likely an issue with Vue.

Here is the link to the fiddle
https://jsfiddle.net/dkdev030/0x1nqmbh/15/
I removed just the bullets and one series, that doesn't matter anyways.

**Comment by dkdev030** [comment]
Okay, it was the reactivity of Vue.
We can close the issue. 

The reasoning why it worked before would be just wild guesses on my side. Maybe it was just luck.

I can only emphasize for others who maybe get here, to use `shallowRef` or `markRaw()`, for every element that is associated to the chart. Both will work and will remove the reactivity. You will gain also your performance back, because Vue isn't checking the whole components `data`.

Thanks to @martynasma and @zeroin for leading me to a solution.
