### ISSUE TITLE
Line Series Tooltip DataItem DataContext returning undefined. 

### ISSUE THREAD

**Issue by LumineLittlelight** [amcharts/amcharts5#644]
Hi,

I want to set an adapter to tooltip label on Line Series and I need to see the dataItem.dataContext (i.e the context of the data which the tooltip is hovering on), however, it returns undefined. 

```
series.get("tooltip").label.adapters.add("text", function (text, target) {
	console.log(target);
	var totalP = calcPercent(target._dataItem.dataContext.Total, target._dataItem.dataContext.TotalSum);

	return "Total : [bold]{Total}[/]\nPercent : [bold]"+totalP+"[/]";
});

```

The code above works when I tried on column series, but not on line series because it is returning undefined on the dataItems. 

https://codepen.io/LumineLittlelight/pen/eYrVGvQ?editors=1111

I made a codepen with slight modification from your tutorial by adding a console.log on line 193 and it is returning undefined. 

May I know if there is alternative way to know the dataContext of a lineSeries in order to adjust the label via adapter?

Your guidance will be appreciated. Thank you.

**Comment by zeroin** [comment]
A series has a setting, tooltipDataItem which refers to currently hovered data item. Note, it can be undefined, so you should check.
```
var tooltipDataItem = series.get("tooltipDataItem");
if(tooltipDataItem){
    console.log(tooltipDataItem.dataContext.Total)
}
```

**Comment by LumineLittlelight** [comment]
Ah understood. Okay I will add that undefined checks then. Thank you.
