### ISSUE TITLE
Sankey label adapter

### ISSUE THREAD

**Issue by nsds26** [amcharts/amcharts5#645]
**Question**
Hey there!

I was building a Sankey diagram on V5 for the first time, but faced an issue with labeling. On v4 I was adding a adapter like so:
```
chart.nodes.template.nameLabel.label.adapter.add("textOutput", function (text) {
       return text.split("-")[0];
});
```
How can I achieve this outcome on V5?

Another question, how can I set the label of the last node to be the **_sumIncoming_**, while the rest using the **_sumOutgoing_**? Would I have to define each node individually on the _**series.nodes.data.setAll**_ and then on **_nodeSettings_** property? Or is there a way to select only the last node?

Thank you!!

**Comment by zeroin** [comment]
Here is how you access labels of sankey nodes:
https://www.amcharts.com/docs/v5/charts/flow-charts/sankey-diagram/#Label_content

you can add "text" adapter for the `series.nodes.labels.template`
