### ISSUE TITLE
CursorSelection Boundary to be dynamically adjusted to the axis when zooming

### ISSUE THREAD

**Issue by LumineLittlelight** [amcharts/amcharts5#646]
Hi,

May I check if there is any settings that allow XYCursor selection rectangle (the grey rectangle) to adjust its boundary accordingly to the axes when zooming?

At the moment, it seems upon zoom, the selection boundary (since its a Rectangle) makes it looks like floating on the axis.
Any work around on this? 

Thank you.

**Comment by zeroin** [comment]
I must say I don't understand, some sketch explaining what you want to achieve would help.

**Comment by LumineLittlelight** [comment]
Hi zeroin, apologies for the confusion. 

https://codepen.io/team/amcharts/pen/ZEoGaLM

So based on this codepen, lets say we make a selection.

![ss_max](https://user-images.githubusercontent.com/112674127/192979594-9a43beab-fcda-4d41-8ac7-9b2ea077f320.png)

So above, is the initial grey rectangle selection.
Then, let's zoom in the axes while the selection still there.
![ss_zoom](https://user-images.githubusercontent.com/112674127/192979725-7a4130ff-2d91-4145-9c5e-aea0b922e094.png)

As we can see the selected scatters are now outside of the selection rectangle. 

Similar behavior can be seen when we try to draw any shapes/rectangle to the charts. Seems we cannot anchor it to the axes (i.e the shapes are zoom in tandem with the axes zoom).

**Comment by zeroin** [comment]
To solve this, you should create line series and draw the rectangle using series, not just a regular shape. In this demo the colored rectangles are made with series:
https://www.amcharts.com/demos/animated-xy-bubble-timeline-chart/

**Comment by LumineLittlelight** [comment]
Got it. Understood. Thanks for the confirmation. We will be using method suggested by you.
