### ISSUE TITLE
Added axis label hidden by column serie

### ISSUE THREAD

**Issue by carinezhang** [amcharts/amcharts5#647]
Hello,
I'm currently trying to add a threshold line to my graph but the label is hidden by the column serie.
The line is above the column serie, but not the label.

![Capture du 2022-09-29 17-45-36](https://user-images.githubusercontent.com/10708475/193078033-48da2f61-e39d-4959-970e-332e0f9a522e.png)

You can find my test here: [https://codepen.io/carinezhang/pen/bGMvGLO](https://codepen.io/carinezhang/pen/bGMvGLO)
How can i fix that ?

Thank you !

**Comment by zeroin** [comment]
The easiest way to solve this would be to set layer:100 for your label. Note, try to avoid having many different layers, as this is not good for performance.

**Comment by carinezhang** [comment]
it works, thank you !
