### ISSUE TITLE
DateAxis without baseInterval

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts5#648]
Hello,

Is there a way to make a LineSeries based on a DateAxis without setting a baseInterval ?

I would like to print my data without rounding date...

Or maybe to change the baseInterval in relation to the zoom?

Thanks for your support !

**Comment by martynasma** [comment]
There's no way to do that. `baseInterval` is an indicator about granularity of your data.

If it's not consistently spaced out, you can use smallest possible increments that you think makes sense for your data.

For example, if you have data spaced at hours, but data points that could come at any minute within the hour, it would make sense to use "minute" as interval.

Zooming will adjust the grid/labels/scale automatically, but the axis needs to know the nature of your data.

Hope that makes sense.

**Comment by ptorrent** [comment]
Hello,

Thanks for your answer, make sense for me.

Thanks !

**Comment by ptorrent** [comment]
Hello again @zeroin ,

In fact it's a bit confuse for me...

As my data is not consistently spaced I choose "millisecond" as baseInterval unit. Does it make sense? 

I can have 30 values in 1 minute and maybe nothing for next 15 minutes...

Whit "millisecond" units seems that tooltip is not displayed:

https://codepen.io/ptorrent/pen/PoabNMv
