### ISSUE TITLE
How to change base value line color

### ISSUE THREAD

**Issue by cwooldridge1** [amcharts/amcharts5#649]
I am looking to change the color of the base value line on the chart. I was not able to find how to change the appearance. Is there a way to change the color?

Thanks

**Comment by martynasma** [comment]
Just to make sure, what is "base value line"?

**Comment by cwooldridge1** [comment]
@martynasma https://www.amcharts.com/docs/v5/charts/xy-chart/axes/value-axis/#Base_value

**Comment by martynasma** [comment]
Gotcha. Thanks.

There's no separate object that you can apply color to.

I suggest simply adding an axis range line at the base value:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/axis-ranges/

**Comment by cwooldridge1** [comment]
Gotcha, thanks.
