### ISSUE TITLE
Synchronize cursors between multiple chart based on date

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts5#650]
Hello !

Is there a way to synchronize cursor between multiple chart ?

This is what I'm using as cursor :

```
var cursor = chart.set("cursor", am5xy.XYCursor.new(root, {
	xAxis: xAcis
}));
cursor.lineY.set("visible", false);
```

Thanks for your help

**Comment by zeroin** [comment]
The best way to do this would be to set private setting "otherCharts" with array of charts you want to sync. This is not yet documented, but we will update docs soon.

`chart0.setPrivate("otherCharts", [chart1, chart2, chart3])`

This will do all the syncing.
