### ISSUE TITLE
How to disable word cloud animation?

### ISSUE THREAD

**Issue by lasivtech** [amcharts/amcharts5#654]
Is there any option to disable animation. I want to appear all word at load instead of load each word by one on animation.

**Comment by zeroin** [comment]
It takes time to make the arrangement, this is quite costly process. You can disable fade-in but it will still take the same amount of time. To disable fade-in, you should set:

`series.labels.template.states.create("hidden", {opacity:1})`

**Comment by lasivtech** [comment]
now much better :)  thank you.
