### ISSUE TITLE
How to get Settings of Indicator?

### ISSUE THREAD

**Issue by mukeshbadgujar** [amcharts/amcharts5#659]
i want all settings that can be edit while plotting the chart.
i can see settings inside _settings
![Screenshot from 2022-10-06 17-17-34](https://user-images.githubusercontent.com/32473209/194304894-70bedd91-ddb5-450f-815c-b3abbf869c9d.png)

but i want,
only those which are here below img
![Screenshot from 2022-10-06 17-14-41](https://user-images.githubusercontent.com/32473209/194304497-b8629afc-a5e6-4f75-b20d-28f5e7b25f01.png)

i want to compare two macd's which one is plotted on chart and one is going to plot.
how i can compare both.

**Comment by mukeshbadgujar** [comment]
currently i am using `stockChart.indicators.values`

**Comment by martynasma** [comment]
If you need to get a value of a setting from the indicator, you can use its `get()` method, e.g.:

```JavaScript
indicator.get("fastPeriod");
```

All available settings for MACD indicator are here:
https://www.amcharts.com/docs/v5/reference/macd/#Settings

**Comment by mukeshbadgujar** [comment]
is there any dynamic way to get all settings shown below,
because there are so many indicators, so to write code to get settings manually for all is not a good idea.
![](https://user-images.githubusercontent.com/32473209/194304497-b8629afc-a5e6-4f75-b20d-28f5e7b25f01.png)

**Comment by martynasma** [comment]
Actually, yes!

You can get editable settings from the indicators' `_editableSettings` property:

```JavaScript
console.log(indicator._editableSettings);
```

For MACD it contains the following:

```JavaScript
[{
	key: "fastPeriod",
	name: this.root.language.translateAny("Fast MA period"),
	type: "number"
}, {
	key: "slowPeriod",
	name: this.root.language.translateAny("Slow MA period"),
	type: "number"
}, {
	key: "signalPeriod",
	name: this.root.language.translateAny("Signal period"),
	type: "number"
}, {
	key: "seriesColor",
	name: this.root.language.translateAny("MACD"),
	type: "color"
}, {
	key: "signalColor",
	name: this.root.language.translateAny("Signal"),
	type: "color"
}, {
	key: "increasingColor",
	name: this.root.language.translateAny("Increasing"),
	type: "color"
}, {
	key: "decreasingColor",
	name: this.root.language.translateAny("Decreasing"),
	type: "color"
}]
```

`key` is the actual setting from indicator you can use in `indicator.get(...)`.

**Comment by mukeshbadgujar** [comment]
ok thanks, working for now
