### ISSUE TITLE
MapChart Not Interactible with Vue3 (Invisible Div Layer)

### ISSUE THREAD

**Issue by Dealman** [amcharts/amcharts5#660]
**Bug Description**

Trying to create a `MapChart` with `amCharts 5` on a Vue3 website, the map can not be interacted with because of a `div` element being injected on top of it - preventing any and all interaction. If this element is deleted, things works as expected - except for zoom being rather erratic. 

**Environment**
- amCharts 5.2.27
- amCharts GeoData 5.0.3
- Vue 3.2.38
- TypeScript 4.7.4

**Additional Context**
[StackOverflow question posted here](https://stackoverflow.com/questions/73975522/empty-div-preventing-interaction-with-amcharts5-mapchart-on-vue3) which has the component's code, but figured I'd make an issue as well since this issue appears even on an entirely empty chart with only the root created.

**Edit:**

As always, I solve the issue just after I give up and post an issue... After digging around I was able to locate the culprit inside `base.css` which is automatically generated when you create a new app project.

Inside this file you can find these lines;
```css
*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  position: relative;
  font-weight: normal;
}
```

Taking those lines and yeeting them in the trash fixes the issue.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by Dealman** [comment]
I updated the original post with the solution, it was due to some remnants of the default startup project adding it via CSS.

This was the code I had at the time;
```typescript
<template>
  <div class="testClass" ref="chartdiv">
  </div>
</template>

<script setup lang="ts">
  import * as am5 from "@amcharts/amcharts5";
  import * as am5map from "@amcharts/amcharts5/map";
  import am5geodata_worldLow from "@amcharts/amcharts5-geodata/worldLow";
  import am5themes_Animated from '@amcharts/amcharts5/themes/Animated';
  import { ref, onMounted, onUnmounted } from "vue";

  const chartdiv = ref<HTMLElement | null>()
  var root!: am5.Root;

  onMounted(() => {
    if (chartdiv.value) {
      // Create the Root
      var root = am5.Root.new(chartdiv.value);
      
      // Setup the MapChart
      var chart = root.container.children.push(
        am5map.MapChart.new(root, {
          panX: "rotateX",
          panY: "rotateY",
          projection: am5map.geoOrthographic(),
          centerMapOnZoomOut: false
        })
      );

      // Setup Animations
      root.setThemes([
        am5themes_Animated.new(root)
      ]);

      // Create MapPolygons
      var polygonSeries = chart.series.push(
        am5map.MapPolygonSeries.new(root, {
          geoJSON: am5geodata_worldLow
        })
      );

      // Setup MapPolygon Styling
      polygonSeries.mapPolygons.template.setAll({
        tooltipText: "{name}",
        fill: am5.color("#909090")
      });
      
      // Setup MapPolygon Hover Styling
      polygonSeries.mapPolygons.template.states.create("hover", {
        fill: am5.color("#FF0000"),
        stroke: am5.color("#00FF00"),
        strokeWidth: 2
      });

      polygonSeries.mapPolygons.template.events.on("click", function(event) {
        //console.log("Clicked: {0}", event.target);
      });

      // Setup Background
      var backgroundSeries = chart.series.unshift(
        am5map.MapPolygonSeries.new(root, {})
      );

      backgroundSeries.mapPolygons.template.setAll({
        fill: am5.color(0x2c84d0),
        stroke: am5.color(0x2c84d0)
      });

      backgroundSeries.data.push({
        geometry: am5map.getGeoRectangle(90, 180, -90, -180)
      });
    }
  });

  onUnmounted(() => {
    if (root) {
      root.dispose();
    }
  });
</script>

<style scoped>
  .testClass {
    width: 50vw;
    height: 50vh;
  }
</style>
```

I have since changed it a little bit so I use the ID tag of the element instead of `ref`.
