### ISSUE TITLE
Logic behind displaying closest data item tooltip for series with cursor enabled

### ISSUE THREAD

**Issue by senchden** [amcharts/amcharts5#661]
**Question**
Hi. I would expect amcharts to display the closest data item tooltip with XYCursor enabled. However with setting smaller `baseInterval` units (like "minute") and zooming to chart values, the tooltip is only displayed after directly hovering the column series item. I would like to display the series tooltip for the closest data item. Is there a way to configure amcharts to achieve such behaviour?

**Environment (if applicable)**
I have created a fiddle here: https://jsfiddle.net/pcmzfhav/2/ , you would need to zoom in on the values completely.

**Additional context**

There if a GIF indicating the problem:

![closest-tooltip-question](https://user-images.githubusercontent.com/31250983/194540091-d8382a36-2c82-42d1-a497-4c96b9af993a.gif)

Thank you in advance.

**Comment by martynasma** [comment]
You may need to enable snapping to series:
https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/#snapping-to-series

**Comment by senchden** [comment]
I see. I would like to do it without snapping. My mistake for not providing the complete use case. Actually the use case is several charts - individual amcharts instances with different roots and manually synced cursors. All charts have the same date range which is explicitly set. Ideally I would like to have all cursors on the same X display position. Since the charts have different data, then cursor would be out of sync. I there another way to do it?

**Comment by martynasma** [comment]
Well, enabling snapping to series does not mean the cursor line itself will snap to data items. It's just the tooltip, which I imagine, is what you need.

**Comment by senchden** [comment]
Here is a screencast to better illustrate the issue:
![closest-tooltip-question-sync](https://user-images.githubusercontent.com/31250983/194570058-5b20ca35-cd0c-423d-8756-818fd4fb9f18.gif)

**Comment by martynasma** [comment]
`cursormoved` is invoked when cursor moves to different category/date/increment.

If you're looking for incremental move, use monitoring of changes for `positionX` private setting:

```JavaScript
cursor.onPrivate("positionX", function(x) {
 console.log(x);
})
```

**Comment by senchden** [comment]
It seems that that `onPrivate("positionX"` handler is actually getting called twice - once with the original value(that on under the mouse cursor) and once more immediately after - with the snapped value, thus rewriting the original value.

**Comment by martynasma** [comment]
Indeed.

You can also monitor `x` coordinate of the cursor line to get exact location:

```JavaScript
cursor.lineX.on("x", function(x) {
 console.log(x);
});
```

Better yet, if you need this only for syncing cursors across charts, you can use `syncWidth` option for cursor:
https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/#syncing-cursors

**Comment by senchden** [comment]
It seems like `syncWidth` together with `snapToSeries` meets my needs. Thank you very much for your help. Marking the issue as closed.
