### ISSUE TITLE
[Line series] Line disappears after zooming in

### ISSUE THREAD

**Issue by nothing-personal-gh** [amcharts/amcharts5#662]
**Bug description**

With a simple LineSeries on a DateAxis with 6-hour interval data, the line disappears after zooming into the chart with atleast 2 data points. I know the points exist there because I can see the tooltips when hovering over the missing line.

Can be reproduced here - https://codepen.io/trooper-isa/pen/oNdaQpQ?editors=0010

See GIF:

![missing-line](https://user-images.githubusercontent.com/111722528/194737994-2fdd40c0-06f5-4fc1-a80f-bb6577bc4c72.gif)

 - amCharts version - 5 latest
 - Browser and its version - Chrome latest
 - Related frameworks and their versions [e.g. Angular, TypeScript, etc.] - N/A

**Comment by martynasma** [comment]
A fix is changing this:

```
    baseInterval: {
      timeUnit: "minute",
      count: 360
    },
```

To this:

```
    baseInterval: {
      timeUnit: "hour",
      count: 6
    },
```

Base intervals in large numbers can sometimes be wonky.

**Comment by zeroin** [comment]
An alternative would be to set baseInterval to:
```
 baseInterval: {
      timeUnit: "minute",
      count: 1
    }
```

In any way groupInterval can not be shorted than your baseInterval. 
If you set baseInterval to 1 minute, the line at some point will disappear too, as you have `connect:false` set on series. If you don't want this, you should either set it to true or increase autoGapCount value of a series.

**Comment by nothing-personal-gh** [comment]
I have taken the approach of setting the `baseInterval` accordingly. That fixed the issue.
