### ISSUE TITLE
Range z-index between series

### ISSUE THREAD

**Issue by IvanMorenoMartin** [amcharts/amcharts5#664]
**Question**
Hi guys!! So I'm have a chart with 3 series, two column series and one Lines series. Just for design purposes I want a grey line at 0 but between the series, the first two columns first after that the line and after the line the Lines series so the Lines series is in top of the grey line.

My approach to draw the grey line is with a range, but with the `above: true` the grey line is at the top of everything and I want the grey line behind the Line series. Is there a way to achieve this?. Thanks in advance.
```
// Grey line at 0
    const rangeDataItem = xAxis.makeDataItem({
      value: 0,
      above: true,
    });
    const range = xAxis.createAxisRange(rangeDataItem);
    range.get('grid').setAll({
      stroke: am5.color(COLORLINE0),
      strokeWidth: 2,
      strokeOpacity: 1,
      location: 1,
    });
    range.get('label').setAll({
      forceHidden: true,
    });
```

**Environment (if applicable)**
I'm using amcharts 5

**Additional context**
Here is a screenshot of the chart. I want line series at the top, after that the grey line and after that the two Column series.
<img width="934" alt="Captura de Pantalla 2022-10-11 a las 16 14 17" src="https://user-images.githubusercontent.com/106824728/195115835-cc24fb47-3732-4f33-95cc-abb23b4a0b3c.png">

**Comment by martynasma** [comment]
Try putting the line series into a separate layer:

```JavaScript
var series = chart.series.push(am5xy.LineSeries.new(root, {
  // ...
  layer: 5
}));
```

**Comment by IvanMorenoMartin** [comment]
Yes!! Thank you very much, works perfectly 👍
