### ISSUE TITLE
How to increase / decrease text front size when zooming / dezooming bar chart ?

### ISSUE THREAD

**Issue by justine-mlss** [amcharts/amcharts5#669]
Hello,

How to increase and decrease font size of bar chart label  when we zoom in/out the chart ?

example :  https://codepen.io/Justinemlss/pen/GRdzEpQ

The font size is set to 18 and so I don't know if it's possible to adapt the fontsize, depending the zooming

Thanks
Justine

**Comment by martynasma** [comment]
You can set `fontSize` to something big, then `oversizedBehavior: "fit"`:

```
      oversizedBehavior: 'fit',
      fontSize: 25,
```
