### ISSUE TITLE
Licence link not working

### ISSUE THREAD

**Issue by osworx** [amcharts/amcharts5#67]
While you point to the license: https://github.com/amcharts/amcharts5/blob/master/LICENSE
this page does not exist.
Could you please add it - or fix the link?

thx

**Comment by martynasma** [comment]
Thank you for bringing this to our attention. The links will be fixed with the next release.

Meanwhile here's the correct link:
https://github.com/amcharts/amcharts5/blob/master/packages/shared/LICENSE
