### ISSUE TITLE
How to have the full label in bar chart ?

### ISSUE THREAD

**Issue by justine-mlss** [amcharts/amcharts5#670]
Hello, 

I have a bar chart with label inside each bar with the parameter `oversizedBehavior: 'hide'` because i don't want to have my label out of the bar.
But there is the place to put the label without zooming but I don't understand why my label isn't visible at the initial state.

img 1 : the inital state of column F & G
![initial_bar](https://user-images.githubusercontent.com/66368359/195609717-7e3886f0-3621-40a6-ac6f-405d9df15133.png)

img 2 : the first zomming state of column F & G
![zomming bar](https://user-images.githubusercontent.com/66368359/195609715-3d9991f6-8645-49fe-99ef-c7750c4b4842.png)

There is the place to store the label in the initial state, is there a way ? (with keeping `oversizedBehavior: 'hide'`)

Example: https://codepen.io/Justinemlss/pen/GRdzEpQ

Thanks
Justine

**Comment by martynasma** [comment]
Each label has default padding set to it, which counts towards determining whether it fits.

You may remove padding:

```
      paddingLeft: 0,
      paddingRight: 0,
      paddingTop: 0,
      paddingBottom: 0,
```
