### ISSUE TITLE
autoTextColor not working for HTML tooltips

### ISSUE THREAD

**Issue by bradzab0623** [amcharts/amcharts5#671]
Text in HTML tooltips do not contrast colors automatically.

Set an HTML tooltip with the color yellow (#ffff00). Notice the text stays white and is hard to see. Changing that same tooltip to text type will change the text color to black.

amcharts 5.2.29
Angular 14

**Comment by bradzab0623** [comment]
While trying to work around it, I tried adding a 'fill' adapter on the tooltip label, which does not work. I'm having to add css classes to my html dynamically based on the tooltip color.

**Comment by martynasma** [comment]
This is by design. We do not want to control any aspect of your HTML content, including colors.

**Comment by bradzab0623** [comment]
while I can understand that, since amcharts is picking the background color for us, I feel like it should at least by default choose the text color for us. But I can see a case where I may want to override that behavior for specific html elements -> not sure how to do 1 without the other.

**Comment by martynasma** [comment]
Well, it's not picking colors for you. It uses a theme.

You can override it with your specific colors:
https://www.amcharts.com/docs/v5/concepts/colors-gradients-and-patterns/#Color_sets
