### ISSUE TITLE
xAxis tooltips and line series are not synced

### ISSUE THREAD

**Issue by byseop** [amcharts/amcharts5#673]
<img width="791" alt="image" src="https://user-images.githubusercontent.com/37991768/196156618-c9e1705b-8494-433d-a8e6-dea19ca44885.png">
<img width="791" alt="image" src="https://user-images.githubusercontent.com/37991768/196156737-7b3f48f3-e68f-4ba0-b5f6-0f0d18911fd1.png">

It is not synchronized with xAxis tooltips and Line series as shown in the screenshot  
My options here
```typescript
const xAxis = chart.xAxes.push(
  am5xy.CategoryAxis.new(instance, {
    categoryField: data.axies.x,
    renderer: am5xy.AxisRendererX.new(instance, {
      // minGridDistance: 0
    }) as am5xy.AxisRenderer,
    marginTop: 10
  })
);
```
`minGridDistance: 0` option is work correctly.
<img width="794" alt="image" src="https://user-images.githubusercontent.com/37991768/196158500-36ac7b9e-db23-40c4-a914-43da2c922488.png">

But another issues arise.

<img width="794" alt="image" src="https://user-images.githubusercontent.com/37991768/196157746-a0a6cf08-af1c-452d-afea-c035a31d336e.png">

When the all of tooltips is display, It is sync. But if exist too many tooltips, It is overlap each other.

Can I synchronize the chart and tooltips with the appropriate number of tooltips?

----

[Add example](https://codepen.io/byseop/pen/RwyOmpz)
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/37991768/196325232-38723745-9029-410a-9b6c-6c248c9c3c01.png">
It happens when the window size decreases. The Korea label and Russia column are overlap.

**Comment by martynasma** [comment]
Please refer to this tutorial about positioning of axis labels:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#location-of-axis-elements

**Comment by byseop** [comment]
> Please refer to this tutorial about positioning of axis labels: https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#location-of-axis-elements

This only happens when the chart container width is not enough.
Do you mean that I should apply the options of label positioning only under specific conditions?

**Comment by martynasma** [comment]
Have you tried setting this, as per the link I suggested?

```JavaScript
var xRenderer = xAxis.get("renderer");
xRenderer.labels.template.setAll({
  multiLocation: 0
});
```

**Comment by byseop** [comment]
It works for me. Thanks!!
