### ISSUE TITLE
Responsive - Max Columns for Mobile 

### ISSUE THREAD

**Issue by IMTanuki** [amcharts/amcharts5#674]
**Use Case**
I’m trying to set up a responsive legend:
– there are only 3 items in the legend, and the legend values are only 3-4 characters long, so I’d like to have a single row.
– works fine for desktop, and some wider mobile platforms
- but on narrower mobile platforms (e.g. Galaxy S9+ iPhone SE), it resolves to 2 rows (2 items in the first and 1 item in the second row) - looks kind of funky.

No matter what I do, I can't seem to get a single 3 column row for all mobile devices! I've tried combinations of: x, centerX, dx, maxColumns, maxRows, fixedWidthGrid, maxWidth, oversizedBehavior, and fontSize:
- I can't go lower than .8rem for fontSize
- maxWidth of 10, 20, 30 all have the same effect
- oversizedBehavior will correctly truncate labels, but doesn't change the number of columns

In all other respects, the responsive wrapper works fine – I can change all other settings for mobile.

[codepen](https://codepen.io/imtanuki/pen/bGMJZOj)

**Relevant Responsive Code**
```
// adjust legend – horiz pos
legend.setAll ( {
y: null,
centerY: null,
x: am5.p50,
centerX: am5.percent ( 50 ),
dx: 0,
dy: 0,

layout: am5.GridLayout.new ( root, {
maxColumns: 3,
maxRows: 1,
fixedWidthGrid: false,

} )
} );

// adjust labels
legend.labels.template.setAll ( {
fontSize: “.8rem”,
fontWeight: “300”,

maxWidth: 20,
// notes
// – the following params don;t seem to work with multi-column grids
// oversizedBehavior: “truncate”,
// ellipsis: “…”,

} );`
```

**Comment by martynasma** [comment]
It doesn't look like your CodePen is using custom Responsive theme. You're just adding default one:

```JavaScript
		root.setThemes ( [
			am5themes_Animated.new ( root ),
			am5themes_Responsive.new ( root )
		] );
```

**Comment by IMTanuki** [comment]
Hi - thx for the quick reply. However, I believe the docum mentioned that we can modify the default responsive theme - it seems to work for all other responsive settings...

**initial responsive theme  setup:**
```
		root.setThemes ( [
			am5themes_Animated.new ( root ),
			am5themes_Responsive.new ( root )
		] );
```

**customization (after initChart and initAxes functions):**
```
function initChartResponsive () {
		responsive = am5themes_Responsive.new ( root );

		// use newEmpty for a clean responsive theme (no preset defaults)
		// responsive = am5themes_Responsive.newEmpty(root);

		responsive.addRule ( {
			relevant: am5themes_Responsive.widthL,
			applying: function () {

				chart.setAll ( {
					// layout:  root.verticalLayout, // chart is already vertical
					height: am5.percent ( 100 ),
				} );

				// adjust - xAxis labels
				xAxisRenderer.labels.template.setAll ( {
					fontSize: ".8rem",
					fontWeight: "300"
				} );

				// adjust legend - horiz pos
				legend.setAll ( {
					y: null,
					centerY: null,
					x: am5.p50,
					centerX: am5.percent ( 30 ),
					dx: 0,
					dy: 0,

					layout: am5.GridLayout.new ( root, {
						maxColumns: 3,
						maxRows: 1,
						fixedWidthGrid: false,
					} )
				} );

				// adjust labels
				legend.labels.template.setAll ( {
					fontSize: ".8rem",
					fontWeight: "300",

					maxWidth: 20,
					// note - the following params don;t seem to work with multi-column grids
					// oversizedBehavior: "truncate",
					// ellipsis: "...",

				} );
			},
			removing: function () {...
```

**Comment by martynasma** [comment]
I did see that there's a code for your custom theme. I just mentioned that your CodePen is not using it.

Your `initChartResponsive()` function creates a new instance of a `ResponsiveTheme`, but it does not actually use it in chart.

Here's a modified version, which works just fine:
https://codepen.io/team/amcharts/pen/oNdrwyg/4e8208b9d30e606be7ab312c62d40d84?editors=0010

**Comment by IMTanuki** [comment]
My CodePen _**is**_ using the responsive theme, and all other aspects of my responsive theme work.

_And your version has exactly the same issues that mine does_.

**Comment by martynasma** [comment]
I'm not sure that it does.

Here's the chart at normal with:
![image](https://user-images.githubusercontent.com/1458520/197456791-dbdaaa84-431b-43c6-a378-24331ad70e65.png)

Here's one when scaled down:
![image](https://user-images.githubusercontent.com/1458520/197456850-3f2ad26f-3296-4f57-b9cc-09368ea38029.png)

The text truncation is being applied.

Maybe I'm missing something, but it looks to me that it does exactly what you described you need it to do.

**Comment by IMTanuki** [comment]
This is getting frustrating, TBH.

The issue has NOTHING to do with text truncation.
The issue is the number of columns supported on a small form factor mobile device:
 - on mid-size mobile devices, I can display a row of 3 cells
 - on devices like a Galaxy S10+, I can only get 2 cells across (max).

The result in the example above is that I get:
- the first row  with 2 cells
- the second row with 1 cell

Which looks really kludgy. The only acceptable alternative is 3 rows of 1 cell each, which chews up the vertical space for the entire chart.

**_The fact that you keep choosing relatively wide mob devices does not demonstrate that this is not a problem._** 

I've said this now at least 6 times in this thread and emails with you. i don't know how else to explain the issue.

**Comment by sassomedia** [comment]
If the included functionality doesn't work for your specific use case, you could either put the legend in an [external container](https://www.amcharts.com/docs/v5/concepts/legend/#external-container) or build your own custom legend that is completely separate from the chart; put 3 buttons in a flexbox or style it any way you like it. On button click, just have the chart toggle the respective series on/off.

**Comment by martynasma** [comment]
OK, the following threw me off:

```
// – the following params don;t seem to work with multi-column grids
// oversizedBehavior: “truncate”,
// ellipsis: “…”,
```

Perhaps we can both work on our communication skills ;)

Do I understand you correctly now when I say that you need to avoid a two-column situation. I.e.. if three columns fit, we display three columns; if they don't we go straight to 1 column?

For that you would need to apply a responsive rule which sets `maxColumns: 1` on a legend.

**Comment by IMTanuki** [comment]
@sassomedia Thanks for your suggestion, but I don't think my use case is unusual enough to warrant writing a custom legend. Further, this issue happens with all my charts - what makes it problematic is that a 3 label legend looks really weird when the row wraps. I think this is a minor bug in the grid calculation of cell width.

**Comment by martynasma** [comment]
One other thing. Standard legend item includes a label and a value label. If you're not using the latter, it still takes up space. Might want to disable it:

https://www.amcharts.com/docs/v5/concepts/legend/#Disabling_value_labels
