### ISSUE TITLE
How I can set unchecked state of legend/series by default

### ISSUE THREAD

**Issue by jdim** [amcharts/amcharts5#677]
**Question**
How I can set unchecked initial state one of the labels/series?

<img width="1504" alt="Screenshot 2022-10-22 at 17 37 21" src="https://user-images.githubusercontent.com/8625641/197342362-d2851e9d-eea2-4ad1-855c-e446f69ff55a.png">

**Environment (if applicable)**

 - amCharts 5
 - Browser: Chrome

**Comment by martynasma** [comment]
Please refer to this tutorial:
https://www.amcharts.com/docs/v5/charts/xy-chart/series/#Pre_hiding_series

**Comment by jdim** [comment]
Thanks!

But is there a way to calculate the scale of Y axis, so that it won't include hidden series's MAX value?

https://codepen.io/dm-khabarov/pen/mdKbQWg

**Comment by zeroin** [comment]
Yes, you should add:

`series2.hide(0);`
