### ISSUE TITLE
Display Tooltip outside chart horizontally 

### ISSUE THREAD

**Issue by federico-bohn** [amcharts/amcharts5#678]
**Question**

I'm working with small micro charts, I built a tooltip based on data of many series. When mouse is hovered on middle portion of chart, I can't see tooltip arrow, that is because tooltip try to fix inside chart. I configured `tooltipContainerBounds` props, but tooltip display outside just vertically, not horizontally. Is there a way to accomplish that?
Thanks in advance.
![image](https://user-images.githubusercontent.com/12296318/197853609-f6385f54-90ca-464b-83cc-5b8d4e6bb838.png)
My code https://codepen.io/federico-bohn/pen/Vwdwdzb

**Environment (if applicable)**

 - amCharts 5.2.31
 - Chrome Version 105.0.5195.125 

 **Additional context**

**Comment by zeroin** [comment]
If a tooltip fits into the plot area, the chart shoes it in plot area. You can hack this by adding adapter for "bounds" to the tooltip and returning `undefined`, plus, setting `pointerOrientation` to `left`:

https://codepen.io/team/amcharts/pen/PoaovpE/fb214d30801a1c79ac3ab63106ad9a1d?editors=1010

**Comment by federico-bohn** [comment]
Nice!! It works!! Ty
