### ISSUE TITLE
Referencing Label and RoundedRectangle in Stand-Alone Legend Item

### ISSUE THREAD

**Issue by LumineLittlelight** [amcharts/amcharts5#680]
Hello,

Apologies, this was a follow up issue from #621.

Basically, I have a stand-alone legend that is not connected to a series. 
I want to change the label and rounded rectangle color appearance of each legend item upon toggling to make it looks like the active/inactive state (i.e being greyed out).
 
We are using Vue, thus it will go through webpack (and build minification).
Initially, I am using this method to manually change the color into gray when disabled.
itemContainer is the target of the legend item container that receive the click event.
Then, we are looking for Label and RoundedRectangle class name as the conditional logic to go through each children.

```
itemContainer.children.each((child) => {
                if (child.constructor.name == "Label") {
                  child.setAll({
                    fill: am5.color(0xcccccc),
                  });
                }
                if (child.constructor.name == "Container") {
                  child.children.each((containerChild) => {
                    if (containerChild.constructor.name == "RoundedRectangle") {
                      containerChild.setAll({
                        fill: am5.color(0xcccccc),
                        stroke: am5.color(0xcccccc),
                      });
                    }
                  });
                }
              });
```

The solution above works under development (i.e webpack serve).

However, when we use webpack build, we no longer able to refer to class name due to minification on webpack (specifically uglify). This causes the logic to find the Label and Container (i.e xxx.constructor.name) no longer works.

Below is the screenshot of console.log(itemContainer) variable, as you can see now the constructor become "t" or "e" due to webpack minification.
![itemcontainer build](https://user-images.githubusercontent.com/112674127/198532004-f43a5935-0ca2-4d0c-b8bb-ec9dff5aed85.JPG)

Is there an alternative way to find the Label child and the RoundedRectangle child on the legend container? Finding the relevant children is quite difficult without class name.

Your help will be very appreciated.
Thank you.

**Comment by xorspark** [comment]
We provide the `className` property for this sort of use case. You can use that instead of `constructor.name`. 

https://www.amcharts.com/docs/v5/reference/label/#className_property
https://www.amcharts.com/docs/v5/reference/container/#className_property
https://www.amcharts.com/docs/v5/reference/roundedrectangle/#className_property

**Comment by LumineLittlelight** [comment]
Ah, got it. Thank you for the alternative. Closed.
