### ISSUE TITLE
How do you get rid of grid lines in a XY chart?

### ISSUE THREAD

**Issue by frankiewag** [amcharts/amcharts5#681]
How do you get rid of the grey grid lines in a XY chart?

<img width="318" alt="Screenshot 2022-10-28 at 14 19 29" src="https://user-images.githubusercontent.com/1587675/198586434-68423c08-d87d-49c4-9218-aef70e46f513.png">

How would you go about doing it, in this codepen example (a clone from the demos).
https://codepen.io/fwagnerius/pen/mdKJBaw

**Comment by xorspark** [comment]
You can set `visible` to false on the axes' grid template.

```
xAxis.get('renderer').grid.template.set('visible', false)
yAxis.get('renderer').grid.template.set('visible', false)
```

**Comment by frankiewag** [comment]
Thank you so much! It works!
