### ISSUE TITLE
Create NodeNext Module Resolution ESM Distribution

### ISSUE THREAD

**Issue by bestickley** [amcharts/amcharts5#682]
**Question**

I'm trying to use @amcharts/amcharts5 with "moduleResolution" of NodeNext within my tsconfig.json. This has been available since TS 4.7. When I do this, I'm getting type declaration errors from amCharts. Can an ESM distribution of amCharts5 be created utilizing the new exports map functionality? In order for this to work, the "type" key within package.json must be "module" and an "exports" would explicitly list out each export under the package path "@amcharts/amcharts5/*". Alternatively you could use a sub-path wildcard to export all files at root level

**Environment (if applicable)**

amCharts 5
TS >= 4.7

**Additional context**
Current workarounds are to use .js extensions:
```ts
import {
  PieChart as amPieChart,
  PieSeries,
} from "@amcharts/amcharts5/percent.js";
```
or for default exported values, use `.default` like below:
```ts
import Animated from "@amcharts/amcharts5/themes/Animated.js";
...
Animated.default.new(root);
```
UPDATE: default export for Animated works in TS but doesn't work at runtime. Need to do:
```ts
import _Animated from "@amcharts/amcharts5/themes/Animated.js";
const Animated = _Animated as unknown as typeof _Animated.default;
```
See https://github.com/microsoft/TypeScript/issues/50690

**Comment by bestickley** [comment]
Errors with NodeNext "moduleResolution":
![image](https://user-images.githubusercontent.com/35735118/198712823-66857b2d-a538-4473-b72b-d03938eaa28a.png)

**Comment by bestickley** [comment]
For the record, this works in NodeNext environment:
```ts
import { p50, p100, Root, Tooltip, Label } from "@amcharts/amcharts5";
```

**Comment by martynasma** [comment]
Thanks for sharing the solution!

**Comment by bestickley** [comment]
@martynasma, you're welcome! Anything I can do to help get this prioritized? Have you considered creating separate ESM/CJS distributions? It's common practice amongst node package authors. I understand you're probably very busy but I think this will be helpful moving forward as more of the community moves to ESM.

**Comment by bestickley** [comment]
Additional guidance: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by Pauan** [comment]
Our code is already fully compatible with ES6 modules, but you must use a bundler (like Webpack or Rollup).

We don't support running amCharts in Node. And our dependencies are incompatible with the NodeNext resolution, so even if we changed our code it still wouldn't work.

Why are you using NodeNext resolution?

Also, if you are using NodeNext then you must use the `.js` extension, that is expected because that's how NodeNext works.

**Comment by bestickley** [comment]
@Pauan, yes, I'm using a bundler too (Rollup through Vite). I'm not running amCharts in Node, but I am bundling amCharts in Node.

>And our dependencies are incompatible with the NodeNext resolution
Understood. It may take a while for the ecosystem to adapt.

I'm using NodeNext resolution because it's the new standard for using ESM within Node (which is used to bundle amCharts). To quote TS [docs](https://www.typescriptlang.org/docs/handbook/esm-node.html): "however, support for ESM in Node.js is now implemented in Node.js, and the dust has begun to settle. That’s why TypeScript brings two new module and moduleResolution settings: node16 and nodenext"

If using NodeNext and importing a dependency that has an `"exports"` key in the package.json with a file specifier that already has a .js in it, you do not need to use the .js extension. See example:
```json
{
  "name": "my-package",
  "exports": {
    ".": "./lib/index.js",
    "./lib": "./lib/index.js",
    "./lib/*": "./lib/*.js",
    "./feature": "./feature/index.js",
    "./feature/*": "./feature/*.js",
  }
}
```
The [docs](https://nodejs.org/api/packages.html#package-entry-points) do say they recommend against extensionless exports which speaks to your point though.

Why use `"exports"? From Node.js [docs](https://nodejs.org/api/packages.html#package-entry-points): "For new packages targeting the currently supported versions of Node.js, the ["exports"](https://nodejs.org/api/packages.html#exports) field is recommended."

The biggest challenge I've had with amCharts with NodeNext is default exports. My current workaround as mentioned above is having to do this to import themes:

```ts
import _Animated from "@amcharts/amcharts5/themes/Animated.js";
const Animated = _Animated as unknown as typeof _Animated.default;
```

I'd imagine that amCharts could update their package.json#exports field to accomodate NodeNext but I'm admittedly not aware of all the intricacies of the library.

Thank you for taking the time to read this issue. I think NodeNext is the way forward for TS and bundlers in Node.js world and I'd like to see amCharts move forward to if time allows it.

**Comment by Pauan** [comment]
> I'm using NodeNext resolution because it's the new standard for using ESM within Node (which is used to bundle amCharts).

It's the new standard for running ES6 code in Node.

You don't need it if you're bundling, because you're not running the ES6 code in Node, you're running it in the browser.

> More generally, I think the issue here is default exports.

The issue is that you are using a resolver which is intended for Node, but you're not running your code in Node.

If a library is designed to be used in bundlers (like amCharts), then it will not work with Node's resolution algorithm.

> I'd imagine that amCharts could update their package.json#exports field to accomodate NodeNext but I'm admittedly not aware of all the intricacies of the library.

That is for libraries which are running in Node, but amCharts does not run in Node.

**Comment by bestickley** [comment]
>That is for libraries which are running in Node, but amCharts does not run in Node.

Most frontend libraries I'm using are compatible with NodeNext or are using `"exports"` in package.json so I don't think it's a crazy request even for a library that doesn't run in Node.js. I understand this is likely low priority, but could we leave this issue open to see if it garners more support/is desired by the community?

**Comment by Pauan** [comment]
Supporting NodeNext is a lot more than just adding `"exports"` to package.json, we would need to make changes to all of the files in amCharts. It's a big change. And it's a change that *only* affects people who are incorrectly trying to run amCharts in Node. And even if we made those changes, our dependencies are not compatible with NodeNext, so it will still break.

**Comment by bestickley** [comment]
Understood. I'm not trying to "run amCharts in Node", but I see your point. I'm _building_ my web app in Node.js. Thanks for doing research into this!

**Comment by Pauan** [comment]
> I'm building my web app in Node.js.

Yes, but that's irrelevant. NodeNext is for running your code in Node without a bundler, since you're using a bundler you don't need it.
