### ISSUE TITLE
Labels too close located

### ISSUE THREAD

**Issue by t3946** [amcharts/amcharts5#684]
I made xychart with labels and now have a problem. Two labels first on x axis and first on y axis too close located. I have tried to hide one but can't. 
![Screenshot_2](https://user-images.githubusercontent.com/26932760/199726128-0b7422e9-7d32-4578-b74f-34e4b391b5c8.jpg)

**Comment by zeroin** [comment]
There is an AxisLabel setting for that - minPosition. So if you set it to 0.05, it would mean that labels within first 5% of the axis will be hidden:

`xAxis.get("renderer").labels.template.set("minPosition", 0.05);`

https://www.amcharts.com/docs/v5/reference/axislabel/#minPosition_setting
https://www.amcharts.com/docs/v5/reference/axislabel/#maxPosition_setting

**Comment by t3946** [comment]
> There is an AxisLabel setting for that - minPosition. So if you set it to 0.05, it would mean that labels within first 5% of the axis will be hidden:
> 
> `xAxis.get("renderer").labels.template.set("minPosition", 0.05);`
> 
> https://www.amcharts.com/docs/v5/reference/axislabel/#minPosition_setting https://www.amcharts.com/docs/v5/reference/axislabel/#maxPosition_setting

Thanks. It helped me.
