### ISSUE TITLE
setThemes method flips labels in chart Axis

### ISSUE THREAD

**Issue by emmanuelolivo1002** [amcharts/amcharts5#685]
I'm using amCharts5 on a React app that has a dark/light mode switch. If users change the mode, whose value is saved in the `mode` variable, it will trigger the following hook that will take the chart element and set its theme to the corresponding one.

```
  useLayoutEffect(() => {
    if (ref.current) {
      const { root } = ref.current;
      root.setThemes(
        mode === "dark"
          ? [am5themes_Responsive.new(root), am5themes_Dark.new(root)]
          : [am5themes_Responsive.new(root), am5themes_Animated.new(root)],
      );
    }
  }, [mode]);
```

However when the `setThemes` function run, for some reason the labels in the charts' Axis Range labels flip horizontally.

#### Dark Mode 
<img width="535" alt="image" src="https://user-images.githubusercontent.com/17680221/199978321-c84d091b-66df-4cc2-924b-386b65de2120.png">

#### Light Mode 
<img width="570" alt="image" src="https://user-images.githubusercontent.com/17680221/199978436-dae24108-65c6-4027-a0c3-1e1cb400b0d8.png">

**Comment by martynasma** [comment]
I'm afraid amCharts 5 is not designed to support dynamic switching of themes.

You will need to re-create the whole chart.
