### ISSUE TITLE
Revert Value Axis min and max to be automatically calculated

### ISSUE THREAD

**Issue by LumineLittlelight** [amcharts/amcharts5#686]
Hi,

May I check if we had defined min and max values of value axis previously, how do we revert the value axis back to make the min-max value automatically calculated?

Appreciate your kind help :)
Thank you.

**Comment by zeroin** [comment]
You should set min and max to undefined:

`yAxis.set("min", undefined)`
`yAxis.set("max", undefined)`

**Comment by LumineLittlelight** [comment]
Ah got it. Thanks!
