### ISSUE TITLE
Using Tootlip's background template fields

### ISSUE THREAD

**Issue by forJihye** [amcharts/amcharts5#688]
**Question**

Hello !

I'd like to apply the background color of the tooltip differently by value.

So I added the code, but it doesn't work.
`tooltip.get('background')setAll({templateField: "tooltipSettings"};`

Is there any other way?

Codesanbox Example
https://codesandbox.io/s/wild-wave-xvj9pr?file=/src/AmChart.js

**Comment by martynasma** [comment]
`templateField` works for series items. Tooltip is not a series item, and therefore it won't work.

What you can do, is to use an adapter:

```JavaScript
tooltip.get("background").adapters.add("fill", (fill, target) => {
  return target.dataItem && target.dataItem.dataContext ? target.dataItem.dataContext.tooltipSettings.fill : fill;
});
```

**Comment by forJihye** [comment]
Perpect !!
thank you so much 😄
