### ISSUE TITLE
Pre-zoom for multiple series chart

### ISSUE THREAD

**Issue by jawaher1** [amcharts/amcharts5#69]
How to pre-zoom multiple series charts and keep yaxis autoscaling activated. The problem I am facing is that the prezoom is done but for only one series which makes the graph uncompleted.
Here is the code : 
   series.events.on("datavalidated", (ev) => {
      this.dateData = this.dateData.reverse()
      ev.target.get("xAxis").zoomToDates(new Date("2021-10-24"),new Date("2021-10-30"));
    });

**Comment by martynasma** [comment]
Well, in amCharts 5, data parsing is not asynchronous. This means that by the time "datavalidated" kicks in for one series, some other series haven't even began parsing its data, which should not, but may lead to some anomalies when zoom starts immediately.

You may want to delay zoom operation until all of your series report "datavalidated".

Or, if you could post your chart on CodePen or jsFiddle, we could take a look if maybe this is somehow solvable differently.
