### ISSUE TITLE
Question: Is there a way to configure text escaping?

### ISSUE THREAD

**Issue by jon-appinio** [amcharts/amcharts5#691]
First, thank you so much for this great tool and support! 🙇 

I will explain first the context of the issue we had and then the question we would like to ask.

## Our context
We have a page in our product which contains many different charts types, each one with each one separated component and functions. This page has dynamic content that gets render in the charts.

We encounter that one version of this page, for an important client, was completely frozen with no error in the console. Really difficult to debug. After many hours debugging it we realise we had  `some texts we used in the charts had brackets`. 
Example text: `HBO MAX [USA & BRA]`

After removing those from the data source the chart rendered beautifully.

Then `we found this entry about Escaping` in amCharts5's documentation about the need of escape those brackets in the text we use with the charts, which `explained the issue we had`: 
https://www.amcharts.com/docs/v5/concepts/formatters/text-styling/#Escaping

## The problem we're facing
`We came up with a temporary solution of escaping the texts we used` with the different charts.
But it requires us to escape every single text we want to pass to amCharts. 
And as we have all content dynamic and many chart-components this gets a bit `difficult to maintain for us`.

Also important thing is **for text-styling there may be special [blocks](https://www.amcharts.com/docs/v5/concepts/formatters/text-styling/#Available_style_codes)** which makes for us really hard to escape the text without breaking the styles.

# Our Question
`- Is there any way to customise the escaping mechanism of AmCharts on a project/root configuration level?`

Thank you so much in advance! 🙏

**Comment by martynasma** [comment]
Well, you can use `Label` setting [`ignoreFormatting: true`](https://www.amcharts.com/docs/v5/reference/label/#ignoreFormatting_setting) to completely disable in-line formatting.

However, if you are using in-line formatting, too, that won't work for you.

Not sure what else to suggest, beyond the escaping of brackets :(

**Comment by jon-appinio** [comment]
Thank you for your answer @martynasma 
We think we may still need in-line formatting in some cases.  So we don't think we can simply use `ignoreFormatting`.
But we will investigate on that. Thank you!

**Comment by jon-appinio** [comment]
@martynasma Is there a way we can keep the formatting and let **amcharts** do the escaping before applies the formatting?

**Comment by martynasma** [comment]
Maybe you can use an [adapter](https://www.amcharts.com/docs/v5/concepts/settings/adapters/).

**Comment by jon-appinio** [comment]
@martynasma is there a way to create a generic adapter? Or needs to be for each chart/template?
