### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SteviZiu** [amcharts/amcharts5#692]
How can I import amchart5 library on a ReactJS application that uses only Javascript (no typescript used) ? The following error is throwns: ROOT is undefined

**Comment by martynasma** [comment]
Why not just use JS version of amCharts included via `<script>`?

```
<script src="https://cdn.amcharts.com/lib/5/index.js"></script>
<script src="https://cdn.amcharts.com/lib/5/xy.js"></script>
<script src="https://cdn.amcharts.com/lib/5/themes/Animated.js"></script>
```
