### ISSUE TITLE
AMcharts 5 Stacked and clustered chart

### ISSUE THREAD

**Issue by MeharHaris** [amcharts/amcharts5#693]
I'm facing issue, if I don't have value in 2021, then the series should be collapsed. I don't want to see blank area.

https://www.amcharts.com/demos/stacked-clustered-column-chart/

![3](https://user-images.githubusercontent.com/104983855/201507490-ad01671e-e5e2-4fac-8f69-bceeed9cb834.png)

Pleased help me.
if anyone can help then please provide codepen link.

**Comment by martynasma** [comment]
There's no way to collapse an empty space in a single category, I'm afraid. Sorry.

**Comment by MeharHaris** [comment]
then how can I hide it?

**Comment by martynasma** [comment]
Well, you can't. Each category is reserved the same width as the others.

**Comment by MeharHaris** [comment]
Ok noted,

**Comment by MeharHaris** [comment]
Ok noted
