### ISSUE TITLE
Series in XYChart LineSeries doesn't appear

### ISSUE THREAD

**Issue by ValL10** [amcharts/amcharts5#694]
Hi, 

My question is why the strokes and the fill in my xyChart/LineSeries/CategoryAxis doesn't appear? 

All things run fine, but the line series doesn't appear in the graph

**Comment by ValL10** [comment]
Thank you for replying, but it's running fine now.
Very Sorry

**Comment by DouglasNel** [comment]
> Thank you for replying, but it's running fine now. Very Sorry

Hi there did you change anything? This is happening to me.

Rerpoduced in code pen.

https://codepen.io/FryDouglas/pen/abamoRB
