### ISSUE TITLE
Reorder legend dinamically

### ISSUE THREAD

**Issue by JuniorDiasOliveira** [amcharts/amcharts5#695]
**Question**

Hi

I have a "line chart with data being added each 1sec" with multiple series, which means I also have a legend with multiple values.

I wonder if it's possible to dinamically reorder the legend items according to the serie position in the chart.

I know that the following code do the job:
`legend.children.moveValue(legend.itemContainers.values[0], 1);`

But I don't actually know where I'm going to find the `legend.itemContainers.values[item]` inside the series container.

**Environment (if applicable)**
Not applicatble

**Additional context**
No needed

**Comment by martynasma** [comment]
Well, why not push series into `legend.data` at the same time the series is pushed into `chart.series`?

This way the order of the legend will resemble the order of series in the chart.

Or am I missing something?

**Comment by JuniorDiasOliveira** [comment]
@martynasma I tried that way, for some reason it causes a bug (nothing appears in the console, but the legend disappears)

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
