### ISSUE TITLE
how to change active circle fillGradient in ForceDirected?

### ISSUE THREAD

**Issue by BratikWWW** [amcharts/amcharts5#696]
Hi! Can I change the fillGradient of a circle when I click on it and change it back?

**Comment by BratikWWW** [comment]
`series.circles.template.adapters.add('fillGradient', function(fill, target) {      
                    if(!target.dataItem.get('disabled')) {                      
                        return gradient;
                    }else{
                        return negativeGradient;
                    }
});`
this only works on first init

**Comment by martynasma** [comment]
I'd say you create "active" state for your circles. Also set `toggleKey: "active"` so that active state is toggled on and off on click.

https://www.amcharts.com/docs/v5/concepts/settings/states/
