### ISSUE TITLE
Square brackets passed as chart data to the XY chart make the whole web page unresponsive

### ISSUE THREAD

**Issue by ValentinTyanov** [amcharts/amcharts5#698]
Hey,

I've stumbled upon a very odd issue. The XY chart seems to malfunction with a specific type of input. Might be the Column Series or some other component as well but it definitely seems to be one of the @amcharts/amcharts5/xy imports.

In some situations, when square brackets are passed as part of the chart data, it seems to cause a problem as the chart is not visualized and the whole page becomes unresponsive (you can't even open DevTools). 

- Changing either of the square brackets to any other symbol resolves the problem
- Using curly braces or parentheses instead of square brackets is fine
- Changing the content inside the brackets doesn't seem to matter (e.g. [00] instead of [TEST] also breaks)
- Moving the square brackets to a different index seems to resolve the issue (although not always, feels random)

I've attached screenshots from VS Code with examples where I've confirmed the input causes an issue (pictures named input_malfunction_x) and another screenshot where the input is fine (input_working). 

I've also attached an implementation which is interacting with amCharts5
This happens with all browsers.

![endless dashboard spin](https://user-images.githubusercontent.com/62349117/202435194-8be73ca6-eb3e-40f3-aefe-c0856df731f0.png)
![input_malfunction](https://user-images.githubusercontent.com/62349117/202444308-c27db4f1-baf6-4ee0-af79-60b3e216b54a.PNG)
![input_malfunction_2](https://user-images.githubusercontent.com/62349117/202444310-3b217073-b543-4504-a135-7851e1dc4afe.PNG)
![input_malfunction_3](https://user-images.githubusercontent.com/62349117/202444313-352d2379-4744-4225-aca9-8b12d6f970bb.PNG)
![input_working](https://user-images.githubusercontent.com/62349117/202444315-e9bc7885-5873-4e80-aea9-bfeaa688b202.PNG)
[bandwidth-chart.component.txt](https://github.com/amcharts/amcharts5/files/10031500/bandwidth-chart.component.txt)
[chart-config.service.txt](https://github.com/amcharts/amcharts5/files/10031501/chart-config.service.txt)
[task-bandwidth.component.txt](https://github.com/amcharts/amcharts5/files/10031502/task-bandwidth.component.txt)

**Comment by martynasma** [comment]
Square brackets denote in-line formatting in amCharts labels:
https://www.amcharts.com/docs/v5/concepts/formatters/text-styling/

Having stuff in there that does not resolve to something meaningful, format-wise, might produce some undesired results.

There are two things you can do:

1) Escape square brackets:
https://www.amcharts.com/docs/v5/concepts/formatters/text-styling/#Escaping

2) Disable in-line formatting:
https://www.amcharts.com/docs/v5/reference/label/#ignoreFormatting_setting

**Comment by ValentinTyanov** [comment]
Thanks for the quick response and for pointing that out!

**Comment by mbektchiev** [comment]
@martynasma I think that this issue shouldn't be dismissed so easily.  Sending invalid input should never crash the web browser page.

**Comment by martynasma** [comment]
Fair enough. Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by ValentinTyanov** [comment]
I'll try to do that soon (hopefully tomorrow)

**Comment by ValentinTyanov** [comment]
@martynasma I couldn't reproduce it in isolation. Unfortunately, I don't have any more time to spend on this so I will not be proceeding further. Thanks for the help :)
