### ISSUE TITLE
Defining a custom Tooltip object on RoundedRectangle doesn't work

### ISSUE THREAD

**Issue by willjosefi** [amcharts/amcharts5#699]
**Bug description**

I'm trying to use a custom Tooltip object on an XY Chart but seems like the configuration is just skipped. It only works if I add tooltipText

```javascript
series.columns.template.setAll({
    tooltip: am5.Tooltip.new(root, {
        labelText: 'from tooltip object'
    }),
    tooltipText: ' from tooltipText'
});
```

I created a codepen using as base one of your demos: https://codepen.io/willjosefi/pen/xxzPpGG
- Hover your mouse above one of the bars, and you will see that the Tooltip which shows up is the one from `tooltip` object.
- comment out line 74 `tooltipText` you will see that no tooltip shows up

**Environment (if applicable)**

 - amCharts version 5.2.33
 - Chrome Browser 107

**Comment by martynasma** [comment]
You can specify tooltip content via `tooltipText`. The rest of the tooltip customization can come via custom tooltip object.

Does that make sense?
