### ISSUE TITLE
Border between Europe and Asia using  am5geodata_continentsLow

### ISSUE THREAD

**Issue by arirangz** [amcharts/amcharts5#700]
**Bug description**

Using am5geodata_continentsLow, we can still see a slight gap (margin or stroke) between Asia and Europe even with fill and stroke set with the same color :
![image](https://user-images.githubusercontent.com/1193727/202847090-ee9f851e-2938-4319-afb5-ce718a61e4b5.png)
Codepen:
https://codepen.io/anthonyupto/pen/jOKajyL

**Comment by martynasma** [comment]
Must be the resolution thing. I don't see the gap.

That being said, try increasing polygon border width:

```JavaScript
countrySeries.mapPolygons.template.setAll({
  tooltipText: "{name}",
  interactive: true,
  strokeWidth: 1
});
```

(default is `0.5` I think)

**Comment by arirangz** [comment]
Thanks, it's working this way
