### ISSUE TITLE
minRadius and maxRadius with Pack series

### ISSUE THREAD

**Issue by birkasbence** [amcharts/amcharts5#702]
Hi

Is there a way to have a min and max radius settings in a Pack series just like in a Force-directed series?
Like in the example here: https://www.amcharts.com/docs/v5/charts/hierarchy/force-directed/#Sizing_nodes

**Comment by martynasma** [comment]
No, I'm afraid. The idea behind a Pack diagram is to display relations of composite values. Having chart limit sizing the circles would completely derail it.

You can add some padding to the nodes, though:
https://www.amcharts.com/docs/v5/reference/pack/#nodePadding_setting

**Comment by birkasbence** [comment]
Thank you for the answer. I get what you're saying, but it's really hard to hover on some of the really small circles to get the tooltip. The padding helps a little, but doesn't solve the problem.

**Comment by birkasbence** [comment]
I imagine it like this:
-values less than someValue --> minRadius = X px
-values more than someOtherValue --> maxRadius = Y px
-values between --> normal behavior

**Comment by martynasma** [comment]
This is inviting other problems. What if a bunch of small values with forced minRadius start overlapping and making each other not just unhoverable, but even invisible.

**Comment by birkasbence** [comment]
Hmm I thought that they were drawn dynamically so they would never overlap.

**Comment by martynasma** [comment]
They are drawn dynamically, but sized according to value so they fit exactly within each other.

**Comment by birkasbence** [comment]
Could it be sized according to minRadius, maxRadius and value?

**Comment by martynasma** [comment]
Ok, hypothetical situation: we have space for 60 pixels and two circles that go into it.

Let's say minRadius is 15, which would may all circles 30 pixels across at least.

One circle has value 100, the other 1.

What would you happen? Both circles be sized at 30 pixels so they fit. This is very wrong since size perception is now off dramatically.

Or have one circle at 59 pixels and the other at 30?

Size is off again, but now we have overlapping scenario.

The way I see it, there's no correct way to achieve what you need.

**Comment by birkasbence** [comment]
I see, fair point. What do you think about adding a minPX, and adding that number of px to the radius? It would be better to compare 8px vs 15px than 3px vs 10px. This way we can keep the proportions too.

**Comment by martynasma** [comment]
How would that be different than `nodePadding` (which can also be negative)?

**Comment by birkasbence** [comment]
The problem might be on my part, but `nodePadding` doesn't make the circles any bigger, just the space between them. So hovering the small ones is still an issue.

<img width="395" alt="Screenshot 2022-11-28 at 17 59 34" src="https://user-images.githubusercontent.com/53494862/204337121-e6a9dcc6-5f5d-4009-af30-6bb8aa01d58c.png">

**Comment by martynasma** [comment]
Try `nodePadding: -10`.

**Comment by martynasma** [comment]
Looks unhealthy, but kinda cool :)

Not sure what else to suggest. Sorry.

**Comment by birkasbence** [comment]
Well I made my suggestions. Thank you anyway.
