### ISSUE TITLE
amCharts5 - fix map resolution on mobile screen

### ISSUE THREAD

**Issue by ABr0wne** [amcharts/amcharts5#703]
I've created a amCharts 5 map for my website using the plugin for Wordpress. It looks great on desktop but not on mobile. The resolution looks really poor (the outlines of the countries are thick and blurry).

Is there a way to make the map responsive so it looks good on all screen sizes? I've set the responsive theme but not sure how that can be used for this issue. I've searched the amCharts 5 documentation and haven't found a solution yet.

Include what you have tried so far. Best of all, post your current chart online.

This is the code - 
https://codepen.io/ABr0wne/pen/wvXxQYQ

And this is a screenshot of how it looks on mobile - 
![IMG_9748](https://user-images.githubusercontent.com/119416082/204524717-2c9cfe6d-d275-4c67-8d06-a2705f69de9e.PNG)

**Comment by martynasma** [comment]
Try this:
https://www.amcharts.com/docs/v5/getting-started/root-element/#Safe_resolution

**Comment by ABr0wne** [comment]
@martynasma that worked, thanks!!
