### ISSUE TITLE
Possible memory leak in property change event handlers

### ISSUE THREAD

**Issue by senchden** [amcharts/amcharts5#706]
Hello.
I am using event handlers for property change events - specifically `.onPrivate("selectionMin", ...)` and `.onPrivate("selectionMax", ...)`. I am calling a callback in the event handlers and I am updating series data dynamically. With every data update there seems to be a memory leak. Is this and intended behaviour and I have just missed something or is it a bug? Eventually I have settled on disposing those event handlers before updating series data and re-adding event handlers after that, but that doesn't seem like a clean solution to me. I have used amcharts version 5.2.35 and Chrome version 107.0.5304.122.
Thank you in advance.

**Comment by martynasma** [comment]
Can you clarify how you are using those events? They're set on an axis, not series, right?

Do you also update axis when you update the series? Also, can you please clarify what that "update" includes?

If you could provide a small repro case that would go a great length towards figuring this out.

**Comment by senchden** [comment]
After creating a minimal sample, I was unable to reproduce a memory leak. So that is probably not an error in amcharts after all. That said, I would like to see an event that would return both (start/end) selection bounds after cursor selection ends, also without using private properties (any interval value change in tick handler caused my "selectionMin"/"selectionMax" handler to fire without user interaction)

**Comment by senchden** [comment]
I get there is nothing really hacky about it, but ideally I would like to have an option to react only to user selecting a range with a cursor (maybe even independently of the axis - like a property on the cursor itself). `selectionMin` and `selectionMax` could also be unfortunately changed if `min`/`max`/`extraMin`/`extraMax` (and possibly other axis properties) are being changed. By the way, just now I tried using event handlers for  `selectionMinFinal` and `selectionMaxFinal` ant their event handlers are not being called at all (possibly because I have not enable an animated theme).

**Comment by martynasma** [comment]
Yes, you might be right about animation theme.

Not sure what else to suggest :(

**Comment by senchden** [comment]
Ok. Then I will be closing this issue and instead open a new one with the feature proposal about the XYCursor I have explained above.

**Comment by senchden** [comment]
This is the link to the feature request issue: https://github.com/amcharts/amcharts5/issues/710
