### ISSUE TITLE
amcharts5 with Vue3 Composition API

### ISSUE THREAD

**Issue by TangoPJ** [amcharts/amcharts5#707]
Is it possible to use amcharts5 with Vue3 composition API?
Thank you

**Comment by xorspark** [comment]
amCharts5 is framework agnostic, so it should just work, regardless of what API you use in Vue. The [same caveats from our docs](https://www.amcharts.com/docs/v5/getting-started/integrations/vue/#Important_note) still apply.

Here's a basic chart built from the hello world sample from their docs: https://stackblitz.com/edit/vitejs-vite-yfb14k?file=src/components/HelloWorld.vue

**Comment by TangoPJ** [comment]
@xorspark Hello, thank you very much, it worked for me :)
