### ISSUE TITLE
Scrollbar Grip customization

### ISSUE THREAD

**Issue by jawaher1** [amcharts/amcharts5#71]
Is it possible to customize the scrollbar grips like in amcharts4? Or the default icon and styling is the only choice?

**Comment by martynasma** [comment]
Yes, grips are buttons and can be customized any way you want by accessing scrollbar's `startGrip` and `endGrip` that hold [`Button`](https://www.amcharts.com/docs/v5/reference/button/) objects.

https://www.amcharts.com/docs/v5/concepts/common-elements/buttons/

**Comment by jawaher1** [comment]
Thank you, this actually works perfectly for my needs.
