### ISSUE TITLE
[Feature request] XYCursor range selected event

### ISSUE THREAD

**Issue by senchden** [amcharts/amcharts5#710]
Currently to be able to get the range selected by an XYCursor you have to rely on the `selectionMin`/`selectionMax` private properties on the respective range. However these properties could also be change if other axis properties are being set - like `min`/`max`/`extraMin`/`extraMax`, meaning event handlers for `selectionMin`/`selectionMax` would be called when it is not expected. That's why I'm proposing to add a new event directly on XYCursor, something like "XrangeSelected"/"YrangeSelected", that would return an object with both properties, like `{start: Number, end: Number}`.

**Comment by zeroin** [comment]
XYCursor has events `selectstarted` and `selectended` which you can use for this purpose. start and end positions can be get using positionX and positionY private settings:

```
cursor.events.on("selectstarted", (e)=>{
    console.log(cursor.getPrivate("positionX"))
    console.log(cursor.getPrivate("positionY"))
})

cursor.events.on("selectended", (e)=>{
    console.log(cursor.getPrivate("positionX"))
    console.log(cursor.getPrivate("positionY"))
})
```

**Comment by senchden** [comment]
Great. Looks like the thing I wanted, thank you.
