### ISSUE TITLE
Canvas not getting left and top position style properties set appropriately since 5.2.39

### ISSUE THREAD

**Issue by swack-cybernet** [amcharts/amcharts5#714]
Since amCharts 5.2.39, a bad interaction between all charts and bootstrap containers has occurred, causing chart canvases to be rendered without setting the left and to position style properties to 0px, as was the behavior before.

The difference is illustrated here: https://jsfiddle.net/oyv2aqxu/ (5.2.38) and https://jsfiddle.net/hoxudr9q/ (5.2.40).

**Comment by martynasma** [comment]
Thanks for the heads up! We're looking into it.
