### ISSUE TITLE
1 tooltip for all stacked columns

### ISSUE THREAD

**Issue by OdysseasMas-lw** [amcharts/amcharts5#715]
**Question**

In amcharts4 we had figured out a way to have 1 tooltip per stacked column that contains information from every stacked column. So, if one hovered over the red column (in the screenshot below) a tooltip over the yellow column would still show up (with aggravated info from all columns).
![Screen Shot 2022-12-08 at 2 00 27 PM](https://user-images.githubusercontent.com/73153370/206576455-27ab9e88-d5d7-4924-82cd-e1d48a2c471a.png)

This was achieved by setting a `tooltipText` adapter on a series obtained like so:
`const series = chart.series.values[chart.series.length - 1]`

Somehow, with the above (*I think*) the tooltip was restricted to only show at the "top" column in each stack. Hovering on any column below it would still prompt it to show at the same place.

In amcharts 5, a similar implementation will not trigger a tooltip when hovering over any column other than the one that was attached to a tooltip.

Is there a proper way to implement this?

Here is an illustration of the above in amcharts 4 and essentially what we'd like to achieve in amcharts 5.
https://user-images.githubusercontent.com/73153370/206646568-1a65a2be-f599-4efc-9dba-245aa39945ae.mov

**Comment by martynasma** [comment]
How about using [`maxTooltipDistance`](https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/#limiting-number-of-tooltips-shown-at-a-time) to make tooltip trigger on the closest column to the pointer?

Here's an example:
https://www.amcharts.com/docs/v5/tutorials/combining-tooltip-values-from-multiple-series/

You can use adapters to achieve the same in V5, too. It just seems to me that using XYCursor + maxTooltipDistance is much cleaner/easier solution.
