### ISSUE TITLE
Pinching/Zooming in charts is blurry

### ISSUE THREAD

**Issue by OdysseasMas-lw** [amcharts/amcharts5#716]
Pinching any chart in amcharts 5 is blurry
https://user-images.githubusercontent.com/73153370/206577834-3fede56d-d47f-4119-b01f-8b23f65d7eaa.mov

Amcharts4 did not seem to have any issues like that
https://user-images.githubusercontent.com/73153370/206577954-898e7e5c-b9f3-4a62-baad-b4d71e2a3aed.mov

Assuming this is because of [Canvas API](https://stackoverflow.com/questions/38746737/canvas-grid-gets-blurry-at-different-zoom-levels)?

**Comment by martynasma** [comment]
Well, v4 used SVG, which is vector. v5 is based on canvas, which is bitmap.

I'm not entirely sure what yo mean by pinch-zooming though.

Zooming the page should change the resolution, and the charts should also redraw themselves for the new resolution.

Also, if you are using Safari (which is very unfriendly to canvas-based apps), take a look here:
https://www.amcharts.com/docs/v5/getting-started/root-element/#Safe_resolution

**Comment by OdysseasMas-lw** [comment]
To clarify, by "pinch" or "zooming-in" I mean an action similar to a Macbook user "pinching" their trackpad. This was observed on Chrome.

**Comment by martynasma** [comment]
Gotcha. I don't think there's much that can be done about that, I'm afraid :(

**Comment by OdysseasMas-lw** [comment]
Yes, makes sense. Thank you!
