### ISSUE TITLE
Straighten US State Map

### ISSUE THREAD

**Issue by mediagirl** [amcharts/amcharts5#717]
I can't for the life of me figure out how to straighten my US state map. Can you direct me to the setting? I have search the docs extensively but I can't find the settings.

The example on your website which uses a Florida map is similarly tilted/rotated.

MAP SCREENSHOT
https://dl.dropboxusercontent.com/s/34b3u58pns3ovxz/2022-12-13_17h38_12.png?dl=0

**Comment by xorspark** [comment]
You need to change the `projection`. If you're using our Florida example as a base, it is using the `am5map.geoAlbersUsa` projection. Replacing it with `am5map.geoMercator`  will straighten it out:

```
var chart = root.container.children.push(
  am5map.MapChart.new(root, {
    // ...
    projection: am5map.geoMercator() // you can also omit this setting entirely 
                                     // as Mercator is the default if not specified
  })
);
```

[You can find a list of supported projections here.](https://www.amcharts.com/docs/v5/charts/map-chart/#Projections)

**Comment by mediagirl** [comment]
Thank you, thank you and thank you! I never would have figured that one out. I really appreciate your quick answer. This is my first time working with this library. I did start with that Florida example code.
