### ISSUE TITLE
Chart Display

### ISSUE THREAD

**Issue by sknhkrn** [amcharts/amcharts5#72]
Hi

Is there a way where I can replace the charts and remove the old charts?
For example, when the div already have line charts, if I create another line charts, it will redundant with the older chart. 

Is there any way that I can replace the charts without emptying the div?
In amcharts4, I can do it by only updating the data of the series. I dont need to recreate the whole charts and series. 

How to do it in am5?
Tq

**Comment by martynasma** [comment]
Do you perhaps mean you want to to add and remove series dynamically?

**Comment by sknhkrn** [comment]
Yes but I do not want the series to be disappear and appear again. 
In amcharts 4, the series will appear like the line series is moving each time I add and update the data to the series.

**Comment by sknhkrn** [comment]
Currently, when I update load the charts, it become like this:-[](ur
![pic chart](https://user-images.githubusercontent.com/57323027/142131394-23a77d62-d704-4b36-8be8-8a58ee189f8c.PNG)
l)

**Comment by martynasma** [comment]
OK, I must admit I'm still a bit at loss about what's different and what you are doing. You mentioned removing and adding charts, then series, now you mention about data being added.

Perhaps it's just a term mixup, but it gets in the way.

Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can get a better understanding of what you are doing?

**Comment by sknhkrn** [comment]
Ok, this is the jsFiddle for am5:
https://jsfiddle.net/tyq3e70p/2/

And this is jsFiddle for am4:
https://jsfiddle.net/o05farL3/1/

What I want is like the one in am4 but I dont know if there is a way to do the same in am5.

**Comment by sknhkrn** [comment]
As you can see in the jsFiddle am5, when I create the chart on the same div. It does not replace the old chart instead creating a new one behind it while in am4, I can update the data only to replace the line chart.

**Comment by martynasma** [comment]
Well, you need to dispose the old chart before slapping on a new one in its place.

I updated your jsFiddle here:
https://jsfiddle.net/ozrny5qp/

We might implement some kind of autoDispose setting (like we had in v4) in the future.

**Comment by sknhkrn** [comment]
Hi, yes I can get it to work. Thank you.
