### ISSUE TITLE
Add date-axis bullets along the top of a date-value chart

### ISSUE THREAD

**Issue by zola-25** [amcharts/amcharts5#720]
Hi, thank you for your charting tool it really is amazing.

**Question**

I am trying to make a chart of a half hourly value with a date, using a date axis and the new grouped data feature. 

This I can do, but what I'd also like to add icons (bullets?) horizontally along the top of the chart.

In amcharts 4 I was able to hack this by creating a new series with a fixed y-value:

<img width="523" alt="image" src="https://user-images.githubusercontent.com/29863888/207746448-b48f685b-63d8-49ae-99b8-849c3673d690.png">

But it wasn't great because on zoom out all icons got mashed together.

Part of the issue is the icons are daily but the xy value is more granular.

I thought I might have found part of the solution with axis bullets: https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#axis-bullets

But the example uses CategoryAxis. I've tried essentially the same code but with DateAxis but I get `dataItem.dataContext` is undefined:

https://codepen.io/zola-25/pen/oNyKLNj

What I'm attempting may not be possible, maybe there is a different approach to what I'm attempting?

**Comment by martynasma** [comment]
Unlike `CategoryAxis`, `DateAxis`' data items do not have direct relation to data. It's just date scale. So the approach we used for the `CategoryAxis` won't work int this case.

It's still doable, albeit a bit hacky:

```JavaScript
let xDateAxis = chart.xAxes.push(am5xy.DateAxis.new(root, {
  groupData: true,
  maxDeviation: 0.2,
  baseInterval: {
    timeUnit: "hour",
    count: 1
  },
  renderer: am5xy.AxisRendererX.new(root, {
    opposite: true
  }),
  bullet: function (root, axis, dataItem) {
    var sprite = am5.Picture.new(root, {
      dy: 10,
      width: 24,
      height: 24,
      src: "dataItem.dataContext.icon"
    });
    
    sprite.on("x", function(x, target) {
      const seriesDataItem = axis.getSeriesItem(valuesWithIconsSeries,  axis.valueToPosition(target.dataItem.get("value")));
      if (seriesDataItem && seriesDataItem.dataContext.icon) {
        target.set("src", seriesDataItem.dataContext.icon);
      }
    })
    
    return am5xy.AxisBullet.new(root, {
      location: 0.5,
      sprite: sprite
    });
  }
}));
```

Let me know if that makes sense.

**Comment by zola-25** [comment]
Thank you, I got your example working and I'm starting to get the all the concepts now.

The problem actually made me rethink what I wanted to display on the chart and in the end I decided I wanted the bullets to move depending on a different y-axis value - essentially two different series with the same date axis, but with separate grouping functionality.

I pretty much managed to get it to work, but I had to have two X DateAxes because the grouping is defined on the DateAxis rather than on the series, but that was okay as I just hid one DateAxis. 

Seems to work great, the only issue is it's not possible to 'sync' up date axes like you can with value axes, so I have to make sure they have the same min/max values so that they align themselves.

Also auto-zoom on datavalidated doesn't work for this set up (the two data series get all jumbled and out of sync):

```
valuesWithIconsSeries.events.once("datavalidated", function(ev) {
            (ev.target.get("xAxis") as DateAxis<am5xy.AxisRenderer>)
                .zoomToDates(new Date(...), new Date(...));
        });
```

But I can get it to work with the start and end settings on the xAxes.

Thanks for your help!
