### ISSUE TITLE
How do I show values in Legend of ColumnSeries?

### ISSUE THREAD

**Issue by onlyarte** [amcharts/amcharts5#722]
**Question**
Why passing valueField does not work and how do I fix it?

```
// Create series
var series = chart.series.push( 
  am5xy.ColumnSeries.new(root, { 
    name: "Series", 
    xAxis: xAxis, 
    yAxis: yAxis, 
    valueYField: "value", 
    categoryXField: "category",
    tooltip: am5.Tooltip.new(root, {})
  }) 
);

series.data.setAll(data);

// Add legend
var legend = chart.children.push(am5.Legend.new(root, {
  nameField: "categoryX",
  valueField: "value",
  centerX: am5.percent(50),
  x: am5.percent(50)
}));

legend.data.setAll(series.dataItems);
```

https://codepen.io/team/amcharts/pen/QWvOYRX

**Comment by martynasma** [comment]
Legend is not a series and does not have nameField/valueField settings.

What are you trying to achieve here?

If you need to display values from series, please read here:
https://www.amcharts.com/docs/v5/charts/xy-chart/legend-xy-series/#Legend_label_content

**Comment by onlyarte** [comment]
@martynasma Thanks for the quick reply! I'm trying to add a legend to a chart containing ColumnSeries/RadarColumnSeries using the method described [here](https://www.amcharts.com/docs/v5/concepts/legend/#data-item-list). While it works well to display categories in the legend, I haven't managed to display values.

Here is my example:
https://codepen.io/onlyartee/pen/vYroryo (Solid Gauge)

In the legend I need this:
- Total Filled Quantity - 300
- Total Offered Quantity - 600

Thanks a lot!

**Comment by zeroin** [comment]
Only series set legendValueText on legend, and as your legend items are not series, you should set it on the series:

`legend.valueLabels.template.set("text", "{valueX}")`

**Comment by onlyarte** [comment]
@zeroin it works, thanks a lot!
