### ISSUE TITLE
Columns w/ Negative Values - Fill and Tooltip Config

### ISSUE THREAD

**Issue by IMTanuki** [amcharts/amcharts5#724]
Use Case
Trying to configure columns to display negative values with unique:
- fill
- tooltip position

The only docum I can find is: https://github.com/amcharts/amcharts5/issues/new?assignees=&labels=&template=question.md&title=

The only amcharts 5 config option for value-dependent columns is "based on whether value of the column is higher or lower than the previous column in series", not on whether a given column is positive or negative.

```
// - riseFromPrevious seems to be applied to all positive values
	series.columns.template.states.create("riseFromPrevious", {
		fill: am5.color ( 0x7986CB ),
		stroke: am5.color ( 0xC6168D ),
	});

// - dropFromPrevious seems to be applied to all negative values
	series.columns.template.states.create("dropFromPrevious", {
		fill: am5.color(0xC6168D),
		stroke: am5.color(0x7986CB),
	});
```

The above code sort of works for column fill and stroke, but:
- the rendered columns first display the dropFromPrevious, then riseFromPrevious property settings for positive values
- adding tooltip properties does not work.

Question
1. is there an amcharts5 set of states for positive and negative values, rather than states that compare a column to the previous column?

**Comment by zeroin** [comment]
You can use an adapter for fill to achieve this:

```
series.columns.template.adapters.add("fill", function(fill, target) {
    var dataItem = target.dataItem;
    if (dataItem.get("valueY") < 0) {
        target.set("tooltipY", am5.p100);
        return am5.color(0xff0000);
    }
    return fill;
})
```

https://codepen.io/team/amcharts/pen/abjbZyr/1220033ca723842f286196dfd740095b?editors=1010

**Comment by IMTanuki** [comment]
Interesting... I tried the following from the doc: https://www.amcharts.com/docs/v4/tutorials/different-column-fill-colors-for-positive-and-negative-values/
```
series.columns.template.adapter.add("fill", function(fill, target) {
  if (target.dataItem && (target.dataItem.valueY < 0)) {
    return am4core.color("#a55");
  }...
```
I kept getting "undefined" errors. But your code works fine.

Can I ask - if I wanted to modify multiple properties (e.g. stroke, tooltip position, etc.), I would need a separate function for each, am I correct?

Thx for the quick solution!

**Comment by zeroin** [comment]
It's because you tried to use v4 code on v5.

**Comment by IMTanuki** [comment]
got it.

Re the follow-on question - do I need a separate instance of an adapter for each property that is value-dependent? If I read your example correctly, it appears that I can:

- use a single adapter
- assign multiple properties (e.g. target.set("tooltipY", am5.p100...)
- but return only the property in the adapter parameters (e.g. "fill")

I'll try this out, but TBH, the syntax is a bit kludgy.

Also, FWIW, there's nothing I could find in the V5 docum that explains the latest syntax for value-dependent properties...just the state model I noted in my original post.

**Comment by zeroin** [comment]
Yes, you can use adapter to modify other properties. We will try to update docs. Note, if your values change, you might need to use a different property, as fill adapter is called only once (unless you initiate it by changing fill value). So in some cases you could use adapter for x/y/width/height, return the same value and modify fill before that.

**Comment by IMTanuki** [comment]
@zeroin -  I think the code below works fairly well - I used active as the parameter, since it will rarely be updated, and returned null. All properties are explicitly changed, which I think makes it easier to understand.

One last question - I can set the tooltip to be positioned above or below a negative column:
- if above, is there any way to compute the net of am5.p100 and an additional 10? (e.g. am5.p100 + 30) so that the tooltip sits off a little from the column?
- if below, is there any way to flip the tooltip bkg pointer, so that it points up

```
series.columns.template.adapters.add ( "active", function ( active, target ) {
	var dataItem = target.dataItem;
		if ( dataItem.get ( "valueY" ) < 0 ) {
			// negative values - column props
			target.set ( "fill", am5.color ( 0xC6168D ) );
			target.set ( "stroke", am5.color ( 0x7986CB ) );

			// negative values - tooltip props
			// target.set ( "tooltipY", am5.p100 );		// positions tooltip above column
			target.set ( "tooltipY", +60 );					// positions tooltip below column 
			return null;
		}
		return null;
	} )
```

Thx again!

**Comment by IMTanuki** [comment]
Thx so much! I'm aware of pointerOrientation, but I wasn't quite sure if child classes (of column) could be referenced in an adapter. But your dy example provides that.

Will give it a shot when I get in to the office today.

Thx for all your help!
