### ISSUE TITLE
Add tooltip on pie chart label

### ISSUE THREAD

**Issue by jguyon88** [amcharts/amcharts5#725]
**Question**

I try to add a tootlip on an a label that lie inside a PieChart. My chart is based on the code from the tuto here : https://www.amcharts.com/docs/v5/tutorials/sum-label-inside-a-donut-chart/

Following the doc here : https://www.amcharts.com/docs/v5/concepts/common-elements/tooltips/, adding tootlipText on the label should be enough but does not work. 
I tried also adding a new tooltip instance to the label without success. I also tried to use the set method instead.

```
series.children.push(am5.Label.new(root, {  
     text: "${valueSum.formatNumber('#,###.')}",
     fontSize: 40,  
     centerX: am5.percent(50),
     centerY: am5.percent(50),
     populateText: true,
     tooltip: am5.Tooltip.new(root, {}),
     tooltipText: "test"
}));
```

If somebody can make it work on the tuto code I would be gratefull.

**Comment by martynasma** [comment]
Adding `tooltipText` is not enough for labels. This doc explains:
https://www.amcharts.com/docs/v5/concepts/common-elements/labels/#labels-as-interactive-elements

We'll add related info to the Tooltips tutorial as well, so it's more prominent. Thanks!

**Comment by jguyon88** [comment]
Thanks, it works, I agree it makes sens to add a note about label tooltips in the tooltip doc because it's tricky.

**Comment by martynasma** [comment]
There ya go:
https://www.amcharts.com/docs/v5/concepts/common-elements/tooltips/#Tooltips_on_labels
