### ISSUE TITLE
CategoryAxis Custom Html Shake Problem

### ISSUE THREAD

**Issue by gucal** [amcharts/amcharts5#727]
I using Gantt Chart. 

DateAxis (xAxis) is fine but CategoryAxis (yAxis) is not working properly.

```
yAxis.get('renderer').labels.template.adapters.add('html', function () {
        return '<div>{category}</div>';
});
```
You can check the example.
https://stackblitz.com/edit/angular-ivy-1z9quq?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

**Comment by martynasma** [comment]
Just disable ghost label:

```JavaScript
yAxis.ghostLabel.set("forceHidden", true);
```

More info:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/value-axis/#Ghost_label

**Comment by gucal** [comment]
In this case, only some of the category titles are visible.

Updated stackblitz code.

**Comment by martynasma** [comment]
You may need to center the labels properly:

```JavaScript
yAxis.get('renderer').labels.template.setAll({
  centerX: 0
});
```

**Comment by gucal** [comment]
Yes, the problem was solved in this way.

Thanks...

**Comment by shailendrakanherkar18** [comment]
Thanks I was also facing similar issue, @martynasma I need one more favor with the above solution its getting aligned to center but not able to get it back to right(original) layout, Could you please help me?
