### ISSUE TITLE
XY

### ISSUE THREAD

**Issue by nseb** [amcharts/amcharts5#731]
Hello,
I have created a simple case XYChart with SmoothedXLineSeries, the data xAxis are Label (year) , i'm not use DateAxis but CategoryAxis. I have two problems 

- Label or not align with data on line
- labels are missing on the X axis, (ex 2020 ,2022))

version ; amcharts5-5.2.45 
![image](https://user-images.githubusercontent.com/6363226/209450613-e27aa69f-d6d0-43c3-a369-969a679ad328.png)

**Comment by xorspark** [comment]
> Aligning labels

You can try setting `location` to 0.5 on your x axis renderer label template to center them: https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#location-of-axis-elements

Example:

```
let xRenderer = xAxis.get("renderer");
xRenderer.ticks.template.setAll({
  location: 0.5,
  // ....
});
```

> Missing labels

Try decreasing the `minGridDistance` on your axis renderer. This controls the label density (how many labels are visible): https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#location-of-axis-elements

Example:

```
let xRenderer = xAxis.get("renderer");
xRenderer.set('minGridDistance', 20);
```
