### ISSUE TITLE
Manually positioning cursor  is pointing to the line point and not moving when we move the cursor

### ISSUE THREAD

**Issue by VanavarayanK** [amcharts/amcharts5#732]
Manually positioning cursor is fine when we adjust date from top, the tooltip is not pointing to the line and also is there any method to move cursor as per the as per mouse movement even if we place the position manually 
[Tootip.webm](https://user-images.githubusercontent.com/118241594/209629688-53c44e0b-a230-4278-bb8e-7e24ca0eb593.webm)

https://codepen.io/team/amcharts/embed/gOWXZxM?default-tab=result&editable=true&theme-id=dark

**Comment by zeroin** [comment]
Tooltips are hidden when zoom animation happens, so my suggestion would be to add some timeout before setting position for the cursor. If you want the cursor to follow the mouse while user is hovering the chart, you should set positions to undefined when plot area is hovered:

https://codepen.io/team/amcharts/pen/gOWXZxM

**Comment by VanavarayanK** [comment]
Thanks team, it helps a lot but when we  adjust the chart toolbar or while
changing the select period  graph changes but the tooltip getting fixed at
the same position until we  hover on the graph.
[image: image.png]
[image: image.png]


Regards,
Vanavarayan

**Comment by VanavarayanK** [comment]
Also Tooltip value is same as before its not changing dynamically as per
the graph changes.

**Comment by martynasma** [comment]
This question goes beyond the free support scope we try to offer here.

If you have an amCharts support subscription, we suggest contacting our helpdesk. If you don't, you might consider acquiring one. For more details on procuring support please refer to [this page](https://www.amcharts.com/support/support-info/get-support/).

**Comment by VanavarayanK** [comment]
HicTeam,

We have purchased the licence but when it comes to bug issues how can
resolve it from our side?, Even after refering to the documentation if
there is no solution what is the solution.

Regards,
Vanavarayan

**Comment by martynasma** [comment]
You can contact our support via contact@amcharts.com. Thanks.

**Comment by VanavarayanK** [comment]
Thank you.
