### ISSUE TITLE
No function for chart redraw. 

### ISSUE THREAD

**Issue by Amitnaresh29** [amcharts/amcharts5#733]
**Bug description**

**Environment (if applicable)**

**Additional context**

i am stuck in a place where my values are getting updated but i need to redraw the chart.There is no option available for redrawing the chart.

**Comment by martynasma** [comment]
Do you mean data values or values of settings?

Setting either one should get the chart redrawn automatically.

**Comment by Amitnaresh29** [comment]
I have the working code and inside drawing series in console I am recieving the data ,but i chart doesnt shows the updated data for this purpose I want to redraw chart.

**Comment by Amitnaresh29** [comment]
in amchart 4 there was function validateData() for this purpose.In amcharts v5 there is no function like this,is there any ?

**Comment by martynasma** [comment]
amCharts 5 data detects changes automatically:
https://www.amcharts.com/docs/v5/concepts/data/#Updating_existing_data
