### ISSUE TITLE
GANTT CHART FUNCTIONS 

### ISSUE THREAD

**Issue by sknhkrn** [amcharts/amcharts5#735]
Hi amCharts, my company is considering of purchasing the license for amChart5.
However, they want to know some function for the Gantt Chart. 

1. For the gantt chart, is it possible to have 2 bar in one timeline. For example, the gantt chart need to be use for monitoring a timeline so need to have two bar which indicate the plan timeline and the actual timeline.

2. Is it possible to move the bar in gantt chart to anywhere on the chart by the user (not from coding part). For example, a user might want to move the bar on date 23/9/2022 to date 22/9/2022. In short, I want to have flexible bar instead of fixed bar display. 

Feel free to recommend any solution on how to achieve the functions which I mentioned above. 
Thank you in advance.

**Comment by martynasma** [comment]
That's a yes for the first requirement, and a no for the second one. amCharts does not offer any built-in column editing capabilities.
