### ISSUE TITLE
Stacked Bar Chart with Negative Values 

### ISSUE THREAD

**Issue by harshal-c99** [amcharts/amcharts5#736]
can we arrange the positive and negative values of bar chart strictly left and right in chart? like y axis values?
![image](https://user-images.githubusercontent.com/109568978/209934186-4c7d83e5-aff3-4960-9c41-9bb2372a7672.png)

**Comment by martynasma** [comment]
I'm not entirely sure what you mean. Isn't it already like that in the screenshot above?

**Comment by harshal-c99** [comment]
so I want the value 0.1 , 0.2,0.3 of male aligned strictly to left  and same for female 0.3,0.3,0.6 aligned strictly to right.
for ex.
0.1               ---------|----------------------        0.3
0.2        ---------------|-----------------------      0.3
0.3    ------------------|------------------------     0.6
       6     4       2      0       2       4         6

**Comment by martynasma** [comment]
Thanks.

This can be done using an adapter on a bullet's `x` setting:

```JavaScript
  series.bullets.push(function() {
    var sprite = am5.Label.new(root, {
      centerY: am5.p50,
      text: "{valueX}",
      populateText: true,
      centerX: labelCenterX
    });

    sprite.adapters.add("x", function(x, target) {
      return target.get("centerX");
    });

    return am5.Bullet.new(root, {
      locationX: 1,
      locationY: 0.5,
      sprite: sprite
    });
  });
```

Here's a CodePen:
https://codepen.io/team/amcharts/pen/VwBaQyj/b4712200ebb0337d37477f3485cfeacc

**Comment by harshal-c99** [comment]
@martynasma Thanks a lot!
