### ISSUE TITLE
Using comma as seperator when reducing long numbers

### ISSUE THREAD

**Issue by trgcyln** [amcharts/amcharts5#737]
Hi,

Let's say , I've very big numbers in my series. I'm trying to show them like 1,5B   or 4.5M  or 4.8K
I tried the next code but I've no luck so far.
```
root.numberFormatter.setAll({`
        numberFormat: "#.0a",
        decimalSeparator: ",",

        
        bigNumberPrefixes: [
            { "number": 1e+3, "suffix": "K" },
            { "number": 1e+6, "suffix": "M" },
            { "number": 1e+9, "suffix": "B" }
        ],

        
        smallNumberPrefixes: []
    });
```
    
    Could someone help me with this ?

**Comment by martynasma** [comment]
There is no `decimalSeparator` setting in a `NumberFormatter`. Decimal separator comes from a locale. If you do not want to change the locale, you can override just this particular thing like this:

```JavaScript
root.locale._decimalSeparator = ",";
```

More info:
https://www.amcharts.com/docs/v5/concepts/locales/creating-translations/#Modifying_individual_prompts

**Comment by trgcyln** [comment]
Thank you so much ! It solved my problem.
