### ISSUE TITLE
Logarthmic scale min max not working correctly

### ISSUE THREAD

**Issue by Finnitio** [amcharts/amcharts5#738]
When displaying data like

`var data = [
  { freq: 20, single: 93 },
  { freq: 100, single: 95 },
  { freq: 150, single: 94 },
  { freq: 200, single: 95 }
];`

in a logarthimic scale am charts displays a range from 2-200 which puts the line only on half of the space. 
![grafik](https://user-images.githubusercontent.com/12029353/210136072-fbf7c517-571e-4182-bf19-dc6540915c16.png)
Setting the axis to a linear scale the range is displayed correctly.
![grafik](https://user-images.githubusercontent.com/12029353/210136131-f4fdc16a-c808-4ebf-bee2-13221b602eec.png)

[codepen.io](https://codepen.io/Finncois/pen/poZyXzY)
https://codepen.io/Finncois/pen/poZyXzY

**Comment by zeroin** [comment]
You should set extraMin/extraMax to 0 for log axis, as by default these values are 0.1 for extraMin and 0.2 for extraMax (when log axis is used).

**Comment by Finnitio** [comment]
Thank you my fold, now it is working!
