### ISSUE TITLE
How to built this kind of graph using amcharts 5

### ISSUE THREAD

**Issue by Amitnaresh29** [amcharts/amcharts5#739]
![1672647781607](https://user-images.githubusercontent.com/85749939/210208040-c0286cb1-7005-4b5c-96dd-6f619dde88b4.jpg)

**Comment by martynasma** [comment]
No, I'm afraid we do not offer a chart like that.

**Comment by Amitnaresh29** [comment]
I am doing this in amcharts 5 is there a way in which we can change the height of the bars in this.
![1672657381113](https://user-images.githubusercontent.com/85749939/210223123-e3dcea3d-a733-407a-b319-5e46a1ae77a8.jpg)

**Comment by Amitnaresh29** [comment]
and the color of the bars as well
