### ISSUE TITLE
addLicense() does not hide watermark

### ISSUE THREAD

**Issue by sassomedia** [amcharts/amcharts5#74]
The [Registry](https://www.amcharts.com/docs/v5/reference/registry_module/#addLicense_method) item `addLicense` does not seem to work (v5.0.5). For one, the suggested import cannot be resolved:
```javascript
import * as $registry from "@amcharts/amcharts5/Registry"; // ESLint complains about Registry not being available
```
but the usage example targets a valid function (this was the same code in `am4`):
```javascript
am5.addLicense("xxxxxxxx");
```
However, the watermark still displays and our amPlus subscription is up to date.

Is there now a different way we have to add the license?

**Comment by martynasma** [comment]
No need to import `Registry` for that. `addLicense()` function is exported via `index` (am5) as well.

What goes into parameter of the license differs from v4 though.

For info you can log into our support area:
https://www.amcharts.com/support/my-downloads/

Or reach out to us at contact@amcharts.com

**Comment by sassomedia** [comment]
Ok that worked, thanks @martynasma
