### ISSUE TITLE
No method to change height of bar in partion chart.

### ISSUE THREAD

**Issue by Amitnaresh29** [amcharts/amcharts5#740]
**Question**

**Environment (if applicable)**

**Additional context**
There is no way with which we can change height of bar in partion chart.

**Comment by martynasma** [comment]
The height of the bars in a Partition chart will depend on the number of rows/columns and value as well as available space. There is no way to fix the height at specific pixel value, I'm afraid.

**Comment by Amitnaresh29** [comment]
how we can change color of the bar in partition chart .
