### ISSUE TITLE
Sankey Diagram Node Ordering

### ISSUE THREAD

**Issue by maridevcse** [amcharts/amcharts5#741]
**Question**

Hi

In the am5 Sankey diagram is there any way to order the nodes and the **node order should be same as the order in the node data array**

For Example :
`const nodeArray =[{node :'A'},{node:'B'},{node:'C'},{node:'D'},{node:'E'}];`

The output diagrams node order should be same order of this nodeArray

**Comment by martynasma** [comment]
Nodes are ordered in exact same order as they appear in data by default.

If you have a chart that does not do that, maybe you can post it on CodePen so that we can take a look?
