### ISSUE TITLE
Always show series tooltips

### ISSUE THREAD

**Issue by Finnitio** [amcharts/amcharts5#742]
I am struggeling to find a way to always display the series tooltips like in this tutorial:
![grafik](https://user-images.githubusercontent.com/12029353/210264541-a250f366-4473-4c29-93aa-2d1394174993.png)
[https://www.amcharts.com/demos/multiple-value-axes/](url)
Instead I am only able to finde this possible:
![grafik](https://user-images.githubusercontent.com/12029353/210264586-c86f4258-4f5b-4d8d-96a6-4ba336c28940.png)
[https://www.amcharts.com/demos/highlighting-line-chart-series-on-legend-hover/](url)

I don't see any difference in tooltip options, what am I missing here?

kind regards

Finn

**Comment by martynasma** [comment]
The difference is the `maxTooltipDistance` setting:

https://www.amcharts.com/docs/v5/charts/xy-chart/cursor/#limiting-number-of-tooltips-shown-at-a-time

**Comment by Finnitio** [comment]
Thank you, that is it!
