### ISSUE TITLE
Traceable Sankey Link Color

### ISSUE THREAD

**Issue by maridevcse** [amcharts/amcharts5#744]
**Question**
Hi 

I have attached the link for traceable Sankey diagram below , Actually I am looking for a way to give single color for the link , from start to end while hovering,I done a analysis on that but couldn't find anything, is there any way to do it

https://www.amcharts.com/demos/traceable-sankey-diagram/

**Comment by xorspark** [comment]
You can change the color on the hovered link by modifying the  [hover state](https://www.amcharts.com/docs/v5/concepts/settings/states/#Creating_or_modifying) of the series link template

```
series.links.template.states.create("hover", {
  fill: am5.color(0x297373),
});
```

If you want to change the base color of the link itself, set the `fill` on the template directly:

```
series.links.template.setAll({
  // ...
  fill: am5.color(0xff0000)
});
```

The hover will inherit the fill

**Comment by maridevcse** [comment]
Thanks @xorspark @martynasma 

I have achieved in this manner

`
 series.links.template.events.on("pointerover", function (event) {
      let dataItem = event.target.dataItem;
      let id = dataItem.get("id");
      am5.array.each(series.dataItems, function (dataItem) {
        if (dataItem.get("id") === id) {
          dataItem.get("link").hover();
          dataItem.get("link").set("fillStyle", "solid");
          dataItem.get("link").set("fill", "green");
        }
      });
    });

    series.links.template.events.on("pointerout", function (event) {
      am5.array.each(series.dataItems, function (dataItem) {
        dataItem.get("link").unhover();
        dataItem.get("link").set("fillStyle", "source");
      });
    });
`

Thank you very much for your simple approach
