### ISSUE TITLE
Extend the Line of LineSeries to the extereme ends of the Axis.

### ISSUE THREAD

**Issue by attacker88** [amcharts/amcharts5#745]
I have used a line series for one of my charts and it works fine with no issues.
There is a requirement that the line series should be extended to the complete end of the bars like below  image which is not happening.
![Capture](https://user-images.githubusercontent.com/66474039/210393164-be97120b-d165-48d7-b9ea-38332e5d8424.PNG)

I understand that it is a default behaviour of Lineseries that the line series will start at middle of the axis cell. I have tries the LocationX and it only moves the Line either up or down and it doesn't extend the line
Below image is what we have got so far.
![Capture1](https://user-images.githubusercontent.com/66474039/210393699-a320456d-3a06-4aab-b6cd-8766880bcc23.PNG)

Any Help is appreciated.

**Comment by martynasma** [comment]
If you need to draw a vertical line, why not just use an [axis range](https://www.amcharts.com/docs/v5/charts/xy-chart/axes/axis-ranges/)?

**Comment by attacker88** [comment]
Thank You @martynasma.
we wanted to show legends as well for the bar and the line. Anyways I have used axis range and did a workaround for the legend.

Thanks
