### ISSUE TITLE
Missing support for Slovak (sk) locale

### ISSUE THREAD

**Issue by bsvensson** [amcharts/amcharts5#748]
**Bug description**

amcharts4 has support for Slovak (sk), but amcharts5 does not.
Not sure if this is a bug/oversight, or an enhancement request :)

* https://github.com/amcharts/amcharts4/tree/master/dist/es2015/lang
* https://github.com/amcharts/amcharts5/tree/master/src/locales (for 5.2.22)

**Comment by martynasma** [comment]
Thanks for the heads up!

Slovak locale was added after language info was forked over to amCharts 5.

We'll pull it in for the next version, and let you know here.

**Comment by martynasma** [comment]
Added in [5.2.48](https://github.com/amcharts/amcharts5/releases/tag/5.2.48).

## [5.2.48] - 2023-01-17

### Added
- Slovak (sk_SK) locale added.

### Fixed
- Grid was not being placed in correct place on a `DateAxis` with grid or grid interval in 30 minutes.
- Cursor tooltip was not being snapped to an `XYSeries` with `snapTooltip: true` when it was left of the first available data item.
- `PeriodSelector` was not properly zooming the X axis with a non-standard value in `firstDayOfWeek` locale.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
