### ISSUE TITLE
Chart doesn't render in given height width.

### ISSUE THREAD

**Issue by keyurtruenorth** [amcharts/amcharts5#749]
**Bug description**

The chart renders within a small block despite giving it appropriate height & width

![image](https://user-images.githubusercontent.com/62983988/210726045-c7d1e434-37bc-43aa-af0e-b20da8860f53.png)

Any specific tinkering that needs to be done?

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by martynasma** [comment]
Not sure what to suggest then. Try disabling moving parts in your part, to find out which one causes it.

Also, you seem to be using an older version of amCharts 5. Try the latest one.

**Comment by keyurtruenorth** [comment]
Super, let update and tinker around.

**Comment by keyurtruenorth** [comment]
Still not able to figure out, do you think any css will hinder the rendering? Or any specific typescript/angular method which will affect the rendering?

**Comment by martynasma** [comment]
Nah, I don't think CSS can affect it, since it's canvas, not individual DOM elements.

Did you try updating to the latest version?

**Comment by keyurtruenorth** [comment]
Yes did that as well but same result.
