### ISSUE TITLE
Sankey diagram Y axis nodes ordering

### ISSUE THREAD

**Issue by maridevcse** [amcharts/amcharts5#751]
Hi

I'm looking for a way to order a nodes in Y axis 

For Example here you can see the marked y axis and the NODE ORDER is **I,L,M,J,N,K** , but i want to order it based on highest outgoing to lowest outgoing , The node order should be  **I,N,L,M,J,K**

![Screenshot (176)](https://user-images.githubusercontent.com/54475989/211183198-0c2d62c6-86bf-40d8-8e63-b11c4b3528c4.png)

**Comment by martynasma** [comment]
I suppose you can use `SankeyDiagram` setting `sortBy`:

https://www.amcharts.com/docs/v4/reference/sankeydiagram/#sortBy_property

**Comment by martynasma** [comment]
There's no way to force a specific order of nodes. They will appear in exactly same order as they first appear in data: either as from or to node.
