### ISSUE TITLE
Positioning nodes in descending order. Force directed. 

### ISSUE THREAD

**Issue by BratikWWW** [amcharts/amcharts5#753]
Hi! Are there any options to position nodes by value in descending order? 
![image](https://user-images.githubusercontent.com/42339020/211249269-e0a2394d-83f2-42ce-bcb8-983c5123d757.png)

**Comment by martynasma** [comment]
No, I'm afraid. The ForceDirected algo adds some randomness factor into its initial positioning logic, at which point built-in physics push/pull/collision model kicks in to make the nodes dynamically settle into their position.

**Comment by BratikWWW** [comment]
> No, I'm afraid. The ForceDirected algo adds some randomness factor into its initial positioning logic, at which point built-in physics push/pull/collision model kicks in to make the nodes dynamically settle into their position.

thanks for the reply
