### ISSUE TITLE
Trigger click event on slice of a sunburst chart

### ISSUE THREAD

**Issue by marcomonto** [amcharts/amcharts5#755]
Hello,
I am trying to trigger an event of a slice click in my code logic, 
i tried to read the docs and after various tries i couldn't succeed,
searching online i found that in amcharts 3 there was clickSlice(index), in pieChart it did the work, probably i am missing something here, thanks in advance to everyone can help.

**Comment by martynasma** [comment]
In case of `Sunburst`, you should probably use its method: [`selectDataItem()`](https://www.amcharts.com/docs/v5/reference/sunburst/#selectDataItem_method). It carries all the logic associated to clicking a slice.

If you have a slice object, you want to trigger a click on, you can access its `dataItem` property to use as a parameter for `selectDataItem()`.

If you don't, you can iterate, via `series.dataItems` array, and locate the one you need to click on using your own logic.

**Comment by martynasma** [comment]
Here's an example: https://codepen.io/team/amcharts/pen/LYBLRoN

Code that simulates click on a node by its name:

```JavaScript
function drillTo(name) {
  series.nodes.each(function(node) {
    if (node.dataItem.get("category") == name) {
      series.selectDataItem(node.dataItem);
    }
  })
}
```

**Comment by marcomonto** [comment]
Thanks a lot!
