### ISSUE TITLE
How to remove the line at the top of columns in a stacked bar chart?

### ISSUE THREAD

**Issue by krista-prokop** [amcharts/amcharts5#758]
see codepen: https://codepen.io/krista-prokop/pen/xxJrzyq

How can i remove the line (border?) at the top of the columns?

**Comment by xorspark** [comment]
The line is coming from the column series' stroke. Setting the `strokeOpacity` to 0 on the column template will remove it.

```
  series.columns.template.setAll({
    tooltipText: "{name}, {categoryX}:{valueY}",
    width: am5.percent(90),
    strokeOpacity: 0,
    tooltipY: 0
  });
```

**Comment by krista-prokop** [comment]
Thank you!
