### ISSUE TITLE
How to Add Graphics Relative to Stock Chart Axes

### ISSUE THREAD

**Issue by oluwakayode-a** [amcharts/amcharts5#759]
First, many thanks for this awesome library.
I have a problem I've been stuck on for some time now.

I'm trying to add markers to a stock chart using the Graphics module. I can get it to appear, however, the x and y values don't seem to correspond to the axes (they're all over the place, I'm not sure what they correspond to). 
The examples on the docs only show the graphics at the center of the chart using am5.percent(50) on both x and y axes.

Here's what I'm currently doing.

```
stockChart.children.push(am5.Graphics.new(root, {
            stroke: am5.color(0x000000),
            strokeWidth: 1,
            fill: am5.color(0x990000),
            fillOpacity: 0.5,
            x: new Date("2022-10-24T07:38:00-04:00"),
            y: 70,
            rotation: 45,
            centerX: am5.percent(50),
            centerY: am5.percent(50),
            draw: function(display) {
                display.drawRect(0, 0, 8, 8)
            }
        }));
```

How do I set Graphic elements relative to the x and y axes defined in my stock chart?

Any help would be much appreciated.

**Comment by martynasma** [comment]
If you need a marker to be attached to a date on a DateAxis, you can use axis bullets:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#axis-bullets

If you need a bullet that is also attached to an Y value, you will need to create a separate Series (e.g. LineSeries) with bullets and own data.
https://www.amcharts.com/docs/v5/charts/xy-chart/series/#Bullets

Hope it makes sense.

**Comment by oluwakayode-a** [comment]
@martynasma 
Thank you so much!
