### ISSUE TITLE
Labels and Ticks on pie chart series with visible property set to false appear when legend item clicked twice

### ISSUE THREAD

**Issue by jcgithub9** [amcharts/amcharts5#76]
On Pie chart with a legend, when series labels and ticks have visible property set to false, if the legend items are clicked twice to remove and then re-draw the particular item, the item's label and tick will appear when re-drawn.  Example from amcharts5 donut with radial gradient demo - click a legend item twice to seen labels/ticks appear for clicked-on item.
https://www.amcharts.com/demos/donut-with-radial-gradient/ 
Seems to be unintended behavior, as assume labels/ticks should remain non-visible.

**Comment by jcgithub9** [comment]
UPDATE - found that setting the forceHidden property keeps the labels/ticks non-visible when legend items clicked.

**Comment by martynasma** [comment]
> UPDATE - found that setting the forceHidden property keeps the labels/ticks non-visible when legend items clicked.

Yup, that's it.

Applying different states might affect `visible` setting. Whereas `forceHidden` is rock solid. If it's set, it is guaranteed to be hidden regardless of any processes going on inside the chart.
