### ISSUE TITLE
how to change createSeriesRange method on amchart4 to on amchart5?

### ISSUE THREAD

**Issue by yunyami0605** [amcharts/amcharts5#760]
**Question**

Hi, I made a chart to use **amchart4**
```
    const range = valueAxis.createSeriesRange(salesSeries);
    range.value = 100;
    range.endValue = 0;
    range.contents.stroke = am4core.color("#F61313");
    range.contents.fill = am4core.color("#F61313");
    range.contents.fillOpacity = 0.6;
```

from amchart4 code in [https://codepen.io/yunyami0605/pen/vYaePyp](url)

but, i can't found this 'createSeriesRange'  method on **amchart5** version documention

please, advise for me.

**Environment (if applicable)**

```
"@amcharts/amcharts5": "^5.2.47",
"react": "^16.13.1",
"typescript": "^3.8.3",
```

**Comment by martynasma** [comment]
There's no `createSeriesRange` method in amCharts 5. There's `createAxisRange` method on the series itself.

More info: https://www.amcharts.com/docs/v5/charts/xy-chart/axes/axis-ranges/#series-axis-ranges
