### ISSUE TITLE
Sice minimum width  on a pie chart

### ISSUE THREAD

**Issue by sutkovoy** [amcharts/amcharts5#761]
Hello. I'm using amcharts 5.
Can the minimum width be set for slices on a pie chart? Didn't find any related info in the documentation.
![Screenshot 2023-01-18 at 18 27 06](https://user-images.githubusercontent.com/8820429/213236137-5e1c019c-9a4c-4ad5-8566-93d9b8ddebe3.png)

**Comment by zeroin** [comment]
No, it can't.
