### ISSUE TITLE
Axes Charts Base grid line

### ISSUE THREAD

**Issue by emlim23** [amcharts/amcharts5#766]
**Question**

Hi I'm using AMCharts 5 to create a bar chart that has no grid EXCEPT the base grid lines (the ones at 0 mark). According to this documentation: [https://www.amcharts.com/docs/v5/charts/xy-chart/axes](https://www.amcharts.com/docs/v5/charts/xy-chart/axes/ )

`There is no template for base grid line - a grid line that is displayed on a zero value.`

I've tried what was in the example:

`myTheme.rule("Grid", ["base"]).setAll({`
`  strokeOpacity: 1`
`});`

`root.setThemes([`
`  myTheme`
`]);`

But this doesn't work. If I remove the `["base"]` I can see that the theme does work on ALL the grids. I am trying a workaround by using this snippet:

let xbaseCount = 0;
xRenderer.grid.template.on('forceHidden', (_, target) => {
    if (xbaseCount === 0) {
        target?.set('forceHidden', false);
      }
      xbaseCount++;
});

This works but when the data changes this no longer triggers. My guess is the redraw doesn't get triggered. This is also an ugly and unreliable work around, because the 'yAxis' base grid is on index 1 instead of 0!

I'd like to know how I can achieve this as I am in the process of evaluating if we will be using your plugin or not. Thanks a lot!

**Comment by emlim23** [comment]
btw, I've used your version 4 and this was way easy to achieve there. The change between 4 and 5 for modifying these settings seems drastic.

**Comment by martynasma** [comment]
Without seeing your actual code, I reckon there might be two issues:

1) You missed the `var myTheme = am5.Theme.new(root);` line.

2) You call `root.setThemes()` again and override the first time which sets `myTheme`.

**Comment by emlim23** [comment]
@martynasma Thank you for the quick response. I've added that. Here's a fork of the sample code from the demos page with the custom theme changes: https://jsfiddle.net/bfvy8mzq/

I tried making the strokeWidth and the color of the base too, but no effect.

**Comment by martynasma** [comment]
Well, the reason is that "base grid" is not visible.

It's usually at value zero, and it's not visible.

If you need to style the lower line of the chart instead, you can do so by styling the axis line:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#axis-line

**Comment by emlim23** [comment]
@martynasma Thank you very much! I wouldn't have guessed it if you haven't told me that it was not visible. I thought it was always visible by default.
