### ISSUE TITLE
a problem with plotting line series with V5.2.23

### ISSUE THREAD

**Issue by AmirhosseinAyoubi** [amcharts/amcharts5#769]
**Bug description**
I plot time series with this library using React. Most of the time the plot is drawn correctly, but sometimes it displays as below. I also exported the json file from the chart and attached it.

[](url)
![chartBug](https://user-images.githubusercontent.com/96124350/214885519-f845bf12-ef13-47ab-9d23-1a7e55c369c0.png)

``` json
[ {
    "date": 1673625600000,
    "value": 0.08027
  },
  {
    "date": 1673629200000,
    "value": 0.0798
  },
  ...,
  {
    "date": 1674486000000,
    "value": 0.08731
  }]
```

**Environment (if applicable)**

 - amCharts version = 5.2.23
 - Browser = edge & chrome
 - Related frameworks and their versions = React js

**Comment by xorspark** [comment]
I'm unable to reproduce this by following your data format on 5.2.23 or the latest release 5.2.50, as you can see [here](https://codepen.io/team/amcharts/pen/abjGrEy/f834e33e35f7fa1b6f104f3b2d3f002f?editors=0010). Can you please provide reproduciable sample either in codepen or codesandbox so we can take a closer look?
