### ISSUE TITLE
AMCharts 5 and NextJS

### ISSUE THREAD

**Issue by alienbuild** [amcharts/amcharts5#77]
I'm trying to build my next application but it's failing build on amcharts 5. Can anyone confirm if this package is ok to use with nextjs 12? Thanks

Error and trace is:
```
> Build error occurred
/home/****/public_html/****/node_modules/@amcharts/amcharts5/index.js:1
export { Root } from "./.internal/core/Root";
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.9504 (/home/****/public_html/****/.next/server/pages/veve/market/components/TradingChart/PrimaryChart.js:69:18)
    at __webpack_require__ (/home/****/public_html/****/.next/server/webpack-runtime.js:25:42)
    at Object.8707 (/home/****/public_html/****/.next/server/chunks/8707.js:15:77) {
  type: 'SyntaxError'
}

```

**Comment by Pauan** [comment]
amCharts uses standard ES6 modules which work in every bundler (Webpack, Rollup, etc.) so that seems like a bug in NextJS.

I noticed you [already filed an issue](https://github.com/vercel/next.js/issues/31518), so let's wait and see what they say.

**Comment by alienbuild** [comment]
No response as of yet but temp fix for now if anyone else comes across this is to install `next-transpile-modules`, and then in your next.config.js

```
const withTM = require('next-transpile-modules')(['@amcharts/amcharts5'])

module.exports = withTM({});
```

**Comment by pmerolle** [comment]
Any update?

**Comment by Pauan** [comment]
NextJS has decided to not fix this bug, but you can workaround it by disabling SSR when importing your amCharts component, like this:

```js
import dynamic from 'next/dynamic';

const Chart = dynamic(() => import('../components/Chart'), { ssr: false });

export default () => {
  return (
    <div>
      <Chart />
    </div>
  );
};
```

**Comment by guidra-rev** [comment]
> NextJS has decided to not fix this bug, but you can workaround it by disabling SSR when importing your amCharts component, like this:
> 
> ```js
> import dynamic from 'next/dynamic';
> 
> const Chart = dynamic(() => import('../components/Chart'), { ssr: false });
> 
> export default () => {
>   return (
>     <div>
>       <Chart />
>     </div>
>   );
> };
> ```

I tried that, it doesn't work, only transpiling worked

**Comment by hencework** [comment]
import dynamic from 'next/dynamic';

const Chart = dynamic(() => import('../components/Chart'), { ssr: false });

export default () => {
  return (
    <div>
      <Chart />
    </div>
  );
};

after using this code, error removed on local server but it is still occurred in deployment

**Comment by hencework** [comment]
> NextJS has decided to not fix this bug, but you can workaround it by disabling SSR when importing your amCharts component, like this:
> 
> ```js
> import dynamic from 'next/dynamic';
> 
> const Chart = dynamic(() => import('../components/Chart'), { ssr: false });
> 
> export default () => {
>   return (
>     <div>
>       <Chart />
>     </div>
>   );
> };
> ```

after using this code, error removed on local server but it is still occurred in deployment

**Comment by jmtimko5** [comment]
@Pauan I have a question regarding this. I am concerned that the only solution at this point is transpiling modules as mentioned [here](https://github.com/vercel/next.js/issues/31518). Doing a dynamic import for actual components makes total sense and is a viable solution, but how can I prevent this build error when working with the various utility classes and types exported by amCharts. 

For instance, I have util functions to control the color of Sankey nodes. In order to control this fill color, I need to use the amCharts color function, which I import as follows:
`import { color } from "@amcharts/amcharts5";` or `import { color } from "@amcharts/amcharts5/.internal/core/util/Color";`
I get the build error above. My question is how are we supposed to lazily import our own utility functions that consume amcharts helper utils. Also when importing various types, I don't think it's possible to lazily define types such as this: 
```
export type SelectedSankeyNode = SankeyNodeIdentifier & {
	rectangle: RoundedRectangle; // amCharts type
};
```
Any guidance you have would be greatly appreciated, as I would like to avoid module transpiling if possible. Thanks so much.

**Comment by alienbuild** [comment]
> @Pauan I have a question regarding this. I am concerned that the only solution at this point is transpiling modules as mentioned [here](https://github.com/vercel/next.js/issues/31518). Doing a dynamic import for actual components makes total sense and is a viable solution, but how can I prevent this build error when working with the various utility classes and types exported by amCharts.
> 
> For instance, I have util functions to control the color of Sankey nodes. In order to control this fill color, I need to use the amCharts color function, which I import as follows: `import { color } from "@amcharts/amcharts5";` or `import { color } from "@amcharts/amcharts5/.internal/core/util/Color";` I get the build error above. My question is how are we supposed to lazily import our own utility functions that consume amcharts helper utils. Also when importing various types, I don't think it's possible to lazily define types such as this:
> 
> ```
> export type SelectedSankeyNode = SankeyNodeIdentifier & {
> 	rectangle: RoundedRectangle; // amCharts type
> };
> ```
> 
> Any guidance you have would be greatly appreciated, as I would like to avoid module transpiling if possible. Thanks so much.

You should be able to use refs to directly manipulate.
