### ISSUE TITLE
Graph jolts upwards on 'pointerdown' or 'click' event

### ISSUE THREAD

**Issue by bye7** [amcharts/amcharts5#773]
**Bug description**
When interacting with the graph after using 'pointerdown' or 'click' event listeners `chart.events.on("pointerdown");`, an unexpected upward movement of the graph occurs. I have opened the [Line Chart Demo](https://www.amcharts.com/demos/line-chart-adding-data-every-second/) in [CodePen](https://codepen.io/bye7/pen/ExppgGY) and added the one line code at the end.

To reproduce, simply click anywhere inside the chart, you will notice it will pan slightly upwards.

**Environment**
AmCharts 5.3.0 library
Chrome v109.0.5414.120 64-bit

**Comment by zeroin** [comment]
We know this, but we don't have a fix for that. I recommend adding click events on plotContainer instead:

`chart.plotContainer.events.on("pointerdown");`

**Comment by bye7** [comment]
Great, that works as intended.
