### ISSUE TITLE
Avoiding onClick event for legends when event registered to the root.dom property

### ISSUE THREAD

**Issue by FarrukhZeb** [amcharts/amcharts5#776]
So what I am working on is to handle the event dispatcher for the whole chart. **Required: Where ever the user clicks on the chart will dispatch the event**. The event is registered using the following method
```
import { utils } from '@amcharts/amcharts5';
utils.addEventListener(root.dom, 'click', () => {
  // Do something
})
```
Now this also executes the default legend event too which I want to avoid. How can I execute an onClick handler on the whole chart except the legend section?
Also if you are going refer me to Series event registering then I don't want that it will only trigger on clicking the lines/bars.

**Comment by martynasma** [comment]
Just to make sure you don't want to register ANY built-in events on chart components except your custom click event OR you still want built-in click events except on legend?

For the latter, please read here:
https://www.amcharts.com/docs/v5/concepts/legend/#Altering_functionality

**Comment by FarrukhZeb** [comment]
@martynasma 
Well not sure, but best to have built-in events too. For now we the use case is to click on the whole chart we've already set up the handler but it also executes on clicking the legend bullets.

**Comment by FarrukhZeb** [comment]
Okay I've got it I just had to set an event on the `chart.plotContainer` 
```
chart.plotContainer.events.on('click', this.handleOnBarClick);
```
