### ISSUE TITLE
Chart above another chart using the same xaxis

### ISSUE THREAD

**Issue by morrow95** [amcharts/amcharts5#777]
I am attempting to show a column chart (or a line chart would work too) above a gannt chart using the same xaxis (timestamp) and having trouble with spacing as well as getting any data to show in the column chart.  I don't even know if this is possible to do, but the help docs made it sound like it was so I am more than likely missing quite a few things in the configuration or doing things wrong.

I've created a [codepen](https://codepen.io/scubapongo/pen/GRBYwYw) with what I have so far.  The original gannt chart shows fine, then I am able to get the column chart's yaxis to show (although it overlaps the gannt instead of being above it and does not show any data).

Any assistance/explanation with this would be appreciated.

**Comment by zeroin** [comment]
To solve axis overlapping you should set:

`chart.leftAxesContainer.set("layout", root.verticalLayout);`

like in this demo: https://www.amcharts.com/demos/vertically-stacked-axes-chart/

As for the second series - as baseInterval of your xAxis is 1second, the columns are very thin and you do not see them. If you enable stroke, you will see them. Or you can set width for the columns to some `width:am5.percent(3600)`  or so.

**Comment by morrow95** [comment]
Thank you - that helped solve some things, but ended up bringing more issues.  I created another [codepen](https://codepen.io/scubapongo/pen/NWBejrd) with what I now have currently.  I 'solved' the column width issue by using start/end timestamp values that will show better with the seconds information below.  Currently I am facing the following issues I can't seem to get around : 

- Tooltips do not want to show on the column chart in the codepen (they do in my own test env though).  In my test env I need to hover on the far right of each column (end timestamp) to show them.  I would prefer if any part of the column was hovered they would show.  Somewhat related is I expected snapping to occur on the column chart same as the gannt chart - it does not.

If I can get the above to work then that takes care of all the visual and usability aspects of the chart I was trying to do.  Of course, after that I need to tackle the export stuff, but don't expect too big of a problem with that.

**Comment by zeroin** [comment]
Do we talk about the bottom series tooltips? I can see them when moving a mouse, no need to hover over the exact position. If it's different on your dev environment and on codepen, then try to clear browser cache and check if you use the same versions. It should be the same.

**Comment by morrow95** [comment]
The top - the column chart.  The bottom works exactly as I expected.  I want the same tooltip behavior on the top columns as well.

**Comment by zeroin** [comment]
I am afraid with this setup the solution would be to set tooltip on columns instead of series:
https://codepen.io/team/amcharts/pen/YzjgOBa/8d027e8b0bc01a6e1d9e365a0d3927ae?editors=1010

However it might be a bit complicated to hover over the narrow columns.

**Comment by morrow95** [comment]
@zeroin Well, that example does work, but as you said it is tough to hover over the narrow columns on the bottom chart.  There is no way to snap on both of these?

The only other thing I thought of was keeping the tooltip how it was (snapping on the bottom chart) and then in each tooltip showing the top charts values.  I'm not sure if that is possible though since each chart has its own data source.  The way the information for this chart works is there will only ever be data in the top chart for a specific hour IF there is already data in the bottom chart.  I guess I'll play around with that tonight, but I have a feeling I won't be able to access the top chart's data in the bottom chart's tooltip to display them together.

**Comment by zeroin** [comment]
I imagine you could use the initial approach where cursor was snapped to the bottom series, then based on the `tooltipDataItem` of your bottom series search for the required data item in the top series and then simply do `dataItem.get("graphics").showTooltip()` to force-show tooltip of the column.
