### ISSUE TITLE
How we can place the bubbles on top of the stock chart line?

### ISSUE THREAD

**Issue by rafee11** [amcharts/amcharts5#782]
I am trying to create a line chart with bubbles on top of the stock chart line series for specified datetime(xaxis) and value(yaxis).
Here is the sample when we change the chart into line series, bubbles are placed as floating marked as red circle. I need to place the bubbles at the line series in yellow marked area.
 
https://codepen.io/rafee11/pen/vYabBrE

![image](https://user-images.githubusercontent.com/23078836/216586524-459b5954-62db-4758-bce8-87a317120758.png)

**Comment by martynasma** [comment]
Please refer to this tutorial on how to add bullets to series:
https://www.amcharts.com/docs/v5/charts/xy-chart/series/#Bullets
