### ISSUE TITLE
Overwriting some colours in heatRules in the customFunction

### ISSUE THREAD

**Issue by jdim** [amcharts/amcharts5#783]
I'm happy with yellow and green colours, but I need to fill weekends in grey (repaint the pre-calculated color).

<img width="1350" alt="Screenshot 2023-02-03 at 18 02 08" src="https://user-images.githubusercontent.com/8625641/216663067-9faffe1a-d4d6-4870-b1ac-c8de8e3af6b2.png">

Trying to use customFunction but I get the default blue color for negative cases.

<img width="1350" alt="Screenshot 2023-02-03 at 18 03 11" src="https://user-images.githubusercontent.com/8625641/216663233-229337c7-01ed-4500-81c2-ce08f2743816.png">

```ts
// Set up heat rules
      // https://www.amcharts.com/docs/v5/concepts/settings/heat-rules/
      series.set('heatRules', [
        {
          target: series.columns.template,
          dataField: 'value',
          min: minColor,
          max: maxColor,
          key: "fill",
          customFunction: function (sprite, min, max, value) {
            const di = sprite.dataItem;

            if (di) {
              // @ts-ignore
              const periodDate = di.dataContext?.periodDate;

              if (isWeekend(periodDate)) {
                // @ts-ignore
                sprite.set('fill', colors.weekend);
              } else {
                // don't touch the precalculated  color (spectre)
                // ...👆👆👆
              }
            }
          },
        },
      ]);
```

**Environment (if applicable)**

 - amCharts version 5
 - Browser - Chrome
 - TypeScript

I would very appreciated for any ideas how to implement this.
Thanks.

**Comment by xorspark** [comment]
You can use the Color's [interpolate method](https://www.amcharts.com/docs/v5/reference/color/#interpolate_method) to calculate the correct fill in your else case, e.g.

```
sprite.set('fill', am5.Color.interpolate((value - min) / (max - min), am5.color(0xfffb77), am5.color(0xfe131a), "rgb"))
```
