### ISSUE TITLE
Helpful Error Logs

### ISSUE THREAD

**Issue by TurtIeSocks** [amcharts/amcharts5#784]
**Bug description**

Thank you for the very intriguing library!

I was wondering if it'd be possible to add error logs that are a bit more user friendly and provide some hints on the context of the issue. Currently the errors are just the stack trace and due to the complexity of the library, it's quite difficult to get a meaningful takeaway from them in order to debug the issue at hand.

**Comment by martynasma** [comment]
Thank you.

There are no error logs, I'm afraid. Most errors are result of something unexpected happening out of configuration. Unexpected means we can't document it. Besides having exceptions handle everything would not only slow down, but also bloat up the library.

Most of the errors can be avoided by closely following the documentation.

Hope that sounds reasonable.
