### ISSUE TITLE
How to rotate labels only for period change date?

### ISSUE THREAD

**Issue by bye7** [amcharts/amcharts5#785]
**Question**

How can I rotate only the periodChangeDate label on the x-axis to -90? New data is being added every second and the chart allows zoom and pan interactions.

I wasn't sure how to track periodChangeDate, so instead I've tried to rotate the minute mark, but when I zoom-in/out and pan, the wrong label becomes rotated and when I zoom-out to a certain distance I get `Uncaught TypeError: Cannot read properties of undefined (reading 'get')` error using the following code:

```JS
let xRenderer = xAxis.get("renderer");
xRenderer.labels.template.adapters.add('rotation', (rotation, target) => {
    let dateTime = target.dataItem.get("value");
    if (dateTime == am5.time.round(new Date(dateTime), "minute", 1).getTime()) {
      return -90;
    } else {
      return 0;
    }
  });
  ```

**Environment (if applicable)**
AmCharts v5.3.2

**Comment by martynasma** [comment]
Good question. There's nothing in the dataItem that would allow us to determine whether the label is for the period change or a regular one.

Let me put another workaround on the table:

```JavaScript
xAxis.get("periodChangeDateFormats")["day"] = "_MMM";

let xRenderer = xAxis.get("renderer");
xRenderer.labels.template.adapters.add('text', (text, target) => {
  console.log(text)
  if (text && text[0] == "_") {
    target.setAll({
      rotation: -90,
      centerY: am5.p50
    });
    return text.substr(1);
  }
  return text;
});
```

If the above does not make sense, we're adding an underscore to a period change format so that we can recognize it in the adapter.

We also use an adapter for `text` to remove the underscore and rotate the labels that have it.

**Comment by martynasma** [comment]
Example:
https://codepen.io/team/amcharts/pen/YzjBmWr/c88d55478ddf70010fefccb8ca337fe6

**Comment by bye7** [comment]
In the CodePen example you've shared, why are other labels that are not formatted as "_MMM" are rotated?
These two shouldn't be rotated. I was also having the same issue testing it on my end:
![image](https://user-images.githubusercontent.com/82799248/216800931-55baad59-e677-4e4a-b2bc-cbfa24aaf9c0.png)

**Comment by martynasma** [comment]
They aren't for me, but it probably depends on exact with of the chart.

I have updated the CodePen. Let me know if they're still rotated for you.

**Comment by bye7** [comment]
Those labels don't rotate anymore on your example code. I will see how they work on my end.

**Comment by bye7** [comment]
Thanks, it's working as intended. Although, the labels that are not rotated had gaps above them and it was not aligned with the rotated label, the following code resolved that:
``` JS
xRenderer.labels.template.adapters.add('text', (text, target) => {
  console.log(text)
  if (text && text[0] == "_") {
    target.setAll({
      rotation: -90,
        centerY: am5.p50,
        centerX: am5.p100
    });
    return text.substr(1);
  }
  else {
    target.setAll({
      rotation: 0,
        centerY: am5.p0,
        centerX: am5.p50
    });
  }
  return text;
});
```
