### ISSUE TITLE
Dynamically changing series stroke doesn't show when grouping

### ISSUE THREAD

**Issue by zola-25** [amcharts/amcharts5#786]
I have a button that highlights a particular section of an XY line, by dynamically adding a strokeSettings template field to the start data item (and removing it at the end).

However it only shows the new stroke settings at the fully un-grouped level. When zoomed out, the styling remains the same:

Typescript:

```
            let xAxis = chart.xAxes.push(am5xy.DateAxis.new(root, {
                groupData: true,
                maxDeviation: 0.2,
                baseInterval: {
                    timeUnit: "minute",
                    count: 30
                },
                renderer: am5xy.AxisRendererX.new(root, {}),
                tooltip: am5.Tooltip.new(root, {})
            }));

            let yAxis = chart.yAxes.push(am5xy.ValueAxis.new(root, {
                ariaLabel: "kWh",
                renderer: am5xy.AxisRendererY.new(root, {})
            }));

            let consumptionSeries = chart.series.push(am5xy.LineSeries.new(root, {
                name: "Consumption",
                xAxis: xAxis,
                yAxis: yAxis ,
                valueYField: "consumptionKWh",
                valueXField: "dateTicks",
                valueYGrouped: "sum"
            }));

            consumptionSeries.strokes.template.setAll({
                templateField: "strokeSettings"
            });

           let myData: EnergyReading[] = [ { .... } ]

            consumptionSeries.data.setAll(myData);
```
```
public highlightPeriod(chart: Chart, startTicks: number, endTicks: number): void {

            let consumptionSeries = chart.series.getIndex(0)
            let startIndex = (consumptionSeries.data.values as EnergyReading[]).findIndex(c => c.dateTicks === startTicks);
            let endIndex = (consumptionSeries.data.values as EnergyReading[]).findIndex(c => c.dateTicks === endTicks);

            let existing = consumptionSeries.data.getIndex(startIndex) as any

            existing.strokeSettings = {
                stroke: am5.color(0x990000),
                strokeDasharray: [3, 3]
            }

            consumptionSeries.data.setIndex(startIndex, existing)

        }
```

Displays correctly when not grouped: 
<img width="572" alt="image" src="https://user-images.githubusercontent.com/29863888/216798272-28d06d97-5b59-41d2-9552-6d3b41cb183d.png">

Once I zoom out, the new stroke settings stop being applied:
<img width="444" alt="image" src="https://user-images.githubusercontent.com/29863888/216798294-16dbe4a6-ef1a-4d58-9a92-f3a36d49194c.png">

How do I get the new stroke settings to apply to the grouped data? Will I have to somehow include them in a custom aggregate function?

**Comment by martynasma** [comment]
When data is aggregated, only numeric values are calculated and included into the group data item.

There's really no way how to interpolate/group data included in data objects the `templateField` is referencing to.

In your case, you'd probably better off using axis ranges to apply different styling to part of the line series:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/axis-ranges/#series-axis-ranges

**Comment by zola-25** [comment]
Thanks @martynasma , I used axis ranges instead and it worked fine
