### ISSUE TITLE
Can a chart with ValueAxis for both x and y axes have axis autoscaling enabled?

### ISSUE THREAD

**Issue by krista-prokop** [amcharts/amcharts5#789]
in [this codepen](https://codepen.io/krista-prokop/pen/JjBVgaK) I am using `ValueAxis` for both x and y axes. I note that when zooming in on the left side of the chart the Y axis does not autoscale. If I change the x axis to a `DateAxis` on line 61, zooming in on the left side does autoscale the Y axis.

 [This issue from amcharts4](https://github.com/amcharts/amcharts4/issues/1527) seems to be the same issue. I want to confirm that this is indeed still the case in amcharts5? Is there now support to be able to natively autoscale a ValueAxis chart?

**Comment by zeroin** [comment]
It's by design. However you can do it form outside, with this particular example that would be:

```

xAxis.on("start", function() {
  autoZooom();
})

xAxis.on("end", function() {
  autoZooom();
})

function autoZooom() {
  var start = xAxis.get("start", 0);
  var end = xAxis.get("end", 1);

  var min = Infinity;
  var max = -Infinity;

  chart.series.each(function(series) {
    var startItem = xAxis.getSeriesItem(series, start);
    var endItem = xAxis.getSeriesItem(series, end);
    if (startItem && endItem) {
      var startIndex = series.dataItems.indexOf(startItem);
      var endIndex = series.dataItems.indexOf(endItem);

      for (var i = startIndex; i < endIndex; i++) {
        var valueY = series.dataItems[i].get("valueY", 0);
        if (valueY < min) {
          min = valueY;
        }
        if (valueY > max) {
          max = valueY;
        }
      }
    }
  })

  var startPos = yAxis.valueToPosition(min);
  var endPos = yAxis.valueToPosition(max);

  //yAxis.set("start", startPos)
  //yAxis.set("end", endPos)
  yAxis.zoom(startPos, endPos);
}
```

Codepen: https://codepen.io/team/amcharts/pen/QWBRdjE

We do not auto-zoom the axis because most often in XY chart with two value axes data is not sorted. If it's not sorted, then istead of finding start and end indexes like I suggested, you will have to loop through all the data, which is quite costly.
