### ISSUE TITLE
Epoch timestamps from hourly resolution OHLC data are not converting correctly

### ISSUE THREAD

**Issue by Quantmatic** [amcharts/amcharts5#79]
I have an hourly OHLC dataset, the epoch times are correct, verified using epochconverter.com

But am5 is not converting the timestamps correctly, it sees 
1970-01-19 23:44:02
1970-01-19 23:44:06
1970-01-19 23:44:27

But the real dates are like - Tuesday, November 16, 2021 1:00:00 PM

The only way I could get it to display the chart is by using the base interval with 
```
            baseInterval: {
                timeUnit: "second", count:1
            },
```
[Screenshot](https://i.postimg.cc/027JcyqH/Screenshot-2021-11-17-at-12-52-51.png)

Data sample:
`
      var data = [
        {
          "close": 60974.55,
          "date": 1637042400,
          "high": 61505.36,
          "low": 60822.18,
          "open": 61247.69,
        },
        {
          "close": 60871.59,
          "date": 1637046000,
          "high": 61033.82,
          "low": 60343.34,
          "open": 60969.91,
        },
        {
          "close": 60822.02,
          "date": 1637049600,
          "high": 61090.74,
          "low": 60452.32,
          "open": 60871.59,
        },
        {
          "close": 61024.25,
          "date": 1637053200,
          "high": 61056.33,
          "low": 60608.22,
          "open": 60822.03,
        },
        {
          "close": 60202.82,
          "date": 1637056800,
          "high": 61295.73,
          "low": 60175,
          "open": 61024.75,
        },
        {
          "close": 60196.41,
          "date": 1637060400,
          "high": 60340.09,
          "low": 58638,
          "open": 60201.21,
        },
        {
          "close": 60615.95,
          "date": 1637064000,
          "high": 60688.66,
          "low": 60100,
          "open": 60196.21,
        },
        {
          "close": 60060.83,
          "date": 1637067600,
          "high": 60888,
          "low": 60049.73,
          "open": 60615.94,
        },
        {
          "close": 60615.1,
          "date": 1637071200,
          "high": 60786.92,
          "low": 60058.39,
          "open": 60069.59,
        },
      ]; 
`

**Comment by martynasma** [comment]
The timestamps in your data translate to Jan 19, 1970. Why would they need to be displayed as 2021?

![image](https://user-images.githubusercontent.com/1458520/142214647-4847c966-0a47-440c-b9a9-295b339e100a.png)

**Comment by Quantmatic** [comment]
That's node doing this...

This is recent bitcoing data
[Epochconverter](https://i.postimg.cc/WzX75GCj/Screenshot-2021-11-17-at-14-05-38.png)

**Comment by martynasma** [comment]
OK, thing is that JavaScript timestamps are in milliseconds. Just * 1000 all timestamps ;)
