### ISSUE TITLE
axisBreaks in v5?

### ISSUE THREAD

**Issue by olneyMatt** [amcharts/amcharts5#791]
Hi,

Can you tell me if the `axisBreaks` functionality [that was in v4](https://www.amcharts.com/docs/v4/concepts/axes/#Breaks) has been carried over to v5 please?

If not, are there any plans to add it?

Thanks for all your work
Cheers
Matt

**Comment by zeroin** [comment]
No, we do not have plans to implement it. It's a really heavy, code and cpu consuming thing which was not very popular, so we decided not to implement it.

**Comment by olneyMatt** [comment]
Understood - thanks for the quick response.

Regards
Matt
