### ISSUE TITLE
XY Chart cursor ev.point offset results in wrong values

### ISSUE THREAD

**Issue by koenreijns** [amcharts/amcharts5#793]
**Bug description**
Click event on an XY Chart does not relate to actual x/y position but relative in the browser.

I'm trying to grab the clicked data point on a chart when an user clicks on an x-axis. This is captured by the 'globalpointerup' event and extracted from the ev.point.x details.

The returned X point actually includes the margin / space used left of the graph to display the Y axis labels and therefor results in an incorrect result retrieving the data via a positionToValue call.

Example repo: https://angular-abqcge.stackblitz.io/
Click on the 1.0m axis and check the console output.

<img width="463" alt="image" src="https://user-images.githubusercontent.com/65684646/217547961-56ec0703-791d-475c-adfd-3c7d825c06f2.png">

Steps:
 - Click 1.0m line
 - Returned ev.point.x value is in my example: 237.369
 - Converted value via positionToValue(ev.point.x) is 570.48593
 - Expected value from positionToValue would be 1.0

**Environment (if applicable)**

 - amCharts version: 5.3.2
 - Browser and its version: Microsoft Edge, Version 109.0.1518.78 (Official build) (x86_64)
 - Related frameworks and their versions: Angular 15.1.x

**Additional context**
-

**Comment by martynasma** [comment]
This is how to convert document X to a value on an axis:

```JavaScript
const local = xAxis.toLocal({x: ev.point.x, y: ev.point.y});
const value = xAxis.positionToValue(xAxis.coordinateToPosition(local.x));
```

**Comment by koenreijns** [comment]
Thanks, this indeed fixes the problem I had retrieving the clicked value.
