### ISSUE TITLE
Can't change the tooltip on rectangle's on Treemap chart

### ISSUE THREAD

**Issue by jdim** [amcharts/amcharts5#794]
Seems I can't set a new tooltipText on Treemap.

Also, how to hide Tooltips?

The example from tutorial doesn't work.
`series.rectangles.template.set("tooltipText", "{category}: [bold]{sum}[/]");`

https://www.amcharts.com/docs/v5/charts/hierarchy/treemap/#Tooltips

CodePen example (see 👇 in code)
https://codepen.io/dm-khabarov/pen/qByGYVd

 - amCharts version 5
 - Browser Chrome
 - Related frameworks: TypeScript, React

**Comment by martynasma** [comment]
Thanks for the heads up.

The documentation is wrong in this case. `tooltipText` should be set on the node instead:

```JavaScript
series.nodes.template.set("tooltipText", "{category}: [bold]{sum}[/] my text)))");
```

We're fixing the docs now, as well.
