### ISSUE TITLE
The tooltip implemented via the adapter does not want to show grouped values

### ISSUE THREAD

**Issue by rocketsan** [amcharts/amcharts5#795]
**Bug description**

I'm using the source code from adapter tutorial to display a combined tooltip on my chart. Link to tutorial - https://www.amcharts.com/docs/v5/tutorials/combining-tooltip-values-from-multiple-series/
This works fine until my data is grouped. If I enable the grouping option, the values in the tooltip become incorrect.

```
groupData: true // in DateAxis
valueYGrouped: "sum" // in Series
```

I have sketched a chart example that shows a linear graphic with daily random values - https://jsfiddle.net/odpubc5s/ 
The data is grouped into 7 days. 
The tooltip implemented through the adapter shows incorrect data.
The error is that it displays detailed values instead of grouped ones.

![image](https://user-images.githubusercontent.com/4901801/217804069-a86db735-b06a-4fdb-a685-ae1c427d71a2.png)

The part of the code where the error may occur:
```
  tooltip.label.adapters.add("text", function(text, target) {
    chart.series.each(function (series) {
      text += '\n[' + series.get("stroke").toString() + ']●[/] [bold width:100px]' + series.get("name") + ':[/] {' + series.get("valueYField") + '}'
    })
    return text
  })
```

**Environment (if applicable)**

amCharts Version 5

**Comment by martynasma** [comment]
Grouped data points do not retain original data context, so you can't reference them with data placeholders.

What you can do in your adapter, is grab a value from the grouped data item: `series.get("tooltipDataItem")`.

```JavaScript
tooltip.label.adapters.add("text", function(text, target) {
  chart.series.each(function (series) {
    var dataItem = series.get("tooltipDataItem");
    if (dataItem) {
      text += '\n[' + series.get("stroke").toString() + ']●[/] [bold width:100px]' + series.get("name") + ':[/] ' + dataItem.get("valueY");
    }
  })
  return text
})
```

**Comment by rocketsan** [comment]
Thanks for the solution!
