### ISSUE TITLE
use explicit path

### ISSUE THREAD

**Issue by jimmywarting** [amcharts/amcharts5#797]
tried to simple load this over a CDN, and it breaks for not having explicit path

extension-less path is a bad practices (it's not how the web works)

Take this for example:
https://cdn.jsdelivr.net/npm/@amcharts/amcharts5@5.3.3/themes/Animated.js
```js
import { AnimatedTheme } from "../.internal/themes/AnimatedTheme";
export default AnimatedTheme;
//# sourceMappingURL=Animated.js.map
```
it can't find `themes/AnimatedTheme` cuz it is not explicit
it needs to point to
```js
import { AnimatedTheme } from "../.internal/themes/AnimatedTheme.js";
```

**Comment by Pauan** [comment]
The NPM package is designed to be bundled with something like Webpack or Rollup, which is standard practice for the web.

If you want to load the JS files directly in the browser, then you must use our pre-compiled CDN, which can be found here:

https://www.amcharts.com/download/

**Comment by jimmywarting** [comment]
those are not esm so i can't use `import` syntax...
either way i think it's best to have explicit path anyways

**Comment by Pauan** [comment]
Even if we used explicit paths, our dependencies don't, so it still won't work in the browser. Most npm packages are not designed to be run directly in the browser.

And the browser doesn't support npm packages inside `node_modules`, so you need to use either [import maps](https://github.com/WICG/import-maps) (which requires pre-compilation), or bundling with Webpack (which also requires pre-compilation).

There is just no way to avoid pre-compilation if you are deploying to the browser.
