### ISSUE TITLE
remove Chord node when node dies

### ISSUE THREAD

**Issue by jimmywarting** [amcharts/amcharts5#798]
Hi, i'm relative new to amcharts5 and it's a wonderful tool. but i'm not really sure what to search for to get the right answer i'm looking for

I'm using a Chord
```js
var series = root.container.children.push(am5flow.ChordNonRibbon.new(root, {
  sourceIdField: "from",
  targetIdField: "to",
  sort: "ascending",
  linkType: "line"
}))
```
and when new nodes join then i call: `series.data.push`
```js
function onNewNode(id, to, value) {
  series.data.push({ from: id, to, value })
}
```
But nodes can also leave the Chord ring, so i would like to remove all bullets, links, nodes. and this is what i need help with.
```js
function onNodeClose(id) {
  // series.data.removeIndex(x)
  // TODO: help
}
```
i have tried `series.data.removeIndex(x)` but that only remove one line between two nodes
if a node dies then i would like to remove all associated links and bullets and also remove the node from the circle.

i need to remove one node that is connected to many

**Comment by martynasma** [comment]
Well, the link is the data item for series. It also creates nodes that need to be removed.

```JavaScript
// Remove link
const dataItem = series.dataItems[x];
series.data.removeValue(dataItem.dataContext);

// Remove source
series.nodes.data.removeValue(dataItem.get("source").dataContext);

// Remove target
series.nodes.data.removeValue(dataItem.get("target").dataContext);
```

**Comment by jimmywarting** [comment]
Thanks for the tip, will try it out right now and report back how it goes 🙏 

Will close this (not really a bug, more of a question at this point)
can keep discussion going even if this is closed... 

PS. have you considered enabling discussion on this repo? 
it is good for things that aren't really bug, issues or tasks (todos)

**Comment by jimmywarting** [comment]
Hmm, whenever i remove links, source and target then the other existing lines will kind of be incorrectly pointed to the correct peer

**Comment by jimmywarting** [comment]
manage to reproduce in fiddle: https://jsfiddle.net/tyr2f3o1/

**Comment by martynasma** [comment]
Turns out flow chart might be doing a bit more data wrangling, so removing just these two might not be enough.

This works though:

```JavaScript
series.data.setAll(series.data.values.splice(0, 1));
```
