### ISSUE TITLE
Show tooltips programmatically

### ISSUE THREAD

**Issue by nizhnikovskiy** [amcharts/amcharts5#8]
If try to display tooltip programmatically, then it isn't displayed until you hover over it. After hover over element, then the tooltip can be correct display programmatically.

Demo: https://codepen.io/nizhnikovskiy/pen/powpgRG?editors=0010

**Comment by martynasma** [comment]
Well, `circle` holds a template object, which is used to create actual bullets, but is not drawn on screen. So you would need to dig for actual bullet and display tooltip for it.

Furthermore, there's only a single `Tooltip` object for the whole series, so if you want to show multiple tooltips, you will need to create an individual tooltip for each bullet.

```JavaScript
  var circle = am5.Circle.new(root, {
    radius: 7,
    tooltipText: "Drag me!",
    cursorOverStyle: "pointer",
    tooltipY: 0,
    fill: am5.color(0xffba00),
    stroke: root.interfaceColors.get("background"),
    strokeWidth: 2,
    draggable: true,
    tooltip: am5.Tooltip.new(root, {})
  });
  
  showTooltipsButton.addEventListener('click', () => {
    am5.array.each(pointSeries.dataItems, function(dataItem) {
      am5.array.each(dataItem.bullets, function(bullet) {
        console.log(bullet)
        bullet.get("sprite").showTooltip();
      })
    })
  });  
```

One other thing, you should probably move out code that adds "click" handler to your custom button out of the bullet creation function.

Right now it will add multiple click events for each bullet created.

https://codepen.io/team/amcharts/pen/8e3ea83001aa919e036f5df3e3ae3111?editors=0010

**Comment by nizhnikovskiy** [comment]
Thanks, you help me, it works!
