### ISSUE TITLE
use real private class fields `#`

### ISSUE THREAD

**Issue by jimmywarting** [amcharts/amcharts5#800]
all this public/private and prefixed `_` names makes it to a kind of soup. it would clear things up if you instead used `#` instead for both fields and methods

**Comment by martynasma** [comment]
Do you mean properties of objects that are prefixed by an underscore?

Those are for internal use only and should never be used.

Or is it about something else?

**Comment by martynasma** [comment]
BTW, we have discussed using `#` privates at some point, and decided against it for two reasons:

1) They may introduce a slight performance penalty.
2) Makes it harder to debug chart setups at runtime.
