### ISSUE TITLE
HTML elements do not appear on export

### ISSUE THREAD

**Issue by CharlotteCutler** [amcharts/amcharts5#803]
**Bug description**

https://codepen.io/Charlotte-1/pen/rNZNmJR

When exporting as pdf, png or jpg, html elements do not show. (in the example, the x axis renderer labels (with text "Description") do not appear in the exported file).

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
HTML elements cannot be exported I'm afraid. There's no way around it.
