### ISSUE TITLE
Dateaxis ticks do not align(vertical)

### ISSUE THREAD

**Issue by Kshitij-Gajbhiye** [amcharts/amcharts5#804]
I have a Dateaxis as my X axis. When I am trying to plot any values for a particular time the cursor is pointing to the middle position which should not be the case as you can see in the picture below.

![image](https://user-images.githubusercontent.com/125353158/218959424-10f1ab7a-adfc-4f19-b5ca-64d809029da0.png)

Similar issue was reported in Amcharts V4. Link to the issue -> https://github.com/amcharts/amcharts4/issues/1415

Here is my code for the DateAxis. Am I missing something? The cursor aligns properly if I set the count to 1 in baseInterval.

```
var xAxis = chart.xAxes.push(
      am5xy.DateAxis.new(root, {
        maxDeviation: 0.2,
        baseInterval: {
          timeUnit: "minute",
          count: 15,
        },
        renderer: am5xy.AxisRendererX.new(root, {}),
        tooltip: am5.Tooltip.new(root, {}),
      })
    );
    xAxis.children.push(
      am5.Label.new(root, {
        text: `[bold]Time`,
        x: am5.p50,
        centerX: am5.p50,
      })
    );
```

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
