### ISSUE TITLE
Amchart testing with Vitest + Vite + Vue 2

### ISSUE THREAD

**Issue by KaskoYurii** [amcharts/amcharts5#805]
Hello. 
I'm using Amcharts on the Vue2 project with Vitest + Vite. 
packages: 
` "vite": "^3.0.9",
   "vitest": "^0.28.1",
    "vue": "^2.7.8",
     "jsdom": "^21.1.0",
     "@amcharts/amcharts5": "^5.2.29"
     `

When I write a test for the component that includes a chart I have errors: 

> Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
    at module.exports (node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)

And 

> TypeError: The provided value is not of type 'Element'.
> Root.value node_modules/@amcharts/amcharts5/.internal/core/Root.js:1830:22
>     1828|      * licenses for removal of amCharts branding from charts.
>     1829|      *
>     1830|      * The only legit way to do so is to purchase a commercial license for amCharts:
>        |                      ^
>     1831|      * https://www.amcharts.com/online-store/
>     1832|      *
>   This error originated in "name.test.js" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.

How I can run the test for Amchart properly?

**Comment by Pauan** [comment]
Vitest is quite similar to Jest, so you may be able to get it working by following these tutorials:

https://www.amcharts.com/docs/v5/getting-started/integrations/jest/

https://vitest.dev/guide/migration.html#migrating-from-jest

In particular, you need to install the `canvas` npm package, you need to [set the environment to `jsdom`](https://vitest.dev/config/#environment), and you may need to setup Babel.

**Comment by KaskoYurii** [comment]
After installing `canvas` got the error `Error: Module did not self-register: canvas.node`. 

- Installed packages for Ubuntu from Readme of canvas:
`sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev`
- Trying to disable `threads: false` - no changes. 

Maybe exist another way to run it on Vite + Vitest?

**Comment by Pauan** [comment]
The `canvas` library is necessary because amCharts uses the `<canvas>` element.

You should be able to [fix that error by setting `threads: false`](https://github.com/vitest-dev/vitest/issues/1982).

If you can't get it working with `canvas` + `jsdom` then your only option is to run the tests in a browser.
