### ISSUE TITLE
am5percent, how do I not display labels when value is 0

### ISSUE THREAD

**Issue by mrfour44** [amcharts/amcharts5#806]
**Question**
I want to show no label in Pipe Chart when some value is 0. Is there any method to support it?

**Environment (if applicable)**

**Additional context**

**Comment by xorspark** [comment]
You can use an adapter to hide the label if it is zero:

```
series.labels.template.adapters.add("visible", function(hidden, target) {
  return target.dataItem.get("value") > 0;
});
```

**Comment by mrfour44** [comment]
ok,i got it. thx
