### ISSUE TITLE
Combination Line and Bar Chart - Series zIndex

### ISSUE THREAD

**Issue by IMTanuki** [amcharts/amcharts5#808]
**USE CASE**
Hi - I have 2 functions to declare a line series and column series, respectively. I'd like to change the zIndex such that line series sits on top of the column series. 

**QUESTION**
Where do I set the zIndex for a series?

**NOTES**
Not finding anything in V5 doc re zindex. The only doc is for V4: 
Ordering zIndex of series lines and bullets
(https://www.amcharts.com/docs/v4/tutorials/ordering-zindex-of-series-lines-and-bullets/)

I see the following from the sample codepen in the V4 page above:
chart.seriesContainer.zIndex = 10;

...but setting zindex for the chart.seriesContainer will affect both series.

**OTHER**
I flipped the order of the function calls so that the line series was declared second:
- _this brought the line series to the top (above the column series)_
- _but it caused the chart legend to duplicate the line series reference (legend shows units, sales, units)_ 

```
initChartSeriesColumn ( data, "Sales", "Sales", valueXFieldName );
initChartSeriesLine ( data, "Units", "Units", valueXFieldName );
```

**SERIES DECLARATIONS**
```
	function initChartSeriesLine ( data, seriesName, valueYFieldName, valueXFieldName ) {
		let series = chart.series.push (
			am5xy.LineSeries.new ( root, {
				name: seriesName,
				xAxis: xAxis,
				yAxis: yAxisLeft,
				valueYField: valueYFieldName,
				categoryXField: valueXFieldName,...
			} ) );

	function initChartSeriesColumn ( data, seriesName, valueYFieldName, valueXFieldName ) {
		let series = chart.series.push ( am5xy.ColumnSeries.new ( root, {
			name: seriesName,
			xAxis: xAxis,
			yAxis: yAxisRight,
			valueYField: valueYFieldName,
			categoryXField: valueXFieldName,...
			} ) );
```

**Comment by martynasma** [comment]
The order of pushing series into `chart.series` will determine how they are laid out.

If you need column series to absolutely be behind line series, you can use `chart.series.unshift()` instead of `push()`.

If you need to change order dynamically, you can use `chart.seriesContainer.moveValue()` method, e.g.:

```JavaScript
chart.seriesContainer.children.moveValue(series2); // Move series to the end
chart.seriesContainer.children.moveValue(series2, 0); // Move series to the start
```

**Comment by IMTanuki** [comment]
unshift works perfectly!

Thanks so much!
