### ISSUE TITLE
Pie Chart with Broken Down Slices - Slice Tooltips

### ISSUE THREAD

**Issue by IMTanuki** [amcharts/amcharts5#809]
**USE CASE**
Trying to customize pie chart slice tooltips using a tooltip object - the slice tooltip options are somewhat limited.

**ISSUE**
Either of the following work fine:
- basic pie chart (no sub-slices broken out), tooltip object assigned to series.slices.template.
- advanced pie chart (sub-slices broken out on click), tooltip settings assigned directly to series.slices.template (no tooltip object)

But the following does not work:
- advanced pie chart (sub-slices broken out on click), tooltip object assigned to series.slices.template.

When I use the latter method, clicking on a slice freezes the chart:
- slices cannot be expanded
- tooltips no longer appear

**ENVIRONMENT** 
- dev platform is IntelliJ
- chrome browser Version 110.0.5481.104 (Official Build) (64-bit)
- amcharts 5 via https://cdn.amcharts.com/lib/5...

TOOLTIP OBJECT
```
		// series tooltips
		var seriesTooltip = am5.Tooltip.new ( root, {
			keepTargetHover: true,																		
			autoTextColor: true,
			getStrokeFromSprite: false,
			getFillFromSprite: true,
			getLabelFillFromSprite: true,
			showTooltipOn: "hover",
			labelText:  "{type}:  {value}%",

			crisp: true,
			paddingLeft: 20,
			paddingRight: 20,
			paddingTop: 10,
			paddingBottom: 10,
			opacity: 1,
			scale: 1.1,

			//animationDuration: 100,
		} );
```

**TOOLTIP ASSIGNED TO SLICE**
```
		series.slices.template.setAll ( {
			tooltip: seriesTooltip,
		} );
```

**WORKAROUND**
update slices directly (limited tooltip settings)
```
		series.slices.template.setAll ( {
			// tooltip: seriesTooltip,
			showTooltipOn: "hover",
			tooltipText: "{type}:  {value}%",
                        etc...
		} );
```

**CODEPEN**
will update if needed - hoping there is an explanation for this...

Thanks!

**Comment by zeroin** [comment]
I am afraid we will need a codepen in order to help.

**Comment by IMTanuki** [comment]
Sorry! Looks like I had a bad parameter - everything works fine now!
