### ISSUE TITLE
Will there any plan to have scatter plot for thousands/hundred thousands data points?

### ISSUE THREAD

**Issue by LumineLittlelight** [amcharts/amcharts5#811]
Hi!

We really like amcharts for its features and animations.
However, we do face some difficulties with this library  when plotting scatter plot for many data points.
We need to revert to other library when it is compulsory for us to visualize scatter plots.

Will there be any plan on scatter plot development for thousands or hundred thousands data points?

Thank you.

**Comment by zeroin** [comment]
What kind of points do you expect to have - just some pixel (I would say anything else would make no sense with this amount of data)? If you don't need these points to be interactive, I could try some approach, but I don't think I could promise it to work fine with hundreds, more likely tens of thousands.

**Comment by LumineLittlelight** [comment]
Hi zeroin.

The interactivity expected is as long as the tooltip to see the data is responsive.
Tens of thousand will be good starting point. 
At the moment, when we try to visualize thousands (i.e 2000-5000), we start to feel it slows down.
This is a feedback for development onwards, if there is limitation for now I can understand the situation :)

Hopefully scatter plots can be further developed for amcharts because so far the limitation is to use bullets.
Currently, it is also not too straight forward either because technically we use line series, use the bullets and hide the line compared to other libraries.

At the moment we need to resort to other open source library like ECharts for massive scatter plots, like below.
https://echarts.apache.org/examples/en/editor.html?c=scatter-stream-visual 

I can understand that in terms of app perspective, hundreds of thousands scatter plot sometimes not intuitive if we can summarize it in bar chart or line chart form. But since our clients are from engineering field, they tend to use scatter plots for trending purposes.

Hope this can be accounted in for amcharts further development.

**Comment by zeroin** [comment]
I tested one idea and first tests are very promising. I guess I will add it to next release. Any chance you have sample data which we could use to illustrate this new possibility?

**Comment by LumineLittlelight** [comment]
Hi zeroin. 
The data itself is quite simple. Its just a random x and y coordinate that is iterated until the array size is 5000.

**Comment by zeroin** [comment]
Ok, so here is a demo:

https://codepen.io/team/amcharts/pen/XWPXQar

It has 15K data points but can handle a lot more, especially if you wont' add Animated theme.

The concept is that I do not add any bullets to the series (which is the main bottleneck, as each bullet is a separate object) and draw them on a separate canvas and then pass this canvas as an image to some canvasBullets Graphics which I create and add to a series. The cursor still works as it does not check the actual hover but looks for the most close points. 

You can modify the code to draw rectangles or any other shapes.

**Comment by LumineLittlelight** [comment]
Ah got it thanks zeroin for the demo. Let us review it if it can fulfill our requirements. Closing the thread.

**Comment by zeroin** [comment]
In v 5.3.6 we added beginPath() method to our CanvasGraphics class, so now you can achieve the same using our drawing API, which makes things a lot easier - no need to create a separate Canvas, no need to include resolution when calculating positions. 

Here is a demo: https://codepen.io/team/amcharts/pen/BaOQrKG

**Comment by pemberdom** [comment]
Hi @zeroin, if I may ask a question on that closed issue: the method levering the CanvasGraphics / beginPath is definitely faster 👍 , is there a plan to enhance the drawing feature to get it closer to what we can achieve through the series bullets:
- stroke
- path (or different shapes)
Thanks
