### ISSUE TITLE
How to access chart after load?

### ISSUE THREAD

**Issue by MissonHxC** [amcharts/amcharts5#813]
Hi,

I'm trying to change a gauge chart value via an AJAX request that update a lot of other stuff in my page (every 30 seconds).
With amChart 4, I'm doing this in the done event of my AJAX request.
```
brmsAmCharts.instances['AvgTemp'].hands.each(function (hand) {
  hand.showValue(data['TMax'], 600, am4core.ease.cubicOut);
});
```

But I can't seems to find a similar way with amChart 5.

Any idea?

Thanks a lot.

**Comment by martynasma** [comment]
Refer to this doc:
https://www.amcharts.com/docs/v5/charts/radar-chart/gauge-charts/#Dynamic_value

**Comment by MissonHxC** [comment]
Thank you for your answer.

I did see this doc but I didn't explain my problem well :(

The update of the value of my chart is done in a completely different context than the init of the chart. I'm in another file that handles a lot of AJAX requests.

The doc says to use `handDataItem.set("value", 20);` but I don't have access to `handDataItem` here.

Hence my question. With amCharts 4, I had access to the `hands` property and could use the `showValue` method to change the value.
With amCharts 5, I don't see how to find `handDataItem` outside the context of the chart creation.

**Comment by martynasma** [comment]
The same way you log chart instance in your application, you can log `handDataItem`, so you can reuse it when needed.

**Comment by MissonHxC** [comment]
Damn, I'm such an idiot. It was so simple :D
Sorry for wasting your time and thank you very much!
