### ISSUE TITLE
Pie Chart with Broken Down Slices - Mobile - Tooltips

### ISSUE THREAD

**Issue by IMTanuki** [amcharts/amcharts5#814]
USE CASE
User needs to emulate desktop hover on mobile devices to invoke a tooltip for a sub slice. For example - on a mobile device:
- user taps and holds on a on a slice (that has sub slices)
- slices tooltip is displayed
- user releases tap
- sub slices are displayed and the tooltip for the sub slice closest to the tap is displayed

But now the user wants to see tooltips for other sub slices - on a desktop:
- user hovers over other sub slices
- the sub slice tooltip is displayed

User would like to emulate similar behavior on a mobile device. To see another sub-slice tooltip:
- user taps and holds on another sub slice
- sub slice tooltip is displayed

ISSUE
A problem arises on mobile devices, since there is no real hover event. In the above use case, if the user wants to view a different sub slice:
- user releases tap (on first sub slice)
- at this point, the sub slices collapse back to the original main slice
- user then needs to tap on the main slice (a second time) to display the sub slices
- user can then tap and hold on the desired (second) sub slice to view its tooltip

TBH, _this is really a limitation of mobile devices, not an Amcharts bug_.

POSSIBLE WORKAROUND - QUESTION
Is there a way to display the tooltips for all sub slices (only when sub slices are displayed)? 
- user taps on a main slice to expand chart
- all sub slice tooltips are displayed
- user taps again to collapse sub slices
- all sub slice tooltips are no longer displayed

SERIES LABELS and TICKS
These really don't look good on a mobile device, since they crowd the chart or sometimes appear off screen, so they're not really a viable alternative to tooltips.

CODEPEN
No codepen - pls try [Amcharts demo](https://www.amcharts.com/demos/pie-chart-broken-slices/). on a mobile device.

Thanks!

**Comment by martynasma** [comment]
Do you imagine any reasonable solution to this?

Maybe do not collapse slices on click, but display zoom out button instead? Like in slice grouper:
https://www.amcharts.com/docs/v5/charts/percent-charts/grouping-slices/#Example

**Comment by IMTanuki** [comment]
So, again, this is a mobile constraint. Probably not the most important feature request, but I think a setting to display all sub-slice tooltips would be great - for mobile only
- tap on primary slice
- expand all sub-slices and display all tooltips

- tap again on any sub-slice
- all sub-slices collapse back to the primary and all sub-slice tooltips disappear

Advantages over labels and ticks:
- these are always displayed to the side / above pie charts
- no room on mobile devices
- label and tick font formatting not super readable 

whereas tooltips:
- designed to float on top of slices (columns, etc)
- already have collision logic, so they won't conflict with each other

I think it's a pretty good idea!

**Comment by martynasma** [comment]
I see this as a matter of fuzzy logic of this particular demo, not something that needs to be built-in.

The break-down, collapse logic in that demo is on client-side custom code, so I think it would be a matter of modifying it to provide better experience for the user.

The workaround I suggested in my previous reply (zoomout button) would be easy to implement.

Another option would be to not collapse slices on first tap, so that tooltips remain. Only subsequent tap on an "active" slice would collapse all of them.

This too should not be hard to implement with some custom code.

Let me know if any of those sound OK, and if you need any help with the implementation.
