### ISSUE TITLE
Align tooltip text

### ISSUE THREAD

**Issue by ninbura** [amcharts/amcharts5#815]
Is it no longer possible to align text within a Tooltip like in amCharts 4?

amCharts 4 syntax:
```
series.tooltip.label.textAlign = "middle";
```

What I assumed amCharts 5 syntax would have been (didn't work):
```
tooltip: am5.Tooltip.new(root, {
  textAlign: "middle",
  ...
})
```

**Comment by xorspark** [comment]
You have to set `textAlign` on the [tooltip's `label` property](https://www.amcharts.com/docs/v5/reference/tooltip/#label_property), similar to v4. Note the accepted values for [textAlign](https://www.amcharts.com/docs/v5/reference/label/#textAlign_setting):

```
tooltip.label.set('textAlign', 'center')
```

**Comment by ninbura** [comment]
I tried that as well, but was using the keyword 'middle' instead of 'center'.

Thanks for the help 👍
