### ISSUE TITLE
Why doesn't Map Indonesia filter properly

### ISSUE THREAD

**Issue by asherginting** [amcharts/amcharts5#818]
**Question**
<img width="794" alt="image" src="https://user-images.githubusercontent.com/39787908/220874785-f69accbf-4a6d-4eb0-ab14-74ffc9540adf.png">

<img width="799" alt="image" src="https://user-images.githubusercontent.com/39787908/220876222-dc764926-7597-487b-8600-519a1ff974c3.png">

I want an Indonesian map, but why do maps from other countries join the Indonesian map? even though I chose the JSON API based on country=ID, is this my mistake, or is there a bug, or is there another way, so that the map can be hidden

API : https://www.amcharts.com/lib/4/geodata/json/indonesiaLow.json?country=ID

**Comment by martynasma** [comment]
This is by design. So that the map does not look odd with chunks of land removed where we are used to seeing it.

I suggest you simply filter out the areas that are not needed using `exclude`:
https://www.amcharts.com/docs/v4/chart-types/map/#Including_and_excluding_objects
