### ISSUE TITLE
publishing a "umd" formatted bundle with rollup.js

### ISSUE THREAD

**Issue by alhuangfb** [amcharts/amcharts5#82]
Hi,

I'm working on a project with a yarn pipeline that uses a single file bundle of this package. Currently the CDN for amCharts5 gives us a IIFE format. Wondering if the team could also publish a `umd` formatted one.  I'm currently manually formatting it by

- pulling the package
- run the `npm run build`
- run `rollup dist/es2015/index.js --file index.unminified.js --format umd --name 'index' `

Thanks!

**Comment by Pauan** [comment]
If you're using Rollup, why not just use [our npm package](https://www.npmjs.com/package/@amcharts/amcharts5)? Then you will benefit from optimizations, tree shaking, etc.
