### ISSUE TITLE
Category axis with multiple values per category (bullets)

### ISSUE THREAD

**Issue by enriquepiatti** [amcharts/amcharts5#820]
Is possible to show multiple values in Y axis for the same X axis category? I'm trying to show multiple bullets under the same X value, if I use ValueAxis it works fine, but if I change the axis to CategoryAxis then it shows all the bullets in "0" X axis value.    
Data example:
```
        data = [
            {window: '1 min', pricemov: 0.5, repeat: 1},
            {window: '1 min', pricemov: 1.5, repeat: 1},
            {window: '1 min', pricemov: 2.5, repeat: 1},
            {window: '1 min', pricemov: -0.5, repeat: 1},
            {window: '1 min', pricemov: -1.5, repeat: 1},
            {window: '5 min', pricemov: 0.5, repeat: 1},
            {window: '5 min', pricemov: 1.5, repeat: 1},
            {window: '5 min', pricemov: 2.5, repeat: 1},
            {window: '5 min', pricemov: -0.5, repeat: 1},
            {window: '5 min', pricemov: -1.5, repeat: 1},
        ];
```
// to make it work with ValueAxis I need to change "window" to int 1 and 5, but I don't want to have those values separated by "4" Xgrids

**Comment by zeroin** [comment]
It should work fine, but I need to see your full code (codepen would be best) in order to tell where the problem is.
