### ISSUE TITLE
Fold scrollbar width when it's not shown

### ISSUE THREAD

**Issue by krista-prokop** [amcharts/amcharts5#821]
Hi! When i set a vertical scrollbar on my centered legend, the horizontal space/width for the scrollbar is always reserved even when the scrollbar isn't shown, which has the effect of visually throwing off the legend's centering.  See [example](https://codepen.io/kristapro/pen/wvEWpjP)

Is there a way to conditionally remove that reserved space when the scrollbar is not shown? My legend items are highly variable and i'd like them centered when there isn't a scrollbar showing.

**Comment by zeroin** [comment]
Internally we set paddingRight to the width of a scrollbar when it's added. I will try to solve this in next release. Meanwhile you can monitor private "visible" and modify paddingRight:

```
legendScrollbar.onPrivate("visible", function(visible){
  if(visible){
    legend.set("paddingRight", legendScrollbar.width())
  }
  else{
    legend.set("paddingRight", 0)
  }
})
```
