### ISSUE TITLE
Lazy loading Picture in bullets

### ISSUE THREAD

**Issue by mlomb** [amcharts/amcharts5#824]
**Question**

I have a TreeMap with bullets with a Picture in every depth. It has ~350 nodes (~10 per depth) and it appears that bullets are created during initialization so all images are loaded together.

Is there a way to lazy load the images until the user dill down up to the corresponding depth?

**Environment (if applicable)**

amCharts v5.3.3

**Additional context**

I'm creating the bullets like this:

```js
series.bullets.push(function (root, series, dataItem) {
    const picture = Picture.new(root, {
        src: dataItem.dataContext.imageSrc,
        centerX: p50,
        centerY: p50,
        width: 32,
        height: 32,
        isMeasured: true,
        dy: -28,
    });

    // picture.states.lookup("default")!.setAll({ forceHidden: true });

    return Bullet.new(root, { sprite: picture });
});
```

I tried setting `forceHidden: true` to then wait for some event but the images are still being loaded.

**Comment by martynasma** [comment]
An idea that might work: do not set `src` initially, but only when `visible` property changes:

```JavaScript
picture.on("visible", function(src, target) {
  picture.set("src", target.dataItem.dataContext.imageSrc);
})
```

**Comment by mlomb** [comment]
It seems that the event "visible" fires at initialization too, at least for the TreeMap, so all images are being loaded at once 😢

I managed to hack it with the idea of not setting the `src` initially:

```ts
series.events.on("dataitemselected", ({ dataItem }) => {
    dataItem?._settings.children.forEach((c) => {
        (c.bullets![0].get("sprite") as Picture).set("src", c.dataContext.imageSrc);
    });
});
```

**Comment by martynasma** [comment]
> It seems that the event "visible" fires at initialization too, at least for the TreeMap, so all images are being loaded at once 😢

Yeah, you should probably check whether `visibility` is `true` before loading.

**Comment by mlomb** [comment]
I can't find `visibility` but `visible`, yet it is `true` for all Pictures during initialization too 😢
```js
picture.on("visible", function (src, target) {
    console.log(target?.get("visible"));
});
```

**Comment by martynasma** [comment]
Yes, I meant `visible`, duh 😳

Do you have a CodePen of your chart?

**Comment by mlomb** [comment]
Sure, here is an example: https://codepen.io/mlomb/pen/RwYGYmG (check the console)

**Comment by martynasma** [comment]
Hm, indeed.

How about watching for `visible` of the node instead:

```JavaScript
series.nodes.template.on("visible", function(visible, target) {
  console.log(target.dataItem.bullets)
})
```
