### ISSUE TITLE
Is there a way to bent ticks in Pie chart series?

### ISSUE THREAD

**Issue by ArchaQP** [amcharts/amcharts5#826]
I am trying to build pie chart using amcharts 5. I have lots of data (approx 30 key value pairs). I want to show all the options within the defined screen. But, my ticks are intersecting with each other and creating a lot of mess. 

It looks something like this :
![pie chart ticks](https://user-images.githubusercontent.com/45165745/221834754-42f61136-1ece-4668-9f65-0e65dfcce0e0.png)

I was thinking if we have any option to bend/curve the ticks so that all the options are inside screen properly and ticks do not intersect.
Something like this : 
![bent ticks](https://user-images.githubusercontent.com/45165745/221835398-46087f2a-c21b-40db-9e1c-3695daa09d5c.png)

**Comment by martynasma** [comment]
There is no option to make "bent" ticks, I'm afraid.

However, you can make the labels go around the pie chart:
https://www.amcharts.com/docs/v5/charts/percent-charts/pie-chart/pie-series/#alignment
