### ISSUE TITLE
Possible replacement for amcharts dependency on es5-ext due to malware?

### ISSUE THREAD

**Issue by binaryartifex** [amcharts/amcharts5#829]
**Question**
Is it possible to find a replacement for the amcharts dependency on es5-ext? The bright spark of an author has decidedly added a post install 'protestware' script (call it what you want, its malware, full stop) that flags my virus protection, windows defender, my work pipelines fail, npm fails every time i go to update or install a new package in my project, because i use pnpm i have to delete the entire pnpm store each time i make a change to any project that uses pnpm. The package author continues to double down on the issue as evidenced in the outstanding issue [here](https://github.com/medikoo/es5-ext/issues/186). I don't care where anyone stands on the russia issue, but this is a blatant disregard for the spirit of the open source community and its emboldening other package authors to do equally stupid and disruptive things. If you have something to say, put it in your readme. i am falling behind on several projects on account of me constantly fighting with this damn package.

**Comment by martynasma** [comment]
Not barring any other possible solutions we may explore, have you considered reporting this false positive to:

a) maintainer of es5-ext as he seems to be quite eager to work with antivirus publishers to fix false detections.
b) MS as the maker of the antivirus package you are using.

**Comment by binaryartifex** [comment]
@martynasma appreciate the reply. A quick look through the issue referenced above and you'll see despite the efforts to fix false detections (in my opinion it isn't a false detection) there is myriad ongoing issues for people whos messages he hasn't deleted. that aside, as a consumer of the package, i shouldn't have to be going to such extremes just to do my job. not to mention the dangerous precedent being set by hijacking the open source community in such a way. its just this package and few others today, tomorrow it will be [insert package here] with yet another postinstall script preaching [whatever message here] that will ultimately fall onto the consumers wasting valuable time trying to find find ways around this very issue. its not just virus protection, its our pipelines, third party docker containers, npm and pnpm itself when it comes to managing dependencies, everything is 2 steps back to go steps forward with that damn package.

**Comment by martynasma** [comment]
BTW, es5-ext is not used by amCharts directly. It's used by one of the sub-sub-sub dependencies (starting with pdfmake) which takes away all of the control from our hands.

We'd need to replace pdfmake with something else entirely, which is a huge overhead, if there are even any feasible alternatives available.

**Comment by martynasma** [comment]
It goes like this: `pdfmake -> @foliojs-fork -> linebreak -> brfs -> static-module -> scope-analyzer -> es6-set` with the latter being responsible for pulling es5-ext in.

**Comment by binaryartifex** [comment]
well hot damn. Thats clearly out of your hands and theres no guarantee any pdfmake alternatives don't use that same library either. Not about to ask you guys to go down that kinda rabbit hole. Thats a shame. with that troublesome package having over 10,901,576 weekly downloads he's really got his hooks in to a lot of transient dependencies for a lot of reputable packages. Appreciate you looking into this @martynasma

**Comment by martynasma** [comment]
At this point it's not clear what we could do about this. We could spin Exporting plugin (which uses pdfmake) into a separate package, but that would be a breaking change, and pain in the arse for the developers. So, no-go.

Or fork pdfmake and possibly some other dependencies to see if we can juggle our way out of using es5-ext. That too sounds like a super huge overhead with no guarantee of success.

Beyond those options, I don't see anything else besides trying to work with the authors on the whole chain of dependencies and antivirus makers.

If only NPM would not suck, and would allow defining "optional dependencies"...

**Comment by binaryartifex** [comment]
heh your not wrong there. Ill close this discussion for now, i spose if more people come forward with similar issues it might be worth looking at options, but at least you guys are aware of it. hopefully in upcoming versions he will finally remove the bloody postscript. thanks again.
