### ISSUE TITLE
Legend markers don't take stroke opacity into consideration

### ISSUE THREAD

**Issue by OwsOwies** [amcharts/amcharts5#830]
**Bug description**

If I have two series with the same stroke color but different opacity, they both have the same marker on the legend.
It seems legend does not derive this information from the stroke itself.

```
currentSeries.strokes.template.setAll({
  ...seriesDefinition.stroke,
  opacity: seriesDefinition.opacity ?? 1,
});
```

**Comment by amcharts** [comment]
Yes, it doesn't. You must change stroke opacity of your legend marker.

**Comment by OwsOwies** [comment]
Would you mind telling me how?
As per documentation:
> Since the markers are build by each target, e.g. series, and can contain a number of elements, there's little we can do about configuring the look for those.

Regardless, I've tried those three approaches:
```
legend.markers.template.setAll({ opacity: 0.3, width: 50 }); // Changes the width but not the opacity

legend.markerRectangles.template.setAll({ opacity: 0.3, fillOpacity: 0.3 });
		
legend.markers.template.setup = marker => {
  marker.setAll({ opacity: 0.3 });
};
```
both before and after setting legend data. 
None of those seem to work and I can't find anything useful in the documentation.

**Comment by martynasma** [comment]
You should probably not use `opacity` setting, but rather `fillOpacity` and `strokeOpacity`.

Those two will carry over to the legend markers, whereas `opacity` won't.

**Comment by OwsOwies** [comment]
Thank you kindly, that solves the problem.
