### ISSUE TITLE
Force-directed - How to programmatically find links connected to a node?

### ISSUE THREAD

**Issue by meganindya** [amcharts/amcharts5#831]
I have a 2-layer deep Force-directed chart that has a set of parent nodes and each has some child nodes. In addition, the child nodes have crosslinks to other child nodes (belonging to different parent nodes).

I want to be able to highlight (change stroke width) the links connected to a node (both parent and child) on hovering over the respective node. I noticed that in v4, a node's `dataItem` has a property called `childLinks` which isn't present in v5.

Is there a way to achieve the following:

- Highlight child links when hovering over a parent node
- Highlight cross links when hovering over a child node
  Say there are two nodes `A` and `B` which are cross-linked, I want the link to be highlighted on hovering over either of `A` or `B`.

**Comment by martynasma** [comment]
You can use target node's data item's `links` setting to find a list of all links (including parent, child, and cross-links).

Then apply state to it as needed, e.g.:

```JavaScript
series.links.template.setAll({
  strokeWidth: 1,
  strokeOpacity: 0.5
});

series.links.template.states.create("active", {
  strokeWidth: 3,
  strokeOpacity: 1
});

series.nodes.template.events.on("pointerover", function(ev) {
  am5.array.each(ev.target.dataItem.get("links"), function(link) {
    link.set("active", true);
  });
});

series.nodes.template.events.on("pointerout", function(ev) {
  am5.array.each(ev.target.dataItem.get("links"), function(link) {
    link.set("active", false);
  });
});
```

Live example:
https://codepen.io/team/amcharts/pen/LYJyxMb?editors=0010

**Comment by meganindya** [comment]
Thanks a lot! This is exactly what I needed.
