### ISSUE TITLE
Circles as legend marks for SmoothedXLineSeries

### ISSUE THREAD

**Issue by jdim** [amcharts/amcharts5#834]
Hello.
Can I get rounded corners on the legend marks when I use SmoothedXLineSeries?

Seems `cornerRadiusTL/...` not applicable

Like that:

<img width="1350" alt="Screenshot 2023-03-03 at 17 18 17" src="https://user-images.githubusercontent.com/8625641/222772908-db073433-cf6d-49ee-98a2-dfb1f363e329.png">

Tried on examples:

https://codepen.io/dm-khabarov/pen/qBMmMNm

Provide details about your development environment where you think it might be useful. E.g.:

 - amCharts version 5
 - Browser Chrome
 - Related frameworks React / Typescript

**Comment by xorspark** [comment]
You need to set [useDefaultMarker](https://www.amcharts.com/docs/v5/concepts/legend/#default-markers) to true in order to further customize the marker look. Adding this will make your cornerRadius* values work.
