### ISSUE TITLE
Force-directed - How to override click to toggle with another event type?

### ISSUE THREAD

**Issue by meganindya** [amcharts/amcharts5#835]
**Context**

I have a 2-layer deep Force-directed chart that has a set of parent nodes and each has some child nodes. In addition, the child nodes have crosslinks to other child nodes (belonging to different parent nodes).

**Question**

Is it possible to override the default "click to toggle" event with another event type? I want to toggle (show/hide child nodes) on `dblclick` and perform some other task on `click`.

**Comment by martynasma** [comment]
```JavaScript
series.nodes.template.setAll({
  toggleKey: "none"
});

series.nodes.template.events.on("dblclick", function(ev) {
  ev.target.set("disabled", !ev.target.get("disabled"));
});
```

**Comment by meganindya** [comment]
It does what I want, but I noticed that `click` is triggered twice as well

e.g., for the following

```ts
series.nodes.template.setAll({
  toggleKey: "none"
});

series.nodes.template.events.on("dblclick", function(ev) {
  ev.target.set("disabled", !ev.target.get("disabled"));
  console.log("dblclick");
});

series.nodes.template.events.on("click", function(ev) {
  console.log("click");
});
```

on double clicking on a node, the output is

```console
click
click
dblclick
```

**Comment by martynasma** [comment]
Correct. Doubleclick also triggers click. There's no way around it.

You can debounce the stuff in your click handler, and cancel it if dblclick occurs.
