### ISSUE TITLE
Force-directed - How to find nodes connected to a link?

### ISSUE THREAD

**Issue by meganindya** [amcharts/amcharts5#836]
**Context**

I have a 2-layer deep Force-directed chart that has a set of parent nodes and each has some child nodes. In addition, the child nodes have crosslinks to other child nodes (belonging to different parent nodes).

Codepen: https://codepen.io/meganindya/pen/BaORvWv

**Question**

How to find the nodes connected to a link (both parent-child or crosslink)? On hovering over a link, I want to change the opacity of the nodes connected by the link. E.g. in the codepen example above, on hovering over the link between `B1` and `C2`, I want to change the opacity of `B1` and `C2`.

**Comment by martynasma** [comment]
You can use link's `source` and `target` settings that will reference start and end nodes of the link:

```JavaScript
series.links.template.events.on("pointerover", function (e) {
  const link = e.target;
  const source = link.get("source");
  const target = link.get("target");
  // ...
});
```

**Comment by meganindya** [comment]
Thanks!
