### ISSUE TITLE
LineSeries type in the chart, freezes when scrolling on mobile.

### ISSUE THREAD

**Issue by mbdmt** [amcharts/amcharts5#837]
**Bug description**

Finger dragging down on the chart when there are LineSeries type in the chart, freezes when scrolling on mobile.

**Environment (if applicable)**
amCharts 5

e.g.
https://www.amcharts.com/demos/column-and-line-mix/
When I set panX & panY: false , the page cannot be dragged

**Comment by martynasma** [comment]
You should probably set `behavior: "none"` on XYCursor, too.

**Comment by mbdmt** [comment]
> You should probably set `behavior: "none"` on XYCursor, too.

It`s working, thanks!
