### ISSUE TITLE
Can we add axis labels to HeatLegend

### ISSUE THREAD

**Issue by swapnilh-cognologix** [amcharts/amcharts5#842]
Please find below screenshot for ref from amcharts 4
![image](https://user-images.githubusercontent.com/49631041/223723209-596774ca-9674-49c9-8ff5-559c02251937.png)

**Comment by martynasma** [comment]
There is no such functionality in amCharts 5, I'm afraid.

I suppose you could try pushing a `ValueAxis` into heat legend's `children`.

**Comment by swapnilh-cognologix** [comment]
Thanks @martynasma It worked

Awesome Thanks again!
