### ISSUE TITLE
Force-directed: How to place a node's label outside the node?

### ISSUE THREAD

**Issue by meganindya** [amcharts/amcharts5#844]
I have a force directed chart with different node sizes. I want to do the following:

1. Set fixed font-size of `14px` for the labels

    I think I can do this using

    ```ts
    _series.labels.template.setAll({
      fontSize: '14px',
      overflowBehavior: 'none'
    })
    ```

    This can overflow, so I want to set the following behavior

2. Position labels as:

    1. If label fits inside the node, place in the center (default behavior)
    2. If label doesn't fit inside the node, place on top of the circle at a gap of `10px`

    **Is it possible to detect whether a label fits inside of a node?**
    
    **If possible, how do I implement that?**

**Comment by martynasma** [comment]
Something like this:

```JavaScript
series.labels.template.setAll({
  fontSize: 14,
  oversizedBehavior: "none",
  paddingLeft: 0,
  paddingRight: 0
});

series.labels.template.adapters.add("centerX", function(centerX, target) {
  var circle = target.dataItem.get("circle");
  var radius = circle.get("radius") + 10;
  var width = target.width();
  if (width > (radius)) {
    target.set("y", -radius -10)
    target.set("fill", am5.color(0x000000));
  }
  else {
    target.set("y", 0);
    target.set("fill", am5.color(0xffffff));
  }
  return centerX;
});
```

Demo:
https://codepen.io/team/amcharts/pen/LYJdQvN??editors=0010

**Comment by meganindya** [comment]
Exactly what I needed. Thanks a lot!
