### ISSUE TITLE
Unwanted Zoom Functionality on XY Chart Scrollbar

### ISSUE THREAD

**Issue by jeinhorn787** [amcharts/amcharts5#846]
**Question**
Is it possible to disable automatic zoom when a `Scrollbar` is added to an XY Chart?  Or if not, is it possible to keep a fixed zoom level at all times?

I am aligning 2 instances of the same amCharts Chart side by side (with different data and different `id`s).  I'm trying to keep the bars of the 2 charts thee same width and aligned horizontally on initial load. An example below:

![image](https://user-images.githubusercontent.com/29580247/224101551-077cf49a-8b5a-4562-9fb6-9f87e1c6206c.png)

If the data array passed to the chart is 8 or less objects, there is no scrollbar.  If it's greater than 8, a scrollbar must be in place. The issue I'm having is that when I set an amCharts `Scrollbar` as the charts `scrollbarY`, it has this automatic zoom that causes the bar width to expand because it is being zoomed in on.  This is confirmed by [the docs](https://www.amcharts.com/docs/v5/charts/xy-chart/zoom-and-pan/#Zooming_with_scrollbars).

![image](https://user-images.githubusercontent.com/29580247/224108619-0ebc334a-a29e-45bc-b2d3-f760382a3a68.png)

I need the bars to be the same width at all times (no zoom) so they can be neatly aligned horizontally as soon as the data loads.  The codesandbox is below with the issue present, look at line 46 in `Container.jsx` for a comment on how to see proper alignment when there is no scrollbar.  The actual amCharts instance is written in `BarChart.jsx`.

https://codesandbox.io/s/hungry-panka-jpo9no?file=/src/Charts/Container.jsx

Thank you for any help you can provide in advanced!

**Comment by martynasma** [comment]
So, basically, you need to "fix" zoom at certain number of categories and use scrollbar only for scrolling, not allowing it to zoom?

Pre-zooming the chart to a number of categories and hiding scrollbar grips should achieve that:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/category-axis/#pre-zooming
https://www.amcharts.com/docs/v5/charts/xy-chart/scrollbars/#Scrollbar_elements

**Comment by jeinhorn787** [comment]
> So, basically, you need to "fix" zoom at certain number of categories and use scrollbar only for scrolling, not allowing it to zoom?
> 
> Pre-zooming the chart to a number of categories and hiding scrollbar grips should achieve that: https://www.amcharts.com/docs/v5/charts/xy-chart/axes/category-axis/#pre-zooming https://www.amcharts.com/docs/v5/charts/xy-chart/scrollbars/#Scrollbar_elements

This is great, thank you so much! I did not know a `CategoryAxis` had the `zoomToIndexes()` method, not sure why I couldn't find that in the docs after endlessly searching. All I could find was `yAxis.zoom()` and that was too granular.  Yup, I had the grips disabled right from the get-go.  Thank you so much again!
