### ISSUE TITLE
The tooltip implemented via the adapter show grouped values without numberformatter

### ISSUE THREAD

**Issue by perumalsamyrajaveni1518** [amcharts/amcharts5#848]
**Bug description**
I'm implementing the tooltip via the tooltip adapter to show grouped values but the tooltip value doesn't format based on **numberformatter**  it shows normal values.

Please refer to the attached image.

`Tooltip.label.adapters.add('text', (text, target) => {
       text  +='[#fff bold]{valueX.formatDate('dd-MM-yyyy HH:mm:ss a')}[/]';
       chart.series.each(function (series) {
          let dataItem = series.get("tooltipDataItem");
          if (dataItem) {
            text += '\n[' + series.get("stroke").toString() + ']▬[/] [bold width:100px]' + series.get("name") + ':[/] ' + dataItem.get("valueY");
          }
        })
        return text;
    });`

**Environment** 
- amCharts 5
- Chrome
- Angular 
- Typescript

**Additional context**

![image](https://user-images.githubusercontent.com/127523713/224344712-d29c4e3c-021f-422a-82d5-c2dec6312ead.png)

**Comment by martynasma** [comment]
Since you are adding the value to tooltip directly, you need to apply formatting to it yourself:

```
root.numberFormatter.format(dataItem.get("valueY"));
```

**Comment by perumalsamyrajaveni1518** [comment]
It's working fine. Thank you so much for the solution @martynasma
