### ISSUE TITLE
DateAxis | Line Series - Not able to see the tooltip in case of dateInterval set to 'minute' OR 'day'

### ISSUE THREAD

**Issue by swapnilh-cognologix** [amcharts/amcharts5#851]
1 - Not able to see the tooltip in case of dateInterval set to 'minute' also cursor not auto focusing on next data point.
2 - Not able to see Tooltip for First 2 data points and last 3 data points in case of dateInterval set to 'day'.

https://codepen.io/swapnilh-cognologix/pen/bGxMLVw

Thanks:)

**Comment by martynasma** [comment]
Two things:

1) Your data needs to be in ascending order. Right now it seems to be out of any particular order. You need to fix that.
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#Data_order

2) Enable snapping of the tooltip to series using series setting `snapTooltip: true`.
https://www.amcharts.com/docs/v5/reference/xyseries/#snapTooltip_setting
