### ISSUE TITLE
axis-ranges above

### ISSUE THREAD

**Issue by chunlampang** [amcharts/amcharts5#852]
axis-ranges `above` is not working to it's label.
![image](https://user-images.githubusercontent.com/30290516/225858585-97fd509c-725d-4a3b-a5cb-5afc1457b855.png)

**Comment by martynasma** [comment]
Try adding `layer: 30` setting to the axis range label element.

**Comment by chunlampang** [comment]
Solved, thank you.
`rangeDataItem.get("label").setAll({ layer: 30 })`
