### ISSUE TITLE
Transform scale on amchart 5 container

### ISSUE THREAD

**Issue by jrothfus** [amcharts/amcharts5#854]
I have been working with amcharts in the context of larger dashboards (with more than just amcharts elements in it) and came upon a problem when transforming the outer dashboard container using CSS `transform: scale(<#>)`: hovering over the graph no longer shows tooltips correctly. To be more specific, when I hover over the graph the tooltip does not appear where it would normally but instead appears further away from the cursor. This problem gets worse the larger the scale transform. Its as if the graph itself has followed the outer div's scale transform, however any events that are tracking the mouse position are operating on the original, non-transformed graph.

I decided to dig deeper and get to the root of the issue, so I opened a codepen of an [amcharts 5 bar graph](https://www.amcharts.com/demos/column-with-rotated-series/) from the amcharts5 demos and play around to see if transforming it on there would work. Worth noting that this codepen should be using the most recent version of amcharts 5.

Here are two codepens that show the issue in 2 different ways:

1) A transform scale on the container that was used when creating the root off the graph:
[Transform on the immediate container containing the graph](https://codepen.io/jrothfus/pen/dyqqwLV)

2) A transform scale on the body of the html that contains the chart div
[Transform on the outer body containing the graph](https://codepen.io/jrothfus/pen/mdGGvdK)

**The Problem**
In these code pens you can see that the vertical line that determines which column's tooltip will show up does not follow the mouse. It appears to be following the un-transformed graphs's size/location. I would expect that the transform would not impact the behavior of the graph and it's tooltips.

I am aware of the following issue #258 that appears to have mentioned this problem or something similar being fixed in version 5.1.4. If I am just missing something about this post, please let me know.

**Comment by martynasma** [comment]
Please refer to this doc:
https://www.amcharts.com/docs/v5/getting-started/root-element/#Custom_sizing_function
