### ISSUE TITLE
Can we configure tooltip like this?

### ISSUE THREAD

**Issue by rafee11** [amcharts/amcharts5#855]
```
series.bullets.push(function() {
    var tooltips1 = am5.Tooltip.new(root, {
		labelText: "test1",
		getFillFromSprite: true,
		getStrokeFromSprite: true,
		autoTextColor: true,
		getLabelFillFromSprite: true,
		labelText: 'test'
	});
    tooltips1.get("background").setAll({
		 fill: am5.color(0x39FF74),
		 fillOpacity: 0.8
	});
    return am5.Bullet.new(root, {
      sprite: am5.Circle.new(root, {
        radius: 5,
        fill: series.get("fill"),
        tooltip: tooltips1
      })
    });
});
```

It gives empty tooltip as attached below

Output
![image](https://user-images.githubusercontent.com/23078836/226637789-10887d85-f1ae-4b08-b04e-c70cb2ff08ea.png)

Codepen: https://codepen.io/rafee11/pen/XWPxpRq

**Comment by martynasma** [comment]
Is there a reason why want each bullet to have own `Tooltip` instance?

**Comment by rafee11** [comment]
@martynasma  I am getting this error 

![image](https://user-images.githubusercontent.com/23078836/226684359-5c0a7297-1298-48b0-a04a-62c8ac59ff13.png)
