### ISSUE TITLE
Fill area below the minimum of two curves

### ISSUE THREAD

**Issue by franz-86** [amcharts/amcharts5#858]
Dear all, 
I'm trying to obtain an XYplot with two curves and the area filled below the minimum of the two curves. 
I tried creating a third field, defined as the minimum, and used 
`series3.fills.template.setAll({
      fillOpacity: 0.3,
      visible: true,
    });`
However, as sadly expected, I got issues on the edges, where the slopes of the two curves are different and some tiny portion of the edge is not filled with the color. 
Any suggestion?

**Comment by martynasma** [comment]
I'm afraid there's no such functionality.

**Comment by franz-86** [comment]
many thanks for your reply. I solved by adding "manually" the crossing point
