### ISSUE TITLE
Access nested data using dot notation

### ISSUE THREAD

**Issue by alienbuild** [amcharts/amcharts5#86]
I'm trying to access some data that I have in a nested object ie:

```
{
   "date:" ....,
   "value": 123
   "prevSold": {
      "price": 123
    }
}
```

However I can't seem to tap into the prev sold price using the following line, but it works perfectly on the first level:
```
 valueYField: "prevSold.price"
```

Is dot notation supported or is there a different syntax for that? I did also try `"prevSold['price']"`

Thanks,

**Comment by martynasma** [comment]
I'm afraid dot notation is not supported in data fields. At this time we do not have any plans on implementing it.

The only option is to "flatten" your data so that values are directly accessible by data fields.

**Comment by buggedcom** [comment]
@alienbuild as per @martynasma suggestion and easy way to do this is to utilise [flat](https://www.npmjs.com/package/flat)
