### ISSUE TITLE
Legend markers disappear when using series.appear(<delay>).

### ISSUE THREAD

**Issue by Eoic** [amcharts/amcharts5#861]
**Bug description**

When I have a single series in a bar chart and use `legend.data.setAll(series.dataItems);` to set legend item for each bar, using `series.appear()` causes legend markers to disappear. See [this](https://codepen.io/eoic/pen/gOdQzLw) CodePen demo. Uncomment `series.appear(1000);` to see legend markers disappear after the chart loads.

![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/18404082/227175660-93e1c118-f0a5-48ea-97b7-8b5c0b51c16b.gif)

**Comment by zeroin** [comment]
I tried to find a solution and the best thing I could do is to add another adapter:

```
legend.markerRectangles.template.adapters.add("fill", (fill, target)=>{
  var dataItem = target.dataItem;
  if(dataItem){
    var graphics = dataItem.dataContext.get("graphics");
    if(graphics){
      return graphics.get("fill");
    }
  }
  return fill
})
```

**Comment by Eoic** [comment]
@zeroin Yes, that works for me. Although clicking on the legend marker to hide series does not change the color, so I would probably need to add 'click' events on the legend markers to do that manually.
