### ISSUE TITLE
Implement Axis break in am5

### ISSUE THREAD

**Issue by swapnilh-cognologix** [amcharts/amcharts5#863]
Is there any way to implement/draw the axis break like in amcharts 4

https://www.amcharts.com/demos-v4/column-chart-with-axis-break-v4/

**Comment by zeroin** [comment]
Hi,

We decided not to add this feature in v5, as it required a lot of additional code and affected performance.
You can simulate a similar thing by stacking three axes. Here is a demo:
https://www.amcharts.com/docs/v5/tutorials/simulating-axis-gaps/
