### ISSUE TITLE
Amcharts 5 Animations -  Is there a way to disable chart animations after every chart update/re-render

### ISSUE THREAD

**Issue by mayurhotwani** [amcharts/amcharts5#866]
**Question**

We are using am5themes_Animated to enable animations for the charts. on initial loading of chart data we have animation which is perfect. Now the problem is when we perform any change which will also change the chart data and make the chart to re-render/update again, the animations are also active on chart data update. 

**My question is, Is there a way to disable chart animations  after chart update.** [I already know that we can use `series.showOnInit = false` to disable animations, but that is only for disabling animations on first load. I am looking for something which will disable the animations after every chart update/re-render]

**Environment (if applicable)**

We are currently using below amcharts versions: 
`"@amcharts/amcharts5": "^5.2.50",
  "@amcharts/amcharts5-geodata": "^5.1.0",`

**Additional context**

**Comment by martynasma** [comment]
How about disabling the Animated theme, and just using `appear()` methods on target elements to show initial animation? E.g.:

```JavaScript
series.appear(1000, 100);
chart.appear(1000, 100);
```

**Comment by CHANDRAMOHANnegi** [comment]
Can we use am5themes_Animated theme and disable initial mount animation

root.setThemes([am5themes_Animated.new(root), getChartTheme(root)]);

we have multiple series

series.appears() // if we use this its get animated
chart.appears()
