### ISSUE TITLE
Preserving precision using dynamic grouping aggregation

### ISSUE THREAD

**Issue by krista-prokop** [amcharts/amcharts5#867]
If I'm using dynamic grouping with `valueYGrouped = "average"`, is there a native way to preserve the aggregate datapoint's precision to match that of the original dataset?  

For example, if my dataset values are whole numbers, I want the group-aggregated `average` to be reflected in my tooltip as a whole number. Likewise if my dataset is composed of values with 1 decimal place, that's how I want it reflected in my tooltip.

**Comment by martynasma** [comment]
I'm afraid there's no built-in way to do that.

You can only achieve that using custom aggregation functions:
https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#Custom_aggregation_functions
