### ISSUE TITLE
Click event for treemap does not work in amcharts 5

### ISSUE THREAD

**Issue by lovehamburger** [amcharts/amcharts5#869]
![image](https://user-images.githubusercontent.com/22336867/228107248-4f26eaf5-07f6-4333-b41f-6df4db9e99a8.png)

Im trying to implemente a event handler for my treemap chart (i need to retrieve the element i clicked) but when i follow the event example found in the 'Event' documentation page looks like it gets all the series and not only element i clicked.

This is part of my code

    `root.setThemes([
                    am5themes_Animated.new(root)
                ]);

        var container = root.container.children.push(am5.Container.new(root, {
            width: am5.percent(100),
            height: am5.percent(100),
            layout: root.verticalLayout
        }));

        var series = container.children.push(am5hierarchy.Treemap.new(root, {
            singleBranchOnly: false,
            downDepth: 1,
            upDepth: 1,
            initialDepth: 1,
            valueField: "value",
            categoryField: "name",
            childDataField: "children",
            layoutAlgorithm: "binary"
        }));

     
         series.nodes.template.events.on("click", function (ev) { console.log("function: ", ev.target.uid); });

My series already have data, i tried to use series.nodes (does not recognize the event) or ev.dataItem (undefined). Im probably missing something somewhere, hope someone can help me.

Thank you in advance.

**Comment by xorspark** [comment]
Your code works for me, as long as you set your event *before* you add your data to the series: https://codepen.io/team/amcharts/pen/WNgmdgo/ebf57000afd12ee5f68e5ed9e028fd1f?editors=0011

**Comment by lovehamburger** [comment]
thank you，but How do I change from clicking to expand a child level to hovering to expand a child level ？

**Comment by xorspark** [comment]
You can use the `pointerover` event and call `selectDataItem` on the hovered node.

```
series.nodes.template.events.on("pointerover", function (ev) { 
  const children = ev.target.dataItem.get('children')
  if (children && children.length) {
   series.selectDataItem(ev.target.dataItem)
  }
});
```

Debouncing the callback is recommended.

Demo: https://codepen.io/team/amcharts/pen/rNZbMym/51e514ab27b3092e75025c472b5cb5c3?editors=0010

**Comment by lovehamburger** [comment]
Thank you，ok ， I simply write this：
series.nodes.template.setAll({
					toggleKey:"none",
				});

				series.nodes.template.events.on("pointerover", function(ev) {
					ev.target.set("disabled", !ev.target.get("disabled"))
				});

**Comment by lovehamburger** [comment]
Think you ，ok ，I simply write this：

				series.nodes.template.setAll({
					toggleKey:"none",
				});

				series.nodes.template.events.on("pointerover", function(ev) {
					ev.target.set("disabled", !ev.target.get("disabled"))
				});
