### ISSUE TITLE
Odd Behavior with Export Icon and Export Menu

### ISSUE THREAD

**Issue by jcgithub9** [amcharts/amcharts5#872]
Using latest version of amcharts5 (5.3.9), have maps and charts that use the export menu with no problems until web-site had styles and joomla templates recently upgraded; now the export icon and menu on maps and charts is behaving oddly:
1) The export icon does not appear unless the mouse is hovered-over the upper right portion of the map/chart;
2) When the export icon is clicked, the export menu appears but has NO text visible within it - is a blank menu

Example web page with maps and charts that have this behavior is at: 
https://cbreview.thearda.com/us-religion/group-profiles/groups?D=7 

Have to scroll down to see maps and line charts with the noted export icon and menu behavior.

Since this was working fine prior to style updates, certainly seems to be a side effect of the modified styles/template, but have no clue at this point what might be causing this or how to investigate further and appreciate any suggestions.

**Comment by martynasma** [comment]
It looks like CSS from your template.css file is messing up the menus. Use browser's dev tools to inspect the menu elements, so that you can fix the CSS on your website.

**Comment by jcgithub9** [comment]
Thanks - we did find the side-effect problem in template.css where it was setting properties on "a" tags that made them opaque
