### ISSUE TITLE
Is it possible to have a hour interval, but at half past each hour?

### ISSUE THREAD

**Issue by JosephCHW** [amcharts/amcharts5#873]
Hi, I have a chart that has data every hour, with the data being gathered every hour in UTC time. This works fine for UTC and UK time, but when using Indian time, which is 4:30h ahead, the data is at times of 14:30-15:30, 15:30 - 16:30 etc. I have checked the chart data and the date object indeed has data with date values at half past every hour, but this displays in the chart as being at 18:00 instead of 18:30 for example. I’d like the labels to be at half past each hour, correctly representing the date in the data object. I have tried experimenting with baseInterval and gridIntervals but I’ve not managed to do what I want it to do.

Currently I have
baseInterval: {
    timeUnit: “hour”,
    count: 1
}

 Changing to “minute” and 30 doesn’t work either. 
![AD551ADA-484C-4F89-AE2D-39713E4E8834](https://user-images.githubusercontent.com/57486230/229153089-cce0fba8-db3d-4ba4-b1a5-448b33d42ed6.jpeg)
I have attached photos of it in UTC and it in IST time. Ideally they would both be the same, except in IST the labels would say :30 instead of :00 with the correct offset.

![C08A5257-F3A8-4656-93ED-CFB01B1B41D1](https://user-images.githubusercontent.com/57486230/229153040-6b7e9b80-99fe-418a-9eb9-eba322a40b09.jpeg)

**Comment by zeroin** [comment]
Have you tried to set a timezone for your chart?
https://www.amcharts.com/docs/v5/getting-started/root-element/#time-zone

`root.timezone = am5.Timezone.new("Asia/Calcutta");`

**Comment by JosephCHW** [comment]
> Have you tried to set a timezone for your chart? https://www.amcharts.com/docs/v5/getting-started/root-element/#time-zone
> 
> `root.timezone = am5.Timezone.new("Asia/Calcutta");`

Thanks for the suggestion, but this does not fix the issue I have. It still shows with the bar cut in half at the start , and labels and bars at :00 not :30

**Comment by JosephCHW** [comment]
Accidentally closed the issue - reopened because I have not found a solution yet

**Comment by zeroin** [comment]
Could you create a codepen with exact data and setup, so I could take a look?
