### ISSUE TITLE
Amchart 5 performance analysis

### ISSUE THREAD

**Issue by swapnilh-cognologix** [amcharts/amcharts5#874]
Is there any video or report to see the amchart 5 performance vs amchart 4 performance.

**Comment by martynasma** [comment]
No, there's no video, I'm afraid.

Though, v5 was designed to be times more faster than v4, and it is :)

**Comment by swapnilh-cognologix** [comment]
Thanks @martynasma yes Amchart 5 is faster than Amchart 4

Thanks for this awesome library :)

**Comment by Lancy-11** [comment]
its not true, amchart 5 map is a really shit, they should put in the trash
