### ISSUE TITLE
Setting min/max dynamically  on DateAxis

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts5#876]
Hello !

Is there a way to change min/max dynamically ?

```
let yAxis = chart.yAxes.push(
  am5xy.DateAxis.new(root, {
    min: new Date(....),
    max:  new Date(....),
    renderer: am5xy.AxisRendererY.new(root, {})
  })
);
yAxis.min =  new Date(....)
yAxis.max =  new Date(....)
```

Thanks for your support !

**Comment by xorspark** [comment]
Yes, you have to use `set` or `setAll` as [`min`](https://www.amcharts.com/docs/v5/reference/dateaxis/#min_setting) and [`max`](https://www.amcharts.com/docs/v5/reference/dateaxis/#max_setting) are [settings](https://www.amcharts.com/docs/v5/concepts/settings/). Note that the types are numeric so you need to call `getTime` on your Date objects.

```
yAxis.set('min', new Date(2020, 0, 1).getTime())
yAxis.set('max', new Date(2022, 0, 1).getTime())
// or
yAxis.setAll({
  min: new Date(2020, 0, 1).getTime(),
  max: new Date(2022, 0, 1).getTime()
})
```

**Comment by ptorrent** [comment]
Thanks !
