### ISSUE TITLE
Asynchronous data loading on date serie

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts5#877]
Hello,

I'm working on this codepen. :

https://codepen.io/ptorrent/pen/yLRBbwV

This is my goal: 

I would like to add data depending on zoom..  Not sure this is possible with amchart, looks like a bit hard to define baseInterval ( I can have interval every minute (even evrey seconds) on a specific interval and every day on other (depending where the user has zoomed).

is there a way to do this simply? 

```
function onZoom(){
	clearTimeout(onZoom.timeout) 
	onZoom.timeout = setTimeout(function(){
		var min = new Date(xAxis.getPrivate("selectionMin"));
		var max = new Date(xAxis.getPrivate("selectionMax"))
		if((max - min) > 1000 * 60 * 60 * 24) return console.error('ignore zoom')
			
		var dataInterval = 1000 * 60 * 60
		//we keep old and future value
		data = data.filter(function(a){
			return a.ts < min || a.ts > max
		})
		//we add new set of value
		data.push(...generateData(new Date(min), dataInterval, new Date(max)))
		//we sort 
		data.sort(function(a,b){return a.ts - b.ts})
		console.error('data',new Date(min),new Date(max),data)
		series.data.setAll(data);
	},2000)
}
xAxis.onPrivate("selectionMin", onZoom)
xAxis.onPrivate("selectionMax",onZoom)

```
Do I've to do something with baseInterval ? Is there a way to update it manually ?

![image](https://user-images.githubusercontent.com/6083644/229910051-218d7adc-33fd-48ba-9cad-641b03d5b85d.png)

You have to zoom on a day to get this rendering

Othere point cursor:

If I zoom on an interval and add some point, cursor is working fine:
![image](https://user-images.githubusercontent.com/6083644/229913842-ebd1cece-f3da-4c42-9806-8be71b41f418.png)

But I'm not able to see cursor on dayly point:

![image](https://user-images.githubusercontent.com/6083644/229914068-eda6ae8f-c1a5-4e4b-a7ae-af43344e3e60.png)

You can reproduce if you zoom a a day, then unzoom and move you mouse. Cursor will works only on minute data interval.

Thanks for your support

**Comment by martynasma** [comment]
Perhaps it's just enough to enable tooltip snapping to series:

```JavaScript
var series = chart.series.push(am5xy.LineSeries.new(root, {
	xAxis: xAxis,
	yAxis: yAxis,
	valueYField: "value",
	valueXField: "ts",
	snapTooltip: true, // <-- this
	tooltip: am5.Tooltip.new(root, {
		pointerOrientation: "horizontal",
		labelText: "{valueY}"
	})
}));
```
