### ISSUE TITLE
Tooltip labelText does not reference valueX or valueY on axes

### ISSUE THREAD

**Issue by dez1729** [amcharts/amcharts5#879]
When adding a labelText a tooltip for the axes, trying to reference valueX or valueY does not work properly.

![image](https://user-images.githubusercontent.com/20635596/229900809-f9d1173e-c670-47c4-946c-48ead4865d91.png)

**Comment by xorspark** [comment]
You have to set the [`tooltipDateFormat`](https://www.amcharts.com/docs/v5/reference/gaplessdateaxis/#tooltipDateFormat_setting) or [`tooltipDateFormats`](https://www.amcharts.com/docs/v5/reference/gaplessdateaxis/#tooltipDateFormats_setting) to modify the tooltip. 

```
var xAxis = chart.xAxes.push(
  am5xy.GaplessDateAxis.new(root, {
    // ...
    tooltipDateFormat: "'Date:' MMM dd",
    // ...
  })
);
```

More information can be found here: https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#axis-tooltip
