### ISSUE TITLE
Hide tooltip on zero value example

### ISSUE THREAD

**Issue by dimuls** [amcharts/amcharts5#88]
Can't find any in documentation and demos.

**Comment by dimuls** [comment]
Able to do that this way:
```
tooltip.label.adapters.add("forceHidden", (hidden, target) => {
  if (target.dataItem && target.dataItem.dataContext[id] === 0) {
    tooltip.set("forceHidden", true);
  } else {
    tooltip.set("forceHidden", false);
  }
  return hidden;
});
```
But not sure if this is right way

**Comment by martynasma** [comment]
It depends on your chart and how it is configured. Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

In any case, hiding label of a tooltip does not seem like a good idea to me.

**Comment by dimuls** [comment]
This reason and many others forced me to return to version 4. I don't have any examples for version 5 right now.

**Comment by martynasma** [comment]
Well, you did try the above code on something, so you could post that and I'll take a look how we can do it better :)
