### ISSUE TITLE
Item containers in legend have wrong name since version 5.3.8

### ISSUE THREAD

**Issue by MClimate** [amcharts/amcharts5#880]
**Bug description**

Legend items are no longer having right areaLabel name since version 5.3.8. Before this version (specifically in 5.2.8), areaLabel was returning the proper name of the series, but now it is returning {name}. 

I am using it in the legend events 

`legend.itemContainers.template.events.on("click", function (ev) {
const areLabel = ev.target._settings.ariaLabel;
})`

where ev.target._settings.ariaLabel is now returning "{name}; Press ENTER to toggle" instead of "Example name; Press ENTER to toggle"

**Environment (if applicable)**
version ^ 5.3.8

**Comment by martynasma** [comment]
We started using placeholders in `ariaLabel` so that they are populated properly when something changes.

If you need to know the name of the series associated with the legend item, you can use `ev.target.dataItem.dataContext.get("name")`.
