### ISSUE TITLE
Changing yAxis for an existing series

### ISSUE THREAD

**Issue by aklauza** [amcharts/amcharts5#882]
Hi,

I'm trying to add a button for the user to change the Y axis in the stock chart for an existing series that is already drawn. I am using `series.set('yAxis', new_yAxis)` but this does not work, it does not create any new yAxis and it makes my series drawing disappear, what am I missing? 

See below a snippet of the code in charge of moving my series from the right to the left axis:

Thanks
```ts
series: am5xy.LineSeries;  // This is the amstock series I'm looking to modify its yAxis
this.stockChart: am5stock.StockChart // This is my reference to am5stock main object

// Create new left yAxis
yRenderer = am5xy.AxisRendererY.new(this.root, {
    pan: "zoom",
    opposite: false,
});
yRenderer.grid.template.set('visible', false);   // Disable grid
yAxis = this.stockChart.panels.getIndex(0).yAxes.push(am5xy.ValueAxis.new(this.root, {
    renderer: yRenderer
}));

// Remove old yAxis
this.stockChart.panels.getIndex(0).yAxes.removeValue(series.get('yAxis'));

// Update my series to use new yAxis
series.set('yAxis', yAxis);

// Set data again to force a rerendering
series.data.setAll(ts_data);
```

**Comment by martynasma** [comment]
Have you tried setting `yAxis` on a series, before removing the old axis from the panel?

**Comment by aklauza** [comment]
Yes, commenting out the removeValue line does not help, still not working

**Comment by zeroin** [comment]
I am afraid we will need a codepen where this can be reproduced in order to help.

**Comment by aklauza** [comment]
Please find attached the code sandbox to reproduce the issue here: https://codesandbox.io/s/amcharts5-angular-yaxis-snq1ej?file=/src/app/app.component.ts

Focus on the `swapYAxis()` on line 49. That code is triggered with the button in the view:

![image](https://user-images.githubusercontent.com/11398584/233800529-b94053ee-27a4-4bcc-a064-ccd049451ac1.png)

and then when pressing it, the series disappears:

![image](https://user-images.githubusercontent.com/11398584/233800553-f56d5bfd-1e81-4578-b68f-2a873202a3f9.png)

Please let me know if this is a bug or I am missing some command. thank you
