### ISSUE TITLE
How to position tooltips on map charts?

### ISSUE THREAD

**Issue by ibrahimAboelsuod** [amcharts/amcharts5#884]
**Question**

How to position tooltips on map charts? 

I am trying to change the position of a tooltip on a map chart. It's not working.
```
polygonSeries.mapPolygons.template.setAll({
      tooltipText: '{name}',
      tooltipX: 100,
    });
```

But that doesn't seem to be possible with map charts?
The docs say ([here](https://www.amcharts.com/docs/v5/concepts/common-elements/tooltips/#Position)):

> For elements that have width and height (e.g. columns), it's possible to set the point its tooltip will be anchored to.

Does that mean we can't set the point the tooltip is anchored to on map charts polygons? 

**Environment **

 - amCharts version: 5.3.11
 - Angular version: 15.1.5

**Comment by zeroin** [comment]
This doesn't work on map polygons, sorry. The only way to modify position of a tooltip would be to create a tooltip and then modify dx/dy settings, something like:

```
var tooltip = am5.Tooltip.new(root, {
  dx:100
});

// Create main polygon series for countries
// https://www.amcharts.com/docs/v5/charts/map-chart/map-polygon-series/
var polygonSeries = chart.series.push(am5map.MapPolygonSeries.new(root, {
  geoJSON: am5geodata_worldLow,
  tooltip: tooltip
}));
```

**Comment by ibrahimAboelsuod** [comment]
> The only way to modify position of a tooltip would be to create a tooltip and then modify dx/dy settings, something like:

This seems to do the trick, thank you.
