### ISSUE TITLE
Legend element not always becomming gray when using series.hide() with dynamic legend text

### ISSUE THREAD

**Issue by SirBouBou** [amcharts/amcharts5#885]
Hello,

I'm having multiple XY chart with custom buttons that call series.hide() and series.show() functions to dynamically activate or desactivate multiple element on the graph. But while the series are disapearing correctly, the linked legend element does not always become gray, except if I hover them with my mouse.

Here's the exemple when using my custom button : 
![image](https://user-images.githubusercontent.com/60543491/231767874-f5b83f06-0f7d-44a9-99f9-0d7424247460.png)

Here's the same exemple after hovering with my mouse on each legend element :
![image](https://user-images.githubusercontent.com/60543491/231768051-687b7e81-4d11-4837-80df-8b704627e95e.png)

The function used by my custom button : 
![image](https://user-images.githubusercontent.com/60543491/231768468-06c230f0-fa02-4da7-a070-7bcc7347359a.png)

I'm not completely sure it's a bug, but it looks like one. Also, maybe there's a better way to do what I'm trying to achieve here that I'm not aware about.

**Comment by SirBouBou** [comment]
Hello, sorry for taking a long time to answer, needed some time before coming back to this problem. Adding the set("disabled",true) seems to have decreased the frequency of the bug but it's still there.

Unfortunatly, I can't reproduce it in a codepen, maybe because I'm not able to reproduce the resources the real program need to create multiple graph, each one fetching multiple rows of data from the database.

Is there a way to update/refresh the legend that I could call at the end of my function (like what's happening when hovering legend buttons) ? Or do you have another idea, especially for chart that uses many resources ?

**Comment by zeroin** [comment]
There is no general redraw method for legend. I must say I really don't know why this happens and could only help if you could create an example where this is reproduced.

**Comment by SirBouBou** [comment]
Okay no problem, I'll soon be able to test this code in another environment. If the issue persist, I will try again to simulate it in a codepen and share it there.
