### ISSUE TITLE
Animated.js File fails to work with salesforce lightning locker service

### ISSUE THREAD

**Issue by Devarshi87** [amcharts/amcharts5#886]
I am trying to use the amCharts in lightning web components in salesforce and the Animated.js script fails to load with a blank undefined error.

Any workarounds for this?

The locker service documentation can be found here - https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/security_api_viewer.htm

and the validation console is [here](https://developer.salesforce.com/docs/component-library/tools/locker-service-console)

Thanks

**Comment by Devarshi87** [comment]
The Lightning Locker is a security architecture for Lightning components. Its meant to enhance component security inside salesforce, more information can be found on this [link](https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/security_code.htm) .

At present just loading the script causes and undefined error `renderedCallback(){
        Promise.all([
    
          loadScript(this, amChart + '/amcharts/index.js'),
          loadScript(this, amChart + '/amcharts/xy.js'),
          loadScript(this, amChart + '/amcharts/Animated.js' ),
		])
			.then(() => {
                this.isChartJsInitialized = true;
                 this.createChart();
			})
			.catch(error => {
				console.log('chartConfig======error===>',error);
				// this.dispatchEvent(
				// 	new ShowToastEvent({
				// 		title: 'Error loading amChart',
				// 		message: error.message,
				// 		variant: 'error',
				// 	})
				// );
			});

    }`

**Comment by Pauan** [comment]
Are you sure that the URL is correct? Shouldn't it be `/amcharts/themes/Animated.js`?

**Comment by Devarshi87** [comment]
I am loading it from a local resource, so the script shows up in the console properly.

**Comment by Pauan** [comment]
What is your `loadScript` function?

**Comment by Devarshi87** [comment]
loadScript is a method provided by Lightning web component framework in salesforce to load third party scripts.

**Comment by Pauan** [comment]
Well, I can't reproduce it in the console, I always get `SecurityError: The operation is insecure.` and it refuses to run. So I think you'll have to ask Lightning Locker for help, since the problem is with their loading system / sandbox.

The `Animated.js` file doesn't do anything weird, it just exports some classes, so I don't see any reason why it should break.
