### ISSUE TITLE
How to show polygon series tooltip on hover of external element(Outside of map)?

### ISSUE THREAD

**Issue by exytab** [amcharts/amcharts5#888]
For amcharts4, it was possible to trigger a hover event outside of the component.
https://www.amcharts.com/docs/v4/tutorials/map-polygon-hover-via-api/#Finding_polygon_object

```javascript
let france = polygonSeries.getPolygonById("FR");
france.isHover = true;
```

But for amcharts5, this doesn't work
```javascript
const france = polygonSeries.getDataItemById("FR");
france.component.hover(); 
```

 Can you please suggest something here?

**Comment by zeroin** [comment]
You should get `mapPolygon` object from data item:

`france.get("mapPolygon").hover();`
