### ISSUE TITLE
ERROR in ../node_modules/@amcharts/amcharts5/index.js Module not found: Error: Can't resolve './.internal/core/util/Timezone'

### ISSUE THREAD

**Issue by zeair** [amcharts/amcharts5#889]
Hello, 

When I try to webpack Amcharts5 I'm receiving following error: 

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/Registry' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 3:0-89 3:0-89 3:0-89 3:0-89
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/Root' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 1:0-45 1:0-45
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/Theme' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 2:0-47 2:0-47
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/Bullet' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 8:0-56 8:0-56
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/Button' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 9:0-56 9:0-56
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/Chart' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 35:0-54 35:0-54
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/Circle' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 10:0-56 10:0-56
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/Component' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 13:0-72 13:0-72 13:0-72
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/Container' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 14:0-62 14:0-62
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/Ellipse' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 11:0-58 11:0-58
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/Graphics' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 15:0-60 15:0-60
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/GridLayout' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 16:0-64 16:0-64
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/HeatLegend' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 17:0-64 17:0-64
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/HorizontalLayout' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 18:0-76 18:0-76
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/Label' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 19:0-54 19:0-54
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/Layout' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 20:0-56 20:0-56
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/Legend' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 21:0-56 21:0-56
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/Line' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 22:0-52 22:0-52
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/Picture' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 23:0-58 23:0-58
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/PointedRectangle' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 24:0-76 24:0-76
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/RadialLabel' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 25:0-66 25:0-66
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/RadialText' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 26:0-64 26:0-64
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/Rectangle' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 27:0-62 27:0-62
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/RoundedRectangle' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 29:0-76 29:0-76
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/Scrollbar' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 30:0-62 30:0-62
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/SerialChart' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 36:0-66 36:0-66
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/Series' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 34:0-56 34:0-56
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/Slice' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 32:0-54 32:0-54
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/Slider' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 31:0-56 31:0-56
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/Sprite' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 33:0-56 33:0-56
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/SpriteResizer' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 65:0-70 65:0-70
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/Star' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 12:0-52 12:0-52
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/Text' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 37:0-52 37:0-52
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/Tick' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 38:0-52 38:0-52
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

ERROR in ../node_modules/@amcharts/amcharts5/index.js
Module not found: Error: Can't resolve './.internal/core/render/Tooltip' in 'D:\backup\node_modules\@amcharts\amcharts5'
 @ ../node_modules/@amcharts/amcharts5/index.js 39:0-58 39:0-58
 @ ./RAPORTS/raports_datamodel.ts
 @ ./RAPORTS/raports.ts
 @ multi ./RAPORTS/raports.ts

My package.json is 

{
  "name": "Audits",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "start": "webpack-dev-server --inline",
    "uploadToPWCDev": "webpack --config webpack.uploadToPWCDEV.config",
    "uploadToPWCProd": "webpack --config webpack.uploadToPWCPROD.config"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@amcharts/amcharts4": "^4.10.35",
    "@amcharts/amcharts5": "^5.3.11",
    "@babel/cli": "^7.7.5",
    "@babel/polyfill": "^7.7.0",
    "@babel/preset-env": "^7.7.6",
    "@babel/preset-typescript": "^7.7.4",
    "@pnp/common": "^1.3.8",
    "@pnp/graph": "^1.3.8",
    "@pnp/logging": "^1.3.8",
    "@pnp/odata": "^1.3.8",
    "@pnp/polyfill-ie11": "^1.0.2",
    "@pnp/sp": "^1.3.8",
    "@types/chosen-js": "^1.8.1",
    "@types/microsoft-ajax": "0.0.35",
    "@types/sharepoint": "^2016.1.6",
    "array-flatten": "^3.0.0",
    "array.prototype.flat": "^1.2.3",
    "babel-engine-plugin": "^0.3.0",
    "babel-loader": "^8.0.6",
    "bootstrap-switch": "^3.4.0",
    "chosen-js": "^1.8.7",
    "computed-style-to-inline-style": "^3.0.0",
    "core-js": "^3.4.8",
    "dom-to-image": "^2.6.0",
    "html2canvas": "^1.0.0-rc.5",
    "inline-css": "^2.6.3",
    "juice": "^6.0.0",
    "p-iteration": "^1.1.8",
    "regenerator-runtime": "^0.13.3",
    "source-map-loader": "^0.2.4",
    "spsave-webpack-plugin": "^2.0.0",
    "sweetalert2": "^9.5.3",
    "ts-loader": "^6.2.1",
    "ts-polyfill": "^3.7.3",
    "typescript": "^4.3.2",
    "weakmap-polyfill": "^2.0.1",
    "webpack-cli": "^3.3.10"
  },
  "devDependencies": {
    "@babel/core": "^7.7.5",
    "@fortawesome/fontawesome-free": "^5.12.0",
    "html-webpack-plugin": "^3.2.0",
    "install": "^0.13.0",
    "webpack": "^4.41.2"
  }
}

I tried diffrent versions of Amcharts, webpack and typescirpt - I'm not able to solve it. If anyone could point me in the right direction would be perfcet. Thank you.

**Comment by martynasma** [comment]
What do you mean by "try to webpack Amcharts5"?
