### ISSUE TITLE
Pie charts do not render if the order of adding the series/data differs from the default examples

### ISSUE THREAD

**Issue by buggedcom** [amcharts/amcharts5#89]
I wrote out a long detailed explanation but appears github is having issues and it was lost.

Check this codepen https://codepen.io/buggedcom/pen/BadEqMy

There if the data is added to the series differently than your examples it results in an empty pie chart. We do it differently to prevent needless react rerenders. This sequence works fine with XY charts

**Comment by martynasma** [comment]
> I wrote out a long detailed explanation but appears github is having issues and it was lost.

It's fine. CodePen is better than lengthy explanation.

Thanks for the heads up!

**Comment by martynasma** [comment]
OK, so here's the deal. amCharts 5 starts processing data and creating series elements (slices) immediately after you set data.

If at that point series is not assigned to a chart it does not have access to a theme, which in turn cannot set color set for the series.

Solution is to either set data after series was added to chart, or to create a color set for the series:

```JavaScript
am5percent.PieSeries.new(root, {
    colors: am5.ColorSet.new(root, {}),
    name: "Series",
    valueField: "sales",
    categoryField: "country"
  });
```

**Comment by buggedcom** [comment]
I get that, but what I'm trying to point out is an inconsistency with the charts API depending on the chart type. For example:

https://codepen.io/buggedcom/pen/XWaweVM

a clustered bar chart using the same ordering of setting data works fine. Ideally the API between the libraries should probably work the same?

**Comment by martynasma** [comment]
Inconsistency comes from the fact that in XYChart colors are assigned to series by the chart when they are added, whereas in PieChart colors to slices are assigned to PieSeries elements by series itself.

At this moment we do not have any plans to change it, I'm afraid.

**Comment by buggedcom** [comment]
Ok - fair enough.
