### ISSUE TITLE
Dynamically change axis labels

### ISSUE THREAD

**Issue by borutc** [amcharts/amcharts5#890]
I'm using an adapter to format the y-axis labels. Something like this
`yAxis.get('renderer').labels.template.adapters.add('text', () => {
    return 'Custom Label';
  });`
I'd like to change those labels to something else on a button click. Is this achievable in amCharts 5? It was doable in amcharts 4 (https://github.com/amcharts/amcharts4/issues/3212)

code pen of what im trying to do: https://codepen.io/borutc/pen/rNqLXBX

**Comment by martynasma** [comment]
Yes, it's possible.

Please refer to this doc:
https://www.amcharts.com/docs/v5/concepts/common-elements/labels/#interactive-axis-labels

**Comment by zeroin** [comment]
One way of doing this - loop through all eintities of a template and set new text:

```
am5.array.each(xRenderer.labels.template.entities, (label)=>{
  label.set("text", "some new text")
}
```

You can also use adapter, but you should trigger it in order it to be applied at some event:

am5.array.each(xRenderer.labels.template.entities, (label)=>{
  label.set("text", label.get("text")
}

**Comment by borutc** [comment]
> One way of doing this - loop through all eintities of a template and set new text:
> 
> ```
> am5.array.each(xRenderer.labels.template.entities, (label)=>{
>   label.set("text", "some new text")
> }
> ```
> 
> You can also use adapter, but you should trigger it in order it to be applied at some event:
> 
> ```
> am5.array.each(xRenderer.labels.template.entities, (label)=>{
>   label.set("text", label.get("text")
> }
> ```

This does not seem to be working. After changing labels with
`am5.array.each(xRenderer.labels.template.entities, (label)=>{
  label.set("text", "some new text")
}`
adapter is called, changing them right back to the previous value. 
Check my updated code pen https://codepen.io/borutc/pen/rNqLXBX
