### ISSUE TITLE
XY axis with date axis scatter issue

### ISSUE THREAD

**Issue by tech-dev-vin** [amcharts/amcharts5#892]
**Bug description**

On Scrollbar X zoom some of my scatter bubbles are disappearing. I have attached a link with the same.

Codepen link: https://codepen.io/vineetechosquare/pen/GRQdNYM

**Comment by martynasma** [comment]
The date-based data need to be ordered in ascending order, whereas yours seem to be out of order. It creates the anomalies.

https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#Data_order

**Comment by tech-dev-vin** [comment]
thanks @martynasma
