### ISSUE TITLE
Choppy scrolling behaviour

### ISSUE THREAD

**Issue by alexpetrean80** [amcharts/amcharts5#896]
**Question**

Having a scrollable container with multiple axes and wheelY set to “none” in the chart options, scrolling via mouse while having the mouse over the chart(not over the scrollbar) is very choppy. It looks like the event is debounced or straight up ignored some times, other times it works as expected. 

CodePen link: 

[https://codepen.io/alexpetrean80/pen/ExdNBYo](https://codepen.io/alexpetrean80/pen/ExdNBYo)

**Environment (if applicable)**

amCharts version: 5.3.9

**Comment by zeroin** [comment]
So I have a workaround for this problem - you have to set `interactiveChildren:false` for the scrollable container:
https://codepen.io/team/amcharts/pen/vYVJXgQ?editors=1010

We will try to find a more proper solution, but for now it's the best I can offer.
