### ISSUE TITLE
SankeyNode does not support fill adapter

### ISSUE THREAD

**Issue by jmtimko5** [amcharts/amcharts5#898]
**Bug description**
- Adapters do not seem to work on SankeyNodes. I am adding a `fill` adapter to the node template, and it is never invoked on render.
 [CodePen](https://codepen.io/jmtimko5/pen/VwEbVrx)

**Environment (if applicable)**
 - amCharts version: Latest (I think that is what codepen is downloading. In our environment we are using 5.1.7)

**Comment by xorspark** [comment]
You need to set the fill adapter on the `rectangles` template inside of the nodes list to change their color.

```
series.nodes.rectangles.template.adapters.add("fill", (originalFill, target)=> {
  return am5.color("#f00")
})
```

**Comment by jmtimko5** [comment]
This was the initial approach we tried. This however has the problem of the sankey links not respecting the rectangle fill in their gradient coloring. See this screenshot from modifying the codepen above with the rectangles adapter.

![Screen Shot 2023-04-26 at 1 41 43 PM](https://user-images.githubusercontent.com/6867087/234697859-28447037-8921-46b0-8e50-9f527d8ab982.png)

**Comment by xorspark** [comment]
You also need to set an adapter on the links template as well if you want to change them, otherwise it will default to the gradient. Note that you have to set the fillStyle to `solid` for a fill adapter to work.

```
series.links.template.adapters.add("fill", (originalFill, target)=> {
  return am5.color("#f00")
})
series.links.template.setAll({
  fillStyle: 'solid'
})
```
