### ISSUE TITLE
Set DateAxis tooltip position

### ISSUE THREAD

**Issue by ptorrent** [amcharts/amcharts5#899]
Hello,

Is there a way to force the tooltip to be set on the top of the chart ?

![image](https://user-images.githubusercontent.com/6083644/234644450-4afd22d6-5258-4642-87cd-f217a671648a.png)

I tried different way
```
	tooltip: am5.Tooltip.new(root, {
		opposite: true
	})
```

Thanks for your help!

**Comment by martynasma** [comment]
There's no such setting, but you can achieve that by adding additional axis on top.

Here's an example:
https://www.amcharts.com/docs/v5/tutorials/additional-axis-tooltip-to-display-totals/
