### ISSUE TITLE
Column opacity resets when hiding series

### ISSUE THREAD

**Issue by aniznik1** [amcharts/amcharts5#90]
The opacity of a ColumnSeries seems to reset when toggling it with legend item.

Reproduce: https://jsfiddle.net/tnu76j08/10/
1. Click on any legend item
2. Opacity of selected series will reset to 1

Opacity also resets when calling `series.appear()`

**Comment by martynasma** [comment]
Well, hiding/showing element animates its opacity, hence it's getting reset.

Better set opacity on series columns instead, so they don't get reset:

```JavaScript
  series.columns.template.setAll({
    tooltipText: "{name}, {categoryX}:{valueY}",
    width: am5.percent(90),
    opacity: 0.4,
    tooltipY: 0
  });
```
