### ISSUE TITLE
Chart shakes on safari resize

### ISSUE THREAD

**Issue by Vostryakoff** [amcharts/amcharts5#900]
https://user-images.githubusercontent.com/27483492/234890308-5ab4174f-6a1b-4ae0-a91d-6d160363d93e.mov

Sometimes when resizing a window, there is a bug in Safari. Also when full screen mode. The easiest way is to click on the sidebar safari toggle button

**Comment by martynasma** [comment]
Does this happen every time?
Which version of macOS are you running?

I was clicking around on the latest macOS Safari on that demo, and wasn't able to reproduce the shaking :)

**Comment by Vostryakoff** [comment]
Safari 16.4. Happen not every time. Most often when you decrease the window together sidebar button.

**Comment by Vostryakoff** [comment]
https://user-images.githubusercontent.com/27483492/236445847-f0802c8e-0a08-431d-9452-d870660542c5.mov

**Comment by martynasma** [comment]
Does this happen to you outside of amcharts.com website?

I was able to reproduce it when the website switches to mobile mode (low resolution) only. So it must be something related to website, not the library.

**Comment by Vostryakoff** [comment]
@martynasma At first I reproduced it locally on my working  project. One of the clients complained about this bug. I thought that my environment breaks amchart. But on demo website reproduce too.
