### ISSUE TITLE
Legend not appear with right colors

### ISSUE THREAD

**Issue by cbaghiuAIZ** [amcharts/amcharts5#901]
I have created a codepen where you see the error.

First of all you don't see the color of each series in the legend. The Positive series should be yellow and the Negative series should be green.

Second, when I hover over one bar it changes the colors of the legend for both. I think this is also a bug.

https://codepen.io/cbaghiuAIZ/pen/MWPozQw

**Comment by zeroin** [comment]
You should set fill on series, as legend doesn't take color from columns, only from series. 
My suggestion here would be to use one series here and add custom data to the legend instead.

**Comment by cbaghiuAIZ** [comment]
Thanks @zeroin  for answering. Could you please tell me how to do it. The bookstore is new to me and I don't know how to do it. What happens is that when I click on the Positive legend I want only the positive ones to be disabled, would that be possible?

**Comment by zeroin** [comment]
Here is how I'd do it:
https://codepen.io/team/amcharts/pen/NWOgoLY/34170da069f4c343dfa472b366c68282

**Comment by cbaghiuAIZ** [comment]
Great. Thanks @zeroin :) I close this because if solved
