### ISSUE TITLE
Bullet tooltip overlaps over another

### ISSUE THREAD

**Issue by jcostello** [amcharts/amcharts5#905]
**Bug description**

Having a bullet with tooltip with close values overlaps the tooltips over another

Left is the cursor tooltip, right are the bullet toolip (only bullet in the last point of the series)
![image](https://user-images.githubusercontent.com/1168582/235971160-ecd9f17e-a117-4641-ba8d-b454b3b641ac.png)

```
   currentSerie.bullets.push(function (root, series, dataItem) {
          const last = series.dataItems[series.dataItems.length - 1]
          if (last.uid === dataItem.uid) {
            return am5.Bullet.new(root, {
              sprite: am5.Circle.new(root, {
                radius: 2,
                fill: series.get('fill'),
                showTooltipOn: 'always',
                tooltipText: "{name} {valueY.formatNumber('#.###')}",
                tooltip: am5.Tooltip.new(root, {}),
              }),
            })
          }
        })

```

**Environment (if applicable)**

 - amCharts5
 - Chrome

**Comment by martynasma** [comment]
Stacking tooltips is an intended behavior. Would you rather they overlapped?

Or am I missing something here?

**Comment by jcostello** [comment]
@martynasma sorry, I should have say overlap. The intended behavior is the one on the left, but for bullet is behaving like on the right

**Comment by jcostello** [comment]
@martynasma yes, here you are

https://jsfiddle.net/zvkLjfsx/1/

**Comment by martynasma** [comment]
Thanks.

Unfortunately, the tooltip stacking only is applied when used in conjunction with an `XYCursor`.

Always-on tooltips are not stacked. There's no way around it, I'm afraid.

**Comment by jcostello** [comment]
Got it.

I need to have something like the tooltip at the end on each line series. Labels seems to have the same problem. Any other posible way to do it so they dont overlap?. Is there a way to have a XYCursor stick at the end and one following the mouse?

**Comment by martynasma** [comment]
No, I'm afraid there's no way to have two cursors.

**Comment by jcostello** [comment]
No problem. Any suggestion on how to acomplish what I want to do?

**Comment by zeroin** [comment]
If fyou use labels for bullets, you could try this approach:
https://www.amcharts.com/docs/v5/tutorials/solving-overlapping-bullets/

**Comment by jcostello** [comment]
@zeroin unfortunatly it doesnt solve the issue because the overlap happens on close values. So I need the library to know when the overlap happens and move the labels

**Comment by martynasma** [comment]
I'm afraid we do not have plans for bullet overlap check functionality.
