### ISSUE TITLE
Series html tooltip for combination of category & date axis with a cursor

### ISSUE THREAD

**Issue by hesselmeulenbeld** [amcharts/amcharts5#907]
Is it possible to use a series html tooltip when having a category axis on the y-axis and a date axis on the x-axis, and also having the cursor enabled?

See: https://codepen.io/hesselmeulenbeld/pen/poxdGRN

Without the cursor the correct tooltip is shown in the correct location
When adding the tooltip to the columns template using setup it also works, but this can't be used when having a lot of data items or having complex html tooltips.

When the cursor is enabled the tooltip is shown at the start of the category with a (random?) value.

**Comment by zeroin** [comment]
Hi, setting `snapToSeries:[series]` for the cursor should do the thing:

**Comment by hesselmeulenbeld** [comment]
Thanks, that works.
