### ISSUE TITLE
Hovering effect not working for amcharts5 when fingerprint is enabled in Brave Browser

### ISSUE THREAD

**Issue by Utkarshsteve** [amcharts/amcharts5#908]
I'm using amcharts5 to create a sunburst chart and I'm facing an issue where only some of the slices of the chart are responding to mouse hover effects. This seems to be happening only when I'm using Brave Browser with fingerprint enabled. Is there any way to apply the hovering effect to all slices of the chart, even if the fingerprint is enabled?

This is the code snippet i am running in [codepen]( https://codepen.io/team/amcharts/pen/KKmGxgo) , open this link in brave browser.

Is there any alternative for enabling hovering effect or do I have to add custom hovering effect to the amcharts?

**Comment by martynasma** [comment]
By default, Brave scrambles canvas pixel detection (which we rely on), so interactions might work erratically on that browser, or not work at all.

They call it "fingerprinting protection". You may disable this specific protection, without completely turning the shields off.

It's not just amCharts. It's any web app that relies on interactions with the canvas elements.

**Comment by Utkarshsteve** [comment]
@martynasma can you suggest any alternate library which will overcome this issue?

**Comment by martynasma** [comment]
You can use amCharts 4. But it's support is nearing EOL.

**Comment by Utkarshsteve** [comment]
Thank You @martynasma .
