### ISSUE TITLE
Change column bullet color depending on it's position

### ISSUE THREAD

**Issue by roshaxo** [amcharts/amcharts5#912]
Hello!
I want to change bullet color depending on it's position.
For example:
1. If bullet is inside the column (1000) - make it white.
2. If bullet is outside the column (1.5, 2, 3)- make it black.
3. If bullet can't fit inside the column (2500) - make it black and add padding.

As I understand, I need to retrieve somehow y-coordinates and heights of each column it's bullet.
Could you help me, please?

```
series.bullets.push(function(root, series, dataItem) {
    let fill = null;
    
    if (dataItem.dataContext.value === 10000) fill = root.interfaceColors.get("alternativeText");
    
    return am5.Bullet.new(root, {
      sprite: am5.Label.new(root, {
        text: "{valueY}",
        ...(fill ? {fill} : {}),
        centerX: am5.percent(50),
        centerY: am5.percent(100),
        populateText: true
      })
    });
  });
```

<img width="493" alt="image" src="https://github.com/amcharts/amcharts5/assets/108542985/dbab6e56-34b6-4104-9456-bb1f22826bce">

**Comment by martynasma** [comment]
Perhaps this tutorial will help:
https://www.amcharts.com/docs/v5/tutorials/hide-or-relocate-label-bullets-for-small-columns/

It shows how you can modify bullet's settings depending of the target column height.

**Comment by roshaxo** [comment]
@martynasma How did I miss this example... Thank you so much!!!
