### ISSUE TITLE
How to adjust legend container ?

### ISSUE THREAD

**Issue by rareaqil** [amcharts/amcharts5#913]
![image](https://github.com/amcharts/amcharts5/assets/64183077/168fc49c-59fa-43e7-9e9b-c1e1c1d62c0d)
how to adjust the legend to not make any spases and make the chart getting squeeze

**Comment by martynasma** [comment]
I think the whitespace on the right is reserved for value labels. You can disable those:
https://www.amcharts.com/docs/v5/concepts/legend/#Disabling_value_labels

**Comment by rareaqil** [comment]
it workss

**Comment by rareaqil** [comment]
![image](https://github.com/amcharts/amcharts5/assets/64183077/470b82ec-6fd7-412a-92a9-51b119d0f190)
can we posiblly remove the grid in the chart ?

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.

**Comment by rareaqil** [comment]
thanks you so much
