### ISSUE TITLE
Can we Select or Apply Right Click on Plotted Graph Line/Candle? and How? 

### ISSUE THREAD

**Issue by mukeshbadgujar** [amcharts/amcharts5#914]
I want apply selection on line.

![image](https://github.com/amcharts/amcharts5/assets/32473209/5b4ac740-68df-4ae5-bc63-63c601f954fd)

**Comment by martynasma** [comment]
Right-clicks are tricky, because disabling context menu depends on browser/platform. If you can do that, you can use `pointerdown` or `pointerup` events to detect the right click:

```
valueSeries.columns.template.events.on("pointerup", function(ev) {
  if (ev.originalEvent.which == 3) {
    console.log("Right-clicked on a candle", ev.target)
  }
});
```
