### ISSUE TITLE
how to apply numberformat on labels?

### ISSUE THREAD

**Issue by lasivtech** [amcharts/amcharts5#915]
I want to display full numbers without float on donut chart labels.

I have tried below code, that don't work. please help

```
this.series.labels.template.setAll({
      fontSize: 14,
      maxWidth: 100,
      oversizedBehavior: "wrap", // to truncate labels, use "truncate"
      numberFormatter : {
        numberFormat: "#."
      }
    });
```

**Comment by xorspark** [comment]
`numberFormatter` needs to be a [`NumberFormatter`](https://www.amcharts.com/docs/v5/reference/numberformatter/) instance, not a regular object.

```
series.labels.template.set(
  "numberFormatter", 
  am5.NumberFormatter.new(root, {
    numberFormat: "#."
  })
);
```

Note that this won't impact any inline calls to `formatNumber` in the text value. The default value for the label's `text` in a pie chart is:

```
series.labels.template.set("text", "{category}: [bold]{valuePercentTotal.formatNumber('0.00')}%[/] ({value})");
```

**Comment by lasivtech** [comment]
> `numberFormatter` needs to be a [`NumberFormatter`](https://www.amcharts.com/docs/v5/reference/numberformatter/) instance, not a regular object.
> 
> ```
> series.labels.template.set(
>   "numberFormatter", 
>   am5.NumberFormatter.new(root, {
>     numberFormat: "#."
>   })
> );
> ```
> 
> Note that this won't impact any inline calls to `formatNumber` in the text value. The default value for the label's `text` in a pie chart is:
> 
> ```
> series.labels.template.set("text", "{category}: [bold]{valuePercentTotal.formatNumber('0.00')}%[/] ({value})");
> ```

Thank you so much. that works :)
