### ISSUE TITLE
Force-directed: How to set different radius ranges for parent nodes and child nodes

### ISSUE THREAD

**Issue by meganindya** [amcharts/amcharts5#917]
I have a 2-level force-directed chart where there are some parent nodes and each parent node has some child nodes.

I can set the circle radii range using:
```ts
series.setAll({
  minRadius: 24,
  maxRadius: 40,
})
```

However, that range seems to be global. Is there a way to set different ranges for parent nodes and child nodes? For example, I want child radii to vary between [16-32] and parent radii to vary between [32-48], based on the value of their `value` field.

**Comment by martynasma** [comment]
I suppose you can do that with an adapter for circle's `radius`. E.g.:

```JavaScript
series.circles.template.adapters.add("radius", function(radius, target) {
  if (target.dataItem.get("depth") == 0) {
    return 10;
  }
  return radius;
});
```

Basically you can derive if the circle is for a top-level node (`target.dataItem.get("depth") == 0`) then act accordingly.

Hope this helps.

**Comment by meganindya** [comment]
Thanks a lot!
