### ISSUE TITLE
HTML label appears above the tooltip

### ISSUE THREAD

**Issue by roshaxo** [amcharts/amcharts5#918]
Hello!

I have Y-Axis label with tooltip. Both of them are implemented with `HTML` prop, but the label appears above the tooltip.
I tried adding `label` property to the tooltip, but it didn't help.

Could you help me, please?

<img width="653" alt="image" src="https://github.com/amcharts/amcharts5/assets/108542985/458c974b-d7a0-49e6-aaeb-60ab15b97dd4">

**Comment by martynasma** [comment]
I'm afraid there's no way around it. HTML content is displayed above canvas, in which tooltip border/background is drawn.

You can try using CSS in the HTML of your tooltip, add a white background to it, so it obstructs any content below.

**Comment by roshaxo** [comment]
@martynasma Got you! Thanks.
