### ISSUE TITLE
Multiple blank canvases drawn on top of chart canvas in Firefox and Chrome

### ISSUE THREAD

**Issue by cbryan-risklens** [amcharts/amcharts5#92]
Hey AMCharts team!

I'm having a problem in which three blank `<canvas>` elements are being drawn on top of the main `<canvas>` element that contains the chart.

I am seeing it in both Firefox and Chrome with this Codepen: https://codepen.io/cbryan-risklens/pen/KKvYVJP

The problem is that, when I right click on the chart and click Save Image As, it saves a transparent PNG with only the AMCharts logo in the bottom left:
![canvas-blank](https://user-images.githubusercontent.com/37117937/142974733-89efeb21-733e-482e-b470-c5d6e575af39.png)

But if I delete the three extra canvases, I can download the image as normal:
![canvas](https://user-images.githubusercontent.com/37117937/142974748-49192a1b-e7b6-453b-ad2b-3cbbf890d108.png)
:

**Comment by martynasma** [comment]
This is by design. The canvases are not blank, but used for various elements, like scrollbars, tooltips, etc.

If you need to save a snapshot of a chart, I suggest using exporting plugin. Either via export menu, or via its API:

https://www.amcharts.com/docs/v5/concepts/exporting/

**Comment by cbryan-risklens** [comment]
Got it, thanks!
