### ISSUE TITLE
Category Y-Axis with responsive HTML label

### ISSUE THREAD

**Issue by roshaxo** [amcharts/amcharts5#921]
Hello!
My goal is to create responsive category Y-Axis with HTML labels + tooltips.
I've managed to achieve responsiveness, but I have 2 issues:
1. Tooltips don't work.
2. I need some additional styles for html, based on data, but I can't set `html` for labels using `.adapters`. Only `.set` works for me.

Codepen:
https://codepen.io/flexinclique/pen/zYmaXYp

Maybe you know how to fix it or have better solution.

Thank you in advance.

**Comment by martynasma** [comment]
> Tooltips don't work.

I'm afraid tooltips are [not supported](https://www.amcharts.com/docs/v5/concepts/common-elements/html-content/#Tooltips_on_HTML_elements) on HTML elements.

> I need some additional styles for html, based on data, but I can't set html for labels using .adapters. Only .set works for me.

Adapters for `html` should work.

Here's an example:
https://codepen.io/team/amcharts/pen/GRxWbeJ

**Comment by martynasma** [comment]
> @martynasma The `pointerover` event also doesn't work for the HTML label?

Nope. But I suppose you can add various events on the elements in label's HTML.

**Comment by roshaxo** [comment]
@martynasma Will try, thanks!
