### ISSUE TITLE
Partially Filling Rectangle in treemap with a percentage value

### ISSUE THREAD

**Issue by NandaNxD** [amcharts/amcharts5#922]
![image](https://github.com/amcharts/amcharts5/assets/65838540/327509be-cd6e-4e26-b4e6-d8808a747acb)

Im trying to give a partial fill based on a percentage value that every data point in our data has, this is other than the value that is taken for the treemap width and height. Is it possible to partially fill a color of rectangle treemap using percentages?
Please help me out in this :(

**Comment by NandaNxD** [comment]
Could we achieve it using some other method?

**Comment by martynasma** [comment]
Come to think of it, it's totally doable using `Rectangle` as a bullet and a few adapters:
https://codepen.io/team/amcharts/pen/JjmBaOa

**Comment by NandaNxD** [comment]
Thanks a lot!!!! :)
