### ISSUE TITLE
Negative values in ValueAxis labels for RTL

### ISSUE THREAD

**Issue by UMSF-K13-3-Sahan** [amcharts/amcharts5#924]
**Bug description**
In labels of value axis i have incorrect view of negative values (With and without percent). Minus sign in wrong place. It must be on the left side of number.
(demo [here](https://codepen.io/umsf-k13-3-sahan/pen/NWOLXwq))

I had created same issue for amcharts4 3 years ago, and you fixed it by adding new `NumberFormatter` setting: `forceLTR`.

**Comment by martynasma** [comment]
Thanks for the heads up!

We're adding `forceLTR` to `NumberFormatter` in the next version.

Will let you know when the new version is out.

**Comment by martynasma** [comment]
Implemented in [5.3.13](https://github.com/amcharts/amcharts5/releases/tag/5.3.13).

## [5.3.13] - 2023-05-30

### Added
- New setting `forceLTR` (default: `false`) on `NumberFormatter`. If set to `true`, will force all formatted numbers to be LTR, regardless of the direction settings on chart/page.
- `legend: true` added to `dataContext` of a legend bullet `DataItem` (bullets are created for LineSeries), just so it is possible to distinguish between bullets created for series and legend.

### Fixed
- `Hierarchy` was not not keeping its node toggle state after resize.
- In some cases `DateRangeSelector` was generating an error when zooming `SotckChart`.
- Always-on / on-click `Tooltip` was not being disposed properly when `Root` element was disposed.
- Memory leak was happening when disposing a `Container` with `verticalScrollbar` enabled.
- `PieSeries` was erroring if its `stroke` setting was set.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
