### ISSUE TITLE
Click on tooltip doesn't work

### ISSUE THREAD

**Issue by VikaBondareva** [amcharts/amcharts5#926]
**Bug description**

We use custom HTML tooltip with a button. I have updated version of amchart to 5.3.12 and in this version clicking on button in tooltip doesn't work anymore. And the "cursor:pointer" styles don't work. But with version 5.3.8 the button click works

https://codesandbox.io/s/elegant-dawn-is0en3?file=/src/utils/tooltip.js

**Environment**

 - amCharts 5.3.12
 - React, TS

**Comment by VikaBondareva** [comment]
Added this code, but with it the tooltip doesn't disappear when hovering outside the chart. And buttons works. How to fix disappearing tooltip?

**Comment by martynasma** [comment]
This issue was fixed in dev version, and will be released soon.

We'll notify you here when that happens.
