### ISSUE TITLE
'Error: EventDispatcher is disposed' when customizing tooltips in the Drill-Down Map Chart.

### ISSUE THREAD

**Issue by suu3** [amcharts/amcharts5#928]
**Question**

Hello, I am currently using the same Drill-down Map Chart as the following demo. https://codepen.io/team/amcharts/embed/WNOpoJL?default-tab=result&editable=true&theme-id=dark

I wrote the code as follows because I want to customize the tooltip of my chart:

```
const tooltip = am5.Tooltip.new(root, {
    getFillFromSprite: false,
});
tooltip.setAll({
    background: am5.RoundedRectangle.new(root, {
        cornerRadiusTL: 50,
        cornerRadiusTR: 50,
        cornerRadiusBL: 50,
        cornerRadiusBR: 50,
        fill: am5.color(0xffd400),
    }),
    minWidth: 100,
});
```

Then I set the tooltip for the worldSeries and countrySeries:

```
worldSeries.mapPolygons.template.setAll({
    tooltip,
    tooltipText: "{name}",
    interactive: true,
    fill: am5.color(0xaaaaaa),
    templateField: "polygonSettings",
});

countrySeries.mapPolygons.template.setAll({
    tooltip: tooltip,
    tooltipText: "{name}",
    interactive: true,
    fill: am5.color(0xaaaaaa)
});
```

However, when I click on a country, then click "Back to the world Map," and click a country again, I get the following error:

```
index.js:1 Uncaught Error: EventDispatcher is disposed
    at g.isEnabled (index.js:1:261710)
    at l._setDataItem (index.js:1:172313)
    at l._setDataItem (index.js:1:114275)
    at l._setDataItem (index.js:1:125296)
    at Li.showTooltip (index.js:1:185196)
    at index.js:1:175497
    at Object.dispatch (index.js:1:263076)
    at index.js:1:262634
    at Module.o (index.js:1:215238)
    at g._eachListener (index.js:1:262359)
```
I have looked for other "EventDispatcher is disposed" issues, but I haven't found a solution that fits my case. :(

Could you please help me? If you know any similar cases or solutions, please let me know.
Thank you.

**Environment (if applicable)**

amCharts version ^5.0.10

**Comment by martynasma** [comment]
Have you tried modifying existing background, rather than overwriting it?

```JavaScript
tooltip.get("background").setAll({
    cornerRadiusTL: 50,
    cornerRadiusTR: 50,
    cornerRadiusBL: 50,
    cornerRadiusBR: 50,
    fill: am5.color(0xffd400),
});
```

**Comment by suu3** [comment]
I tried the provided code, but the same error still occurs. I believe the error occurs when using the following code:

```
const tooltip = am5.Tooltip.new(root, {
});

...

worldSeries.mapPolygons.template.setAll({
    tooltip,
    tooltipText: "{name}",
});

countrySeries.mapPolygons.template.setAll({
    tooltip,
    tooltipText: "{name}",
    ...
});
```

However, I'm unsure how to customize the tooltip without using the above code.

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by suu3** [comment]
Of course, thank you for your assistance.
Here is a CodePen where I have briefly reproduced the error situation in my project code: https://codepen.io/suu3/pen/GRYePWN?editors=1111

Please try repeating the steps of clicking on a country and then clicking 'Back to world map' several times.
There is an issue where tooltips disappear or the chart freezes.
If you open the browser console, you will see an error stating "EventDispatcher is disposed."

**Comment by martynasma** [comment]
OK, so the issue is that you are adding custom tooltip to polygon template.

You need to add it to series:

```JavaScript
var countrySeries = chart.series.push(
  am5map.MapPolygonSeries.new(root, {
    tooltip, //added code
    visible: false
  })
);
```

**Comment by suu3** [comment]
Oh, I made the changes as you suggested, and it works. Thank you. I will close this issue.
