### ISSUE TITLE
Custom Legends: How to "remove" a slice from a pie chart?

### ISSUE THREAD

**Issue by buggedcom** [amcharts/amcharts5#93]
I'm creating a purely HTML legend for various reasons, however I can't seem to find the correct documentation for toggling a slice "on" and "off" again (ie removing it from the pie so that the pie recalculates). The best I can manage is to toggle the visibility of the slice.

What would be the best way to accomplish what I want to do.

This is a demo codepen https://codepen.io/buggedcom/pen/NWvVwEg

**Comment by martynasma** [comment]
Nope, you would need to toggle slice's data item:

```JavaScript
slice.dataItem.hide();
```

Please note that this way it will not only correctly hide slice, but also hide/show related elements like ticks and labels, so you don't have to do anything about them.

**Comment by buggedcom** [comment]
Wonderfull. Thank you.

**Comment by buggedcom** [comment]
One note though, it does not hide an active hover state tooltip. So I still need to call `unhover` on the element.

```
                    if (slice.get('visible')) {
                        slice.dataItem.hide();
                        slice.unhover();
                    } else {
                        slice.dataItem.show();
                        slice.hover();
                    }
```

**Comment by martynasma** [comment]
Yup, good catch.
