### ISSUE TITLE
Bullet returns width of the column

### ISSUE THREAD

**Issue by roshaxo** [amcharts/amcharts5#931]
Hello!
I want to get bullet width, but if it is outside the column and text is longer than column **width()** method returns width of the column (in my case Mango column).
If the bullet is inside the column - everything is ok.
Here is an example:
https://codepen.io/flexinclique/pen/KKGLNzG

Could you tell me what I'm doing wrong?

Thank you in advance!

**Comment by martynasma** [comment]
Bullets get their `maxWidth` set to the width of the related column automatically. `width()` method takes `maxWidth` into account, hence width of "Mango" bullet coming in as the same as the related column.

Try resetting `maxWidth`:

```JavaScript
series.bullets.push((root) =>
  am5.Bullet.new(root, {
    locationY: 0.5,
    locationX: 0,
    sprite: am5.Label.new(root, {
      text: `{value}`,
      centerY: am5.p50,
      paddingLeft: 0,
      paddingRight: 0,
      populateText: true,
      maxWidth: 1000
    })
  })
);
```

**Comment by roshaxo** [comment]
@martynasma Works! Thank you!
