### ISSUE TITLE
How to control data series visibility from a parent react functional component?

### ISSUE THREAD

**Issue by binaryartifex** [amcharts/amcharts5#932]
is there any examples of how to control a data series visibility from outside the chart? the example of toggling a series on/off is insufficient in the context of a react app using functional components. the closest ive come to a working implementation is

```typescript
  useLayoutEffect(() => {
    const seriesList = chartRef.current?.series;
    if (seriesList) {
      seriesList.each((xySeries) => {
        const key = xySeries.get("valueYField") || "";
        const isEnabled = activeSeriesData.includes(key);
        const isHidden = xySeries.isHidden() || xySeries.isHiding();

        if (isHidden && isEnabled) {
          xySeries.show();
        }

        if (!isHidden && !isEnabled) {
          xySeries.hide();
        }
      });
    }
  }, [activeSeriesData]);
```

where activeSeriesData is the list of keys that make up the valueYFields. whenever this value changes, id like the chart to animate between those states. it has an exit animation, but theres no enter animation, the chart just flickers and the old dataset is back, and the flickering between states is annoying and i can't seem to fix it when there is any control at all thats passed to a parent component.

**Comment by martynasma** [comment]
You can pass in a millisecond value to `show()` and `hide()` methods to trigger hide and show animation.
