### ISSUE TITLE
Add gap between stacked bars

### ISSUE THREAD

**Issue by roshaxo** [amcharts/amcharts5#937]
Hello!
Is it possible to add gap between stacked bars (e.g. 2px)?
<img width="1005" alt="Screenshot 2023-05-31 at 17 43 08" src="https://github.com/amcharts/amcharts5/assets/108542985/eccc1503-5fba-4212-840c-a9e102313feb">

Thank you in advance!

**Comment by xorspark** [comment]
There isn't a direct setting for that, but you can fake the appearance of a gap by setting the column `stroke` to match your chart's background color and set the `strokeWidth` to 2 to make it 2px thick:

```
  series.columns.template.setAll({
    // ...
    stroke: am5.color(0xffffff),
    strokeWidth: 2,
    // ...
  });
```

**Comment by roshaxo** [comment]
@xorspark Thank you!
