### ISSUE TITLE
Chart redraw issue while dynamic changes

### ISSUE THREAD

**Issue by perumalsamyrajaveni1518** [amcharts/amcharts5#938]
**Question**

Dynamically update **baseInterval**, **Data**, and **DateAxis min, max scale** the chart properly redraw with the same **timeUnit**. But I update it at a different **timeUnit** the chart did not properly redraw.

```
updateChart() {
    // Update MIN and MAX
    xAxis.setAll({
        min: this.xAxisMinMax.min,
        max: this.xAxisMinMax.max
    });
    // Update BaseInterval
    xAxis.set('baseInterval', { count:this.count, timeUnit: this.timeunit });

    // Update Data

    xAxis.data.setAll(this.data);
    chart.series.each((val) => {
        val.data.setAll(this.data);
    });
}
```
1. Hourly data `timeUnit:"minute"`
![image](https://github.com/amcharts/amcharts5/assets/127523713/73c93716-dd42-48fa-930b-fbe80bd71995)
2. Weekly Data `timeUnit:"hour"`
![image](https://github.com/amcharts/amcharts5/assets/127523713/881c77fb-4c02-4b9b-a731-edfdcfb33fb5)
3. Back to Hourly data the chart didn't properly redraw.
![image](https://github.com/amcharts/amcharts5/assets/127523713/dc794657-260d-4333-8e12-71c1e3fdb297)

How to resolve the issue?

**Environment (if applicable)**

- amCharts 5
- Angular 14

**Additional context**

**Comment by perumalsamyrajaveni1518** [comment]
@zeroin Every time I set the new data array

**Comment by zeroin** [comment]
Sorry. Could you create a codepen with your setup and data where this is reproduced?
