### ISSUE TITLE
Set different look for Line (HierarchyLink) in ForceDirected chart

### ISSUE THREAD

**Issue by elinagilevich** [amcharts/amcharts5#939]
Is there any possibility to customise the look of HierarchyLink in terms of shape?
For example I'm trying to achieve arrow-line look.
I know there're many properties in HierarchyLink Settings for stylising (like strokeWidth, stroke, strokeDasharray and etc.), but I can't find something suitable for my case.
I'll really appreciate some help here.

Thanks a lot in advance!

**Comment by martynasma** [comment]
I'm afraid there's no way to add arrows to a hierarchy link :(

**Comment by martynasma** [comment]
I don't think so :(

**Comment by elinagilevich** [comment]
Similar feature request https://github.com/amcharts/amcharts5/issues/83 already exists.
