### ISSUE TITLE
how do i show value instead of percentage 

### ISSUE THREAD

**Issue by noor-khan-myglu** [amcharts/amcharts5#94]
how do i show value instead of percentage

**Comment by martynasma** [comment]
Your question is too vague. Please provide more details what you have right now, and what you are trying to achieve.

**Comment by noor-khan-myglu** [comment]
i am trying to show value instead of number in pie chart labels and legends.

**Comment by martynasma** [comment]
Please refer to these tutorials:
https://www.amcharts.com/docs/v5/charts/percent-charts/pie-chart/pie-series/#Label_content
https://www.amcharts.com/docs/v5/charts/percent-charts/legend-percent-series/#Legend_label_content

**Comment by noor-khan-myglu** [comment]
Thank you so much for resolving, it's difficult to find in am docs

**Comment by Martin12350** [comment]
Also thanks for help. Was searching so hard in docs and still struggle to find correct syntax to customize tooltip with percentage.
The magic word is "**valuePercentTotal**", not only percent/valuePercent.
Here is snap, that I needed:
`series.labels.template.set("text", "{category}: [bold]{valuePercentTotal.formatNumber('0.00')}%[/] ({value})");`
