### ISSUE TITLE
Fixed width between legend items

### ISSUE THREAD

**Issue by roshaxo** [amcharts/amcharts5#942]
Hello!
Is it possible to set fixed width between legend items?
I tried to use `legend.itemContainers.template.setAll`, but it didn't help.

`
  legend.itemContainers.template.setAll({
    marginRight: 10,
    paddingRight: 0,
    paddingLeft: 0,
    marginLeft: 0,
  });
`

![Screenshot 2023-06-01 at 17 39 15](https://github.com/amcharts/amcharts5/assets/108542985/cc49c1a2-89af-4fc1-a31a-8d66ffd8b5c5)

Thank you in advance!

**Comment by zeroin** [comment]
Most likely you should hide the valueLabel of a legend. Try setting `legend.valueLabels.template.set("forceHidden", true)` as it takes some space which you want to remove.

**Comment by roshaxo** [comment]
@zeroin Didn't know about that. Thank you, it helped!
