### ISSUE TITLE
Compiling standalone JS scripts locally

### ISSUE THREAD

**Issue by VT-hash** [amcharts/amcharts5#943]
I'm building amcharts5 with npm locally on Ubuntu22.04 at the moment and I'm wondering how I should compile it such that it generates the standalone JS scripts similar to what is under `amcharts4/dist/script` from amcharts4 (core.js, charts.js).

**Comment by martynasma** [comment]
Check this:
https://github.com/amcharts/amcharts5#building-script-version

**Comment by VT-hash** [comment]
Thanks for the help. I'm not sure how I missed that from the front page. 

***

With the compiled standalone JS files, I can't seem to use the `am5*` namespace to initialize the root. It claims that `am5` is unresolved for the following line. 

```javascript
var root = am5.Root.new("chartdiv");
```

The JS scripts were loaded as:
```javascript
<script type="text/javascript" src="~/path/to/flow.js"></script>
<script type="text/javascript" src="~/path/to/hierarchy.js"></script>
<script type="text/javascript" src="~/path/to/index.js"></script>
<script type="text/javascript" src="~/path/to/map.js"></script>
<script type="text/javascript" src="~/path/to/percent.js"></script>
<script type="text/javascript" src="~/path/to/radar.js"></script>
<script type="text/javascript" src="~/path/to/stock.js"></script>
<script type="text/javascript" src="~/path/to/venn.js"></script>
<script type="text/javascript" src="~/path/to/wc.js"></script>
<script type="text/javascript" src="~/path/to/xy.js"></script>
```

Is `am5` not offered as a global object similar to `am4core`?

**Comment by martynasma** [comment]
> Is am5 not offered as a global object similar to am4core?

It is, in "script" version, which you can build with `yarn build:script`

**Comment by VT-hash** [comment]
Right, that's what I did (`yarn build:script`).

Correct me if I'm wrong:

The build generates the directory `dist/script` containing the standalone JS scripts. However, the scripts don't seem to supply `window.am5` like how it is with amChart4 where it had `window.am4core` in `core.js`. 

When I move everything under `dist/script` to a directory in my project, `am5` can't seem to be resolved as a global object. Did I do something wrong or is there a workaround for this?

**Comment by martynasma** [comment]
It generates .js files to be included via `<script>` tag. Once you do, you'll have a global `am5` variable.

**Comment by VT-hash** [comment]
Turned out to be a bug with Rider's syntax analysis. The IDE couldn't resolve `am5` as a variable but it actually works fine.
