### ISSUE TITLE
Issue of Pie of pie chart slice display when selected

### ISSUE THREAD

**Issue by cooldammy** [amcharts/amcharts5#944]
**Bug description**

Adopted from the official demo code of pie of pie chart. If the size of subData from the very first set of series data is less than others, then the pie misses some share of subData. For example in the codpen below, select the "Ireland" slice after rendering, you will see B/C share are 0% respsctively. Moreover, after you select the slice with the maximum size of subData, the share display becomes normal as expected. 

Check the code mentioned above in https://codepen.io/tsungming-liao/pen/MWPNJNy

 - amCharts version: 5
 - Browser and its version: Microsoft Edge Version 113.0.1774.57 (Official build) (64-bit)

**Comment by zeroin** [comment]
Switching setIndex with show() should fix the problem:
https://codepen.io/team/amcharts/pen/jOegvLW/3aec39970ad2d6d414296ce9a53dc56e

**Comment by cooldammy** [comment]
Hi @zeroin , thank you for your tips. It now works normal after adjusting the order of setIndex and show(). The show() should precede the setIndex method.
