### ISSUE TITLE
Fit series bullet inside the chart area

### ISSUE THREAD

**Issue by roshaxo** [amcharts/amcharts5#946]
Hello!
Is it possible to fit series bullet inside the chart area? For example: bullet for 2023 column is being truncated, but I want to show full text (https://codepen.io/flexinclique/pen/vYVoJMo).
I know about the `maskBullets` property, but this is not what I want to achieve.

Thank you in advance!

**Comment by martynasma** [comment]
Maybe use `extraMax` on an X-axis?

https://www.amcharts.com/docs/v5/charts/xy-chart/axes/value-axis/#Relative_scope_extension
