### ISSUE TITLE
dynamical update for grouped items looks strange

### ISSUE THREAD

**Issue by markGotech** [amcharts/amcharts5#948]
I have a chart with data by minute. I grouped it by hours. And every minute push new data from server, without rerender all charts, use series for it. But chart draw last item to the middle of grid. And if it's end of hour it's look like this:

Before: 

![Screenshot 2023-06-05 at 14 52 05](https://github.com/amcharts/amcharts5/assets/128690082/f82716e3-dace-46ab-bc71-12cabeb019d3)

After: 
![Screenshot 2023-06-05 at 14 52 56](https://github.com/amcharts/amcharts5/assets/128690082/0f91d5a6-6f48-4d98-a91b-b78cc141dd51)

Environment 
 - amCharts version : "@amcharts/amcharts5": "^5.3.12",
 - Browser: Chrome last version
  - Related frameworks:
    "react": "^18.2.0",
    "typescript": "^4.9.5"

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by markGotech** [comment]
> Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

I found the issue. Issue was i set 0 in minDistance in xAxis Render. I changed it to dynamical vars (calculate by browser size), and now it works correct
