### ISSUE TITLE
Drawing controls for other chart type than Stock Chart

### ISSUE THREAD

**Issue by SirBouBou** [amcharts/amcharts5#949]
Hello,
I've seen that Amcharts 5 let you have drawing tools on Stock Chart ([Link to the doc](https://www.amcharts.com/docs/v5/charts/stock/toolbar/drawing-control/#Prerequisites)). While that's the type of chart where this feature is the most useful, it would be pretty nice to be able to enable it on other chart types too.

So, i would like to know, is there any way to activate this feature on other types of chart or could this be something that could be added in a future update ?

**Comment by martynasma** [comment]
For regular charts we do have this plugin:
https://www.amcharts.com/docs/v5/concepts/exporting/annotator/

The full-fledge annotator is only available for StockChart, I'm afraid.

**Comment by SirBouBou** [comment]
Okay, that seems pretty useful, thank you. However, there seems to be a bug on it, directly reproductible in the page you sent me (https://www.amcharts.com/docs/v5/concepts/exporting/annotator/).
The step to reproduce on the first exemple (line chart): 

- Open the annotation system, draw anything then presse the cross to discard the changes
- Open it back, draw anything then delete it with the bin and press the chack button to validate
- The first drawing that should have been discarded reappear.

I don't know if I should open a new issue to report it or if this one can be used.

**Comment by SirBouBou** [comment]
Yes, no problem, thanks for the answer
