### ISSUE TITLE
Pie SliceGrouper plugin

### ISSUE THREAD

**Issue by buggedcom** [amcharts/amcharts5#95]
Version 4 has the `SliceGrouper` plugin available. Will it also be made available for version 5?

**Comment by martynasma** [comment]
The decision hasn't been made, yet. But we see some demand for it, so chances are good we'll implement it.

Marking this as an enhancement, and will keep you posted here.

**Comment by martynasma** [comment]
Implemented in [5.0.19](https://github.com/amcharts/amcharts5/releases/tag/5.0.19).

## [5.0.19] - 2021-12-27

### Added
- `groupDataDisabled` setting added to XYSeries. If set to `false` will exclude series from data grouping mechanism, even if it is enabled on related `DateSeries`.
- New plugin `SliceGrouper`. Can be used to automatically group small slices on percent charts like Pie, Funnel, etc. [More info](https://www.amcharts.com/docs/v5/charts/percent-charts/grouping-slices/).

### Fixed
- If data was added to percent series after initial data was already processed, the bew slices would get colors from the start of the color set.
- Multiple square bracket and apostrophe escaping was not working properly.
- A JS error could occur when changing `XYSeries` data with less data items then there were before.
- `PieSeries` were not arranging its labels properly in some cases.
- `XYCursor` taps were not working properly after chart zoom on touch devices.

[Full change log](https://github.com/amcharts/amcharts5/blob/master/packages/shared/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
