### ISSUE TITLE
Browser freezes when clicking and dragging to zoom with vertically stacked axes

### ISSUE THREAD

**Issue by micawho** [amcharts/amcharts5#950]
I set up a charting project that uses vertically stacked y-axes and a cursor with 'zoomXY' behavior. When I click and drag to zoom, occasionally the entire tab freezes and becomes unresponsive. Refreshing doesn't fix the tab, it has to be completely closed. Additionally there aren't any helpful error messages in the console.

I reproduced this behavior in a simplified example here: https://codepen.io/micagee/pen/JjmgvbM

It usually occurs after 1-10 click and drag interactions in quick succession, but also occasionally happens after clicking the zoom out minus button. I have seen this behavior in both chrome and firefox.

I haven't had any issues with zoomXY and multiple horizontally stacked axes so is there some sort of incompatibility with the vertically stacked setting?

**Comment by martynasma** [comment]
I've been clicking around the CodePen like mad but was not able to reproduce the freeze. Can you provide more details about your setup, like OS, versions, etc?

That being said, using `zoomXY` behavior with stacked axes must be super confusing for the user. Seems like bad UX. You interact with one "panel", and other "panels" with totally different scales zoom, too.

I strongly suggest reconsidering this type of setup.

**Comment by micawho** [comment]
I ended up changing the cursor behavior to 'zoomX' instead of 'zoomXY' and haven't had any issues with crashing or freezing. I think it suits the vertical stacked axes better as well.
