### ISSUE TITLE
Can I use amcharts v5 in a React Native app?

### ISSUE THREAD

**Issue by dsinger376** [amcharts/amcharts5#951]
**Question**

Hello, as an amPlus license holder, I have built out many custom charts using amcharts (v5.3.12) for a React (v18.2.0) web app over the past 2 years,  and now I want to use them in a React Native (v0.71.8) app built with Expo.  

While migrating one of the charts (RadarChart) over to the react native app, I noticed that as soon as I instantiate the root `i.e. let root = am5.root.new(rootRef.current)`, I get an error (screenshots).
Is it true that Amcharts v5 requires the DOM to render charts, and is this the cause for that error?

Other than this [package](https://github.com/vikisingh23/react-native-amcharts) (which supports amcharts v4), I'm unaware of any third-party dependencies that would allow me to use the charts I built in a react native app.

Do you have any recommendations as far as modifications to the amcharts package, third-party dependencies to 'wrap' my existing charts, or other libraries entirely that can support what I'm trying to do?  Any help would be greatly appreciated.

error 1/2            |  error 2/2
:-------------------------:|:-------------------------:
<img width="460" alt="error 1:2" src="https://github.com/amcharts/amcharts5/assets/88509443/25ed0de8-5f70-4dba-a5e9-9a706bfca09f">  |  <img width="453" alt="error 2:2" src="https://github.com/amcharts/amcharts5/assets/88509443/3ec38205-df6b-4258-abdb-8d6eb8212b6c">

**Comment by martynasma** [comment]
> Is it true that Amcharts v5 requires the DOM to render charts, and is this the cause for that error?

That is correct. amCharts 5 does rely on DOM to be there to function.

> I'm unaware of any third-party dependencies that would allow me to use the charts I built in a react native app.

I'm not aware of any wrappers for amCharts 5 for React native, either, I'm afraid.

> Do you have any recommendations as far as modifications to the amcharts package, third-party dependencies to 'wrap' my existing charts, or other libraries entirely that can support what I'm trying to do? Any help would be greatly appreciated.

Although we haven't had any experience with it ourselves, I've head about something like "Virtual DOM" for React, which has some implementations for React Native. Perhaps you can look into it.

Again, no experience or even reports that it works, just something to look into.

I know it's not much to go on, but that's what I have :(

**Comment by dsinger376** [comment]
@martynasma I appreciate the feedback, thank you 🙏

**Comment by ibelgin** [comment]
Is there any update ?
