### ISSUE TITLE
Custom Candlestick Colors in OHLC charts - am5 Edition

### ISSUE THREAD

**Issue by enjoywithouthey** [amcharts/amcharts5#952]
Regarding OHLC Charts, I am trying to color candles based on a unique type. In the data series, I have assigned a random type to each candlestick. I would like to map this type to a color for each candle.

The issue was solved in am4charts issue #2017, posted here:
[Candlesticks with custom colors #2017](https://github.com/amcharts/amcharts4/issues/2017)

However, the methods have changed in am5 and the above solution does not work. 

Attached is a link to my repo of the working code, with various attempts made to customize the candlestick colors.
[Github Repo with issue](https://github.com/enjoywithouthey/amcharts5-OHLC/tree/main)

Thank you so much.

**Comment by xorspark** [comment]
Coloring based on data is different in v5 - you need to use a `templateField`, which is an object that contains the appropriate settings you wish to modify, not an individual field like v4 handles it: https://www.amcharts.com/docs/v5/concepts/settings/template-fields/

```
// in generate data:
    chartData.push({
      date: newDate.getTime(),
      value: value,
      open: open,
      low: low,
      high: high,
      type: type,
      columnSettings: { // move typeColor into a templateField object called 'columnSettings' with the fill and stroke properties adjusted
        stroke: am5.color(typeColor),  // note that you need to use am5.color if you're using numeric values for colors
        fill: am5.color(typeColor),
      }
    });

// ... after series creation ...
series.columns.template.set('templateField', 'columnSettings') // set the templateField to match the property containing your settings in your data
```

Demo: https://codepen.io/team/amcharts/pen/WNYbNRX/4b3fb63dd7cd76835b76741b0a3dc04f?editors=0010

**Comment by enjoywithouthey** [comment]
Excellent. Thank you so much.
