### ISSUE TITLE
Positioning of tooltips created for HierarchyLink in Force-directed

### ISSUE THREAD

**Issue by elinagilevich** [amcharts/amcharts5#953]
I'm trying to add tooltip for each HierarchyLink in Force-directed chart. I also want to make them always visible and anchored to position of HierarchyLink.

I've tried to achieve this with the following code:
`series.links.template.setup = function(target) {
        target.setAll({
          showTooltipOn: "always",
          tooltipX: am5.percent(50),
          tooltipY: am5.percent(50),
          tooltip: am5.Tooltip.new(root, {
            pointerOrientation: "vertical"
          })
        });
      }`

And I see that tooltips are all visible and created properly, but their position is sticked to chart container and not to parent link.

Is there any way to make tooltips relatively positioned to its link?

Thanks a lot in advance for help!

**Comment by elinagilevich** [comment]
Hello, maybe is there any reponse?

I'll really appreciate for some help.

**Comment by martynasma** [comment]
I'm afraid there's no built-in way to attach a tooltip to a link line itself.
