### ISSUE TITLE
does amCharts 5: Maps have USA regional  states map with its county? (state like Oklahoma)

### ISSUE THREAD

**Issue by padfoot044** [amcharts/amcharts5#955]
**Question**
does amCharts 5: Maps have USA regional  states map with its county? (state like Oklahoma)
or there are any way to implement Oklahoma map with county chart please respond on it

**Environment (if applicable)**
Angular 12
amCharts 5

**Additional context**

**Comment by martynasma** [comment]
Yes:
https://www.amcharts.com/docs/v5/tutorials/using-regional-maps/

**Comment by anurag-044** [comment]
@martynasma I tried this but I only got USA simple map, not get a Oklahoma map with county, I only want Oklahoma map with county

**Comment by martynasma** [comment]
That tutorial has a live example of Florida county map. Just replace it with the map of Oklahoma.

**Comment by padfoot044** [comment]
where can I get all county Ids for Heat Map?

**Comment by martynasma** [comment]
In any FIPS database. E.g.:
https://transition.fcc.gov/oet/info/maps/census/fips/fips.txt

**Comment by padfoot044** [comment]
Thank you so much @martynasma
