### ISSUE TITLE
Jerking charts after rendering

### ISSUE THREAD

**Issue by roman-gorkunenko** [amcharts/amcharts5#956]
**Bug description**

After loading the page, there is often a jelly twitching of the charts. Presumably this is due to the application of the font-family.

Video examle:
https://www.dropbox.com/s/rlur48ivq0vszfh/chrome_7EScVtdMYW.mp4?dl=0
https://www.dropbox.com/s/4npootw1tovcph4/chrome_pDHNwLnqs4.mp4?dl=0

This can be reproduced on codepen by frequently reloading the page.

Code example:
CodePen (https://codepen.io/Roman-Gorkunenko-the-flexboxer/full/jOQEVwr)

Development environment:
 - amCharts version 5
 - Chrom Version 114.0.5735.110 (Official Build) (64-bit)
 - windows 10

**Comment by martynasma** [comment]
I can't seem to be able to reproduce it, but you can try disabling "ghost label" if it helps:

```JavaScript
yAxis.ghostLabel.set("forceHidden", true);
```

**Comment by roman-gorkunenko** [comment]
Thanks, at the moment after disabling "ghost label", I did not detect a twitch
