### ISSUE TITLE
Occasional surprising conflicts/dependencies of properties

### ISSUE THREAD

**Issue by wernerdaehn** [amcharts/amcharts5#957]
Put yourself into the shoes of an average user.

I want to create a PieChart with Circular Labels like in your demo.
<img width="208" alt="image" src="https://github.com/amcharts/amcharts5/assets/13607767/198bd6be-aa30-4374-a196-15c5641adf8a">
So I create a Piechart, set the labels to `textType: circular` as told here
https://www.amcharts.com/docs/v5/charts/percent-charts/pie-chart/pie-series/#circular-labels
and the result is this.
<img width="241" alt="image" src="https://github.com/amcharts/amcharts5/assets/13607767/1b1d3992-e966-4973-a03e-a6debd735a4d">
You have no chance to figure out the mistake. Ever. The docs just state to use a setAll on the label with some settings.

I know what broke it. The `alignLabels: false` must be set also. So although you said `circular`, said `inside` and specified a `radius`, the default value of `alignLabels` take precedence. Which is sort of okay if something useful would be the result, e.g. the circular label gets ignored and you get feedback. Instead the chart is broken and no reason provided why.

I would argue this is not even a documentation problem - it is to some extent - but there should rather be clear rules for these cases in general.
For example:

- RadialLabel: If labels are circular then the alignLabels is false always.

To reproduce:
Take your example and remove the `alignLabels`. https://codepen.io/team/amcharts/pen/dyWZGgG
Labels will not be shown.
Then assume you have no idea about the inner workings, read the documentation and check how long it takes you to figure out the root cause.

I have seen a couple of places where things simply don't work unless you figured out the working combination of settings.

All of that is not user friendly. It could take you days and weeks to figure out why something is not rendered as expected. AmCharts is too user friendly and powerful in every other regard, hence I am hoping you support us here as well.

**Comment by martynasma** [comment]
> Take your example and remove the alignLabels. https://codepen.io/team/amcharts/pen/dyWZGgG
> Labels will not be shown.

Labels **are** shown, they're just colored white (as per code), so are not visible on a white background.

Your point of mentioning about `alignLabels` taking precedence is spot on, though. We'll make sure we add that the docs. 

Thanks!
