### ISSUE TITLE
second click event doesn't raised

### ISSUE THREAD

**Issue by AAJeck** [amcharts/amcharts5#958]
Hi Guys 

In order to listen to the user drawing, I am listening to the click event 
The first click was handled, but the second one wasn't
The charting version we use is amcharts5 

`this.stockChart.events.on("click", (value: any) => {
            debugger;
});`

**Comment by martynasma** [comment]
I suggest adding click events to specific panel, not the stock chart itself, e.g.:

```
mainPanel.events.on("click", function(ev) {
  console.log(ev);
});
```

**Comment by AAJeck** [comment]
Thank you, but it doesn't work like it does from the chart.
any suggestions?

**Comment by AAJeck** [comment]
The first click works properly, but the second one doesn't

**Comment by martynasma** [comment]
Can you post your chart on CodePen? All clicks, including subsequent ones, work for me in my tests.

**Comment by AAJeck** [comment]
[https://codepen.io/JekaK/pen/VwVvPmg](url)

**Comment by martynasma** [comment]
Thanks.

I get click alerts every time I click on chart. What am I missing?

**Comment by AAJeck** [comment]
Select the "Drawing" option and proceed to create a line by using the drawing tools

**Comment by AAJeck** [comment]
any ideas? recommendations?

**Comment by martynasma** [comment]
Drawing mode creates own events. Is there a reason why you need to register clicks in drawing mode?

**Comment by AAJeck** [comment]
To fulfill requirement of exporting, saving, and analyzing user drawings, it is crucial to monitor clicks and implement my business logic.

**Comment by martynasma** [comment]
How about using `drawingsupdated` event instead?

https://www.amcharts.com/docs/v5/charts/stock/serializing-indicators-annotations/#Events
