### ISSUE TITLE
Pie chart: Adapters do not seem to fire even when chart is updated via legend.

### ISSUE THREAD

**Issue by buggedcom** [amcharts/amcharts5#96]
https://codepen.io/buggedcom/pen/ZEJdLyJ

In this example, all ticks and labels should be hidden by default as the adapters say that any arc under 30deg should be `forceHidden`. However if you then start clicking on the legend items (going from right to left), which gradually increases the slies of the other slices, the adapters are not recalled even though the slices are recalculated.

The expectation is that the slices, once they become greater than 30deg should show ticks and labels.

**Comment by martynasma** [comment]
Well, the reason why they do not kick in is that other slices are hidden, so ticks/labels of the remaining slices do not get invalidated. It would be wrong for adapters for random elements kicking in if something else was updated.

I'd not rely on adapters in this case, but rather use events. Something like this:

```JavaScript
series.slices.template.on("startAngle", () => {
  series.ticks.each((tick) => {
    const slice = tick.dataItem.get('slice');
    const arc = slice.get('arc');
    tick.set("visible", arc >= 30)
  })
});
```

**Comment by buggedcom** [comment]
You solution suggestion works well. Thank you.
