### ISSUE TITLE
How to customize legend marker color

### ISSUE THREAD

**Issue by underwater2** [amcharts/amcharts5#961]
Hi I have some problem.

**I want change legend marker color.**
I already customized series color, but legend marker still have the color before the change.

![스크린샷 2023-06-15 오전 11 43 00](https://github.com/amcharts/amcharts5/assets/81406442/3161b9f3-a45d-4192-85fa-b663609614ce)

I tried to add adapter, but it didn't work.
Below is the code I tried.
```
legend.markers.template.adapters.add("fill", function(fill, target) {
      return am5.color("#000000");
});
```

**Comment by martynasma** [comment]
How did you customize the color of series? If you could post your whole chart code, that would help.

**Comment by underwater2** [comment]
https://codepen.io/Park-the-lessful/pen/yLQewMJ
This is the whole chart code.
I used this to change the color of series.
```
series.slices.template.adapters.add("fill", function(fill, target) {
  .....
});
```

**Comment by underwater2** [comment]
It works.. Thank you!

I have one more question.
Is there any other way to change series or legend color?
In `// determine the color here` section, i hardcoded using uid....
And i guess that might not be a good way, I want to fix i using a better way.

**Comment by zeroin** [comment]
The most correct way to do this would be by using templateField approach - you add settings object to the data and set templateField for the slices:

`series.slices.template.set("templateField", "settings");`

`{ name: "A2", value: 10, settings:{fill:am5.color(0x00ff00)} }`


https://www.amcharts.com/docs/v5/concepts/settings/template-fields/

**Comment by underwater2** [comment]
@zeroin 
Thanks. It works successfully. The code looks better.
But the color of the legend's marker does not follow the change.
Are there other similar methods for legend?

**Comment by underwater2** [comment]
It has been very helpful. thank you @zeroin
