### ISSUE TITLE
Update chart.series config

### ISSUE THREAD

**Issue by roman-gorkunenko** [amcharts/amcharts5#962]
Hello. Can you tell me please, how to update chart.series config? The documentation says https://www.amcharts.com/docs/v5/charts/xy-chart/series/#Changing_data_fields some fields cannot be updated via set. For example, the Stacked field, how can its value be updated if the chart has already been built?

**Comment by zeroin** [comment]
To toggle "stacked" setting, you should set new stacked value and then set data for the series again, as data is processed based on this setting: https://codepen.io/team/amcharts/pen/JjeXPod/f650698f8c56b13415b74f92ab4d658b?editors=0010

**Comment by roman-gorkunenko** [comment]
Thanks.
