### ISSUE TITLE
Invalid license info in npmjs / github interpreted by open source projects scanner

### ISSUE THREAD

**Issue by ccjasonlin** [amcharts/amcharts5#966]
This is regarding how well known open source projects scanner such as Synopsys black duck interpret amcharts5 libraries license information.

Typically, the open source library `license` will have a valid value such as `MIT`, `BSD-3-Caluse`, or `Apache-2.0`.

But in npmjs
https://www.npmjs.com/package/@amcharts/amcharts5-geodata
https://www.npmjs.com/package/@amcharts/amcharts5

License section is `SEE LICENSE IN LICENSE`, and that shows up as high license risk. (Unknown License).
It would be nice that you can fix this issue.

Thanks

**Comment by martynasma** [comment]
Well, amCharts is not technically OS and is not compatible with any of those OS licenses. So, I'm not entirely sure how it can be "corrected". Any suggestions?
