### ISSUE TITLE
Can I apply 'border-radius' and 'object-fit' properties to the Picture Sprite?

### ISSUE THREAD

**Issue by suu3** [amcharts/amcharts5#969]
**Question**

Hello, this is my demo site (https://codepen.io/suu3/pen/oNQLGZX?editors=1010).

I would like to add a background image to the rectangles of the TreeMap chart.
I tried using bullets by referring to this example (https://www.amcharts.com/demos/drill-down-treemap/)
but I'm not sure how to apply the cornerRadius property, which is applied to the rectangles, to the Picture, too. 

Additionally, I would like to apply object-fit: cover to the image, but I'm unsure how to do it. Can you help me?

**Comment by martynasma** [comment]
I'm afraid there's no way to apply border radius to images.

The image fitting can be achieved via events.

Please refer to this demo for code:
https://www.amcharts.com/docs/v5/tutorials/treemap-with-node-images-and-labels/

**Comment by suu3** [comment]
Ok, thank you. I'ill close this issue.

**Comment by thrashzone13** [comment]
Hi @suu3 !
Sorry for reopening this issue but I'm really stuck with the same thing. Could you finally figure out how to make the pictures rounded?

**Comment by suu3** [comment]
@thrashzone13 I regret to say that I couldn't come up with an alternative method to round the corners of the images. Given that the website I'm currently developing is designed to handle a limited amount of incoming data, specifically five inputs or fewer, I chose to address this by creating a component directly instead of TreeMap chart. I apologize for not being able to offer more assistance.
