### ISSUE TITLE
How to add hover and on click events to category legend label?

### ISSUE THREAD

**Issue by maayanLayfer** [amcharts/amcharts5#970]
**Question**

Trying to underline the label I'm hovering gives the result in the video :/
I'm trying to only apply the change on the hovered label, also why the underline is not truncated?

**Environment (if applicable)**

I'm working with AMCharts5, React and TS

**Additional context**

Adding the code snippet and a video:

```
    legend.events.on("pointerover", ({ target }) => {
      array.each(target.labels.template.entities, (label) => {
        const dataContext: any = label.dataItem?.dataContext;
        console.log(label)
        label.children.values[0].set(
              "text",
              "[underline]" + dataContext?.category + "[/b]"
          );
      });
    });

    legend.events.on("pointerout", ({ target }) => {
      array.each(target.labels.template.entities, (label) => {
        const dataContext: any = label.dataItem?.dataContext;
        console.log(label.children.values[0]);
        legend.events.on("pointerout", ({ target }) => {
          label.children.values[0].set(
              "text",
              dataContext?.category
          );
        })
      });
    });
```

https://github.com/amcharts/amcharts5/assets/108460092/62827f45-8676-4f0a-9c91-a1a8b492b861

**Comment by zeroin** [comment]
You should add events on legend.itemContainers.template instead of all the legend:

```
legend.itemContainers.template.events.on("pointerover", (e)=>{
  e.target.dataItem.get("label").set("textDecoration", "underline")
})
```

As for the underline, it looks like a bug on our side, we need to investigate it.

**Comment by martynasma** [comment]
@maayanLayfer 

> I'm trying to only apply the change on the hovered label, also why the underline is not truncated?

That is a bug. Though, can you post it as a separate issue though so that we can process it and notify you properly?
