### ISSUE TITLE
LinePattern on Pie chart won't show on the slice

### ISSUE THREAD

**Issue by maayanLayfer** [amcharts/amcharts5#971]
**Question**

I can see the pattern on the legend rectangle but not on the slice.

**Environment (if applicable)**

I'm working with AMCharts5, React and TS

**Additional context**

Adding the code snippet, a pic and codePan:

```
    series.slices.template.adapters.add("fillPattern", (fill, target) => {
      const dataContext: any = target.dataItem?.dataContext;
      if (dataContext?.intersection) {
        const parts = dataContext?.category.split(" + ");
        const matchedObjects = data.filter(obj => parts.indexOf(obj.category) !== -1);
        const colors = matchedObjects.map(obj => obj.color);
        return LinePattern.new(root, {
          color: Color.fromString(colors[0]),
          rotation: 45,
          width: 200,
          height: 200,
          gap: 10
        }) || fill;
      }
    });
```

![Screenshot 2023-06-21 at 11 59 24](https://github.com/amcharts/amcharts5/assets/108460092/087de92b-7bc3-418d-97ea-8cde1a836e7a)

CodePan: https://codepen.io/maayan-layfer/pen/OJaXERm

**Comment by zeroin** [comment]
I am afraid I don't see any pattern code in your codepen, please provide an exact codepen with full code.

**Comment by maayanLayfer** [comment]
So sorry.. can you please have a look now @zeroin ?

**Comment by maayanLayfer** [comment]
Works perfectly, thanks a lot! :)
