### ISSUE TITLE
Is it possible to only 1 tooltip following pointer with multiple line series?

### ISSUE THREAD

**Issue by Y-m1** [amcharts/amcharts5#973]
**Question**

I'd like to show the 1 tooltip which follow the mouse pointer on multiple line series chart.
Like join up these two example. (I only use line series.)
https://codepen.io/team/amcharts/pen/ExXrXYo
https://www.amcharts.com/docs/v4/tutorials/context-sensitive-tooltip-that-follows-mouse-cursor/

Is it possible on amCharts5?

**Comment by zeroin** [comment]
Yes, it is. Here is an example:
https://codepen.io/team/amcharts/pen/ExXrXYo

I added tooltip to plotContainer of a chart to do this.

**Comment by Y-m1** [comment]
This one works fine for me, thank you!
