### ISSUE TITLE
How to handle if multiple data bullets on same coordinates.

### ISSUE THREAD

**Issue by hassan-anzer-ai** [amcharts/amcharts5#974]
Following problems, I'm facing right now and I need help resolving them on a priority
1. I have used amcharts5 with react and implemented bullets on coordinates in data there are many more objects which have the same coordinates but different information when I render only one coordinate shows because they are on the same latitude and longitude. 

I need to show them in a cluster when I click on cluster it should show me all points

**Comment by zeroin** [comment]
Unfortunately we do not support this out of the box. You can achieve this by analyzing your data, creating one map point for the same coordinates and then adding some custom behavior on click - it could be a tooltip which shows what's inside, or like your described, a bullet which splits on click - but all this is quite a custom programming, we do not have this functionality implemented.

**Comment by martynasma** [comment]
We also have this tutorial, which you may find useful:
https://www.amcharts.com/docs/v5/tutorials/solving-overlapping-bullets/
