### ISSUE TITLE
SSR Framework Inclusion

### ISSUE THREAD

**Issue by labriola** [amcharts/amcharts5#978]
Hello-

I have read and I am aware of the amcharts opinion of being included in SSR frameworks such as SvelteKit or Next.js and the discussions around the module type, etc. so I promise I am not doing this blindly.

While I understand it is not possible to actually use the SSR functions with amcharts, the ability to include amcharts in a bundle made by these framework/bundlers would be incredibly helpful. I used to have a pro amcharts license, but I had to migrate back to d3 as the limitations of amcharts with SSR framework became untenable for me, and using D3 works as expected.

That said, I forked amcharts and did a minimal set of changes that would allow the project to work with SvelteKit. (I know sveltekit is not on your list of supported frameworks) Again, this does not allow SSR but what it does allow is amcharts to be bundled into code deployed with SvelteKit and rendered client side. Most of it was adding file extension (if you are not aware of the full scale war on this topic between Node/TS and full stack devs, it's a great read)

Beyond the file extensions, I changed your build script to add the 'module' type to the package json in the 'es2015' dist. I recognize there are many reasons you may want to do this and I did not test the side effects in your other distributions, so I am not suggesting you just use my code, but I thought I would make a concrete effort to demonstrate what would be required to open amcharts to a community that currently cannot use your product.

Code here, I will likely keep working on it if I find additional issues.
https://github.com/labriola/amcharts5

Using the assets built with this distribution I can use imports:

`import { addLicense, Root, Container, percent, color, Rectangle, Line, Label } from "@amcharts/amcharts5";
`

from within modules bundled for SvelteKit and rendered on the client.

**Comment by Pauan** [comment]
Our docs show how to use amCharts with Next, it works with SSR:

https://www.amcharts.com/docs/v5/getting-started/integrations/next-js/

I haven't tested SvelteKit, but it should also work if you follow their directions:

https://kit.svelte.dev/faq#how-do-i-use-a-client-side-only-library-that-depends-on-document-or-window

This is the correct way to load browser-only modules in SvelteKit.

> Beyond the file extensions, I changed your build script to add the 'module' type to the package json in the 'es2015' dist. 

We tried that earlier, but it caused a lot of issues. It's something we want to do, but the ecosystem isn't ready yet.

**Comment by labriola** [comment]
Yes, I know about the the docs and that is what I was referencing in my original post but it is missing the larger point of how these frameworks work from a compilation/bundling perspective. That said, I completely understand your stance; I was offering this only because I believe there are people who would prefer to use this library (I am one of them) but are seeking other options because of the hurdles. 

There are a number of reasons the faq from sveltekit doesn't work well with amcharts but I won't bore you with those details. I am very familiar with the internals of most of these toolchains so I spent a few days trying to engineer a clever way of working with amcharts in the sveltekit ecosysstem before deciding to try the fork. In case someone else finds this in the future, the second most promising was to use custom loaders in node to overcome some of the file extension issues and do a runtime loader directly into vite. 

That said, I can continue to work with my fork (it works quite well) or work with d3 directly.

In any case, thanks for your time, I do appreciate you taking the time to respond

**Comment by Pauan** [comment]
> Yes, I know about the the docs and that is what I was referencing in my original post but it is missing the larger point of how these frameworks work from a compilation/bundling perspective.

Could you explain what point we are missing? Even if we made the changes you suggest (changing the file extensions and using `"type": "module"`) it will still break, because amCharts requires browser-only APIs like the DOM.

And so when Next tries to run the amCharts code in Node, it will error, because those APIs don't exist in Node.

Therefore, the official way to run browser-only code is to use the method described in our docs. That is the solution that [Next recommends](https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading#with-no-ssr). We have previously [discussed this with the developers of Next](https://github.com/vercel/next.js/issues/31518#issuecomment-993457117).

It's not a file extension issue, it's an SSR issue, and every framework has their own solution for handling browser-only code. So amCharts users must use the proper framework-specific way to load browser-only code. It's not something we can fix, it is up to the user to write their code properly.

**Comment by Pauan** [comment]
So I just tried creating a new SvelteKit project (by following [their directions](https://kit.svelte.dev/docs/creating-a-project)), and then I followed [their directions](https://kit.svelte.dev/faq#how-do-i-use-a-client-side-only-library-that-depends-on-document-or-window) for browser-only modules:

```ts
<div id="chartdiv" style="width: 100%; height: 500px"></div>

<script>
import { onMount } from "svelte";

onMount(async () => {
    const [am5, am5xy, { default: am5themes_Animated }] = await Promise.all([
        import("@amcharts/amcharts5"),
        import("@amcharts/amcharts5/xy"),
        import("@amcharts/amcharts5/themes/Animated"),
    ]);

    let root = am5.Root.new("chartdiv");

    root.setThemes([am5themes_Animated.new(root)]);

    let chart = root.container.children.push(
      am5xy.XYChart.new(root, {
        panY: false,
        layout: root.verticalLayout
      })
    );

    let data = [{
        category: "Research",
        value1: 1000,
        value2: 588
      }, {
        category: "Marketing",
        value1: 1200,
        value2: 1800
      }, {
        category: "Sales",
        value1: 850,
        value2: 1230
      }
    ];

    let yAxis = chart.yAxes.push(
      am5xy.ValueAxis.new(root, {
        renderer: am5xy.AxisRendererY.new(root, {})
      })
    );

    let xAxis = chart.xAxes.push(
      am5xy.CategoryAxis.new(root, {
        renderer: am5xy.AxisRendererX.new(root, {}),
        categoryField: "category"
      })
    );
    xAxis.data.setAll(data);

    let series1 = chart.series.push(
      am5xy.ColumnSeries.new(root, {
        name: "Series",
        xAxis: xAxis,
        yAxis: yAxis,
        valueYField: "value1",
        categoryXField: "category"
      })
    );
    series1.data.setAll(data);

    let series2 = chart.series.push(
      am5xy.ColumnSeries.new(root, {
        name: "Series",
        xAxis: xAxis,
        yAxis: yAxis,
        valueYField: "value2",
        categoryXField: "category"
      })
    );
    series2.data.setAll(data);

    let legend = chart.children.push(am5.Legend.new(root, {}));
    legend.data.setAll(chart.series.values);

    chart.set("cursor", am5xy.XYCursor.new(root, {}));

    return () => {
        root.dispose();
    };
});
</script>
```

This worked perfectly both in dev mode and build mode, without any errors, and the chart worked fine.

Like I said, it isn't a file extension issue, it's an SSR issue, and the solution is to follow your framework's guidelines on how to load browser-only modules.

**Comment by Pauan** [comment]
Also, an alternate solution for SvelteKit is to use the iso-import plugin:

https://github.com/bluwy/vite-plugin-iso-import

You just add it into your `vite.config.ts` file as usual.

Then you can just import amCharts as a client-only module:

```ts
import * as am5 from "@amcharts/amcharts5?client";
import * as am5xy from "@amcharts/amcharts5/xy?client";
import am5themes_Animated from "@amcharts/amcharts5/themes/Animated?client";
```

This also works fine.

**Comment by labriola** [comment]
Thank you so much for taking the time to respond and replicate; I really do appreciate it. 

I will take a look at the isomorphic import-plugin, that feels more natural for what we are trying to accomplish and is probably a very good way to handle the issue for now.

To answer your question from above, the aspect that I feel is most important is to allow the bundling and tree-shaking to still occur, if possible, while treating the amcharts library as a static import. Allowing SvelteKit (when I say that here I am simplifying of course as I really mean the chain from compilation through bundling) to determine how modules are composed and served is the goal. 

As you already saw, my fork was really just was allowing node.js to resolve the code paths correctly by including file extensions instead of relying upon the implicit browser resolution rules and declaring the items as module so that node would comprehend the import/export statements. While yes, in a way, we agree it is not a file extension issue, the tooling that is used for compilation and bundling runs in node and if node cannot traverse the module at build time, then it is _not_ an SSR issue.. we never get far enough to render anything... it is a build issue. And that build issue, based largely on choices between the TypeScript and NodeJs teams, is created by the lack of file extensions on imports. As noted, D3 also has browser dependencies, and for many reasons you already know is a great analog to the problem here, but it can be imported directly and used in the way I had indicated because of the inclusion of file extensions and declaration of a the package.json as a module.

So to reiterate, I appreciate your efforts but this wasn't just about following my framework's guidelines. I conceded in the beginning that there were multiple ways to make it work. The goal was to have an improved developer (and arguably production) experience that is more consistent with the normative approach to importing modules, removing any barriers that might prevent adoption. While it's 100% true that amcharts itself is not intended to run in node, I think it's important to see the increasingly mixed mode (server and client side) frameworks are gaining adoption, especially in the enterprise space where I feel amcharts has a natural fit. 

Again, than you for your time, I was not expecting this much effort on this issue and I sincerely appreciate it. I like this library, I just want to see as many people adopt it as possible.

**Comment by Pauan** [comment]
> To answer your question from above, the aspect that I feel is most important is to allow the bundling and tree-shaking to still occur, if possible, while treating the amcharts library as a static import.

That is exactly what the vite-plugin-iso-import does.

> While yes, in a way, we agree it is not a file extension issue, the tooling that is used for compilation and bundling runs in node and if node cannot traverse the module at build time, then it is not an SSR issue..

It is absolutely an SSR issue. If you disable SSR then the code is not run in Node at all, which means you do not get any errors.

The reason why the errors are happening is because SvelteKit is trying to run the code in Node (that's what SSR means).

But because the amCharts code is not compatible with Node, you get errors. Using `?client` causes the code to not run in Node, which fixes the errors.

> And that build issue, based largely on choices between the TypeScript and NodeJs teams, is created by the lack of file extensions on imports.

Even if you add file extensions to amCharts, you will still get errors:

```svelte
<script>
import * as am5 from "@amcharts/amcharts5";

// This will always error
let root = am5.Root.new("chartdiv");
</script>
```

That's because during SSR, the code is being run in Node. amCharts cannot run in Node, and so you will *always* get errors.

It just so happens that SvelteKit removes `onMount` during SSR. So if you put your code inside of `onMount` then it will work fine, because the code is never run in Node.

This is an SSR issue, and the solution is to tell SvelteKit to not run your code in Node.

> The goal was to have an improved developer (and arguably production) experience that is more consistent with the normative approach to importing modules, removing any barriers that might prevent adoption.

Yes, I also think that it is unfortunate that most frameworks make it very difficult and unintuitive to run browser-only code. But that is an issue with the frameworks that we cannot fix. The best we can do is provide documentation that shows users how to run their amCharts code only in the browser.

**Comment by labriola** [comment]
Okay, well we disagree.  

And, thanks, I am aware of what SSR means, how node modules resolution works, and I can provide multiple replication cases where, with SSR disabled, the same issue will occur. 

Even more fun, I can take a project that does work properly now (like for example D3), and ensure it fails in the same way by changing the two things I mentioned..... all this without changing it's dependency on the DOM or any other code. Lastly, my fork, which I provided at the beginning of this 'conversation' makes precisely two changes (file extensions and package.json) and demonstrates the ability to import it into the contexts where it is only used in the browser.... 

However, we have clearly reached the useful end of this conversation and I will happily close the issue. Thanks for the help you provided and I really did appreciate your initial responses.
