### ISSUE TITLE
Columns minimum width

### ISSUE THREAD

**Issue by roshaxo** [amcharts/amcharts5#979]
Hello!
I want to set minimum width for the columns.
I have tried 2 approaches:
1. Usage of `series.columns.template.set("minWidth", 20)`, but it doesn't work.
2. Usage of `series.columns.template.onPrivate("width", callback)` - it works, but when proportion between parts is too big, small ones are stacked on top of each other, not one behind the other.

Codepen: https://codepen.io/flexinclique/pen/NWEddPa

If there is a way to fix it?
Thank you in advance!

**Comment by roshaxo** [comment]
@zeroin 
Not sure, that I understand how to set this minimum value. Could you explain in more detail, please?

**Comment by zeroin** [comment]
There is no build in way to do that. You just need to modify your data. Then you can add some "displayValue" field in your data and show this displayValue in a tooltip. But in general, this is very wrong from dataviz perspective.

**Comment by roshaxo** [comment]
@zeroin 
Thank you! Will try to play with it
