### ISSUE TITLE
Line chart xAxis render

### ISSUE THREAD

**Issue by RavidAtiasAxonius** [amcharts/amcharts5#980]
Hi
Looking for a way to hide only the left xAxis grid template
Is there a way to do so?
![Screenshot 2023-06-26 at 16 09 50](https://github.com/amcharts/amcharts5/assets/111275139/6ea9d4d6-04f8-4363-bbaa-5d7b2cf56507)

**Comment by RavidAtiasAxonius** [comment]
This is not working:
setting `yRenderer.grid.template.set('visible', false)` remove all horizontal grid lines
![Screenshot 2023-06-27 at 9 55 40](https://github.com/amcharts/amcharts5/assets/111275139/49958a1d-d332-4096-8386-543947497fba)

setting `xRenderer.grid.template.set('visible', false)` remove all vertical grid lines

![Screenshot 2023-06-27 at 9 56 50](https://github.com/amcharts/amcharts5/assets/111275139/984f226c-7ccb-4a5b-8fa2-a70ce86ea75a)

While I want to remove only the outer vertical grid line

**Comment by zeroin** [comment]
This is not a grid but axis itself, it could be hidden by setting `strokeOpacity:0` on the AxisRendererX or AxisRendererY itself.

**Comment by RavidAtiasAxonius** [comment]
@zeroin 
setting
`  yRenderer.set("visible", false);
  yRenderer.set("opacity", 0);
  yRenderer.set("fillOpacity", 0);
  yRenderer.set("strokeOpacity", 0);
  xRenderer.set("fillOpacity", 0);
  xRenderer.set("opacity", 0);
  xRenderer.set("strokeOpacity", 0);
  yRenderer.setAll("visible", false);
  yRenderer.setAll("opacity", 0);
  yRenderer.setAll("fillOpacity", 0);
  yRenderer.setAll("strokeOpacity", 0);
  xRenderer.setAll("fillOpacity", 0);
  xRenderer.setAll("opacity", 0);
  xRenderer.setAll("strokeOpacity", 0);`
still make no change :(
![Screenshot 2023-06-27 at 10 45 37](https://github.com/amcharts/amcharts5/assets/111275139/7cf359f0-69f0-4d11-8c29-156841481bb0)

**Comment by zeroin** [comment]
If you could create a codepen, I could check it and modify.

**Comment by RavidAtiasAxonius** [comment]
https://codepen.io/isItMeYouLookingFor/pen/BaGpMJo
@zeroin  Thanks!

**Comment by zeroin** [comment]
So the strokeOpacity:0 set on AxisRendererY will remove the axis line (btw, you were using wrong syntax with setAll, it should be:

`yRenderer.setAll({"visible":false});`

And then, if you want to hide first grid only but keep the others, you can do it with an adapter:

```
  xRenderer.grid.template.adapters.add("strokeOpacity", function(strokeOpacity, target){
    if(target.x() == 0){
      return 0
    }
    return strokeOpacity
  });
```
x coordinate of first grid will always be 0.

https://codepen.io/team/amcharts/pen/LYXxabP/40916b5df44bbf95a5da6bec999c0d31
