### ISSUE TITLE
how to make the x axis scroll to show the axis range

### ISSUE THREAD

**Issue by evehaxor** [amcharts/amcharts5#981]
Hello,

I'm facing an issue with setting the axis range on the stock chart. When the values of the axis range exceed the values of the chart, it doesn't appear. Is it possible to make the x-axis scroll to the value of the axis range?

Here's the link to the code: [codepen.io/evehaxor/pen/VwVPOxN](https://codepen.io/evehaxor/pen/VwVPOxN)

When I change line 217 to:

```javascript
var range = dateAxis.createAxisRange(
  dateAxis.makeDataItem({
    value: data[data.length - 1].timestamp + ((60 * 1000) * 3),
    endValue: data[data.length - 1].timestamp + ((60 * 1000) * 4)
  })
);
```

The axis range is no longer visible. I have tried adjusting the `maxDeviation`, but the distance of the axis range could be much greater than the values of `data`. 

I would greatly appreciate it if someone could help me find a solution to this issue. Thank you in advance!

**Comment by zeroin** [comment]
To solve this, you should create regular DateAxis instead of GaplessDateAxis and set:

`range.set("affectsMinMax", true);`

for the axis range data item. I am afraid we do not have a possibility to do the same with GaplessDateAxis, you should add a data item to your series if you need to use it.

**Comment by evehaxor** [comment]
Hello @zeroin,

Thank you so much for your response! Your solution resolved my issue. I truly appreciate your help. Have a great day!
