### ISSUE TITLE
How can I enable wheel zoom on the candlestick chart to zoom in on the candle where the cursor is positioned?

### ISSUE THREAD

**Issue by evehaxor** [amcharts/amcharts5#982]
Hello,

I'm currently working with the example provided at https://www.amcharts.com/demos/candlestick-chart/ and I noticed that when zooming, it zooms in on the candle where the cursor is positioned. However, in the stock chart example at https://www.amcharts.com/demos/stock-chart/, the zoom is always performed on the first candle on the right corner.

I would like to use the stock chart but have the zoom functionality work on the candle where the cursor is positioned. Can anyone guide me on how to achieve this? Your help would be greatly appreciated.

**Comment by martynasma** [comment]
StockChart has wheel-zoom "glued" to the end enabled by default, as it's the most common practice in financial charts.

You can change that using `wheelZoomPositionX` setting on the panel. More info:
https://www.amcharts.com/docs/v5/charts/xy-chart/zoom-and-pan/#Wheel_zoom_center
