### ISSUE TITLE
Line chart padding

### ISSUE THREAD

**Issue by RavidAtiasAxonius** [amcharts/amcharts5#983]
Hello
Using XYchart and Line series I set :
  const root = Root.new(id);
  root.setThemes([am5themes_Animated.new(root)]);
  const chart = root.container.children.push(
    XYChart.new(root, {
      layout: root.verticalLayout,
      paddingLeft: 0,
      paddingRight: 0,
    })
  );

But still, I get the padding (marked in red)

![Screenshot 2023-06-29 at 10 52 02](https://github.com/amcharts/amcharts5/assets/111275139/b4327792-b756-4254-b0aa-a3d87df21df7)

What can I do?
Thankx

**Comment by zeroin** [comment]
I guess you should also set paddingLeft:0 for the axis label template.

**Comment by RavidAtiasAxonius** [comment]
Thanks!
