### ISSUE TITLE
Increasing bullet click area

### ISSUE THREAD

**Issue by RavidAtiasAxonius** [amcharts/amcharts5#984]
Hey
I have the following configuration for XYchart with Line series:

    const bulletTemplate = Template.new(root, {});

    bulletTemplate.events.on("click", e => {
      onClick(target);
    });
    bulletTemplate.events.on('pointerover', ({target}) => {
      document.body.style.cursor = "pointer";
    });
    bulletTemplate.events.on('pointerout', () => {
      tooltipDataSetter(null);
      document.body.style.cursor = "default";
    });

    series.bullets.push(() => {
      return Bullet.new(root, {
        sprite: Circle.new(root, {
          strokeWidth: 3,
          stroke: series.get("stroke"),
          radius: 1.5,
          fill: root.interfaceColors.get("background"),
        }, bulletTemplate)
      });
    });

I want to increase the bullet's area for the click event interaction, is there a way to do so?
Thanks

**Comment by zeroin** [comment]
Sure - use Container as a main sprite of a bullet and then add two circles to it - one like in your code and another, bigger with opacity set to 0.
