### ISSUE TITLE
polygonSeries.zoomToGeoPoint() is not a function

### ISSUE THREAD

**Issue by szy-kenn** [amcharts/amcharts5#985]
**Why is polygonSeries.zoomToGeoPoint() not identified as a function?**

I have not made any modifications to the demo code, but using `zoomToGeoPoint()` is giving me an error. I tried using `zoomToDataItem` and this works perfectly fine, so I don't really know why this is happening. I tried it inside the ready() function, and I am certain I called this after the polygonSeries initialization. 

- am5Charts Map
- OperaGX
- Vanilla JS

**Comment by xorspark** [comment]
It doesn't work on the series because it is a MapChart method, so it needs to be called on the chart/map itself: https://www.amcharts.com/docs/v5/reference/mapchart/#zoomToGeoPoint_method. 

```
chart.zoomToGeoPoint({ longitude: 10, latitude: 52 }, 3.5);
```
