### ISSUE TITLE
How align legend with start of plotContainer?

### ISSUE THREAD

**Issue by Y-m1** [amcharts/amcharts5#986]
**Question**

I want to set the legends start position to start of plotContainer.
I tried to add the legends to plotContainer but it move to inside the chart.
How can I do it?

**Comment by Y-m1** [comment]
![Screenshot 2023-06-30 at 17 27 18](https://github.com/amcharts/amcharts5/assets/137384148/d470babe-d1b3-48a7-874d-5f852b7a8f99)

I mean I'd like to set the legends start position to set this black line.

**Comment by martynasma** [comment]
You'd probably need to set `paddingLeft` of the legend to whatever width the left axis is:

```JavaScript
var legend = chart.children.push(am5.Legend.new(root, {
  centerX: 0,
  x: 0
}));

yAxis.events.on("boundschanged", function(ev) {
  legend.set("dx", yAxis.width() + chart.get("paddingLeft", 0));
});
```

https://codepen.io/team/amcharts/pen/zYMwZmr?editors=0010

**Comment by Y-m1** [comment]
it works fine, thanks!
