### ISSUE TITLE
Map interaction does not work in Brave with Block fingerprinting on

### ISSUE THREAD

**Issue by omusil24** [amcharts/amcharts5#987]
Map interaction does not work in Brave browser when the "Block fingerprinting" feature of the browser is turned on (set to Standard or Strict).

Here's a minimal example:
https://ds3x8c.csb.app/
https://codesandbox.io/s/nervous-glade-ds3x8c?file=/src/App.tsx

**Environment**
 - amCharts version: 5.3.8
 - Brave version: v1.52.129

**Comment by omusil24** [comment]
Also found a possibly related issue here:
https://stackoverflow.com/questions/76166878/hovering-effect-not-working-for-amcharts5-when-fingerprint-is-enabled-in-brave-b

**Comment by martynasma** [comment]
There's nothing we can do here, I'm afraid. More details: https://github.com/amcharts/amcharts5/issues/908#issuecomment-1534846065
