### ISSUE TITLE
Get/save legend selection in local storage

### ISSUE THREAD

**Issue by skeuomorphismis** [amcharts/amcharts5#988]
**How do I save legend selection in local storage?**

I need to get the series name.

**Comment by skeuomorphismis** [comment]
Should I use the `uid` or.. 

```
legend.itemContainers.template.events.on('pointerover', (e) => {
  console.log(e?.target?.dataItem);
});
```

This is what I get:
<img width="921" alt="image" src="https://github.com/amcharts/amcharts5/assets/138443198/ff427b15-f4e4-4ed6-bc0e-7e75661f9727">

**Comment by martynasma** [comment]
You can access series name by `ev.target.dataItem.dataContext.get("name")`.

**Comment by skeuomorphismis** [comment]
Thank you @martynasma, that's right. Is this the right way of doing this or should I rather check whether series are hidden or shown (in which case what method would I use) on page load.

**Comment by markGotech** [comment]
How can i take value of legend? I mean disable or enabled?

**Comment by martynasma** [comment]
> How can i take value of legend? I mean disable or enabled?

```
ev.target.dataItem.dataContext.isHidden()
```

**Comment by markGotech** [comment]
thank you)

**Comment by markGotech** [comment]
> > How can i take value of legend? I mean disable or enabled?
> 
> ```
> ev.target.dataItem.dataContext.isHidden()
> ```

Could you explain me, i understood how to show and hide line, but it only hidden, but chart doesn't recalculated zoom, and size of another line. How can i managed it?

**Comment by markGotech** [comment]
https://github.com/amcharts/amcharts5/assets/128690082/2f4f6563-cbc5-48cd-ad10-155cbd42e0ad

**Comment by martynasma** [comment]
Do you mean vertical zoom?

**Comment by markGotech** [comment]
> Do you mean vertical zoom?

Yes
