### ISSUE TITLE
Scatterplot Tooltip Positioning

### ISSUE THREAD

**Issue by sassomedia** [amcharts/amcharts5#99]
How would I be able to get the tooltip to just point to a certain point hovered over as opposed to it jumping from point to point when the mouse is moved? This is especially problematic when two points have the same x or y axis value. The tooltip will only show one point's value. Example in this [pen](https://codepen.io/sassomedia/pen/mdMZQGb?editors=0010).

I figured that `maxTooltipDistance` would be for this but I guess that only applies for multiple series. A scatterplot only has one series. Is there another setting for this behavior?

**Comment by martynasma** [comment]
Maybe remove series tooltip altogether, and just set `tooltipText` directly on bullet's circle element?

**Comment by sassomedia** [comment]
Yeah, I did have that initially but couldn't get the `dataItem` from it. Just tried this again and apparently I had the event listener on the tooltip instead of on the circle. All working now, thanks!
