### ISSUE TITLE
Custom Drawing Tool

### ISSUE THREAD

**Issue by workingbuddy10** [amcharts/amcharts5#990]
I want to customize the drawing tool, like showed in the image. I have simply used the below code rendering the drawing tools and other features.
How can I access and handle tools so that I can achieve the desired results.

```
      var toolbar = am5stock.StockToolbar.new(root, {
        container: document.getElementById("chartcontrols"),
        stockChart: stockChart,
        controls: [
          am5stock.DrawingControl.new(root, {
            stockChart: stockChart,
          }),
          am5stock.IndicatorControl.new(root, {
            stockChart: stockChart,
            legend: valueLegend,
          }),
          am5stock.DateRangeSelector.new(root, {
            stockChart: stockChart,
          }),
          am5stock.PeriodSelector.new(root, {
            stockChart: stockChart,
          }),
          am5stock.ResetControl.new(root, {
            stockChart: stockChart,
          }),
          am5stock.SettingsControl.new(root, {
            stockChart: stockChart,
          }),
        ],
      });
```

Desired result:

![image](https://github.com/amcharts/amcharts5/assets/137867461/6d2fdde1-6d33-4489-9ba9-18b6edd8b230)

**Comment by martynasma** [comment]
Do you mean you don't want the text labels to show in the Tool dropdown?

Or you need this toolbar to always be visible when in drawing mode?

**Comment by workingbuddy10** [comment]
I want to place individual tools (shown in the image) in the left side of the chart, like right its showing inside a button and when we click the then further menu is opening.

I just want to place each drawing in the left side and right side the chart gets plotted, so if I want to use any drawing tool then just click on the icon and it should get active. 
Just like the drawing tools which are presented in Tradingview.com .

**Comment by martynasma** [comment]
I'm afraid there's currently no way to enable layout like that :(

**Comment by workingbuddy10** [comment]
It has been used in one of the private accessed website, and I have also attached the image in this which shows the alignment and am5charts has been used for the drawing tools and charts.

**Comment by martynasma** [comment]
If that is true, they must've implemented something custom. I'm afraid I have no knowledge of that specific user implementation.
