### ISSUE TITLE
Clickable links in tooltips in Amcharts 5

### ISSUE THREAD

**Issue by kekikcilerakin** [amcharts/amcharts5#991]
How can add clickable links in tooltips in Amcharts 5?
It works in v4 but can't get it to work in v5.

Here's a working example in v4:
https://codepen.io/team/amcharts/pen/YMJZqW

**Comment by martynasma** [comment]
Please refer to this doc:
https://www.amcharts.com/docs/v5/concepts/common-elements/html-content/#Interactive_elements

**Comment by kekikcilerakin** [comment]
> 

I did. And when I added a link to the tooltip it opens the link wherever I click. I want it to open only when I click on the link.

**Comment by martynasma** [comment]
Do you have an example you can post on CodePen?

**Comment by kekikcilerakin** [comment]
> 

Tried this also. But like this: 
`var polygonSeries = chart.series.push(am5map.MapPolygonSeries.new(root, {
        geoJSON: am5geodata_worldLow,
        exclude: ["AQ"],
        tooltip: am5.Tooltip.new(root, {
          labelHTML: '<a href="https://example.com">{name}</a>',
          keepTargetHover: true
        })
      }));
      
      polygonSeries.get("tooltip").label.set("interactive", true);`

but I removed this part:
`polygonSeries.mapPolygons.template.setAll({
        tooltipHTML: '<a href="https://example.com">{name}</a>',
        toggleKey: "active",
        keepTargetHover: true,
        interactive: true
      });`

that's why it didnt work then... Anyways thank you.
