### ISSUE TITLE
The stock chart experiences choppy horizontal scrolling when handling a large amount of data

### ISSUE THREAD

**Issue by kubickaoliver** [amcharts/amcharts5#993]
**Bug description**

If there is a large amount of data in the StockChart (more than 4000 candles), horizontal scrolling is choppy. Is there an option to specify if the chart should be updated while dragging/resizing the scrollbar or only at the moment when the user releases the mouse button?

**Development environment:**

 - amCharts version: 5.4.0
 - Browser and its version: Firefox Browser 102.12.0esr (64-bit)
 - Related frameworks and their versions: React 11.10.5, TypeScript 4.8.4

**Comment by kubickaoliver** [comment]
![issue](https://github.com/amcharts/amcharts5/assets/45532792/eda65dec-0c8e-4877-9965-922ea20cb2e7)

**Comment by kubickaoliver** [comment]
![ezgif com-video-to-gif 4](https://github.com/amcharts/amcharts5/assets/45532792/e2530bdd-30e3-4317-af00-f7e89cbbb2f6)

**Comment by kubickaoliver** [comment]
> > Is there an option to specify if the chart should be updated while dragging/resizing the scrollbar or only at the moment when the user releases the mouse button?
> 
> There's no such option, I'm afraid.
> 
> However, displaying 4000 candles sounds like a bad idea to me. Why not enable [data point grouping](https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#dynamic-data-item-grouping)?

**Comment by kubickaoliver** [comment]
> > Is there an option to specify if the chart should be updated while dragging/resizing the scrollbar or only at the moment when the user releases the mouse button?
> 
> There's no such option, I'm afraid.
> 
> However, displaying 4000 candles sounds like a bad idea to me. Why not enable [data point grouping](https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#dynamic-data-item-grouping)?

I tried it, but when I zoomed in on the stock chart to display hourly candles, it became choppy again because it showed the same number of candles.

**Comment by martynasma** [comment]
The whole point of data grouping is to not show a lot of data points at the same time. If it's showing 4k data points when you zoom in, it means there's something off with the chart configuration. Would you be able to share your data and code on CodePen?

**Comment by kubickaoliver** [comment]
Data grouping works great. But let's say we have 4000 data for a candlestick (hourly interval). If the chart does not show hourly candles, everything goes like clockwork. If I zoom in on the chart so that the hourly candles start to appear, the problem occurs again as 4000 candles are displayed on the chart. Couldn't this be solved by some data virtualization so that only the data that is displayed on the chart is rendered?

**Comment by martynasma** [comment]
That's no how data grouping works.

If you have 4000 hourly data points, it means you have like 166 days worth of data.

When chart is fully zoomed out, it will show a candle per day - 166 candles. All good.

If you zoom into chart, say 30 days, the chart will still be in days (unless you configure it otherwise).

If you continue zooming in, the chart will switch to hours at some point, but at this point you will have a time span of 8 days or so, so 8 * 24 = 192. Only 192 hourly candles. Not 4000.

Hope that makes sense.

That's the default behavior anyway. I deliberately asked for your code, to try and check whether you have that default behavior changed somehow.

**Comment by kubickaoliver** [comment]
Data grouping works for me exactly as you wrote, the only problem is that the scrollbar does not move smoothly with hourly interval data. But that is probably due to the large amount of data. Could this be solved somehow?

**Comment by kubickaoliver** [comment]
Here is code: https://codepen.io/Tim-dvadsatsedem/pen/XWyzaXz

**Comment by martynasma** [comment]
Yes, the scrollbar might be issue. You should probably enable grouping for the scrollbar, too.

The following doc shows how:
https://www.amcharts.com/docs/v5/charts/xy-chart/scrollbars/#Scrollbar_with_chart_preview

**Comment by kubickaoliver** [comment]
I enabled grouping in the scrollbar but it didn't help. I noticed the following bug that may be causing my problem. When I move the stockChart horizontally with data grouping enabled, the data is automatically zoomed in certain parts as you can see in the GIF.

![ezgif com-video-to-gif 7](https://github.com/amcharts/amcharts5/assets/45532792/c1760591-ed8a-4a48-aa94-687084819fdf)

**Comment by martynasma** [comment]
Would you be able to post your current chart setup in a runnable form? E.g. on CondeSandbox. That behavior from your screengrab looks weird.
