### ISSUE TITLE
Whenever I refresh the chart its shaking up down

### ISSUE THREAD

**Issue by padfoot044** [amcharts/amcharts5#994]
Whenever I refresh the chart its shaking up and down and change its y-axis label
 - amCharts 5
 - Chorme Version 114.0.5735.199 
 - Angular 12

![as](https://github.com/amcharts/amcharts5/assets/55396959/ca89cf8d-7b98-4c06-9506-5e4fdb70db77)

As you can see this attachment, we have like 7 charts in same page but with different Id and root
in some charts there are less data and some more, I don't know why its look like this

**Additional context**

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by padfoot044** [comment]
> 

Okay, I will upload code on that and let you know soon
