### ISSUE TITLE
Line chart Xaxis

### ISSUE THREAD

**Issue by RavidAtiasAxonius** [amcharts/amcharts5#995]
Hi,
I'm having line chart with DateAxis xaxis.
Setting:
xAxis.get("dateFormats")["day"] ='MMM dd, YYYY';
works on all labels except one.
How can I fix it?
![Screenshot 2023-07-06 at 13 35 40](https://github.com/amcharts/amcharts5/assets/111275139/611c3ac3-660f-4f3a-938f-ccf05fcccecc)

When more thing is that I what the most left label to be inside the canvas
How can I do it?

![Screenshot 2023-07-06 at 13 36 17](https://github.com/amcharts/amcharts5/assets/111275139/1c4f3e81-1ea5-40d5-84ad-2e9deb6615bb)

This is a codepen reproducing the issues
https://codepen.io/isItMeYouLookingFor/pen/BaGpMJo

Thanks!

**Comment by xorspark** [comment]
> xAxis.get("dateFormats")["day"] ='MMM dd, YYYY';
> works on all labels except one.

The other label is controlled by the `periodChangeDateFormats` list as documented [here](https://www.amcharts.com/docs/v5/charts/xy-chart/axes/date-axis/#period-change-date-formats). You can either apply the same format on that list's `day` key like in `dateFormats` or you can set `markUnitChange` to false on the axis to not use `periodChangeDateFormats` at all.

> When more thing is that I what the most left label to be inside the canvas

You can add some padding on the chart to make it fit: `chart.set('paddingLeft', 30)`

**Comment by xorspark** [comment]
Another alternative is to use the `location`/`multiLocation` properties, though it will impact their location on the grid.

https://www.amcharts.com/docs/v5/charts/xy-chart/axes/#location-of-axis-elements

Not much else you can do outside of that.
