### ISSUE TITLE
"Moving categories up" for amcharts5

### ISSUE THREAD

**Issue by rogeraraujo90** [amcharts/amcharts5#996]
**Question**

I would like to do the same thing as detailed in the section "[Moving categories up](https://www.amcharts.com/docs/v4/tutorials/column-labels-as-categories/#Moving_categories_up)" in the v4 docs but using amcharts5. I couldn't find anything related in the docs and the code from v4 doesn't work (it actually breaks the app).

How can I move the categories to the top of the bars using amcharts5?

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
There you go:
https://www.amcharts.com/docs/v5/tutorials/column-labels-as-categories/

**Comment by rogeraraujo90** [comment]
Thanks! Closing the question! 🚀
