### ISSUE TITLE
Is (Butterfly Chart) this Chart is available in AmCharts5?

### ISSUE THREAD

**Issue by mukeshbadgujar** [amcharts/amcharts5#998]
I have searched and check the below type of chart in amcharts demo but i cant find it, can you let me know is this available, 
or if not then give me reference similar like this chart

![image](https://github.com/amcharts/amcharts5/assets/32473209/f3620a40-10f5-45fc-bbba-7d6cfd81b45a)

Reference Website: https://trendlyne.com/equity/1355/TATACHEM/tata-chemicals-ltd/
(scroll down to EMA & SMA)

if nothing is there (give me any chart that can be possible to implement above functionality)

**Comment by mukeshbadgujar** [comment]
i think it called as butterfly chart... but let me know.

**Comment by martynasma** [comment]
I don't think it's called a butterfly chart. [This is](https://www.amcharts.com/demos/stacked-bar-chart-with-negative-values/).

The bars on that chart, are those just stylized gradiented background, or they are related to some actual data?

**Comment by mukeshbadgujar** [comment]
They are related to actual data based on

Exponential Moving Average (EMA) is similar to Simple Moving Average (SMA), measuring trend direction over a period of time. However, whereas SMA simply calculates an average of price data, EMA applies more weight to data that is more current.

And

A bullish signal is generated when the shorter moving average crosses above the longer moving average. A bearish signal is generated when the shorter moving average crosses below the longer moving average. These events are based on simple moving averages.

Based on this the pointer is moving across.

But in your reference it is vertical with multiple columns.

But in this case the background chart is just static and with colors, and the pointer is moving based on values.

**Comment by martynasma** [comment]
Do you have a sample data you'd feed in such chart?

I think this can easily be recreated with a simple XYChart and floating columns.

**Comment by mukeshbadgujar** [comment]
> Do you have a sample data you'd feed in such chart?
> 
> I think this can easily be recreated with a simple XYChart and floating columns.

The data is visible in the reference site which i given, the green and red color data is there based on that the pointer is plotted.

**Comment by martynasma** [comment]
Yeah, what about the data for the bars?

**Comment by mukeshbadgujar** [comment]
i think they just static.

**Comment by martynasma** [comment]
OK, so actually, that chart is only a bullet + thin floating column at some x/y coordinate.

**Comment by martynasma** [comment]
Yes: an `XYChart`:

1) With a static background image.
2) `ColumnSeries` with a single data item and bullet, placed ad required X and Y coordinates.
3) All axes are hidden.

I don't have an example for such chart, but the above description should give you hinds on where to start.
