### ISSUE TITLE
Visual Editor Compatible With AM Charts 5

### ISSUE THREAD

**Issue by ng-druid** [amcharts/amcharts5#999]
We have developed a plugin for our climate aware CMS that adds charting capabilities using JSON charts.

https://github.com/rollthecloudinc/solid-amcharts5

We would like know whether a visual editor compatible with AM Charts 5 is in development. If so what is the timeline on a release. Would be interested in integrating the visual editor into our climate aware CMS as well.

https://github.com/rollthecloudinc/spearhead

Thanks

**Comment by martynasma** [comment]
Thanks for the link. I'm afraid there's currently no visual editor in development for amCharts 5.
